### ISSUE TITLE
`kubectl gs login`: Add environment variable as equivalent to set `--keep-context`

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1011]
A user has requested "global" configurability for the `--keep-context=true` behaviour of `kubectl gs login`.

Let's add an environment variable `KUBECTL_GS_LOGIN_KEEP_CONTEXT` that will set the default for that flag.

The `--keep-context` flag should be able to override the environment variable.

## Examples

1. With `KUBECTL_GS_LOGIN_KEEP_CONTEXT` set to `true`, and `--keep-context` not set, `kubectl gs login` will not modify the current kubeconfig context.
2. With `KUBECTL_GS_LOGIN_KEEP_CONTEXT` set to `false`, and `--keep-context` not set, `kubectl gs login` will modify the current kubeconfig context.
3. With `KUBECTL_GS_LOGIN_KEEP_CONTEXT` set to `false`, and `--keep-context=true`, `kubectl gs login` will not modify the current kubeconfig context.
4. With `KUBECTL_GS_LOGIN_KEEP_CONTEXT` set to some other string than `false` or `true`, `kuebctl gs` will ignore the variable.

## Tasks

- [ ] kubectl-gs implementation
- [ ] Documentation change

**Comment by weatherhog** [comment]
@gawertm we think this is in bigmac
