### ISSUE TITLE
Document coding style guidelines and best practices for JS projects

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1013]
Our [`fmt`](https://github.com/giantswarm/fmt) repo serves as a reference for coding styles and best practices. The JavaScript section is very outdated (last update was 2 years ago), and does not cover all the current use cases in our JS/TS/React projects (mainly `happa`). This makes it difficult for people new to these projects to learn what guidelines we follow, and what the best practices are.

I think updating the JavaScript section (and keeping it updated) is an important step towards enabling more people to work independently on the web UI.

**Comment by weatherhog** [comment]
closing
