### ISSUE TITLE
When cluster creation fails, the web UI should allow retrying

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1014]
When the attempt to create a cluster fails (e. g. because of a timeout), the user is redirected to a different page and we show a flash message.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/273727/162141326-315e465b-7a54-4eab-a6ad-c46e792ee274.png">

This means that in order to retry creation, the user has navigate to the form again and re-enter all data.

Ideally we would keep the form with all input open in this case and allow submission once more.

The same should apply for node pools.

**Comment by PrashantR31** [comment]
Hi @marians, 

I have 2 suggestions:
1. Changing cluster creation to 20 s instead
2. Then add log output (if possible) to see where the time is being consumed for cluster creation for it to exceed 10 s ?

What do you think?

**Comment by marians** [comment]
Waiting for 10 seconds for the result of a form submission is already far above our general goal. Normally the API should respond in less than a second and in most cases it does. Increasing the timeout to 20 sec will likely only result in longer wait times for the end user before the transaction fails.

In the case of a timeout we don't get any response from the API, so we have no information regarding why the request took so long to process.

UX wise the best I can think of is to offer a re-try as I wrote above:

> Ideally we would keep the form with all input open in this case and allow submission once more.

Along with this we should show a message saying that the request timed out and that re-trying might work. If that doesn't help, users should reach out to our support.

Also we should check whether we can send a specific error to Sentry to record details on when and where this happens.

**Comment by PrashantR31** [comment]
To check: Is it a random or happens always because some valid reason.
