### ISSUE TITLE
Allow Org admin to have permission to read secret for the `default` namespace

### ISSUE THREAD

**Issue by ghost** [giantswarm/roadmap#1020]
From (https://gigantic.slack.com/archives/C02EVLE9W/p1649250753651099)

- Why the default namespace?
- Should we provide a ClusterRole for this?

**Comment by anvddriesch** [comment]
@LolloneS is this still relevant for ista?

**Comment by LolloneS** [comment]
We migrated to org- namespaces for those credentials so I’d say we can close this. Access is also possible via the automation service account
