### ISSUE TITLE
CAPG cluster deletion

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1021]
## Story

_*-As a cluster admin, I want to delete a CAPG clusters in order to cleanup test clusters, GCP resources and to reduce infrastructure costs.*_

## Background

The deletion of CAPG clusters fails.

**Comment by mnitchev** [comment]
After deleting a few clusters recently we've noticed that these resources get leaked in GCP:
* Instance Groups
* Load Balancer (references Instance Groups)
* External IP Address (used by Load Balancer)
* Health Checks (used by Load Balancer)
* Firewalls (this one has only leaked for some clusters)

I've also seen Routes and VPC Networks get leaked, however this hasn't happened recently.

**Comment by AverageMarcus** [comment]
Fixed merged upstream and due to be included in release `v1.1.0`
