### ISSUE TITLE
Guide for custom admission controllers uses outdated API version

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1023]
Our page https://docs.giantswarm.io/advanced/custom-admission-controller/ uses the outdated API version `admissionregistration.k8s.io/v1beta1` and should be updated for `admissionregistration.k8s.io/v1`.

See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122 for reference

The article is currently assigned to team Rocket.

**Comment by pipo02mix** [comment]
This is done and published
