### ISSUE TITLE
[Spec] Namespaced catalogs

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#104]
Tue, Mar 17, '20 Update

**User story:** As a user within a shared Control Plane, I want to create app catalogs that are only available to my org and cannot be seen or used by users in other orgs of the same Control Plane, so that I can share a Control Plane with different companies/divisions/teams that need to be separated without sharing my internal apps.

---

**Context**

Currently, AppCatalog CRs are cluster scoped.
In the future, we would like to make the GiantSwarm App Catalog available to other (non-GS) users.

This means we have to give the customers access to a control-plane. To limit the number of Control Planes, we'll have to use multi-tenant CPs. This means we need AppCatalog to be namespace scoped. As a result:
- in our current setup: different teams of the same customer can use different AppCatalogs
- in the future: different customers of GS App Catalog system can coexist in the same Control Plane.

**Comment by corest** [comment]
Spec is ready
