### ISSUE TITLE
Schema to express which permissions are required for a use case

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1049]
Towards https://github.com/giantswarm/roadmap/issues/808

The goal, requirements

- Specify the Kubernetes RBAC permissions needed to fulfil certain use cases, in a machine-readable way
- Use cases can be grouped
- Use cases have a name
- Use cases can carry a description
- Permissions are expressed with these details:
  - group
  - resource type
  - verbs
- Cluster scope / in a namespace

**Comment by marians** [comment]
Looking good so far.

The `namespace: ''` part is a bit too implicit for my taste. I think we need a solution here that is both more explicit / self-explanatory and more fail-safe. Also simply omitting the `namespace` key to express "cluster scope" is very implicit.

How about something like this?

```yaml
scope:
  cluster: true
```

```yaml
scope:
  namespaces:
    - default
```

```yaml
scope:
  namespaces:
    - "*"
```

**Comment by marians** [comment]
One more thing I'd like to bring in before we implement this: Should we rename `group` to `category` to avoid any confusion with the RBAC API group or user group concept?

**Comment by kuosandys** [comment]
> One more thing I'd like to bring in before we implement this: Should we rename `group` to `category` to avoid any confusion with the RBAC API group or user group concept?

Seeing as we’re mainly using it for UI- related purposes right now, I think it would be a good precaution to take 👍

**Comment by kuosandys** [comment]
Implemented in https://github.com/giantswarm/happa/pull/3370 with our current use cases - I think we can close this issue.
