### ISSUE TITLE
kubectl-gs update check fails for (some) users

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1053]
As I just learnt from a user (not Giant Swarm staff member), both self-compiled binaries of kubectl-gs and our experimental Windows binaries fail to check for updates with this error:

```
Error: Version not found: couldn't find the latest version and/or release assets on GitHub, probably due to token without access to the repository giantswarm/kubectl-gs.
```

Since the repository is public, this should not happen.

**Comment by kuosandys** [comment]
Waiting for confirmation from customer

**Comment by marians** [comment]
I just re-read the issue and understood this:

When compiling your own kubectl-gs binary, and then using it, the update check will cause an error.

We should check if we can make the update check conditional, so that it would only be executed for a proper release binary.

**Comment by weatherhog** [comment]
closing
