### ISSUE TITLE
kubectl-gs on Windows should show colored output

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1059]
As a consequence of https://github.com/giantswarm/roadmap/issues/1055 we disabled colored output on Windows (as of v2.7.11) to avoid printing cryptic ANSII escape codes on the terminal.

To let errors stand out from other output, we should re-enable colored output in a way that's functioning on Windows, too. The https://github.com/fatih/color README shows:

```golang
// Windows supported too! Just don't forget to change the output to color.Output
fmt.Fprintf(color.Output, "Windows support: %s", color.GreenString("PASS"))
```

**Comment by weatherhog** [comment]
closing
