### ISSUE TITLE
Cluster autoscaler and spot instances

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#1061]
If spot instances are not available, cluster autoscaler fails and pages but we can't do anything.
How should the experience be for customers?

**Comment by whites11** [comment]
@alex-dabija will raise the topic in sig-product or sig-customer-success

**Comment by AverageMarcus** [comment]
Education for our customers / options to avoid:
* Multiple node pools (ensuring at least one using on-demand)
* Mixed instance ASGs - either all spot with different type options or a mix of spot and on-demand to ensure a certain level of availability

**Comment by whites11** [comment]
Happening again today on otter/cprod

**Comment by alex-dabija** [comment]
The CloudFormation has ASG has an option

**Comment by paurosello** [comment]
Found that cloudformation can "ignore" all the errors, not specific to ASG instance availability, will dig as I remember seeing something that could help.

**Comment by paurosello** [comment]
Closing this one in favor of https://github.com/giantswarm/giantswarm/issues/22787

**Comment by paurosello** [comment]
Evaluating Karpenter for spot instances as it gives more flexibility

**Comment by alex-dabija** [comment]
Phoenix & Hydra will sync on this. Not urgent for now. @alex-dabija will schedule a meeting.

**Comment by T-Kukawka** [comment]
closing - this will be taken up with Karpenter implementation
