### ISSUE TITLE
Research how customers configure the  dex app, especially when using k8s-authenticator in WCs

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1064]
Towards https://github.com/giantswarm/roadmap/issues/489
Fernando might be a good person to ask

**Comment by marians** [comment]
Asked in [Slack](https://gigantic.slack.com/archives/CSPJ172LT/p1650878720171699)

**Comment by anvddriesch** [comment]
At the present moment, the CA has to be part of the `values.yaml` that is used to configure the `dex-app`.
