### ISSUE TITLE
UI implementation: CLI guide for "Inspect permissions via the Management API"

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1066]
Towards https://github.com/giantswarm/roadmap/issues/808.

The goal for this issue is to provide a basic CLI guide for our permissions overview, so that users can connect what they see in the web UI with the relevant `kubectl` commands.

Advanced specs will follow in https://github.com/giantswarm/roadmap/issues/1071 to more closely align CLI output with the web UI.

**Comment by kuosandys** [comment]
@marians Are there some more detailed specs for this somewhere? I can't seem to find them - would appreciate some help 😅
