### ISSUE TITLE
add support for SOPS encrypted values to konfigure

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1069]
### User Story
 
- as a Giant Swarm engineer I want konfigure to support SOPS encrypted values so that I can use them to configure new installation
- as a Giant Swarm engineer I want konfigure to support so that I can encrypt installation secrets before the installation exists

#### Background 

@giantswarm/team-rocket had a long discussion about future of management clusters.  We are currently working with @giantswarm/team-phoenix on an RFC to have a common roadmap for it. 
One essential part of it is to move the current configuration related things out  the bootstrap process. By this we want to:
- reduce complexity of the current process
- enable CI/CD because we can create secrets in advance without relying on vault, or reuse existing ones as they become independent of the installation
- ease the process of creating a new installation by having the automation to do it in one place. 

### Related RFC and issues
https://github.com/giantswarm/rfc/tree/future_of_mc_bootstrap/future-of-mc-bootstrap

**Comment by kubasobon** [comment]
Just to be super-extra clear, we're talking SOPS GPG encryption, right?

**Comment by kopiczko** [comment]
I guess `konfigure` should work with SOPS with any of its backends.

**Comment by tfussell** [comment]
sops also supports a vault backend which could replace our custom `vault:` per-key encryption in `konfigure` as an intermediate step to using `gpg/age`. Note that sops encrypts whole files instead of individual fields so it doesn't make sense to just look at the prefix of each encrypted field to determine which encryption to use.

**Comment by gianfranco-l** [comment]
@alex-dabija  @cornelius-keller for the team it is still unclear what the severity here is. Could you give us an idea/ help us understand better about the Impact and severity of this one? This would help us understand better how to prioritize this one

**Comment by AverageMarcus** [comment]
The replacement of vault (with SOPS) is the current blocker for getting new management clusters built in a way we're comfortable with maintaining long-term. This in turn is a blocker for us moving forward with CAPG and GCP clusters. 

Phoenix has a "soft" deadline of the end of the month to have an MC in GCP for the customer to start testing out and working with us to discover the pain points. We then have a "hard" deadline of August for production.

**Comment by kopiczko** [comment]
This blocks automated tests implementation for MC creation and upgrades.

**Comment by MarcelMue** [comment]
I think the technical implications are quite clear and the soft deadline for Phoenix for end of this month is also clear to me now.

We are specifically asking if we should drop work on GitOps now and focus on this as a team. That is something I stressed previously - specifically asking both @cornelius-keller and @alex-dabija to assign clear priorities and impact to the ticket to make this decision.

From what I infer here, we (as in Honeybadger) should work on this ASAP as it's blocking progress for phoenix with a fixed deadline. Can I please get explicit confirmation of that from the POs here and apply the relevant labels (e.g. `impact/high`)?

**Comment by gianfranco-l** [comment]
@giantswarm/team-honeybadger there is a discovery work to be done on our side to understand how big is the scope of work and how big is the effort. We raised priority to start working on this spike right now

**Comment by alex-dabija** [comment]
The impact is high from my point of view because:
- blocks the implementation of automated tests for MC creation and upgrades (CI / CD pipelines). This leads to long feedback loops and creates friction between Phoenix and Rocket. It's difficult to know if we broke each other's functionality. I think that in order for us to iterate faster and deliver to our customers we need to reuse functionality across all providers and to enable teams to collaborate with as little friction as possible. My biggest concern at the moment is the fact that we are making it very difficult for our teams to work together by not having good software development / deployment practices;
- Phoenix has a soft deadline with CAPG end of May which means that we need to have a relatively stable management cluster setup for our customer that doesn't require too much manual intervention afterwards.

**Comment by cornelius-keller** [comment]
@gianfranco-l Team rocket wants to start to work on test automation soonish. Please let us now if there are some sub tasks were we can help. If your team can spec it out and guide us in the implementation we can contribute here. 
The other option we have is to work on an intermediate solution involving the automated use of last pass, but I would prefer to contribute to the final solution if possible.

**Comment by ljakimczuk** [comment]
A still WIP PR is here: https://github.com/giantswarm/konfigure/pull/121

**Comment by gianfranco-l** [comment]
@alex-dabija @cornelius-keller we look forward to hear your feedback on the above https://github.com/giantswarm/konfigure/pull/121 cc @giantswarm/team-honeybadger

**Comment by alex-dabija** [comment]
We discussed the topic today in the KaaS Sync: https://gigantic.slack.com/archives/C95NTB55M/p1652360513766179 .

Rocket is going to try it next week.

**Comment by gianfranco-l** [comment]
@giantswarm/team-rocket any update on this?

**Comment by kopiczko** [comment]
We haven't started with that yet. The idea is to try that with CAPVCD.

**Comment by ljakimczuk** [comment]
Hasn't this already been tried out? I remember configuring vaultless bootstraps in `management-clusters-fleet`.

**Comment by uvegla** [comment]
We tried it a few months ago with @ericgraf and it was working if I recall correctly.

**Comment by kopiczko** [comment]
`mc-bootstrap` already supports it. From my POV it can be closed.

**Comment by gianfranco-l** [comment]
closing [as suggested](https://github.com/giantswarm/roadmap/issues/1069#issuecomment-1251109550)

**Comment by cornelius-keller** [comment]
We really want to work on this, at it is still critical for our testing. I
currently can't give you a timeline as we also have to work on a lot of
customer facing issues.

**Comment by kopiczko** [comment]
@cornelius-keller this is already done
