### ISSUE TITLE
Generate PGP keys to be used with Flux+SOPS

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1070]
This is a feature request that came out in a secret management workshop held with a customer.

This is a customer feature request with three parts. As a Giant Swarm customer:

1. I'd like to have a PGP key pair generated for each Workload Cluster.
2. I'd like for the private PGP key to be delivered to Workload Cluster in a secret usable with SOPS.
3. I'd like for the public PGP to be published somewhere.

As a customer, I'd live to have the 3 points above automated (@kubasobon if i'm wrong, pls remove this sentence :))
Additional requirements for key safety were mentioned during the workshop, like generating more than one key pair for backup.
These additional requirements will be further refined and discussed during the implementation work

**Comment by gianfranco-l** [comment]
@kubasobon can we close this as this is done?

**Comment by piontec** [comment]
Closing, as we have this now in `kgs gitops`
