### ISSUE TITLE
Add upgrade schedule documentation to public docs

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#1074]
Source: https://github.com/giantswarm/upgrade-schedule-operator#how-to-schedule-the-upgrade

We currently don't have this mentioned on our public docs (so can't easily point our customers at it)

**Comment by whites11** [comment]
we have this in the intranet to start from https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/scheduling-upgrades/

**Comment by alex-dabija** [comment]
`kubectl-gs` has an `update` subcommand to schedule or trigger an upgrade: https://docs.giantswarm.io/ui-api/kubectl-gs/update-cluster/ .

I think we just need to mention and link to it from the cluster upgrades article we have in our public docs: https://docs.giantswarm.io/general/cluster-upgrades/ . It's the first link listed when I search for `upgrades`.

**Comment by AverageMarcus** [comment]
@alex-dabija  does that command also allow for changing out removing the schedule? If not, that should need included in the docs.

**Comment by alex-dabija** [comment]
> @alex-dabija does that command also allow for changing out removing the schedule? If not, that should need included in the docs.

Good point. I don't know if you can remove the schedule with `kubectl-gs`. It's probably not possible given the arguments, but it should be possible to reschedule.

**Comment by njuettner** [comment]
Adding the command to remove the upgrade schedule in `kubectl-gs` is not so easy, see the comments. There need to be a bit more thinking on that side, I created an issue https://github.com/giantswarm/giantswarm/issues/22140 for rainbow to have some ideas how we wanna do it.
