### ISSUE TITLE
Use AWS secret manager instead of SOPS

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#1076]
As a user of flux on the management cluster I'd like to use the AWS secret manager instead of SOPS for secrets

https://aws.amazon.com/blogs/security/how-to-use-aws-secrets-configuration-provider-with-kubernetes-secrets-store-csi-driver/

**Comment by gianfranco-l** [comment]
this depends from this one https://github.com/giantswarm/roadmap/issues/1073
the dependency at the moment (given the size and the current focus of the needed teams) is not likely to be worked for the Q3 and Q4 2022

**Comment by teemow** [comment]
@gianfranco-l imo this is not dependent on #1073. It depends on this https://github.com/giantswarm/roadmap/issues/1084

**Comment by teemow** [comment]
Feedback from the customer about the reasoning SOPS vs AWS secret manager:

> For our Enterprise Instalations i don't like the handling of keeping secrets within the git repository for this reasons:
>
>  * It has potential to be exposed by accident
>  * You need SOPS to be installed and configured correctly
>  * you can't see who has accessed it (auditing)
>  * secret rotation is hard to achieve
>
> External Secrets Operator:
> With the CSI Driver you can achieve the same by Syncing a Secret to a Kubernetes Secret.
> https://secrets-store-csi-driver.sigs.k8s.io/topics/sync-as-kubernetes-secret.html

**Comment by MarcelMue** [comment]
Unassigned myself and added the blocked label as we wait for #1084

**Comment by weatherhog** [comment]
@mproffitt is this something that we are now doing with ESO?

**Comment by mproffitt** [comment]
We have the option available to use ESO to pull secrets out of any external secret store, not just AWS SecretsManager.

IMO the requirements here are fulfilled and can be closed as complete.
