### ISSUE TITLE
Consistently get Giant Swarm workload cluster worker node defaults for CPU and Memory

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#108]
As a Giant Swarm developer creating a cluster to test components, I want to consistently get Giant Swarm's workload cluster worker node defaults for CPU and Memory regardless of which method I use (whether Happa or gsctl), so I know my component works out-of-the-box in any cluster.

As a customer admin creating a cluster to test components, I want to consistently get Giant Swarm's workload cluster worker node defaults for CPU and Memory regardless of which method I use (whether Happa or gsctl), so I know my component works out-of-the-box in any cluster my users creates.

**Is your feature request related to a problem? Please describe.**

Right now, the TC worker node defaults for CPU and Memory are different when creating via Happa vs gsctl, at least in KVM. Not sure w other providers.

@sslavic mind describing how this made your life harder in KVM implementing default HPA for NGINX IC?

**Describe the solution you'd like**

- [ ] Rest API `GET /v4/info/` on KVM should inform about the default worker node size (RAM, CPUs).
- [ ] Happa should make use of the above info instead of it's own defaults.

**Describe alternatives you've considered**

**Additional context**

**Comment by sslavic** [comment]
When a new tenant cluster is created with all the settings on their defaults as a customer I'd expect pre-installed components to at least start (if not have some predictable quality of service guarantees).

So, I wanted to ensure this is still true after making changes to nginx app, only to find out that there's discrepancy between default KVM worker node size when tenant cluster is created through happa (4 CPU workers) and through gsctl (2 CPU workers); they use different sources of definition of what default value is, and that approach can result in those two definitions going out of sync. Via https://github.com/giantswarm/cluster-service/pull/414 I've synced them manually, while keeping same approach of having two definition sources for default kvm worker node CPU.

**Comment by snizhana-dynnyk** [comment]
ping @marians

**Comment by marians** [comment]
Happa should get it's defaults from the API's [info endpoint](https://docs.giantswarm.io/api/#operation/getInfo). We have to ensure that this is the case.

gsctl does not apply any client side defaulting. Here, server-side defaulting should apply. The result should be consistent with the info endpoint's data.

**Comment by marians** [comment]
Just checked. On KVM the info endpoint does NOT yet provide the default worker node size parameters.

**Comment by marians** [comment]
With the Control Plane k8s API use coming to the web UI we need to have an idea how this info can be accessed.

**Comment by marians** [comment]
Adding to WG Control Plane API board for discussion. We need a way to inform clients about installation config, defaults etc. In other words: a replacement for the [Rest API's info endpoint](https://docs.giantswarm.io/api/#operation/getInfo).

**Comment by puja108** [comment]
This will be folded into the new way how we do defaulting and versioning for WCs
