### ISSUE TITLE
CAPG e2e DNS tests

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1080]
## TODOs

- [ ] Add (or verify existence of) e2e DNS tests for CAPG.

## Background

The [dns-operator-gcp](https://github.com/giantswarm/dns-operator-gcp) we implemented to manage the workload cluster's hosted zone and to create DNS records for the Kubernetes API needs to be tested.

**Comment by fiunchinho** [comment]
We have acceptance tests in the `dns-operator-gcp` app, should we close this one?

**Comment by alex-dabija** [comment]
This refers to having DNS test(s) in our end to end test suite. I would keep this issue around until we get the end to end test suite running for CAPG and until we confirm or add DNS tests to it.
