### ISSUE TITLE
Which terraform provider to use with management cluster CRs for cluster management

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#109]
Related to https://github.com/giantswarm/giantswarm/issues/8609

## User story

_As a cluster admin, I want to define a workload cluster using a simple values file, letting Terraform take care of the creation of custom resources in the Giant Swarm management cluster._

## Context

Customer basically want to manage (create, modify, delete) clusters in a git-ops fashion. Terraform is supposed to apply any changes to the GS management cluster.

Currently it is not clear which terraform provider should be used for this purpose.

From a customer call ([notes](https://github.com/giantswarm/giantswarm/issues/8609#issuecomment-594541797)).

**Comment by corest** [comment]
New terraform provider for k8s works pretty well

**Comment by marians** [comment]
@corest Nice! Is there a canonical URL for this URL to that new terraform provider for k8s, so that we can point customers to it?
