### ISSUE TITLE
GCP project for VM images

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1091]
## Stories

-*-As a cluster admin, I want to have all VM images in a single project managed by Giant Swarm in order to have quick access to updates.*_

_*-As a developer, I want to have all VM images in a single project manged by Giant Swarm in order to build images only once and to quickly provide updates.*_

## Background

The images are built and available in the test project. They need to be made available in a separate project.

## Changes
- [x] VM images are available in a separate GCP project meant only to be used for this purpose.

**Comment by AverageMarcus** [comment]
Created project `giantswarm-vm-images`
Owner permission given to PE and SRE google groups
Compute Engine API enabled

**Comment by AverageMarcus** [comment]
Related CAPO issue: https://github.com/giantswarm/roadmap/issues/597

**Comment by AverageMarcus** [comment]
Service account created for building images `image-builder@giantswarm-vm-images.iam.gserviceaccount.com` and keys added to LastPass as `gcp-image-builder-keys`

**Comment by AverageMarcus** [comment]
The following images have been created:
* `cluster-api-ubuntu-1804-v1-20-15-1655136076`
* `cluster-api-ubuntu-2004-v1-20-15-1655136892`

Both images have also been made "public" (See https://cloud.google.com/compute/docs/images/managing-access-custom-images#share-images-publicly) so they can be used cross-project.

**Comment by AverageMarcus** [comment]
Tekton pipeline (https://github.com/giantswarm/capi-image-builder) set up and confirmed working.
