### ISSUE TITLE
Kubernetes API to access etcd through load balancer

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1092]
## Story

_*-As a cluster admin, I want to have the Kubernetes API access `etcd` through the load balancer in order to improve the cluster's performance.*_

## Background

The Kubernetes API is configured to access `etcd` via `localhost` even for highly available clusters.

We identified that the cluster's performance can be improved if the Kubernetes API accesses `etcd` through the load balancer. See [comment](https://github.com/giantswarm/giantswarm/issues/21946#issuecomment-1123557966) for more details.

## Changes

- [ ] Configure the Kubernetes API to access `etcd` through a load balancer for highly available clusters. Clusters with a single node control plane should still access `etcd` via `localhost`.

**Comment by paurosello** [comment]
@whites11 isn't this done or was it "hacked" in deu01?

**Comment by whites11** [comment]
> @whites11 isn't this done or was it "hacked" in deu01?

hacked

**Comment by whites11** [comment]
It is now merged and released in `k8scc`.
Need to bump the dependency in `aws-operator` and `azure-operator`.

**Comment by alex-dabija** [comment]
It's included in the release.
