### ISSUE TITLE
Enable `aws-cni` prefix delegation for new workload clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1096]
## Story

_*-As a cluster admin, I want `aws-cni` prefix delegation to be enabled by default for new clusters in order improve the startup times of pods during scaling events.*_

## Background

The allocation of new IPs with `aws-cni` is quite slow and AWS now offers prefix delegation to allocate IPs in chunks which should improve the start time of pods during scaling events.

## Changes

- [ ] Enable `aws-cni` prefix delegation nodes by default for new workload clusters.

**Comment by alex-dabija** [comment]
We are still evaluating if we really want to do this because we might move to Cilium.

**Comment by T-Kukawka** [comment]
closing this as in v19 cilium will be included and there will be no aws-cni running anywhere
