### ISSUE TITLE
CIFS pod volumes

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1100]
## Story

_*-As a cluster admin, I want to attach CIFS volumes to pods in order to migrate existing applications to Kubernetes.*_

## Resources

- [Initial Github issue](https://github.com/giantswarm/giantswarm/issues/22088);
- [smb-csi-driver](https://github.com/kubernetes-csi/csi-driver-smb);

**Comment by Rotfuks** [comment]
Closed for now as won't do. Will potentially rediscover in the future.
