### ISSUE TITLE
ensure calico is properly monitored

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1105]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [ ] ensure it is scraped by Prometheus
- [ ] make sure there are basic alerts

**Comment by bavarianbidi** [comment]
As `cilium` is our `CNI` of choice i think this issue can be closed as cilium monitoring will be done https://github.com/giantswarm/roadmap/issues/1106 

cc @gawertm / @cornelius-keller

**Comment by gawertm** [comment]
@cornelius-keller how do you usually do it? move it to done september? can we archive this? or even deleting?

**Comment by cornelius-keller** [comment]
We just closed and then the automation moved. You can decide how to do in future.
