### ISSUE TITLE
Add boiler plate for new controller in PMO

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1110]
We need a new controller to reconcile `RemoteWrite` CustomResources in [prometheus-meta-operator](https://github.com/giantswarm/prometheus-meta-operator).

Controllers are defined here https://github.com/giantswarm/prometheus-meta-operator/tree/master/service/controller

Add a new controller by re-using boiler plate from other controllers and omit the reconciled resource for now. We will add this later when we have it.
Controllers are then wired and started [there](https://github.com/giantswarm/prometheus-meta-operator/blob/master/service/service.go), we can wire it to test but we should leave this out until the controller implementation is complete.

**Comment by mcbenjemaa** [comment]
remotewrite controller implementation will be on this PR: https://github.com/giantswarm/prometheus-meta-operator/pull/905
