### ISSUE TITLE
Upgrade current controller to ignore RemoteWrite field

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1111]
Towards: https://github.com/giantswarm/roadmap/issues/496

### Description

Update the current [Prometheus resources](https://github.com/giantswarm/prometheus-meta-operator/tree/master/service/controller/resource/monitoring/prometheus) to ignore the `Prometheus.spec.remoteWrite` field when computing diff and when performing and update.

### TODO

- [x] Ignore changes in prometheus.spec.remoteWrite
- [x] Carry over changes in prometheus.spec.remoteWrite

**Comment by mcbenjemaa** [comment]
Agreed with @TheoBrigitte  that PMO controller will ignore diffing and updating remotewrite field.
on the other hand, remotewritecontroller will be the only controller to update this field in the prometheus CR.
