### ISSUE TITLE
VPN setup

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1113]
## Story

_*-As a cluster admin, I want to access clusters over a VPN in order to increase the cluster's security.*_

## Resources

- [Giant Swarm VPN](https://github.com/giantswarm/vpn);
- [CAPG Network Layout](https://miro.com/app/board/uXjVO9UfMjE=/). See `phase 2` for VPN setup.

## Background

Giant Swarm's VPN setup requires that bastion hosts be on a subnet with a /27 CIDR to be reserved and to be globally unique for each management cluster. This has the following drawbacks:
* the globally unique CIDR couples management clusters between each others;
* the management cluster VPC has the VPN gateway attached to it. This makes management clusters different from workload clusters;
* workload clusters can't be promoted to management clusters.

The VPN is required in order to SSH to clusters nodes and to have access to the Kubernets API.

## Solutions (high level description)

* Use current Giant Swarm VPN setup and accept it's limitations;
* Use current Giant Swarm VPN setup, but attach the VPN gateway to both management clusters and workload clusters. In this case, workload clusters can't be treated as cattle because the /27 CIDR needs to be globally unique;
* Use wireguard (tailscale, netmaker) and have all cluster nodes on the same network. The network can be per customer, per management cluster & workload clusters, per cluster (either management or workload). In this case there are no bastion hosts;
* Use wireguard (tailscale, netmaker) and have all bastion hosts on the same network;

**Comment by calvix** [comment]
BTW I realized why we have the `/27` for the  bastion subnet because the smallest subnet size you can create on AWS is `/28` so in order to have 2 bastions each in different AZ we need 2x `/28` which si the `/27`

we cannot make this any smaller unfortunately, only solution would be live with 1 bastion which you give us `/28` for bastion
