### ISSUE TITLE
Configure  encryption at rest configuration

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#1116]
`--encryption-provider-config` is missing in api-server flags for CAPO. We need to add it by adding the necessary things. 

Pawel's comment:

> For encryption at REST I found this https://github.com/giantswarm/encryption-provider-operator but it requires some learning on how it works. From a quick glance it runs in a MC and connects to remote WCs from there. It also installs https://github.com/giantswarm/encryption-config-hasher by creating Chart CRs in the WC.

**Comment by kopiczko** [comment]
For the record linking Slack discussion with Vaclav: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1652688001253479

**Comment by kopiczko** [comment]
Follow up issue: [Make encryption-provider-operator watch CAPI v1beta1](https://github.com/giantswarm/giantswarm/issues/22156)

**Comment by kopiczko** [comment]
The last bit is releasing `cluster-openstack`.
