### ISSUE TITLE
Support Audit log for CAPO

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#1117]
We need to support audit logs for api-server and add these flags for CAPO.

```
--audit-log-maxage 
--audit-log-maxbackup 
--audit-log-maxsize 
--audit-log-path 
--audit-policy-file  
```

**Comment by gawertm** [comment]
solution by atlas with fluentbit in place

**Comment by erkanerol** [comment]
we noticed that fluentbit is not enough. we have to enable auditlog flag too. reopening it.

**Comment by pipo02mix** [comment]
this  no more relevant, closing
