### ISSUE TITLE
Configure Cilium and Linkerd such that they do not "overlap" in functionality

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#1121]
As we are testing Cilium as a replacement for AWS-CNI (ref. https://github.com/giantswarm/roadmap/issues/1102), a fundamental point to verify is that Cilium can also replace AWS-CNI in environments where Linkerd is being used.

It will therefore be important to:
- perform tests first-hand to understand whether some configuration adjustments are required
- test with customers in dev clusters and verify that there is no disruption

**Comment by LolloneS** [comment]
We have migrated AWS to Cilium with Giant Swarm release 18.0.0. Have some tests on how Cilium and Linkerd work together been run or planned? @weatherhog @T-Kukawka

**Comment by weatherhog** [comment]
@LolloneS no. all communication regarding cilium was so far more on the informational side. A meeting regarding what KaaS has done with cilium would be great so that we in cabbage can start thinking of tests for linkerd

**Comment by T-Kukawka** [comment]
@weatherhog there has been alpha v18 as well as now v18 GA GS release with cllium in place of aws-cni. Here is our internal documentation: https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/upgrade-to-cilium/upgrade-to-cilium/

**Comment by weatherhog** [comment]
thanks. created an issue for atlas so that we will test linkerd on cilium clusters

**Comment by mcharriere** [comment]
hey there. we are already running Cilium+Linkerd. Do we want to keep this issue open?

**Comment by LolloneS** [comment]
IMHO this can be closed
