### ISSUE TITLE
CAPG workload clusters in a different project

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1124]
## Story

_*-As a cluster admin, I want to workload cluster to be created in a specific GCP project in order to have a clear separation of ownership between teams or systems.*_

## Background

One common GCP pattern is to have a separate project for each team or system in order to separate cloud resources for security and ownership reasons.

## Resources

- [Creating and managing GCP projects](https://cloud.google.com/resource-manager/docs/creating-managing-projects);

**Comment by nprokopic** [comment]
We can close this one, right?

**Comment by mnitchev** [comment]
Seems to work on `frieza` with latest cluster-gcp versions
