### ISSUE TITLE
Add organization label to metrics to enable customer to filter by that

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#1129]
**Is your feature request related to a problem? Please describe.**

As user admin, I would like to filter in Grafana by organization

**Describe the solution you'd like**

New label in metrics to filter with

**Describe alternatives you've considered**

Now we have to select between the long list of clusters which ones belong to the organisation which makes it really difficult when you have many clusters

**Additional context**

**Comment by QuentinBisson** [comment]
@TheoBrigitte I think this is done right?
