### ISSUE TITLE
Expose cluster creator via our API / front end

### ISSUE THREAD

**Issue by rossf7** [giantswarm/roadmap#113]
Currently we ask everyone to include their username in the cluster name when creating test clusters. This is important so we can contact the owner if they are generating errors or unnecessary costs.

However it's easy to forget and we have lots of new starters who don't know this. 

Idea from @marians is to add a `created_by` field to the API object. It can then be exposed in Happa and gsctl.

Idea from @corest is to use this for the Cluster Police bot. To notify the owner and so we don't spam the #ops channel with these notifications.

Threads:

#sig-product https://gigantic.slack.com/archives/C02521EC0/p1573809116294100
#product-kaas https://gigantic.slack.com/archives/CNX3Z835G/p1573809431036900

**Comment by Oshratn** [comment]
Looking at this from the sales enablement PoV. Would customers fins this useful too?

**Comment by MartaD** [comment]
It will be done after KVM uses CAPI.

**Comment by puja108** [comment]
closing this for now as it's stale and does not seem to get any priority soon
