### ISSUE TITLE
Cilium as the CNI for management clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1136]
## Story

_*-As a management cluster admin, I want to use Cilium as the CNI for management clusters in order to improve the pods' startup time when lots of pods need to start at the same time and to gain experience with it.*_

## Background

AWS Giant Swarm clusters use `aws-cni` which can be quite slow when lots of pods are scheduled at the same time because the cluster needs to request IPs from AWS for each pod. Yes, there is the option to pre-request IPs, but this doesn't help with new nodes which need to come up as soon as possible because of auto scaling events.

We want to replace `aws-cni` with Cilium on workload clusters, but we don't have experience with Cilium yet.

## Questions

- What is the experience of migrating from `aws-cni` to Cilium?

**Comment by whites11** [comment]
everything looking very good.
I tested the migration from aws-cni to cilium and it goes pretty smooth. There is a moment where things stop working for obvious reasons, but as soon as cilium DS is up and running everything starts working again.
I've got a couple of PRs to merge in `app-operator` and `chart-operator`, but apart from that, this is ready to ship on test installations.

Next steps:

- deploy on an AWS test installation
- deploy on an Azure test installation

**Comment by whites11** [comment]
Deploying on test installations:

- [ ]  gaia
- [ ]  gauss
- [ ]  ginger
- [ ]  giraffe
- [ ]  ghost
- [ ]  godsmack
- [ ]  gremlin

**Comment by whites11** [comment]
Seems an incompatibility between cilium and azure-aad-pod-identity

**Comment by whites11** [comment]
I believe it's incompatible, opened an issue upstream https://github.com/cilium/cilium/issues/20103

**Comment by whites11** [comment]
Things/problems I noticed so far:

- sometimes the cilium pod fails to start because: `error="ciliumnodes.cilium.io \"master-000010\" already exists"` and requires manual fix
- not compatible with azure-ad-pod-identity. Requires PR to azure-ad-PI and creating of ad-hoc cilium CR
- kiam requires ad-hoc cilium CR (not a problem for MCs)

**Comment by whites11** [comment]
Opened PR to aad-pod-identity to make bind address configurable https://github.com/Azure/aad-pod-identity/pull/1284

**Comment by whites11** [comment]
Blocked until this PR is merged and released https://github.com/Azure/aad-pod-identity/pull/1284

**Comment by whites11** [comment]
We decided to deploy the cilium branch of giantnetes-terraform to `gorilla` to see how it behaves in production.

**Comment by whites11** [comment]
Goal: deploy to all test installations, gollum and gorilla

- [ ]  ghost
- [ ]  godsmack
- [ ]  gremlin
- [ ] gollum
- [ ]  gaia
- [ ]  gauss
- [ ]  ginger
- [ ]  giraffe
- [ ] gorilla

**Comment by whites11** [comment]
Releasing everywhere

- [ ]  akita
- [ ]  alpaca
- [ ]  anaconda
- [ ]  anchovy
- [ ]  anteater
- [ ]  antelope
- [ ]  argali
- [ ]  bandicoot
- [ ]  eagle
- [ ]  flamingo
- [ ]  fox
- [ ]  gaia
- [ ]  gauss
- [ ]  ginger
- [ ]  giraffe
- [ ]  gorilla
- [ ]  kudu
- [ ]  otter
- [ ]  tiger
- [ ]  valkyrie
- [ ]  viking
- [ ]  viper
- [ ]  visitor
- [ ]  ghost
- [ ]  godsmack
- [ ]  goku
- [ ]  gollum
- [ ]  gremlin
- [ ]  icecream
- [ ]  orion
- [ ]  talos
- [ ]  victory
