### ISSUE TITLE
CAPG monitoring and alerting

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1145]
## Story

_-As a cluster operator, I want to be notified if the clusters are not functioning properly in order to fix issues as soon as possible and to offer a stable environment to application developers._

## Background

Giant Swarm already has a monitoring solution based on Prometheus, Alert Manager and OpsGenie. This should also be used for CAPG CAPI clusters.

**Comment by fiunchinho** [comment]
Monitoring won't work until we provision `StorageClasses` into the cluster, because they are needed by prometheus statefulsets.

**Comment by alex-dabija** [comment]
Monitoring and alerting are enabled for CAPG clusters. Any problems found with monitoring will be addresed in separate issues.
