### ISSUE TITLE
Support PodSecurityPolicies in CAPO

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#1148]
PodSecurityPolicies feature gate is not enabled for CAPO yet. We need to enable it for GA.

When we enable PSPs now, kube-proxy is not working. AWS and GCP providers use https://github.com/giantswarm/cluster-shared to deploy necessary PSPs via `ClusterResourceSet` and state `cluster-shared` as a dependency like https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/Chart.yaml#L11

**Comment by othylmann** [comment]
@erkanerol are we doing PSPs for CAPO now or moving directly to Kyverno? If not, then this should be closed.

**Comment by erkanerol** [comment]
The last decision was to support PSPs too but we may need to reconsider the decision according to the timeline. PSPs will be deleted in k8s 1.25, which is going to be released at the end of this month or next month. We use 1.22 in THG prod now.
