### ISSUE TITLE
Default 'NGINX NodePort and LoadBalancer Services externalTrafficPolicy' to Local

### ISSUE THREAD

**Issue by omegas27** [giantswarm/roadmap#115]
Tue, 23. Jun 2020 update: Where this is available
* Azure 11.4.0 https://github.com/giantswarm/giantswarm/issues/10871 (drafting release)
* AWS node pools clusters (10+) is covered with nginx IC App 1.6.10
* Decided not to do
** AWS legacy is not needed, at least Vaclav suggested not to invest in legacy any more unless it turns out needed
** KVM is not high prio, it's currently undergoing lots of changes (libs flattening, CRD v1 migration), so would not recommend investing in external traffic policy changes for nginx there yet; we can reevaluate once I'm back

---

We're moving NGINX IC load balancer management from azure-operator to the NGINX IC app, in order to enable
* externalTrafficPolicy configurability
* default to `Local` on Azure (Preserves source IP for security, as well as improves NGINX capacity for concurrent connections), and
* making Azure load balancer configurable between internal or public
* eventual turning of NGINX from a preinstalled to an optional app on Azure

---

Default NGINX NodePort and LoadBalancer Services externalTrafficPolicy needs to be changed to Local. Optionally externalTrafficPolicy of nginx Services should be made configurable.

This is needed:
- to preserve source IP for IP based filtering/security
- to remove unnecessary internal hops/traffic and with this support (increase capacity for) more concurrent connections

**Comment by cokiengchiara** [comment]
@sslavic will update this ticket w new discussion w customer.

**Comment by cornelius-keller** [comment]
For @giantswarm/team-ludacris find out how LB works on KVM

**Comment by cokiengchiara** [comment]
Thu, May 7, '20 Status From @sslavic 
* @whites11 is taking care for Azure. [slack](https://gigantic.slack.com/archives/CR99LSZ1N/p1588865957183500)
* AWS node pools is covered with nginx IC App 1.6.10
* AWS legacy is not needed, at least Vaclav suggested not to invest in legacy any more unless it turns out needed
* KVM is not high prio, it's currently undergoing lots of changes (libs flattening, CRD v1 migration), so would not recommend investing in external traffic policy changes for nginx there yet; we can reevaluate once I'm back

**Comment by cokiengchiara** [comment]
@whites11 mind giving a short update on what you want to do this week for this? :) couldn't get that from Halo planning :D

**Comment by cokiengchiara** [comment]
@sslavic can you confirm - what's kept us from further progress on this is being able to do performance testing, i.e. this https://github.com/giantswarm/giantswarm/issues/11062 is that correct? 

For now moving this back to Planned for Current Cycle.

**Comment by cokiengchiara** [comment]
Hoping to finish before Hackathon. 
Finishing release notes. 
Christian will look into migration script.

**Comment by cokiengchiara** [comment]
Mon, 29. Jun 2020 

Testing works.
Planning to release this week. (We won't include app updates)

**Comment by sslavic** [comment]
Source IP preservation support was shipped in Azure 11.4.0 platform release /w nginx IC App 1.7.0.

AWS legacy remains unsupported, migration to node pools platform releases is advised.

For KVM @omegas27 will check if there's demand, and if so a new ticket can be created.

@cokiengchiara @omegas27 lets close this one.

**Comment by cokiengchiara** [comment]
@sslavic thanks!

Done in Azure! https://github.com/giantswarm/releases/tree/master/azure/v11.4.0
Will create PDR about not in kvm and old aws https://github.com/giantswarm/giantswarm/issues/11999
