### ISSUE TITLE
Add VCD to mc-bootstrap

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1150]
- [ ] add support to mc-bootstrap to deploy a VCD  Management cluster.

**Comment by glitchcrab** [comment]
related: https://github.com/giantswarm/roadmap/issues/1126

**Comment by glitchcrab** [comment]
works up to cert manager app installation

**Comment by glitchcrab** [comment]
clusters are mostly created :rocket:

**Comment by glitchcrab** [comment]
closing in favour of https://github.com/giantswarm/roadmap/issues/1273
