### ISSUE TITLE
Package CAPVCD as an app 

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1151]
Create a Helm chart and app for the CAPVCD controllers 

https://github.com/giantswarm/cluster-api-provider-cloud-director-app

**Comment by vxav** [comment]
CAPVCD controller image available at `quay.io/giantswarm/cluster-api-provider-cloud-director-vcd:003336f`

Tagged by commit ID.

**Comment by vxav** [comment]
Initial release made, closing this.
