### ISSUE TITLE
Package CAPI controllers as an app

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1168]
- [x] Reach out to team Phoenix to ask about specifics of https://github.com/giantswarm/cluster-api-app
- [x] Make sure that the version matches what is currently deployed
- [x] Adapt OpenStack collection https://github.com/giantswarm/openstack-app-collection/pull/88
- [x] Migrate existing CAPO clusters
- [x] Adapt mc-bootstrap for CAPO
- [x] Adapt cloud-director collection https://github.com/giantswarm/cloud-director-app-collection/pull/3
- [x] Adapt mc-bootstrap for cloud-director

**Comment by JosephSalisbury** [comment]
would be useful to stop @kopiczko having to use clusterctl to enable ignition features

**Comment by glitchcrab** [comment]
needs updating to latest version of capi controllers. Erkan AFK next week.

**Comment by erkanerol** [comment]
We use `v1.1.5` in production and that version is the part of `cluster-api-app` `v1.5.1`

**Comment by erkanerol** [comment]
TODOS:
- collection
- existing clusters
- mc-bootstrap
   - [ ] https://github.com/giantswarm/mc-bootstrap/pull/214

**Comment by glitchcrab** [comment]
Currently waiting for THG to let us migrate their clusters

**Comment by erkanerol** [comment]
Migration is DONE.  For OpenStack, we only need this PR https://github.com/giantswarm/mc-bootstrap/pull/214

**Comment by erkanerol** [comment]
For Vsphere, we added an item into this epic https://github.com/giantswarm/roadmap/issues/319
