### ISSUE TITLE
Access information about installations via Management API

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#117]
## Rationale 

We currently store different metadata in Installations repo.
We could expose data about Azure VM sizes, AWS instance types, CPU, defaults for worker node sizes in kvm etc. via Control Plane API.

## User Story

- _As a Giant Swarm user, I would like to access information about installations via k8s API_

## Dependency 
 
- [x] #103 Make cluster/machinedeployment/appcatalogs CRs namespaced by organization

**Comment by axbarsan** [comment]
> We currently store different metadata in Installations repo.
> We could expose data about Azure VM sizes, AWS instance types, CPU, defaults for worker node sizes in kvm etc. via Control Plane API.

We plan to use the `athena` service for that on the client-side. I think it could be used by customers, as well.

**Comment by marians** [comment]
FYI: Terminology in the title changed from "Control Plane API" to "Management API".
