### ISSUE TITLE
Enable Linkerd 2.11.x proxies to bootstrap correctly in clusters with Calico Network Policies

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#1174]
There is a race condition in Kubernetes clusters that use a non-Calico CNI together with Calico as a policy engine (network policies). in case there is a pod that uses post-start hooks we have observed that the network is not working well during the hook execution. It seems calico has not configured the pod IP by that time and network policies will not work as expected.

More details in [upstream issue](https://github.com/projectcalico/calico/issues/3499)

We need to find a workaround disabling the hook or some temporal network policy extension

**Comment by pipo02mix** [comment]
[According to Casey it may have been fixed in AWS CNI](https://github.com/projectcalico/calico/issues/3499#issuecomment-1163609512). I would be great to give it a try

**Comment by danibaeyens** [comment]
There is a valid workaround by using a no-op initContainer. A pod sandbox receives an IP after starting its containers and run their webhooks, or just when an initContainer has successfully run. Once assigned an IP, there are no issues with the postStart hook.

See: https://github.com/linkerd/linkerd2/issues/8738#issuecomment-1179812203

**Comment by pipo02mix** [comment]
The init container hack has been added by default to current version till there is a stable solution
