### ISSUE TITLE
Make api load balancer type configurable in openstack.

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1178]
### Context
Currently the load balancer for openstack  it is `single_lb_tiny`. This can create issues because it is not highly available. `ha_lb_tiny` is the better choice.
We will also make this configurable to make further changes of the LB more easy.  
### Tasks
- [ ] make api load balancer configurable in `cluster-openstack`
- [ ] set `ha_lb_tiny as default
https://gigantic.slack.com/archives/C025SV21RP1/p1655470617560139

**Comment by cornelius-keller** [comment]
Feedback from Refinement:
- it is not implemented in CAPO
- we don't have the permission to list the available flavors
- Can we set a default flavor on openstack?

**Comment by bavarianbidi** [comment]
> assumption: Loadbalancer type is set via flavor - [openstack documentation](https://docs.openstack.org/octavia/latest/admin/flavors.html)

1. we're not able to list different provided loadbalancer flavors
2. per default no `flavor_id` is specified in a loadbalancer create call (neither via `openstack loadbalancer create` or in `CAPO`)
3. creating a loadbalancer via CLI by setting a flavor - with the current permissions we have - works fine:
    ```
    openstack loadbalancer create --name standalone-lb --flavor ha_lb_tiny --description "hb_lb_tiny-test" --enable --vip-subnet-id 10d89517-zzzz-yyyy-xxxx-c2cdea6c7a9d
    ``` 
4. Upstream Issue kubernetes-sigs/cluster-api-provider-openstack#1278 for tracking purpose got created

For customer workload it's already supported to define the loadbalancer flavor by setting the annotation `loadbalancer.openstack.org/flavor-id` (xref: https://github.com/kubernetes/cloud-provider-openstack/blob/master/pkg/openstack/loadbalancer.go#L1713-L1715)

**Comment by gawertm** [comment]
@bavarianbidi what is the state of this issue? what do we expect from this upstream issue?

**Comment by bavarianbidi** [comment]
@gawertm upstream issue got created to make the issue/feature request transparent to CAPO community. This helps to track the feature request on CAPO side and also makes it easy to reference other open feature requests which might be impacted by this issue(a possible implementation).

As we've got a few thumbs up, it's fine to start with the implementation and contribute to upstream.

**Comment by gawertm** [comment]
@bavarianbidi yeah, I think I formulated my question wrong^^ ofc its clear why we created upstream issue, question was more, what will happen now or what are we waiting for. 
But as you said we can start with the contribution. should I put it back to the backlog then?

**Comment by bavarianbidi** [comment]
> But as you said we can start with the contribution. should I put it back to the backlog then?

as the requirements are clear, it should be fine to start with the implementation. (so yes, moving back to backlog is fine - IMO)
