### ISSUE TITLE
Replace CoreOS with Flatcar on Azure

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#118]
## User Story

- As a Giant Swarm employee I want to provide service using OS version that is supported so it will receive updates and fixes.

## Background
Red Hat announced the [End of Life of CoreOS Container Linux](https://coreos.com/os/eol/). After careful consideration of options we have made a decision to change OS for all providers to Flatcar Container Linux.

**Comment by MartaD** [comment]
The change was successful for new clusters. Unfortunately we have issues with upgrading clusters from coreOS to Flatcar:
Previously when using the coreOS image, we did not specify a plan in our ARM template. Now when we try to use the Flatcar image, we need to specify a plan.
Unfortunately Azure does not seem to allow the upgrade of a VMSS from an image without a plan to an image with a plan. 

We are looking at options and solutions how to upgrade our VMSS from the coreos image to a Flatcar image. Discussions with Microsoft and Kinvolk are in progress.

**Comment by snizhana-dynnyk** [comment]
@MartaD all Azure control planes are running Flatcar now.

**Comment by MartaD** [comment]
Thank you! ❤️  I'll close this ticket then.
