### ISSUE TITLE
Use kustomize to automatically generate the CAPVCD helm chart

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#1183]
At the moment the Helm chart was created manually but this won't scale, especially given that the upstream project is not released yet.

We will need to use the same method as CAPO to dynamically generate the chart for [CAPVCD](https://github.com/giantswarm/cluster-api-provider-cloud-director-app).

**Comment by erkanerol** [comment]
The PR is ready for review https://github.com/giantswarm/cluster-api-provider-cloud-director-app/pull/27

**Comment by erkanerol** [comment]
Done.
