### ISSUE TITLE
Phase out `kubectl gs template nodepool` command

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1188]
With Cluster API, node pools are configured via cluster app bundles. For GCP, we haven't implemented the `kubectl gs template nodepool` command so far because of that.

## Questions/discussion

- Should we decide to not offer `template nodepools` for Cluster API clusters? (-> PDR)

- If `template nodepools` is not available, how do CLI users simply create a node pool (manifest) with all possible configuration options? How do GitOps users extend their cluster app bundle ConfigMap?

- If we phase out the command, how to communicate this? (Starting when? Adapt usage text? Adapt docs page?)

## Tasks

- [x] Remove CAPZ support info from docs
- [x] Remove CAPZ support from the command

**Comment by alex-dabija** [comment]
KaaS Sync:
* `kubectl gs template nodepool` will not be maintained for Cluster API;
* Happa is going to edit the cluster's configmap for non gitops clusters. `kubectl gs` could do the same.

**Comment by vvondruska** [comment]
Notes from refinement:
- Check for which providers it should be supported
- Validate the value of `--provider` flag and show meaningful error messages for CAPI providers
- In the docs pages of kubectl-gs commands related to nodepools (`get nodepools`, `template nodepool`) make it clear that it is not supported for CAPI providers

**Comment by marians** [comment]
Just checked. Currently `--provider` only supports `aws` and `azure` vintage.

**Comment by marians** [comment]
Currently no customer is using CAPZ. We will remove the current CAPZ implementation for `kubectl gs template nodepool` and consider it a non-breaking change. Also we'll clean up docs.
