### ISSUE TITLE
Allow App Catalogs and Apps to be created at the same time with GitOps

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1189]
feedback from @LolloneS : 

Currently, sending a PR that:
- creates an App Catalog `X`
- installs an App from the App Catalog `X`

results in Flux not reconciliating because the dry-run for the operation is failing. This is reasonable, because we are trying to install an App from an App Catalog that does not exist yet.

Would it make sense to allow an App CR to complete a dry-run successfully even though it references a non-existing App Catalog? The pro I can see is that we rely more on eventual consistency, whereas I see the con as being some very slack tests. Maybe a common ground could be something like not running a dry-run on the App CR only when some label/annotation (e.g. `managed-by: flux`) is present?

From customer PoV:

```
I think it matters because it prevents someone from copying something like an existing config from London to DE. Doing so would break the deployment immediately, and the user wouldn’t realise
```

**Comment by gianfranco-l** [comment]
@piontec as agreed during planning, could you provide team perspective from opportunity/effort point of view?

**Comment by piontec** [comment]
Hey! This seems very low priority to me. Unless someone's doing very heavy catalog management, I don't really see a problem with 1 additional PR to kick off the catalog first. On the other side of things, it is very hard to provide this feature from technical side - in general, everything in kuberentes is only eventually consistent, so even submitting Catalog and App and the same time is not a solution, we would have to build something to achieve the consistency. So currently, I think this is a very minor limitation we have to live with.

**Comment by weatherhog** [comment]
closing this issue
