### ISSUE TITLE
`kubectl gs` commands should support `--context` flag

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1190]
The `kubectl gs template cluster` command, for some providers, relies on contact to a management cluster in order to retrieve details/defaults from the management API.

For example, for `--provider gcp`, there must be a GCP management cluster available.

In order to be able to run a kubectl-gs command without having to pre-select a context, we should make sure to support the `--context` flag to select a contect. Example:

```nohighlight
kubectl gs template cluster --context gs-foobar --provider gcp ...
```

**Comment by alex-dabija** [comment]
KaaS Sync:
* @marians is going to talk with @giantswarm/team-rainbow to see if it can be globally implemented for all commands.

**Comment by anvddriesch** [comment]
Done, related https://github.com/giantswarm/roadmap/issues/1230
