### ISSUE TITLE
Add deletion blocker operator in CAPVCD default apps

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#1193]
In reference to https://github.com/giantswarm/giantswarm/issues/22246

Same behavior observed with CAPVCD.

**Comment by erkanerol** [comment]
The app has been a part of the collection https://github.com/giantswarm/cloud-director-app-collection/blob/main/flux-manifests/deletion-blocker-operator.yaml

We fixed the config issue recently https://github.com/giantswarm/config/pull/1212

Testing now.

**Comment by erkanerol** [comment]
While testing, I noticed a small improvement in `cluster-cloud-director` to get a faster result from `deletion-blocker-operator`. Other than that, everything is fine.
