### ISSUE TITLE
Defaulting of App CR user-values properties

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#1195]
Currently in our vintage product, `cluster-operator` watches for `*-user-values` configmaps and secrets and if found will populate the `.spec.userConfig` properties with the relevant values. This makes it easy for our customers to override values by just creating a ConfigMap, such as how we describe in the [coredns configuration docs](https://github.com/giantswarm/area-oncall-scheduler/pull/57/files).

With the more to CAPI, this "defaulting" functionality is lost as we no longer use `cluster-operator`. I think having a standard named configmap that customers can use to provide their values is useful, and a wide-user feature so I'd like to see it in CAPI clusters also. Without the defaulting, customers will also need to update the App CR themselves - not a huge effort but does mean we need to update our docs and may cause some issue during upgrades from vintage to CAPI.

## Potential solutions:

1. Move the watch/defaulting logic that currently lives in `cluster-operator` instead into `app-operator` so that the same functionality continues without any change on the users side.
2. Pre-populate the "expected" resource names on the App CR and have `app-operator` ignore if not found. (treating it as though no values were provided). The [current code](https://github.com/giantswarm/app/blob/877fd0afacb4adebd6c4e588968fd975cb8edefc/pkg/values/configmap.go#L61-L76) would return an error if the resource wasn't found.
3. Build a new tiny operator that performs just this watch/defaulting functionality to be deployed onto CAPI clusters. (Seems overkill in my opinion)

The [RFC](https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#enhancing-app-cr) raised to enhance the config layering would also be effected by this issue if the `userConfig` value is replaced by `configs` (which it doesn't sound like is going to be the case in the first release at least).

/cc @uvegla

**Comment by piontec** [comment]
TBH, I didn't know such a functionality existed. I think it might be good to take it over in `app-operator`, but as a config option to control when it's enabled.

**Comment by AverageMarcus** [comment]
That works for me, so you think solution 1 is the best way to go? I do in this scenario but don't feel confident enough to say it would work for every case, especially with the proposed RFC changes.

If it is agreed this would be worth including in app-operator I'm happy to take a look and get a PR up.

**Comment by piontec** [comment]
@AverageMarcus, we have decided to keep the existing `config` and `userConfig` fields, so this can be 100% backward compatible: if `app-operator` sees a config map with a specific name based on App CR name (`app-uservconfig`), it can edit the relevant App CR's `userConfig` field.
Do we get it right, that you have some capacity to work on this:) ? Would be awesome :)

**Comment by piontec** [comment]
Perfect, let us know if you need any help :)

**Comment by AverageMarcus** [comment]
@piontec I wasn't 100% sure how best to tackle this with how the operator is structured, got my attempt in this PR here: https://github.com/giantswarm/app-operator/pull/1030 Would love your thoughts on it :)

**Comment by piontec** [comment]
I'm no app-op developer myself, but other honeybadgers will have look :)
