### ISSUE TITLE
add testing + metrics to deletion-blocker-operator

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1198]
add testing + metrics to deletion-blocker-operator

**Comment by gawertm** [comment]
@erkanerol do we still need this?

**Comment by erkanerol** [comment]
Yes. We haven't invested in this. On the other hand, I have to admit that it is not critical. I think we should do it when we need to touch that operator again.

**Comment by gawertm** [comment]
will be handled as part of bigger (operator) testing discussion
