### ISSUE TITLE
Create Azure Workload Clusters with a single PR using Flux

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#1199]
## User Story

- As a Platform Engineer, I would like to be able to create WCs on Azure using Flux by sending a single Pull Request to a Git repository, so that I don't need to create CRs one-by-one in a specific order and there is 1:1 correspondence between a PR and a Workload Cluster.

## Acceptance Criteria

- [ ] Given a PR creating a new Azure Workload Cluster (currently `Cluster`, `AzureCluster` and `AzureMachine` CRs), when I merge the PR in `main`, Flux running in the Management cluster should successfully create the Workload Cluster

**Comment by T-Kukawka** [comment]
@LolloneS can we close it? You  tested it that it works

**Comment by LolloneS** [comment]
@T-Kukawka this issue is for CAPZ. If we're sure about the single-PR-per-WC in CAPZ, I can close this :)

**Comment by T-Kukawka** [comment]
right, removing from Phoenix then

**Comment by T-Kukawka** [comment]
This should work on CAPZ, it is only issue for Vintage
