### ISSUE TITLE
Remove `write_all_group` keys from Dex configmap-values.patch.yaml files

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1206]
We still have `write_all_group` keys in some Dex configmap-values.patch.yaml files in the config repo. These should be removed, as it's rbac-operator handling this, not Dex.

**Comment by mogottsch** [comment]
I searched for `write_all_group` in all `configmap-values.yaml.patch` files that belong to `dex-app` in the [config repo](https://github.com/giantswarm/config). I found nothing. It seems like this was already fixed or do I miss something @anvddriesch?

For convenience: `grep -n write_all_group ./**/dex-app/configmap-values.yaml.patch`

**Comment by kuosandys** [comment]
I think this has already been done in this [PR](https://github.com/giantswarm/config/pull/1227), and there also seems to be a related issue https://github.com/giantswarm/giantswarm/issues/19735. If there's nothing remaining we could close this one and check off the task item in that issue as well, so we don't further confuse ourselves 😅

**Comment by mogottsch** [comment]
Oh yes, you are right. 
That issue also mentions another value
```
kubernetes:
  auth:
    tenantAdminTargetGroup: XXX 
```
That value is still used in some installations. However, I do not know if that should be removed as well.

**Comment by kuosandys** [comment]
> 

No we still currently use that, though refactoring/simplifying config is outside the scope of this issue. Thank you for looking into the dex app values!
