### ISSUE TITLE
CAPG proxy-only subnet

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1218]
## Story

_*-As a cluster admin, I want to have a proxy-only subnet for each cluster in the same region as the cluster in order to use external regional HTTP(s) or internal HTTP(s) load balancers.*_

## Background

A proxy-only subnet per VPC region is a requirement of GCP in order to use external regional HTTP(s) or internal HTTP(s) load balancers.
The documentation mentions that `--purpose` with the value `REGIONAL_MANAGED_PROXY` must be specified when creating such a subnet from the command line:
```
You can't reuse an existing subnet as the proxy-only subnet; you must create a new subnet in
each region that has an Envoy-based load balancer. This is in part because the subnets update
command doesn't allow modifying a subnet's --purpose field. For the proxy-only subnet,
the --purpose must be set to REGIONAL_MANAGED_PROXY.
```

## Requirements

- the proxy subnet has to be created in the same region as the cluster;
- the proxy subnet CIDR needs to be configurable via `values.yaml`;

## Implementation details

- add `proxySubnet.cidr` optional property to values.yaml;
- if the proxySubnet.cidr property is specified then an annotation will be set on the GCPCluster CR;
- a new operator will reconcile the GCPCluster CR and create a proxy subnet with the specified CIDR.

## Resources

- [GCP load balancing overview](https://cloud.google.com/load-balancing/docs/load-balancing-overview);
- [GCP proxy-only subnets](https://cloud.google.com/load-balancing/docs/proxy-only-subnets);

**Comment by fiunchinho** [comment]
There is a bug on `conversion-gen`, the tool CAPI uses to generate functions to convert types between api versions. The only workaround is to replace slices of pointers with slices of objects. [I've created an issue upstream](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/issues/701), but 
- it won't be an easy task
- it's probably a breaking changes, so I'm not sure about when it'd be released

**Comment by fiunchinho** [comment]
[The PR upstream to support specifying the purpose of the subnet](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/713) has been merged. Now we just need a release that contains the changes.

Now we have [this PR on `cluster-gcp`](https://github.com/giantswarm/cluster-gcp/pull/140) to configure the `proxy-only` subnet.
