### ISSUE TITLE
Replace "Client certificates" tab with "Access" tab in cluster details

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1219]
From [refinement](https://github.com/giantswarm/roadmap/issues/1192#issuecomment-1178767174).

The "Client certificates" tab in cluster details in the web UI currently doesn't display client certificates created via MAPI. We have a broader [issue](https://github.com/giantswarm/roadmap/issues/536) to make this possible some time in the future (current status: blocked).
<img width="1208" alt="Screen Shot 2022-07-08 at 13 32 50" src="https://user-images.githubusercontent.com/62935115/177984398-0ddfbd78-02bc-48ad-9eb2-dfb7a61c8adc.png">
 
Currently, this tab doesn't display any client certificates for many customers, and with the move towards CAPI, there will be even more customers who won't find any client certificates listed here.

We would like to replace this tab with an "Access" tab instead, in order to provide customers with useful information regarding how to access their workload cluster. We have also received feedback from a customer that they would navigate to the "Get started" guide for information regarding workload cluster access, so providing that information here feels like a better use of the space.

### Tasks:
- [ ] Spec for "Access" tab in cluster details in the web UI
- [ ] Replace "Client certificate" tab with "Access" tab in cluster details (web UI implementation)

**Comment by kuosandys** [comment]
After this is implemented, we should also think about removing/replacing the Client certificates widget in cluster details overview.

**Comment by marians** [comment]
With our decision to develop Backstage plugins as our web UI, we are not investing in bigger happa improvements like this one. Closing this issue.
