### ISSUE TITLE
Display instructions for configuring ingress in "Ingress" tab

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1220]
From [refinement](https://github.com/giantswarm/roadmap/issues/1192#issuecomment-1178767174).

Currently we only display instructions for configuring ingress after the user has installed our Ingress Controller app. We should instead display the information regardless of whether the app has been installed.

**Comment by marians** [comment]
Closing, as we minimize the effort we put into happa. @weatherhog
