### ISSUE TITLE
CAPA MC Bootstrap

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1223]
## Story
_*-As a Giant Swarm developer, I want the management clusters to be based on the Giant Swarm CAPI releases in order to easily get feedback on new features and to implement features only once.*_

## Background
Vintage Giant Swarm management cluster use a different setup than vintage Giant Swarm workload clusters. This lead to:
* always having to implement a feature 2 times, for management clusters and for workload clusters;
* different feature set between management clusters and workload clusters;

**Comment by calvix** [comment]
https://github.com/giantswarm/mc-bootstrap/pull/213
