### ISSUE TITLE
GCP opsctl ssh with allow lists

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1227]
## Story
_*-As a operations engineer, I want to have access to management and workload cluster nodes in order to provide proper support for these clusters.*_

## Background
On GCP, the bastion hosts have public IPs during phase 1. Of course, the bastion hosts should be protected by firewall rules.

The plan is to first jump to the VPN bastion hosts and from there to go through the bastion hosts of management / workload clusters.

## Changes
- [ ] Update `opsctl` to generate the ssh command line with the proper flags to jump through those 2 jumpboxes in order to access cluster nodes.

## Resources
- [OpenSSH documentation](https://man.openbsd.org/ssh). See: `-J` flag;

**Comment by calvix** [comment]
done, just waiting for an opsctl release - https://github.com/giantswarm/opsctl/pull/1518

**Comment by calvix** [comment]
`-J` was not used as its too basic to allow proper tooling
