### ISSUE TITLE
Use Cilium with CAPA

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1232]
## Story
_*-As a cluster admin, I want to use Cilium instead of `aws-cni` on Cluster API for AWS clusters in order to have a flexible Kubernetes network solution.*_

## Background
Cilium is currently used on:
- CAPG;
- CAPO;
- Vintage AWS management clusters;

The plan is to replace `aws-cni` with Cilium in the AWS v18.0.0 release for vintage workload clusters.

**Comment by calvix** [comment]
https://github.com/giantswarm/default-apps-aws/pull/34 to use cilium with CAPA, there might be still need for some cleaning up

**Comment by calvix** [comment]
done,
