### ISSUE TITLE
CAPG Bastion hosts allow lists

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1233]
## Story

_*-As a cluster admin, I want to have the Kubernetes API protected by allow lists in order to improve the security of clusters.*_

## Background

CAPG doesn't protect the Kubernetes API and it's currently exposed on the Internet. This, of course, is really bad for security and needs to be changed. Long-term we are going to have a VPN configured and the communication between management clusters and workload clusters is going to go over VPC endpoints.

We'll use allow lists, for now, in order to shorten the path to production.

## Requirements

- Access is restricted by default;
- Firewall rules to allow access only from specific IPs or CIDRs need to be configured for the Kubernetes API and bastions hosts of management clusters and workload clusters;
- Firewall rules must contain the specific port to which access is granted;
- The default list should include Giant Swarm's VPN endpoints;
- The customer needs to be able to configure the list of IPs or CIDRs (values.yml);
- Required access:
  * Kubernetes API (probably port 443, needs to be confirmed);

**Comment by mnitchev** [comment]
With the addition of giantswarm/capg-firewall-rule-operator#21this is done.
Tried it out on gohan manually too. Using regular ssh on the public IP of the bastion hosts works on already created clusters. However new clusters with cluster-gcp version  `0.17.0` only work with `opsctl ssh`.
