### ISSUE TITLE
Create `capa-app-collection` to separate app collection for CAPI and vintage AWS

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1236]
Create `capa-app-collection` to separate app collection for CAPI and vintage AWS.

**Comment by calvix** [comment]
app collection is created but I will still need to add a bunch of apps to it 
https://github.com/giantswarm/capa-app-collection

**Comment by calvix** [comment]
TODO - create list

[ ] capa-iam-operator
[ ] ....

**Comment by calvix** [comment]
the list is finished, if there is something we missing we can add ad-hoc, but this should be enough for now
