### ISSUE TITLE
SPIKE: Investigate cloudfront/private s3 bucket solution for IRSA in place of public bucket

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1237]
Based on AWS Public doc: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

**Comment by njuettner** [comment]
Cloudfront for IRSA is working, but needs some additional changes:

- New Cloudfront distribution needs to created per cluster, it auto generates a new domain name (e.g. d12amkbgptnl2n.cloudfront.net) this needs to put in different places
- New OIDC provider needs to get created with the new domain name 
- S3 Open ID configuration needs to be changed with this domain name 
- S3 Bucket policy needs restrict Cloudfront only
- API server flag `--service-account-issuer` has to be changed to Cloudfront (this means we need to roll all nodes again)

- Route53 Manager Role needs to be changed to the new issuer

Biggest issues: 
- The domain name will be autogenerated so we need to pass this information from irsa-operator to aws-operator a lot of code changes, probably needs to stored in a config map
- How to do the transition of exisiting clusters?
