### ISSUE TITLE
[Prometheus Remote Write] Write public documentation 

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#1238]

**Comment by QuentinBisson** [comment]
@mcbenjemaa feel free to reopen once you're back

**Comment by TheoBrigitte** [comment]
We might want to add a `kubecl explain` into the doc to describe how to get details on the RemoteWrite CR schema.

**Comment by QuentinBisson** [comment]
Bringing this to @giantswarm/sig-docs

**Comment by mcbenjemaa** [comment]
the doc looks good.

**Comment by Oshratn** [comment]
Has it been merged into public docs?

**Comment by QuentinBisson** [comment]
Yes it is here https://docs.giantswarm.io/advanced/prometheus-remotewrite/

First thing is: I'm wondering if we should not rename it like https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/ 

Then, how to explain how to setup the CR to configure the remote write ;)

**Comment by QuentinBisson** [comment]
Your input would be more than welcome @Oshratn :)

**Comment by Oshratn** [comment]
In general it looks good to me.
If you plan to add to it, I recommend adding a structure in a way similar to the New Relic document.

**Comment by QuentinBisson** [comment]
Easy improvements on the doc: https://github.com/giantswarm/docs/pull/1543

Let's share it with customers so we can get feedback
