### ISSUE TITLE
Automated app updates through "update-operator"

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#124]
User story: As an end user developer, I want to be able to specify how updated I want my app to be within certain major / minor boundaries and have the app be automatically updated according to those specifications.

We don't want to encourage this until configurations are safe. Currently, there is no migration path for configuration values.

**Comment by cokiengchiara** [comment]
@giantswarm/team-batman , @pipo02mix commented in Slack from customer,

"At the same time they spend time and resources in updating the managed apps. Ideally, we offer the same experience as clusters and we push and maintain those up to date. They would like to trust the versioning and allow upgrade apps automatically for minor and patches. There is a roadmap ticket #124 but not sure how far we are with this."

Now that we have more apps, would it be a good time to revisit?

**Comment by rossf7** [comment]
@cokiengchiara Yes, I think we should be aiming for the same experience as clusters. However this is a complex feature especially if we need to have maintenance windows etc.

I think an intermediate step could be to have a dashboard showing all optional apps that have an upgrade available. We could do this as part of https://github.com/giantswarm/roadmap/issues/322

We could add this quite easily to the metrics generated by app-exporter and use the AppCatalogEntry CRs to check if there is an upgrade.

**Comment by pipo02mix** [comment]
That would be awesome so we can track customer apps in a board and ask them to update old versions or perform he updates for them

**Comment by piontec** [comment]
And for the auto-upgrades themselves: I think we can't really do that before we have automated upgrade testing. Otherwise it's going to unleash hell on us.

**Comment by othylmann** [comment]
I agree with @pipo02mix and there is a ticket for this: #322 - I would actually put this on a backlog somewhere further in the back and mark it as not to be done now.

**Comment by gianfranco-l** [comment]
closed in favor of https://github.com/giantswarm/giantswarm/issues/20641
