### ISSUE TITLE
Display cluster app version and details

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1246]
- Release panel can not be named "release" anymore
- For now, we can not display available updates (no spec for this needed rn)
- Display kubernetes version
- Display kubernetes EOL info
- If the cluster has a cluster app, we display the version
- If possible, get information from actual CRs
- Focus on desired state (cr spec) for version
- Compare desired state (cr spec) and current state (cr status) for cluster transitions/status
- Right now we don't see value in including default apps version

Tasks:
- [x] display cluster app and Kubernetes version in cluster list (homepage) and cluster details overview
- [ ] display oldest/newest release/cluster app version in Organizations details

**Comment by marians** [comment]
Current release info in cluster list:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/273727/179517807-7ec5b154-9352-4f13-8e4b-da1db89423f9.png">

We can keep this as is, and show the cluster app version in the same place where currently the release version is shown.

Current release panel:

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/273727/179517583-63e1f85c-8104-4f18-8a77-45fca8ac085e.png">

- Replace panel label `RELEASE` with `VERSIONS`
- Between the version-tag icon and the version number, add the label `Cluster app`
- Replace the link to opening a modal with a link to the cluster-app's release notes, e. g. https://github.com/giantswarm/cluster-gcp/releases/tag/v0.16.0 (in a new tab)
- Between the Kubernetes logo icon and the version number, add the label `Kubernetes`

**Comment by kuosandys** [comment]
We currently also display some summary statistics about releases in the Organizations overview page:
<img width="380" alt="Screen Shot 2022-08-08 at 14 26 29" src="https://user-images.githubusercontent.com/62935115/183417781-6d5d2858-8143-40c2-a459-500535cd685e.png">
This would have to also be adapted for clusters created from cluster apps (i.e. not using releases).

@marians Would the following be a suitable replacement for the 'Releases' section?
<img width="380" alt="Screen Shot 2022-08-08 at 14 27 20" src="https://user-images.githubusercontent.com/62935115/183417753-41ed65d2-a6af-462f-80a6-53363c38519e.png">
