### ISSUE TITLE
Custom AWS resolver rules

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1249]
## Story
_*-As a cluster admin, I want to configure custom AWS resolver rules in order to resolve domain names to hosts / servers that are accessed during cluster creation.*_

## Background
Some customers use a plain proxy to filter traffic which needs to be configured and used by any component which requires external communication. Also, in such situation the proxy domain name is configured in a private DNS server.

The proxy domain name needs to be resolvable durring cluster creation because otherwise:
* container images can't be pulled;
* app catalogs are not available.

## Requirements
- a list of extra custom resolver rules must be configurable via `values.yml` for each cluster (workload, management cluster);

## Resources
- [AWS resolver rules](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resolver-rules-managing.html);

**Comment by calvix** [comment]
feature merged, we will need to enable this on the necessary MC
