### ISSUE TITLE
How should the "Inspect releases" use case be adapted for cluster apps

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1250]
Initial thoughts: we can extend the use case to include both releases and cluster apps

**Comment by marians** [comment]
For context:

![image](https://user-images.githubusercontent.com/273727/184320589-96622029-8b11-47a0-91c4-f44009db46a0.png)

Notes from refinement:

- With CAPI, releases don't exist, so we don't have to display the Releases row item.
- No replacement needed. The assumption is that cluster apps and cluster default apps are available as app catalog items in a public namespace.

TODO: check whether ACEs are in the default namespace now. If not, follow up with Hydra.

**Comment by kuosandys** [comment]
The UI changes have already been implemented, and we have a [separate issue](https://github.com/giantswarm/giantswarm/issues/23740) to track the TODO from above
