### ISSUE TITLE
Upstream Flatcar image-builder issues

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#1264]
* https://github.com/kubernetes-sigs/image-builder/pull/907 - depending on the CI OpenSSH version we might not be able to build the image because of SSH issues
* https://github.com/kubernetes-sigs/image-builder/issues/937 - without this we need to do image post-processing as described in the issue
* https://github.com/kubernetes-sigs/image-builder/issues/939 - when this is fixed we can remove [this](https://github.com/giantswarm/cluster-openstack/pull/85/files#diff-5d5883ddf8c1c53c57998dd4e264ba16884f7052542e6aaac0b5764c644985a7R15-R27)

**Comment by gawertm** [comment]
only relevant for Openstack

**Comment by gawertm** [comment]
lets see if we hit same issue when using image builder for capvcd
