### ISSUE TITLE
Display cluster app status in collapsed view

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#1266]
App item UI in a collapsed state should display an indicator for a status other than "deployed".

App item collapsed:

![App bundle details expanded](https://user-images.githubusercontent.com/273727/179733394-552d4af1-e971-496b-914b-b6641accc5fd.png)

App item expanded:

![App details expanded](https://user-images.githubusercontent.com/273727/179733449-0cd9e8a3-2a7c-46dc-9a10-876f7740b660.png)

Figma prototype is [here](https://www.figma.com/file/MZsHQqUHAn3WPRRvsOH8t2/Happa-Cluster-API-apps?node-id=0%3A1).

**Comment by gusevda** [comment]
@uvegla, @piontec I'm working on the implementation for this ticket, and I want to know your thoughts on these questions:
- is it useful to have other colors for some other statuses? Green for 'deployed' for example, or yellow for some 'pending' statuses. Current idea is to display all statuses as red except the 'deployed' status.
- is it better to display more human readable texts for some statuses or is it better to display them as is? For example: 'pending-install' => 'Installation is pending', 'pending-upgrade' => 'Upgrade is pending', 'pending-rollback' => 'Rollback is pending'.

Plain -> Sentence case capitalization -> Interpreted texts
![statuses](https://user-images.githubusercontent.com/445309/181007431-f7185ef4-6db8-4fbd-84aa-a8191a4fb129.png)


btw, is it the full list of all possible statuses an application can have?

**Comment by piontec** [comment]
I like the idea of "more colors" - "uninstalled" or "pending upgrade" should be red (IMHO 1st one should be something like gray, 2nd one yellow). As for text... the shorter is better, I like the middle column the best

**Comment by gusevda** [comment]
@piontec thanks for the feedback. When you say 1st one and 2nd one - do you mean from the original list? So the `Unknown` is gray and `Deployed` is yellow.

**Comment by piontec** [comment]
I mean from the "uninstalled" and "pending something" pair, "Deployed" should be green to me.

**Comment by uvegla** [comment]
In case it is still relevant, my 5 cent is that `uninstalling` and `uninstalled` is not a bad thing so I would not use red for them. Maybe yellow for the first one - as it is on progress - and grey for the latter.

I am on the edge with `superseeded` to make it yellow as well but I am not sure what we mean by that status. In case it is a bad thing that needs GS / customer attention, only then I would keep it red.

**Comment by gusevda** [comment]
How does it look?

<img width="179" alt="Screenshot 2022-08-01 at 12 59 52" src="https://user-images.githubusercontent.com/445309/182124377-8424a7dd-22e7-46a9-883e-50e017731499.png">

**Comment by piontec** [comment]
I like it. Just 1 minor thing: 'Unknown' and 'Uninstalled' - should they look the same? 'Unknown' is kind of "bad" status for me - how a status can be unknown? Maybe it should be... some other color?
