### ISSUE TITLE
App priority at Cluster Creation - High prio for Cillium

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1268]
Problem phoenix is facing: most applications' helm charts are developed assuming they will be installed on a 100% healthy cluster. Since we decided to install foundational components (CNI among others) of a cluster as a managed app as well, the cluster that kaas providers deploy is not fully functional. If the CNI app is not installed as the very first application, other apps likely will fail to install. If those apps have pre-install hooks that require a working CNI, the installation process gets stuck and delays installation of all other apps for several minutes. Sometimes for 30+ minutes. We need a way to at the very least mark some apps as "high priority" and ensure those are installed first.

Honeybadger is working on a dependencies solution that will cover installing cillium as one of first apps.

**Comment by T-Kukawka** [comment]
https://github.com/giantswarm/giantswarm/issues/22963

**Comment by whites11** [comment]
maybe we can close this thanks to app dependencies?

**Comment by T-Kukawka** [comment]
yep yep
