### ISSUE TITLE
Reduce IAM permissions scope for AWS operator role

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#127]
**Is your feature request related to a problem? Please describe.**

In the current standing, the AWS operator policy is too broad. Some of our customers have independent accounts for Giant Swarm but some not. As an example, we have full rights for S3 (`"s3:*"`). Also, as today is possible the operator to create any policy, attach to a role and assume it. Which indeed give you full admin rights into the accounts, and in case they are peering VPC from different accounts they are vulnerable.  

**Describe the solution you'd like**

There are three measures we can do
- Limit action of service (instead of wildcard use only actions we need `"s3:*"` -> `"s3:GetObject"`)
- Restrict resources (instead of `"Resource": "*"` -> `"arn:aws:iam::<CUSTOMER_ACCOUNT_ID>:role/*-EC2-K8S-Role"`)
- Add conditions. Here will be useful specially for IAM itself
Example
```
"Statement": {
    "Effect": "Allow",
    "Action": [
      "iam:AttachRolePolicy"
    ],
    "Resource": [
      "arn:aws:iam::<CUSTOMER_ACCOUNT_ID>:role/gs-*"
    ],
    "Condition": {"ArnLike": 
      {"iam:PolicyARN": "<CUSTOMER_ACCOUNT_ID>:policy/GiantSwarmAdminPolicy"}
    }
  }
```

For some services, like EC2 or Cloud Formation, is fine to have a wildcard but others need to be reviewed

- [ ] autoscaling:*
- [ ] cloudwatch:*
- [ ] elasticloadbalancing:*
- [ ] events:*
- [ ] kms:*
- [ ] logs:*
- [ ] route53:*
- [ ] route53domains:*
- [ ] s3:*

Tight with conditions 
- [ ] sts:AssumeRole
- [ ] iam:AttachRolePolicy
- [ ] iam:CreatePolicy
- [ ] iam:CreateRole
- [ ] iam:DeletePolicy
- [ ] iam:DeleteRole
- [ ] iam:DeleteRolePolicy
- [ ] iam:PassRole

**Describe alternatives you've considered**

No other alternatives considered

**Comment by puja108** [comment]
We get requests for this restriction of our access rights a lot in talks with potential customers or when existing customers onboard new projects and security or here rather data privacy is involved. This also applies to the IAM role that we require for Giant Swarm Operations staff.

As we separate Control Plane account and the accounts that Tenant Clusters are in and recommend to have nothing else in the CP account, this is more important for the roles we use in the TC accounts.

**Comment by puja108** [comment]
A concrete issue a potential customer mentioned is that they keep privacy/GDPR relevant customer data in S3 and cannot allow a third party like us to have access to those.

**Comment by alex-dabija** [comment]
This will probably never be implemented given our current push to Cluster API for AWS.
