### ISSUE TITLE
Fix IP subnet overlapping during pivot

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#1271]
When running mc-bootstrap for CAPVCD, the controller tries to create a load balancer when one already exists, causing it to hang forever. The following error is logged by the CAPVCD controller:

`Overlapping subnets detected for existing virtual service virtual IP address 178.170.32.23 and 178.170.32.23`

The manual workaround is to add the IP of the Kube API to the newly created LB Pool, then delete the existing virtual service so it can be recreated on the new pool.

---

Load balancer pools and virtual services are named using the InfraID field that is stored in the status section of the VCDCluster CR. During the clusterctl move operation, the ID is not carried over and a new one is generated. Meaning the controller creates a new load balancer pool with that ID and tries to create a new virtual service with the same IP (stored in spec>controlPlaneEndpoint) and fails because it is already in use by the existing virtual service.

We need a way for the CAPVCD controller in the target cluster to know that a Pool/virtual service already exist.

@bavarianbidi pointed out that CAPO achieves this by looking for an existing LB or creating a new if there's none: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/96ee54aab679d8403eef04c0f87e0dde36098e57/pkg/cloud/services/loadbalancer/loadbalancer.go#L77-L80

---

Upstream issue: https://github.com/vmware/cluster-api-provider-cloud-director/issues/211

**Comment by glitchcrab** [comment]
blocked by https://github.com/vmware/cluster-api-provider-cloud-director/issues/211

**Comment by vxav** [comment]
Upstream maintainers don't really want to implement that fix. It is apparently not a problem with the API schema extension (we currently don't have it in Ikoula). They plan on making it a mandatory requirement as it adds value for tracking, troubleshooting...
Next step is to ask Ikoula to [extend the API schema](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/docs/VCD_SETUP.md#register-cluster-api-schema)

**Comment by vxav** [comment]
The workaround works. To make clusterctl move work so the target cluster doesn't create a new ID, set the RdeID field in the cluster values file. Example `NO_RDE_11111111-2222-3333-4444-5555666666`
The ID part must be hexadecimal only.

**Comment by erkanerol** [comment]
@vxav does the value have to be unique per cluster? How will we set it for WCs?

**Comment by vxav** [comment]
Yes, unique per cluster.

Set in https://github.com/giantswarm/cluster-cloud-director/blob/main/helm/cluster-cloud-director/values.yaml#L27

**Comment by erkanerol** [comment]
> The ID part must be hexadecimal only.

What does this exactly mean? Can you give an example that is not working?

If we don't care value of this parameter and if it has to be unique per cluster, is there a way to build this field based on cluster name? If necessary, we can use some hash functions for the input format.

**Comment by vxav** [comment]
This is a workaround, the end goal is that all VCD environments using CAPVCD will have the [API schema extension](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/docs/VCD_SETUP.md#register-cluster-api-schema) registered, in which case the issue doesn't exist.

Perhaps we can create the ID by using that same syntaxe and changing the ID part so it works in both scenarios.

**Comment by vxav** [comment]
The maintainers are looking for a better way to handle this and avoid manually setting NO_RDE ID, which would be ideal and simpler. Re-opening to follow this.

**Comment by vxav** [comment]
https://github.com/giantswarm/cluster-cloud-director/pull/22
