### ISSUE TITLE
Display "Preinstalled Apps" the same way as "Installed Apps" in Happa

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#1277]

**Comment by gusevda** [comment]
If we decide to go with this approach - to use the same component for preinstalled apps as we use for user installed apps, we would need to change this box so it makes more sense for the preinstalled apps list. It's being shown during cluster creation. @marians  Could you work on a spec for it?

![Image](https://user-images.githubusercontent.com/445309/183450052-e68289df-a941-4e2e-9353-4893413a0a5c.png)

**Comment by marians** [comment]
During cluster creation, both the list of installed apps and default apps / preinstalled apps should inform that the list is still incomplete during creation of the cluster. I would change headline and body text accordingly:

Headline: **The cluster is currently being created**

Text: Apps will be displayed here once the cluster is ready.

**Comment by gusevda** [comment]
@marians I suggest not to look into a cluster's `isCreating` status to display this message. A cluster has it for a while after being created (~15 mins).

For user installed apps I suggested to keep the same message that we display right now - **No apps installed on this cluster**. The `Install app` button is available and a user can install an app right after a cluster is created.

For preinstalled apps - let's display **The cluster is currently being created** only until apps appear - it takes 3-5 mins. Not during the whole period the cluster has `isCreating` status.

Is it ok?

**Comment by gusevda** [comment]
Right after a cluster is created:
<img width="1205" alt="Screenshot 2022-08-16 at 10 32 58" src="https://user-images.githubusercontent.com/445309/184823722-d88327fc-6c41-4369-afae-0b6e595f24d3.png">

Cluster creation is still in progress, but one app is installed by a user:
<img width="1205" alt="Screenshot 2022-08-16 at 10 34 18" src="https://user-images.githubusercontent.com/445309/184823896-e28f14ed-e279-42fd-a3ea-bbeeff513864.png">
