### ISSUE TITLE
Enable access to Control Plane API via internal communication

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#128]
**Is your feature request related to a problem? Please describe.**

Enable access to Control Plane Cluster API via internal communication.

Recently we have implemented whitelisting in our Control Plane API and customers that desire to access via transit VPC or TGW need this.

**Describe the solution you'd like**

The steps will be:

1. It needs to have a separate domain as we did in tenant clusters (e.g. internal-g8s)
2. PKI needs to be adjusted to allow this domain
3. Dex needs to be adjusted to allow domain configuration

**Describe alternatives you've considered**

An alternative exists and it is IP whitelisting. 

**Additional context**

**Comment by corest** [comment]
Did the customer approve it works? @pipo02mix

**Comment by corest** [comment]
Closing as I think it works
