### ISSUE TITLE
CAPG subnet creation with custom node CIDR

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1284]
## Story

_*-As a cluster admin, I want to create a CAPG cluster with a custom node CIDR without providing an existing subnet in order to have an improved user experience.*_

## Background

CAPG allows for the CIDR to be configured only by allowing an existing subnet to be specified. The user has to ensure that the subnet exists before the cluster can be created.

CAPA has the same issue and we implemented a custom operator to create the subnets to ensure that they exist before creating the cluster.

## Outcome

Given a node CIDR configurable via the `values.yaml` file, a new cluster is created with a new subnet which has the specified node CIDR.

## Resources

- [CAPG cluster definition](https://github.com/giantswarm/cluster-gcp);
- [CAPG cluster definition values schema](https://github.com/giantswarm/cluster-gcp/blob/main/helm/cluster-gcp/values.schema.json);

**Comment by fiunchinho** [comment]
PR upstream https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/677

**Comment by fiunchinho** [comment]
PR to our cluster app https://github.com/giantswarm/cluster-gcp/pull/123

**Comment by fiunchinho** [comment]
We have decided to use a custom image for capg instead of waiting for upstream to release.

**Comment by fiunchinho** [comment]
The custom image has been deployed to all our gcp installations.

**Comment by fiunchinho** [comment]
`cluster-gcp` v.0.25.0 has been released. When the customer uses this version, the subnet will be created. Do you want to close this one @alex-dabija or should we wait until we can use an upstream release?

**Comment by alex-dabija** [comment]
We can close this one. I created a [separate issue](https://github.com/giantswarm/roadmap/issues/1338) to track the progress on the upstream PR.
