### ISSUE TITLE
chart tests weirdly failing on dex-app (seems to be a problem with pytest command call, not actual app configuration)

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#1286]

**Comment by mogottsch** [comment]
[Here](https://app.circleci.com/jobs/github/giantswarm/dex-app/2028?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) is the failing pipeline.
To run tests locally use [app-build-suite](https://github.com/giantswarm/app-build-suite) and [app-test-suite](https://github.com/giantswarm/app-test-suite).

**Comment by mogottsch** [comment]
[Slack discussion](https://gigantic.slack.com/archives/CRZN9GLJW/p1665734029582059)
