### ISSUE TITLE
Enable Ephemeral Containers (k8s 1.23x beta feature)

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1287]
As a customer i would like to have Ephemeral Containers feature enabled for k8s 1.23 release for troubleshooting improvements.

Official doc: https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/

**Comment by T-Kukawka** [comment]
cc @alex-dabija putting to hydra as well  to check the flags

**Comment by whites11** [comment]
```
If you are using Kubernetes 1.23 or newer, ephemeral containers are enabled by default, so you can skip to the next section.
```

So I assume we don't need to do anything

**Comment by T-Kukawka** [comment]
My bad - true that - closing then 👍
