### ISSUE TITLE
First CAPA test management cluster

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1288]
## Story

_*-As a developer, I want to have a CAPA test management cluster in order to test new features, recent changes and upgrades.*_

## Background

We recently decided to base the management clusters on CAPA instead of the vintage configuration based on Terraform.
The Vintage management clusters have been used to test Cluster API on AWS until recently.

## Requirements

Have a running test management cluster with the default CAPA configuration.

## Outcome

- `opsctl ssh` works to access managemnt cluster machines;
- `kubectl get nodes` works to list the cluster nodes;
- all pods running on the management cluster are healthy.

**Comment by calvix** [comment]
TODO list:
[ ] make OIDC work
[ ]  make `opsctl ssh` work
[ ] ensure all services are working on MC

**Comment by calvix** [comment]
done
