### ISSUE TITLE
Kubernets API private loadbalancer

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1289]
## Story

_*-As a cluster admin, I want to the Kubernetes API loadbalancer to be configurable as private in order to improve the security and privacy of clusters.*_

## Background

Some customers requested support for private clusters as an alternative. One of the first things which needs to be done is to create a private loadbalancer instead of a public one.

CAPA clusters have a public loadbalancer created by default.

## Requirements

- the option to use a private or a public loadbalancer for the Kubernetes API needs to be configurable in the `values.yml` file.

## Outcome

- [ ] test management clusters are configured to use a private loadbalancer;
- [ ] `opsctl ssh` works to access clusters nodes from our development machines;
- [ ] `kubectl get nodes' works to list cluster nodes from our development machines;
- [ ] all pods running on the test management clusters are healthy.

**Comment by AverageMarcus** [comment]
From discussion yesterday:

The Helm chart will expose two values to control if a cluster has public or private resources:

* `.network.vpcMode` - Set to `public` (default) will let CAPA set up infra as normal. Set to `private` then our operator takes over and creates a fully private VPC setup.
* `.network.apiMode` - This replaces `.controlPlane.apiLoadbalancerScheme` and controls if the API load balancer is exposed to the internet or not. (`public` = exposed, `private` = internal only)

Validation is also added to ensure that only valid combinations of these two properties are provided. e.g. you can't have public API with private VPC.

**Comment by AverageMarcus** [comment]
Still to do (blocked on https://github.com/giantswarm/roadmap/issues/1355):

- [ ] If `.network.vpcMode` is set to private then the pause annotation needs adding to the cluster
- [ ] The `aws-vpc-operator` then needs to perform the VPC (and other resource) creation and update the `Cluster` and `AWSCluster` as needed. Finally removing the pause annotations

**Comment by alex-dabija** [comment]
This is done. The private clusters are created with a private load balancer for the API.
