### ISSUE TITLE
Display all components running in a AWS cluster in Happa

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#129]
**Is your feature request related to a problem? Please describe.**

There are several components shown in the Giant Swarm API but missed in the UI.

**Describe the solution you'd like**

Include these components:

- [ ] cert manager
- [ ] kiam
- [ ] external DNS

Consider separating cluster characteristics like RBAC or CoreOS from Managed Apps or Components like Cluster Autoscaler or CoreDNS.

**Comment by cokiengchiara** [comment]
@pipo02mix check if it is fixed now. If there's a bug, then Oli will check.
@oponder will take a look why they are not showing up.

**Comment by cokiengchiara** [comment]
This is fixed.
