### ISSUE TITLE
Kubernetes API default firewall rules

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1293]
## Stories

_*-As a Giant Swarm operations engineer, I want connections to be allowed by default from the Giant Swarm VPN exit endpoints to the CAPG Kubernetes API for management and workload clusters in order to do support for CAPG clusters.*_

_*-As a cluster admin, I want connections to be allowed by default from the CAPG management cluster to the CAPG workload cluster's Kubernetes API in order to manage and monitor workload clusters.*_

_*-As a cluster admin, I want to have a default firewall rule with the lowest priority to drop all network traffic in order to have a secure cluster out of the box.*_

## Background

The Giant Swarm CAPG provider has support to configure firewall rules for, but the Giant Swarm VPN exit points and the management cluster's NAT gateway have to be specified for each workload and management cluster in the `values.yml` files. This makes the creation of new clusters cumbersome and error prone. It also allows the customer to modify and overwrite by mistake some of the firewall rules which are critical for Giant Swarm to support and monitor the clusters.

## Requirements

- traffic to the workload cluster's Kubernetes API (destination port 443) must be allowed from the management cluster. All clusters have a NAT gateway its public IP(s) need to be allowed;
- traffic to the workload cluster's Kubernetes API (destination port 443) must be allowed from Giant Swarm's VPN exit endpoints on the Internet. The VPN endpoints' public IP(s) be allowed;
- all other traffic must be blocked by default. This rule must have the lowest priority.

## Outcome

A new cluster will have 3 firewall rules configured if no other rules are configured for the Kubernetes API loadbalancer. See previous requirements section for their exact behavior.

Any additional firewall rules configure in `values.yml`, if there are any, will be present besides the default rules.

### Checks
- [x] traffic is allowed from the management cluster;
- [x] traffic is allowed from the VPN endpoints;
- [x] all other traffic is dropped by default;
- [x] any extra firewall rules have higher priority then the default block everything rule;
- [x] `opsctl login` works for management clusters;
- [x] `opsctl login` works for workload clusters;
- [x] `kubectl-gs get nodes` lists all nodes.

## Resources

- [Cloud NAT](https://cloud.google.com/nat/docs/overview);
- [Giant Swarm VPN](https://github.com/giantswarm/vpn/).

**Comment by mnitchev** [comment]
This is done with [v0.5.1](https://github.com/giantswarm/capg-firewall-rule-operator/releases/tag/v0.5.1) release of `capg-firewall-rule-operator`
