### ISSUE TITLE
Bastion hosts default firewall rules

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1294]
## Stories

_*-As a Giant Swarm operations engineer, I want connections to be allowed by default from the Giant Swarm VPN exit endpoints to the CAPG bastion hosts of management and workload clusters in order to do support for CAPG clusters.*_

_*-As a cluster admin, I want to have a default firewall rule with the lowest priority to drop all network traffic to the workload and management cluster's bastion hosts in order to have a secure configuration out of the box.*_

## Background

The Giant Swarm CAPG provider has support to configure firewall rules for, but the Giant Swarm VPN exit points have to be specified for each workload and management cluster in the `values.yml` files. This makes the creation of new clusters cumbersome and error prone. It also allows the customer to modify and overwrite by mistake some of the firewall rules which are critical for Giant Swarm to support and monitor the clusters.

## Requirements

- SSH traffic to the management and workload cluster's bastion hosts (destination port 22) must be allowed from Giant Swarm's VPN exit endpoints on the Internet. The VPN endpoints' public IP(s) must be allowed;
- all other traffic must be blocked by default.

## Outcome

A new cluster will have 2 firewall rules configured if no other rules are configured for bastion hosts. See previous requirements section for their exact behavior.
The additional firewall rules, if there are any, will be present besides the default rules.

Any additional firewall rules configure in `values.yml`, if there are any, will be present besides the default rules.

### Checks
- [ ] traffic is allowed from the management cluster;
- [ ] traffic is allowed from the VPN endpoints;
- [ ] all other traffic is dropped by default;
- [ ] any extra firewall rules have higher priority then the default block everything rule;
- [ ] `opsctl login` works for management clusters;
- [ ] `opsctl login` works for workload clusters;
- [ ] `kubectl-gs get nodes` lists all nodes.

## Resources

- [VPC firewall rules](https://cloud.google.com/vpc/docs/firewalls);
- [Giant Swarm VPN](https://github.com/giantswarm/vpn/);

**Comment by mnitchev** [comment]
This is done with [v0.5.1](https://github.com/giantswarm/capg-firewall-rule-operator/releases/tag/v0.5.1) release of `capg-firewall-rule-operator`
