### ISSUE TITLE
Display node pool details

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1299]
Display:
- [ ] description
- [ ] instance type
- [ ] desired
- [ ] current

Hide:
- [ ] scaling
- [ ] cgroups version

**Comment by kuosandys** [comment]
How is scaling range defined/configured for cluster apps?
How can we determine which cgroups version is active in the node pool?

**Comment by alex-dabija** [comment]
> How is scaling range defined/configured for cluster apps?

CAPG clusters don't use machine pools (node pools). Instead the concept used is a [machine deployment](https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine-deployment.html) which is similar in a way to a machine pools.

At the moment, the size of a machine deployment is fixed and set as a [property](https://github.com/giantswarm/cluster-gcp/blob/a295a3c3b22edf3c0b73fe1a1aafcfd1c6078493/helm/cluster-gcp/values.yaml#L56) in the Helm chart. This value ends up in the [MachineDeployment CR](https://github.com/giantswarm/cluster-gcp/blob/a295a3c3b22edf3c0b73fe1a1aafcfd1c6078493/helm/cluster-gcp/templates/_machine_deployments.tpl#L17). As a consequence, **cluster autoscaling is not supported** for GCP clusters.

> How can we determine which cgroups version is active in the node pool?

Unfortunately, there isn't a way to identify which version of cgroups is being used on CAPG clusters like we have on AWS vintage. The plan is to support just cgroups v2 with CAPI.

While looking into this to provide an answer, we noticed that on Ubuntu both versions of cgroups are enabled which is very confusing. See [Slack thread](https://gigantic.slack.com/archives/C03LV8E0RL7/p1660729757116149). I'll come back with an answer as soon as have one.

**Comment by alex-dabija** [comment]
`cgroups v1` are the default on Ubuntu 20.04. As, I mentioned previously, CAPI clusters will only support `cgroups v2` in order to avoid any migration. We'll also switch as soon as the time allows to Ubuntu 22.04 as the OS for CAPG clusters to have have `cgroups v2` enabled by default (see [Github issue](https://github.com/giantswarm/roadmap/issues/1324)).

**Comment by kuosandys** [comment]
Thanks for the response @alex-dabija !

As discussed with Team Rainbow [on Slack](https://gigantic.slack.com/archives/C02FJACQ3D4/p1660814652358779), we will modify the display of node pools to provide the most useful information for our users:
- the MIN/MAX columns for scaling will be hidden for now on GCP
- the cgroups column will be hidden for CAPI clusters
