### ISSUE TITLE
Cluster creation without organization label must fail

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1300]
## Story

_*-As a cluster admin, I want the cluster creation to fail if there isn't an organization label specified instead of using a default in order to reduce the risk of an invalid configuration which could lead to other errors.*_

## Background

A default organization label is used by `cluster-gcp` if the user doesn't provide one. The default value already led to the having an invalid configuration for a few management clusters.

## Requirements

- an error must be returned (displayed) in case a value is not provided for the organization label `cluster-gcp`.

**Comment by fiunchinho** [comment]
Done here https://github.com/giantswarm/cluster-gcp/pull/131
