### ISSUE TITLE
Align IAM roles naming 

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#131]
**Is your feature request related to a problem? Please describe.**

Giant Swarm needs two roles in customer AWS account to work successfully. One for the automation (`aws-operator`) and one for operations (`Admin staff`). Both roles have consistent naming and are well explained in the [guide for preparing the AWS account](https://docs.giantswarm.io/guides/prepare-aws-account-for-tenant-clusters/).

But AWS operator at the same time needs to create some roles for the workers or components in the cluster to be able to talk with AWS API. Currently, we have

```
<cluster_id>-master-EC2-K8S-Role
<cluster_id>-Route53Manager-Role
<cluster_id>-IAMManager-Role
<cluster_id>-gs-cluster-role-<node_pool_id>
```

For the customer is hard to use a wildcard to whitelist Giant Swarm roles and the naming is not clear.

**Describe the solution you'd like**

Giant swarm has written down [a new AWS Role name convention](https://github.com/giantswarm/fmt/pull/105) to have a coherent format. Now all roles will be prefixed with `gs-` and will have a clear structure.

But for the transition period, Giant Swarm will ensure to use old and new names until all customers have moved to the new convention

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-dabija** [comment]
This will probably never be implemented given our current push to Cluster API for AWS.
