### ISSUE TITLE
Differentiate a management cluster in the web UI

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1310]
In CAPI, the management cluster will appear in the list of clusters for organization `giantswarm`. We want this item to appear different than workload clusters, so users avoid treating them as WC by mistake.

## TODO

-  [ ] UI spec

**Comment by marians** [comment]
Status update: we decided that we want to hide management clusters in happa first, before we adapt happa to display them in the appropriate way and hide specific functionality.

**Comment by weatherhog** [comment]
closing
