### ISSUE TITLE
Make `external-dns` work with GCP workload identity

### ISSUE THREAD

**Issue by fiunchinho** [giantswarm/roadmap#1313]
We don't want `external-dns` to rely on the service account assigned to the worker nodes, or change the app to load credentials from a secret on GCP. We can use workload identity.

**Comment by alex-dabija** [comment]
Blocked by https://github.com/giantswarm/giantswarm/issues/23333 .

**Comment by fiunchinho** [comment]
[I've created this PR](https://github.com/giantswarm/cluster-apps-operator/pull/258) so that the `gcpProject` is passed to all apps installed on the cluster.
[We also have this PR on the `external-dns`](https://github.com/giantswarm/external-dns-app/pull/181) app to expose the values required for workload identity.

Once both PR's are merged, we can change [our `default-apps-gcp` app](https://github.com/giantswarm/default-apps-gcp) to pass the values to the app. I was thinking that we could get rid of [the dynamic creation of configmaps/secrets in there](https://github.com/giantswarm/default-apps-gcp/blob/main/helm/default-apps-gcp/templates/apps.yaml#L54-L81), and just create the configmaps for the apps that require it. We would loop through the `Apps` to be created, but below that we'd have the definition of the required `ConfigMaps`, like a `ConfigMap` for `cilium`, another one for `external-dns`, etc. This would allow us to pass the required values to `external-dns-app` for workload identity, like the service account name, and `$gcpProject` would be available because it will be available to all apps once the above PR is merged.

**Comment by mnitchev** [comment]
Released in [external-dns-app v2.16.0](https://github.com/giantswarm/external-dns-app/releases/tag/v2.16.0)
