### ISSUE TITLE
Managed External DNS

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#132]
**Is your feature request related to a problem? Please describe.**

Some customers would like to use external DNS as managed service. Currently, Giant Swarm already runs this [component](https://github.com/giantswarm/external-dns-app) for cluster DNS configuration.

Thanks to this component customer can automatically create records on Route 53 when an Ingress or Service resource is created.

**Describe the solution you'd like**

Study to open the component to be used for the customer. Show it in the UI list and allow extra configuration.

Consider allow these options:
```
  `--aws-prefer-cname` No create record A (CNAME is easier to manage)
  `--aws-batch-change-size=1000` Number of records can be changed at once
  `--interval=5m` (avoid hammer API)
  `--domain-filter` composable
```

**Describe alternatives you've considered**

In case it is dangerous for the cluster integrity to allow customer to run its own version.

**Additional context**

---

Pasting info from duplicate ticket.

**Is your feature request related to a problem? Please describe.**
Customer want to use `external-dns` for a private hosted zone, to route to their on-prem datacenter without exposing the endpoints publicly. Our mandatory app is only supporting public zone.

**Describe the solution you'd like**
To support both private and public hosted zone, we need to have 2 external-dns running at the same time. Having the ability for the customer to install it via a manage app is nice.

**Describe alternatives you've considered**
Customer will probably run it by themselves until we can provide it to them.

**Additional context**
None

**Comment by cokiengchiara** [comment]
thanks @pipo02mix 

You seem to mean sth like "Add External DNS as an app in Happa", right?

You don't mean "Managed External DNS," as in _a managed apps team should take care of this for customers with SLA_?

**Comment by pipo02mix** [comment]
No really, I created a ticket [here](https://github.com/giantswarm/roadmap/issues/129) to show the App in Happa (which I think @oponder has already solved :) and can be closed).

This is more about opening the External DNS App we used for our own components, to be used for the customers too as Managed App. So yes it will imply SLA :)

**Comment by cokiengchiara** [comment]
@jgsqware is also requesting for customer.

**Comment by jw-s** [comment]
@cokiengchiara Any progress on this?

**Comment by cokiengchiara** [comment]
> @cokiengchiara Any progress on this?

hi @jw-s ! Not yet, we're working on https://github.com/giantswarm/roadmap/issues/175 😀 

We'll start working on it next week and expect to be done comfortably by Feb 5. Does that work for you?

**Comment by jw-s** [comment]
@cokiengchiara Yeah that works for us! Thank you.

**Comment by cokiengchiara** [comment]
@giantswarm/app-squad-external-dns FYI might be helpful for you to review!

**Comment by glitchcrab** [comment]
@cokiengchiara this is now done :)

**Comment by cokiengchiara** [comment]
thanks @glitchcrab ! 🥳  follow up for docs.giantswarm.io... https://github.com/giantswarm/giantswarm/issues/15627
