### ISSUE TITLE
Enable `kubectl gs login` to workload cluster for non-admins

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1321]
The command `kubectl gs login ... --workload-cluster` requires permission to list Organization resources, which are cluster scoped. A customer has been running into an issue with this.

```
Error: Organizations.security.giantswarm.io is forbidden: User "REDACTED" cannot list resource "organizations" in API group "security.giantswarm.io" at the cluster scope
```

The solution for non-admins is to add the `--organization ORG` flag, where ORG is the organization owning the workload cluster.

However we want to provide better usability by making this flag optional or dropping it entirely.

Source: [Slack](https://gigantic.slack.com/archives/C01RPJ3EY78/p1660654913340959)

## Tasks

- [ ] Verify if there are any additional queries that require cluster-admin permissions.
- [ ] Change organization listing to use the SelfSubjectAccessReview method

**Comment by marians** [comment]
@vvondruska This is the issue we just talked about.

**Comment by marians** [comment]
I have just updated the priority of this issue from high to low. For the customer reporting the problem originally, we found that the root cause for not having admin permissions was a configuration problem, which is fixed now.

The remainder of this story is a general UX improvement for non-admins.

**Comment by vvondruska** [comment]
This issue was resolved when organization management logic was added to kubectl-gs.
