### ISSUE TITLE
`kubectl gs login` with `--workload-cluster` does not work with `--internal-api` flag

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1323]
When issuing `kubectl gs login INSTALLATION --internal-api --workload-cluster ...`, the commonName passed to the CertConfig resource contains `https://`, which is invalid.

Looks like we need some additional sanitization before this: https://github.com/giantswarm/kubectl-gs/blob/main/cmd/login/clientcert.go#L87

Example of a resulting CertConfig commonName:

    eb0d4deb850f9678.rc40i.k8s.https://internal-g8s.REDACTED.eu-central-1.aws.gigantic.io/

Reference: https://gigantic.slack.com/archives/C02EVLE9W/p1660733264886639

**Comment by marians** [comment]
Will be released with kuebctl-gs v2.19.2

**Comment by marians** [comment]
The changes in 2.19.2 did not completely solve the problem.

We have an internal Slack thread here: https://gigantic.slack.com/archives/C02EVLE9W/p1660733264886639

Taking this into refinement.

**Comment by vvondruska** [comment]
Notes from refinement
Suggested solution:
- Extend the common name sanitization mechanism to remove everything in front of `g8s.`
- Build a testing binary (if we know the platform) or create a standalone kubeconfig file for them or set up an internal API and test it internally first (ask Vaclav R. in https://gigantic.slack.com/archives/C02EVLE9W/p1660733264886639)

**Comment by vvondruska** [comment]
This issue may require a smaller fix than expected.

According to kubectl-gs documentation the internal-api the hostname of the internal API endpoint is the same as a regular endpoint, only prefixed with `internal-` (https://docs.giantswarm.io/ui-api/kubectl-gs/login/#flags).

In that case we only need to remove the `internal-` prefix (together with all the other things we already remove).

**Comment by marians** [comment]
And id we do that, we have to make sure that the certificate is actually usable for the host. I'm currently not sure if the certificate's DN must include the host name to connect to.

**Comment by vvondruska** [comment]
From the Slack thread I understand that it should work. But I agree that it needs to be tested.
