### ISSUE TITLE
Scheduling cluster upgrades with GitOps

### ISSUE THREAD

**Issue by luca-rui** [giantswarm/roadmap#1325]
Scheduling a cluster upgrade via `kubectl gs` is currently not supported in combination with GitOps, please review this use-case and see original [support thread](https://gigantic.slack.com/archives/C02BBLEE2KW/p1660317066400179?thread_ts=1660316966.861619&cid=C02BBLEE2KW)

**Comment by gianfranco-l** [comment]
[further context](https://gigantic.slack.com/archives/C02EVLE9W/p1660317344863509)

**Comment by gianfranco-l** [comment]
closed in favor of the larger conversation [here](https://github.com/giantswarm/roadmap/issues/1661)
