### ISSUE TITLE
Managed Cert Manager

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#133]
**Is your feature request related to a problem? Please describe.**

Some customers would like to use cert-manager as Managed App. Currently, Giant Swarm already runs [this component](https://github.com/giantswarm/cert-manager-app) for certificate generation.

Thanks to this component customer can automatically create certificates for their Ingress resources.

**Describe the solution you'd like**

Study to open the component to be used for the customer. Show it in the UI list and allow extra configuration.

**Describe alternatives you've considered**

In case it is a concern for the cluster integrity, allow customers to run its own version.

**Additional context**

**Comment by wombat** [comment]
The pre-installed version has caused me some headache as I need a newer version (current 0.9.0 is installed and I would need at least 0.11). Once I install my own version the leader-election kicks in and causes problems with the pre-installed one.
I have not found a way to install multiple `cert-manager` versions inside the same cluster without causing issues.

**Comment by glitchcrab** [comment]
cert-manager-app v2.0.0 is now released, it just needs to be included in a platform release for AWS

**Comment by cokiengchiara** [comment]
Cert Manager is now available as an app in the Giant Swarm Catalog. See here in happa: https://happa.g8s.gorilla.eu-central-1.aws.gigantic.io/apps/giantswarm/cert-manager-app/2.4.2

In our docs https://docs.giantswarm.io/general/releases/#apps it shows as preinstalled for AWS 10+ and optional for Azure and KVM. 

Question for @giantswarm/app-squad-cert-manager and maybe @glitchcrab : In AWS 10+ clusters where cert manager is preinstalled, is it possible for customers to use it as an optional app for their own purpose? (alongside the preinstalled one)

**Comment by cokiengchiara** [comment]
> cert-manager-app v2.0.0 is now released, it just needs to be included in a platform release for AWS

thanks @glitchcrab please remind me as it doesn't show in the [changelog](https://github.com/giantswarm/cert-manager-app/blob/master/CHANGELOG.md#200-2020-07-21). Does it allow installing as an optional app, alongside the preinstalled one?

**Comment by glitchcrab** [comment]
No, you cannot have two cert-managers in the same cluster - they fight with each other.

You can however install it as an optional app in clusters which don't come with it pre-installed (so legacy AWS releases, all Azure and all KVM releases). cert-manager works just fine in those clusters when installed by the customer.

**Comment by cokiengchiara** [comment]
Closing this issue. It's done.

> You can already install cert-manager from Happa etc, so for clusters where it isn't pre-installed the customer just installs from the giantswarm catalog. and in clusters which come with cert-manager pre-installed, the customer can just create their own Issuers to request certificates from (instead of using our Issuer).

I will somehow add this to docs.
