### ISSUE TITLE
Make `kubectl gs template cluster|nodepool` flags depend on the `--provider`

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1331]
From [Slack](https://gigantic.slack.com/archives/C02FJACQ3D4/p1660644635199439)

The command `kubectl gs template cluster` has many provider specific flags. A user normally only wants to create a manifest for a cluster on one specific provider at a time.

What if the command could be executed using `kubectl gs template cluster --provider aws` to show only info on the flags that are compatible with that provider?

**Comment by marians** [comment]
As we are deprecating `kubectl gs template cluster`, I am closing this one.
