### ISSUE TITLE
Make it easier to detect mandatory flags in `kubectl gs template` commands

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1333]
From [Slack](https://gigantic.slack.com/archives/C02FJACQ3D4/p1660644635199439)

The usage info from e. g. `kubectl gs template cluster --help` makes it hard to detect mandatory flags.

When starting to use the command by trial and error, only one missing flag is mentioned in the error message, so users will add them one by one.

**Comment by weatherhog** [comment]
closing
