### ISSUE TITLE
Support Flatcar image build pipeline

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1337]
We need to add support for building openstack flatcar images in the image build pipeline.

**Comment by cornelius-keller** [comment]
@kopiczko please write down the current state of flatcar image building and then hand over to hydra.

**Comment by kopiczko** [comment]
I checked everything and unless we are using OpenSSH 9.0+ in the machine building the image it should not require anything special at the build time. The only thing that we need to is to set the `oem_id`, but  happens after the actual build, and it's described in more detail here https://github.com/kubernetes-sigs/image-builder/issues/937.

@AverageMarcus please let me know if this is enough or you require more info.

**Comment by AverageMarcus** [comment]
Assuming image-builder already has a Flatcar build task for QEMU it should just be a case of adding it to the pipeline. We're already building the images for AWS but not yet using them - https://github.com/giantswarm/capi-image-builder/blob/8a218535d5b40fd2ad22995fa9a31e97e8c72ca2/helm/capi-image-builder/templates/pipelines/capa.yaml#L55

**Comment by kopiczko** [comment]
It's `make FLATCAR_CHANNEL=stable FLATCAR_VERSION=3139.2.3 build-qemu-flatcar`

**Comment by AverageMarcus** [comment]
Actually, the capo pipeline is set up to expect a single OS. If we're looking to switch to Flatcar (rather than build both) you can just update this: https://github.com/giantswarm/capi-image-builder/blob/8a218535d5b40fd2ad22995fa9a31e97e8c72ca2/helm/capi-image-builder/templates/pipelines/capo.yaml#L14

**Comment by kopiczko** [comment]
How about post-processing?

**Comment by AverageMarcus** [comment]
Do you mean the `oem_id` or something else?

If the `oem_id` I think it might be best to handle that as part of the build process (it might actually be possible, let me take a look) to make things simpler. 

If not part of the build process I'm not entirely sure how to go about handling it exactly as not really sure how to work with qemu images. Can it be modified "from the outside" or does that property need to be done on a running instance?

**Comment by kopiczko** [comment]
I'm not sure what you mean, let's sync tomorrow

**Comment by kopiczko** [comment]
We talked with @AverageMarcus and agreed he'll try to push a fix for https://github.com/kubernetes-sigs/image-builder/issues/937 as a first step.

**Comment by kopiczko** [comment]
Status update:

@AverageMarcus proposed a PR to set `oem_id` during the build of the Flatcar image: https://github.com/kubernetes-sigs/image-builder/pull/966

I was testing that but it doesn't seem to work right now. The OEM partition is empty after the image is built.

While trying to test I found there is a bug in the `image-builder@master` and proposed a PR here https://github.com/kubernetes-sigs/image-builder/pull/970.

**Comment by kopiczko** [comment]
I'm not sure who should sort what here. @cornelius-keller said he'll talk with @alex-dabija

**Comment by alex-dabija** [comment]
This depends on current priorities. Unfortunately, Hydra needs to focus on its current priorities with CAPA and for now (short term) we don't plan on having flatcar support.

I purpose for Rocket to take care of the implementation  and to have a chat with @AverageMarcus on how flatcar support could be handled if this is urgent.

**Comment by gawertm** [comment]
as this one was for openstack. not needed. will open new ones for the other providers
