### ISSUE TITLE
Enable CoreDNS configuration through the web UI 

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#134]
**Is your feature request related to a problem? Please describe.**

Our Managed CoreDNS App allows being customized by customers. In GS versions `<=9.x.x` it was thanks to a config map in the tenant clusters. For newer clusters, it is only possible via Management API.

**Describe the solution you'd like**

Include CoreDNS user configuration in our UI (Happa). Same as we do for Nginx Ingress Controller.

**Describe alternatives you've considered**
Only allow it via Management API

**Additional context**

**Comment by T-Kukawka** [comment]
this should land in Cabbage as they own the DNS part of the platform

**Comment by weatherhog** [comment]
moving this to @giantswarm/team-rainbow as this is regarding Happa

**Comment by marians** [comment]
> Include CoreDNS user configuration in our UI (Happa). Same as we do for Nginx Ingress Controller.

This appears to be a misunderstanding. I am not aware of any special way to configure NGINX ingress controller. We do have dedicated widget to install the nginx-ingress-controller-app into the workload cluster, but this does not include extra configurability.

All apps, including external-dns, can be configured via the web UI in a generic way by uploading a config values YAML file (and in addition a secret config values file).

**Comment by pipo02mix** [comment]
But CoreDNS is under preinstalled apps and it is not possible to change it through the UI. It will be very helpful though 
![Screenshot 2023-01-17 at 14 11 34](https://user-images.githubusercontent.com/892157/212907686-7e7dc6f4-ee46-43dd-a16e-04bdb5aa1f2f.png)

**Comment by marians** [comment]
Ah, there we go.

The web UI only allows direct configuration of apps that are installed individually. Default apps are installed as a bundle, and as far as I understand, the bundle holds the configuration for all child apps.

So we'd have to clarify how this (overwriting the bundle config for a child app) would work technically.

**Comment by weatherhog** [comment]
@giantswarm/team-honeybadger is there any possibility in the app-platform to override the values for a single child app installed with the default-apps bundle?

**Comment by weatherhog** [comment]
closing this issue in favour of backstage development
