### ISSUE TITLE
Update CLI guide: List organizations via the Management API

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1340]
Depends on https://github.com/giantswarm/giantswarm/issues/16531

As soon as the `kubectl gs get orgs` command is released, we should update our CLI guide in happa.

**Comment by marians** [comment]
@vvondruska Do you also want to do the honours of making this little change? Could be that all you have to do is change this one line: https://github.com/giantswarm/happa/blob/main/src/components/MAPI/organizations/guides/ListOrganizationsGuide.tsx#L51

... and of course then learn how to test a change in happa, in case you haven't done that before. :)

**Comment by kuosandys** [comment]
I think it could also be a nice touch if we provide a link to the [documentation](https://docs.giantswarm.io/ui-api/kubectl-gs/get-organizations/) for `get organizations` 🙂 It could replace the current link to `login` docs in that guide.
