### ISSUE TITLE
Remove cilium support from v18.x in favor of v19

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1346]
We have run CNCF conformance (k8s 1.23) test and got such failures:

```
[sig-network] Services should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] Services should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] Services should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]
```
It seems a known problem in cilium when using kube-proxy: cilium/cilium#16163
Bug was fixed in 1.12.1, but 1.21.1 is bugged as well and crashes: cilium/cilium#20963

We are waiting for new version of Cilium and postponing switch from provider CNIs until v19

**Comment by whites11** [comment]
Will be released with 18.0.1.
There is a release [ticket](https://github.com/giantswarm/roadmap/issues/1345) for this.
Closing
