### ISSUE TITLE
`retagger` needs updating to replace references of `k8s.gcr.io` with the new registry: `registry.k8s.io`

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#1348]
See here for details on change: https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)

With the release of Kubernetes v1.25, going forward the `registry.k8s.io` container image registry will be used for all official Kubernetes images (including things like coredns, etc). While the old `k8s.gcr.io` will remain accessible and images will still be available, new image tags will not be back-ported to it.

As far as I know, all images currently in the `k8s.gcr.io` are now available in `registry.k8s.io` as well as newer images such as coredns v1.9.3

**Comment by uvegla** [comment]
Responded on https://github.com/giantswarm/retagger/pull/726 and merged it, closing this ticket.
