### ISSUE TITLE
Support dry-run when upgrading to v19

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1349]
As a  user i would like to upgrade cluster with gitops approach to v19 where the Cilium is added and aws-cni removed. Currently the dry-run is blocked with flux due to issue that an annotation for Pod CIDR range has to be added such that it does not overlap with AWS CNI if any custom setting has been set. After upgrade that flag is also removed from the Cluster CR.

Internal customer thread: https://gigantic.slack.com/archives/C5PDDBBDG/p1661156983145929

**Comment by kaarthis** [comment]
What use cases do you see for other operations common issues to surfact - in Scaling, Create , Update etc ?

**Comment by T-Kukawka** [comment]
This given issue is due too a flag we require that is later removed. Added more details  @kaarthis
