### ISSUE TITLE
Users should not be prompted to upgrade clusters to a non-active release in the web UI

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1352]
From internal Slack thread: https://gigantic.slack.com/archives/C02FJACQ3D4/p1661510981049379

Giant Swarm staff accessing the web UI as an admin are able to see non-active releases (releases with status `deprecated`, `wip`, or `preview`). As a result, GS staff are being prompted to upgrade clusters to these non-active releases.
![image (1)](https://user-images.githubusercontent.com/62935115/186916196-b94c27fc-17e0-4d0f-bebe-df286be26f45.png)

We should only display the "Upgrade available" caution if there is an active release (status `active`) that the cluster could be upgraded to. We should also only display the "Upgrade cluster..." button if the next available release for upgrade is not deprecated.

Note that this issue is only present in the "admin" version of the web UI - only GS staff have access to this UI, and customer users are unaffected.

**Comment by marians** [comment]
Sounds legit!
