### ISSUE TITLE
How we create installation names

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1353]
On our Barcelona Onsite we just talked about how we want to pick/generate installation names in the future.

### About the status quo

- Currently whoever creates the installation picks a name
- Customers often don't embrace/adopt the names. Instead they talk about locations like "Dublin" or "onprem".
- Installation names are part of public DNS
- Customers can have many installations.
- We don't want to encode any information in the installation names (like e. g. customer, region)
  - One exception: installation names start with the same first letter as the customer name. We have several customers with the same first letter.
- We like the fact that installation names are usually easy to handle. Ideally they are easy to search for, as they are terms which don't get used in our normal communication.
- The best installation names are easy to spell, type, and pronounce.

### In the future we want to

- Manually maintain a list of at least 100 terms that can be used as new installation names.
  - All terms in the list match our criteria of min and max length, simplicity, uncommonness.
- Publish that list in a Github repository.
- Let customers pick their installation names from that list.
- Avoid matching the first installation name letter with the customer name. GS staff should not be encouraged to assume which customer an installation belongs to, based on the name.

### Open

- [x] Assign team ownership
- [x] Create names repo
- [x] Create RFC
- [x] Create public documentation (or internal if can't be public)
- [x] Adapt internal documentation pointing to public

**Comment by marians** [comment]
Adding to SIG product for ownership

**Comment by marians** [comment]
Some domains which provide word lists:

- Plants, crops
- Animals
- Planets
- Materials
- Chemical elements
- Foods
- Names (given names)

**Comment by marians** [comment]
In https://github.com/giantswarm/installation-names we now have a public repository where customers can pick their installation names.

**Comment by puja108** [comment]
Rainbow to create an RFC and if that goes through drive implementation

**Comment by marians** [comment]
RFC draft is available for review: https://github.com/giantswarm/rfc/pull/45

**Comment by marians** [comment]
Public documentation is published at https://docs.giantswarm.io/getting-started/installation-name/

**Comment by marians** [comment]
Intranet docs is also updated. Done.
