### ISSUE TITLE
CAPA private networking

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1355]
## Story

_*-As a cluster admin, I want a CAPA cluster to use private networking in order to run clusters in private environments.*_

## Background

CAPA networking can be configured in 2 different ways:
- default mode, in which the CAPA controllers decide which subnets, NAT gateways and Internet gateway need to be created. This mode is very inflexible and it doesn't allow for much customization;
- bring your own network mode, in which CAPA controllers don't manage any of the subnets, NAT gateways or Internet gateway. This mode is very flexible but it requires additional automation before the cluster is created. It also encourages clusters to be treated as pets. Giant Swarm will not support this mode because we want to the network to be managed by controllers.

Upstream plans on revisiting the network topologies in v2.x, which doesn't have release yet and will probably take a very long time to be available. See [upstream issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1484).

## Changes

Create a new AWS networking operator to reconcile CAPA resources and to create the required AWS resources:
- VPC;
- private subnets;
- routing tables;
- security groups (handled by CAPA controllers);
- transit gateway attachment (part of a separate story);

## Requirements

- create VPC;
- create a private subnet for each each availability zone;
- the control plane nodes and the worker nodes share the same subnet for a given availability zone;
- the CAPA controllers need to be able to find the new AWS resources and to use them while creating the cluster;
- the CIDRs need to be configurable for each private subnet;
- the VPC CIDR needs to be configurable;
- the option to create a cluster with either public or private networking must be configurable in the `values.yaml` file of the `cluster-aws` chart;
- create and reconcile the routing tables for the private subnets;

## Outcome

A new cluster can be created with either private or public networking.

## Questions

- Does the VPC also need to be created?

## Resources

- [Advanced networking topologies upstream issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1484);

**Comment by teemow** [comment]
Another pstream issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3711

**Comment by alex-dabija** [comment]
@AverageMarcus we'll look into the current implementation of the CAPA controllers if it's possible to change it to only create private subnets. At the moment, it does expect to have at least on public subnet.

**Comment by AverageMarcus** [comment]
I've started to look through the CAPA code to see what changes would actually be needed.

Focussed on subnets to start with. Currently the code requires at least 1 public and 1 private subnet (per AZ) when using CAPA-managed VPCs. This is enforced in several places:
* when getting the subnets the count is checked - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/13617fa198118cf8ffbcf252584da15a23445dd9/pkg/cloud/services/network/subnets.go#L109-L116
* when building the initial default subnets, a public subnet is created in each AZ - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/14f91d84eae9c76ddbb151fc007dd10459956903/pkg/cloud/services/network/subnets.go#L225-L234
* when creating a bastion if no public subnet is found it errors out - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/14f91d84eae9c76ddbb151fc007dd10459956903/pkg/cloud/services/ec2/bastion.go#L66-L68
* there's currently no way to skip the creation of a NAT gateway (that requires a public subnet) - https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/14f91d84eae9c76ddbb151fc007dd10459956903/pkg/cloud/services/network/network.go#L62-L66

**Comment by AverageMarcus** [comment]
After further going through the code and some discussion with folk upstream it seems clear that updating CAPA to support fully private networking would result in a change of expected behaviour and thus require a new breaking change version.

For example, changing the NAT gateway to be optional based on private-only subnets would result in this safe-guard error no longer being thrown on potential mis-configuration: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/14f91d84eae9c76ddbb151fc007dd10459956903/pkg/cloud/services/network/natgateways.go#L56-L65

I'm not quite sure how this would line up with CAPAs release lifecycle as they seem to only treat breaking **API** changes as a new major version. This kind of change could then perhaps be included in a minor version release.

**Comment by teemow** [comment]
Since the implementation upstream is a breaking change of behaviour and will take a bit longer, we've decided to turn off networking in the CAPA controllers for now and build a controller that creates the necessary network resources.

**Comment by alex-dabija** [comment]
The security groups are created no matter which networking mode the CAPA controllers operate in. No need to handle them as part of this story.

**Comment by alex-dabija** [comment]
From our discussion today. The `aws-vpc-operator` will have the following behavior:
- to create the VPC, subnets and the route tables;
- there will be just one subnet per availability zone (it's what CAPA does at the moment);
- the control plane nodes and the worker nodes will share the same subnet for a given availability zone;
- routes for internal traffic (inside the VPC) are added to each subnet's route table;
- routes for external traffic (outside the VPC) are added by the `aws-network-topology-operator`;

**Comment by alex-dabija** [comment]
We are currently testing the creation of private clusters with private networking. The issues identified during testing are usually fixed in other separate Github issues.

**Comment by alex-dabija** [comment]
We tested successfully this by creating multiple private clusters.
