### ISSUE TITLE
kubectl-gs login --workload-cluster with --self-contained and/or --keep-context` make unnecessary modification to main kubeconfig

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1372]
Executing a kubectl-gs login command to create certificates for workload clusters should not make any changes to the main kubeconfig file in case the `--keep-context` and/or `--self-contained` flags are present.

It may need to make a legitimate modification of the kubeconfig file during the login process, but creation of certificates for workload clusters should not modify the file at all.

However when a certificate for workload cluster is created, Kubectl-gs attempts to restore the initial context in the main kubeconfig file even in case it is not necessary.

In addition to that one of our customers reported a case when the main kubeconfig file is completely overweitten by the content of the self-contained file: [comment in customer thread](https://github.com/giantswarm/vodafone/issues/563#issuecomment-1219968332 )

This needs to be investogated.

**Comment by vvondruska** [comment]
This issue was resolved by changes applied in the following issues:
- #1732 
- #1542
