### ISSUE TITLE
Error when setting the desired minimum size of an AWS machine pool

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1378]
## Task

Investigate why increasing minimum size of an already provisioned AWS machine pool does not increase the desired minimum value of the ASG,  but ends with an error: 

```
ValidationError: Desired capacity:3 must be between the specified min size:5 and max size:10
```

**Comment by bdehri** [comment]
It looks like error is returned by ec2 itself according to this [line](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/autoscaling/autoscalinggroup.go#L310).

**Comment by bdehri** [comment]
Adjusting desired replicas to minimum replicas fixes the issue but it causes divergence between `MachinePool` CR ad `AWSMachinePool` CR

**Comment by bdehri** [comment]
Example code change can be found [here](https://github.com/bdehri/cluster-api-provider-aws/pull/1/files).

**Comment by T-Kukawka** [comment]
closing
