### ISSUE TITLE
Enable dual stack IPv4/IPv6 connectivity

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#138]
## User Story

- As a Giant Swarm user I want to host applications in Azure with IPv4 and IPv6 connectivity so they can simultaneously reach IPv4 and IPv6 content.

## Acceptance Criteria

- deployed applications can be reached with both IPv4 and IPv6
- deployed applications can simultaneously reach IPv4 and IPv6 content

**Comment by Rotfuks** [comment]
IPv6 is currently not in the scope of our capi product, so this is closed for now.
