### ISSUE TITLE
RFC: Ensure no single point of failure in management cluster access

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1384]

**Comment by kuosandys** [comment]
### Notes from refinement:

Scope of the RFC:
- we want to also mention Prometheus and AlertManager in the RFC, and deprecate Auth0
- we need to investigate whether Grafana is to be included

Service Account tokens:
- remove the section detailing the use of service account tokens
- we should still mention in the RFC why we decided against this

PKI for client cert creation:
- this is reliant on a larger epic

We don't need the PKI as we have other methods:
- we have client cert as a fallback, except for CAPI management clusters, where we currently use the kubeconfig stored in LastPass
- we can improve this by renewing it more frequently, and include this in `opsctl` (e.g. using the LastPass API or LastPass CLI)

Dex in workload clusters:
- we can make it easier to set up dex in workload clusters for customers - i.e. enable it by default
- we'd also have to make athena and nginx defaults for this to work
- this also helps us with supporting them, and we don't anticipate a lot of pushback, as we already have access via client certificates anyways
- configuration for dex is currently pushed to the `config` repo - ask for feedback on this topic

Tasks:
- [ ] restructure RFC according to our thoughts above and get more reviews for it

**Comment by weatherhog** [comment]
can the RFC merged and the issue closed?

**Comment by anvddriesch** [comment]
yes
