### ISSUE TITLE
Intranet page on SSO for staff needs a review with regard to Rest API

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1387]
Our installation setup guide includes information regarding the REST API. As we are no longer creating new installations to use the REST API, these sections should be removed, or at least marked differently, so that GS staff following the guide do not configure anything for the REST API unnecessarily.

Link: https://intranet.giantswarm.io/docs/support-and-ops/installation-setup-guide/giantswarm-sso-setup/

**Comment by marians** [comment]
The article is updated.
