### ISSUE TITLE
Containerd log format does not work properyl with current fluentd config

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#1399]
**Is your feature request related to a problem? Please describe.**

Since we have switched from docker-shim to containerd the log format has changed and now the logs are processed by EFK weirdly in [fluentd logging app](https://github.com/giantswarm/fluent-logshipping-app/). 

**Describe the solution you'd like**

We need to change fluentd collector to parse the new format correctly 
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/412

**Describe alternatives you've considered**

**Additional context**

**Comment by weatherhog** [comment]
@QuentinBisson do you know how to solve this issue?

**Comment by QuentinBisson** [comment]
This requires us to upgrade the fluent-bit app in the fluent logshipping app and to add the new cri parser that exists upstream and configure it for the specific kubernetes versions

**Comment by pipo02mix** [comment]
This worked for adidas FYI

```<parse>
        @type cri
        <parse>
          @type json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
          keep_time_key true
        </parse>
       </parse>```

**Comment by QuentinBisson** [comment]
@giantswarm/team-phoenix do we have a way to know if we are usign docker or CRI? Either a kubernetes version, or smth else? Otherwise we will have to enforce customer configuration

**Comment by whites11** [comment]
You have it in the node CR info.

![docker](https://user-images.githubusercontent.com/868430/191190541-21e1ee18-8d1f-4aa8-a5a5-334d7c7b9c73.png)

**Comment by QuentinBisson** [comment]
Thanks I'll see if I can access that using helm .Capabilities, otherwise, can I assume versions 18+ are using containerd?

**Comment by whites11** [comment]
yes

**Comment by QuentinBisson** [comment]
Fixed by https://github.com/giantswarm/fluent-logshipping-app/pull/93
