### ISSUE TITLE
App catalog entry readme section shows horizontal scroll bar placeholder

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1405]
With a mouse attached, there is this white bar in the bottom of the README section:

![image](https://user-images.githubusercontent.com/273727/190366443-bb7c776e-f687-49d1-8ac1-0978faa57f9f.png)

Seen in Chrome

**Comment by marians** [comment]
Guess I created a duplicate of https://github.com/giantswarm/roadmap/issues/1000 , right?

**Comment by kuosandys** [comment]
Also fixed by https://github.com/giantswarm/happa/pull/3736 🙂
