### ISSUE TITLE
Have documentation that documents `kubectl login` logic in detail

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1411]
context: https://gigantic.slack.com/archives/CLPMFRVU6/p1663154978275849?thread_ts=1663051770.235359&cid=CLPMFRVU6

maybe client server diagram?
https://creately.com/diagram/example/hm5w2tuf1/client-server

**Comment by marians** [comment]
I was looking vor "sequence diagram". https://mermaid-js.github.io/mermaid/#/./sequenceDiagram

**Comment by anvddriesch** [comment]
That looks pretty cool.
Btw the image I drew while talking to Martin is this one https://gigantic.slack.com/archives/C02FJACQ3D4/p1659439021556109?thread_ts=1659357486.374159&cid=C02FJACQ3D4

**Comment by marians** [comment]
Copying here for easier access

![image](https://user-images.githubusercontent.com/273727/190990592-6d1c9dcf-e965-468a-ba7f-604184114e45.png)

**Comment by weatherhog** [comment]
@gawertm we think this is in bigmac
