### ISSUE TITLE
kubectl gs login for workload cluster should fail gracefully if no server endpoint is available

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1413]
In an AWS installation (vintage) we saw the problem that a server entry created by `kubectl gs login` contained `https://:0` as the server URL.

This was for a workload cluster.

The reason was that in the cluster resource the attribute `.spec.controlPlaneEndpoint.host` was empty at the time the context got created.

We should print an error in this case and exit before creating any entries in the kubeconfig file. Suggestion:

> Could not create a context for this cluster, as the cluster's API server endpoint isn't known (yet). If the cluster has been created recently, please wait for a few minutes and try again.

If we add logic to take the creation date/time into account, we can make the second sentence optional and only show it if the cluster is younger than e. g. 30 minutes. After that, is should look like this:

> Could not create a context for this cluster, as the cluster's API server endpoint isn't known. Since the cluster has been created a while ago, this appears to be a problem with cluster creation. Please contact Giant Swarm's support.

Source: [Slack](https://gigantic.slack.com/archives/CLPMFRVU6/p1663582902704179)

**Comment by weatherhog** [comment]
@gawertm we think this is in bigmac
