### ISSUE TITLE
`MachinePool` CR stuck in deleting

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1418]
## Issue

Cluster deletion sometimes leaves `MachinePool` CR stuck in deleting for unknown reason. Only manual cleanup of finalizer will unstuck the deletion process.

## Context

@calvix guess is that the following error is the problem:
```
E0916 20:10:16.604719       1 controller.go:317] controller/machinepool "msg"="Reconciler error" "error"="failed to retrieve kubeconfig secret for Cluster org-giantswarm/outgoing-proxy: secrets \"outgoing-proxy-kubeconfig\" not found" "name"="outgoing-proxy-machine-pool0" "namespace"="org-giantswarm" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachinePool" 

```

See [original issue](https://github.com/giantswarm/giantswarm/issues/23703) for additional details.

## Resources

- [Original issue](https://github.com/giantswarm/giantswarm/issues/23703);

**Comment by calvix** [comment]
fixed
