### ISSUE TITLE
Create an app deploying Kyverno Mutating webhooks for automatic proxy configuration

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1419]
### User Story
-  As a giantswarm PE|SRE I want all pods GS is responsible for to be configured to use an http_proxy via environment variables, so that I can run GS managed applications in an environment behind an HTTP proxy.
### Tasks
- [ ] implement

**Comment by cornelius-keller** [comment]
The kyverno policies are already existing. Here is the repository.
https://github.com/giantswarm/kyverno-policies-connectivity 
IMO we just need to add a job that automatically restarts pods after the web-hook is in place, as we don't have dependency management in the app platform.

**Comment by bavarianbidi** [comment]
Chart is working and could be used via the `config` repo.

Closing the issue for now.

https://github.com/giantswarm/kyverno-policies-connectivity/releases/tag/v0.1.0
