### ISSUE TITLE
Manage workload clusters on various cloud providers via a common management cluster

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#142]
## User Story

_- As a customer I want to control clusters in various data centers and providers (AWS, Azure, KVM/on premises) from a common control plane, so that I can efficiently manage my clusters regardless of the provider they are using._

## Details, Background

- Some customers have installations on two or more providers already.
- Some customers need more flexibility to expand from AWS only to AWS and Azure (or vice versa) in order to provide specific services to their customers.

**Comment by cokiengchiara** [comment]
sig product Mon, 03. May 2021
* It's becoming more relevant w cluster api?
* it should work w cluster api.

Still needs UI and the whole organization concept is not meant for across installations, resilience, architecture, failure domains, etc. 

@snizhana-dynnyk says Biscuit.
