### ISSUE TITLE
Support creating Clusters using an http proxy in cluster-cloud-director

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1421]
Support creating clusters using HTTP_PROXY in cluster-cloud-director.
Please make sure that we are using the same interface (helm variables) as team hydra. See https://github.com/giantswarm/cluster-aws/pull/105

### Tasks
- [ ] Make sure that app platform still supports running behind a proxy so that we can get things bootstrapped.

**Comment by vxav** [comment]
PR to align proxy values with CAPA => https://github.com/giantswarm/cluster-cloud-director/pull/30
No change in functionality, we still use the native capvcd integration.
This only set environment variables on the nodes, not the workloads.

**Comment by vxav** [comment]
The HTTPS Proxy env variable is configured for containerd on the nodes and can pull images fine.
However there is a bug upstream that it doesn't pupolate the HTTP env variable. The maintainers will have it fixed quickly.

**Comment by vxav** [comment]
Closing this as it is done from a cluster chart perspective.

**Comment by gawertm** [comment]
@vxav I think this story is already implemented? current proxy implementation by @bavarianbidi was tested on CAPVCD

**Comment by bavarianbidi** [comment]
The current implementation in `cluster-cloud-director` based on [this](https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/1) PR in `cluster-api-provider-cloud-director` make it possible to create a cluster behind a proxy.

in [upstream issue #299](https://github.com/vmware/cluster-api-provider-cloud-director/issues/299) we track the current process of our forked changes (as in one of the recent meetings with CAPVCD-maintainers we decided with them that the current build-in solution isn't very flexible)
