### ISSUE TITLE
Support creating Management Clusters using a proxy in mc-bootstrap

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1423]
`mc-bootstrap` needs to be adapted to ensure clusters can be configured with proxy variables if required.

- [ ] install cluster-<providrer> chart with proxy configuration
- [ ] bootstrap the app plattform with proxy configuration -> https://github.com/giantswarm/chart-operator/blob/master/helm/chart-operator/values.yaml#L54 and https://github.com/giantswarm/chart-operator/blob/a0c60e37dc1bbb468ce27fc8f4a91d21eff9aa83/helm/chart-operator/templates/deployment.yaml#L102
- [ ] What do we do with flux?

**Comment by bavarianbidi** [comment]
Kyverno connectivity policies PRs:
- [ ] https://github.com/giantswarm/kyverno-policies-connectivity/pull/18
- [ ] https://github.com/giantswarm/kyverno-policies-connectivity/pull/17

**Comment by bavarianbidi** [comment]
Implementation is blocked:

As `kyverno` is currently deployed in namespace `giantswarm`, it's not possible to create a mutating config which affects pods in namespace `giantswarm`.

The future goal in general would be moving `kyverno` out of `namespace/giantswarm`, but this isn't implemented yet:
* https://github.com/giantswarm/giantswarm/issues/23971
* [slack thread #1](https://gigantic.slack.com/archives/C01F7T2MNRL/p1665138123647429)
* [slack thread #2](https://gigantic.slack.com/archives/C02FL4EAADD/p1662033056878279)

**Comment by bavarianbidi** [comment]
Open PRs

- [ ] https://github.com/giantswarm/prometheus-meta-operator/pull/1010

**Comment by bavarianbidi** [comment]
2022-10-18:
* `CAPVCD` isn't able to create instances if `httpsProxy` and `noProxy` is set - could be also a bug which is already solved. Waiting for a new `CAPVCD` version before continue with debugging
* continue on [extending `cluster-operator`](https://github.com/giantswarm/roadmap/issues/1419#issuecomment-1282301419)
* Prepare a summary about the current state of implementation.

**Comment by bavarianbidi** [comment]
with the recent changes in `mc-bootstrap`, `cluster-cloud-director` and `default-apps-cloud-director` it's possible to create a MC behind a corporate proxy.

All follow up topics/open questions are documented in https://github.com/giantswarm/roadmap/issues/1424 and in the RFC https://github.com/giantswarm/rfc/pull/50
