### ISSUE TITLE
Allow management of an app in multiple clusters

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1426]
## User story

- _As an app admin, I want to ensure that the same app and configuration is running in certain workload clusters._

## Details

To be added. @teemow mentioned the need of some customers to get a better overview over apps across their clusters, so that they see which version is deployed where.

**Comment by marians** [comment]
@teemow If you have, feel free to add details here regarding what requirements you have heard about.

**Comment by weatherhog** [comment]
closing this issue
