### ISSUE TITLE
Proxy test environment

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1427]
## Stories

_*-As a Giant Swarm engineer, I want to have a test environment with a plain proxy in a separate VPC in order test the implementation of private networking with proxy support.*_

## Background

Talax uses a transit gateway through which they route all their network traffic. Also, any HTTP and HTTPS traffic going to the Internet must go through a plain proxy. This proxy has a known domain name.

## Requirements

- a VPC with 2 subnets (one private and one public) need to be created;
- the transit gateway created during `mc-bootstrap` cluster creation has to be attached to the VPC;
- a plain proxy for HTTP and HTTPS traffic must be part of the test environment;
- a public Route53 hosted zone needs to be created;
- the proxy domain name must be configured in the public hosted zone;
- HTTP and HTTPS must be routed to go through the plain proxy;
- any other HTTP and HTTPS traffic not routed through the proxy must be blocked at the transit gateway level;
- a NAT gateway must be configured in order to access the Internet through the proxy;
- the proxy must be created in a private subnet;
- a public subnet is needed for the NAT gateway.

## Questions

- What automation technology should be used to get the test environment as soon as possible?
> Probably, Terraform would be the fastest option to get the AWS resources created (VPC, Route53 hosted zone, etc.). I don't know if the plain proxy can be created with Terraform.
> Also, an operator can be used to create all the required AWS resources.

- Does AWS offer a managed plain proxy service for HTTP and HTTPS traffic?
> Unknown.

- Should the transit gateway be part of the test environment?
> The transit gateway can just be attached to the management cluster VPC if it exists in the test environment. The transit gateway can be referenced in the management cluster configuration before it's created and it can be attached durring cluster creation.
> The transit gateway needs to be created and attached to a few VPCs (management cluster VPC and the test environment VPC) before the management cluster creation can continue. The `mc-bootstrap` needs to be aware of the test environment.

- How are routing rules updated?
> The routing rules need to be updated when a management or workload clusters is created. Maybe, transit gateway propagation rules or prefix lists could be used to ease the configuration.
> Talax will have the routes already configured because they will know all the CIDR blocks before any cluster is created. This probably doesn't make much sense for a dynamic test environment.

## Resources

- [Transit gateway route tables](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-route-tables.html);
- [Transit gateway prefix lists refrences](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-prefix-lists.html);
- [Prefix lists](https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html);
- [Giant Swarm test proxy environment diagram](https://miro.com/app/board/uXjVODIW9Rs=/?moveToWidget=3458764531000127919&cot=14);

**Comment by alex-dabija** [comment]
The proxy test environment is created, if enabled, at the same time when a new cluster is created. We successfully routed traffic through the Squid proxy for a pod manually configured with proxy settings.

Further testing is blocked for now until we finish the following two stories:
- https://github.com/giantswarm/roadmap/issues/1355;
- https://github.com/giantswarm/roadmap/issues/1424.

**Comment by calvix** [comment]
still partially blocked, but starting to prepare some stuff for test proxy MC

**Comment by alex-dabija** [comment]
All the cloud-init kubeadm phases finished successfully.

**Comment by calvix** [comment]
cluster machines can boot successfully, all machines join the kubernetes cluster, now I need to sort the core apps that are necessary to run the cluster

**Comment by calvix** [comment]
done
