### ISSUE TITLE
Kubernetes API failures due to ingress controller LB sending requests to all nodes on GCP

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1428]
## Issue

The ingress load balancer sends requests to nodes which are not running Nginx ingress controller pods when `externalTrafficPolicy` is set to `Local` which leads to failures.

The current workaround is to set `externalTrafficPolicy` to `Cluster` on the Nginx ingress controller LB Service for GCP clusters (CAPG).

Issue as mentioned by @mnitchev on [Slack](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1655906985126349?thread_ts=1655800692.427919&cid=C02HLSDH3DZ):

> looks like the problem is that nginx-ingress-controller isn't running on all the worker nodes. This makes any domain pointing to the ingress LoadBalancer IP be unreachable for all Pods on the nodes where nginx isn't running.

## Resources

- [Slack thread](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1655800692427919);

**Comment by alex-dabija** [comment]
@giantswarm/team-cabbage We need help with this one because we don't know if setting the `externalTrafficPolicy` to `Cluster` is the best way forward that the client IP is no longer visible (e.g. audit logs). Could you investigate what is going on?

**Comment by Gacko** [comment]
Setting this to `Cluster` is actually the worst way. On other providers the providers load balancer is doing health checks and disables nodes without an `nginx-ingress-controller`.

**Comment by Gacko** [comment]
Oh and the behavior described by @mnitchev rather sounds like `internalTrafficPolicy` has been set to `Local`.

**Comment by alex-dabija** [comment]
Could you have a link and see what the problem is? We (Hydra), are not really experts when it comes the `nginx-ingress-controller`.

**Comment by Gacko** [comment]
This is not related to `nginx-ingress-controller`, this is a Kubernetes concept:

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy

Anyway: The providers load balancer should implement the health check provided by the `Service` resource (see the [`.spec.healthCheckNodePort` section](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip)). When using `externalTrafficPolicy: Cluster` every node in the cluster can accept connections / requests for this service and then distributes them internally. So we're basically losing the source IP address and add extra network hops.

With `externalTrafficPolicy: Local` only nodes running an instance of the service accept connections and respond to the health check. This way the providers load balancer can determine where an instance of the service is running and disable the nodes without an instance of the service.

**Comment by alex-dabija** [comment]
@Gacko Thanks! If I understood correctly, the issue might be with the load balancer controller which might not be doing the right thing.

I'll check with Hydra to see if something is miss-configured.

**Comment by paurosello** [comment]
@alex-dabija where are you currently facing this issue? would like to take a look at the cluster facing the issue.

One thing I could see happening is nginx being scheduled on masters, and as masters are not added to the LB it could be broken but otherwise the LB looks to be working as expected.

**Comment by alex-dabija** [comment]
@mnitchev will try to reproduce the issue.

**Comment by mnitchev** [comment]
I've only seen this happen on an MC, so it might be something specific to the bootstrapping process. One of our test installations is getting recreated today, I'll keep an eye to see if it happens again

**Comment by paurosello** [comment]
I think this is not really supported when running in kube-proxy mode. Digging deeper

![Screenshot 2022-09-28 at 10 15 37](https://user-images.githubusercontent.com/1133954/192726609-d6ed46ec-175a-40c9-89bc-b64acfaa6ab7.png)

**Comment by paurosello** [comment]
We tested without kubeproxy and its working correctly, we will move CAPG and CAPA to EBPF

**Comment by Gacko** [comment]
@paurosello: Sounds really good! Just reach out to us if you need more help! :)

Can we remove this issue from Cabbage's board for now or even close it since eBPF might be part of the roadmap anyway?

**Comment by alex-dabija** [comment]
> Can we remove this issue from Cabbage's board for now or even close it since eBPF might be part of the roadmap anyway?

Yes, it can be removed from Cabbage's board. I just did it.

**Comment by Gacko** [comment]
Is this still a thing? If so: Re-open.

**Comment by mnitchev** [comment]
We currently have this setup on the LB service for the ingress and it seems to be working. So I think we can close this one
```
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
```
