### ISSUE TITLE
Web UI walkthrough session

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#1430]
Invite all new joiners to a web UI walkthrough session.

To replace https://drive.google.com/file/d/10sUpT1MybSgNE3OElOs6Al9Sni-WFSro/view (Nov 2019) with up-to-date content.

## Content outline

- Purpose of happa
- How to find it
- How to log in
- Versions (MAPI vs. REST API, providers)
- From the user perspective:
  - Cluster list
  - Cluster creation
  - Cluster details
  - Installed Apps
  - Installing an IC
  - Browsing app catalog
  - Installing an app from the catalog
  - Organizations
  - Org access control
- Architecture: Runs in every MC, uses API proxy, 
- Usage data
- Exceptions
- Development

**Comment by kuosandys** [comment]
Slides: https://docs.google.com/presentation/d/1YU31kh7AFsl01RRjRLVSjD-aop_CgXR72jhX40uDbZA/
Recording: https://drive.google.com/drive/u/0/folders/1An45AN91y8lVMompw9i_AsCdz25ftfNJ
