### ISSUE TITLE
Deprecate CRDs which are for KVM only

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1433]
On https://docs.giantswarm.io/ui-api/management-api/crd/ we show some CRDs which are used in KVM only. Since we discontinue KVM, we should mark these CRDs as deprecated.

CRDs itself have deprecation logic built in. Check the kubebuilder docs to find out how to configure this in Go source.

For our docs, we have to set additional deprecation information in the config file. [See here](https://github.com/giantswarm/docs/blob/main/scripts/update-crd-reference/config.yaml#L127-L128) for an example.

**Comment by marians** [comment]
@cornelius-keller We talked about this last week in KaaS sync.

**Comment by cornelius-keller** [comment]
done
