### ISSUE TITLE
Velero (workload cluster backup tool)

### ISSUE THREAD

**Issue by paurosello** [giantswarm/roadmap#144]
**Is your feature request related to a problem? Please describe.**
As a customer I would like to make regular backups of resources and volumes in my clusters.

**Describe the solution you'd like**
I want an easy to install solution that make backups of all the YAMLs inside the cluster and stores results in a long-term storage service (S3, Glacier...)

**Describe alternatives you've considered**
The most common tool for this feature is Velero

**Additional context**
We know some companies using Velero in production and are pretty happy about it.

**Comment by puja108** [comment]
We had companies (both current customers and potential ones) often ask us either for backup functionality in general or Velero specifically. Currently, I do not see any other decent tooling next to Velero out there.

Maybe, if we see a lot of customers asking for it we could add it to the Playground for now.

**Comment by cokiengchiara** [comment]
Do they need us to manage it for them? Or would Playground app be sufficient?

**Comment by paurosello** [comment]
@fer and me are working on initial playground app for now in https://github.com/giantswarm/velero-app

**Comment by fer** [comment]
> @fer and me are working on initial playground app for now in https://github.com/giantswarm/velero-app

Are you referring to the right 'fer'?

**Comment by paurosello** [comment]
no, sorry was referring to @pipo02mix :)

**Comment by cokiengchiara** [comment]
@paurosello you already have it in Playground right? Does it work for you and customer? If yes, we can close it now? :)

**Comment by paurosello** [comment]
Yes, let's close it for now

**Comment by cokiengchiara** [comment]
> Yes, let's close it for now

Thanks! <3

**Comment by cokiengchiara** [comment]
@paurosello , actually @piontec mentioned before it would be nice if we announce when new apps are available in Playground. 

1. WDYT about announcing this in news-product that this app is now available. Something like this.

:farnsworth: Velero is now available as an app in our Playground Catalog.

**What is it?**
**Why did we add it?** 
**Who can use it?** 
**How to use it?** 

2. We could add the above as a checklist to playground catalog checklist. WDYT @pipo02mix ? @giantswarm/team-halo

**Comment by pipo02mix** [comment]
I like the idea IMO we dont inform customers about the Apps we have or are working on. I guess we cannot dump lot info in the Slack channels but we can think of a way to do it (maybe happa can help)

**Comment by cokiengchiara** [comment]
How come I don't see Velero in the playground in Gorilla? 🤔 https://share.getcloudapp.com/7KumvPDB

**Comment by paurosello** [comment]
I see it's on test-playgorund, we will push to playground fully today

**Comment by cokiengchiara** [comment]
ping @paurosello are you still doing this? :)

**Comment by paurosello** [comment]
No 😞 I'm not right now and not sure when I will be able to pick up

**Comment by cokiengchiara** [comment]
@paurosello , @T-Kukawka said his customer would be interested. If it's a quick win, maybe you could collaborate with pushing it to the playground catalog? cc @pipo02mix

**Comment by T-Kukawka** [comment]
what is needed to bring it to the playground exactly @cokiengchiara? got off track with apps recently

**Comment by cokiengchiara** [comment]
> what is needed to bring it to the playground exactly @cokiengchiara? got off track with apps recently

@paurosello said it's already in test playground, so release it to playground catalog? I think this is the doc https://intranet.giantswarm.io/docs/dev-and-releng/how-to-release-a-project/ but someone pls correct me if I'm wrong.

Here are some guidelines for playground in case you have to start from scratch. https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/application-quality-bars/#basic-level But really, just make it available for customer 😅

**Comment by T-Kukawka** [comment]
successfully backed up Azure cluster after some struggles - will start moving app to the playground

**Comment by T-Kukawka** [comment]
@cokiengchiara i have a working app for newest kubernetes and Azure PR here: https://github.com/giantswarm/velero-app/pull/5

**Comment by T-Kukawka** [comment]
Added to playground - works fine on Azure
