### ISSUE TITLE
Support Cluster API provider AWS (CAPA) in the web UI

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1442]
This is the issue tracking the implementation of support for Cluster API provider AWS (CAPA) in the web UI.

## Details
As a first milestone, we aim to provide support for displaying all information our users are used to seeing from other providers.
Support for cluster and node pool management for CAPA will follow. Please see https://github.com/giantswarm/roadmap/issues/1181 as the tracking issue for the broader topic of supporting cluster creation for cluster apps.

### References
- [Cluster app](https://github.com/giantswarm/cluster-aws)
- [CRDs](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/main/api/v1beta1)

## Tasks
- [x] #1446
- [x] #1447
- [x] #1450

### Display
- [x] #1474
- [x] #1507
- [x] #1475 
  - [x] Display instance type statistics for worker nodes
  - [x] #1526
- [x] #1492
  - [x] Display instance type statistics for control planes
- [x] #1501
- [x] #1575
- [x] #1509
- [x] #1508

**Comment by muemich** [comment]
There is a pr open that will close this issue.
