### ISSUE TITLE
kubectl gs 5 chars cluster name validation

### ISSUE THREAD

**Issue by silenteh** [giantswarm/roadmap#1444]
Copying the Slack conversation:

Accorgin to https://github.com/giantswarm/roadmap/issues/1017 we decided we want to support 10 characters in the cluster name in CAPI.  

Currently there is a validation happening in kubectl gs
```bash
Error: Invalid flag: --name must only contain alphanumeric characters, start with a letter, and be no longer than 5 characters in length
```

Digging into the code reveals that there is another flag that we can pass to extend the length of the name to 10 chars: `https://github.com/giantswarm/kubectl-gs/blob/5e272a9c4377fe39336ddf7d0e5a2d3f9d9a69ee/internal/key/key.go#L57`
the flag should be `--enable-long-names`  according to this `https://github.com/giantswarm/kubectl-gs/blob/main/cmd/template/cluster/flag.go#L20`
However I don't see that flag being used/documented in the current version of kubectl-gs  (2.23.0) because it's marked as hidden.

Passing that flag: `--enable-long-names true` allows to bypass the validation and generate a YAML template with the longer name.  

So this is what I believe could to be done to conform to [ISSUE 1017](https://github.com/giantswarm/roadmap/issues/1017):  
- [ ] Remove the hidden flag (unless used for other purposes as well)
- [ ] Use the 10 chars validation by default
- [ ] Remove the 5 chars validation altogether

**Comment by marians** [comment]
@alex-dabija Can hydra take a look into this please?

**Comment by marians** [comment]
@alex-dabija Can hydra take a look into this please?

**Comment by alex-dabija** [comment]
> @alex-dabija Can hydra take a look into this please?

Unfortunately, not at this moment in time. We are strictly focused on the deliverables for private clusters. I'm adding it to our backlog for now.

**Comment by vvondruska** [comment]
When a fix is implemented, ask Hydra to review the PR.

**Comment by vvondruska** [comment]
The `--enable-long-names` flag is used in 3 places/comands:
- `template cluster`
- `template networkpool`
- `template nodepool`

Should we remove it from all 3 commands? Or only from `template cluster` command?

**Comment by vvondruska** [comment]
Note from planning - we should keep things consistent and apply the change to all relevant resources.

**Comment by vvondruska** [comment]
Removing the `--enable-long-names` may be a breaking change in kgs. Question is if anyone even uses it since it's marked as hidden, but it might be safer if we mark the flag as deprecated first and remove it later. What do you think?
