### ISSUE TITLE
Add app bundle annotation to `cluster-aws` and `cluster-gcp`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1448]
## Task

Rainbow is currently working on adding support for app bundles to Happa. According to this [document](https://intranet.giantswarm.io/docs/product/pdr/008_app_bundle_naming/#decision), an app that represents a bundle should be annotated with: application.giantswarm.io/app-type: bundle. This way they can distinguish normal apps from app bundles. What do you think about adding this annotation to:
* [cluster-apps-aws](https://github.com/giantswarm/default-apps-aws);
* [cluster-apps-gcp](https://github.com/giantswarm/default-apps-gcp);

## Resources
- [Slack thread](https://gigantic.slack.com/archives/C03LV8E0RL7/p1664454801882699).

**Comment by calvix** [comment]
done
added "cluster" app type to `cluster-aws` and `cluster-gcp`
added `bundle` app type annotation to default apps for both providers
