### ISSUE TITLE
Integrate CNI as a additional health check to validate masters health

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1452]
As a customer i want to have healtcheck also for CNI running on master nodes that will determine if the nodes are fully  up and running

**Comment by whites11** [comment]
what provider is this? all of them I guess

**Comment by T-Kukawka** [comment]
Ideally all but primarly was for AWS

**Comment by whites11** [comment]
and what does "health check" mean in this scenario? Like the ASG healthcheck?

**Comment by T-Kukawka** [comment]
I believe so, that comes as follow up from Nick and he will take it up

**Comment by T-Kukawka** [comment]
we are going away from aws-cni in favor of Cilium - not needed
