### ISSUE TITLE
Cleanup operator for GCP Clusters

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1459]
### User story 
- As a giant swarm user on GCP I want that if I delete a workload cluster, also all resources associated to it in the cloud provider are cleaned up, so that I don't have to worry about costs of left overs in my cloud account.
### Background
If a workload cluster is deleted via cluster API, resources that are not directly created by cluster API are not deleted. This can be 
- load balancers
- disks 
- other cloud provider resources.

In order to save costs for resources that are not longer needed and also not to fill up our cloud accounts with left overs while doing automated tests on cluster creation and deletion we need  to make sure that a cluster leave no trace when deleted.

**Comment by gawertm** [comment]
as discussed, assigning back to Hydra, as priorities and prereqs changed.
