### ISSUE TITLE
Allow locking resources to avoid accidental deletion

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#146]
**Is your feature request related to a problem? Please describe.**

Some customers (especially security divisions of customers) are having issues with deletion of resources (e.g. clusters) being a single step process when using our APIs directly. Our clients have safe guards that ask for confirmation on delete, however, API calls or kubectl do not have these safeguards built-in (one could say by design)

**Describe the solution you'd like**

Current favored solution would be to have a locking mechanism for resources (e.g. through a defined `finalizer`).

**Describe alternatives you've considered**

Another solution would be to have deletion implemented as a "deletion request" (similar to CSRs). However, that breaks the typical native Kubernetes workflow of resources.

**Additional context**

As [`finalizers`](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers) are just like labels common metadata fields of Kubernetes resources, a simple implementation of this might be to define a specific finalized (so we have at least a bit of control and structure) and allow customers to add that as metadata to any resource they own within our Control Planes. The implementation of the access controls might be similar to us allowing the creation and editing of certain labels on cluster CRs.

Any issues you see with that?

**Comment by puja108** [comment]
@ubergesundheit @corest as you have worked on access controls the most recently, do you see any issues with the above suggestion?

**Comment by puja108** [comment]
Other alternatives would be having admission control prevent deletion in some way.

**Comment by cokiengchiara** [comment]
sig product Mon, 03. May 2021
* Ludacris is working on accidental deletions https://github.com/giantswarm/giantswarm/issues/14504
* having less privileged kube config by default

Does this mean Team Ludacris owns this? @puja108

**Comment by puja108** [comment]
This is different from the issue Ludacris is working on. Ludacris is responsible of the use case of preventing accidental deletion of resources (by GS admins) inside Workload Clusters.

This issue is for the Management API to avoid accidental deletion of a full cluster or parts thereof through our management interfaces. I'd say this is biscuit in that context.

**Comment by JosephSalisbury** [comment]
@snizhana-dynnyk let's make sure to bring this up in next week's mapi planning, we have a clear customer use case and i reckon it's a fairly tractable, user-facing story

**Comment by snizhana-dynnyk** [comment]
From Oliver: we should talk to AEs after refinement before implementation to agree on a solution with customers.

**Comment by marians** [comment]
One customer asked specifically for a mechanism that requires more than one user to agree on the deletion.

**Comment by marians** [comment]
[KEP-2839](https://github.com/kubernetes/enhancements/issues/2839) attempts to design a related specification. [Draft pull request](https://github.com/kubernetes/enhancements/pull/2840)

**Comment by fiunchinho** [comment]
Now that we have [the service priority labels for clusters](https://github.com/giantswarm/rfc/pull/35), I believe it would be straight forward to implement a policy in kyverno that would block the deletion of a cluster when labeled as `HIGHEST` priority, making this accident less likely. Also, if a customer is using gitops and wants to delete a `highest` priority cluster, they need two PRs, which I think it's a good "are you sure" kind of mechanism.

**Comment by marians** [comment]
Since we want the service priority label only to be used on the Cluster resource:

- How do we treat node pools? Not being able to delete a node pool in a cluster that has highest service priority seems like overly restrictive to me.
- If a user attempts to delete the infrastructure (e. g. awscluster) resource, how is that prevented?

**Comment by uvegla** [comment]
> Now that we have [the service priority labels for clusters](https://github.com/giantswarm/rfc/pull/35), I believe it would be straight forward to implement a policy in kyverno that would block the deletion of a cluster when labeled as `HIGHEST` priority, making this accident less likely. Also, if a customer is using gitops and wants to delete a `highest` priority cluster, they need two PRs, which I think it's a good "are you sure" kind of mechanism.

My 5 cent is that I would use another label. I think the point of the priority label is different and this behaviour encourages abusing that label.

**Comment by puja108** [comment]
+1 to Lazlo's comment, as we overload a term with added meaning and functionality by doing this and would incentivize misuse. As mentioned above, the user should have the ability to lock any resource they consider critical enough, use cases includes things like App CRs (think: never delete the ingress controller) or even certain secrets.

On the technical side: We should evaluate if a label even makes sense, as officially labels are for identifying information not for added functionality, for that annotations (or in this case maybe even a finalizer) should be considered.

**Comment by marians** [comment]
I just came across https://github.com/giantswarm/deletion-blocker-operator which sounds related at least by its name.

**Comment by fiunchinho** [comment]
> I just came across https://github.com/giantswarm/deletion-blocker-operator which sounds related at least by its name.

It's not related to this issue, although the name may seem related :smile:

**Comment by weatherhog** [comment]
please also have organisations in mind as organisations should be as protected as clusters

**Comment by gawertm** [comment]
@puja108 based on the titel "allow locking ressources" I think this should be an opt-in feature that admins can enable e.g. for critical ressources (like production cluster). is this correct? then this would be rather easy to do

**Comment by puja108** [comment]
Yes, and if it's something flexible like label based it could be applied to any resource. Also, if it need to be added as a default, we can solve that in GitOps or so.

**Comment by gawertm** [comment]
its not possible to add a policy that targets all resources. we need to select the one where we want this feature to work for.
we would start with:

- clusters (per provider with all related CRs like machines, CPs, nodepools  etc.)
- apps (also default-apps and cluster apps)
- organisations
- namespaces

pls give feedback if you think some other resources should also be able to be available in this feature as well

**Comment by puja108** [comment]
yes, I think for now it is safe to limit to the customer facing CRDs (focus on CAPI first I'd say)

**Comment by marians** [comment]
I wonder about the effects of this feature on the end user side. Leaving some thoughts here, as I don't know how far the spec goes for this.

As a cluster admin, I can add the label to the cluster resource (even via happa where cluster editing is possible = vintage) and this will block deletion of the main cluster resource, but not prevent deletion of anything else in the cluster (control plane, node pools). Let's make sure we educate customers about this.

To be safe, adding the label to all resources of a cluster is required. But this is quite a task. When someone adds a node pool to a protected cluster, will they remember to protect this node pool, too?

If it becomes a routine for admins to add this label to pretty much everything they create, it might also become part of their routine to delete the label before deleting something. And when it has become part of a routine (or script), I wonder if it still has the protection effect that we implemented this feature for.

**Comment by mogottsch** [comment]
@marians 
The advantage of this mechanism is that it is harder to delete a resource that is not created temporarily.
For example, we often create resources to test something and delete them immediately afterward. At the moment deleting a resource always is just one command away.

I expect a user to think twice as soon as the Kyverno policy blocks the deletion. If you are testing things and creating and deleting resources in a short period of time, you would not add this label.

However, adding the label to all cluster-related resources definitely is cumbersome. I think that the current PR could be a first iteration and we should hear back from customers, whether it solved their issue or not.

**Comment by gawertm** [comment]
@marians what would you suggest then to make this feature more useful?

I dont think that removing these labels will become a routine and thus the feature has no protection effect. I think often customers have long-lived clusters and potentially also node-pools. When they add the label during initial creation, I think it can indeed protect later on from accidential deletion.

But I agree it can later on be easily forgotten when adding new clusters / node pools. on the other hand if they just copy the gitops template from another cluster, maybe they will see the labels

**Comment by marians** [comment]
> @marians what would you suggest then to make this feature more useful?

I don't have _the_ solution at hand. My main points were: (a) I'm uncertain about the effects of this solution. (b) Let's make customer / end users aware that each individual resource needs protection to reduce risk.

If you want me to generate ideas, I'd have some on the web UI level:

- Indicate that a resource (cluster, node pool, app) is protected, e. g. by some icon and text.
- Do not show the delete button on a cluster that is protected, and show info why that is.
- If a cluster has protected node pools, apps etc., but the cluster itself is not protected, show a warning. E. g. in the context of the delete function.
- If a cluster is protected, make it easy for the user (one click) to protect its node pools and other resources (like a single click)

**Comment by gawertm** [comment]
ok understood. very good ideas I think. are you following up on this for some UI implementation?

@mogottsch can you make it more exolicit or give a warning in your doc, that all ressources need individual protection? and if e.g. a cluster is protected, it does NOT mean that ressources like nodepools in the cluster are protected as well
also I realized, its probably good to post this in teddyfriends channel once we finished everything. then they can inform the customers about this new feature

**Comment by mogottsch** [comment]
I've added a warning that all resources need individual protection [here](https://github.com/giantswarm/docs/pull/1885/files#diff-8a691f9f61573cbc514dbae87b2e02db2596de57953b4b1c03fea23754356a03R69-R72).

Feel free to suggest improvements.
