### ISSUE TITLE
CAPA (private environments) - Listing all Network Calls we have

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#1460]
To implement monitoring for private environments in CAPA we ne to list all Network calls we are having. With this information we can proceed creating our resourced for private environments

**Comment by hervenicol** [comment]
A list already exists here: https://docs.giantswarm.io/security/domain-allowlist/

**Comment by muemich** [comment]
Any updates on this one @weatherhog ?

**Comment by weatherhog** [comment]
@muemich please ask @TheoBrigitte for updates regarding team Atlas. He is in charge for these things. 

@TheoBrigitte  any updates on this?

**Comment by TheoBrigitte** [comment]
Added a bullet point about this in our [main epic](https://github.com/giantswarm/roadmap/issues/1467) and commented on couple of tasks to remind us to update the domain allowlist.

Closing this as this is no concrete goal to achieve, but rather a reminder that goes with every task in this epic.
