### ISSUE TITLE
CAPA (private environment) - Prometheus to Grafana Cloud

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#1461]
To implement monitoring for private environments in CAPA we need to make sure that prometheus can communicate with Grafana Cloud (cortex)

**Comment by QuentinBisson** [comment]
Working in CAPA, waiting for a private env to be up for further testing.

**Comment by mcbenjemaa** [comment]
Metrics are being sent to Grafana Cloud.

**Comment by QuentinBisson** [comment]
Then i Guess we Can close
