### ISSUE TITLE
CAPA (private environment) - Alertmanager to Opsgenie

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#1462]
To implement alerting for private environments in CAPA we need to make sure alertmanager can communicate with Opsgenie

**Comment by hervenicol** [comment]
Quick checkup:

* Alertmanager is up, but has no alerts - not even the healthcheck.
* prometheus is up
    * discovery looks ok
    * most targets are up, some are missing
       * golem-prometheus/bastions-golem/0 (0/2 up)
       * golem-prometheus/bastions-golem/0 (0/2 up)
       * golem-prometheus/kube-proxy-golem/0 (0/6 up)
       * golem-prometheus/kubernetes-controller-manager-golem/0 (0/3 up)
       * golem-prometheus/kubernetes-scheduler-golem/0 (0/3 up)
       * golem-prometheus/vault-golem/0 (0/2 up)
       * golem-prometheus/workload-golem/0 (50/51 up)
       * serviceMonitor/monitoring/prometheus-operator-app-operator/0 (0/1 up)
    * no rules are setup
 * kubernetes has `prometheusrules` in namespace `monitoring`
 * configmap `prometheus-golem-rulefiles-0` in namespace `golem-prometheus` exists but contains no data :disappointed: 
 * in other prometheus namespaces, same: no data in rules configmaps.
 * prometheus-operator logs show no mention of "rule" or "err"
 * prometheus-meta-operator logs show no mention of "rule" or "err"
 * I tried editing the rulesfile configmap by hand, but my changes get immediately reverted.

So, before we can check if communication from Alertmanager to Opsgenie works, we have to fix Prometheus setup.

**Comment by marieroque** [comment]
`golem` dead
https://gigantic.slack.com/archives/C03LV8E0RL7/p1666874558813139

**Comment by hervenicol** [comment]
Manually fixed alerts on `golem` and `tornado` (see https://github.com/giantswarm/giantswarm/issues/24355): heartbeats are sent to Opsgenie :+1: 
So I think it means it works? Anything else to check?

**Comment by QuentinBisson** [comment]
Alerts are sent to opsgenie. @TheoBrigitte can you ensure we have the private counterpart to this issue?

**Comment by QuentinBisson** [comment]
@giantswarm/team-hydra as tornado is still configured with `pipeline: testing`, the slack alerts are sent to the `alert-test-tornado` slack channel instead of the `alerts` channel but this channel does not exist in slack. Is this fine for you or do we need to move the installation to `pipeline: stable` or create the `alert-test-tornado` channel temporarely?

**Comment by fiunchinho** [comment]
The idea is that `tornado` is `stable`, but we are re-creating it this week. Maybe we can set `pipeline: stable` once we are done recreating it.

**Comment by QuentinBisson** [comment]
Sure that's fine :)

**Comment by AverageMarcus** [comment]
Looks like `grizzly` is incorrectly attributed to Phoenix. 😕

**Comment by fiunchinho** [comment]
> Looks like `grizzly` is incorrectly attributed to Phoenix. confused

Just fixed it here https://github.com/giantswarm/installations/pull/2086

**Comment by hervenicol** [comment]
Ok, now that we have `golem` as private CAPA cluster, and alerts are correctly sent to opsgenie, I guess we can close the issue.

**Comment by QuentinBisson** [comment]
Is goat not the really private mc?

**Comment by hervenicol** [comment]
https://gigantic.slack.com/archives/C04TGHDEF/p1669025588019269
![image](https://user-images.githubusercontent.com/12008875/204215072-3b61732f-87b6-44d8-8120-4463b5b05fc8.png)
I assumed it means if it works on `golem` we're good?

**Comment by QuentinBisson** [comment]
I think we need to wait for goat thé new installation

**Comment by QuentinBisson** [comment]
@alex-dabija or @TheoBrigitte Can you confirm?

**Comment by TheoBrigitte** [comment]
Let's re-test this on private environement

**Comment by hervenicol** [comment]
Alerts from `goat` in opsgenie, received today.
Proves alertmanager can communicate with opsgenie 👍 

![Image](https://user-images.githubusercontent.com/12008875/207549513-864845da-1912-4cce-b5ad-e1b34be123f7.png)
