### ISSUE TITLE
CAPA (private environement)- Auth0 check if the callback works

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#1463]
For the implementation of private environments in CAPS we ne to check if the Callback of Auth0 works

**Comment by QuentinBisson** [comment]
Working on CAPA

@TheoBrigitte can you create the private env counter part so we can close this one?

**Comment by TheoBrigitte** [comment]
Let's make sure we document all network call into https://github.com/giantswarm/docs/blob/main/src/content/platform-overview/security/cluster-security/domain-allowlist/index.md

**Comment by QuentinBisson** [comment]
Tested and documented here https://github.com/giantswarm/docs/pull/1670
