### ISSUE TITLE
CAPA (private environment) - Silences need to be pulled via cronjob from Github (also Prometheus Rules)

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#1466]
For the implementation of private environments in CAPA - silences need to be pulled from github via cronjob which is running on the cluster. The same for prometheus rules

**Comment by QuentinBisson** [comment]
Works on CAPA (created a release of the silence operator), waiting for the private env ticket to be created before closing

**Comment by TheoBrigitte** [comment]
Let's make sure we document all network call into https://github.com/giantswarm/docs/blob/main/src/content/platform-overview/security/cluster-security/domain-allowlist/index.md

**Comment by QuentinBisson** [comment]
github is documented and silences were created on Goat :)
