### ISSUE TITLE
Provide more debugging resources in Alerts

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1476]
We want to provide more resources for oncall people to ease debugging

One way to do this is to improve the PR template in prometheus-rules repository at https://github.com/giantswarm/prometheus-rules/blob/master/.github/pull_request_template.md

And add checkboxes for debugging resources (dashboard, ops-recipe etc)

**Comment by TheoBrigitte** [comment]
Updated the PR template in prometheus-rules repository, by adding links to various piece of documentation on :
- how to create a dashboard
- how to write unit test for prometheus rules
- how to write an alert
