### ISSUE TITLE
Update `etcd-backup-operator` for GCP MCs

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1484]
## Task

Push latest version of `etcd-backup-operator` to the GCP app collection.

## Background

`etcd-backup-operator` is not pushed to gcp app collection and thus GCP MCs are using very old version which does not backup CAPI etcd clusters.

**Comment by fiunchinho** [comment]
Upgraded here by @calvix https://github.com/giantswarm/gcp-app-collection/commit/8d586760012335b04a023fd105fcfa78d1be9ca9

**Comment by fiunchinho** [comment]
Added circleci job so that new releases are automatically pushed to the gcp app collection https://github.com/giantswarm/etcd-backup-operator/pull/355
