### ISSUE TITLE
Add configuration field in CR for /var/log disk size

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1487]
As a user i would like to have possibility  to configure the /var/log space same as Kubelet and Docker disks. By default all  3 disks are configured with 100GB however two later ones can be configured via CR fields. We would like to extend such  possibility  with optional field for logs as well. 

- [ ] Add new field in CRD
- [ ] Add defaulting of new field to 100Gb in aws-admission-controller
- [ ] Make aws-operator use the new field
- [ ] Ensure kubectl-gs render the new field in `kubectl template nodepool`
- [ ] Ensure adding the new field works fine with existing cluster

**Comment by whites11** [comment]
I spoke with Jose, I need to manually delete v1alpha2 from the CRDs in MCs and then I should be able to apply the changed version

**Comment by whites11** [comment]
Jose's black magic trick works, I'm able to test on gaia.
For some reason, the log disk size field gets defaulted to 100 even when I set it to something else.
Need more troubleshooting and to adjust frontends

**Comment by T-Kukawka** [comment]
@alex-dabija to check if the feature is available in CAPI

**Comment by T-Kukawka** [comment]
will be satisfied by: https://github.com/giantswarm/giantswarm/issues/25022

**Comment by T-Kukawka** [comment]
will be released in v19 - the default is 50GB now
