### ISSUE TITLE
Disable Hyper-Threading technology for workload clusters

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#149]
**Is your feature request related to a problem? Please describe.**

In some occasions, the [Hyper-Threading technology does not work as expected](https://aws.amazon.com/blogs/compute/disabling-intel-hyper-threading-technology-on-amazon-linux/). When running single thread or high-performance computing workloads the overall CPU performance improvements vanishes and it could indeed penalize these workloads. 

**Describe the solution you'd like**

Add a cluster-wide option to disable Hyper-Threading in our operating systems. 

**Describe alternatives you've considered**

Disabling the logical CPUs after the machine has booted up. It could have some unexpected consequences and it is not persistent through reboots.

**Additional context**

https://coreos.com/os/docs/latest/disabling-smt.html
https://stackoverflow.com/questions/10709442/single-cpu-programs-running-on-hyper-threading-enabled-quadcore-cpu

**Comment by cornelius-keller** [comment]
We currently don't see clients requesting this anymore.
