### ISSUE TITLE
Font awesome icons sometimes don't load in the web UI

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1490]
Sometimes the font awesome icons don't load:
![Screen Shot 2022-10-07 at 14 08 11](https://user-images.githubusercontent.com/62935115/194550599-ac6b935e-c8da-42d1-90c2-2461568586fa.png)
![Screen Shot 2022-10-07 at 14 08 24](https://user-images.githubusercontent.com/62935115/194550597-63764837-b120-4624-b50b-470f35537e95.png)

Error in the console:
![Screen Shot 2022-10-07 at 14 07 26](https://user-images.githubusercontent.com/62935115/194550602-74ba8bb3-4aa3-4ed8-9a0f-eb11d1fe8a7e.png)

A hard refresh of the webpage resolves the issue.

**Comment by marians** [comment]
Some questions:

- Can we find this in Sentry?
- Is this happening on certain installations, in certain browsers?

**Comment by kuosandys** [comment]
I was seeing this on multiple installations with Chrome on Friday, and now cannot reproduce it at all. I also don't see this reported in Sentry.

Closing as it's not reproducible or actionable. If any other users report similar issues we can investigate further.
