### ISSUE TITLE
NodeLocal DNS Cache as a Managed App

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#1494]
## User Story

- As a cluster administrator, I would like to use NodeLocal DNS Cache so that cluster DNS performance is improved.
- As a Giant Swarm customer, I would like to have NodeLocal DNS Cache available as a Managed App so that I can rely on Giant Swarm for sensible defaults and important upgrades.

## Acceptance Criteria

- [x] When I check the available Managed Apps, then I should be able to install NodeLocal DNS Cache
- [x] When I install NodeLocal DNS Cache, then `__PILLAR__CLUSTER__DNS__` should be used instead of `__PILLAR__UPSTREAM__SERVERS__` by default
- [ ] When I install NodeLocal DNS Cache in a Workload Cluster running on Cilium, the tool should work out of the box

## Dependencies

- We need to understand if it makes sense to use this tool when the CNI is Cilium
- Build knowledge on the tool
- Revive the current [Playground App](https://github.com/giantswarm/k8s-dns-node-cache-app)

**Comment by Gacko** [comment]
`__PILLAR__CLUSTER__DNS__` is already being used in one of the latest releases. adidas already ran an older version from our catalog on `deu01`. So for now it's just the Cilium testing left.

**Comment by Gacko** [comment]
Anyway: Right now we are not code owners for this, Phoenix is working on it.

**Comment by weatherhog** [comment]
@giantswarm/team-phoenix moving this to you as you are the code owner

**Comment by T-Kukawka** [comment]
node-local-dns cache is added now as default app, we are working on Cilium part

**Comment by whites11** [comment]
this is done
