### ISSUE TITLE
Disable AWS AZ rebalance for AutoScalingGroups

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#150]
**Is your feature request related to a problem? Please describe.**

By default [AWS rebalance the auto-scaling groups when there are are more nodes in one zone than the other](https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html#AutoScalingBehavior.InstanceUsage). For Kubernetes clusters where there is already a Cluster Autoscaler operating the AutoScalingGroup (ASG) it could have some undesired effects. 

Example there is an unbalanced ASG, but cluster autoscaler removes a node in the zone or add a new node in the unbalanced zone (which will balance again the number of machines), it can result in the two mechanisms take corrective actions at the same time provoking an unexpected result.

Ideally, we have only one controller that decides when to expand or shrink the node pool.

**Describe the solution you'd like**

AWS allows suspending the AZ rebalance feature for your AutoScaling Group.

**Describe alternatives you've considered**

Leave it like it is. Most of the times work fine but is some scenarios like cluster upgrade or autoscaler scaling in/out the node pool the action does not add any value

**Additional context**

**Comment by darraghjones** [comment]
You can suspend and then resume one or more of the processes for your Auto Scaling group. https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-suspend-resume-processes.html
