### ISSUE TITLE
Display user-installed and default apps

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1501]
Towards https://github.com/giantswarm/roadmap/issues/1442.

- Fix default apps showing up as user-installed apps

**Comment by kuosandys** [comment]
When investigating https://github.com/giantswarm/roadmap/issues/1527 we found that clusters + default apps created with a newer version of `kubectl gs template cluster` breaks our current implementation.

**Comment by gusevda** [comment]
Fixed in https://github.com/giantswarm/happa/pull/3834
