### ISSUE TITLE
`kubectl gs template cluster` should support all CAPI providers

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1529]
## User story

- _As an admin, I want to create a cluster manifest via the CLI, so that I can create a cluster in a reproducible way._

## Details

The [`kubectl gs template cluster`](https://docs.giantswarm.io/ui-api/kubectl-gs/template-cluster/) command should provide a manifest for creation of the App and ConfigMap resources needed to provision a workload cluster.

## Tasks

- [ ] #1554
- [ ] `kubectl gs template cluster` should support CAPZ

As a product owner, please convert your line item into a provider-specific issue to track in your team.

**Comment by uvegla** [comment]
FTR We have been working on adding support for creating `gitops` bases for CAPx cluster in `kubectl gs`. Currently for `template` only CAP[A,G,O] uses the cluster + default apps App CRs approach so we limited the scope in https://github.com/giantswarm/roadmap/issues/1828 to support these providers only. There are some intersection / cross calling / using same data structures to avoid some double maintenance in the future, so setting up other providers - CAP[Z,V,CVD] at the moment - is more optimal when `template` supports the new structures as well. Created tickets to add support for these in the future for `gitops add base` and cross linked them.

**Comment by weatherhog** [comment]
not investing more effort into this command
