### ISSUE TITLE
Separate subnets for the ingress LB

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1534]

**Comment by alex-dabija** [comment]
Team Cabbage already has an issue for this.

**Comment by alex-dabija** [comment]
I reopened the issue because team Cabbage only had an [issue](https://github.com/giantswarm/giantswarm/issues/24120) to investigate if it's possible to configure the ingress controller to use custom subnets.

**Comment by alex-dabija** [comment]
@Jose & I talked about how we could ensure the the ingress controller LB starts on specific subnets. The approach we agreed on is to ensure that the ingress controller subnet names can be configured from the `values.yaml` file.

@AverageMarcus  already pushed a [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3991/files) to CAPA for this, but it will only work for public clusters.

The subntet creation for private clusters is handled by the `aws-vpc-operator`, which has the same behavior as CAPA. The operator will be updated to allow for the subnet names to be customized via tags set in `values.yaml`.

**Comment by fiunchinho** [comment]
Changes done and released on `v0.3.0`.
