### ISSUE TITLE
Getting Secrets securely into Kubernetes

### ISSUE THREAD

**Issue by muemich** [giantswarm/roadmap#1539]
As a Customers 
I'd like to have secret management 
Which I can use for my own apps provided centrally by Giant Swarm.

We need to invest time with customers to get a better general understanding of what our customers need and want to build this capability.

**Comment by muemich** [comment]
https://github.com/giantswarm/roadmap/issues/1431

**Comment by puja108** [comment]
cc @piontec as the use case towards which the ESO issue #1431 be a solution to

**Comment by gianfranco-l** [comment]
team did a spike and defined an ESO implementation plan (public roadmap ticket [here](https://github.com/giantswarm/roadmap/issues/1749))

**Comment by gianfranco-l** [comment]
closed in favor of https://github.com/giantswarm/roadmap/issues/1749
