### ISSUE TITLE
Automatic replacement of MC NotReady nodes

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#1541]
Similarly to what we do on WCs, we should have an automatic replacement feature of MC nodes when they get not ready

**Comment by whites11** [comment]
@giantswarm/team-hydra is there any feature like this implemented in the CAPI world?

**Comment by alex-dabija** [comment]
CAPI does have the concept of [health checks](https://cluster-api.sigs.k8s.io/tasks/automated-machine-management/healthchecking.html) for machines. Unfortunately, it only works with machine deployments and not with machine pools because a machine resource CR (or machine set CR) needs to be present.

**Comment by T-Kukawka** [comment]
Waiting for CAPA to stabilize implementation of machinepools/machinedeployments

**Comment by whites11** [comment]
did some progress in giantnetes-terraform 14.12.0.
We run a script in the masters that take the node down if services are down

**Comment by nprokopic** [comment]
In CAPI all MCs will also be WCs at the same time (with all CAPI CRs and managed my CAPI), so it will be possible to use MachineHealthChecks (however well/bad they work).

Currently it should be possible to use MachineHealthChecks for control plane nodes and workers created with machine deployments (CAPG and CAPZ, and I think all onprem providers).

When it comes to MachinePool support (currently used in CAPA), there is an [open PR](https://github.com/kubernetes-sigs/cluster-api/pull/7938) to implement MachinePoolMachine, which should then make it possible to implement MachineHealthChecks for MachinePool as well.

**Comment by fiunchinho** [comment]
[CAPA is currently using it for the control planes nodes](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/templates/_machine_health_check.tpl).

**Comment by fiunchinho** [comment]
Nowadays I think this is a duplicate of https://github.com/giantswarm/giantswarm/issues/28006. I think I'd close this one @T-Kukawka

**Comment by T-Kukawka** [comment]
agreed, closing
