### ISSUE TITLE
Refactor internal handling of providers in kubectl-gs

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1545]
Look at https://github.com/giantswarm/kubectl-gs/blob/main/pkg/commonconfig/commonconfig.go#L37-L59 

It seems as if we only support three providers: AWS, Azure, OpenStack.

And OpenStack is the default?

This does not make sense to me and I wonder how it would make sense to any team implemenenting another provider.

If the intent was to have a value for "any CAPI provider", I think we should make this explicit.

**Comment by vvondruska** [comment]
This issue was resolved when a new logic to add support for authentication in CAPI clusters was added.
It was further extended when a new provides was added,
