### ISSUE TITLE
Use custom domain name for IRSA cloudfront

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#1546]
As a customer i would like to have a custom domain for the Cloudfront bucket containing the IRSA details. Currently the Cloudfront generated url is hard to use in automation. This applies for both - Vintage and CAPA clusters.

Testing scenarios:

- [x] Test creation of new v17 cluster with irsa enabled works
- [x] Test creation of new v18 cluster with irsa enabled works
- [x] Test enabling irsa on v17 cluster works
- [x] Test enabling irsa on v18 cluster works
- [x] Test upgrade of irsa operator upgrades cloudfront settings and does not break v17 clusters
- [x] Test upgrade of irsa operator upgrades cloudfront settings and does not break v18 clusters
- [x] Test creating capa cluster with IRSA enabled
- [x] Test upgrading irsa-operator impact on existing capa cluster
- [x] Test v18 cluster in china with irsa enabled
- [x] Test enabling irsa in v18 china cluster

**Comment by whites11** [comment]
During irsa-operator upgrade, configmap URL does not get updated

**Comment by whites11** [comment]
@paurosello release 18.0.3 with fix of duplicate flag ready to be tested https://github.com/giantswarm/releases/tree/aws-18.0.3

**Comment by paurosello** [comment]
We have an issue here which is very similar to the one we just fixed, the old cloudfront issuer needs to be kept otherwise the SA tokens are invalid again during the change.

Current SA tokens:
```
{
  "aud": [
    "sts.amazonaws.com"
  ],
  "exp": 1698235219,
  "iat": 1666699219,
  "iss": "https://d1znzzt8xntvfq.cloudfront.net",
  "kubernetes.io": {
    "namespace": "kube-system",
    "pod": {
      "name": "external-dns-7444869f65-hh6sq",
      "uid": "afdeb536-5816-4b62-95d4-1974a8be3959"
    },
    "serviceaccount": {
      "name": "external-dns",
      "uid": "2a2f575b-e1d2-41f5-b622-0ce14d3f391b"
    },
    "warnafter": 1666702826
  },
  "nbf": 1666699219,
  "sub": "system:serviceaccount:kube-system:external-dns"
}
```


Currently we replaced one with the other but we will need to keep both somewhow if they already enabled IRSA with Cloudfront (and the old one with the cluster domain):
`--service-account-issuer=https://d1znzzt8xntvfq.cloudfront.net`
`--service-account-issuer=https://irsa.test.k8s.gauss.eu-west-1.aws.gigantic.io`

**Comment by paurosello** [comment]
Another issue is that the trust policy of Route53 role is not updated with the new OIDC provider:

![Screenshot 2022-10-25 at 13 25 50](https://user-images.githubusercontent.com/1133954/197770593-529609e4-d020-43d9-a571-df78b67f1373.png)


should be 

![Screenshot 2022-10-25 at 14 16 48](https://user-images.githubusercontent.com/1133954/197770683-5d040299-17c4-4c35-9e92-d88b82a922cc.png)

**Comment by paurosello** [comment]
Then also we have 2 OIDC providers with different thumbprints

![Screenshot 2022-10-25 at 13 25 40](https://user-images.githubusercontent.com/1133954/197770756-808fa5df-2905-40ad-9438-ee1659b23035.png)

**Comment by paurosello** [comment]
I tried the new aws-operator and have not see any issues with the signing keys

**Comment by whites11** [comment]
> Then also we have 2 OIDC providers with different thumbprints
> 
> ![Screenshot 2022-10-25 at 13 25 40](https://user-images.githubusercontent.com/1133954/197770756-808fa5df-2905-40ad-9438-ee1659b23035.png)
> 
> I was getting some issues in externalDNS with invalid thumbprint but would like to fix the other issues first before testing this again as the issuer might be related to this.

what is the desired state here? To have one provider but change the Url to the new one?

**Comment by T-Kukawka** [comment]
IRSA operator CloudFront domain alias needs to be optional or the option to disable it needs to be provided. This has to be implemented to facilitate the private clusters setup that we are working on for CAPA solution.

**Comment by LolloneS** [comment]
Will customers need to create the custom domain or will they be able to just rely on a default domain that we provide (e.g. linked to the cluster ID or something like that)? 

It would be great if they could rely on some default one.

**Comment by whites11** [comment]
we provide a default

**Comment by AverageMarcus** [comment]
> we provide a default

"provide" or "only support" ?

**Comment by whites11** [comment]
the current implementation (still WIP) hardcodes a calculated value as the alias, and that's the only alias we support right now.
The alias is something like this:

```
irsa.<cluster ID>.k8s.<installation>.<region>.aws.gigantic.io
```

**Comment by whites11** [comment]
I am testing this, on a v19 cluster.

- I created the cluster with irsa operator 0.8.5 running
- I tested irsa, all good
- I upgraded irsa-operator
- all needed resources have been created.
- master nodes are still NOT rolled.
- irsa workloads fail, with the following error

```
time="2022-11-14T16:45:48Z" level=error msg="records retrieval failed: failed to list hosted zones: WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: OpenIDConnect provider's HTTPS certificate doesn't match configured thumbprint\n\tstatus code: 400, request id: 07adce02-4dd3-4d34-a4d3-1fb35cad1659"
```

I think it is because the s3 file `keys.json` already includes the new URL

**Comment by paurosello** [comment]
Just finished testing master on vintage and found no issue creating/upgrading/migrating from old irsa operator. I think we are good to go

**Comment by whites11** [comment]
> Just finished testing master on vintage and found no issue creating/upgrading/migrating from old irsa operator. I think we are good to go

how about china?

**Comment by paurosello** [comment]
ohh yeah

**Comment by paurosello** [comment]
Vintage tested and looks good

**Comment by T-Kukawka** [comment]
Blocking this for vintage until customers adjust the permissions

**Comment by whites11** [comment]
all merged, ready to be released as soon as customer permissions will be ok

**Comment by othylmann** [comment]
@whites11 is this the option to allow adidas to not use clusterIDs for IRSA? And all we have been waiting for is for them update the permissions that @T-Kukawka talked about in other tickets?

**Comment by othylmann** [comment]
And can adidas specify the custom domain? or is it still with the clusterid? Because then you can't use clusters as cattle.

**Comment by T-Kukawka** [comment]
As discussed here: https://github.com/giantswarm/adidas/issues/1071

the custom domain is predefined and will have to be with cluster-id

**Comment by paurosello** [comment]
The main interest form Adidas side to use a custom domain was in order to use a single role with the same domain across all the clusters but this introduces many issues for security upgrades.... I already had a chat with Iya about it and they will be creating a role per cluster for now as this is the best situation and they should sill be able to achieve this with automation

**Comment by T-Kukawka** [comment]
was CAPA tested?

**Comment by T-Kukawka** [comment]
this is implemented and works for both Vintage (integrated) and CAPA (integrated)
