### ISSUE TITLE
Adapt Prometheus Operator App to new coreDNS label in CAPI clusters

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#1547]
After adopting CAPI coreDNS deployment in CAPI the label for the deployment has changed to `coredns`. We need to make sure the prometheus monitor target the right service

```
selector:
    k8s-app: kube-dns
```

to 

```
selector:
    k8s-app: coredns
```

**Comment by QuentinBisson** [comment]
This is an upstream issue https://github.com/prometheus-community/helm-charts/blob/37771b0e600a124507f4e652276cdbf59100fd85/charts/kube-prometheus-stack/templates/exporters/core-dns/service.yaml#L22

**Comment by pipo02mix** [comment]
But I see it can be overwrite by values, so in CAPI we could provide the right one?

**Comment by QuentinBisson** [comment]
Are we using 

```
selector:
    k8s-app: kube-dns
```

on vintage?

**Comment by QuentinBisson** [comment]
Or can we transition to coredns?

**Comment by QuentinBisson** [comment]
Released in https://github.com/giantswarm/prometheus-operator-app/releases/tag/v2.0.1
