### ISSUE TITLE
Visibility on traffic towards API server

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#1549]
Improve https://grafana.g8s.gaia.eu-central-1.aws.gigantic.io/d/zFUtlNp7z/api-audit?orgId=1 dashboard and make it obvious for everybody to answer the question: what component(s) is(are) overloading the API server

**Comment by paurosello** [comment]
Doesn't this already show who is hammering the API?

![Image](https://user-images.githubusercontent.com/1133954/198020779-3906c99a-330b-4d99-a0c0-e26d61fd921c.png)

What would you like to see here?

**Comment by whites11** [comment]
I would like to have another chart, where the query is `by (user)` and not `by (user_agent)` but yeah I guess we can consider that chart good enough

**Comment by paurosello** [comment]
I think doing it by user is a bit better as you see the service account name. ![Screenshot 2022-10-26 at 15 54 58](https://user-images.githubusercontent.com/1133954/198045280-4ca5fe98-2476-4f62-bb4e-602b8a9bd70a.png)

In the previous image, the 4th component is actually kyverno as you can see in the image above, should we switch to user or you want to keep the user_agent?

**Comment by paurosello** [comment]
Whenever grafana dashboard is released it will be there
