### ISSUE TITLE
Ensure RBAC role bindings whenever new organization is created

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1558]
## User story

- _As an admin, I want to ensure that with every new organization we create, certain role bindings (here: for service accounts) are put in place._

## Details

Some customer's RBAC setup relies on role bindings that are configured per organization (or, in other words: a RoleBinding being available in every organization namespace).

Creating some role bindings for existing organizations is easy. However, it is harder to ensure that organizations to be created in the future will be prepared in the same way.

**Comment by anvddriesch** [comment]
Related: https://github.com/giantswarm/roadmap/issues/2706

**Comment by anvddriesch** [comment]
This is solved using [role binding templates](https://docs.giantswarm.io/use-the-api/management-api/authorization/#role-binding-templates)
