### ISSUE TITLE
Prevent mutations of cluster level CM with OPA the same way we do not allow users to change the giantswarm labels

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#156]
Towards https://github.com/giantswarm/giantswarm/issues/10925

## User Story

**As a Giant Swarm Oncaller in the process of editing cluster-level configuration** to fix a problem,
**I want to** be nudged towards editing the user-values configmap, 
**so** my fixes will not get overridden by App Developers.

**As a Giant Swarm Oncaller in the process of editing an App’s default configurations** to fix a problem,
**I want to** be nudged towards editing the user-values configmap, 
**so** my fixes will not get overridden by App Developers.

**Comment by cokiengchiara** [comment]
@giantswarm/team-batman , do you know if this is still an issue? I haven't heard of it.

**Comment by rossf7** [comment]
We want to stop using OPA and Gatekeeper so I think this is stale. I'd say we should close it.

**Comment by rossf7** [comment]
Problem hasn't happened recently and gatekeeper is gone.
