### ISSUE TITLE
Kubernetes `v1.23` on CAPG

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1564]
## Task

Update to the latest version of Kubernetes `v1.23` on CAPG.

## Background

CAPG is using Kubernets `v1.22` which will be end of life by the end of October 2022.

**Comment by AverageMarcus** [comment]
PR bumping default version: https://github.com/giantswarm/cluster-gcp/pull/177

I've manually tested bumping the version of a pre-existing workload cluster without any issues. 

Once PR is merged and released I'll work on upgrading the following:
- [ ] gohan
- [ ] gunter
- [ ] frieza
