### ISSUE TITLE
Reduce github api requests for  management-clusters-fleet

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1566]
For example: https://github.com/giantswarm/management-clusters-fleet/actions/runs/3313244164/jobs/5470966916

![Image](https://user-images.githubusercontent.com/1612809/197544477-856decc7-9fde-4ece-bb61-1a8c5f4bee72.png)

**Comment by gianfranco-l** [comment]
@mproffitt

**Comment by weatherhog** [comment]
closing this
