### ISSUE TITLE
Update crd doc comments

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#1569]
We introduced a new formatting style for crd doc comments ([PR](https://github.com/giantswarm/crd-docs-generator/pull/125)).
This is a breaking change and we need to update all doc comments in [all repositories](https://github.com/giantswarm/docs/blob/main/scripts/update-crd-reference/config.yaml).

**Comment by mogottsch** [comment]
Steps to update are described [here](https://gigantic.slack.com/archives/C04TGHDEF/p1666948949702909).

**Comment by weatherhog** [comment]
@gawertm we think this is in bigmac

**Comment by weatherhog** [comment]
oh yeah. This is my fault
