### ISSUE TITLE
Create controllers required for MachinePool

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#157]
Create controllers required for MachinePool (provider-independent stuff to cluster-operator and rest provider-specific stuff to azure-operator)

Start with:
- [x] create an azure MachinePool controller with HelloWorld resource - use upstream types
- [ ] RESEARCH: what are all the azure specific resources we need to have a node-pools cluster. If we had one ARM template what would be in that template? Single resource or several of them?

Ultimately:
- list all the resources that azure-operator needs to create: separate subnets for all the workers, separate security groups (at least rules), VMSS needs to be created
- then work on how we actually implement it - create separate tickets for each resource to work on parallel

**Comment by fiunchinho** [comment]
First thing that CAPZ controller does when reconciling `AzureMachinePools` is to fetch the parent `MachinePool`. will we use those as well?

**Comment by MartaD** [comment]
ping @tuommaki ⬆️

**Comment by fiunchinho** [comment]
Ok, IIUC both `AzureMachinePool` and `MachinePool` objects need to be created every time we want a nodepool. There is only one controller to reconcile those two CRDs. Is this correct?

**Comment by tuommaki** [comment]
> First thing that CAPZ controller does when reconciling AzureMachinePools is to fetch the parent MachinePool. will we use those as well?

Yes.


> There is only one controller to reconcile those two CRDs. Is this correct?

`azure-operator` has controller to only reconcile `AzureMachinePool` (the provider one).

We need to add controller to `cluster-operator` to reconcile `MachinePool`. Resource set there would be pretty much of what `MachineDeployment` controller has atm.

**Comment by cornelius-keller** [comment]
I just checked if my idea to use the upstream controller for the `MachinePool` resource could work. Unfortunately the controller controlling it is part of the general `capi-controller-manager` which is responsible also for the other provider independent resources like `Cluster` and `MachineDeployment`
