### ISSUE TITLE
k8s-dns-node-cache app move to managed catalog and upgrade to latest release 1.22.13

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1571]
[k8s-dns-node-cache app](https://github.com/giantswarm/k8s-dns-node-cache-app) to managed catalog and upgrade to latest release 1.22.13

Many customers are already using it and some are concerned about it being on playground

Internal thread:
https://gigantic.slack.com/archives/C01G30NGUS3/p1666772012714709?thread_ts=1666769502.271609&cid=C01G30NGUS3

**Comment by paurosello** [comment]
Tested release on 18.0.2 cluster 

![Image](https://user-images.githubusercontent.com/1133954/198622480-4071bc13-032e-4550-856f-28bf3aaa292b.png)

Executing this in externaldns pod we can see the cache is processing the requests
```bash
while true; do
  nslookup google.es
done
```

**Comment by paurosello** [comment]
Release 17.4.3 also good

![Image](https://user-images.githubusercontent.com/1133954/198638413-a9324629-abdf-47f2-9372-30d5e6e221ae.png)

**Comment by paurosello** [comment]
We will need to tell customers to move to the new application by removing the old one in the old catalog and installing the new one that will be in the main GiantSwarm catalog

**Comment by paurosello** [comment]
PR in https://github.com/giantswarm/k8s-dns-node-cache-app/pull/15

**Comment by paurosello** [comment]
We got it

![Image](https://user-images.githubusercontent.com/1133954/199477406-1dddc1e3-f049-4cf6-a1a2-c2b2d83757bd.png)
