### ISSUE TITLE
Allow fine grained access to our central grafana

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#1572]
Currently, we can allow access to our management cluster grafana at the installation level only without finer permissions (per organization).

As our customer base grows, we are starting to see more organization centric approaches in our management clusters. 
We need to allow all organizations to access their own data and give MC admin access to all the data.

This will become even more important with the logging solution currently being worked on

**Comment by Rotfuks** [comment]
Duplication of the linked epic.
