### ISSUE TITLE
Use VNET peering in place of VPN

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#158]
Replacing VPN gateway with VNet peering, because it will:
 - speed up cluster creation time,
 - speed up the connection between management cluster and workload cluster,
 - it's cheaper (to be verified)

Be sure to test for BYOC clusters on different AD.

**Comment by T-Kukawka** [comment]
**Telekom:**
- Subscription for Control Plane - Separate Azure AD
- 3 Subscriptions for clusters - Separate Azure AD
- Orange Subscription for Clusters - Separate AD
**Vaillant**
- 2 Subscriptions (one of them with Control Plane and clusters) within the same Azure AD
**GK***
- 2 Subscriptions (one of them with Control Plane and clusters) within the same Azure AD
**Container Solutions**
- 1 Subscription - they deploy clusters from our CP so separate Azure AD
**DVAG**
- 3 Subscriptions (one of them with Control Plane and clusters) within the same Azure AD
**IC Consult**
- Subscription for Control Plane and clusters - Separate Azure AD
- Subscription for Customer clusters - Separate Azure AD

**Comment by whites11** [comment]
- [ ] Silence operatorkit error rate too high for all azure MCs that didn't migrate to the new structure
- [ ] release 14.2.0-beta1
