### ISSUE TITLE
node-local-dns-cache for Cilium

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1582]
When moving to Cilium in v19 we will have to support the [node-local-dns-cache app ](https://github.com/giantswarm/k8s-dns-node-cache-app) such that customers can further use it's features.

**Comment by paurosello** [comment]
Try this solution https://cloud.yandex.com/en/docs/managed-kubernetes/operations/cilium-node-local-dns

```
apiVersion: "cilium.io/v2"
kind: CiliumLocalRedirectPolicy
metadata:
  name: "nodelocaldns"
  namespace: kube-system
spec:
  redirectFrontend:
    serviceMatcher:
      serviceName: kube-dns
      namespace: kube-system
  redirectBackend:
    localEndpointSelector:
      matchLabels:
        k8s-app: node-local-dns
    toPorts:
      - port: "53"
        name: dns
        protocol: UDP
      - port: "53"
        name: dns-tcp
        protocol: TCP
```

**Comment by paurosello** [comment]
https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/values.yaml#L1054

**Comment by paurosello** [comment]
after doing this change on a live cluster I had to restart the cilium-operator pods to make the new CRD appear

**Comment by paurosello** [comment]
On local DNS we need to change

- disable host network
- Add parameters "-skipteardown=true", "-setupinterface=false", "-setupiptables=false"

Additional things as I have not yet gotten this setup to work, will continue testing

**Comment by paurosello** [comment]
Reading the documentation, the redirect policy does not affect pods that have a connection already stablished and they need to be restarted. 

I think DNS queries create a new connection each time, but will try to see if we can avoid having to reboot all pods in the clusters to make this effective.

**Comment by paurosello** [comment]
Configmap I used to install cilium, localRedirectPolicy is the only thing needed.

```
apiVersion: v1
data:
  values: |
    ipam:
      mode: kubernetes
    k8sServiceHost: api.f2iuuk0stj.gaws.gigantic.io
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    localRedirectPolicy: true
    hubble:
      ui:
        enabled: true
        backend:
          image:
            tag: v0.9.2
        frontend:
          image:
            tag: v0.9.2
      relay:
        enabled: true
    defaultPolicies:
      enabled: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: f2iuuk0stj-default-apps
    meta.helm.sh/release-namespace: org-giantswarm
  creationTimestamp: "2022-11-08T08:15:10Z"
  labels:
    app-operator.giantswarm.io/watching: "true"
    app.giantswarm.io/branch: ""
    app.giantswarm.io/commit: ""
    app.kubernetes.io/instance: f2iuuk0stj-default-apps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: default-apps-aws
    app.kubernetes.io/version: 0.7.0
    application.giantswarm.io/team: hydra
    giantswarm.io/cluster: f2iuuk0stj
    giantswarm.io/managed-by: f2iuuk0stj-default-apps
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: managed
    helm.sh/chart: default-apps-aws-0.7.0
  name: f2iuuk0stj-cilium-user-values
  namespace: org-giantswarm
  resourceVersion: "10175849"
  uid: e5eecf5e-1324-4c8b-b1e6-c5539c2a8787
```

We should change hubble UI default images, otherwise it gives an error
```
    hubble:
      ui:
        enabled: true
        backend:
          image:
            tag: v0.9.2
        frontend:
          image:
            tag: v0.9.2
```

**Comment by paurosello** [comment]
Here we can see apps using node-local-dns with hubble UI (very useful to see cilium rules in place)

![Screenshot 2022-11-08 at 14 36 59](https://user-images.githubusercontent.com/1133954/200578980-2d70b316-3282-4778-9efd-05e14e91615e.png)

**Comment by T-Kukawka** [comment]
released
