### ISSUE TITLE
Allow setting node labels and taints via annotation on a CR

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#1583]
## User Story

- As a cluster admin, I want to be able to ensure that all nodes in a node pool get a certain set of labels, annotations, or taints, so that I can easily schedule CPU- or memory-intensive workload on nodepools of appropriate instance flavors. 

## Acceptance Criteria

- [ ] Given a Cluster API Workload Cluster, when I create a nodepool `X` then I should be able to specify annotations/taints/labels to be applied to the nodes in the nodepool `X`.

## Priority

medium-low

**Comment by AverageMarcus** [comment]
Issues to cover CAPA and CAPG created:
* CAPG - https://github.com/giantswarm/roadmap/issues/1587
* CAPA - https://github.com/giantswarm/roadmap/issues/1586

Removing this issue from Hydras board.

**Comment by AverageMarcus** [comment]
@LolloneS CAPG and CAPA not support node labels and node taints through the app config.

**Comment by LolloneS** [comment]
Thank you! I will add this issue to Team Clippy's board once they have one and we should be good.

**Comment by LolloneS** [comment]
CAPZ issue: https://github.com/giantswarm/roadmap/issues/1619

**Comment by gawertm** [comment]
added issue for CAPO and CAPVCD. Implementation should be same on all providers and quick, thats why I grouped them
https://github.com/giantswarm/roadmap/issues/1637

**Comment by T-Kukawka** [comment]
Feature is available on CAPA and CAPZ
