### ISSUE TITLE
Migrate happa and fe-docs helm charts to use `app-build-suite`

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1585]
In order to implement chart tests for happa (towards https://github.com/giantswarm/giantswarm/issues/20068), we should first migrate to using `app-build-suite`. Without successfully running `app-build-suite`, we are unable to run `app-test-suite` locally (afaik). Generally `app-build-suite` seems to be [better and more modern](https://github.com/giantswarm/architect-orb/blob/master/docs/job/push-to-app-catalog.md#executor-optional-either-architect-or-app-build-suite-defaultarchitect).

To do that we will need to adapt our helm chart, as `app-build-suite` runs some checks that currently would not pass.
E.g. add `application.giantswarm.io/team: team-rainbow` to `Chart.yml` and add `values.schema.json` [for validation](https://intranet.giantswarm.io/docs/organizational-structure/teams/cabbage/app-updates/helm-values-schema/).

**Comment by ubergesundheit** [comment]
Parameter [`persist_chart_archive`](https://github.com/giantswarm/architect-orb/blob/master/docs/job/push-to-app-catalog.md#persist_chart_archive-optional-boolean-defaultfalse) can be also used with architect based chart builds.

**Comment by mogottsch** [comment]
> Parameter [`persist_chart_archive`](https://github.com/giantswarm/architect-orb/blob/master/docs/job/push-to-app-catalog.md#persist_chart_archive-optional-boolean-defaultfalse) can be also used with architect based chart builds.

Thanks for pointing that out. I will unblock the other issue.
