### ISSUE TITLE
Create RFC for labelling default app and cluster app

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1599]
We want to propose a labelling scheme to safely identify the default-apps and the cluster app App CRs for a workload cluster.

This is required for

- Deleting a workload cluster
- Display a workload cluster's defining apps

**Comment by weatherhog** [comment]
From Healthcheck. Find out which team needs to be addressed and then address the team directly

**Comment by weatherhog** [comment]
@gusevda did we find out who to address the RFC to ?

**Comment by gusevda** [comment]
@weatherhog I haven't looked into it yet, I'll try to do it today.

**Comment by weatherhog** [comment]
@gusevda any news on this one? or can it be closed?
