### ISSUE TITLE
Adapt v5 api for Azure Cluster API CRDs

### ISSUE THREAD

**Issue by tuommaki** [giantswarm/roadmap#160]
API for `v5` path should support now also Azure when node pools are released. Therefore its endpoints and related services should be adapted to also support Azure types.

- [x] List clusters - @nprokopic - https://github.com/giantswarm/api/pull/1057
- [x] List node pools - @nprokopic - https://github.com/giantswarm/api/pull/1071
- [x] Search specific cluster - @tuommaki - https://github.com/giantswarm/api/pull/1056
- [x] Search specific node pool - @axbarsan - https://github.com/giantswarm/api/pull/1086
- [x] Create cluster - @tuommaki - https://github.com/giantswarm/api/pull/1067
- [x] Create kubeconfig - @tuommaki - https://github.com/giantswarm/cluster-service/pull/458
- [x] Create node pool - @tuommaki - https://github.com/giantswarm/api/pull/1073
- [x] Delete cluster - @nprokopic - https://github.com/giantswarm/api/pull/1057
- [x] Update cluster - @axbarsan - https://github.com/giantswarm/api/pull/1089
- [x] Update node pool - @axbarsan - https://github.com/giantswarm/api/pull/1088
- [x] Allow passing of kubectl config file path instead of restconfig params, for the purposes of local testing. See how we did it for [azure-operator](https://github.com/giantswarm/azure-operator/pull/620/files) @nprokopic 
- [x] Delete node pool - @axbarsan - https://github.com/giantswarm/api/pull/1097

**Comment by nprokopic** [comment]
@tuommaki fyi the branch I'm working in is this one https://github.com/giantswarm/api/tree/azure-v5, in case you need it before it's merged. (still not tested though, will do it after the lunch)

**Comment by axbarsan** [comment]
Everything ready 👍
