### ISSUE TITLE
irsa-operator/amazon-eks-pod-identity-webhook configured to use regional endpoints by default

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1601]
Based on documentation which is recommended approach: https://github.com/aws/amazon-eks-pod-identity-webhook#aws_sts_regional_endpoints-injection

**Comment by njuettner** [comment]
`aws-pod-identity-webhook` has a new release `v1.1.0` which uses the regional endpoint as the default one.

With any next cluster upgrade `aws-pod-identity-webhook` will be updated automatically.
