### ISSUE TITLE
Fix IRSA placeholder replacement on cluster upgrades

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1602]
## Issue

Currently CAPA clusters are unable to upgrade (roll) control plane nodes without manual intervention.

When the new control plane node comes up and joins the cluster the apiserver static manifest still contains the following:

```
--service-account-issuer=PLACEHOLDER_CLOUDFRONT_DOMAIN  
```

The `PLACEHOLDER_CLOUDFRONT_DOMAIN` string should have been replace at boot with the correct cloudfront domain.

The [irsa-cloudfront.sh](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/files/opt/irsa-cloudfront.sh) script should run on boot to replace the placeholder but the file it's trying to replace doesn't exist:

```
./cloud-init-output.log:[2022-11-04 14:44:59] sed: can't read /run/kubeadm/kubeadm.yaml: No such file or directory
./syslog.1:Nov  4 14:45:41 ip-10-0-103-93 cloud-init[1004]: [2022-11-04 14:44:59] sed: can't read /run/kubeadm/kubeadm.yaml: No such file or directory
```

Without this value replaced the apiserver cannot correctly authenticate requests and the cluster ends up in a state where API calls either work or fail depending on which node they get routed to. If all nodes are replaced (unlikely as the cluster tends to fail before CAPI can get that far) then the API server will reject all calls as having invalid authentication.

Manual intervention is needed to correct the apiserver - `kubectl debug` onto the node and replace the value in `/etc/kubernetes/manifests/kube-apiserver.yaml` with the correct domain.

---

😕  What I can't understand though is how this works with the initially created nodes. They also don't have the `/run/kubeadm/kubeadm.yaml` but the placeholder value seems to be correct in `/etc/kubernetes/manifests/kube-apiserver.yaml`

---

**Related:** 

There is already an issue to have a predictable cloudfront domain name which would get around the need for this placeholder value - https://github.com/giantswarm/roadmap/issues/1546

**Comment by tuladhar** [comment]
We encountered this when creating new MC `grizzly` as well  and noticed the API server was using:
```
--service-account-issuer=PLACEHOLDER_CLOUDFRONT_DOMAIN  
```

We use kubectl debug to login to each nodes and update the API server static POD manifest and restarted each API server pod.

**Comment by bdehri** [comment]
This issue should be fixed after this [PR](https://github.com/giantswarm/cluster-aws/pull/167).

**Comment by alex-dabija** [comment]
@bdehri & @njuettner tested the fix.
