### ISSUE TITLE
Bigger picture vision regarding the UX of creating workload clusters

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1608]
With

- https://github.com/giantswarm/roadmap/issues/1181

we know that we have to change the way we create clusters in the web UI (for technical reasons: CAPI clusters are created via app bundles, not directly via cluster resource manifests). We use this occasion to re-think and improve the experience of cluster creation in general.

The problem: we have three different ways to create clusters, which are developed independently and don't cooperate well.

1. The **cluster creation form in the web UI** which is easy to use, but provides very limited configuration options.
2. The **kubectl-gs template cluster command** which is complicated to use.
3. The **kubectl-gs gitops create workload-cluster** command which is targeting GitOps and which works again different.

## Tasks

- After a call we had on Nov 8, Team Rainbow members go back to our [Miro board](https://miro.com/app/board/uXjVPU9paWE=/?share_link_id=882948886650) to look at some possible improvements. Then comment here to answer: what do you consider most important now?
- Then we should meet again to make a plan.

**Comment by marians** [comment]
What I'd like to accomplish:

- Give users equal power/flexibility, regardless whether they create a workload cluster via the web UI, or any CLI command.
  - Users should pick the tool that works best for them
- Leverage the capabilities of the web UI (guidance) to create a cluster config that can then be applied in a different way (e. g. CLI or GitOps)
  - This is an extension of the idea of our CLI guides. However, instead of generating an imperative CLI command, we should generate a representation of the cluster that can be (a) used with GitOps (declarative), (b) applied with the CLI, or maybe even (c) stored somewhere as a template.

**Comment by marians** [comment]
@giantswarm/team-rainbow Please add your thoughts on what is important to you and how we should proceed with this story.

**Comment by kuosandys** [comment]
What's important to me:
- Providing the option for users to export the created resources/config from the web UI
  - I think combining a guided cluster creation process with the ability to examine the resource/config to be applied provides users with more flexibility and visibility
- Providing "sane defaults"/not having a CLI command flag or UI input field for every configuration
  - I think we need a way to distinguish between essential configurations that the user should set, and more advanced options that they may not need to set, but can still configure if needed

**Comment by weatherhog** [comment]
From Refinement (30.11.2022): 

- exploration regarding happa
- check libraries to generate form based on schema
- cluster creation in CLI QandA based? 
- if we get the WebUI right we do not need to invest in a CLI experience

**Comment by marians** [comment]
Closing, done
