### ISSUE TITLE
Sort out CRDs

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#161]
Sort out CRDs(both Cluster API and ours) that are required for MachinePool (and provider specific parts of it)

- [x] `v1alpha3` Cluster API CRDs to `apiextensions` https://github.com/giantswarm/apiextensions/pull/465
- [x] Azure provider extensions for Cluster API types. https://github.com/giantswarm/apiextensions/pull/465
- [x] Ensure CRDs are installed on all installations: https://github.com/giantswarm/opsctl/pull/673

### AWS

- [x] `alpaca`
- [x] `anteater`
- [x] `antelope`
- [x] `archon`
- [x] `argali`
- [x] `asgard`
- [x] `atlantis`
- [x] `axolotl`
- [x] `gaia`
- [x] `gauss`
- [x] `ginger`
- [x] `giraffe`
- [x] `gorilla`
- [x] `icarus`
- [x] `iris`
- [x] `seal`
- [x] `viking`

### Azure

- [x] `davis`
- [x] `dingo`
- [x] `ghost`
- [x] `godsmack`
- [x] `goku`
- [x] `gollum`
- [x] `impala`
- [x] `talos`
- [x] `victory`

**Comment by tuommaki** [comment]
For the record: I solved the CRD version incompatibility problem between AWS and Azure by implementing additional filtering in `opsctl`.
