### ISSUE TITLE
Improve how Happa depends on labels and annotations

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#1611]
Apps view in Happa was broken after changes in kubectl gs. Let's think about what actions we can take to prevent situations like this in the future.

**Comment by gusevda** [comment]
Notes from the first discussion:

- Happa broke without us noticing, because labels we rely on no longer were set.
- We want a well-defined API. Labels and annotations are part of the API.
- API conformance must be tested with resources "in the wild".
- Testing in happa is currently based on mock resources.
- Customers are facing the same problem. Let's help them, too.
  - Documentation
  - Tooling?

Questions:

- How to create realistic resources in test scenarios?

- Why are we not catching more of these problems via admission controllers?
  - Some existing resources might have been created before policies got enforced, and haven't been updated.
  - Marian: I think we could in fact enforce more. But here again, we are lacking a process to define and agree on rules to enforce.

Ideas:

- Create mock resources using kubectl-gs. However, admission controllers and controllers modify resources after applying.

- E2e test based on real resources.
  - Happa's requirements can be tested even without contract.
  - How to create the resources to test?
    - Can we avoid creating cloud provider resources?
  - Can we use the test suite as a validator for arbitrary installations? (popeye style)
  - Should be executed as part of the cluster-app/default-apps release process
  - Not only metadata (labels, annotations) should be testable. Also e. g. string values, anything that goes beyond the specified OpenAPISchema, also referential integritiy and presence of resources.
  - Ownership?

- "Contract" should be encoded in a way that crd-docs-generator, e2e test suite, and customers can make sense of it.
  - Human readable changes (diffs) and changelog entries would be a benefit.

**Comment by gusevda** [comment]
Notes from Nov 10 sync:
Let's look into CEL - https://github.com/google/cel-spec, to find out if it can be useful for this story

**Comment by vvondruska** [comment]
Progress of this issue is tracked in 2 other tickets:
- https://github.com/giantswarm/roadmap/issues/1599
- https://github.com/giantswarm/giantswarm/issues/24462
