### ISSUE TITLE
Allow using custom CIDR ranges on CAPZ

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#1620]
### Motivation
As a cluster admin, I want to be able to specify the precise CIDR blocks to be used for nodes in my CAPZ cluster, so that I can limit the number of IPs being used per Workload Cluster and effectively peer many clusters to my on-prem environment.

### Todo

- [ ] enable our capz clusters to have custom vnet configuration
- [ ] if there is no custom vnet configuration given (by parameters, yml, or other ways) the clusters should still use the default vnet configurations

### Outcome
- CAPZ Clusters can have a custom vnet configuration enabling our customers to define the ips(/ranges) used throughout the cluster

### Technical Hints
See https://capz.sigs.k8s.io/topics/custom-vnet.html

**Comment by Rotfuks** [comment]
Refinement Input: 
- Already done in AWS and Legacy, but it's a bit of pain.
- We (potentially) need it for private networks
- We can use the default config as default and custom config once parameters come in

**Comment by LolloneS** [comment]
I don't think this is done in Vintage - this has actually been postponed to "after Cluster API" since CAPI offers it out of the box. Right now we reserve a /16 or something per WC, which wastes a lot of IPs in the case you need to peer a small cluster to your on-prem network.

**Comment by bavarianbidi** [comment]
With https://github.com/giantswarm/cluster-azure/pull/11 it's now possible to define the host CIDR.
As worker nodes and control plane nodes could be in dedicated networks i would keep this story open until we have clearance with the customer needs.

**Comment by Rotfuks** [comment]
Already done :)
