### ISSUE TITLE
Investigate how we could align `managementCluster` field in configmaps (string v.s. object)

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1622]
Some applications expect a string for the `managementCluster` field, and others expect an object. We should investigate whether we could align this across apps to reduce confusion.

e.g. in CAPI this field is defaulted to a string, but dex app expects an object, which means that the app installation fails unless the default value is overridden. This is a problem especially in case customers try to install an app in their workload clusters - it should work out of the box.

More context here:
https://gigantic.slack.com/archives/C02FJACQ3D4/p1668097438201099

**Comment by vvondruska** [comment]
Suggested solution:
- Allow both types in the schema
- Modify the Helm chart to work with both
