### ISSUE TITLE
Move all content from gitops template repo to docs

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#1624]
We need to have comprehensive docs about how to setup a gitops repository and how to use the `kubectl gs` commands. The content in the gitops template repository is already outdated and we need to focus on our docs. 

```[tasklist]
### Guide on how to start from scratch
  * [x] Guide on how to setup a gitops repository
  * [x] Guide on how to setup an organization
  * [x] Guide on how to create a cluster
```
```[tasklist]
* [x] Move expert topics from gitops template repo to docs
* [ ] Delete the docs in gitops template repo
* [ ] Explain the purpose of the gitops template repo (use `kubectl gs gitops` but the repo contains examples)
* [ ] Add more explanations to the examples
```

**Comment by teemow** [comment]
@carillan81 I talked to @marians and heard that you both agreed to move and rewrite the content from the template repo to our docs. I've created a rough overview. Does that make sense? Feel free to add or change stuff.

@giantswarm/team-honeybadger fyi. Besides that the content in the repo isn't easy to digest and references to `kubectl gs gitops` are also missing. Carlos is already writing a guide for our docs. And then we will see how to move the other content. Help from your team would be appreciated. But I know you are busy with other things at the moment.

**Comment by gianfranco-l** [comment]
related to https://github.com/giantswarm/giantswarm/issues/22879

**Comment by uvegla** [comment]
See: https://github.com/giantswarm/roadmap/issues/1529#issuecomment-1377416492

**Comment by carillan81** [comment]
I think we can close this issue as we have already merged in docs the main parts of gitops tutorials.
Currently we are covering:

- basic how to start, create repo, attach to MC
- basic tuto on wc creation
- tuto on base creation
- tuto on environment creation
- tuto on app management

This issue has been already closed. https://github.com/giantswarm/giantswarm/issues/22879

There several pending actions that belong to Honeybadger:
 - Convert repo docs into description of the examples and a more descriptive documentation
 - Expand docs in the future with more advanced topics like more on ecryption or other topics
 - Maintain and keep docs up to date
