### ISSUE TITLE
Custom node labels based on node pools

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#163]
## User Story

_- As a cluster admin I want to ensure that all worker nodes in a node pool have the same set of custom labels, so that we can schedule workloads in a targeted and flexible way._

## Details, Background

Currently worker nodes with the same node pool share the node pool identifier as a label, however this identifier is currently created by Giant Swarm when creating a node pool.

This makes it difficult to decide for a given workload (e. g. deployment) to use some node pool(s), but avoid using some other node pool(s). It enforces any node selectors being very specific to the workload cluster used.

One practical use case is a workload cluster where one node pool provides **GPUs** while the others do not. Adding a custom label to all nodes of the pool, indicating that the node has a GPU, would allow to define node selectors and taints which assign workloads that need the GPU to the right nodes, while allowing other workloads to specifically avoid these (expensive) nodes.

Defining the custom labels on the node pool level would conceptually allow to ensure them on every new node being added to the pool.

Lifecycle:

- Modifying the custom labels (adding a label, deleting a label, changing a label) on the node pool must affect all existing nodes of the pool.

## Blocked by / depends on

- Related function: We already support [custom labels on the workload cluster level](https://docs.giantswarm.io/guides/workload-cluster-labelling/). These affect the [Cluster](https://docs.giantswarm.io/reference/cp-k8s-api/clusters.cluster.x-k8s.io/) resource, but they don't affect the kubernetes nodes. Here, in contrast, the labels would likely have to be set on the [MachineDeployment](https://docs.giantswarm.io/reference/cp-k8s-api/machinedeployments.cluster.x-k8s.io/) level and be copied to the worker nodes.

**Comment by MartaD** [comment]
@alex-dabija we have a customer requesting this on Azure as well, could you invite Team Celestial to the refinement session so we are on the same page?
