### ISSUE TITLE
GitOps Progressive Delivery

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1636]
Use case:
as a platform team,
I want different deployment strategies via traffic routing
so that I can increase observability of large scale rollouts of user-facing applications

Possible solution: using Flagger within a GitOps setup based on Flux

**Comment by gianfranco-l** [comment]
a subset use cases of this larger epic is this internal use case/epic: https://github.com/giantswarm/roadmap/issues/620

**Comment by weatherhog** [comment]
@mproffitt is this issue still valid?

**Comment by mproffitt** [comment]
@weatherhog  We discussed Flagger recently and potentially moving this topic to cabbage. Is there an issue there for it? if so, I'd be in favour linking it here and then closing this ticket.

**Comment by weatherhog** [comment]
closing this for https://github.com/giantswarm/roadmap/issues/3684
