### ISSUE TITLE
Enable `etcd` backups for test MCs

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1642]
## Story

As a GS engineer, I want to have `etcd` backups enabled for test management clusters in order to minimize the differences between test and production environments.

## Background

`etcd` backups are only enabled for stable management clusters. We had an event recently which required us to restore `etcd` from backup in order to investigate a bug in one of our operators running on a test management cluster. Unfortunately, the backups were not available because they are disabled for test management clusters.

## Requirements

- `etcd` backups must be enabled for all management clusters (this includes all the CAPI providers: CAPA, CAPG, CAPO, CAPVCD, etc.).

**Comment by alex-dabija** [comment]
@calvix mentioned today in our standup that the configuration to enable or disable the `etcd` backups for a test management cluster is available in the [config repository](https://github.com/giantswarm/config/).

**Comment by bavarianbidi** [comment]
When you already working on this, please note the late comment from Pawel on following PR to make the configuration a bit more generic: https://github.com/giantswarm/config/pull/1296#discussion_r1020465556

**Comment by bavarianbidi** [comment]
Update:

https://github.com/giantswarm/config/pull/1426?notification_referrer_id=NT_kwDOAUV0n7M0OTYwMzA3MzIwOjIxMzI5MDU1#event-7919693414 configure `etcdbackupoperator` for all `capi` flavored installations.

**Comment by tuladhar** [comment]
The backup is working on all CAPI installations except:
- grizzly and golem

In the logs:
```
 {"caller":"github.com/giantswarm/etcd-backup-operator/v4/service/controller/resource/etcdbackup/create_running_v3.go:52","controller":"etcd-backup-operator-etcd-backup-controller","event":"update","level":"error","loop":"241","message":"Failed to repare v3 backup instance grizzly","object":"/etcd-backup-20230110113916","reason":"context deadline exceeded","resource":"etcd-backup","time":"2023-01-10T11:42:57.225526+00:00","version":"155040551"}
```

Vaclav enabled error logging but that didn't help as well. Based on context deadline, it seems there's some timeout happening somewhere.

**Comment by tuladhar** [comment]
Finally, worked on grizzly as well, after rolling out the control plane/worker nodes as part of registry configuration. 
```
opsctl list etcdbackups --installation grizzly
FILENAME                                          SIZE     AGE
grizzly-grizzly-v3-2023-01-10T14-49-14.db.tar.gz  30.6 MB  0 hours 3 minutes
```
