### ISSUE TITLE
Improve error messages in kgs wc certificate creation

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#1643]
In case kubectl-gs fails to download credentials when creating a client certificate for a workload cluster, it prints a generic error message retrieved from the Kubernetes client:

```
kubectl gs login --workload-cluster ab123 --context context-name --organization organization-name --certificate-group system:masters --certificate-ttl 15m --self-contained /tmp/self-contained.yaml
Error: Not found
```

And there may be other similar cases as well.

Ideally these error messages should provide an explanation of what went wrong.

**Comment by weatherhog** [comment]
@gawertm we think this is in bigmac
