### ISSUE TITLE
Stable Giant Swarm CAPA management cluster

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1644]
## Story

_-As a Giant Swarm engineer, I want to have a stable Giant Swarm CAPA management cluster with alerts enabled in order to identify problems early and to always have a stable environment for demos._

## Background

All the current CAPA management clusters are test environments. Alerts and etcd backups are disabled for them.

## Resources

- [General Github issue](https://github.com/giantswarm/giantswarm/issues/24225).

**Comment by fiunchinho** [comment]
Would this be a matter of promoting `goat` from `testing` to `stable` ?

**Comment by alex-dabija** [comment]
We decided to promote grizzly to be our stable MC.
