### ISSUE TITLE
Manage InhibitionRule Externally.

### ISSUE THREAD

**Issue by mcbenjemaa** [giantswarm/roadmap#1646]
## Summary 

The Inhibition rules are managed by pmo via a static file!
We want to manage those rules Externally without the need of releasing PMO.

## Details

We can add support for a new CRD `InhibitionRule` and integrate it in PMO.

**Comment by QuentinBisson** [comment]
TBH I'd rather we implement that in prometheus operator

**Comment by mcbenjemaa** [comment]
Upstream ?

**Comment by QuentinBisson** [comment]
Yes
