### ISSUE TITLE
Stable Giant Swarm Management Cluster for CAPVCD (guppy)

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#1655]
## Story
- As a Giant Swarm engineer, I want to have a stable Giant Swarm CAPVCD management cluster with alerts enabled in order to identify problems early and to always have a stable environment for demos.

## Background
All the current CAPVCD management clusters are test environments. Alerts and etcd backups are disabled for them.

Resources
https://github.com/giantswarm/giantswarm/issues/24225.

**Comment by gawertm** [comment]
installation on ikoula, with proxy

**Comment by erkanerol** [comment]
@vxav @glitchcrab do you know how can we block all internet access for a cluster?

**Comment by vxav** [comment]
One option would be to deploy the cluster on `network-test-2` as the SNAT rule doesn't touch it and it is served by the squid proxy.
Do we need the installation to be behind the proxy if it is bound to be a permanent testing installation though?

**Comment by erkanerol** [comment]
>  Do we need the installation to be behind the proxy if it is bound to be a permanent testing installation though?

My understanding is yes. At the end of the day, our one prod cluster will be behind a proxy without internet access.

**Comment by erkanerol** [comment]
`guppy` is up&running. It will be seen by other teams after these PRs.

- https://github.com/giantswarm/installations/pull/2090
-

**Comment by erkanerol** [comment]
Other teams can use the cluster after running `opsctl login guppy`.

After merging the PR in management-clusters-fleet, I will close this issue.

**Comment by erkanerol** [comment]
Guppy is working as a stable test cluster. Closing this issue.
