### ISSUE TITLE
Enforce policy that every app should have an icon

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#1658]
We want every app to have an icon (https://github.com/giantswarm/roadmap/issues/1248).
Currently, we are adding icons to apps that are missing an icon or already have one that has an aspect ratio that does not suit the requirements of an icon.

In the future, we would like to enforce that policy, so that the teams owning the app will maintain the icon themselves.

One possible approach to accomplish this would be to add a validation rule to `app-build-suite` like we already do with the team label ([implementation](https://github.com/giantswarm/app-build-suite/blob/master/app_build_suite/build_steps/giant_swarm_validators/helm.py)).
There we could check whether an icon is present and whether it has the correct aspect ratio.
We could also do the same check for the `ui.giantswarm.io/logo` annotation.

**Comment by anvddriesch** [comment]
Since we want to offer customers to add their own apps and we do not want to block them, let's look into making this only a warning or make this only matter for GS managed apps.

**Comment by mogottsch** [comment]
I talked to Honeybadger and they approve of this idea.

**Comment by mogottsch** [comment]
Specifically, we would like to check that:
- [ ] the `Chart.yaml` has the key `icon`
- [ ] the icon has the correct aspect ratio (rectangular) (if it exists)
- [ ] the `[ui.giantswarm.io/logo](http://ui.giantswarm.io/logo)` annotation's icon has the correct aspect ratio (wide) (if it exists)

**Comment by weatherhog** [comment]
closing this issue
