### ISSUE TITLE
Fix VPC endpoint security group assigment

### ISSUE THREAD

**Issue by calvix** [giantswarm/roadmap#1672]
## Issue

when VPC endpoint is created, the `aws-vpc-operator` assign security groups are listed in `AWSCluster.status` but it doesn't check if all SGs are there.

there is a race condition that can cause that very early there is only a default security group and only that one is assigned to the VPC endpoint Saw it happened multiple times in a short period so it's not that rare

the `aws-vpc-operator` should wait for all security groups or update the vpc endpoint every reconciliation to add more groups

but the update could theoretically be too late for the first cp and can block cluster creation

see the discussion here:
https://github.com/giantswarm/aws-vpc-operator/pull/10#discussion_r1025292468

**Comment by alex-dabija** [comment]
@nprokopic I think we can close this issue because the VPC endpoint security groups are set correctly. I haven't seen any issues for the past few days.

**Comment by alex-dabija** [comment]
The fix works. Closing...
