### ISSUE TITLE
CAPA  NS records are not updated

### ISSUE THREAD

**Issue by mnitchev** [giantswarm/roadmap#1679]
THE DNS records are not updated if leftover from previous creation are in place.
This happens when an MC is removed and then installed again, but could also happen to an WC if it isn't cleaned up properly.

The update needs to be done to:
* NS record in the parent DNS zone
* API and ingress records needs to be updated to new values
* bastion record might need an update as well

**Comment by fiunchinho** [comment]
I think this was already solved when we created https://github.com/giantswarm/aws-resolver-rules-operator/
