### ISSUE TITLE
Document prerequisites for GCP projects

### ISSUE THREAD

**Issue by mnitchev** [giantswarm/roadmap#1681]
# Description
Document the necessary setup for GCP projects, prior to creating an MC and WCs. At the moment those are several service accounts that need to be set up before clusters can be created. 
Most notably the control-plane and worker nodes need their own service account and specific permissions. This should also be mentioned in the `kubectl gs template cluster --provider gcp` page.

**Comment by pipo02mix** [comment]
@alex-dabija do we want to keep this open yet?

**Comment by alex-dabija** [comment]
> @alex-dabija do we want to keep this open yet?

Yes, I'm still keeping this open because CAPG development might be restarted if we see value in doing so.
