### ISSUE TITLE
Validate user-level values for apps in the web UI

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#1684]
When uploading user-level values in happa it can be unclear to the user whether to upload a full manifest or just the values in `.data.values`.

![Image](https://user-images.githubusercontent.com/61459260/203966626-b7d7272b-3a79-4e54-b9c3-004579e17f88.png)

We should validate the file the user uploaded and check that is not a manifest.

**Comment by marians** [comment]
Alternatively, we could allow both uploading a ConfigMap manifest or the user values part and make both work.

**Comment by marians** [comment]
Since this is a pure happa improvement, I'm closing it.
