### ISSUE TITLE
Kubectl-gs login does not include port in WC server URL in kubeconfig

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#1685]
For example:

`kubectl gs login https://api.workloadcluster.installation.domain.com:6443` should create a new entry in the kubeconfig file and set the `cluster.server` property to `https://api.workloadcluster.installation.domain.com:6443`.

However, kubectl-gs omits the port and just adds `https://api.workloadcluster.installation.domain.com`.

MC login commands and client certificate creation both work correctly.

It's just the workload cluster login that has this problem.

**Comment by vvondruska** [comment]
The problem was actually caused by a misconfiguration in Athena, where the API URL was defined without port.

The API URL in Athena was created by Helm during deployment (by taking the base domain value and prefixing it with `api.`.

To fix it an override has to be specified in the Values config map of the Athena app, which may not always be obvious to the users. Question is - can we do something to improve the API URL automatic creation to include the correct port?

**Comment by marians** [comment]
Let's have a new issue for athena to solve how to expose the port number. @vvondruska
