### ISSUE TITLE
CAPVCD mc-bootstrap ci support

### ISSUE THREAD

**Issue by ericgraf** [giantswarm/roadmap#1686]
- [x] Secrets moved and used from MCF
  - [ ] https://github.com/giantswarm/mc-bootstrap/blob/main/scripts/cloud-director/setup-cloud-provider-app.sh#L60 
  - [ ] https://github.com/giantswarm/mc-bootstrap/blob/main/scripts/cloud-director/setup-cloud-provider-app.sh#L80
- [x] CAPVCD Generate-mc make target docker support 
- [x] #1706
- [ ] Create a CI cluster to continually be reused.
- [x] add cloud-provider-values.yaml to fleet.

**Comment by ericgraf** [comment]
Error to solve in https://github.com/giantswarm/mc-bootstrap/pull/353
```
generate-mc : generate-mc] + cat ./secrets/cloud-provider-values.yaml
[generate-mc : generate-mc] cat: ./secrets/cloud-provider-values.yaml: No such file or directory
[generate-mc : generate-mc] make: *** [Makefile.custom.mk:262: generate-mc] Error 1
```

**Comment by ericgraf** [comment]
Support has been merged. Last step to complete is creating a reusable ci cluster.

**Comment by gawertm** [comment]
@ericgraf is this currently working again with CAPVCD? because at the moment CAPO is set as the default and we will need to remove the CAPO support from mc-bootstrap soonish

**Comment by gawertm** [comment]
closing for now
cc @erkanerol
