### ISSUE TITLE
`goatproxy` k8s resources are missing

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1696]
## Issue

`goatproxy` k8s resources, like the App CRs and their config maps are missing.

## Background

Private CAPA MCs, like `goat`, have a second cluster created to run Squid proxy in order to have access to the Internet. It's using the Giant Swarm mechanisms to create it as part of `mc-bootstrap`, but not all its resources are moved to the management cluster from kind when `clusterctl move` is executed.

## Resources

- [Slack thread](https://gigantic.slack.com/archives/C04AJ5FJHEK/p1669646715053339).

**Comment by calvix** [comment]
done, resources were actually in the MC but we just didn't have the apps that were agregating the resources, so added the stack ap to the management cluster fleet repo
