### ISSUE TITLE
Web UI permissions overview should allow for different group name prefixes

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1697]
## User story

- _As an admin, I want to inspect permissions for arbitrary RBAC groups_.

## Details

Currently the permission inspection UI in its "Group" mode restricts the user entry to group names starting with `customer:`. This is the name prefix assigned to all group names for users authenticated via OIDC via the Dex connector with the ID `customer`.

<img width="935" alt="image" src="https://user-images.githubusercontent.com/273727/204509701-ab608ac2-c4cc-404c-8e50-ec7080ac03c4.png">

This restriction already affects us (as Giant Swarm staff) currently when testing and using a different Dex connector, in our case `giantswarm`.

Soon we will allow for additional Dex connectors to be configured.

## Questions

- How about not restricting entry at all? In that case we should provide guidance, as users would be likely to omit the group prefix, leading to wrong results (in most cases: no permissions displayed).
  - Such guidance could be given for example if we don't find a `:` (colon) in the group name, in the form of an error message.
- Alternatively, can the web UI provide a list of all valid prefixes to choose from via e. g. a dropdown menu?
  - If the user has `list` access to RoleBinding and ClusterRoleBinding resources, we can collect prefixes from those. Might be a slow procedure. What about users who don't have access to these?

**Comment by gusevda** [comment]
The description looks correct to me. I would vote for the first option (without a restriction and with an error in case a group name doesn't contain a `:`). Additionally, we can have the field initially pre-filled with `customer:`, the same way we do it right now, but allowing a user to modify it. I think it would remind about the group name format.
