### ISSUE TITLE
Elastic File System (EFS) for CAPA

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1699]
## Vintage implementation (DONE)

Elastic File System (AWS NFS) is used by more and more customers  and we need to ensure that `efs-csi-driver` is working properly.

At the moment there are some problems which we need to address:

- the [documentation](https://docs.giantswarm.io/advanced/storage/efs/) is outdated and if you would simply follow the steps it doesn't work
- KIAM agent is interferring requests from `efs-csi-node` and doesn't allow to find the EC2 region because `/latest/dynamic/instance-identity/document` is not whitelisted as metadata service endpoint
- EFS IAM role is currently not created and needs to be created by customers
- CAPA clusters are currently not supported and we need to find a way how to create the IAM role.

For Vintage we can attach the EFS IAM role inside the TCCPN stack to create it like the Route53 Manager role, allowing it via KIAM and IRSA.

We can prepare `efs-csi-driver` similar to `kiam-app` and enable either service account annotation for IRSA or deployment annotation for KIAM

# CAPA implementation coming next 

For CAPA clusters we need to find a way how to prepare this IAM role in case customer wants to use EFS. One solution would using [`capa-iam-operator`](https://github.com/giantswarm/capa-iam-operator) but this only creates the IAM roles for the master and worker nodes but if we would want to us it with IRSA we would need a new operator which creates it.

**Comment by calvix** [comment]
CAPA is done

**Comment by calvix** [comment]
EKS docs in review https://github.com/giantswarm/docs/pull/1996

**Comment by calvix** [comment]
done
