### ISSUE TITLE
Control plane API through Kubernetes itself

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#17]
Replace our existing API with Kubernetes itself.

We would give our customers access to the Kubernetes API of the control plane and define roles for them so that they can see and edit the Custom resources we provide to manage the clusters and also see the components that manage the clusters.

First approach is to let the API talk to kubernetes directly instead of using the services in between. Later goal would be to remove the API in front of Kubernetes.

This has been discussed here: https://github.com/giantswarm/giantswarm/issues/4135

A related UX story can be found here: https://github.com/giantswarm/giantswarm/issues/4370

An idea to involve some customers early would be to give them access to a read-only role in the control plane.

All stories around more visibility into the system would be affected by this. In a positive way. Standard Kubernetes tooling (like kubectl) would give our users already much more insights of what is going on inside the control plane and its tenant clusters.

* https://github.com/giantswarm/giantswarm/issues/3524
* https://github.com/giantswarm/giantswarm/pull/2209
* https://github.com/giantswarm/giantswarm/issues/3579
* https://github.com/giantswarm/giantswarm/pull/2197
* https://github.com/giantswarm/giantswarm/issues/1959

Authentication for customers will also be affected

* https://github.com/giantswarm/giantswarm/pull/2211

These roadmap items would then be obsolete:

* https://github.com/giantswarm/giantswarm/issues/2653
* https://github.com/giantswarm/giantswarm/issues/1268

**Comment by snizhana-dynnyk** [comment]
I have created a new issue for public roadmap so closing this as a duplicate 
https://github.com/giantswarm/roadmap/issues/90
