### ISSUE TITLE
CAPA (private environments) - prometheus-meta-operator

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1703]
To implement monitoring for private environments in CAPA we need to make sure [prometheus-meta-operator](https://github.com/giantswarm/prometheus-meta-operator) works correctly and can reach out the the internet via the [Proxy interface](https://github.com/giantswarm/roadmap/issues/1467#issuecomment-1330411349).

**Comment by marieroque** [comment]
`alertmanager` doesn't reach `slack`:
```
level=info ts=2022-12-19T17:43:29.209Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config/alertmanager.yaml
level=error ts=2022-12-19T22:19:31.083Z caller=dispatch.go:354 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="team_ops_slack/slack[0]: notify retry canceled due to unrecoverable error after 1 attempts: channel \"#alert-test-goat\": unexpected status code 404: channel_not_found"
```

**Comment by marieroque** [comment]
`opsgenie` is provided on `goat`:


![Image](https://user-images.githubusercontent.com/9134338/208708120-4894794c-d7bd-4574-9fab-4512dfc3bec6.png)

**Comment by marieroque** [comment]
I created the slack channel `#alert-test-goat` because it didn't exist.

**Comment by marieroque** [comment]
Status OK on `pmo`:

`pmo`                 -->  `opsgenie`     OK
`alert-manager`  -->  `opsgenie`     OK
`alert-manager`  -->  `slack`           OK

**Comment by marieroque** [comment]
Still error on logs due to `goat-proxy` cluster that has not default-apps deployed:
https://github.com/giantswarm/roadmap/issues/1696

A part from that, no more error on `pmo`!

**Comment by TheoBrigitte** [comment]
Let's make sure we document all network call / domain being call out into https://docs.giantswarm.io/security/domain-allowlist/

**Comment by marieroque** [comment]
PR in `mc-bootstrap` repo to add remotewrite secret when MC is creating:
https://github.com/giantswarm/mc-bootstrap/pull/373

+ adding secret values (grafanaCloud apikey + username) in all lastpass folders required:
```
* Shared-Team Clippy\CAPZ\GS\common.secrets
* Shared-Team Phoenix\CAPA\GS\common.secrets
* Shared-Team Phoenix\CAPG\GS\common.secrets
* Shared-Team Rocket\CAPV\GS\common.secrets
* Shared-Team Rocket\CAPVCD\GS\common.secrets
```

**Comment by marieroque** [comment]
Since `grafana-cloud` secret deployed on `goat-prometheus` and `goatproxy-prometheus` namespaces, no more error in `prometheus-operator` :-)

**Comment by marieroque** [comment]
`prometheus-agent` errors on WC `goatproxy`:
```
ts=2023-01-04T14:30:15.746Z caller=dedupe.go:112 component=remote level=warn remote_name=6eb562 url=https://prometheus.goat.gaws.gigantic.internal/goatproxy/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://prometheus.goat.gaws.gigantic.internal/goatproxy/api/v1/write\": dial tcp: lookup prometheus.goat.gaws.gigantic.internal on 172.31.0.10:53: no such host"
```
