### ISSUE TITLE
CAPVCD cleanup script from cli

### ISSUE THREAD

**Issue by ericgraf** [giantswarm/roadmap#1706]
For mc-boostrap ci we need a cli cleanup script that can cleanup any cloud director left over resources from a failed previous run. 

Inputs:
 - installation name
 - cloud credentials

Expected cleanups:
 - Vapp with installation name ( this should delete all VMS )
 - Load balancer -> Virtual Services and Pool with installation name
 - NAT rules with installation name or cluster ID
 - Load balancer with any cluster id tied to it. ie nginx loadbalancer
 - Storage Disks left over

**Comment by vxav** [comment]
Edit to add a couple things.

Also, should we add something like a mutating webhook (or else) to prepent the name of the cluster to the PVCs?
Otherwise we don't really have a way to identify which cluster they belong to if the cluster is gone.

**Comment by ericgraf** [comment]
Repo: https://github.com/giantswarm/cloud-director-cli

**Comment by ericgraf** [comment]
The current implementation of cd-cli works for initial implementation . 

@vxav We should open another issue to track adding resource tags and using that as a reference. That is something we will for sure need and will be helpful for other tooling. 

I'm closing this issue since the initial requirement I would consider completed.

**Comment by vxav** [comment]
Nice!

What is a resource tag?
