### ISSUE TITLE
`kubeadm` token not renewed on CAPA

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1720]
## Issue

`kubeadm` token is not renewed on CAPA and new nodes are unable to join the cluster. This happened on `grizzly`.

We are supposed to already have a fix for this, but for some reason it didn't work. We think it's probably because the cluster was created before the fix was rolled out, but it's just guessing.

The issue needs to be confirmed.

**Comment by bdehri** [comment]
@alex-dabija Does this also happen on WCs?

**Comment by tuladhar** [comment]
On grizzly MC, we tested scaling the control planes node for berk1 WC, and they were able to join the cluster.

```
puru@giantswarm (gs-grizzly-berk1-clientcert) ~/grizzly> kubectl get nodes
NAME                                          STATUS   ROLES                  AGE     VERSION
ip-10-31-120-92.eu-west-2.compute.internal    Ready    control-plane,master   91s     v1.23.13
ip-10-31-186-244.eu-west-2.compute.internal   Ready    control-plane,master   17m     v1.23.13
ip-10-31-220-52.eu-west-2.compute.internal    Ready    control-plane,master   2m57s   v1.23.13
ip-10-31-255-27.eu-west-2.compute.internal    Ready    control-plane,master   22m     v1.23.13
ip-10-31-83-82.eu-west-2.compute.internal     Ready    control-plane,master   19m     v1.23.13
```

**Comment by calvix** [comment]
@tuladhar the issue only occurs for MachinePool as for `control-plane` node a new kubeadmconfig is generated for each new machine and the token is always fresh

**Comment by bdehri** [comment]
We took a look at cluster-api repository with @tuladhar . Refreshment of the token secrets is dependent existence of the token secret itself which explains why we had problems with our Capa MCs at the moment. But I could not find what deletes the secrets in the first place. I have checked api-server audit logs but I could not found anything there.

**Comment by bdehri** [comment]
https://github.com/kubernetes-sigs/cluster-api/pull/7717

**Comment by bdehri** [comment]
PR is merged, waiting for a release.

**Comment by bdehri** [comment]
It will be part of 1.4 release, custom kubeadm controller is deployed to all CAPA MCs with flux enabled.
