### ISSUE TITLE
CAPA SSH access for private clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1721]
## Story

_-As a cluster admin, I want to be able to SSH into all the cluster's nodes in order to investigate cluster problems._

## Background

Every CAPA public cluster (workload or management) has bastion hosts which are used to get access to all the cluster's nodes. Due to IP space limitations and Giant Swarm VPN routing limitations we can't do the same for private clusters.

## Possible solutions

- Bastion hosts on private separate subnets only for management clusters. Cluster nodes can be accessed through Giant Swarm's VPN -> transit gateway -> cluster node;
- [EC2 instance connect](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Connect-using-EC2-Instance-Connect.html);
- SSH via Teleport. See [Miro board](https://miro.com/app/board/uXjVOraFbrA=/) for possible solutions.

## TODOs

- [ ] Decide on which option to implement;
- [ ] ...;

**Comment by calvix** [comment]
making `bastion` run on private cluster with private IP should allow us to use same approach as for the public bastion ssh, no fixes will be needed.

**Comment by calvix** [comment]
changes for private bastions are released in `0.20.2` of `cluster-aws` need to upgrade `goat` to that version to test properly for MC, for WC it was already tested

**Comment by calvix** [comment]
test on `goat` private bastion works if the ssh port is allowed
