### ISSUE TITLE
Hold a Knowledge Sharing about RBAC for Rainbow

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1725]
towards enablement of Rainbow on [this](https://github.com/giantswarm/roadmap/issues/1711) and [this](https://github.com/giantswarm/roadmap/issues/1666)

**Comment by ljakimczuk** [comment]
RBAC architecture has been documented here: https://intranet.giantswarm.io/docs/security/rbac-architecture/

**Comment by gianfranco-l** [comment]
the doc is done, once we share the process with Rainbow and send official announcement for team to take over the RBAC management, this ticket can be closed

**Comment by ljakimczuk** [comment]
Hey @giantswarm/team-rainbow, as it's been a week with no questions to this issue, nor to the related [RBAC docs](https://intranet.giantswarm.io/docs/security/rbac-architecture/), I think we could finally announce this part of RBAC management is taken over by your team. What do you think?

**Comment by ljakimczuk** [comment]
It has been announced here https://gigantic.slack.com/archives/C0251EQJR/p1676974967035569
