### ISSUE TITLE
Allow Custom SA in cert-manager

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#1730]
**Problem or Ask**
Converting from linked customer request. As a customer, I'd like the ability to pass upstream values.yaml changes to allow setting custom service accounts for a GCP installation's cert-manager. Use-case is to run ClusterIssuer with DNS-verification.

**Comment by TobiasLierzer** [comment]
any update on this?

**Comment by TobiasLierzer** [comment]
# Requirement
I as a customer run GiantSwarm Clusters on GCP. I want to use DNS challenges against GCP Cloud DNS to verify certificates.
I can do this with Access Keys from GCP Service Accounts. But handling Access Keys propose a risk. I therefore want to use Workload Identity Federation to authenticate against the GCP API.

For this, three things need to happen on cert-manager (more specifically `cert-manager-controller`):
1. I need to be able to set a GCP SA annotation on the K8S SA for cert-manager
2. cert-manager-controller needs a label to inject GCP secrets
3. the PSP for cert-manager needs to allow projected volumes

# Problem
1. cert-manager is an app deployed and managed by GiantSwarm. (I as a customer cannot change that)
2. cert-manager can only be installed into a cluster once (I as a customer cannot get my own)
3. cert-manager currently does not allow the required changes above to work with Workload Identity Federation

**Comment by weatherhog** [comment]
We should also focus on AWS or all provider in general.

**Comment by ced0ps** [comment]
This feature was merged with [release 2.18.1](https://github.com/giantswarm/cert-manager-app/releases/tag/v2.18.1)
