### ISSUE TITLE
Allow Custom SA in external-dns

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#1731]
**Problem or ask:**
Converting from linked customer request. As a customer, I'd like the ability to use a custom service account in order to own their own to the SA annotation. The current [link](https://github.com/giantswarm/external-dns-app/blob/master/helm/external-dns-app/templates/serviceaccount.yaml#L9) evaluates if the deployment is gcp but then has the Giant Swarm SA value hardcoded. The new implementation of external-dns needs to be able to run from a different project because we want to run all external-dns instances mapped to one serviceaccount, which we can add during cluster provisioning right away.

**Comment by TobiasLierzer** [comment]
This use-case is not valid for us anymore. 
We run the DNS hosted zone in the same project and use the GS SA as the permissions are the same.

**Comment by mcharriere** [comment]
All done. [Release 2.22](https://github.com/giantswarm/external-dns-app/releases/tag/v2.22.0) includes this feature. Docs are [here](https://docs.giantswarm.io/advanced/external-dns/gcp-custom-sa/).
