### ISSUE TITLE
mc-bootstrap fix automatically computing no-proxy for config repo for kyverno webhook

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1734]
currently, the mc bootstrrap set for the app the values only with MC_NO_PROXY which does not contain calculated ranges from the service range and other, so once flux is deployed it will stop working properly

**Comment by calvix** [comment]
should be covered with https://github.com/giantswarm/kyverno-policies-connectivity/pull/38

**Comment by calvix** [comment]
once its merged i will remove fix that I implemented in the `mc-bootstrap`
