### ISSUE TITLE
Flaky test in kubectl-gs

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1735]
Some tests, which involve resource age calculation are flaky.

Expected age is 0s, actual age is 1s.

Possible cause:
Could be caused by a delay between test setup and execution.

Suggested fix:
Inject resource creation time when the test is executing, not when it is being defined.

**Comment by marians** [comment]
This is coming up again.

Examples:

- https://app.circleci.com/pipelines/github/giantswarm/kubectl-gs/4658/workflows/608cf501-46ba-486f-ba53-194ab20cce8a/jobs/7794
- https://app.circleci.com/pipelines/github/giantswarm/kubectl-gs/4655/workflows/799114aa-a30b-4fc7-aa01-9204e0be9f51/jobs/7787

```
?   	github.com/giantswarm/kubectl-gs/v2/cmd/get/nodepools/provider	[no test files]
--- FAIL: Test_run (0.09s)
    --- FAIL: Test_run/case_1:_get_orgs_for_non-admin (0.08s)
        runner_test.go:134: value not expected, got:
               strings.Join({
              	"NAME     ORG NAMESPACE   AGE\ntest-2   org-test-2      ",
            - 	"0",
            + 	"1",
              	"s\n",
              }, "")
    --- FAIL: Test_run/case_4:_get_org_by_name (0.00s)
        runner_test.go:134: value not expected, got:
               strings.Join({
              	"NAME     ORG NAMESPACE   AGE\ntest-1   org-test-1      ",
            - 	"0",
            + 	"1",
              	"s\n",
              }, "")
FAIL
FAIL	github.com/giantswarm/kubectl-gs/v2/cmd/get/orgs	0.203s
```

**Comment by marians** [comment]
@vvondruska I found the issue we had for this and added the info above.

**Comment by weatherhog** [comment]
closing
