### ISSUE TITLE
cluster-app-cloud-director values schema should cover all object properties

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1738]
Towards ability to create a cluster via the web UI: https://github.com/giantswarm/roadmap/issues/1181

Currently the cluster app schema misses the properties for these objects:

- `.nodePools`
- `.kubectlImage`
- `.nodeClasses`

In order to generate a UI for entry of this data, and for validation of submitted values, the schema must be completed.

**Comment by marians** [comment]
Could not find any information regarding the structure of the `.kubectlImage` content.

**Comment by gawertm** [comment]
@vxav FYI

**Comment by vxav** [comment]
I don't know what the purpose of that field is.

**Comment by vxav** [comment]
@marians here's an example from aws.
https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/values.yaml#L95

**Comment by vxav** [comment]
https://github.com/giantswarm/cluster-cloud-director/pull/68

**Comment by vxav** [comment]
Merged.
