### ISSUE TITLE
`opsctl` can't open cloud provider for a CAPA MC

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1741]
## Issue

`opsctl` can't open cloud provider for a CAPA MC.

```
 λ opsctl open -i grizzly -a cloudprovider --level=debug
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:92","level":"debug","message":"Setting up employees service with config {Logger:0xc000490a20 GitHubToken:*******************************
*****i0j9 Branch: ConfigDir:}","time":"2022-12-05T08:42:49.435702+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:113","level":"debug","message":"Setting up repo service with config {Logger:0xc000490a20 GitHubToken:***********************************
*i0j9 RepoURL:git@github.com:giantswarm/installations.git Branch:master ConfigDir: NoCache:false}","time":"2022-12-05T08:42:49.892099+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:98","level":"debug","message":"Setting up reposervice with config {CacheDir:/home/fciocchetti/.config/opsctl RepoName:installations To
ken:************************************i0j9}","time":"2022-12-05T08:42:49.892262+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:133","level":"debug","message":"Setting up releases service with config {Logger:0xc000490a20 GitHubToken:*******************************
*****i0j9 Repo:releases Owner:giantswarm Branch:}","time":"2022-12-05T08:42:50.285556+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:151","level":"debug","message":"Setting up config service with config {Logger:0xc000490a20 GitHubToken:*********************************
***i0j9 Branch: ConfigDir:}","time":"2022-12-05T08:42:50.285608+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-05T08:42:50.553048+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-05T08:42:50.553325+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-05T08:42:50.554009+00:00"}
Accessing control plane cloud provider console
Error: Empty arn
        /home/runner/work/opsctl/opsctl/command/open/aws.go:58
        /home/runner/work/opsctl/opsctl/command/open/command.go:218
        /home/runner/work/opsctl/opsctl/command/open/command.go:160
        /home/runner/work/opsctl/opsctl/main.go:57

To increase verbosity, re-run with --level=debug

Error: exit status 2
```

The same problem is present for `golem`:
```
❯ opsctl open -i golem --app cloudprovider
Accessing control plane cloud provider console
Error: Empty arn
        /home/alex/work/giantswarm/opsctl/command/open/aws.go:58
        /home/alex/work/giantswarm/opsctl/command/open/command.go:218
        /home/alex/work/giantswarm/opsctl/command/open/command.go:160
        /home/alex/work/giantswarm/opsctl/main.go:57

To increase verbosity, re-run with --level=debug
```

**Comment by alex-dabija** [comment]
As a workaround you can specify the managemnt cluster as the workload cluster (a CAPA MC is is just like any other workload cluster):

```
❯ opsctl open -i grizzly --app cloudprovider --workload-cluster grizzly
```

**Comment by fiunchinho** [comment]
This would fix it for newly created MCs https://github.com/giantswarm/mc-bootstrap/pull/361

**Comment by fiunchinho** [comment]
Fixed the other existing MC that had missing AWS details https://github.com/giantswarm/installations/pull/2095

**Comment by AndiDog** [comment]
This works for me without fixes, by the way (yes, I also use the lambda symbol in my shell):

```
λ opsctl open -i grizzly -a cloudprovider --level=debug
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:92","level":"debug","message":"Setting up employees service with config {Logger:0x140004af410 GitHubToken:************************************MWTM Branch: ConfigDir:}","time":"2022-12-12T17:31:48.29908+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:113","level":"debug","message":"Setting up repo service with config {Logger:0x140004af410 GitHubToken:************************************MWTM RepoURL:git@github.com:giantswarm/installations.git Branch:master ConfigDir: NoCache:false}","time":"2022-12-12T17:31:48.607514+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:98","level":"debug","message":"Setting up reposervice with config {CacheDir:/Users/asommer/.config/opsctl RepoName:installations Token:************************************MWTM}","time":"2022-12-12T17:31:48.614803+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:133","level":"debug","message":"Setting up releases service with config {Logger:0x140004af410 GitHubToken:************************************MWTM Repo:releases Owner:giantswarm Branch:}","time":"2022-12-12T17:31:48.902137+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:151","level":"debug","message":"Setting up config service with config {Logger:0x140004af410 GitHubToken:************************************MWTM Branch: ConfigDir:}","time":"2022-12-12T17:31:48.902507+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-12T17:31:49.223326+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-12T17:31:49.223841+00:00"}
{"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-12T17:31:49.224452+00:00"}
Accessing control plane cloud provider console
Role to assume: `arn:aws:iam::242036376510:role/GiantSwarmAdmin`
Assuming role GiantSwarmAdmin in account 242036376510 by opening

  https://signin.aws.amazon.com/switchrole?account=242036376510&roleName=GiantSwarmAdmin&displayName=grizzly+control+plane
```

**Comment by fiunchinho** [comment]
> This works for me without fixes, by the way (yes, I also use the lambda symbol in my shell):
> 
> ```
> λ opsctl open -i grizzly -a cloudprovider --level=debug
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:92","level":"debug","message":"Setting up employees service with config {Logger:0x140004af410 GitHubToken:************************************MWTM Branch: ConfigDir:}","time":"2022-12-12T17:31:48.29908+00:00"}
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:113","level":"debug","message":"Setting up repo service with config {Logger:0x140004af410 GitHubToken:************************************MWTM RepoURL:git@github.com:giantswarm/installations.git Branch:master ConfigDir: NoCache:false}","time":"2022-12-12T17:31:48.607514+00:00"}
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:98","level":"debug","message":"Setting up reposervice with config {CacheDir:/Users/asommer/.config/opsctl RepoName:installations Token:************************************MWTM}","time":"2022-12-12T17:31:48.614803+00:00"}
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:133","level":"debug","message":"Setting up releases service with config {Logger:0x140004af410 GitHubToken:************************************MWTM Repo:releases Owner:giantswarm Branch:}","time":"2022-12-12T17:31:48.902137+00:00"}
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/primary.go:151","level":"debug","message":"Setting up config service with config {Logger:0x140004af410 GitHubToken:************************************MWTM Branch: ConfigDir:}","time":"2022-12-12T17:31:48.902507+00:00"}
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-12T17:31:49.223326+00:00"}
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-12T17:31:49.223841+00:00"}
> {"caller":"github.com/giantswarm/opsctl/v2/service/installation/repo/repo.go:353","level":"debug","message":"updateRepoIfNeeded() called","time":"2022-12-12T17:31:49.224452+00:00"}
> Accessing control plane cloud provider console
> Role to assume: `arn:aws:iam::242036376510:role/GiantSwarmAdmin`
> Assuming role GiantSwarmAdmin in account 242036376510 by opening
> 
>   https://signin.aws.amazon.com/switchrole?account=242036376510&roleName=GiantSwarmAdmin&displayName=grizzly+control+plane
> ```
> 
> Does that mean the missing info was already added for `grizzly`?

Yes https://github.com/giantswarm/installations/pull/2091
