### ISSUE TITLE
Scale `tornado`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1742]
## Task

Scale `tornado` because the worker nodes are running out of CPU. Either bump the instance type to the next size or add additional nodes.

The following instance types are used by the cluster:
- control plane nodes: `m5.xlarge`;
- worker nodes: `m5.xlarge`.

## Resources

- [Slack thread](https://gigantic.slack.com/archives/C04AJ5FJHEK/p1670255806006609);
- [Slack announcement](https://gigantic.slack.com/archives/C04AJ5FJHEK/p1670260722245419).

**Comment by AverageMarcus** [comment]
Scaled all three machinepools to have a min of 2 replicas (needed anyway for upgrade stability).
