### ISSUE TITLE
Test workload cluster creation on `thunder`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1743]
## Task

Test workload cluster creation on `thunder`.

TODOs:
- [x] Determine which CIDRs can be used by workload clusters;
- [ ] ...;

**Comment by alex-dabija** [comment]
Blocked by https://github.com/giantswarm/giantswarm/issues/24871.

**Comment by alex-dabija** [comment]
Waiting on the customer to provide a list of CIDRs which can be used through their transit gateway.

**Comment by calvix** [comment]
current testing cluster `vaclav-thunder` - range `10.16.4.0/22`

**Comment by calvix** [comment]
current issue is `no_proxy` settings that needs to be set  for app-operator and `etcd-backup-operator` to properly access the WC cluster API without going thru the proxy

but both applications  still need access to outside components so they do need proxy config

**Comment by calvix** [comment]
I give it a try and added global `eu-central-1.elb.amazonaws.com` to  webhook `no_proxy` config and so far everything seems to work.

**Comment by calvix** [comment]
created  a cluster `dev00` for customer with range `10.16.4.0/22`

**Comment by calvix** [comment]
cluster creation work
