### ISSUE TITLE
Upgrade `tornado` to v0.20.1 from v0.18.0

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1753]
## Task

Upgrade `tornado` to v0.20.1 from v0.18.0. The customer needs to be notified before starting the upgrade.

## Background

The customer is impacted by the IRSA placeholder bug and it's blocking their progress.

**Comment by AverageMarcus** [comment]
Cluster has been upgraded but wasn't without issues.

Even though the service account token flag was correctly replaced there was still a lot of issues with pods having authentication errors when calling the apiserver.

Pretty much every pod in the cluster needed restarting.
