### ISSUE TITLE
Upgrade `grizzly` to `v0.20.2` from `v0.18.0`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1756]
## Task

Upgrade `grizzly` to `v0.20.2` from `v0.18.0`.

**Comment by tuladhar** [comment]
Pre-check:
- Ensure machine pool scaling works prior to upgrade.

Potential pitfalls to be aware:
- IRSA placeholder might pop up

**Comment by tuladhar** [comment]
Done, grizzly upgraded.

Discussion thread:
- https://gigantic.slack.com/archives/C04AJ5FJHEK/p1672647090376579
