### ISSUE TITLE
Automatically handle NotReady kubelets

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#176]
## User Story

_- As a person doing oncall, I want kubelets in a NotReady status to be automatically handled, so I don't need to._

## Details, Background

Currently, when a kubelet entires a NotReady status (and doesn't exit it on its own in time), a human gets alerted and we take care of the failing kubelet. With the increasing number of kubelets under our responsibility, this becomes fatiguing for operations, as well as a poor customer experience.

If a kubelet that had entered a `NotReady` status (and wasn't recovering) was automatically handled (e.g: by reboot, terminating the instance, etc), this would be better for operations and customers.

## Blocked by / depends on

Nothing I'm aware of.

## Providers
- [x] AWS
- [x] Azure
- [x] KVM

**Comment by JosephSalisbury** [comment]
fyi @marians @MartaD, from discussion in sig product sync on monday

**Comment by JosephSalisbury** [comment]
this is just a big ol' tracker, feel free to throw away and use other issues or w/e <3

**Comment by MartaD** [comment]
cc: @nprokopic

**Comment by brinker211** [comment]
KVM team will add feedback from kvm perspective and do the needful to continue conversation with product/teams.

**Comment by alex-dabija** [comment]
This is already implemented for AWS. The documentation on how to enable the feature is available at: https://docs.giantswarm.io/basics/automatic-termination-of-bad-nodes/ .

**Comment by marians** [comment]
@yulianedyalkova Is this released already, and if yes, should that info be added to  https://docs.giantswarm.io/basics/automatic-termination-of-bad-nodes/ ?

@MartaD According to the above docs page, this is implemented on Azure. However, the box above is not yet ticked.

If this is in fact done and released for all providers, the issue could be closed.

**Comment by yulianedyalkova** [comment]
@marians it's not released yet but I forgot about the docs - I'll update them. Thanks!

**Comment by MartaD** [comment]
@marians Azure v13.1.0 is not released yet, docs were updated immediately to not forget about it once it is released.

**Comment by yulianedyalkova** [comment]
Feature is included in release `v14.0.0` for KVM and official documentation is updated. Anything else that needs to be done on this issue or should I close it?
