### ISSUE TITLE
Bare-bones dns resolver rules operator

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1761]
## Story

_-As a developer working on the DNS resolver rules operator, I want to have the prerequisite aspects of working on a new operator already in place before I start working on user stories in order to quickly iterate and test my changes on CAPA management clusters._

## TODOs

- [x] Propose & get agreement from the team on the operator's name;
- [x] Create a bare-bones operator without any additional functionality besides that it compiles and runs without crashing (basically, a dump empty loop);
- [x] Release pipeline;
- [x] Deployment pipeline.

**Comment by alex-dabija** [comment]
The operator will be called `aws-resolver-rules-operator`.

**Comment by bdehri** [comment]
* https://github.com/giantswarm/aws-resolver-rules-operator/pull/1
* https://github.com/giantswarm/github/pull/737
