### ISSUE TITLE
Add support for polymorphic values of the 'managementCluster' config property in Rainbow's installable apps

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1762]
Rainbow maintains a few projects, which can be installed to workload clusters as apps.

Some of these projects define the `managementCluster` property in their Helm Values schema. To ensure that they can also be installed on clusters in Capi installations they need to support string values of the `managementCluster` property.

This seems to apply to the following Rainbow projects from this list: https://github.com/giantswarm/github/blob/master/repositories/team-rainbow.yaml

- `api`: defines additional properties in the `managementCluster` object
- `dex-operator`
- `happa`: defines additional properties in the `managementCluster` object
- `kyverno-policies-ux`: has `managementCluster` in values and schema, but does not use it

Another question is if all of these projects are/should be installable to workload clusters.

**Comment by kuosandys** [comment]
From standup:
- the above-mentioned apps are not meant to be installed in a workload cluster, but they're currently in the giantswarm catalog
- maybe we should instead look into preventing these apps from being displayed/communicated as installable in workload clusters

**Comment by weatherhog** [comment]
closing
