### ISSUE TITLE
Add support for cluster API URLs on domains other than GS default domain to kubectl-gs

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1763]
Kubectl-gs validates Kubernetes API URLs during login and uses them to derive URLs of various components, which are required during the login process.

The validation expects a certain structure of the API URL, and it also requires that it runs on a specific domain.

To increase usability of kubectl-gs the domain restriction needs to be removed from the validation.

**Comment by vvondruska** [comment]
A quick fix has been released in kubectl-gs v2.29.3.
