### ISSUE TITLE
Improve dex operator credential management

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1764]
For now, improve dex-operator script for credential creation

- [x] refactor credential management into packages
- [x] manage input and output files to match config
- [x] credentials need to be displayed as a string
- [ ] #2172
- [x] azure
  - [x] update case
  - [x] create case
    - [x] admin consent step
  - [x] cleanup
- [x] github
   - [x] create case: app-manifest-flow implementation
   - [ ] dex-app should be named dex-app
   - [x] install the app within the workflow
   - [x] clean up
   - [x] improve github app manifest flow template design
   - [x] allow more callback URLs
   - [ ] include renaming in template maybe
- [ ] roll out new credentials 
- [ ] #2173

Later:
look into workload identity

At the moment, dex operator is configured via a secret in the config repository
although there is a script to create new credentials, creation and rotation of secrets is manual and reduces the benefit we get from the automation for oauth apps.

let's find an approach that is secure and reduces toil

from call with clippy: maybe workload identity can be interesting https://azure.github.io/azure-workload-identity/docs/

**Comment by anvddriesch** [comment]
Team clippy is planning on making azure identity webhook an installable app: https://github.com/giantswarm/giantswarm/issues/25041

**Comment by anvddriesch** [comment]
https://github.com/giantswarm/giantswarm/issues/24578
we may be able to use this app in the meantime
