### ISSUE TITLE
Add option to `flux-app` to disable force push of image automations controller

### ISSUE THREAD

**Issue by uvegla** [giantswarm/roadmap#1773]
In `v0.27.0` if Flux's image automation controller: https://github.com/fluxcd/image-automation-controller/blob/main/CHANGELOG.md#0270 they changed:

```text
Starting from this version ImageUpdateAutomation objects with a spec.PushBranch specified will have the push branch refreshed automatically via force push. To opt-out from this behaviour, start the controller with: --feature-gates=GitForcePushBranch=false.
```

Following up on the change log it was added in https://github.com/fluxcd/image-automation-controller/pull/453 to fix https://github.com/fluxcd/image-automation-controller/issues/450.

This upgrade was released in GS `flux-app`: https://github.com/giantswarm/flux-app/releases/tag/v0.20.0 

Add support to `flux-app` for the flag: `--feature-gates=GitForcePushBranch=false`.

**Comment by ljakimczuk** [comment]
This is now available in the [v0.20.2](https://github.com/giantswarm/flux-app/releases/tag/v0.20.2) release.
