### ISSUE TITLE
`etcd` backups for `thunder`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1779]
## Task

Ensure that `etcd` backups are enabled for `thunder`.

## TODOs

- [x] Enable `etcd` backups for `thunder`;
- [x] Verify `etcd` backups are pushed to S3.

**Comment by calvix** [comment]
![Screenshot from 2022-12-15 12-53-35](https://user-images.githubusercontent.com/7136358/207853091-1e69a3a3-c51a-46f5-8a54-f3f10f4087a9.png)

**Comment by calvix** [comment]
MC has backups WC dont as we face the issue with the no_proxy setting similar to  app operator, but that will be sorted in different issue
