### ISSUE TITLE
Allow Rewrite rule in main Coredns block

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#179]
**Is your feature request related to a problem? Please describe.**

Feature request to allow Coredns rewrite rule to go in main server block and not in customer will enable easier automation for customers. 

**Describe the solution you'd like**

Move `rewrite` in Coredns configmap from needing to be in `custom` block to the main block.

Example of desired solution:
```
data:
  values: |
    configmap:
      rewrite: original.url new.url
```

**Describe alternatives you've considered**

Putting in a `custom` block of values will allow the rewrite rule.

**Additional context**

[Giant Swarm coredns config reference](https://docs.giantswarm.io/guides/advanced-coredns-configuration/#configuration-reference)

**Comment by puja108** [comment]
Adidas issue for this https://github.com/giantswarm/adidas/issues/572

**Comment by puja108** [comment]
I think this was done already
