### ISSUE TITLE
Workload cluster release process (with CAPI)

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1791]
This depends on the https://github.com/giantswarm/giantswarm/issues/25443

This is not about the automation but how teams create releases and customers "use" releases.

 - [ ] Define how a team creates a cluster release
 - [ ] Define how the workflow for customers would look like

**Comment by Rotfuks** [comment]
Will be addressed with https://github.com/giantswarm/roadmap/issues/2522
