### ISSUE TITLE
Document prometheus-agent

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1792]
Towards: https://github.com/giantswarm/giantswarm/issues/23130

We need to document the changes introduced with prometheus-agent as this as various implication and impact.

This documentation would mainly be aimed at customer, since this will impact them, so we need to describe what changes for customer.
We also need to describe how and why we came to this conclusion in order to provide more context and help understand why this is happening.

This documentation should be public and live somewhere there https://github.com/giantswarm/docs/tree/main/src/content/ui-api/observability which translate into this public url https://docs.giantswarm.io/ui-api/observability/

**Comment by QuentinBisson** [comment]
https://github.com/giantswarm/docs/pull/1709
