### ISSUE TITLE
Autoscaling CAPZ Clusters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1793]
### Motivation
For cost and performance optimisation customers want their cluster sizes more dynamic. We already have autoscaling of machines inside a cluster in our vintage providers and should make sure to match that feature also in CAPZ

### Todo

- [ ] conceptphase

### Outcome
- CAPZ clusters automatically scale in size depending on configurable metrics and boundaries, leading to a better cost control for customers but also optionally better peak performances of the clusters overall

**Comment by Rotfuks** [comment]
We already had a first discussion on it: https://gigantic.slack.com/archives/C04887ZSU20/p1670926088947149


**Conclustion:** 
- All infos around cluster-autoscaler in machinepools issues can be found here: 
https://github.com/giantswarm/giantswarm/issues/19313
-- We should document all further technical infos into that ticket
- CAPZ already has a feature merged for managed machine pools: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2444
-- But it is currently being refactored to match the overall CAPI approach: https://github.com/kubernetes-sigs/cluster-api/pull/7107
- CAPZ already has an issue open for support of autoscaling on unmanaged machine pools: 
https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2588

**Comment by primeroz** [comment]
Let's also remember to double check `scaling to 0` support when the code support lands

**Comment by Rotfuks** [comment]
Helpful Slack Thread in the CAPZ upstream community: https://kubernetes.slack.com/archives/CEX9HENG7/p1674083817745989

**Comment by Rotfuks** [comment]
As Vintage is looking into Karpenter (https://github.com/giantswarm/flexshopper/issues/359) this might also be an interesting tool for this capability.

**Comment by Rotfuks** [comment]
Parent Duplication of https://github.com/giantswarm/roadmap/issues/1376
