### ISSUE TITLE
AWS NTP server as the default

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1800]
## Story 

_-As a cluster admin, I want the system clock to be synced for all private cluster nodes in order to have a well behaved functioning cluster._

## Background

Currently, our CAPA Ubuntu images use the default NTP servers. These are not accessible in a private environment with no Internet access.

A few components which run on CAPA machines require the clocks to be synced:
- `etcd` stops working if the clocks drift;
- `net-exporter` is trying to access public NTP servers;

AWS provides the Amazon Time Sync Service via NTP which is locally accessible at `169.254.169.123`. More details are available in the following [blog post](https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/).

## Tasks

- [ ] Configure the default system NTP server to be `169.254.169.123`
- [ ] Configure `net-exporter` to query Amazon's NTP server: `169.254.169.123`

## Resources

- [Amazon Time Sync Service blog post](https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/);

**Comment by bdehri** [comment]
* https://github.com/giantswarm/cluster-aws/pull/189
* https://github.com/giantswarm/config/pull/1466
* https://github.com/giantswarm/config/pull/1467
