### ISSUE TITLE
Update docker-kubectl image in Cluster API apps

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#1808]
Update `docker-kubectl` image that we use in Cluster API apps to install CRDs.

According to [kubectl version skew policy](https://kubernetes.io/releases/version-skew-policy/#kubectl):

> `kubectl` is supported within one minor version (older or newer) of kube-apiserver.

Which `kubectl` version we need?

- Vintage MCs are currently on Kubernetes `v1.24.x`.
- Also, ideally, for the new CAPI clusters we can go with the latest Kubernetes version, but we still have some CAPI cloud MCs on `v1.23.x`, and onprem MCs on even older `v1.22.x`.

Therefore, in order to respect the `kubectl` version skew policy, the latest `docker-kubectl` image that we can use is different for every app:

- [x] Update `docker-kubectl` image in `cluster-api-app` to the latest `v1.23.x` (one minor older than vintage MCs, same as cloud CAPI MCs, one minor newer than onprem CAPI MCs)
- [x] Update `docker-kubectl` image in `cluster-api-provider-azure-app` to the latest `v1.25.x` (one minor newer than vintage Azure MCs, one minor newer than CAPZ MCs)
- [x] Update `docker-kubectl` image in `cluster-api-provider-aws-app` to the latest `v1.24.x` (same as vintage AWS MCs, one minor newer than CAPA MCs)
- [x] Update `docker-kubectl` image in `cluster-api-provider-gcp-app` to the latest `v1.24.x` (one minor newer than CAPG MCs)
- [x] Update `docker-kubectl` image in `cluster-api-provider-openstack-app` to the latest `v1.23.x` (one minor newer than CAPO MCs)
- [x] Update `docker-kubectl` image in `cluster-api-provider-cloud-director-app` to the latest `v1.23.x` (one minor newer than CAPVCD MCs)

**Comment by nprokopic** [comment]
Closing with created follow up issues (see links above)

**Comment by gawertm** [comment]
@nprokopic wont do it for OpenStack anymore but will check for vsphere (CAPV) as we just picked up CAPV work again

**Comment by nprokopic** [comment]
Yeah I figured that OpenStack will not be done probably. I think I checked some time ago CAPV and I didn't see that it was using `docker-kubectl` image for installing CRDs, so I didn't put it to the list here.

**Comment by gawertm** [comment]
yeah, we stopped to work on CAPV like a year ago and just start to update all the repos again. will have a look :)
