### ISSUE TITLE
Simplify AWS account preinstallation (IAM resources)

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#181]
**Is your feature request related to a problem? Please describe.**

AWS Customers need to do multiple steps to provisions the basic IAM resources for initial configuration of their accounts.

**Describe the solution you'd like**

Create a Cloud Formation template that provision all IAM resources needed. 

**Describe alternatives you've considered**

We have already the guide to do it manually and a terraform helper but still requires unnecessary actions.

**Comment by fiunchinho** [comment]
@pipo02mix can we close this one now that you merged https://github.com/giantswarm/giantswarm-aws-account-prerequisites/pull/97?
