### ISSUE TITLE
Add more advanced chart tests to rbac-operator

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#1812]
We already implemented basic chart tests for rbac-operator.
It would be sensible to implement more advanced ones in the future, as mentioned [here ](https://github.com/giantswarm/rbac-operator/pull/362#pullrequestreview-1222543105).

**Comment by mogottsch** [comment]
Antonia and I had a knowledge sharing session about `rbac-operator`. We decided to implement simple smoke tests for each controller contained in `rbac-operator`. The tests should check whether each controller is running at all by confirming that it created at least one of the expected resources.
