### ISSUE TITLE
Flag `kubectl gs template app --organization` hidden from help text but is needed

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#1815]
***Towards https://github.com/giantswarm/roadmap/issues/1787***

### Description

`kubectl gs template app` for a CAPI cluster produces the wrong namespace. The hidden flag `--organization` must be used, just [as recommended for creating the CAPI cluster](https://docs.giantswarm.io/getting-started/capa-wlcluster-creation/). Therefore, let's unhide that flag so it shows up in `kubectl gs template app --help`.

### TODO

- [ ] Unhide the flag in the given command, and also check if other commands should have it
- [ ] Update changelog

**Comment by weatherhog** [comment]
parent issue got closed. Also closing this one
