### ISSUE TITLE
Stable and well-tested release of node-exporter-app

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#1816]
**Requirements:**
- Release new version of node-exporter-app that is well tested and fixes the bug introduced in v1.14.0 that come along from master.

Thread: https://gigantic.slack.com/archives/C01176DKNP4/p1671783652540999

**Comment by alex-dabija** [comment]
The work for this issue is being done as part of https://github.com/giantswarm/roadmap/issues/1811 .
