### ISSUE TITLE
aws-network-topology-operator image fails push to AliYun

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#1822]
```
11a66f2c: Preparing 
denied: requested access to the resource is denied
The push refers to repository [registry-intl.***********.aliyuncs.com/giantswarm/aws-network-topology-operator]
```

Since the push also failed previously (first fix attempt: https://github.com/giantswarm/aws-network-topology-operator/pull/74), this probably didn't work at all before. Maybe the image repo is just missing.

([our chat](https://gigantic.slack.com/archives/C02JTRT152L/p1672763582905219))

**Comment by alex-dabija** [comment]
We agreed to drop the image push to AliYun CI jobs because CAPA doesn't work in China and requires additional development effort.
