### ISSUE TITLE
Remove silence from `thunder / dev00`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1825]
## Task

Remove silence from `thunder / dev00` once ingress to MC is allowed.

Towards [epic](https://github.com/giantswarm/roadmap/issues/1650).

## Background

Not all firewall rules were configured when the cluster was created, but they are in place now.

## Links

- [Silences repo](https://github.com/giantswarm/silences/);
- [Customer Slack thread](https://gigantic.slack.com/archives/C5PDDBBDG/p1671109688866529).

**Comment by fiunchinho** [comment]
What's the current state here? Could we remove the silence? I see that the PR mentioned by @calvix has been merged.
