### ISSUE TITLE
`kubectl-gs gitops add base` command: assessment and creation

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1828]
Working on https://github.com/giantswarm/roadmap/issues/1624, it was noticed that:

> We lack of a `kubectl gs gitops add base`command. This would be aligned with the rest of the UX and would make really easy to work with a provider. Combined with a good doc, this would make the process of creating a WC really easy. We should assess the creation of this command, but given we are already given the templates for the CAPI clusters in the kubectl gs template command, I would say is pretty realistic to say is not a very hard task. This is mostly blocking the creation of an acceptable How to create WC base doc.

Suggested Action: 
> @giantswarm/team-honeybadger  to assess the creation of the `kubectl gs gitops add base` command in order to be able to create proper UX and docs for base creation, at least for vanilla CAPI providers.

- [ ] Once rolled out this page needs to be updated too: https://docs.giantswarm.io/use-the-api/kubectl-gs/gitops/

**Comment by uvegla** [comment]
FTR: In gitops we only support CAPX and `kubectl gs template cluster` supports the standard cluster + default-apps App CR + config maps approach for CAP[A,G,O]. For CAP[Z,V] `template cluster` supports an old format.

However for CAPZ we have: https://github.com/giantswarm/cluster-azure + https://github.com/giantswarm/default-apps-azure and for CAPV we have: https://github.com/giantswarm/cluster-vsphere + https://github.com/giantswarm/default-apps-vsphere.

**Comment by uvegla** [comment]
Related to: https://github.com/giantswarm/roadmap/issues/1529

**Comment by uvegla** [comment]
Merged: https://github.com/giantswarm/kubectl-gs/pull/992, released as: https://github.com/giantswarm/kubectl-gs/releases/tag/v2.30.0
