### ISSUE TITLE
capa-iam-operator leaves IAM resources behind on cluster deletion

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#1829]
This is on `golem` with capa-iam-operator 0.4.4. For clusters that I had deleted many days ago, resources have been left behind. Note that IAM resources such as roles and policies are limited (e.g. 1000 policies), so this can become very problematic if clusters are often created and deleted.

![Leftover IAM resources](https://user-images.githubusercontent.com/1376043/210572326-bcbc50c8-5183-4aae-91a1-d4b33e8c69fb.png)

The logs hint at issues with finalizer creation:

```
capa-iam-operator 2023-01-04T14:46:24.412078293+01:00 E0104 13:46:24.411946       1 awsmachinepool_controller.go:169] controllers/AWSMachinePool "msg"="failed to add finalizer on AWSCluster" "error"="Operation cannot be fulfilled on awsclusters.infrastructure.cluster.x-k8s.io \"andreas10\": the object has been modified; please apply your changes to the latest version and try again" "awsMachinePool"="andreas10-machine-pool0" "cluster"="andreas10" "namespace"="org-giantswarm"
```

Same for deletion:

```
capa-iam-operator 2023-01-04T15:14:29.810897704+01:00 E0104 14:14:29.810761       1 awsmachinepool_controller.go:133] controllers/AWSMachinePool "msg"="failed to remove finalizer on AWSCluster" "error"="Operation cannot be fulfilled on awsclusters.infrastructure.cluster.x-k8s.io \"andreas10\": the object has been modified; please apply your changes to the latest version and try again" "awsMachinePool"="andreas10-machine-pool0" "cluster"="andreas10" "namespace"="org-giantswarm"
```

It's also hard to find out to which management cluster the deleted workload clusters belongs. I suggest we add informational tags on IAM resources, so it will be easier to clean up such situations manually.

**Comment by AndiDog** [comment]
You're right – it's probably too complex for little benefit. At least we have the cluster name always referenced, so that may be enough.

**Comment by calvix** [comment]
if the deletion work as expected in all cases we should be fine anyway
