### ISSUE TITLE
CAPA (private environment) - prometheus-agent

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1831]
Towards: https://github.com/giantswarm/roadmap/issues/1467

Make sure prometheus-agent communicate to MC prometheus using the given proxy settings when running on private environment.

### How to validate

- [ ] proxy url is used in the `remote_write` prometheus config
- [ ] remote write communication works in a private environment

**Comment by marieroque** [comment]
`prometheus-agent` errors:

* on MC `goat`, certificate issue:
```
ts=2023-01-04T14:34:31.193Z caller=dedupe.go:112 component=remote level=warn remote_name=50cf2c url=https://prometheus.goat.gaws.gigantic.internal/goat/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://prometheus.goat.gaws.gigantic.internal/goat/api/v1/write\": x509: certificate signed by unknown authority"
```

* on WC `goatproxy`, host issue:
```
ts=2023-01-04T14:30:15.746Z caller=dedupe.go:112 component=remote level=warn remote_name=6eb562 url=https://prometheus.goat.gaws.gigantic.internal/goatproxy/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://prometheus.goat.gaws.gigantic.internal/goatproxy/api/v1/write\": dial tcp: lookup prometheus.goat.gaws.gigantic.internal on 172.31.0.10:53: no such host"
```

**Comment by marieroque** [comment]
We have to set proxy env to `prometheus-agent` deployed on `kube-system` namespace because of `kyverno` limitations:
https://github.com/giantswarm/rfc/pull/50/files?short_path=78fcec4#diff-78fcec4175afc37005ef8958f78043f2e99817bd7d261506775c2d80d480427e

PR on `pmo`:
https://github.com/giantswarm/prometheus-meta-operator/pull/1106

**Comment by marieroque** [comment]
With `proxy_url` set in `remote_write` config secret, the error in the agent is different (`x509: certificate signed by unknown authority` => `Internal server error`):
```
ts=2023-01-05T15:56:38.089Z caller=dedupe.go:112 component=remote level=warn remote_name=698074 url=https://prometheus.goat.gaws.gigantic.internal/goat/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://prometheus.goat.gaws.gigantic.internal/goat/api/v1/write\": Internal Server Error"
```

**Comment by marieroque** [comment]
It seems the proxy `squid-proxy` can't access the prometheus ingress:
```
1673613996.504      0 10.255.114.82 NONE_NONE/500 0 CONNECT prometheus.goat.gaws.gigantic.internal:443 - HIER_NONE/- -
```

**Comment by marieroque** [comment]
We did wrong when we added proxy settings in the agent:
https://gigantic.slack.com/archives/C04AJ5FJHEK/p1673614269044229

Proxy has to be used only for requests to public internet.

**Comment by marieroque** [comment]
Branch tested on `goat`:
https://github.com/giantswarm/prometheus-meta-operator/pull/1118

=> no more `Internal server error`

But error with certificate:
```
ts=2023-01-13T14:40:44.027Z caller=dedupe.go:112 component=remote level=warn remote_name=50cf2c url=https://prometheus.goat.gaws.gigantic.internal/goat/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://prometheus.goat.gaws.gigantic.internal/goat/api/v1/write\": x509: certificate signed by unknown authority"
```

=> @calvix and @quentin suggest to deactivate `tls cert verification`:
https://github.com/giantswarm/config/pull/1497

**Comment by marieroque** [comment]
The `prometheus-server` requested by the agent increases cpu/memory too much:
```
goat-prometheus             prometheus-goat-0                                   154m (3%)     225m (5%)   12036245Ki (75%)  14779652086 (90%)  42m
```

That causes `prometheus` restarts.
I even noticed a crash node :-(
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                    Requests           Limits
  --------                    --------           ------
  cpu                         1778m (44%)        2746m (68%)
  memory                      16316985986 (99%)  18980037826 (115%)
```

**Comment by marieroque** [comment]
We had to restart `vpa-recommender` because it didn't work well and prometheus resources were not reallocated correctly.

After `vpa` restart and many prometheus restarts, the monitoring on MC was working:


![Image](https://user-images.githubusercontent.com/9134338/213394719-90d79a14-5b06-4db6-8a6a-cc9934a7cae7.png)

**Comment by marieroque** [comment]
Now that `goat` is fixed, we need to fix:
[] `thunder`
[] `thor`

**Comment by marieroque** [comment]
PR to add `prometheus-remotewrite` to `thor` in `config` repo:
https://github.com/giantswarm/config/pull/1531

**Comment by marieroque** [comment]
`thor` is working well with MC + 2 WC !!!

```
[promtail-app]$ k get po -A | grep prome
kube-system         prometheus-operator-app-operator-55d4cd5c8c-g6xqf                      1/1     Running     0                73m
kube-system         prometheus-prometheus-agent-0                                          2/2     Running     0                4h19m
marie1-prometheus   prometheus-marie1-0                                                    2/2     Running     9 (73m ago)      3h39m
marie2-prometheus   prometheus-marie2-0                                                    2/2     Running     0                14m
monitoring          prometheus-meta-operator-888686d6d-gdx6v                               1/1     Running     0                7h
thor-prometheus     prometheus-thor-0                                                      2/2     Running     0                4h41m
```

**Comment by marieroque** [comment]
Upgrade of `thunder` plan for Tuesday 31/01:
https://gigantic.slack.com/archives/C5PDDBBDG/p1674744054778089
