### ISSUE TITLE
Find out how to access object storage on AWS installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1839]
Towards: https://github.com/giantswarm/roadmap/issues/311

As Loki requires an object storage solution to work at scale, in order to be able to deploy it to our AWS installations, we first need to investigate how we can setup an object storage solutions per installation to be available for Loki.

There are currently 2 possible way of doing so, either via kiam or [IRSA](https://docs.giantswarm.io/advanced/iam-roles-for-service-accounts/). We need to find out which solution will be used to access object storage from Loki

### How to validate
- [x] I can easily setup Loki's object storage dependency on an AWS installation

**Comment by TheoBrigitte** [comment]
Many solutions are available :

- manual script
- giantnetes/terraform
- mc-bootstrap
- crossplane

Crossplane is not ready yet, so keeping this for future.

Object storage should be accessible via [IRSA](https://docs.giantswarm.io/advanced/iam-roles-for-service-accounts/) or KIAM

**Comment by hervenicol** [comment]
Looks like on MCs it's not that easy.
I talked to @paurosello who has to think about a solution for us. (https://gigantic.slack.com/archives/CLPMFRVU6/p1673376333364499?thread_ts=1673285081.122279&cid=CLPMFRVU6)

So I'm blocked until we have an answer from @giantswarm/team-phoenix .

**Comment by T-Kukawka** [comment]
We will extend the instance profile for the S3 bucket permissions to the MC.

@hervenicol can you prepare the list of permissions required to be added?

**Comment by hervenicol** [comment]
@T-Kukawka the list of permissions is documented in the Loki role creation here:
https://github.com/giantswarm/loki-app#prepare-aws-role

Please tell me if you need any more information.

**Comment by T-Kukawka** [comment]
@paurosello is that enough? ⏫

**Comment by paurosello** [comment]
Hello!

Created the bucket [gauss-loki-logs](https://s3.console.aws.amazon.com/s3/buckets/gauss-loki-logs?region=eu-west-1)

And also modified the roles:
- https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/roles/details/gauss-master?section=permissions
- https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/roles/details/gauss-worker?section=permissions

To have the permissions:

      ```
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject" ],
            "Resource": [
                "arn:aws:s3:::gauss-loki-logs",
                "arn:aws:s3:::gauss-loki-logs/*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:GetAccessPoint",
                "s3:GetAccountPublicAccessBlock",
                "s3:ListAccessPoints"
            ],
            "Resource": "*"
        }
```


Can you try deploying in gauss MC? No need to add any IRSA/KIAM annotations.

**Comment by hervenicol** [comment]
We have some loki pods running on `gauss` MC, in the `loki` namespace.
They're not happy yet.

`k --context=gs-gauss logs -n loki loki-write-0` shows:
```
level=info ts=2023-01-17T12:52:22.816075147Z caller=table_manager.go:134 msg="uploading tables"                                                                                                                                               
level=error ts=2023-01-17T12:52:55.404844795Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="AccessDenied: Access Denied\n\tstatus code: 403, request id: 7K6XG50SKFVN337R, host id: pUzxD9QObo9m
W72x3gx5OU4EBGvjTWHBrkpMQnUVC3gUuvOU8a6wGrxQJcspo06LpbW5Sv7xTj8="
```

Here is the relevant config info in loki:
* on gorilla/zj88t (setup using KIAM, working):
```
$ k --context=gs-gorilla-zj88t-clientcert exec -n loki -ti loki-write-0 -- cat /etc/loki/config/config.yaml | yq '.common.storage.s3'
bucketnames: gs-loki-storage-zj88t
insecure: false
region: eu-central-1
s3forcepathstyle: false
```

* on gauss MC:
```
$ k --context=gs-gauss exec -n loki -ti loki-write-0 -- cat /etc/loki/config/config.yaml | yq '.common.storage.s3'
bucketnames: gauss-loki-logs
insecure: false
region: eu-west-1
s3forcepathstyle: false
```

**Comment by hervenicol** [comment]
New bucket `gauss-g8s-loki-logs` works better!
![image](https://user-images.githubusercontent.com/12008875/213174878-75ebd989-578c-492b-999e-2cfb3b612396.png)

**Comment by paurosello** [comment]
The issue is the S3 endpoint was blocking the access.. In order to get around that the bucket name has to contain g8s

**Comment by paurosello** [comment]
As a last question, do we need to create bucket in advance in MC terraform how did you create the one in gorilla?

**Comment by hervenicol** [comment]
Did some more extensive tests on `gauss`, and I can confirm the proposed S3 access config works for us :+1: 
@paurosello , what's the next step then? How can we have this on all AWS installations? :grin:

**Comment by TheoBrigitte** [comment]
We met today and conclude on the following :

- vintage: Loki can access S3 object storage from AWS via the inherited instance profile from the node/ec2 instance to the pod. No changes needed for Loki.

@hervenicol can you please make sure we document this somewhere in our [intranet for Loki setup](https://intranet.giantswarm.io/docs/observability/loki-tech/) ?
@paurosello is there a piece of documentation about the EC2 instance profile inheritance we can link to ?

**Comment by whites11** [comment]
this is released with giantnetes-terraform 14.11.0 and being rolled out as we speak (see https://github.com/giantswarm/giantswarm/issues/25354)

**Comment by whites11** [comment]
deployed everywhere except china installations, where is impossible to deploy yet because of problems with the container registry

**Comment by TheoBrigitte** [comment]
Closing this issue as we actually found how to access object storage from Loki on AWS installation, and this is documented here https://intranet.giantswarm.io/docs/observability/loki-tech/#object-storage-setup

Regarding the object storage creation and deployment please post updates in https://github.com/giantswarm/roadmap/issues/1849
