### ISSUE TITLE
Allow customers to create clusters with deprecated release if they have a cluster with that version running

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#184]
**Is your feature request related to a problem? Please describe.**

Currently, customers can not create clusters by themselves with a release that has been deprecated. It blocks them from using automation for testing upgrade paths for the releases they use.

**Describe the solution you'd like**

Customers should be able to create new clusters with a deprecated release version but only if they have at least one cluster with that version running.

**Additional context**

cc @othylmann

**Comment by cokiengchiara** [comment]
Duplicate of https://github.com/giantswarm/giantswarm/issues/12489?

**Comment by MartaD** [comment]
yes, closing then.
