### ISSUE TITLE
Update readme for cluster API in the `giantswarm-aws-account-prerequisites` repo

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1842]
## Task

Update readme for cluster API in the `giantswarm-aws-account-prerequisites` repo.

**Comment by alex-dabija** [comment]
@calvix could you provide more details about what needs to be updated? Thanks!

**Comment by calvix** [comment]
https://github.com/giantswarm/giantswarm-aws-account-prerequisites#cluster-api

done
