### ISSUE TITLE
Create object storage for AWS installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1849]
Towards: https://github.com/giantswarm/roadmap/issues/311

Find a way to create the object storage which will be used by Loki on AWS installations.

Potential solutions :

- manual script
- giantnetes/terraform
- mc-bootstrap
- ~crossplane~ is not ready yet, so keeping this for future.

**Comment by hervenicol** [comment]
That's managed by @giantswarm/team-phoenix, and @paurosello will link a PR so we can track what has be done.
This will only be for "legacy" AWS installations though. CAPA will be done separately.

**Comment by paurosello** [comment]
PR in https://github.com/giantswarm/giantnetes-terraform/pull/688

**Comment by TheoBrigitte** [comment]
We met today and concluded on the following :

- object storage for AWS is created via [giantnetes-terraform#688](https://github.com/giantswarm/giantnetes-terraform/pull/688) repositories
- deployment is handled by team-phoenix (once a month or on demand)

@hervenicol can you please make sure we document this somewhere in our [intranet for Loki setup](https://intranet.giantswarm.io/docs/observability/loki-tech/) ?

**Comment by QuentinBisson** [comment]
@hervenicol I think this should be WIP as you're mostly waiting for Theo's feedback

**Comment by TheoBrigitte** [comment]
object storage is being deployed by team Phoenix

> this is released with giantnetes-terraform 14.11.0 and being rolled out as we speak (see [giantswarm/giantswarm#25354](https://github.com/giantswarm/giantswarm/issues/25354))


> deployed everywhere except china installations, where is impossible to deploy yet because of problems with the container registry

**Comment by TheoBrigitte** [comment]
Assuming this was deployed
