### ISSUE TITLE
Create Proactive alert for WC master high memory

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1855]
As a customer i do want to be notified when master nodes on the WC are running under high memory consumption for a longer period of time. The usage of master nodes are increasing especially with security pack where if any additional scans are running, the master nodes can be impacted and go OOM.

We would like to create the alerts for the high memory consumption to alert and talk with customers about resizing the nodes. This alert would page AEs to start the communication between Customers and Cloud team for the resizing/investigation.

The go-to instance type would be then the r6.x where the CPUs are the same but they are memory oriented.

**Comment by whites11** [comment]
why don't we instead make use of the already existing too many requests alert?
It serves exactly the same purpose but using a meaningful metric (API being overloaded) rather than this system load based one.
We also already have a list of affected clusters https://github.com/giantswarm/giantswarm/issues/23874

**Comment by T-Kukawka** [comment]
Initially let's try with the 'notify' page to alert us in the slack-channel for validation of the usefulness of the alert

**Comment by whites11** [comment]
PR https://github.com/giantswarm/prometheus-rules/pull/636

Still missing the ops recipe

**Comment by pipo02mix** [comment]
[Ops recipe merged](https://github.com/giantswarm/handbook/pull/50), there is room for improvement in future

**Comment by whites11** [comment]
alert is no active
