### ISSUE TITLE
Update opsctl login to support multiple dex connectors

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#1857]
To support multiple dex connectors with opsctl login, the behaviour of opsctl login should be :

- [ ] opsctl login default behaviour should be according to the existing context
- [ ] opsctl login management cluster default behaviour without kubeconfig can be done with a connector flag or manual via the dex selection page
- [ ] opsctl login should have a flag to add the connector

**Comment by weatherhog** [comment]
for refinement: 
with existing context the --connector Id flag would be ignored?

**Comment by anvddriesch** [comment]
> for refinement:
with existing context the --connector Id flag would be ignored?

Yes, that's the case
