### ISSUE TITLE
Default to `m5.2xlarge` for CAPA MCs

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1863]
## Task

Default to `m5.2xlarge` for CAPA MCs.

## Background

AWS Vintage defaults to `m5.2xlarge`.

## Questions

- Should the default be set to `m6.2xlarge` instead?

**Comment by fiunchinho** [comment]
@T-Kukawka

**Comment by fiunchinho** [comment]
I guess it's still worth it since they are more efficient?

**Comment by T-Kukawka** [comment]
depends also on our reservations right? do we have any already? if not we would have to add some

**Comment by fiunchinho** [comment]
I don't think we have any reserved instances on our accounts. So let's decide which instance type to use, then we can reserve it.

**Comment by T-Kukawka** [comment]
We will upgrade one of the MCs to the `r6.xlarge

**Comment by fiunchinho** [comment]
`grizzly` has been redeployed using `r6i.xlarge`

**Comment by T-Kukawka** [comment]
we have follow up issues for rest of MCs, we have to do it gradually
