### ISSUE TITLE
Improve dex connector name display on selection page

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1864]
![image](https://user-images.githubusercontent.com/273727/212669599-d9ad9691-14d8-482e-8c4f-4e4b2fd737ff.png)

Currently:

    Log in with microsoft connector for giantswarm

Suggestion

    Azure AD for Giant Swarm

We have to investigate how this can be configured, and whether template changes are needed. Also take into account customer vs. Giant Swarm staff connectors. And take into account the unfiltered page, as it appears in Grafana by default.

**Comment by marians** [comment]
Here is how the button labels are filled:

## Dex template

The last level is the Dex page template [login.html](https://github.com/giantswarm/dex-app/blob/v1.32.2/web/templates/login.html#L12). Here the format is like this currently:

    Log in with CONNECTOR_NAME

## Dex config

`CONNECTOR_NAME` is defined in the dex config secret. Here are entries from our two connectors configured for Giant Swarm:

```
- type: github
  id: giantswarm
  name: GitHub for Giant Swarm staff
- type: microsoft
  id: giantswarm-ad
  name: microsoft connector for giantswarm
```

## dex-app

The connector name for the `giantswarm` GitHub connector is part of the dex-app [secret template](https://github.com/giantswarm/dex-app/blob/v1.32.2/helm/dex-app/templates/dex/secret.yaml#L96).

## dex-operator code

The `giantswarm-ad` connector config is created by dex-operator.

It appears as if the name is composed from the lowercase owner key and name ([example](https://github.com/giantswarm/config/blob/main/installations/gremlin/apps/dex-operator/secret-values.yaml.patch#L2)).

**Comment by anvddriesch** [comment]
@marians yeah, that sounds about right.
This function is used in `dex-operator` to get the name from the owner and connector type keys: https://github.com/giantswarm/dex-operator/blob/cfc8bc222c5b4e27dc704d99bd76e10d110939ce/pkg/key/key.go#L42-L44

As far as the connector type goes, it would be very easy to add a more user friendly name to each provider definition that could be used here. (e.g microsoft->azure active directory)
The owner would be a bit more work, however since it's not defined directly in the code but comes from outside. So we would have to add the user friendly owner/customer name to the dex operator config file.

**Comment by marians** [comment]
Thanks for the info. Just a note: the microsoft connector does not automatically mean that Azure AD is in use, according to what I understand.

For best UX, I would definitely like the option to completely customize the label on the button for each connector, which would basically mean that we could simply have strings like "ACME Identity Single Sign-On" on the button, if we want to. We could keep the generic method as a fall-back/default.

**Comment by anvddriesch** [comment]
> Thanks for the info. Just a note: the microsoft connector does not automatically mean that Azure AD is in use, according to what I understand.

Yeah. I think that's even more so with 'oidc' type which can be a lot of different things.
However, that wouldn't really be a problem here since we define it within the code of the specific provider implementation (in this case azure ad)

**Comment by weatherhog** [comment]
- connector name should be fully customisable (option)
- allow to overwrite name
- add default format
