### ISSUE TITLE
Update `aws-network-topology-operator` to allow targeting specific subnets

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#1865]
Currently TGW attachments will attach into the first subnet found for each availability zone.

The operator should be updated to support first checking for subnets tagged with `subnet.giantswarm.io/tgw-attachments: "true"` and if not found then fall back to the first found as it currently does.

This same logic was recently added to the `aws-vpc-operator` in this PR - https://github.com/giantswarm/aws-vpc-operator/pull/22

**Comment by bdehri** [comment]
https://github.com/giantswarm/aws-network-topology-operator/pull/82
