### ISSUE TITLE
Prevent `aws-vpc-operator` from overwriting the `Name` tag

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#1866]
Update to check if the `Name` tag is user-provided and only if not should it be added by the operator.

See: https://github.com/giantswarm/aws-vpc-operator/blob/2d2dd267410a7837bf6c2b9d86aaa5d096bebf53/pkg/aws/subnets/reconciler.go#L70

**Comment by AverageMarcus** [comment]
Note: CAPA has this same behaviour (overwriting the Name) and I'm going to discuss with upstream if it's required or not.

**Comment by AverageMarcus** [comment]
Upstream issue: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3989

**Comment by AverageMarcus** [comment]
Note: we attempted the to get around this by manually setting the `kubernetes.io/role/internal-elb` and `kubernetes.io/role/elb` tags on each subnet to control which subnets are fetched during the autodiscovery. While this worked and the tags weren't overwritten it seems that the in-tree (and out-of-tree) AWS controller ignores the value of the tag so cannot be used to control which are matched and which are ignored.

The [aws-load-balancer-controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) which handles ALBs and NLBs does use the value of the tag but doesn't help us with the ingress LoadBalancer.

**Comment by AndiDog** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3991 is merged. We only need to merge into our CAPA fork. Together with https://github.com/giantswarm/roadmap/issues/1832, we can release the fix.

**Comment by AndiDog** [comment]
CAPA change was released via https://github.com/giantswarm/cluster-api-provider-aws-app/pull/154, so we're done with both aws-vpc-operator and CAPA
