### ISSUE TITLE
app CR validation and defaulting

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#187]
**Is your feature request related to a problem? Please describe.**

With the Control Plane API, customers create app CRs directly either with kubectl or automation. They need to set a lot of fields. This is hard to get right, is frustrating for customers, and is time consuming to debug. 

**Describe the solution you'd like**

Add admission-controller to app-operator with validating and defaulting logic for app CRs.

- [x] Validation. Validate to check what needs to be checked (e.g. app-operator.giantswarm.io/version label is set, catalog has matching appcatalog CR, etc.)
- [ ] Defaulting. Default what can be defaulted (e.g. what can be derived based on the namespace where app CR is created)

---

Currently @giantswarm/team-batman is finishing Upgrade to Helm 3 for tenant clusters https://github.com/giantswarm/roadmap/issues/30.

In the meantime, we can provide docs to guide the creation of app CRs. This could help customer and on call people to debug when something's wrong with an app CR.

**Comment by cokiengchiara** [comment]
Wed, 9. Sep 2020

In the meantime, we added validation to app CRs to make debugging easier. Customers can check CR status next time there is a problem. (see [app-operator changelog](https://github.com/giantswarm/app-operator/blob/master/CHANGELOG.md#added))

**Comment by rossf7** [comment]
> Add admission-controller to app-operator with validating and defaulting logic for app CRs.

@cokiengchiara The admission controller should be outside app-operator because we run multiple operators. We'll name it app-admission-controller to align with aws-admission-controller and azure-admission-controller.

I'm planning to work on this again in https://github.com/giantswarm/giantswarm/issues/11656
 in our next hackathon in October.

**Comment by rossf7** [comment]
@cokiengchiara This is nearly done. See https://github.com/giantswarm/releases/pull/569 that requests the new versions for AWS and the docs PR https://github.com/giantswarm/docs/pull/731

I've moved to WIP in the product board. Can you check if there is anything else we need to update here?

**Comment by cokiengchiara** [comment]
thanks @rossf7 <3 I added https://github.com/giantswarm/docs/pull/731 to In Progress. Closing this.
