### ISSUE TITLE
Update docker-kubectl image in cluster-api-provider-aws-app

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#1878]
Coming from https://github.com/giantswarm/roadmap/issues/1808

Update docker-kubectl image in cluster-api-provider-aws-app to the latest v1.24.x (same as vintage AWS MCs, one minor newer than CAPA MCs)

**Comment by bdehri** [comment]
Should we update to the latest or latest of 1.24? @nprokopic @alex-dabija

**Comment by bdehri** [comment]
https://github.com/giantswarm/cluster-api-provider-aws-app/pull/150

**Comment by nprokopic** [comment]
From here https://github.com/giantswarm/roadmap/issues/1808

> Update docker-kubectl image in cluster-api-provider-aws-app to the latest v1.24.x (same as vintage AWS MCs, one minor newer than CAPA MCs)

That would be v1.24.9 I believe

**Comment by nprokopic** [comment]
Checked now [upstream release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md), the latest v1.24.x is v1.24.10.

**Comment by nprokopic** [comment]
The logic to select which version to deploy is that the difference between kubectl and Kubernetes versions (on MC where kubectl is used to apply CRDs) should not be greater than 1.

On vintage AWS we are using v1.24.x and on CAPA we are still on v1.23.x (checked golem and grizzly), so the latest kubectl version that respects max version skew on both is v1.24.x.

**Comment by bdehri** [comment]
@nprokopic Thank you very much for the clarification. But I am a bit confused about docker-kubectl. But, I am little bit confused, I tought that [docker-kubectl](https://github.com/giantswarm/docker-kubectl) is a repo on our end. That's why I used 1.24.4.

**Comment by nprokopic** [comment]
> But I am a bit confused about [docker-kubectl](https://github.com/giantswarm/docker-kubectl). But, I am little bit confused, I tought that docker-kubectl is a repo on our end. That's why I used 1.24.4.

I had same confusion few days ago for cluster-api-app :smile: 

@fiunchinho updated cluster-api-app to use `giantswarm/kubectl` (built by regtagger, we always retag every upstream version) instead of `giantswarm/docker-kubectl` (coming from our repo, not always up-to-date) https://github.com/giantswarm/cluster-api-app/pull/82/files, I guess we can do the same here for cluster-api-provider-aws-app.

(left this same comment in the PR)

**Comment by bdehri** [comment]
https://github.com/giantswarm/cluster-api-provider-aws-app/pull/150
