### ISSUE TITLE
Make session duration configurable in Kiam managed app

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#188]
**Is your feature request related to a problem? Please describe.**

Currently, Kiam has configured as session duration of 15 minutes (default value). The problem is some apps that AWS Java SDK refresh credentials that are expiring within 15 minutes. As result any API call using the AWS Java SDK will attempt to retrieve credentials, putting tons of load on kiam agent, kiam server, and your pods.

As it is recommended upstream having higher value, like 60 minutes, would solve the problem, especially when there is an upgrade in action. 

**Describe the solution you'd like**

Configured the kiam server and agent to have a session duration of 60/120 minutes by default and make this value configurable for our customers or by cluster.

**Describe alternatives you've considered**

Get rid of kiam and use [IAM roles for Service Accounts](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/).

**Comment by puja108** [comment]
A customer who was using their own kiam before we introduced ours needs this so they can migrate to our newer cluster versions.

**Comment by njuettner** [comment]
Dupl, this was addressed here https://github.com/giantswarm/giantswarm/issues/13174

**Comment by alex-dabija** [comment]
I'm closing the issues as we already support this feature.
