### ISSUE TITLE
Update docker-kubectl image in cluster-api-provider-openstack-app

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#1880]
Coming from https://github.com/giantswarm/roadmap/issues/1808

Update docker-kubectl image in cluster-api-provider-openstack-app to the latest v1.23.x (one minor newer than CAPO MCs)

**Comment by gawertm** [comment]
@nprokopic as stated here, we are not working on OpenStack anymore and wont update these repos anymore.
https://gigantic.slack.com/archives/C02521EC0/p1673452826130819
