### ISSUE TITLE
Resolver rules full of zombie VPCs association

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1883]
Should there be periodic clean up for these zombie VPCs:

![Image](https://user-images.githubusercontent.com/5674762/213187384-e9773af6-4f51-488a-9699-fe83d8bc4de3.png)

![Image](https://user-images.githubusercontent.com/5674762/213187104-50a5b9a6-6ce6-4f1b-808a-7c170a7a0d62.png)

And we have so many zombie VPC’s listed in resolver rules page which are consuming rules association quota.

![Image](https://user-images.githubusercontent.com/5674762/213201440-8fb89b01-a356-46b2-bd72-f447862f2beb.png)

**Comment by alex-dabija** [comment]
We agreed to just replicate the behavior in one of our AWS accounts to better understand how resolver rules work. Depending on the findings we'll decide if a fix is needed or not.

**Comment by tuladhar** [comment]
Encounter in thor by Jose:
```
[   41.995165] cloud-init[1128]: [2023-01-19 12:00:52] 	[ERROR ImagePull]: failed to pull image docker.io/giantswarm/coredns:v1.8.6: output: time="2023-01-19T12:00:52Z" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"docker.io/giantswarm/coredns:v1.8.6\": failed to resolve reference \"docker.io/giantswarm/coredns:v1.8.6\": failed to do request: Head \"https://registry-1.docker.io/v2/giantswarm/coredns/manifests/v1.8.6\": proxyconnect tcp: dial tcp: lookup server-proxy.eu-central-1.aws.hdi.de: no such host"
[   41.995300] cloud-init[1128]: [2023-01-19 12:00:52] , error: exit status 1
```

**Comment by tuladhar** [comment]
I've also requested Talanx if those zombie VPCs belongs to them, so we can clean them up to free up limit quota:

**Comment by fiunchinho** [comment]
We are not removing the associations after removing workoad clusters.

**Comment by tuladhar** [comment]
Sheet: https://docs.google.com/spreadsheets/d/1NoJICH2sm-Jqxx89t3m15fAlcy8hoQ58cUlRm0oi0w4/edit#gid=0

**Comment by tuladhar** [comment]
For future reference, here's the script:
* https://github.com/tuladhar/route53-resolver-disassociations
