### ISSUE TITLE
Bump Kubernetes version to `v1.23.16`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1886]
## Task

Bump Kubernetes version to `v1.23.16` for CAPG clusters.

**Comment by bdehri** [comment]
`gunther` is deleted and will be recreated.

**Comment by bdehri** [comment]
* https://github.com/giantswarm/management-clusters-fleet/pull/362
* https://github.com/giantswarm/config/pull/1583

There is no change in installation repo, so PR is not needed.
