### ISSUE TITLE
Handle `$ref` correctly in schemalint verify command

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#1887]
Related: https://github.com/giantswarm/schemalint/pull/19#issuecomment-1385375214

Currently, schemalint ignores the `$ref` property. However, when checking requirements on properties, it should resolve the reference and check the resolved schema.

**Example**:
```
{
    "$defs": {
        "foo": {
            "description": "short",
            "type": "integer"
        }
    },
    "properties": {
        "refProperty": {
            "$ref": "#/$defs/foo"
        }
    },
    "type": "object"
}
```

`schemalint verify` currently won't check whether the description (and everything else) defined in `"foo"` meets the validation rules.

The solution should work for JSON Pointers, named anchors and external URI-referenced schemas.

**Comment by marians** [comment]
In `schemalignment` I have done something trivial to dereference refs: https://github.com/giantswarm/schemalignment/commit/0c556303032056660125382f6a784c772e1319da#diff-a051a78cc9fd68c471b895fa88a9be9bee89cb4796f22fd8c56582ab67dba6e8R43-R45

I don't know whether this also works with ref URLs though.

**Comment by mogottsch** [comment]
That's what I also plan to do.
The "complicated" thing is that we cannot get the parent (the schema which had the reference) and the parent is not represented in the path. 

This leads to confusing outputs.
**Example**:
```
{
    "properties": {
        "image": {
            "$ref": "external_ref.json"
        }
    },
    "type": "object"
}
```
Current output:
`- Property '/name' description should not repeat the title.`
It would be expected to have: 
`- Property 'image/name' description should not repeat the title.`

But I'm working on a solution.

**Comment by mogottsch** [comment]
When using `$ref` it may happen that a single property path has multiple annotation values, e.g. multiple values for `title`, `description`, etc...
In this case, the value, that is directly defined (not through `$ref`) should take precedence.
This behaviour is also reflected in the `react-jsonschema-form` library we use for rendering in happa.
