### ISSUE TITLE
Clarify reason for using multiple types for property in cluster app schema

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1892]
In the [vsphere cluster-app schema](https://github.com/giantswarm/cluster-vsphere/blob/v0.1.2/helm/cluster-vsphere/values.schema.json) there are two properties with multiple types defined.

In the context of #1733 we (team rainbow) would like to understand the reasons for allowing `null` in addition to the actual property type (object, string).

The properties are:

- `/kubeadm` (see https://github.com/giantswarm/cluster-vsphere/blob/v0.1.2/helm/cluster-vsphere/values.schema.json#L39)
- `/template/properties/storagePolicyName` (see https://github.com/giantswarm/cluster-vsphere/blob/v0.1.2/helm/cluster-vsphere/values.schema.json#L96)

Supporting multiple types complicates our UI for cluster creation/configuration, so we would prefer to restrict cluster app schemas to only use single types per property.

@giantswarm/team-rocket Your input would be appreciated.

**Comment by gawertm** [comment]
@marians thanks for reporting. we havent been working in this for some months. only now we will start updating the charts again and have a look into this as well

**Comment by jkremser** [comment]
I don't think there is a good reason for this in this chart. I had a use-case in past for having either null or something else as an allowed value, but empty string (`""`) or empty object (`{}`) should work here the same way as `null`.

The reason I had (on some other community chart) was when I wanted to remove the `key: value` entry completely from the resulting k8s yaml when it was rendered. Also omitting it completely in values.yaml (it's the same as having the values set to null) would work so the defaults can be shorter. In general the semantics might be different between `foo: zeroValue` and `foo: null` and I am not sure if you should make such a hard assumptions in the UI that each field can have only 1 type. I mean it doesn't make much sense to have something like int or string, but $anything or null seems ok to me.

**Comment by marians** [comment]
Just FYI: not setting a value is not the same as setting it to `null`. Setting a string property to null is invalid. Not setting it (if it's not required) is valid.

For cluster-apps, we are now restricting our requirements to have exactly one type defined.

As it seems that this is not clarified, I'm closing the issue. Thanks!

**Comment by jkremser** [comment]
I agree with you that from the schema POV life would be easier, but there are use-cases for this:
https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key

If it was possible to pass all the "zero values" ("", [], {}) using `--set foo=X` we should be good, but iirc there were some issues with "nulling" the arrays, because the `{}` literal is actually used for passing the arrays not for empty objects.

**Comment by marians** [comment]
I have read the documentation in https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key and my impression is that `--set someProperty=null` means that `someProperty` will be removed from the default values. But it does not mean that the schema for `someProperty` must include the type `null`. At least I don't see this sort of info regarding schema.

> If it was possible to pass all the "zero values" ("", [], {}) using --set foo=X we should be good, but iirc there were some issues with "nulling" the arrays, because the {} literal is actually used for passing the arrays not for empty objects.

This part I don't understand.

**Comment by jkremser** [comment]
You are right. `--set someProperty=null` somehow magically works, even though the schema doesn't allow for `null`s.
