### ISSUE TITLE
Enable CronJobTimeZone feature - 1.24 k8s

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1895]
CronJobTimeZone alpha feature gate can be enabled with a flag on k8s 1.24.

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones

This feature will make customers' lives easier to coordinate in the context of multiple installations that are spawned in different regions and timezones.

**Comment by whites11** [comment]
released in k8scc 15.6.0

**Comment by alex-dabija** [comment]
I created a separate [issue](https://github.com/giantswarm/roadmap/issues/2214) for CAPA.
