### ISSUE TITLE
Move back to machine deployments

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1897]
### Motivation
In https://github.com/giantswarm/roadmap/issues/1869 we compared machine pools - which we want as a long term solution but have some issues with yet - with machine deployments - which are at this time the more stable solution that we can directly implement - and decided to go for machine deployments for now and machine pools in the future. That is why we have to revert any changes we have done earlier to test out machine pools and stabilise our initial product with the usage of machine deployments. 

### Todo
- Revert the changes for machine pools from https://github.com/giantswarm/giantswarm/issues/24562 back. 
- Make sure we're no longer using machine pools but machine deployments
- Make sure everything still works as accepted

### Outcome
- We are relying again on the more mature MachineDeployments instead of the machine pools for our machine types

**Comment by primeroz** [comment]
Need to update schema

**Comment by primeroz** [comment]
this is done and released as 0.0.4 of cluster-azure
