### ISSUE TITLE
How to ship k8s audit log to Loki

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1898]
As an engineer I need a solution to ship [kubernetes audit logs](kubernetes-audit) into my Loki instance.

Document findings under our public documentation within the observability section.
web: https://docs.giantswarm.io/getting-started/observability/
source: https://github.com/giantswarm/docs/tree/main/src/content/getting-started/observability

[kubernetes-audit]: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/

**Comment by QuentinBisson** [comment]
Both issues are similar https://github.com/giantswarm/giantswarm/issues/16744

**Comment by QuentinBisson** [comment]
Ongoing draft https://github.com/giantswarm/docs/pull/1692

**Comment by QuentinBisson** [comment]
I'd rather we had a sample use case to the promtail app when we work on it

**Comment by TheoBrigitte** [comment]
The point here was to actually figure this out here, so we know how to do it in advance and we can help customer who are currently in need for this.

**Comment by QuentinBisson** [comment]
I was planning on explaining it in the doc but it's not the direction it's going

**Comment by QuentinBisson** [comment]
PR added https://github.com/giantswarm/promtail-app/pull/95

**Comment by QuentinBisson** [comment]
Example is added in the promtail app @TheoBrigitte can we close and you communicate that to customers or do we need to add the link to the audit log documentation?

**Comment by QuentinBisson** [comment]
Closing but I'm still expecting feedback @TheoBrigitte :)
