### ISSUE TITLE
Add new alertmanager webhook for MS Teams in prometheus operator

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#190]
**Is your feature request related to a problem? Please describe.**

As a user, I want to receive my alerts in Microsoft teams

**Describe the solution you'd like**

Use [webhook integration for that](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver) extending the Prometheus Operator Chart with this optional setting.

**Describe alternatives you've considered**

Use Slack 

**Additional context**

**Comment by cokiengchiara** [comment]
thanks @pipo02mix ! 

@giantswarm/team-halo @giantswarm/team-batman , we have an existing feature request to "Add webhook notifications to App Platform" https://github.com/giantswarm/giantswarm/issues/10013 - does that issue take care of the "get notifications in MS Teams, Slack, etc." in a general way?

**Comment by rossf7** [comment]
@cokiengchiara The features are similar but separate. Extending alertmanager to support Teams improves our monitoring stack.

giantswarm/giantswarm#10013 is about webhook notifications for app events. e.g. An app was updated or deleted. Or a new version is available for this app.
