### ISSUE TITLE
Define how we handle Promtail configuration

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1903]
Towards: https://github.com/giantswarm/roadmap/issues/311

We want to start shipping Promtail as early as possible to all clusters (MCs and WCs).
In order to achieve this we want to ship Promtail disabled by default with a dummy configuration to scrape nothing, and have the ability to enable it and configure it later on.

In the scope of this task we should define what would be the mechanism to :
- enable Promtail on each cluster
- update Promtail configuration

**Comment by QuentinBisson** [comment]
My idea here is to have a logging-controller that would create a configmap and a secret for each cluster named 
logging-configuration or something that would be mounted by the observability-bundle as extra-configs

The issue I have here is that vintage would not allow us to add extraconfigs properly as opposed to CAPI but that is something we could edit with the logging controller.

This configuration would both enable/disable promtail but eventually configure promtail as well. What do you think?

**Comment by TheoBrigitte** [comment]
I merged the rfc so I'm closing this, happy to discuss further when we get there.
