### ISSUE TITLE
Infrastructure access for GS using Crossplane

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1906]
figure out how to configure infrastructure access through crossplane for giant swarm
    - use case: we want to create a S3 bucket everywhere we deploy harbor
    - info about how it works and what's needed in crossplane: https://docs.crossplane.io/v1.10/reference/configure/
    - idea: let's only provide docs that show how to add a secret to MCF. Then, for each use case, a user can add a new provider access secret tuned and limited to their scope, without us solving the problem of how to provide a generic, yet secure set of permissions
        - it still doesn't help with tasks like "I need 1 new access token for S3 on each MC"
    - docs for the above

**Comment by piontec** [comment]
Access using infrastructure provider generated keys is tested and worked for the Harbor project. Results are described [here](https://github.com/giantswarm/crossplane-examples).
What's left is to figure out key-less access on AWS

**Comment by piontec** [comment]
Examples how to do it are in the [crossplane-examples](https://github.com/giantswarm/crossplane-examples) repo.
