### ISSUE TITLE
Align CAPA registry config with RFC

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1910]
## Task

Align CAPA registry config with [RFC](https://github.com/giantswarm/rfc/pull/49).

## Background

This is currently being worked on for CAPVCD. See [PR](https://github.com/giantswarm/cluster-cloud-director/pull/79/files).

**Comment by alex-dabija** [comment]
More info on the TODO in [Slack](https://gigantic.slack.com/archives/C03LV8E0RL7/p1678097693307449).

**Comment by fiunchinho** [comment]
From what I gathered, it looks like [on line 148](https://github.com/giantswarm/mc-bootstrap/blob/4e747bab7096db9abad8c65f926c95cae80f2b57/scripts/setup-fleet-branch.sh#L148-L152), there is logic based on the env var `CONFIGURE_CONTAINER_REGISTRIES` to add a Secret to the App CR with the registry credentials. [But on line 261](https://github.com/giantswarm/mc-bootstrap/blob/4e747bab7096db9abad8c65f926c95cae80f2b57/scripts/setup-fleet-branch.sh#L259-L288), we have pretty much the same logic, based on the var `registryAuthEnabled`, which I don't know where it comes from.

From vaclav
> AFAIK the way how we put the registry auth via ENV vars  was before the RFC about container registry taken place, now only the injection via the RFC works as the values changes also in the `cluster-aws`.
> That part inserted by us is probably not working anymore anyway, so the part with registryAuthEnabled can be removed.
