### ISSUE TITLE
Dex pods did not have proxy envs injected during an update

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1921]
## Issue

During an update on `goat` the `dex` pods were rolled but the kyverno webhook did not reacted and did not injected the proxy env values,  I assume the pods were recreated when the kyverno was being recreated as well,  it was fixed by deleting the dex pods afterwards.

The issue caused that SSO login did not work so I had to use the kubeconfig from LastPass.

Deleting the pods fixed the problem.

## TODO

- [ ] Investigate why the proxy environment variables were not injected for Dex.

**Comment by fiunchinho** [comment]
Something similar happened last week, flux pods did not have the env vars set because the cluster was having some issues and probably kyverno was not running at that moment.

**Comment by fiunchinho** [comment]
This is related https://github.com/giantswarm/roadmap/issues/1993
