### ISSUE TITLE
Static manifests are using the `k8s.gcr.io/` registry

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1923]
## Issue

Static manifests are using the `k8s.gcr.io/` registry, we could be throttled when images are pulled on private clusters. Also, this registry is deprecated. See [upstream docs](https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io).

## Solution

- Mirror the images on Giant Swarm's registries and update the static manifests.

## Resources

- [retagger](https://github.com/giantswarm/retagger/blob/main/images.yaml).

**Comment by bdehri** [comment]
https://github.com/giantswarm/cluster-gcp/pull/200
