### ISSUE TITLE
Proxy change for upstream CAPVCD

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#1924]
We need to find a way to support our proxy setup with upstream repo and remove this commit from our repo 
https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/9/commits/bb55c60bb00597f25b2a47b51e29f18792b5422e

towards https://github.com/giantswarm/roadmap/issues/1125

**Comment by erkanerol** [comment]
Upstream PR: https://github.com/vmware/cluster-api-provider-cloud-director/pull/395

**Comment by erkanerol** [comment]
I verified the PR on our side. I am waiting for a review from upstream maintainers. Moving this to Waiting column.

**Comment by erkanerol** [comment]
The upstream PR is still open. I have 2 approvals and waiting for the last approval.

**Comment by erkanerol** [comment]
The upstream PR was merged yesterday after two months. 🎉
