### ISSUE TITLE
[reminder] remove/rename crossplane-provider-* image repos when don't needed anymore

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1929]
[reminder] remove crossplane-provider-* image repos if we don't need them anymore (maybe rename upbound-provider-* repos too if we want, but maybe not, cos we might  need to differentiate official and community providers in the long run)

**Comment by gianfranco-l** [comment]
@uvegla is this still relevant? what shall we do with this?

**Comment by uvegla** [comment]
Yea, I think this is still relevant. Let's fix retagger and roll out the new crossplane version and then we can quickly get this short clean up done.

**Comment by piontec** [comment]
done
