### ISSUE TITLE
Display the IP address capacity and usage

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#193]
## User Story

_As a cluster admin, I want to know how many IP addresses are in use and how many addresses are still available in my installation, so that I can understand growth limitations more clusters, nodes, pods._

## Details, Background

Each installation is configured with a range of IP addresses to be used for nodes and pods.

Whenever a workload cluster is created, and whenever a node pool is created, sub sections of the IP range get allocated for these.

This means that the installation-wide IP range and the allocated subnets create growth limits for the number of clusters, node pools and nodes to be created.

Currently, users have no insight into the IP addresses in use on any of these levels, nor into the number of remaining IPs.

**Comment by cokiengchiara** [comment]
sig product Mon, 03. May 2021
* would be helpful for customer admin experience
* @snizhana-dynnyk : Biscuit, because IPs on management clusters. 
* And it also affects workload clusters.
* Stays relevant w cluster api.
