### ISSUE TITLE
CAPA `v1beta2` breaks the subnet config

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1932]
## Issue

CAPA `v1beta2` breaks the subnet config.

## Links

- [Upstream issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4026)
- [Upstream draft doc "Rethinking Networking in CAPA"](https://docs.google.com/document/d/1MRZ-VGr1-ztb7s159FkITcJiO3Gz5VD5F_iYh-o0D7s/edit#heading=h.ob01gtmo0s24)

**Comment by AndiDog** [comment]
We will continue in https://github.com/giantswarm/roadmap/issues/1979. Support for managed network was merged into our CAPA fork, but is not in upstream (https://github.com/giantswarm/cluster-api-provider-aws/pull/437).

**Comment by AndiDog** [comment]
I opened https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4637 to sync our test for the managed subnet functionality back into upstream. This avoids differences to our fork in the long run and ensures that nobody can accidentally break the functionality again.
