### ISSUE TITLE
CAPZ Remove changing labels from templates of Machines to avoid un-needed restarts

### ISSUE THREAD

**Issue by primeroz** [giantswarm/roadmap#1935]
### Motivation
Whenever the `charts` version change this is propagated as a label to the Machines ( both on CP and Worker Nodes of a MD) causing un-needed restarts 

labels:
- helm chart version

### Todo
- remove all mutating labels from the machine templates

### Outcome
- Only have restart of nodes when is needed

**Comment by bavarianbidi** [comment]
let's check `CAPA` and `CAPG`

**Comment by bavarianbidi** [comment]
ATM the following labels got propagated into `kcp` and `machines`:

```
{{- define "labels.common" -}}
{{- include "labels.selector" $ }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
helm.sh/chart: {{ include "chart" . | quote }}
application.giantswarm.io/team: {{ index .Chart.Annotations "application.giantswarm.io/team" | quote }}
{{- end -}}

{{/*
Selector labels
*/}}
{{- define "labels.selector" -}}
app: {{ include "name" . | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
cluster.x-k8s.io/cluster-name: {{ include "resource.default.name" . | quote }}
giantswarm.io/cluster: {{ include "resource.default.name" . | quote }}
giantswarm.io/organization: {{ required "You must provide an existing organization" .Values.metadata.organization | quote }}
{{- end -}}
```

the following providers are doing the same
* [gcp](https://github.com/giantswarm/cluster-gcp/blob/a3a3984c032c9c8a457ac334bccd6a0cc70a3d54/helm/cluster-gcp/templates/_helpers.tpl#L17-L36)
* [capa](https://github.com/giantswarm/cluster-aws/blob/e08b01c1cc23c2221a0613ef8c8b3caf3d3c2817/helm/cluster-aws/templates/_helpers.tpl#L17-L37)
* [cloud director](https://github.com/giantswarm/cluster-cloud-director/blob/090dc060425aafc9c6a3cdbd0791aeb30c1b5b9d/helm/cluster-cloud-director/templates/_helpers.tpl#L22-L43)

All those providers or using these label to generate different kind of specs and generate a `hash` which is used in multiple ways later on.

**Comment by bavarianbidi** [comment]
created issue https://github.com/giantswarm/roadmap/issues/2224 as follow up to track and discuss this issue on a KaaS level
