### ISSUE TITLE
cgroup version info on node level

### ISSUE THREAD

**Issue by luca-rui** [giantswarm/roadmap#1938]
## Story
I want to be able to easily identify which nodes are on which cgroup version, without having to look/compare which node came from which nodepool, where this info is held.

## Background
cgroups v1 is here to stay for some customers and clusters need to be managed accordingly by their platform teams

**Comment by T-Kukawka** [comment]
can u describe the usecase a bit @luca-rui ?

**Comment by T-Kukawka** [comment]
Luca we are adding this to 18.2.0

**Comment by T-Kukawka** [comment]
Closing - will be released with 18.2.0
