### ISSUE TITLE
Azure Release v13.0.0 with Kubernetes v1.18

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#194]
ℹ️ Team Celestial is drafting Azure v13.0.0-beta1 preview release to give customers early access to Node Pools features. This released is not meant for production clusters, but to allow testing the upgrade path from previous releases to 13.0.0.
It will be possible to upgrade from this beta to the stable 13.0.0 release.

## Pre-Release
- [x] Create release ticket on [Releases board](https://github.com/orgs/giantswarm/projects/136)
- [x] Make an announcement on #sig-product that team is doing a release. Include a link to the ticket from the release board.
- [x] Make sure release was tested by creating new cluster, upgrading from older version and with HelloWorld app.
- [x] Aggregate release notes from all changed components and add to `README.md` in the release directory.
- [ ] Send draft release announcement to #sig-product for review ASAP.
- [x] Verify documentation is up to date.

## Releasing
- [x] Create release PR
[Instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/)
    - [x] Define new release in `release.yaml` file.
    - [x] Activate new release by setting `state` to `active`.
    - [x] Deactivate old release if it's within same major version (`state: deprecated`). Verify with PO if you have doubts.
    - [x] Check versions of all components included. They shouldn't be lower than those in the previous release unless there was a rollback.

[Example PR](https://github.com/giantswarm/releases/pull/318)
- [x] Release relevant operators.
    - [x] Tag release branch.
    - [x] Bump operator version in draft release.
- [x] Make sure that WIP releases in releases repo branch are removed and not merged to master since the master branch is deployed automatically after merging PR and that would make WIP releases visible in customers’ installations which should generally not happen.

## Post-Release
- [x] Update front-end cluster with the new release.
- [x] Verify release is available on all installations. You can use [this script](https://github.com/giantswarm/azure-operator/blob/25bf788946c5405532b3b4b76c54b8e685ee291b/scripts/list-releases.sh).
- [ ] Send out release announcement to all customers according to [these instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/#release-notes).
- [ ] PO subscribes to release posts on Slack to get notifications if there are follow-up messages.
- [ ] Close release task on Releases board.

**Comment by tuommaki** [comment]
From Marcel:
> Please include `kube-state-metrics@v1.3.0` and `node-exporter@v1.7.0` in future `13.0.0` releases. Those updates prevent issues when upgrading from pre 13 versions.

To be more specific, those are apps in release.
