### ISSUE TITLE
[Spike] Improving Crossplane severe performance issues

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1946]
We are experiencing a lot of client side throttling on clusters with Crossplane installed, which seemingly became worse with the switch to official providers (they have a magnitude more CRDs, getting over 900 / 1000 on some clusters).

Also experiencing more frequent CRD install job OOM kills for some apps (flux, external-secrets) on clusters with Crossplane.

All these combined causes Flux helm releases to fail often / get stuck in upgrade e.g. helm-controller sees slowness, or crossplane takes too long to come up / get healthy and the CRD jobs getting OOM killed fails the pre install hooks and we end up with a timed out / failed release.

Having these on live clusters (e.g. banana did trigger alert on Friday) will end up with more alerts  for team on-call. Current clusters where we have these are mostly test clusters which are ignored and helm releases are normally reconciled when chart version changes or the flux helm releases is suspended and then resumed. These are the reasons why we don't have the alerts triggering at the moment.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/25892
```

**Comment by uvegla** [comment]
One attempted remediation was increasing QPS / Burst for `helm-controller`: https://github.com/giantswarm/management-clusters-fleet/commit/00e71bef060ae76b7f804d324e0ad9268e8a4bb1. It seemed to have somewhat lower the client side throttling but I would not decisively say it solved the issue.

**Comment by uvegla** [comment]
My other idea is to look into the CRD install job why a simple `kubectl` apply gets OOM killed applying ~10 CRDs / yaml files. I want to try to disable caching for the client as a first attempt.

**Comment by uvegla** [comment]
Tried this 2 scenario:

```shell
kubectl -v=6 apply -f /data/
kubectl --cache-dir="" -v=6 apply -f /data/
```

In both scenarios the `kubectl` bursts out 313 GET requests in roughly 1 second to the API, all of them return but the whole thing is in vain, cos it cannot write the discovery cache because the FS is read-only. Setting `--cache-dir=""` simply makes the root dir for the cache the working directory instead of `~/.kube/cache`; this is confirmed also by: https://github.com/kubernetes/client-go/blob/f457a57d6d2564ff06461d22ada3ff5ca6fec9c4/discovery/cached/disk/cached_discovery.go#L294

Based on: https://github.com/crossplane/crossplane/blob/master/design/one-pager-crd-scaling.md#client-side-throttling

**Comment by uvegla** [comment]
Some related issues / discussions:

- https://github.com/crossplane/crossplane/issues/2869
  - https://github.com/crossplane-contrib/provider-aws/pull/1076#issuecomment-1017162860

**Comment by gianfranco-l** [comment]
following up to [this](https://github.com/giantswarm/giantswarm/issues/25210#issuecomment-1418801895), Mathias from Upbound confirmed that official provider is best bet currently in terms of support/stability

**Comment by gianfranco-l** [comment]
related https://github.com/crossplane/crossplane/issues/3754

**Comment by gianfranco-l** [comment]
We discussed this in SIG Product, this was the outcome:
- If situation does not improve, we might put the general rollout of Crossplane on hold for the time being until it get solved. We rollout only for customers that really push for having it on MCs (= crossplane being a blocker for the strategic initiative) and accept explicitly the possible performance issues.
- We as honeybadger team plan to communicate to whole company and to customers (via AEs) the above if situation does not improve.
- It could be an idea to communicate customers that if they are willing to mitigate potential performance issues, they might consider having a scaled up cluster (= more cost).

**Comment by gianfranco-l** [comment]
meanwhile, [we are trying Crossplane on a virtual cluster](https://github.com/giantswarm/giantswarm/issues/25892)

**Comment by piontec** [comment]
We tried vCluster as isolation method and it works well, but creates new problems, such as:
- how to ensure resiliency of the in-vCluster etcd db?
- how to expose the api server of vCluster to customers in easy way?

As such, we finish this task and might get back to it when we resume crossplane activities
