### ISSUE TITLE
ESO deployment with interested customers

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1952]
- [x] engage with interested customers to start first early rollout and collect initial feedback
- [ ] iterate and improve on first customer feedback
- [ ] create necessary user and operator facing docs
- [ ] depends on https://github.com/giantswarm/giantswarm/issues/25132 to fully close

**Comment by gianfranco-l** [comment]
we received green light from AEs: once customer cluster is ready, we can start the deployment of first managed ESO app (coordinating with other impacted teams and the customer). cc @mproffitt

**Comment by mproffitt** [comment]
First customers have had this deployed. We will now go into a monitoring phase with them to verify that it is successful, after which we can start widening the customer base
