### ISSUE TITLE
Add container data for all Prometheus servers

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1957]
Towards: https://github.com/giantswarm/roadmap/issues/1955

We need to ingest container data for Prometheus servers, to observe:
- cpu usage
- memory usage
- disk space

We need to scrape those data from :
- kube-state-metrics
- cAdvisor

**Comment by marieroque** [comment]
What do we expect here:

* having these metrics on grafana-cloud to have a view of resources usage on all installation at the same time ?
* having these metrics per installation in order to debug an issue related to a customer ?

Currently, we have already all these interesting metrics (cAdvisor, kube-state-metrics, kubelet) on each installation.

The goal of the ticket is to send them to `Grafana Cloud` ?

@giantswarm/team-atlas

**Comment by hervenicol** [comment]
We expect to have these metrics per installation.
We don't have them for all namespaces.
Try to look at the data for a prometheus pod (disk usage, CPU, RAM) last time I looked for it I couldn't find.

**Comment by marieroque** [comment]
For example, this is a dashboard on  `anteater` and we have resources data for `deu01-prometheus` namespace:

https://grafana.g8s.anteater.dub.aws.k8s.3stripes.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=anteater&var-namespace=deu01-prometheus&var-type=statefulset&var-workload=prometheus-deu01&from=1675853343852&to=1675856943852

Is that we expected ?

![Image](https://user-images.githubusercontent.com/9134338/217522058-57ce6612-10bd-4a0d-a126-3af76b24d1af.png)

**Comment by marieroque** [comment]
We also have data on `persistent volume`:

https://grafana.g8s.anteater.dub.aws.k8s.3stripes.net/d/919b92a8e8041bd567af9edab12c840c/kubernetes-persistent-volumes?orgId=1&var-namespace=deu01-prometheus&var-volume=prometheus-deu01-db-prometheus-deu01-0&from=1675252358595&to=1675857158595


![Image](https://user-images.githubusercontent.com/9134338/217522417-50af94bd-8a42-49ab-b4c0-ddca7fd8b702.png)

**Comment by marieroque** [comment]
FYI, the regex on namespaces in scrape-config is:

```
[[- if eq .ClusterType "management_cluster" ]]
  - source_labels: [namespace]
    regex: (kube-system|giantswarm.*|.*-prometheus|monitoring|draughtsman|flux-.*)
    action: keep
```

We scrape all `*-prometheus` namespaces.

**Comment by QuentinBisson** [comment]
I'm not sure why we do not collect all metrics in the MCs but I think we have the data and this can be closed
