### ISSUE TITLE
Be able to enable PodNodeSelector admission controller (and others?)

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#196]
**Is your feature request related to a problem? Please describe.**

As a customer, I would like to enable PodNodeSelector so I can set a default node selector to my pods.

**Describe the solution you'd like**

Kubernetes versions come with a set of admission controllers enabled. At the same time, users can enable other embedded admission controllers adding the name of the controller in the API flag on the manifest

```
--admission-control=NamespaceLifecycle,...,PodNodeSelector
```

Most of these controllers need to set a default configuration. In order to do that API flag `--admission-control-config-file` has to be defined with the content of the admission controller configuration files:

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodNodeSelector
  path: podnodeselector.yaml
...
```

And finally in the `podnodeselector.yaml` configuration file you can define the user values:

```
podNodeSelectorPluginConfig:
 clusterDefaultNodeSelector: giantswarm.io/machine-deployment=dod7k
```

So ideally as customer I gave the name of the admission controller I want to enable  (or activate the one in the list in case we decide to whitelist them) and then provide a configuration file to be used. The cluster is created or modified to contain these values

**Describe alternatives you've considered**

Create a new custom admission controller

**Additional context**

**Comment by MartaD** [comment]
The easiest way to achieve the desired outcome here is by using an upstream bootstrap operator that provides the needed configuration options. The work is major, it requires refactoring of most of our operators and we believe it will take more than 3 months at this. 

Until then team Ludacris will take steps to make the current method more stable for the customers.
