### ISSUE TITLE
Monitor Prometheus itself

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1961]
Towards: https://github.com/giantswarm/roadmap/issues/1955

We need to ingest go data for Prometheus servers, to observe cpu and memory (real) usage.

Those data are available in Prometheus itself.

**Comment by QuantumEnigmaa** [comment]
Does this mean we need to create a dashboard in grafana for this ? Or is creating recording/alerting rule enough ?

**Comment by hervenicol** [comment]
Prometheus for WCs are not scraped.
Example: `prometheus_tsdb_head_samples_appended_total` has data only for the MC prometheus.

We should deploy servicemonitors for each WC prometheus so their data gets scraped.

**Comment by QuantumEnigmaa** [comment]
But is it a good idea since we will move at some point to prometheus-agent for all installations ?

**Comment by hervenicol** [comment]
I think so, because prometheus will still have to store data for a while. So, moving to prometheus-agent for scraping data does not mean we will/can remove WC prometheis from the MC.

**Comment by QuantumEnigmaa** [comment]
Ok makes sense :)

**Comment by hervenicol** [comment]
ok, we can see this data on each prometheus.
The only thing is it gets lost when the cluster is deleted. Not sure it's a problem though.

So, any other data missing for prometheus investigations :question:
