### ISSUE TITLE
Add Prometheus dashboard

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1963]
Towards: https://github.com/giantswarm/roadmap/issues/1955

We need a dashboard to be able to dig into Prometheus data.

We want at least to see:
- memory usage
- cpu usage
- time series cardinality
- compare memory to node memory and vpa

**Comment by hervenicol** [comment]
Started working on it, going for a "meta-dashboard" that we can use as an opsrecipe, listing all useful dashboards and explaining why / what to look at.

Draft looks like this:
![Image](https://user-images.githubusercontent.com/12008875/218860816-4e27a787-fbbf-410e-b462-29a7c988a37e.png)

**Comment by marieroque** [comment]
Improvement of the Prometheus dashboard:
- add persistent volume usage graph
- add limit serie on memory usage graph
- add limit serie on cpu usage graph
- add a filter on the cluster id

Charts based on prometheus metrics will need to be updated when all prometheus will be scraped.

**Comment by hervenicol** [comment]
Idea from here: https://github.com/giantswarm/giantswarm/issues/25877#issuecomment-1437401085

We could track most time-intensive rules groups because they're probably the ones responsible for CPU usage.

**Comment by marieroque** [comment]
Before:
![Screenshot-20230221115930-2503x1048](https://user-images.githubusercontent.com/9134338/220327252-c4e03432-465d-4a4d-b3ae-d49dbd3750db.png)

After:
![gnome-shell-screenshot-4b9a0m](https://user-images.githubusercontent.com/9134338/220327479-25b76ba2-db1d-420d-b462-eca903b315a9.png)

**Comment by hervenicol** [comment]
A few interesting queries around cardinality:

* Top 10 series count by metric names:
`topk(10, count({job=~".+"}) by (__name__))`

* Top 10 jobs:
`topk(10, count({__name__=~".+"})by(job))`

* Top10 serie/job:
`topk(10, count({job=~".+"}) by (job, __name__))`

* Top churning series:
`topk(5, max_over_time(scrape_series_added[5m]))`

**Comment by marieroque** [comment]
See PR: 
https://github.com/giantswarm/dashboards/pull/252
https://github.com/giantswarm/dashboards/pull/253

**Comment by QuentinBisson** [comment]
We did some improvements, let's release and make it better if we need it
