### ISSUE TITLE
Take ownership of app dependencies

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1965]
coming from [this](https://github.com/giantswarm/giantswarm/issues/24081#issuecomment-1420862888)

- Studying the app dependencies code and verifying impact
- Tests
- Create relevant docs

**Comment by ljakimczuk** [comment]
I briefly tested the feature. It is truely lightweight, it works, code looks clean, impact depends - the risk of bad impact is low in my opinion, in terms of positive impact it should increase flexibility of apps deployments. Doc has been created, closing the issue.
