### ISSUE TITLE
Be able to configure managed apps upfront (before cluster creation)

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#197]
**Is your feature request related to a problem? Please describe.**

As a customer, I want to customize a managed app providing specific configuration. Now I have to wait until the App Custom Resource is created to patch with a configmap name and namespace, and then create the configmap in that namespace. It makes it difficult to run it as part of the cluster provisioning.

**Describe the solution you'd like**

Be able to create a configmap with the specific values I would like to configure and the App Custom Resource is updated automatically taking my changes.

**Describe alternatives you've considered**

Provide a installation wide configuration for a managed app

**Additional context**

**Comment by cokiengchiara** [comment]
thanks @pipo02mix ! 

> (before cluster creation)

I guess thus far we assumed user creates cluster first before app. What is the use case where user is creating the app before the cluster...? Is that a commonly occurring use case?

**Comment by pipo02mix** [comment]
> I guess thus far we assumed user creates cluster first before app. What is the use case where user is creating the app before the cluster...? Is that a commonly occurring use case?

I am talking about managed apps, so we are creating the app (App CR together. with the cluster namespace). But. user would like to configure the app (configmap) at the same time cluster is created, and dont need to wait until our operator creates the App CR and cluster namespace.

**Comment by cokiengchiara** [comment]
@giantswarm/team-batman FYI on feature requests. I'll put it to backlog :)

**Comment by rossf7** [comment]
Lets try to cover this as part of the App Sets spec in #279

**Comment by piontec** [comment]
This is already possible if using Flux: https://github.com/giantswarm/gitops-template/blob/main/docs/apps/add_app_template.md
In hte future it might become a native feature of app-operator, but for now, the solution is in Flux. Closing.
