### ISSUE TITLE
CAPA upstream network proposal

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1979]
Follow-up for https://github.com/giantswarm/roadmap/issues/1932 to provide a long-term solution.

- [Upstream issue](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4026)
- [Upstream draft doc "Rethinking Networking in CAPA"](https://docs.google.com/document/d/1MRZ-VGr1-ztb7s159FkITcJiO3Gz5VD5F_iYh-o0D7s/edit#heading=h.ob01gtmo0s24)
- [CAPA slack discussion](https://kubernetes.slack.com/archives/CD6U2V71N/p1679477173175129)

**Comment by AndiDog** [comment]
In a meeting with several maintainers, we coincided that adding a separate `AWSNetwork` CRD makes sense and starting with a prototype would be a good first step to prove that the solution could work (https://github.com/giantswarm/roadmap/issues/2629).
