### ISSUE TITLE
CAPA `mc-bootstrap` on CI

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1980]
## Story

_*-As a Giant Swarm engineer, I want CAPA `mc-bootstrap` management cluster creation to run as part of our CI automation for every change in order to increase the confidence that a new CAPA management cluster can always be created.*_

## Background

The creation of a new CAPA management cluster is a very slow and error prone process. The scripts available keep on getting broken by changes which are not tested for CAPA. The current situation leads to a lot of developer time being wasted that could be used instead to build new features.

## Links

- [mc-bootstram CI requirements doc](https://docs.google.com/document/d/1o6S4XsR_9Uq_1UPcy_pK8Ra5dGKpGAOeUvR5IqgExIE/edit).

**Comment by fiunchinho** [comment]
I think we can close this one now.
