### ISSUE TITLE
Custom CA Support for accessing internal resources

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1988]
### Motivation
Especially from a private network point of view a lot of customers are using custom Root CAs to secure resources hosted in their internal networks. From Git-Repositories, over Artefact-Registries to Databases or ERP Systems; a lot of services and apps deployed on CAPI Workload Clusters might have to access those resources and therefore need support for any custom root CAs.

### User Stories

- [ ] TODO

### Outcome
- Customers should be able to add their root CAs to our Installations to make sure every cluster can access their internal resources.

**Comment by Rotfuks** [comment]
Cabbage should be able to help us there with their cert-manager. 
If Continental has a container registry, we have a bit more work, but everything else is just "on top" of our KaaS solution.

**Comment by gawertm** [comment]
managed Controlplanes need to be considered for this as well. cc @vvondruska

**Comment by stone-z** [comment]
@Rotfuks we had another BigMac --> Shield handover session today and weren't able to figure this one out.

Whether or not an application trusts a root CA is specific to that client's configuration. Can you shed any light on the idea behind this issue?

**Comment by Rotfuks** [comment]
Heya @stone-z ! This was relevant for a customer/prospect that's no longer interested in our solution - so if we don't struggle to see direct value here, let's just close it. Wdyt?

**Comment by stone-z** [comment]
In any case I'm happy to close it if the prospect is out, and maybe their need was something valuable for others in the future, we just couldn't figure out from the wording in this issue what the feature actually was 😄  I'd be curious to know. I'll close this now but would happily have a quick sync if you can remember

**Comment by Rotfuks** [comment]
They generally had this private network setup for which we created the private endpoint/private link setup of CAPZ. 
So we had a lot of issues around their private network concepts, just as this. The idea here as far as I remember was, that the apps that run on the clusters were running in the public cloud environment, but they had dependencies to their big secured internal network where all the onprem stuff like their ERP lived. Some apps might fetch information from an endpoint of that ERP, but need a company-specific custom cert with them to access that (or the other way around? Not sure anymore). Anyways that was the thing.
