### ISSUE TITLE
Empty `ca.crt` for `dex-k8s-authenticator` and `dex-tls` secrets

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1992]
## Issue

The `ca.crt` value in `dex-k8s-authenticator` and `dex-tls` secrets for `dex-app` is empty. The value is required by the app if a private CA is used.

## Background

Private CAPA clusters use a custom CA and its public key needs to be made available to the `dex-app`.

The issue was encountered on `thor` & `thunder` where the `dex-tls` secret was manually updated. Unfortunately, the value in `ca.crt` is overwritten on the next deployment.

## Possible solution

Update the `dex-app` to accept a second secret which contains only the CA's public key and mount the `ca.crt` from this one instead of the `dex-tls` secret.

## TODO

- [ ] Update the app to not overwrite the `ca.crt`;
- [ ] Deploy the change to all impacted clusters;
- [ ] ...

**Comment by alex-dabija** [comment]
@weatherhog I'm dispatching this to @giantswarm/team-rainbow because you own the app.

**Comment by vvondruska** [comment]
@alex-dabija Where does the CA come from? 
AFAIK it needs to be configured manually in Dex App chart values in case letsencrypt is disabled.

When the `.Values.ingress.tls.letsencrypt` property is not `true`, the Dex app deployment creates a secret called `dex-tls` and populates it with contents of properties defined here: https://github.com/giantswarm/dex-app/blob/main/helm/dex-app/values.yaml#L27

Does it need to come from an existing secret?

The `dex-k8s-authenticator` secret is populated with the same properties. Does the authenticator need a different certificate and key? If so, then we need to expose them if a new set of properties.

**Comment by alex-dabija** [comment]
> @alex-dabija Where does the CA come from? AFAIK it needs to be configured manually in Dex App chart values in case letsencrypt is disabled.

The CA's public key is stored in a secret (`giantswarm / installation-ca`) on the MC:
```
kubectl -n giantswarm get secret installation-ca -o yaml
```


> When the `.Values.ingress.tls.letsencrypt` property is not `true`, the Dex app deployment creates a secret called `dex-tls` and populates it with contents of properties defined here: https://github.com/giantswarm/dex-app/blob/main/helm/dex-app/values.yaml#L27

Yes, we saw , but the same secret name `dex-tls` is configured on the ingress CR, which means that it's overwritten by `cert-manager` and it doesn't have the `ca.crt` property set (it's unknown to `cert-manager`).

> 
> Does it need to come from an existing secret instead?

Yes, the `ca.crt` value should be taken from the `giantswarm / installation-ca` secret. 


> 
> The `dex-k8s-authenticator` secret is populated with the same properties. Does the authenticator need a different certificate and key? If so, then we need to expose them if a new set of properties.

I don't really know. We manually updated the secret to fix the problems that we are seeing.

**Comment by vvondruska** [comment]
This is a short summary of the issue after further discussion with Alex:
We need to introduce an additional way to configure the certificates in private clusters with a custom CA and certificates managed by cert manager: provide a reference to an existing secret, which contains the CA, mount it to Dex K8s Authenticator and let the cert manager do the rest.

**Comment by vvondruska** [comment]
@alex-dabija 
This PR adds a possibility to configure the trusted root CA for the `dex-k8s-authenticator` app from an existing resource: https://github.com/giantswarm/dex-app/pull/248
The `dex-k8s-authenticator` secret for ingress is still created during the app installation, but if I understand it correctly, the certificate and key should be populated by the cert manager and the CA won't matter anymore.
Is this solution acceptable?

**Comment by alex-dabija** [comment]
> @alex-dabija This PR adds a possibility to configure the trusted root CA for the `dex-k8s-authenticator` app from an existing resource: [giantswarm/dex-app#248](https://github.com/giantswarm/dex-app/pull/248) The `dex-k8s-authenticator` secret for ingress is still created during the app installation, but if I understand it correctly, the certificate and key should be populated by the cert manager and the CA won't matter anymore. Is this solution acceptable?

Yes, the solution looks good to me. @Jose could have a look over the [PR](https://github.com/giantswarm/dex-app/pull/248)?

**Comment by vvondruska** [comment]
The change has been released in v1.32.3

The custom CA can be configured in the Dex app's user values like this:

```yaml
trustedRootCA:
  name: "ca.pem"
  secretName: "installation-ca"
```

The `ingress.tls-letsencrypt` property needs to be `false`.

**Comment by fiunchinho** [comment]
Added config for `thor` and `thunder` https://github.com/giantswarm/config/pull/1611

**Comment by fiunchinho** [comment]
We just need to resume `flux` on `thor` for the changes to be applied`. @AndiDog is working with `thor` at the moment and needs `flux` to be suspended. When that work is done, `flux` will be resumed and configuration applied.
