### ISSUE TITLE
No proxy environment variables inject if Kyverno is down

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1993]
## Task

Ensure the proxy environment variables are inject even if Kyverno is down or after Kyverno recovers.

## Background

The proxy environment variables were not injected because Kyverno was down which lead to a lot of pods to not work or crash.

## Possible solutions

- cron job to monitor if the proxy environment variables are injected and if they match the current configuration;
- an operator to monitor if the proxy environment variables are injected and if they match the current configuration;
- ensure that no pods (except the critical ones) can be started if the Kyverno rule (which injects the environment variables) is not active;
- ...

## TODOs

- [ ] investigate how the proxy environment variables are injected;
- [ ] decide on which solution to implement;
- [ ] ...

## Links

- [Proxy RFC](https://github.com/giantswarm/rfc/pull/50).

**Comment by stone-z** [comment]
Yes it would most likely be technically possible to use a `mutateExisting` policy to apply the proxy variables to Pods (or better yet Pod controller) specs. Whether that is optimal is another question, which would need some thorough testing.

Offhand, the concerns I would have are: 
- the feature is rather new and we (shield) haven't seen it used, so unknown unknowns
- if the policy is changed or Kyverno suddenly comes up, we'd roll all pods at once
- unclear idempotence -- IIUC the policy must still be triggered by an admission event, so the policy would 1. need to wait until that event and then 2. take into account whether the variable already exists (alphabetical/yaml ordering, etc.) to ensure it didn't re-modify existing pods
- competing with gitops - if injecting proxy variables into pod controllers (Deployments, etc.) or bare Pods managed by gitops (we don't do this to my knowledge but customers might) then the policy would compete

It could work; I'm on the fence about if it should. Would be good to consider some alternatives. Maybe something like a watchdog service to send the pods back through admission in a more controlled way.

> general hardening of the Kyverno setup

To our knowledge, the latest Kyverno release has been very stable and we're still shipping more monitoring improvements. Anything new to discuss here?

**Comment by fiunchinho** [comment]
Before implementing a solution to the problem I'd suggest trying to figure out why this happens in the first place. We deploy `kyverno` with a PDB, meaning that _in theory_ there should be `kyverno` replicas running when we trigger a rolling upgrade of the worker nodes. If we end up without `kyverno` replicas running in the cluster, then there is something strange going on. Does this happen only when upgrading a cluster? Only when we just created the cluster but never again? I wouldn't implement a solution until we figure it out.
