### ISSUE TITLE
Kubernetes Version 1.25 Suppport on Vintage

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1994]
### Motivation
[Kubernetes Version 1.25](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/) brings a lot of newly graduated features and makes Kubernetes overall a bit more stable and secure. Additionally active maintenance support for our currently used Kubernetes Version 1.24 will stop on 28. July 2023. In order to keep our platform secure and stable we need to upgrade the Kubernetes Version we use to 1.25.

```[tasklist]
### Stories
- [ ] https://github.com/giantswarm/roadmap/issues/2533
- [ ] https://github.com/giantswarm/roadmap/issues/2534
- [ ] https://github.com/giantswarm/roadmap/issues/2535
- [ ] https://github.com/giantswarm/roadmap/issues/2536
- [ ] https://github.com/giantswarm/roadmap/issues/2537
```

### Outcome
- Our platform has improved stability, security and some new core-kubernetes features for customers like ephemeral debug containers, pss and more.

**Comment by njuettner** [comment]
Milestone achieved 🎉
