### ISSUE TITLE
OS default settings for CAPA

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1995]
## Story

_*-As a cluster admin, I want to have the same OS default settings as I have on AWS vintage cluster in order to improve the security of CAPA clusters.*_

Towards [epic](https://github.com/giantswarm/roadmap/issues/426).

## Background

CAPA clusters use Ubuntu as the OS without any additional configuration, but the AWS vintage clusters use Flatcar as the OS with many Giant Swarm custom settings.

## TODOs

- [ ] https://github.com/giantswarm/roadmap/issues/996;

## Links

- [Overarching epic](https://github.com/giantswarm/roadmap/issues/426).

**Comment by calvix** [comment]
Done as part of the Flatcar issue
