### ISSUE TITLE
Decide on whether to run multiple node exporter

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#200]
GS runs node exporter. When customer starts Managed Prometheus, node exporter is added again. 

So now there are two node exporters - one for Managed Apps and one for Giant Swarm. 

Maybe Managed Apps could be modified? 

Customer encountered problems when he tried to do it. 

Running exporter by default causes some alerts.

@giantswarm/team-halo FYI I created this issue for when we focus on Prometheus. Learned about it in call w customer.

**Comment by TheoBrigitte** [comment]
Closing this as duplicate from https://github.com/giantswarm/giantswarm/issues/24814
