### ISSUE TITLE
Handle multi-line string properties in schema based UI

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#2005]
Our cluster creation UI should support strings which must contain line breaks. Example: CA certificate in PEM format.

**Comment by marians** [comment]
From https://github.com/giantswarm/roadmap/issues/1181#issuecomment-1424153359

For multi-line string values, our current input fields don't seem to support those well. When I paste a multi-line PEM certificate into a field, it seems like the line breaks get removed.

![image](https://user-images.githubusercontent.com/273727/217818741-3217f88f-65fb-469d-ba42-47f4371b5bcf.png)

This is the values payload I get from our preview at the bottom of the UI:

```json
{

  "clusterName": "kk56k",

  "organization": "giantswarm",

  "controlPlane": {

  
  "oidc": {

  
  
  "caPem": "-----BEGIN CERTIFICATE----- MIICLDCCAdKgAwIBAgIBADAKBggqhkjOPQQDAjB9MQswCQYDVQQGEwJCRTEPMA0G A1UEChMGR251VExTMSUwIwYDVQQLExxHbnVUTFMgY2VydGlmaWNhdGUgYXV0aG9y aXR5MQ8wDQYDVQQIEwZMZXV2ZW4xJTAjBgNVBAMTHEdudVRMUyBjZXJ0aWZpY2F0 ZSBhdXRob3JpdHkwHhcNMTEwNTIzMjAzODIxWhcNMTIxMjIyMDc0MTUxWjB9MQsw CQYDVQQGEwJCRTEPMA0GA1UEChMGR251VExTMSUwIwYDVQQLExxHbnVUTFMgY2Vy dGlmaWNhdGUgYXV0aG9yaXR5MQ8wDQYDVQQIEwZMZXV2ZW4xJTAjBgNVBAMTHEdu dVRMUyBjZXJ0aWZpY2F0ZSBhdXRob3JpdHkwWTATBgcqhkjOPQIBBggqhkjOPQMB BwNCAARS2I0jiuNn14Y2sSALCX3IybqiIJUvxUpj+oNfzngvj/Niyv2394BWnW4X uQ4RTEiywK87WRcWMGgJB5kX/t2no0MwQTAPBgNVHRMBAf8EBTADAQH/MA8GA1Ud DwEB/wQFAwMHBgAwHQYDVR0OBBYEFPC0gf6YEr+1KLlkQAPLzB9mTigDMAoGCCqG SM49BAMCA0gAMEUCIDGuwD1KPyG+hRf88MeyMQcqOFZD0TbVleF+UsAGQ4enAiEA l4wOuDwKQa+upc8GftXE2C//4mKANBC6It01gUaTIpo= -----END CERTIFICATE-----"

  
  }

  }
}
```

**Comment by marians** [comment]
What if we use textareas for some string properties? Some things I'm concerned about:

- Can we always know that we expect a multi-line value for a property? And where would the difference be encoded? In the JSON Schema? In the UISchema?
- Currently we use input type "text" for strings. Can we instead make the control use textarea? Visually, the height should be a single line by default. As soon as line breaks are entered, the field should grow up to a maximum height.

@kuosandys

**Comment by kuosandys** [comment]
> Can we always know that we expect a multi-line value for a property? And where would the difference be encoded? In the JSON Schema? In the UISchema?

As I understand, any property that has `"type": "string"` as defined in JSON schema could potentially include newline characters. Encoding the property names of fields that should use textarea rather than text in UI schema does not sound maintainable to me in the long run.

> Currently we use input type "text" for strings. Can we instead make the control use textarea? Visually, the height should be a single line by default. As soon as line breaks are entered, the field should grow up to a maximum height.

I like the idea of using textarea throughout, and auto-resizing the height based on input 👍  We can also disable manual resizing with a mouse
