### ISSUE TITLE
Loki testing

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2008]
# Loki Tests

These tests should be part of the PR Checks: 
- [x] Validate Helm chart templating
- [ ] Deploy chart
  - [ ] Kind (single instance)

These tests should be part of the tinkereres ci: 
- [ ] Deploy chart
  - [ ] AWS, Azure, CAPI (later)
- [ ] Integration test; Verify all component work together
  - [ ] multi-tenant-proxy + Loki setup
  - [ ] Using canary to generate traffic

### Inspired from

- https://github.com/grafana/loki/blob/main/.github/workflows/helm-ci.yml
- https://github.com/grafana/loki/blob/main/production/helm/loki/src/helm-test/canary_test.go

**Comment by QuantumEnigmaa** [comment]
Concerning e2e tests we discovered that the [apptest-framework](https://github.com/giantswarm/apptest-framework) doesn't support MC-only app. 

We thus decided to go another way and build our own custom "e2e" tests framework : 

* We will update the PR message to empower the user to perform the required tests before asking reviews for its PR. 
* A dedicated directory will be created at the repo's root with a file describing the test procedure and possible scripts.
* Concerning Loki specifically, the testing procedure will consist in deploying the PR's branch version to a giantswarm testing MC with canary enabled, let it run a bit and check on the dedicated dashboard that eveything is working well.

**Comment by QuantumEnigmaa** [comment]
Manual test procedure and script added to the app's repo
