### ISSUE TITLE
vpa `crd-install` job fails in CAPI clusters

### ISSUE THREAD

**Issue by fiunchinho** [giantswarm/roadmap#2009]
# Context

We currently install VPA using two different apps:
- vertical-pod-autoscaler
- vertical-pod-autoscaler-crd

These two apps [are default apps](https://github.com/giantswarm/default-apps-aws/blob/master/helm/default-apps-aws/values.yaml#L193-L216), meaning they are installed on both MCs and WCs. The default apps names are prefixed by the cluster name. So for example, default apps on `thor` are called `thor-vertical-pod-autoscaler` and `thor-vertical-pod-autoscaler-crd` respectively.

# Problem

The problem is that the `vertical-pod-autoscaler` app [has a job that fails](https://github.com/giantswarm/vertical-pod-autoscaler-app/blob/main/helm/vertical-pod-autoscaler-app/templates/crd-patch/crd-job.yaml#L42) to find the `vertical-pod-autoscaler-app` chart because it expects the chart name without any prefix. Can the job be fixed so that it works in both `vintage` and `capi`?

# Questions to the owners

Why do we have that job? Could we remove it? Actually, could we merge both `vertical-pod-autoscaler` and `vertical-pod-autoscaler-crd` into a single app?

**Comment by alex-dabija** [comment]
@TheoBrigitte I'm moving the issue to @giantswarm/team-atlas because you are the owner of the app.

**Comment by QuentinBisson** [comment]
Migrated to helm chart dependency, let's check if this happens again

**Comment by fiunchinho** [comment]
What was migrated?

The name of the `chart` CR doesn't get prefixed, only the `App` CR, so I don't know why it complained when I saw it, but this didn't happen last week when recreating `thunder`. So I think it's fine.

Anyway the questions are still valid IMHO.

> Why do we have that job? Could we remove it? Actually, could we merge both vertical-pod-autoscaler and vertical-pod-autoscaler-crd into a single app?

**Comment by QuentinBisson** [comment]
I added a comment for atlas :D 
We are migrating the app to chart dependency instead of git subtree. We are just discussing the need for the crd job here https://github.com/giantswarm/vertical-pod-autoscaler-app/pull/153

**Comment by QuentinBisson** [comment]
Moving to backlog as it's being worked on by @QuantumEnigmaa

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa had issues testing it on thor, testing on golem right now

**Comment by QuantumEnigmaa** [comment]
The tests on golem MC and WC went fine but also shed light on the need to add a `app-operator.giantswarm.io/depends-on` label on `vertical-pod-autoscaler-app` since we need the `vertical-pod-autoscaler-crd` app CR to be installed before to avoid conflicts.

**Comment by QuantumEnigmaa** [comment]
After merging this PR : https://github.com/giantswarm/default-apps-aws/pull/182 we should be good for release on CAPI :)

**Comment by fiunchinho** [comment]
> Actually, could we merge both vertical-pod-autoscaler and vertical-pod-autoscaler-crd into a single app?

I asked this when creating the issue. Has anyone taken a look at a potential answer?

**Comment by QuantumEnigmaa** [comment]
This is what we plan to do indeed. The current vpa-app is already able to install the CRDs by itself withoutn needing th crd-app

**Comment by fiunchinho** [comment]
So why are we adding the dependency on the `vpa-crd` app on this PR? https://github.com/giantswarm/default-apps-aws/pull/182

If the `vpa` app is capable of installing the CRDs, we wouldn't need the `vpa-crd` app at all, right?

**Comment by fiunchinho** [comment]
That's independent from the `dependsOn` PR, right? You can still do two releases, one adding the new VPA with CRDs, and another one removing the old `vpa-crd`.

If you remember to delete the `dependsOn` change once the `vpa-crd` is gone, I'm fine with it :smile:  But I believe is more work than it needs to be.

**Comment by fiunchinho** [comment]
Ok, makes sense. Thanks for explaining.

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa I think this is done right? You are working on releasing it but it should be in the umbrella ticket I think
