### ISSUE TITLE
Allow customers to configure Kubernetes API in workload clusters

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#201]
**Is your feature request related to a problem? Please describe.**

As a user, I would like to modify  API parameters dynamically to enable feature gates or admission controllers.

Now we set some default but they cannot influence it. If they want to try a feature gate or add admission controller they need. to use `k8s-initiator-app` to hack the master instance thanks to daemonset.

Ex:
- `--registry-qps`, `--registry-burst` For clusters were application have a high number of replicas (and big nodes that could hold several)  `QPS` limit is exceeded. 
- `--allowed-unsafe-sysctls` Some customer workloads need to harden the worker machines increasing default Kernel values. When these parameters are no safe, then kubelet flag should be added.

**Describe the solution you'd like**

Make configurable feature gate, audit policy, admission controllers,... flags to let our customers configure different options available on k8s API.

Ideall  we offer a way to enable/disable these options (Configmap on Control Plane or properties in a  CR).

It would be a  pre-requisite for https://github.com/giantswarm/roadmap/issues/196

**Describe alternatives you've considered**

Make the  `k8s-initiator-app` worked for all use-cases.

**Additional context**

**Comment by puja108** [comment]
@cornelius-keller and the team were thinking of moving toward this with ignition-operator and adaption of more upstream CAPI work.

**Comment by MartaD** [comment]
Yes this is the preferred way, @pipo02mix we plan to start working on the ignition-operator in Q1 2021, is this an acceptable timeline for this story? it would allow us to not invest more time in the solution we would like to remove anyway.
