### ISSUE TITLE
irsa-operator fails to connect to CloudFront from private MC

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2016]
On MC `goat`, I'm experiencing this for the reconciliation of several WCs:

```
irsa-operator-865b66d59-wdrlt irsa-operator 2023-02-14T16:08:56.470112217+01:00 E0214 15:08:56.470008       1 capa.go:327] capa-controller "msg"="failed to create OIDC provider" "error"="failed to dial d2gze8svjon3kz.cloudfront.net:443: dial tcp 54.230.96.201:443: i/o timeout" "cluster"="berk2" "namespace"="org-giantswarm"

irsa-operator-865b66d59-wdrlt irsa-operator 2023-02-14T15:43:10.383076247+01:00 E0214 14:43:10.382975       1 controller.go:317] controller/awscluster "msg"="Reconciler error" "error"="failed to dial d2wwc9ozghjn5h.cloudfront.net:443: dial tcp 54.230.96.76:443: i/o timeout" "name"="andreas31" "namespace"="org-giantswarm" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="AWSCluster"
```

This is with https://github.com/giantswarm/irsa-operator/pull/98 so that we see TLS connection timeouts after a few seconds.

I believe this simply cannot work, as Internet traffic only works through the proxy. Using `curl https://<the failing cloudfront host>` in a debug pod works fine because it goes through the proxy (via injected env vars such as `https_proxy=http://proxy.goatproxy.gaws.gigantic.internal:4000`). Right now, irsa-operator uses `tls.Dial*` functions which do not use any proxy config.

Ideas:

- Use HTTPS client library instead of `crypto/tls`, and try to fetch the certificates that way. Since we use an HTTP squid proxy that performs [HTTP CONNECT tunneling](https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_method), this should work as the caller would see the actual host's certificate. We may have to add CloudFront to the proxy settings.
- We already provision an ACM (AWS Certificate Manager) certificate in case of public clusters (see `cloudfrontAliasDomain`). We could also use ACM here, and then fetch the certificate via AWS API instead of probing the CloudFront host.

**Comment by AndiDog** [comment]
I think this was fixed already via https://github.com/giantswarm/irsa-operator/pull/102. @njuettner / @AverageMarcus can you confirm and close here?

**Comment by calvix** [comment]
can 2e close this? I think it was solved in PR mentioned above by Andreas
