### ISSUE TITLE
[SPIKE] Investigate possible solutions

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2017]
## Task

Investigate & document possible solutions for https://github.com/giantswarm/roadmap/issues/1950 .

**Comment by fiunchinho** [comment]
One potential solution would be to add a new `Condition` to the `AWSCluster` CR when the `aws-resolver-rules-operator` operator is done reconciling. Then having a new reconciler inside one of the operators (the new big operator that would contain all reconcilers?) that removes the `pause` annotation when both `Conditions` are present, the `aws-resolver-rules-operator` condition and the vpc operator condition.

**Comment by fiunchinho** [comment]
I think we can close this one @alex-dabija . We have the other issue with an actual implementation.

**Comment by alex-dabija** [comment]
> I think we can close this one @alex-dabija . We have the other issue with an actual implementation.

Yes, I agree.
