### ISSUE TITLE
Configure registry mirrors for `thor`, `thunder`, `dev00`, `o11y`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2044]
## Task

Configure the GS Azure registry mirror for `thor`, `thunder`, `dev00`, `o11y`.

## Background

The registry configuration in `cluster-aws` was changed (see [commit](https://github.com/giantswarm/cluster-aws/commit/8df9dcc29924bf67833ed74400b921cad2e2be52)).

The clusters were recreated last week with only `docker.io` configured and we dropped the Azure mirror.

**Comment by fiunchinho** [comment]
I'd move the container registry credentials from `userConfig.secret` to `extraConfigs` in the `App` CR when doing this change.

**Comment by tuladhar** [comment]
### Created PR for thor and thunder:
- https://github.com/giantswarm/management-clusters-fleet/pull/394
- https://github.com/giantswarm/management-clusters-fleet/pull/395

### NOTE
- thor and thunder have different dockerHub access token, and is not using shared giantswarmpull secret

![Image](https://user-images.githubusercontent.com/5674762/221002710-136283e1-d439-4101-8e79-8959673fbd4b.png)

### TODO
- Merge the thor PR and wait for flux to reconcile and rollout nodes.

⚠ MachinePool nodes will likely not get rolled, in this case, we manually perform _ASG - Instance refresh_ from AWS ASG, with 180s of instance warmup time.

If all good, continue with thunder and rest.

**Comment by AndiDog** [comment]
Would this apply to WCs as well?

**Comment by fiunchinho** [comment]
yeah , I think so

**Comment by bdehri** [comment]
All of the clusters were updated.
