### ISSUE TITLE
Fix installation of the default Provider when installing crossplane for the first time

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2056]
From Helm docs 
> pre-install	Executes after templates are rendered, but before any resources are created in Kubernetes

This explains why this check fails when installed: https://github.com/giantswarm/crossplane/blob/2c2e781b29374e106b8e5fb2788d4efd137a7d94/helm/crossplane/templates/provider-install/controller-config-aws.yaml#L1

**Comment by gianfranco-l** [comment]
@piontec @uvegla putting it in "working on" as you agreed

**Comment by piontec** [comment]
done!
