### ISSUE TITLE
SRE Investigation on Crossplane: found mitigation actions

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#2061]
We need to compare crossplane performance between different clusters (actually: api server performance when crossplane is installed with AWS provider). 

Installations we should compare are `gauss` (when 1.11 upgrade is complete) and `potato`

**Comment by piontec** [comment]
@gianfranco-l I changed the title, I think this is what you had in mind.

**Comment by gianfranco-l** [comment]
@piontec could you a little bit of description about this?

**Comment by piontec** [comment]
We need to compare why crossplane performance (actually: api server performance when crossplane is installed with AWS provider). 

Installations we should compare are `gauss` (when 1.11 upgrade is complete) and `potato`

**Comment by nce** [comment]
# :warning: working draft

# Investigative Subjects
I was focusing on the impact crossplane has on our controlplane nodes (_not the sizing of the crossplane installation itself_).

General perceived problem was the slow/sluggishness of the api-server requests (best visualised in grafana -> k8s api performance -> API Server Request Duration)

# Summary Findings

# Details
All installations are running `v1.24.10` and have (among others) the same api-server flags:
```
      --max-requests-inflight=266
      --max-mutating-requests-inflight=133
      --enable-priority-and-fairness=true
```

Timestamps are UTC

## Gauss
### Leadup
On 27th of Feb. the aws-upbound provider in v0.30 (or earlier) was installed at around 12:20 on an already _memory-wise_ struggling controlplane.

Controlplane components:
`10-0-5-111` & `10-0-5-185` &  `10-0-5-9` all running on `m5.xlarge` (4Cpu & 16 GiB)

### Impact on basic resources
CPU and Memory exhaustion on all controlplane nodes:
![image](https://user-images.githubusercontent.com/770135/223972887-f4dd9b3f-b3fe-419f-be5c-5f86737edcce.png)
![image](https://user-images.githubusercontent.com/770135/223973089-a98d69e3-d24b-4eb9-83fe-8f1918f7a556.png)

### Impact on k8s components
```
Unable to contact k8s api-server" error="Get \"https://internal-g8s.gauss.eu-west-1.aws.gigantic.io:443/api/v1/namespaces/kube-system\": EOF" ipAddr="https://internal-g8s.gauss.eu-west-1.aws.gigantic.io:443" subsys=k8s 
```
```
Get "https://172.31.0.1:443/api?timeout=32s": dial tcp 172.31.0.1:443: connect: no route to host`
```
```
cacher.go:425] cacher (*unstructured.Unstructured): unexpected ListAndWatch error: failed to list infrastructure.cluster.x-k8s.io/v1beta1, Kind=AWSManagedMachinePool: conversion webhook for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=AWSManagedMachinePool failed: Post "https://capa-webhook-service.giantswarm.svc:443/convert?timeout=30s": dial tcp 172.31.251.1:443: connect: connection refused; reinitializing...
```
```
[{"level":"warn","ts":"2023-02-27T13:30:27.959Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0619cc1c0/etcd2.gauss.eu-west-1.aws.gigantic.io:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}](status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:"etcdserver: request timed out"}: etcdserver: request timed out)
```

=> a lot of timeout.go & retry_interceptor.go `timeouts`  & `context_exceeded` & `post_timeout` from 12:25
Failure to access api-server amongst others (api-server -> etcd timeout)
**This cascades to pod-restarts/evictions (some >200) putting more stress on the controlplane**

### Impact on api-server
![image](https://user-images.githubusercontent.com/770135/223977875-ca6906e9-456a-49c8-85f2-9e6d6aeb0ff6.png)

Rate of API requests stayed almost the same; ETCD Actions & write did around double, but only for a short timeframe and not worrysome. 

Overall etcd performance degraded massive:
![image](https://user-images.githubusercontent.com/770135/223979424-9eb2c737-6947-4f49-8f67-14e89c927f76.png)


### Recovery
[Setting the ASG](https://github.com/giantswarm/installations/pull/2120/files) to `m5.2xlarge` (8Cpu & 32GiB) stabilized the cluster again at around 14:40
## potato 

## anaconda

## grizzly

**Comment by nce** [comment]
# Investigation around deleting and blocking CRDs
As we'r impacted by the amount of (unnecessary) crds, we wanted to test the manual deletion of crds and evaluate its impact.
 
```
(gs-grizzly) ~ ❯❯❯ k get crd | wc -l
    1001
(gs-grizzly) ~ ❯❯❯ k get crds | grep upbound | awk '{print $1}' |  wc -l
     873
(gs-grizzly) ~ ❯❯❯ k delete crd $(k get crds | grep upbound | awk '{print $1}' | head -n 500)
  ...
  customresourcedefinition.apiextensions.k8s.io "originaccesscontrols.cloudfront.aws.upbound.io" deleted
(gs-grizzly) ~ ❯❯❯ k get crd | wc -l                                                                                                                                                                                     
     501
```

Apart from massive logging increase of upbound-provider, we noticed nothing unusual on the provider (like cpu/mem spikes):
```
E0315 08:00:42.279958       1 reflector.go:140] k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1beta1.Cluster: failed to list *v1beta1.Cluster: the server could not find the requested resource (g
et clusters.dax.aws.upbound.io)
W0315 08:00:42.315298       1 reflector.go:424] k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1beta1.Analyzer: the server could not find the requested resource (get analyzers.accessanalyzer.aws.u
pbound.io)
E0315 08:00:42.315323       1 reflector.go:140] k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1beta1.Analyzer: failed to list *v1beta1.Analyzer: the server could not find the requested resource
(get analyzers.accessanalyzer.aws.upbound.io)
```

As anticapted, about 20min later the provider added all missing CRDs again (without pod restart).

Memory consumption of the api-server decreased as expected (then increased again):
![image](https://user-images.githubusercontent.com/770135/225345280-39aaf967-5fd4-4b31-90e1-327ab75c123d.png)
Although no real impact (besides a short spike) in cpu
```
9:51 am CRDs: 1001
system.slice/containerd.service/kubepods-burstable-poddbd36bd9805a5837721c23d7bc568b50.slice:cri-containerd:92c0ded4283ac455e3169362db95f16be262eb68f33a78753eaccd138cd96888      18  357.2     9.6G

10:00am CRDs: 501
system.slice/containerd.service/kubepods-burstable-poddbd36bd9805a5837721c23d7bc568b50.slice:cri-containerd:92c0ded4283ac455e3169362db95f16be262eb68f33a78753eaccd138cd96888      18    7.7     7.7G        -        -

10:14am CRDs: 1001
system.slice/containerd.service/kubepods-burstable-poddbd36bd9805a5837721c23d7bc568b50.slice:cri-containerd:92c0ded4283ac455e3169362db95f16be262eb68f33a78753eaccd138cd96888      18    8.1     8.8G        -        -

```

On a side note, this was observed as well:
![image](https://user-images.githubusercontent.com/770135/225345572-df7442c1-fd6f-4c89-8032-15de6d616692.png)


# Decision
As interesting as this was, we decided not to move forward with this
* unsure if our current state of `kyverno` is up to the task
* very hacky solution
* we decided to wait for upstream tackling this problem (see above post)

**Comment by negz** [comment]
I noticed you're mostly testing with old-ish versions of Kubernetes. If you can, it does help to run Kubernetes v1.26. Each recent API server release has had a few small fixes to improve resource utilization in the face of many CRDs. This won't be enough to provide a good experience (we still need to reduce the number of CRDs Crossplane installs), but it should at least shave a bit of CPU and memory usage (I want to say at least a GB) from what you're seeing.
