### ISSUE TITLE
Improve capvcd manager logs

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2062]
capvcd manager prints everything to logs. We should improve it.

**Comment by gawertm** [comment]
check if there are log levels, set them appropriate or introduce them if not existing

**Comment by vxav** [comment]
What is this issue? How would we improve logging? Upstream PR?

**Comment by gawertm** [comment]
⬆️cc @erkanerol @jkremser

**Comment by erkanerol** [comment]
The logs are not readable easily. It prints almost everything while provisioning machines. There is no proper log levels. 

The change will be in upstream side at first. We can add this into next CAPVCD meeting topics.

**Comment by vxav** [comment]
I don't think we'll have the bandwidth for this and we can live with the logs in the current state.
