### ISSUE TITLE
Evaluate upstream e2e framework

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2067]
Evaluate https://github.com/kubernetes-sigs/e2e-framework and see if it might be useful for our e2e test framework.

**Comment by AverageMarcus** [comment]
My thoughts on the upstream e2e-framework project:

➕ It's quite easy to create custom functions that plug in to the .Setup() and .Finish() functions
➕ Super easy to get it working with a kubeconfig. It automatically sets up all clients and stuff for you and makes them available when needed.
➕ The "features" doe allow for easily coupling setup functionality with assertion functionality
➕ It has a few nice helper functions that I can see expanding in the future to be really useful. A lot of these are in the klient package which could be used in our own framework if we go that route
➕ Parallel tests work. There's a .TestInParallel function you can use to control what tests can be run in parallel too
➖ It doesn't fit in with Ginkgo tests so would require learning a new pattern for writing tests
➖ Having the concept of "features" that are nested into individual test functions is odd to me
➖ Very young project. I couldn't find any real discussion going on anywhere
➖ None of the upstream projects we work with are using it (only notable project I could find using it in any way were Hashicorp Consul and kube-green)

Overall, I'm not convinced it's the right fit for us, at least not at this point. The different approach to testing, the lack of adoption in upstream projects and the fact that it's still in the early days of the project make me think this wont be well adopted within Giant Swarm and would just cause friction for teams writing tests.

There's a few concepts, and even sub-packages, that could be useful and should be assessed when building out our own solution.
