### ISSUE TITLE
Improved Engagement with Prospects

### ISSUE THREAD

**Issue by muemich** [giantswarm/roadmap#2071]
**Goal**: 
- [x] Define workshops and professional services packages that we can offer to prospects to improve early engagement and use the momentum, building trust which hopefully leads to a new subscription customer. 
- [x] Win 3 prospects for the first workshop and/or professional service package such as BMW, MBTI, HDI Global, Continental Edge, (?)

**Situation**: We often run into prospects that are 
a/ not yet ready and/or lack trust to immediately buy a subscription or 
b/ where we lack something to fulfill their requirements (e.g. AKS, EKS support). 

While every situation is unique, we can cluster them into two stages:
1/ Room 1: "Greenfield" - planning/starting to build their first platform 
2/ Room 2: "Brownfield" - reviewing their current platform version, planning to scale 

**Problem**: Right now we don't have anything defined that we can offer prospects in these scenarios to use the momentum, get to know them better, understand their pain points, build trust, and influence them to convert into a subscription customer. 

**Opportunity**
We get into more conversations where we get actively asked if we do consulting and offer professional services. 

Competitors like d2iq and Kubermatic have defined a broad set of professional services and training packages to engage with prospects. see [Kubermatic](https://www.kubermatic.com/services/accelerators/), [d2iq](https://d2iq.com/services-and-support#training). 

Now it's time to think about how we can bring the Giant Swarm flavor to professional services and delight customers early on and convert them later into subscription customers. 

Created a Google Doc with the notes from the "kick-off" session: https://docs.google.com/document/d/1Kgwj08YVUNmCVLQeT44IbBZFP_scD-rh-qJzfmmYao4/edit

**Comment by muemich** [comment]
1st session is scheduled on Fr 3rd of March

**Comment by brinker211** [comment]
Michael since this is scheduled already I will put into in progress. Is there something or thoughts that we can prepare beforehand? This probably goes along with our "productive noise" story but we can sync next meet and decide.

**Comment by muemich** [comment]
We should definitely sync on this, but IMHO it has little to do with productive noise. It is more about what can we do/offer customers that aren't yet ready to a) get paid b) be there

**Comment by henninglange** [comment]
@teemow @othylmann @muemich Friday we had a kick-off session, see notes in the description above plus the google doc.

**Comment by brinker211** [comment]
@muemich are there some items we can act on here? Or plans? I will put into backlog for now but feel free to update the accurate status.

**Comment by muemich** [comment]
The first step has been taken to offer an assessment workshop, which allows us to get in earlier, even before they are technically ready,  and then to dive into all the things of the customer. The next thing could be to offer a package to make them ready, or to help customer with professional services to move them towards a ready/mature state

**Comment by muemich** [comment]
Created a strategy workshop and it is as template in Miro. It is intended to support customers with their strategy and move to exectution.

**Comment by muemich** [comment]
All material is now a template and can be re-used

**Comment by henninglange** [comment]
@muemich I like to reopen this issue. I'd like to have sales-ready materials, being it
- a template that we can share, please link here the templates you've created
- a page on our website we can link people to
- possibly a handout as we did for the cloud-native capability assessment

I am happy to discuss this in our next revenue growth meeting after your holidays.

**Comment by muemich** [comment]
Here is the link: https://miro.com/app/board/uXjVM_KZGus=/ to the Platform Strategy Workshop

**Comment by muemich** [comment]
WIP doc for the Description of the above workshop to create a service offering:
https://docs.google.com/document/d/1JYRrveTSU8uVqx3mVNGFD3GvYWy5A_5o7aZg641ix2A/edit?usp=sharing

**Comment by brinker211** [comment]
@muemich I think we are good to close this with the new processes established and first workshops happened. Do you agree?

**Comment by henninglange** [comment]
@muemich thanks. @filipenko4791 do you think that doc from Michael is enough to create a handout/flyer as well as a landing page for lead gen, etc. for the platform engineering strategy workshop as we did for the assessment workshop?

if so then please create a ticket and add to your backlog. website refresh first. 

@filipenko4791 I'd love to have one central point and overview of our offering with all the connected docs, flyers, etc. I've created in Drive under profits / sales / documents / offering a potential folder structure with workshops, trainings, fleet management, developer platform,  - would be great if you can start putting things here together. then we will also see what's still missing. I'd say it makes sense to change the folder name form 01 documents to 01 Our offering, and change the folder structure to workshop, tranings, etc. and put the präsentation / flyers / etc. in each of these folders.

**Comment by teemow** [comment]
@othylmann can this be closed?
