### ISSUE TITLE
capa-iam-operator pods fail to be admitted

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2073]
Found during https://github.com/giantswarm/roadmap/issues/2023. Version 0.5.1 works, so it's likely the seccomp change in 0.6.0. Compare to https://github.com/giantswarm/aws-vpc-operator/pull/38 for the likely fix.

**Comment by AndiDog** [comment]
We should finish https://github.com/giantswarm/capa-iam-operator/pull/157 and then add latest changes to https://github.com/giantswarm/capa-iam-operator/pull/156 before releasing.

**Comment by alex-dabija** [comment]
We need to wait until we confirm that the cert-manger role changes work.

**Comment by AndiDog** [comment]
Pod admission works, so closing this. https://github.com/giantswarm/roadmap/issues/1981 is a separate topic to test.
