### ISSUE TITLE
Store Tekton task logs for prolonged period

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2079]
Acceptance criteria:

- [ ] Logs from Tekton tasks are stored somewhere for an extended period (a week for example)
- [ ] One possible solution we discussed was Loki - check current status with Atlas and security implications with Shield

**Comment by ericgraf** [comment]
Sig-security thread
https://gigantic.slack.com/archives/C3S23JE75/p1677687986166309
Team-atlas thread: 
https://gigantic.slack.com/archives/C01176DKNP4/p1677777529259079

**Comment by ericgraf** [comment]
Promtail ( a possible client side component of loki ) has the concept of a pipeline. It may be possible to add a list of regex that could remove/obfuscate passwords from logs.

**Comment by ericgraf** [comment]
Explore entrypoint binary redacting secrets from logs github.com /tektoncd/pipeline/issues/3373

**Comment by ericgraf** [comment]
For presenting the data we would need 2fa infront of grafana. This brings up a question of what the correct 2fa should be to achieve this. I raise this issue to track that. 
https://github.com/giantswarm/giantswarm/issues/26166

**Comment by ericgraf** [comment]
Grafana + Loki is now accessible and can be found at the link: https://grafana.ei9o7.k8s.gorilla.eu-central-1.aws.gigantic.io/
 The login credentials can be found in lastpass until  https://github.com/giantswarm/giantswarm/issues/26166 is solved.

**Comment by yulianedyalkova** [comment]
Reopening as it seems we're currently not getting all the required logs in Loki

**Comment by yulianedyalkova** [comment]
Potentially fixed by https://github.com/giantswarm/workload-clusters-fleet/pull/391/files, please validate if we get the logs from all namespace that are relevant to us.
