### ISSUE TITLE
On Prem Storage Solution

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#208]
## User Story

- As an on-premises (KVM) customer, I would like to have an on-premises storage provider  so that i can use volumes to have persistence in my Tenant Clusters
- As a Giant Swarm KVM PE|SE|SRE I would like to have an on-premises storage provider so that I can use Persistent Volumes in KVM control plane clusters.
## Acceptance Criteria

- We can use Persistent Volumes on KVM Control Planes
- We can use Persistent Volumes on KVM Tenant Clusters
- We have a documented the reliability of our solutions to manage customer expectations.

## Tasks
- [ ] evaluate possible on-premises storage solutions

**Comment by brinker211** [comment]
@cornelius-keller to work on / look into during hackathon this week.

**Comment by cornelius-keller** [comment]
Result of the ceph research:
it is possible for us to run ceph via rook on the cp and provide storage to tc
Requirements for that are proper network policies and different pod and service network on CP and TC.

**Comment by cornelius-keller** [comment]
Questions for planning
- Do we need ceph / blockstorage  for panamax or are they happy with the nfs shares that they have now?
What would be the way to introduce this, can we have a pilot  alpha for that with limited SLA, maybe on their dev cluster to both learn what it can do and manage expectations? @jgsqware 
- How would we operationalize this, who can do on call, how do we spread knowledge?
- What would we need to do to own this technology as a team ?

**Comment by Oshratn** [comment]
@cornelius-keller I have a feeling that this is done. If this is the case, can the issue be closed?

**Comment by cornelius-keller** [comment]
yes, it's done. Closing
