### ISSUE TITLE
Grant metrics and logs access to customers

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2082]
## User Story

* As a customer I want to be able to access metrics stored in Prometheus via Grafana Explore feature
* As a customer I want to be able to access logs stored in Loki via Grafana Explore feature

**Comment by TheoBrigitte** [comment]
This should be doable via the `viewers_can_edit` setting, see https://grafana.com/docs/grafana/latest/administration/user-management/manage-dashboard-permissions/#enable-viewers-to-edit-but-not-save-dashboards-and-use-explore

**Comment by hervenicol** [comment]
Would be nice for metrics as well, as some customers would probably like to explore metrics too.

**Comment by TheoBrigitte** [comment]
I think this feature would enable access for both metrics and logs.

**Comment by hervenicol** [comment]
Testing current behaviour on `gauss`:
- logging as "customer" on grafana
![Image](https://user-images.githubusercontent.com/12008875/223497474-fdf6181c-9c23-47a6-ab82-6aec08c32500.png)

- I don't see private dashboards
![Image](https://user-images.githubusercontent.com/12008875/223497610-ce1db276-a644-47cf-a8d7-65314e658906.png)

- I have no "explore" feature.
![Image](https://user-images.githubusercontent.com/12008875/223497728-f43c5f80-2784-4e02-bd31-029f39103ab4.png)

That's all expected. Now let's try changing this!

**Comment by hervenicol** [comment]
done ✅
