### ISSUE TITLE
MC `thor` has config maps with old base domain

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2084]
## Issue

MC `thor` has config maps with old base domain.

This leads to invalid SAN in the API server certificate for workload clusters. We should replace the occurrences. If this issue is a result from restoring a backup, we should update our procedure for **re**-creating an MC.

**Comment by fiunchinho** [comment]
Set the right base domain in the following configmaps

- giantswarm/cluster-catalog
- giantswarm/cluster-test-catalog
- giantswarm/default-catalog
- giantswarm/default-test-catalog
- giantswarm/giantswarm-catalog
- giantswarm/giantswarm-test-catalog
