### ISSUE TITLE
Implement ETCD auto-compaction

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2089]
With etcd 3.x there is an automatic-compaction feature available hence the cronjob for the compaction would not be needed anymore.

With etcd 3.3 there is a new feature as well to specify the revision number to be kept in the DB which could help with the size of ETCD DB.

Reference: https://etcd.io/docs/v3.5/op-guide/maintenance/#auto-compaction

**Comment by T-Kukawka** [comment]
Auto-compaction has to be enabled in the ETCD. It is advised to run also defragmentation after each compaction. We have to be careful here as the defragmentation is blocking read/writes hence the 'downtime' on etcd service. 

We have to check the needed frequency for compaction/defragmentation as well as the number of revisions on the ETCD.

Next steps is to check the data for heaviest cluster (deu01)

**Comment by T-Kukawka** [comment]
Internal steps: https://github.com/giantswarm/giantswarm/issues/26218

**Comment by njuettner** [comment]
With AWS release v18.3.0, we do now integrate etcd compaction and allow quota backend adjustment by default, https://github.com/giantswarm/k8scloudconfig/pull/1116.

Closing this issue for now.
