### ISSUE TITLE
Enable `devctl` to add cluster app specific Makefiles and GitHub actions

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2093]
To efficiently work with JSON schema for `values.schema.json` we provide different tooling.

Currently the integration is already done in `cluster-azure` and includes a GitHub action and a Makefile:
- `.github/workflows/json_schema.yaml` ([here](https://github.com/giantswarm/cluster-azure/blob/main/.github/workflows/json_schema.yaml))
- `cluster-azure/Makefile.schema.mk` ([here](https://github.com/giantswarm/cluster-azure/blob/main/Makefile.schema.mk))

In order to roll that out to other cluster-app repositories we need to manage in somewhere centrally. 
Gerald from Cabbage also offered his help.

**Comment by marians** [comment]
A UX thought: The make targets currently are

- schema-normalize
- schema-validate
- values-generate

Since the noun-verb ordering is slightly counter-intuitive, how about adding targets (aliases so to say) with this order?

- normalize-schema
- validate-schema
- generate-values

**Comment by mogottsch** [comment]
The issue is done, but the resulting "Align files PR" is not yet merged in cluster-aws. Let's keep it in PDV.
