### ISSUE TITLE
Support peering on cloud providers

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#21]
V and AA are peering VPCs with our clusters. Our automation doesn't have awareness of this configuration. This can lead to trouble during upgrades and we should support this out of the box.

From Puja in Slack:

1. peering between 2 GS owned VPCs (i.e. two workload clusters)
2. peering between workload cluster VPC and other VPC in same  account (e.g. China MongoDB runs on VMs in own VPC in same account AFAIK)
3. peering between workload cluster VPC and other VPC in different account
Then there’s bi-directional vs 1-directional peering

**Comment by T-Kukawka** [comment]
in CAPA we have transing gateway so this can be achieved here and we think it is the best way. closing.
