### ISSUE TITLE
announcment - Managed apps upgrade - March 2023

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#2100]
Apps:

- flux-app
- crossaplane-app
- eso-app

## TODO

- [x] upgrade
- [x] rollout

**Comment by gianfranco-l** [comment]
@nce shall we move this to "working on"?

**Comment by nce** [comment]
# Flux
Tested `v0.23.0` on giraffe
* img were pulled (flux-giantswarm)
* all pods ready
* crds are updated/installed
* custom kustomize-controller looks fine
* no apparent errors in `kustomizations/gitrepos`

Rollout is managed here: https://github.com/giantswarm/management-clusters-fleet/pull/564

# ESO
Tests  `v0.5.0` on `giraffe` always timed out bc/ images are pulled from `docker.io`

# Crossplane
Release is currently pending (changes are brought to `master`).

**Comment by nce** [comment]
Crossplane will be handled elsewhere: https://github.com/giantswarm/roadmap/issues/2479

ESO is rolled out (with no issues)
Flux is rolled out as well (with a few issues (Reconiliation is flunky))

**Comment by mproffitt** [comment]
Announcement added to weekly highlights PR https://github.com/giantswarm/docs/pull/1814
