### ISSUE TITLE
Merge aws-resolver-rules-operator & dns-aws-operator

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2112]
- Check if we want to use a command line argument or the annotation `aws.giantswarm.io/resolver-rules-owner-account` (which is currently used in cluster-aws and aws-resolver-rules-operator), and remove one of them

**Comment by mnitchev** [comment]
Done in https://github.com/giantswarm/aws-resolver-rules-operator/releases/tag/v0.7.0
