### ISSUE TITLE
Integrate CAPVCD mc-bootstrap tests into current infrastructure

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2118]
We have a working version of mc-bootstrap automated tests for CAPVCD so let's get them integrated into our shiny new testing platform.

**Comment by ericgraf** [comment]
PRs related to this:
https://github.com/giantswarm/mc-bootstrap/pull/454
https://github.com/giantswarm/mc-bootstrap/pull/350
https://github.com/giantswarm/cicd-gitops/pull/25
