### ISSUE TITLE
Local image cache for customer workloads

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#212]
**Is your feature request related to a problem? Please describe.**

Starting within a few weeks, Dockerhub will enforce limiting on pull quotas. This request is to address customer workloads if this limit is hit. 

**Describe the solution you'd like**

A proxy or cache that would be able to keep configurable list of critical customer images that could be used in case dockerhub was limited. 

**Describe alternatives you've considered**

Mirrored registries however this will interfere with giantswarm's mirrored registry solution. 

**Additional context**

**Comment by brinker211** [comment]
Initially I thought docker's local pull-thru cache would be a good solution but while testing realized that even when pulling from the cache it still needs dockerhub to query content integrity. 

I will need to see if the dockerhub limiting only affects pulling. If that is the case and the pull-thru cache can still query then the solution might work. Really its a matter of docker limiting all requests or just pulls. 

The other solution I am investigating is kube-fledged which can be controlled by app CRs and does not hit the problem of scaling because giantswarm already has mirrored images. In other words, the kubelet can come up so kube-fledged operator should be able to get the customer workload images on the new nodes. 

Will follow up with results of both.

**Comment by puja108** [comment]
Ben, maybe you wanna have a chat with @JosephSalisbury and @snizhana-dynnyk about their research on this issue for our own images.

**Comment by JosephSalisbury** [comment]
I would go towards kube-fledged. Having to modify docker configuration for customer registries sounds pretty heavyweight

**Comment by puja108** [comment]
@brinker211 @JosephSalisbury do we still need this issue as a feature request or can we close it?

**Comment by brinker211** [comment]
I will close for now and focus on evaluation of kube-fledged and re-raise if it ends up looking like implementation is next step. Will link when new issue created.
