### ISSUE TITLE
Honeybadger repos: Core Components/Managed Applications need to have default seccompprofile set

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#2120]
original ticket request by @Strigix :

As part of the roadmap issue https://github.com/giantswarm/roadmap/issues/259
Managed applications and core components need to have a default seccomp profile set.

Some repositories have already gotten the required changes. For team Honeybadger the ones we'd like you ask you to do are: 

- flux
- hello-world

Generally speaking step by step you'll need to at at least:

1. Set seccompprofile on RuntimeDefault in container and pod security context
2. Allow the use of said profiles in the PSP
3. Allow the use of the proper volumes in the PSP (Otherwise pods will have trouble running see: https://github.com/giantswarm/roadmap/issues/259#issuecomment-1436729770)

NOTE: depending on the repository and nature of the component/application, this will differ.

Here's an example for step 1 and 2: 
https://github.com/giantswarm/node-operator/pull/308/commits/d0c8f187b105ca1ccf019453466ea2e869afc032

Here's an example for step 3: 
https://github.com/giantswarm/dns-operator-route53/pull/92/commits/e7513932827c933964b2b778063279abafa6ede6

NOTE: These are the volumes allowed by the restricted PSP as an example, your applications might not need them all, or needs others. We've seen most issues with the volumes Secrets, Projected, and ConfigMap.

**Comment by uvegla** [comment]
`flux-app` should be released by: https://github.com/giantswarm/flux-app/pull/192/

**Comment by piontec** [comment]
Done, closing
