### ISSUE TITLE
Configure instance metadata in AWS instances to use only v2

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#213]
**Is your feature request related to a problem? Please describe.**

As part of the [AWS Foundational Security Best Practices](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ec2-8-remediation) there is a point to enforce the use of IMDSv2 in the EC2 instances. The IMDS provides access to temporary, frequently rotated credentials, to access the AWS metadata endpoint. The new version adds new protections to different types of vulnerabilities. 

```
The control passes if HttpTokens is set to required for IMDSv2. The control fails if HttpTokens is set to optional.
```

**Describe the solution you'd like**

Enable in Cloud Formation the enforcement to use IMDSv2 using `HttpsTokens` equals to `required` in the [launch templates](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html) of our instances. Verify it does no affect any systemd unit or other process that makes use of the AWS metadata endpoint.

**Describe alternatives you've considered**

Keep using IMDSv1 and accept the vulnerabilities exposure. 

**Additional context**

**Comment by paurosello** [comment]
After doin the change I have found a problem in ignition file:

```
[  316.912887] ignition[1800]: Ignition v0.34.0-22-g032f620
[  316.913863] ignition[1800]: Stage: disks
[  316.914575] ignition[1800]: reading system config file "/usr/lib/ignition/base.ign"
[  316.915849] ignition[1800]: no config URL provided
[  316.928645] ignition[1800]: reading system config file "/usr/lib/ignition/user.ign"
[  316.929886] ignition[1800]: no config at "/usr/lib/ignition/user.ign"
[  316.930905] ignition[1800]: GET http://169.254.169.254/2009-04-04/user-data: attempt #1
[  316.949084] ignition[1800]: GET error: Get http://169.254.169.254/2009-04-04/user-data: dial tcp 169.254.169.254:80: connect: network is unreachable
```

**Comment by paurosello** [comment]
Branch left in here https://github.com/giantswarm/aws-operator/tree/aws-api-v2

Pending on Flatcar upgrading ignition

**Comment by pipo02mix** [comment]
For visibility, there is an (upstream issue](https://github.com/flatcar-linux/Flatcar/issues/220) and confirmation by Kinvollk that they are working on it

**Comment by pipo02mix** [comment]
Is this already implemented?

**Comment by paurosello** [comment]
Done in aws-operator to enable this, still missing the upgrade of Ignition

**Comment by yasn77** [comment]
@paurosello @alex-dabija Will this be hitting a release? or is it already in a release?

**Comment by paurosello** [comment]
Not really usable until it ignition supports it, need to check the status here

**Comment by yasn77** [comment]
ANy updatres @paurosello

**Comment by paurosello** [comment]
This is still not supported as of release 2765.2.6 of Flatcar, will try to raise the upstream ticket again to see if there is any plan.
