### ISSUE TITLE
Cilium v1.13 with Hubble UI and Monitoring

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2131]
With latest Cilium v1.13 release to be included in v19 AWS as well as on all MCs we are going to enable Hubble UI and the monitoring of cilium agent themselves.

Next steps:
- [x] test on VIngate
- [x] test on CAPA clusters
- [x] test and rollout to MCs

**Comment by T-Kukawka** [comment]
rolling out to MCs as well

**Comment by whites11** [comment]
running on gaia and gremlin

**Comment by whites11** [comment]
done for vintage

**Comment by alex-dabija** [comment]
@T-Kukawka Do you know what is needed to test? We've been using the latest version of the `cilium-app` in CAPA for a few weeks (https://github.com/giantswarm/default-apps-aws/blob/34e0aece4070c310bac85f020d0b4a163e5869d6/helm/default-apps-aws/values.yaml#L132).

**Comment by fiunchinho** [comment]
Tested on a new CAPA workload cluster. It seems to work

![image](https://user-images.githubusercontent.com/627038/234243636-16365279-a0b9-4f06-aaac-08f649aa909c.png)

@T-Kukawka is there anything else we should check or can we close this one?

**Comment by T-Kukawka** [comment]
all good then 👍
