### ISSUE TITLE
Test a CAPI v1.4.0 release

### ISSUE THREAD

**Issue by mnitchev** [giantswarm/roadmap#2134]
## Task

Test a CAPI v1.4.0 release.

Second beta is already out https://kubernetes.slack.com/archives/C8TSNPY4T/p1678214604307509. We better test in advance and report problems before it becomes stable.

**Comment by bdehri** [comment]
v1.4.0 was deployed to Golem. We plan to observe it for a week before releasing a new cluster-api-app.

**Comment by bdehri** [comment]
Released with v1.11.0
