### ISSUE TITLE
Replace deprecated `node-role.kubernetes.io/master` taint

### ISSUE THREAD

**Issue by mnitchev** [giantswarm/roadmap#2135]
It will be removed in 1.25 ([source](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/)). We have to migrate in order to keep our apps running on control plane nodes, as desired.

Check which version of Kubernetes supports the new taint.

**Comment by fiunchinho** [comment]
We could [do this in our helm templates](https://github.com/giantswarm/chart-operator/blob/fdf61fe5aa3ecdd1f9cc326a255bcd936427dc7d/helm/chart-operator/templates/deployment.yaml#L50-L56).

**Comment by fiunchinho** [comment]
I found these files in repositories that we own 
- [cert-manager](https://github.com/giantswarm/cert-manager-app/blob/1b995e85933d85ff739ff9841d71c1c875986aea/helm/cert-manager-app/templates/controller-deployment.yaml#L33-L34)
- [cluster-api-provider-aws-app](https://github.com/giantswarm/cluster-api-provider-aws-app/blob/7b94374642181f0ad10cdd27a5d19a4b95a47bd3/helm/cluster-api-provider-aws/templates/crd-install/crd-job.yaml#L26-L27)
- [cluster-api-app](https://github.com/giantswarm/cluster-api-app/blob/531581f802536280dc65dcb5b36b1e0e8225e819/helm/cluster-api/templates/crd-install/crd-job.yaml#L27)

**Comment by fiunchinho** [comment]
The taint was deprecated on 1.24
- https://kubernetes.io/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/#api-removals-deprecations-and-other-changes-for-kubernetes-1-24
- https://github.com/kubernetes/kubernetes/pull/107533
