### ISSUE TITLE
Expose more fields via CP API

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#214]
**Is your feature request related to a problem? Please describe.**

Customer's automation can be improved by exposing more fields from CP API. Currently TGW attachments to GS cluster/VPC are manual once the cluster is created.

**Describe the solution you'd like**

Example of this is that subnet information and more VPC networking fields would be able to automate TGW attachments and reduce toil. 

**Describe alternatives you've considered**

Currently this can be worked around by pulling certain values after cluster creation but would be better to do all in one.

**Additional context**

More specific examples to come shortly.

**Comment by puja108** [comment]
Is this about having more info in status fields or actual have it in spec fields to be able to set them on cluster creation?

Also, this sounds like you're talking about AWS (or at least a cloud setting) here, right? Once you get to add more context, also remember adding some labels and maybe already a team in case it is clear.

**Comment by puja108** [comment]
@snizhana-dynnyk will add the internal issue that's we have for this.

**Comment by teemow** [comment]
@alex-dabija @T-Kukawka this an old issue still labeled with firecracker? To phoenix or close?

**Comment by alex-dabija** [comment]
Old issue, it applies to Vintage. Closing for now.
