### ISSUE TITLE
Document how to create a WC on `thor` and `thunder`

### ISSUE THREAD

**Issue by QuantumEnigmaa** [giantswarm/roadmap#2141]
## Task

Document how to create a WC on `thor` and `thunder`.

[Public documentation ](https://docs.giantswarm.io/use-the-api/kubectl-gs/template-cluster/) exist for CAPA clusters but since thor and thunder have specific configurations, it would help a lot to have documentation for those 2.

**Comment by calvix** [comment]
maybe we should  follow the structure with examples like here
https://github.com/giantswarm/cluster-cloud-director/tree/main/examples/cluster-default

**Comment by AndiDog** [comment]
I tried the latest instructions and the first control plane node got stuck in cloud-init with `429 Too Many Requests` error for pulling critical kubelet images from Docker registry. This is fatal at that point. We should document how to set registry credentials (or automatically use the MC's credentials?).

**Comment by bdehri** [comment]
I can add example secret config to the current manifests.
