### ISSUE TITLE
mc-bootstrap adaptions for CAPV

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2152]
this task is to adapt mc-bootstrap to create Management Clusters for Vsphere

**Comment by erkanerol** [comment]
This PR is enough to create a CAPV MC https://github.com/giantswarm/mc-bootstrap/pull/453

**Comment by erkanerol** [comment]
I merged the PR. We are able to create a CAPV MC now. If we need to implement other additional features, we can track separately.
