### ISSUE TITLE
Document our Grafana Cloud usage

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#2159]
We should document that we push some metrics to grafana cloud, which ones and why.

**Comment by QuentinBisson** [comment]
cc @TheoBrigitte as you might want to track this

**Comment by TheoBrigitte** [comment]
The source of truth for metrics we push to grafana cloud is here https://github.com/giantswarm/prometheus-rules/blob/master/helm/prometheus-rules/templates/recording-rules/cortex.rules.yml

We need to turn this into a documentation page.

**Comment by Rotfuks** [comment]
Out of scope for now.
