### ISSUE TITLE
CAPA - machines on public cluster can be put into public subnets

### ISSUE THREAD

**Issue by bdehri** [giantswarm/roadmap#2169]
I saw that for example on grizzly both CP and worker nodes are placed in public subnets and have public IPs

also saw one machine in anzu -

**Comment by calvix** [comment]
I think this needs to be fixed generally in cluster-aws or capa controller and not manually adding filters to every possible cluster there is, this will get painful with customers

**Comment by bdehri** [comment]
Released with cluster-aws `v0.29.0`
