### ISSUE TITLE
Mention in RFC that defaults should not be empty

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#2179]

**Comment by mogottsch** [comment]
The title suggests that the requirement is a SHOULD. Is there any reason not to make this a MUST? @marians 
I'm thinking of something like this:
"If a property specifies a default via the `default` keyword, then the default MUST not be an empty value (`""`).

Also, have we already talked about what we mean by "empty value"? Anything other than `""`?

**Comment by marians** [comment]
We can also try MUST.

The definition of empty differs by type.

- Boolean: `false`
- String: `""`
- Integer: `0`
- Number: `0` or everthing that's equal (`0.0`).
- Array: `[]`
- Object: `{}`

**Comment by mogottsch** [comment]
Done with:
https://github.com/giantswarm/rfc/pull/55/commits/d345df7fe535f059519fdb3ccc85b8fbabf6c3f9
https://github.com/giantswarm/rfc/pull/55/commits/3ee3e0b2ff1fdfa975233e1f7e13e5274df224ae
