### ISSUE TITLE
Allow possibility to create CiliumNetworkPolicy prior to v19 release

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2180]
We have to figure out a way how customers as well as our Managed Aps can bring CiliumNetworkPolicy CRD and CRs prior to v19 upgrade.
This is a must due to the Cilium not handling the IP Block space for the definition of egress traffic, hence need for the CiliumNetworkPolicy that covers it. 

For smooth upgrade, both on customer workload side and managed apps side we need to allow this to be applied before the Cilium release.

**Comment by njuettner** [comment]
I added a new repo https://github.com/giantswarm/cilium-prerequisites which applies 
`ciliumclusterwidenetworkpolicies.cilium.io` and `ciliumnetworkpolicies.cilium.io` via `kubectl apply` as a Job.

There's is a script `hack/sync.sh` which can be used `VERSION=$RELEASE_TAG ./sync.sh` to get the latest Cilium CRD's, you'd only need to bump the app version.

This app is now available in the **`default`** and **`giantswarm`** catalog

Removing the app again won't remove the Cilium CRD's, they will be kept in the cluster.
