### ISSUE TITLE
Monitor Loki usage

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2182]
## User story

* As a customer I want to avoid unexpected cost increase for logging

We [agreed](https://github.com/giantswarm/giantswarm/issues/26035) to run a "trial" for customer, meaning Loki would be installed for a given period of time. During this period we need to get data to determine what is the cost for customers.

So far we estimated cost by hand (https://github.com/giantswarm/giantswarm/issues/24118), but this is not suitable for the trial we want to run.

Let's build a solution which enables us to determine what is the cost of running Loki on each MC. This should ideally be available to both GiantSwarm employees and customers.

We need the following informations:

- Object storage usage
- Resources usage in terms of cpu and memory 
- Network traffic

Bonus: having a global view per customer

**Comment by marieroque** [comment]
Idea of graph to estimate data stored in S3:


![Image](https://user-images.githubusercontent.com/9134338/229126525-08bcf2a9-4d36-43da-b14f-f6b1fde7205a.png)

The blue line `chunk stored` is equivalent to the data stored on S3:


![Image](https://user-images.githubusercontent.com/9134338/229126688-8cf0c47f-c340-4fd4-8975-89dc61fc5feb.png)

**Comment by marieroque** [comment]
Source of interesting metrics to scrape:
https://grafana.com/docs/loki/latest/operations/observability/
https://docs.kubecost.com/architecture/user-metrics

**Comment by marieroque** [comment]
Experimentation by `medium`
https://medium.com/@ronen.schaffer/yes-you-can-use-loki-to-efficiently-retrieve-big-data-for-analysis-80058a922624

**Comment by marieroque** [comment]
<i>Good to know: </i>
The network graph computes the bandwidth for all traffic received by loki-gateway.
But the traffic between promtail on MC and loki is not a real cost, actually it costs 0$.
We can't rely on the cluster_id label because it's always the MC id, as the loki pods are running on the MC.

**Comment by marieroque** [comment]
Dashboard overview 


![Image](https://user-images.githubusercontent.com/9134338/230595297-46861767-ab8d-4c37-a25d-f3b689ca72de.png)

**Comment by marieroque** [comment]
How estimate Loki cost:

- CPU request and Memory request give us values to determine which type of VM we need to buy
- Network bandwidth computed on a month give us the number of bytes received per month and we can estimate the cost of the network for logs transmission
- Total of bytes stored on S3 computed on a month allows us to estimate the cost of S3 storage for Loki

**Comment by marieroque** [comment]
Variable `tenant` added to the dashboard, thus we can estimate the storage cost on S3 by tenant (=WC).

**Comment by marieroque** [comment]
Last commit:

move network panel in Data row and show the total in a separate panel.



![Image](https://user-images.githubusercontent.com/9134338/231083489-d460102b-c41b-45e1-b2c8-ec0a7d1c2cca.png)
