### ISSUE TITLE
logging-operator basics

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2183]
## User story

* As a customer I want to be able to disable logging for some clusters.

Similar to the [disable monitoring feature](https://docs.giantswarm.io/getting-started/observability/monitoring/disable/), a customer needs to be able to disable logging for a specific cluster. We experimented how to achieve this as part of [#2054](https://github.com/giantswarm/roadmap/issues/2054).

**Comment by QuentinBisson** [comment]
@I think this is implemented already?
