### ISSUE TITLE
Prometheus resources usage improvement

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2185]
### Goal

How do we improve resources usage for all apps on WC (good to have for MC)

### Problems

- Ingesting more metrics means bigger pressure on Prometheus (already at capacity)

### Ideas/solutions

- Reduce scrape timeout
  - [x] on Prometheus servers (via PMO)
  - [ ] on Prometheus-agent
- Reduce cardinality
  - [x] k8s apiserver SLO metrics
  - [ ] kyverno metrics (dedicated Prometheus)
  - [x] labels uid, id, etc...
  - [x] Send kyverno data to Grafana Cloud
- [x] Find unused metrics
  - Define metrics contract with other teams
  - Find unused metrics (not in rules or dashboards)
- Mimir could be used to ingest metrics from specific targets like kyverno, but we need to evaluate cost and compare this to the current setup.

**Comment by QuentinBisson** [comment]
Mimir is the way
