### ISSUE TITLE
Rollout ESO to all MCs

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#2186]

**Comment by mproffitt** [comment]
Split rollout into batches

- batch 1: https://github.com/giantswarm/management-clusters-fleet/pull/466
- batch 2: https://github.com/giantswarm/management-clusters-fleet/pull/467
- batch 3: https://github.com/giantswarm/management-clusters-fleet/pull/468
- batch 4: https://github.com/giantswarm/management-clusters-fleet/pull/469

Not rolled to

- thunder - customer request

No customer for:

- halley 
- hyperion
- helios

**Comment by mproffitt** [comment]
First batch rolled

- Rolled back from buffalo - cluster too old
- Not checked bumblebee - no access to cluster. Asking an AE to verify

**Comment by mproffitt** [comment]
AE verified bumblebee - all looks good.

## Batch 2 - issues

gaia - flux seems stuck, will come back to this
goat - certs expired, no access - will check again shortly
gohan flux suspended - asked for reason
golem - stuck creating - recieving `invalid certs` error in webhook

**Comment by mproffitt** [comment]
golem - resolved. May have been impacted by changes being made by hydra upgrades

**Comment by mproffitt** [comment]
gaia - flux was stuck on this cluster and seemingly had been for some time.

It seemed there may have been too low resources assigned to the kustomize deploy although this needs verifying with the team. 

Last night I changed requests from 100m cores and 64mi ram to 500m and 256mi - when the pod eventually came up, flux was apparantly then working but failing on an outdated rolebinding for the customer flux.

Deleting this rolebinding completely from the cluster allowed it to be recreated and flux is now working on this cluster, and has applied the latest changes including ESO successfully

**Comment by mproffitt** [comment]
Most clusters done.

The following are failing or missing

* buffalo - previously mentioned: cluster too old
* puma - cluster too old

* gorgoth - no access to cluster
* gremlin - flux on harbor operator branch
* gubble - no access to cluster
* gunther - broken flux kustomization - secret has no kind (full encrypted secret)
* guppy - on autobranch

**Comment by mproffitt** [comment]
gunther was missing sops decryption information from flux kustomization.

Added it this morning and now everything is fine on this cluster.
