### ISSUE TITLE
Define an API to manage IPs of LoadBalancers

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2188]
to avoid IP address conflicts between servicetype loadbalancer

**Comment by erkanerol** [comment]
[This PR](https://github.com/giantswarm/cluster-vsphere/pull/47) adds a parameter to set subnet for LoadBalancer services. We will be able to manage CIDR ranges manually. I propose deprioritizing this item for a while and implementing an automated solution after finishing other critical tasks. @gawertm

**Comment by erkanerol** [comment]
The parameter is added. Closing https://github.com/giantswarm/cluster-vsphere/pull/47/files#diff-bb01af83b1bd47474d07984492d2206e5dc6cb461bf210f0c8bcc185d94ae2a0R17
