### ISSUE TITLE
Update default-apps and app-collection for Vsphere

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2189]
- [x] Update vsphere-app-collection
       - https://github.com/giantswarm/vsphere-app-collection/pull/34
- [x] Update default-apps-vsphere
       - https://github.com/giantswarm/default-apps-vsphere/pull/57
       - https://github.com/giantswarm/default-apps-vsphere/pull/60
- [x] Update circleci jobs of apps in collection.
  
   ***Don't Push***
    - [x] kube-state-metrics.yaml
    - [x] metrics-server-app.yaml
    - [x] net-exporter.yaml
    - [x] prometheus-operator-app.yaml (observability-bundle)
    - [x] prometheus-operator-crd.yaml (observability-bundle)
    - [x] config-controller.yaml
    - [x] node-operator.yaml
    - [x] release-operator.yaml
   
   ***Push***
    - [x] cluster-api-monitoring -> https://github.com/giantswarm/cluster-api-monitoring-app/pull/41
    - [x] cluster-api.yaml -> https://github.com/giantswarm/vsphere-app-collection/pull/36
    - [x] deletion-blocker-operator -> https://github.com/giantswarm/deletion-blocker-operator/pull/48
    - [x] dex-operator -> https://github.com/giantswarm/dex-operator/pull/41
    - [x] dns-operator-route53 -> https://github.com/giantswarm/dns-operator-route53/pull/97
    - [x] encryption-provider-operator -> https://github.com/giantswarm/encryption-provider-operator/commit/7991e834aea461072e0245081dd429dbd51b2102
    - [x] kyverno-policies-connectivity -> https://github.com/giantswarm/kyverno-policies-connectivity/pull/56
    - [x] kyverno-policies-dx -> https://github.com/giantswarm/kyverno-policies-dx/pull/51
    - [x] kyverno-policies-observability -> https://github.com/giantswarm/kyverno-policies-observability/pull/74
    - [x] kyverno-policies-ux -> https://github.com/giantswarm/kyverno-policies-ux/pull/29
    - [x] kyverno -> https://github.com/giantswarm/kyverno-app/pull/230
    - [x] nginx-ingress-controller-app -> https://github.com/giantswarm/nginx-ingress-controller-app/pull/437

- [x] While adding vsphere collection to apps, remove OpenStack collection.

**Comment by erkanerol** [comment]
All PRs are merged. Closing.
