### ISSUE TITLE
Support kubectl gs on CAPV

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2191]

**Comment by gawertm** [comment]
for kubectl gs template cluster there is currently no priority. I discussed with product and we can continue to focus on gitops only for now. 
There is a plan to introduce a more generic command (kgs create cluster) because we still want to support an imperative way of creating clusters. But that might superseed the kgs template cluster efforts in the end. Honeybadger or turtles will look into this new command and depending on the outcome we will know if we should do something with kgs template cluster or not. In the meantime we can focus on gitops.
fyi @giantswarm/team-rocket

**Comment by jkremser** [comment]
done in https://github.com/giantswarm/kubectl-gs/pull/1129
