### ISSUE TITLE
Verify Cluster Deletion works for CAPV

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2192]
vms are deleted properly
disks are detached properly
maybe LB service need to be checked

**Comment by erkanerol** [comment]
Since we will use kube-vip, we will not need to delete any LB since there will be no LB in vsphere level. 

I am trying to understand how volumes are managed. After understanding it and verifying clean-up process, I will close this ticket.

**Comment by erkanerol** [comment]
I did some tests today. CAPV doesn't clean PVs of WCs. I started a discussion in upstream slack. https://kubernetes.slack.com/archives/CKFGK3SSD/p1681204255627649

**Comment by erkanerol** [comment]
Update: My understanding from the discussion in upstream channel, we need to introduce cluster-api-cleaner-vsphere operator.

**Comment by erkanerol** [comment]
I started to implement the operator. FYI.

**Comment by erkanerol** [comment]
PR is ready for review. https://github.com/giantswarm/cluster-api-cleaner-vsphere/pull/1

**Comment by erkanerol** [comment]
All PRs are merged and cluster-api-cleaner-vsphere 0.1.0 has been released. Closing this issue.
