### ISSUE TITLE
Audit Logging for CAPV

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2194]
We need to support audit logging for CAPV.

Adapt cluster-vsphere
- [x] Add necessary flags to api-server. [Example](https://github.com/giantswarm/cluster-gcp/blob/main/helm/cluster-gcp/templates/_control_plane.tpl#L52)
- [x] Add audit log policy file. [Example](https://github.com/giantswarm/cluster-gcp/blob/main/helm/cluster-gcp/files/etc/kubernetes/policies/audit-policy.yaml)

**Comment by erkanerol** [comment]
The PR is ready for review https://github.com/giantswarm/cluster-vsphere/pull/59

**Comment by erkanerol** [comment]
The PR has been merged. Customer-specific configuration should be done for https://github.com/giantswarm/fluent-logshipping-app. I created customer-specific issues separately. Closing this one.
