### ISSUE TITLE
Remove CAPA crds from vintage MCs

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2199]
## Task

Remove CAPA crds from vintage MCs.

**Comment by fiunchinho** [comment]
From all `vintage` installations I will remove the following
- awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io
- awsclusterroleidentities.infrastructure.cluster.x-k8s.io
- awsclusters.infrastructure.cluster.x-k8s.io
- awsclusterstaticidentities.infrastructure.cluster.x-k8s.io
- awsclustertemplates.infrastructure.cluster.x-k8s.io
- awsfargateprofiles.infrastructure.cluster.x-k8s.io
- awsmachinepools.infrastructure.cluster.x-k8s.io
- awsmachines.infrastructure.cluster.x-k8s.io
- awsmachinetemplates.infrastructure.cluster.x-k8s.io
- awsmanagedmachinepools.infrastructure.cluster.x-k8s.io
- `giantswarm/capa-webhook-service-cert` secret
