### ISSUE TITLE
Possibility to delete the organization for users

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#220]
**Is your feature request related to a problem? Please describe.**
As a user, I cannot delete an organization by myself, only through SE.

**Describe the solution you'd like**
I would like to have an option to delete an organization when it is no longer needed without asking SE to do so.

**Describe alternatives you've considered**

**Additional context**
SEs receive this request frequently, making it possible for customers to delete their organizations can help remove the middle-man.

**Comment by snizhana-dynnyk** [comment]
This was implemented in MAPI
