### ISSUE TITLE
Remove cert-manager from default-apps and add coredns app [CAPVCD]

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2204]

**Comment by gawertm** [comment]
@erkanerol I think this task is obsolete?

**Comment by erkanerol** [comment]
We decided to keep cert-manager in default-apps bundle so ignore that part.

Regarding coredns, it will be tracked via https://github.com/giantswarm/giantswarm/issues/23449

Therefore, we can close this issue.
