### ISSUE TITLE
Check Apps up to date / dependabot for Rocket owned components

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2218]

**Comment by glitchcrab** [comment]
disabled dependabot for the following repos:

- bridge-operator
- kvm-operator
- flannel-network-health
- flannel-operator
- k8s-endpoint-updater
- k8s-kvm
- k8s-kvm-health
- mayu

**Comment by glitchcrab** [comment]
also went through all the PRs for the above repos and cleaned them all up
