### ISSUE TITLE
Upgrade MCs to `cluster-aws` (v0.29.0) and `default-apps-aws` (v0.23.2)

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2225]
## Task

Upgrade MCs to the latest versions of `cluster-aws` (0.29.0) & `default-app-aws` (v0.23.2).

Towards [issue](https://github.com/giantswarm/roadmap/issues/2144).

## Background

`cluster-aws` v0.29.0 introduced a lot of breaking changes due to the reorganization of the `values.yaml` file (see [RFC55](https://github.com/giantswarm/rfc/pull/55)).

The `values.yaml` file can be migrated from the old format to the new one with `yq`. See the following [Slack comment](https://gigantic.slack.com/archives/C03LV8E0RL7/p1679674840966789?thread_ts=1679663388.777069&cid=C03LV8E0RL7).

## TODOs

- [x] Upgrade `golem`;
- [x] Upgrade `grizzly`;
- [x] Upgrade `goat`;

**Comment by calvix** [comment]
done
