### ISSUE TITLE
`prometheus-operator-app` by default stores grafana settings in a emptyDir volume. We should in the `vaules.yaml` info about how to use a PVC.

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#223]
Thu, 29. Oct 2020 Request from @whites11 `prometheus-operator-app` by default stores grafana settings in a emptyDir volume. We should in the `vaules.yaml` info about how to use a PVC.

**Comment by QuentinBisson** [comment]
Also https://github.com/prometheus-community/helm-charts/pull/2050

**Comment by QuentinBisson** [comment]
This does not appear to be needed anymore
