### ISSUE TITLE
Prepare rollback/fallback plan for Cilium AWS v19 upgrade

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2234]
## User Story

- As a Giant Swarm customer, I would like to have a rollback or fallback plan for the upgrade from AWS v18 to v19 so that in case something goes wrong during the upgrade we can safely get the cluster back to a stable state as soon as possible.

## Acceptance Criteria

- [ ] Given a cluster being upgraded from AWS v18 to v19, when I trigger a rollback/fallback mechanism then I should get a working cluster soon after (e.g. after master nodes have rolled)

**Comment by paurosello** [comment]
The only rollback possible is to revert to release 18.4.0, we have tested and it works.

During the rollback there might be some connectivity issues as we are going  back to AWS CNI. 

Before rolling back we need to revert the podCIDR in the AWSCluster or the CF stack will fail to update.

Have also tested upgrading again with success.

**Comment by paurosello** [comment]
Reverting CNI in place is not possible because it depend on the AWS Operator to create ENI Configs and the AWS CNI is not installed as an app.

**Comment by LolloneS** [comment]
@paurosello do you think this rollback might fail because of AWS API throttling in big clusters?
