### ISSUE TITLE
Add CAPV standard test suite to cluster-test-suites

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#2245]
Once we have a working CAPV test MC and the cluster-vsphere is in a stable state this should be added to [cluster-test-suites](https://github.com/giantswarm/cluster-test-suites)

**Comment by AverageMarcus** [comment]
I've added a draft PR to start off adding CAPV - https://github.com/giantswarm/cluster-test-suites/pull/9

**Comment by jkremser** [comment]
- https://github.com/giantswarm/tekton-resources/pull/68
- https://github.com/giantswarm/cluster-test-suites/pull/16

**Comment by jkremser** [comment]
todo: autobranches -> main

**Comment by jkremser** [comment]
other related prs:
- https://github.com/giantswarm/cluster-test-suites/pull/24
- https://github.com/giantswarm/tekton-resources/pull/74
- https://github.com/giantswarm/tekton-resources/pull/73
- https://github.com/giantswarm/tekton-resources/pull/72
- https://github.com/giantswarm/tekton-resources/pull/70
- https://github.com/giantswarm/cluster-test-suites/pull/23
