### ISSUE TITLE
We need to ensure that test tools that create test clusters provide cilium CRDs

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2252]
We rely on cilium now, especially on Cilium Network Policies, and to make our test clusters compatible with tested apps, they need to have at least cilium CRDs installed. This applies to:
- architect, like here https://github.com/giantswarm/kiam-app/blob/88bb4bbeb5055b767cb7e08b2d1aa8ee9f427ef4/.circleci/config.yml
- `appptestctl`, which is in turn used by `ats`

**Comment by kubasobon** [comment]
Necessary changes implemented in `apptestctl` and included in `architect-orb` [v4.29.0 release](https://github.com/giantswarm/architect-orb/pull/416).
