### ISSUE TITLE
To get rid off fake HelmSourceFailed alert, we need to silence it or fix it for KVM

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2254]
More details here: https://gigantic.slack.com/archives/C01176DKNP4/p1680525966212559

To fix the false-positive alert, we need to either release `prometheus-rules` on KVM or silence that alert on KVM installations

There's also problem with China (akita).

**Comment by uvegla** [comment]
Created the `AlertManager` silences until: `2023-08-31`

- Anubis: https://alertmanager.g8s.he.k8s.emea.adsint.biz/#/silences/1c1cdfee-7ecd-466d-b361-1d3624cb54ab
- Buffalo: https://alertmanager.g8s.buffalo.cex.tribe.sh/#/silences/79166efc-b161-4dfa-8a26-862c2e8d0f60
- Bumblebee: https://alertmanager.g8s.bumblebee.kvm.gigantic.io/#/silences/8cdbe742-1262-4620-b7f4-caae4fe3d7b4
- Puma: https://alertmanager.g8s.p5x.telekom.de/#/silences/b3e11e59-79e7-4e27-8e76-af2646b19147

**Comment by uvegla** [comment]
Akita silence: https://github.com/giantswarm/silences/pull/944
