### ISSUE TITLE
Integrate CAPV mc-bootstrap tests into current infrastructure #2220

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2255]
Acceptance criteria:

- [ ] CAPV flow is being tested as part of `/test all-providers` on mc-bootstrap PRs

**Comment by yulianedyalkova** [comment]
Currently blocked by https://github.com/giantswarm/giantswarm/issues/26602

**Comment by jkremser** [comment]
done in https://github.com/giantswarm/mc-bootstrap/pull/513 CAPV should be there \o/
