### ISSUE TITLE
Package Mimir into an app

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2264]
Create a Mimir application under our giantswarm organization

- Setup repository https://github.com/giantswarm/github/#setting-up-a-repository
- Create helm chart (maybe use https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed)
- Push this into control-plane-catalog

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa what's left here? :D

**Comment by QuentinBisson** [comment]
I just setup circleci so I think not :D https://app.circleci.com/pipelines/github/giantswarm/mimir-app

**Comment by QuantumEnigmaa** [comment]
Chart created and working (still under development obviously)
