### ISSUE TITLE
Deploy Mimir

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2265]
Deploy Mimir to `gauss` installation

**Comment by QuantumEnigmaa** [comment]
Should we manually create an app CR for this or should we add Mimir to aws-collection ?

**Comment by hervenicol** [comment]
For early tests, we don't want to push to collections: it would deploy Loki on all MCs.
This issue talks about deploying it only on `gauss`, so it's a manually-crafted app CR.

Now I wonder where we should store these:
* app CR
* user-values

**Comment by hervenicol** [comment]
BTW, it's currently deployed and seems to work, but there is still quite a lot of tuning to do.

**Comment by hervenicol** [comment]
I did some tuning:
* disabled `zoneAwareReplication`
* increased `ingester.max-global-series-per-user`

Next problem: in 3 hours the ingesters fill up their `/data` disk space.
Maybe 2GB is not enough given the amount of metrics it ingests?
```
/data/tsdb/anonymous $ du -shx *
42.9M   01GY0FWADHH6F8C3P531VWXJF6
174.1M  01GY5DXPBHJXEHF5FWQJC7CCA8
224.3M  01GY5DYC5HBAW0Z9XXFTV27YDF
179.9M  01GY5DZ0039EA7JXV77HG1MKFB
19.0M   01GY5DZMSE0CAG6248EMSSJ4QQ
57.8M   chunks_head
4.0K    mimir.shipper.json
0       mimir.shipper.json.tmp
4.0K    thanos.shipper.json
1.1G    wal
/data/tsdb/anonymous $ df -h .
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme6n1              1.9G      1.9G         0 100% /data
/data/tsdb/anonymous $ lsof | grep -i deleted
1       /bin/mimir      34      /data/tsdb/anonymous/wal/checkpoint.00000004.tmp/00000002 (deleted)
/data/tsdb/anonymous $ du -shx wal/*
3.8M    wal/00000000
127.8M  wal/00000001
128.0M  wal/00000002
128.0M  wal/00000003
128.0M  wal/00000004
128.0M  wal/00000005
128.0M  wal/00000006
128.0M  wal/00000007
22.5M   wal/00000008
128.0M  wal/00000009
125.9M  wal/00000010
/data/tsdb/anonymous $ 
```

**Comment by hervenicol** [comment]
With 10Gb PV per ingester, it looks good on `gauss`:
![image](https://user-images.githubusercontent.com/12008875/232703890-45fd1ed4-a832-42b4-b1a8-4b4b4c647094.png)

However, this one will require an alerting rule. Because WAL size may be quite different from one install to another.

**Comment by QuantumEnigmaa** [comment]
I think we can now close this issue as Mimir is being deployed without any error

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa Can you add all that you did to have mimir deployed?

**Comment by hervenicol** [comment]
> @QuantumEnigmaa Can you add all that you did to have mimir deployed?

We chose to make it part of the app repo, so it's easier to find it later.
See https://github.com/giantswarm/mimir-app/pull/9

**Comment by QuentinBisson** [comment]
Nice :) so we can close ?
