### ISSUE TITLE
Managed Apps Upgrades (Month of 9. Nov 2020)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#227]
Aim to focus on 30DU and get them done within 2 days.

**NGINX Ingress Controller** @giantswarm/app-squad-nginx  
https://github.com/giantswarm/nginx-ingress-controller-app @glitchcrab 

* Link to latest release: https://github.com/giantswarm/nginx-ingress-controller-app/blob/master/CHANGELOG.md#1110---2020-11-18

- [x] upgrade
- [x] release

**External DNS** @giantswarm/app-squad-external-dns  
https://github.com/giantswarm/external-dns-app @ubergesundheit 

* Link to latest release: 
* If won't upgrade, why?

*didn't upgrade. our latest release contains latest upstream*

- [x] upgrade
- [x] release

**Cert Manager** @giantswarm/app-squad-cert-manager  
https://github.com/giantswarm/cert-manager-app @glitchcrab 

* Link to latest release: https://github.com/giantswarm/cert-manager-app/blob/master/CHANGELOG.md#232---2020-11-09
* Another release :sweat_smile: https://github.com/giantswarm/cert-manager-app/blob/master/CHANGELOG.md#240---2020-12-22

- [x] upgrade
- [x] release

**EFK** @giantswarm/app-squad-efk  
https://github.com/giantswarm/efk-stack-app @webwurst end of week. Please ping @ubergesundheit 

* Link to latest release: https://github.com/giantswarm/efk-stack-app/blob/136d4e4032e30a4eebb31af895d831629f325264/CHANGELOG.md#040---2020-12-08

- [x] upgrade
- [ ] release

**Kong** @giantswarm/app-squad-kong  
https://github.com/giantswarm/kong-app @ced0ps @ubergesundheit 

* Link to latest release: https://github.com/giantswarm/kong-app/blob/master/CHANGELOG.md#110---2020-12-02

- [x] upgrade
- [x] release

**Prometheus Operator** @giantswarm/app-squad-prometheus  
https://github.com/giantswarm/prometheus-operator-app @ced0ps 

* Link to latest release: 
* If won't upgrade, why?

- [x] upgrade
- [x] release

**aqua**  
https://github.com/giantswarm/aqua-app  -- waiting for Yasser

- [x] upgrade
- [x] release

* Link to latest release: 
* If won't upgrade, why? @jgsqware or @yasn77 we'll skip checking for any upgrades unless you tell us to.

---

Notes
* Team divides the app upgrades amongst ourselves. Please add @ name beside the app
* [30 Day Upgrade Promise](https://intranet.giantswarm.io/docs/product/pdr/003_30-day-upgrade-promise/): By default, we upgrade our apps within 30 days of an upstream release. We know that falling behind releases and putting upgrades off for extended amounts of time, especially when there’s breaking changes, almost always comes back to bite us.
* Engineer can override this default and decide not to upgrade with good reason.

**Comment by cokiengchiara** [comment]
@yasn77 there is Aqua upgrade customer would like deployed. Waiting for more info.

**Comment by cokiengchiara** [comment]
New Aqua upgrade details from @yasn77 https://gigantic.slack.com/files/UNK5QGK7A/F01EUGDE23B/_information_version_5.3_

**Comment by cokiengchiara** [comment]
Preparing for announcements.

Will include NGINX and cert manager in this week announcements.

1. prometheus-operator - hi @TheoBrigitte , @mig4 thanks for helping out w prometheus-operator upgrade! Let me know when you are done with the [PR](https://github.com/giantswarm/prometheus-operator-app/pull/53) or if @giantswarm/app-squad-prometheus can help with anything
2. @giantswarm/app-squad-efk - I see something was [fixed](https://github.com/giantswarm/efk-stack-app/blob/master/CHANGELOG.md#035---2020-11-25). Can you confirm if we are updated within the last 30 days?
3. @giantswarm/app-squad-kong - any upgrades available? :)
4. Aqua - @glitchcrab , we should find additional Squad member for Aqua aside from you. But do you mind taking care of this Aqua upgrade? :) https://github.com/giantswarm/aqua-app/blob/master/CHANGELOG.md (@yasn77 , sorry I dropped the ball on this when I went on vacation. Is adidas still waiting for it?)

**Comment by TheoBrigitte** [comment]
This PR has been stale for couple of days. I'll pick this up on monday.

**Comment by cokiengchiara** [comment]
Kong - @ubergesundheit will look at Kong upgrade. Feel free to ask @glitchcrab or @yasn77 . There is a script that makes this easy. In the repo.

Aqua - @glitchcrab will do it.

**Comment by cokiengchiara** [comment]
thanks @TheoBrigitte !

@giantswarm/team-halo and maybe Theo as well -- I saw the upgrade PR was merged https://github.com/giantswarm/prometheus-operator-app/pull/53. But was it released, just not in the changelog?

**Comment by TheoBrigitte** [comment]
> thanks @TheoBrigitte !
> 
> @giantswarm/team-halo and maybe Theo as well -- I saw the upgrade PR was merged [giantswarm/prometheus-operator-app#53](https://github.com/giantswarm/prometheus-operator-app/pull/53). But was it released, just not in the changelog?

Above PR was merged. But there still an issue with upgrade path. I do not feel confident in releasing before upgrade can be tested successfully.

**Comment by cokiengchiara** [comment]
> > thanks @TheoBrigitte !
> > @giantswarm/team-halo and maybe Theo as well -- I saw the upgrade PR was merged [giantswarm/prometheus-operator-app#53](https://github.com/giantswarm/prometheus-operator-app/pull/53). But was it released, just not in the changelog?
> 
> Above PR was merged. But there still an issue with upgrade path. I do not feel confident in releasing before upgrade can be tested successfully. I have 2 PRs open where I attempted to fix this, but I would need a hand from someone with more experience related to helm2/3 and CRDs.

sure, thanks! Let us know if you need help. @glitchcrab might have encountered it w cert manager as well.

**Comment by cokiengchiara** [comment]
> * [ ]  Aqua - @glitchcrab will do it.

@yasn77 -- do you know what customer is looking for in the Aqua upgrade? So we can test that specifically?

**Comment by cokiengchiara** [comment]
Todos for this week or next year 🙈
- [ ] Review and release prometheus operator https://github.com/giantswarm/prometheus-operator-app/pull/62/files @giantswarm/app-squad-prometheus 
- [ ] Aqua upgrade @glitchcrab
- [ ] Follow up w @yasn77 re: what customer is looking for in Aqua upgrade so we can test specifically.
- [ ] EFK upgrade @giantswarm/app-squad-efk

**Comment by yasn77** [comment]
@cokiengchiara 

> * Follow up w @yasn77 re: what customer is looking for in Aqua upgrade so we can test specifically.

They haven't said anything specific. Just that there is a new version that needs to be deployed. They sent out a changelog which might useful to look over. But I don't really have anything that we should test for.

Once we are ready, it might be worth reaching out to them in the channel to double check.

**Comment by TheoBrigitte** [comment]
[prometheus-operator v0.5.0](https://github.com/giantswarm/prometheus-operator-app/releases/tag/v0.5.0) was release yesterday.

This release is mainly a fix over v0.4.0 which was broken due to CRDs, it also bring minor updates to all components (prometheus-operator , prometheus, etc ...).

Shout out to Mr @glitchcrab for the CRD fix, saved me from going insane and loosing too much time on complex things.

**Comment by cokiengchiara** [comment]
@webwurst will release EFK. 

@glitchcrab is working on Aqua.

**Comment by cokiengchiara** [comment]
> @glitchcrab is working on Aqua.

thanks @glitchcrab . Will include it in this week announcements. https://github.com/giantswarm/releases/pull/576

**Comment by cokiengchiara** [comment]
> Waiting for @webwurst re: EFK to close this issue.

- [ ] @webwurst update customer when it's available ([slack](https://gigantic.slack.com/archives/C01B2TW7JBD/p1610519725008200))

**Comment by cokiengchiara** [comment]
> @webwurst will release EFK.
> 
> @glitchcrab is working on Aqua.

EFK and Aqua are both released and announced, as well as all apps here https://github.com/giantswarm/releases/blob/master/announcements/2021-Week-03/announcement.md closing
