### ISSUE TITLE
Implement best practices for `grafana` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2289]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [ ] the app has properly set PDBs (as percentages)
- [ ] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [ ] the app runs with more than 1 replica by default (if it needs HA)
- [ ] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by Rotfuks** [comment]
From @hervenicol 

> *   Running more than 1 replica (HA setup) requires to externalize the Grafana database (from `sqlite` to `mysql` or `postgresql`). See [Set up Grafana for high availability](https://grafana.com/docs/grafana/latest/setup-grafana/set-up-for-high-availability/).
> *   horizontal scalability requires more than 1 replica
> *   PDBs require more than 1 replica
> 
> So the first step for this issue is to run grafana with a "real" database and HA.  
> It's not only a change of architecture, but also changes how we operate grafana: this will add persistence to custom-imported dashboards and datasources.

**Comment by Rotfuks** [comment]
We don't really see big issues with the resilience of our grafana-app and a lot of effort to implement this. The comment of Hervé shows this. 

So low-value, high-effort - which means we won't be focusing on this issue and close it out of scope for now. 

We might revisit it if we face grafana resilience issues but we don't see it at this point.
