### ISSUE TITLE
Implement best practices for `promtail` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2293]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [x] the app has properly set PDBs (as percentages)
- [x] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [x] the app runs with more than 1 replica by default (if it needs HA)
- [x] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by QuentinBisson** [comment]
- Promtail is not using any emptyDir
- Promtail is a DaemonSet and so does not PDBs and it's very unlikely this will ever make it https://github.com/kubernetes/kubernetes/issues/108124
- Promtail is a DaemonSet so the number of replicas cannot be changed, it's always 1 per node

Now we might want to use VPA for it. @giantswarm/team-atlas what do you think?

**Comment by QuentinBisson** [comment]
@TheoBrigitte can we close here?

**Comment by TheoBrigitte** [comment]
Yes sounds alright to me.
