### ISSUE TITLE
Implement best practices for `rbac-bootstrap` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2301]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [x] the app has properly set PDBs (as percentages)
- [x] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [x] the app runs with more than 1 replica by default (if it needs HA)
- [x] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by anvddriesch** [comment]
rbac boostrap app does not have any deployment/pods so none of the points apply.
