### ISSUE TITLE
Implement best practices for `default-apps-aws` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2306]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [ ] the app has properly set PDBs (as percentages)
- [ ] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [ ] the app runs with more than 1 replica by default (if it needs HA)
- [ ] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by fiunchinho** [comment]
@LolloneS the `default-apps-aws` is a bundle of apps that installs the default apps required in a cluster. It's not an _app_ in itself, so I don't think this issue makes sense for `default-apps-aws`. Before closing it, I'd like a confirmation from your side, because I may be missing something.

**Comment by LolloneS** [comment]
Looking at the apps inside `default-apps-aws` I see:

```
appName: aws-ebs-csi-driver
appName: aws-pod-identity-webhook
appName: capi-node-labeler
appName: cert-exporter
appName: cert-manager
appName: coredns
appName: cilium
appName: external-dns
appName: metrics-server
appName: net-exporter
appName: node-exporter
appName: vertical-pod-autoscaler
appName: vertical-pod-autoscaler-crd
appName: observability-bundle
```

Most of these apps already have their issues assigned to the appropriate teams. Do you see any app owned by hydra that could use a sanity check on whether it's well configured? If yes, I can open an issue for that specific app, otherwise we close this one and we're good :)

**Comment by fiunchinho** [comment]
I don't think we have any other managed apps. The rest of the apps we own are only deployed to MCs.

**Comment by LolloneS** [comment]
Then we're good to close. Thanks! 😄
