### ISSUE TITLE
Implement best practices for `external-secrets` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2307]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [ ] the app has properly set PDBs (as percentages)
- [ ] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [ ] the app runs with more than 1 replica by default (if it needs HA)
- [x] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by uvegla** [comment]
While the app can run in HA cos it has leader election implemented upstream, we disabled it intentionally cos we are running with 1 replica, as 1 will do work at a given time anyway: it is okay to have short disruptions / deployment not being satisfied for short period of time. We also run it on all MCs so having the deployment duplicated could be somewhat costly for pods not doing anything. Currently if any deployment is not satisfied in the `external-secrets` namespace for more than 30m we get [alerted](https://github.com/giantswarm/prometheus-rules/blob/af888cb27255150b753f34e09af8132f9f655c03/helm/prometheus-rules/templates/alerting-rules/external-secrets.rules.yml#L13-L27). Thus with 1 pod and tolerable short outages we are fine, I think PDB does not make sense either for ESO at the moment.

There is no `emptyDir` used in the current state.
