### ISSUE TITLE
Implement best practices for `flux-app` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2308]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [ ] the app has properly set PDBs (as percentages)
- [ ] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [ ] the app runs with more than 1 replica by default (if it needs HA)
- [ ] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by uvegla** [comment]
It is possible to enable leader election in Flux components via the `--enable-leader-election`, but we do not need this at the moment for our split giantswarm / customer flux setup.

The `emptyDir` is needed for Flux to store artifacts and resources it applies to the clusters. There was an approach to use PVCs at an early stage of our Flux offering but [it was deprecated ](https://github.com/giantswarm/flux-app/pull/30/files#diff-a0291ed1bce2304242a87ff0aeb699922daffcc7f79192af0a1947abbde4dfcb) and we moved back to use the upstream recommendation. Cleaning up some leftover files for that via https://github.com/giantswarm/flux-app/pull/195.
