### ISSUE TITLE
Implement best practices for `gitops-server` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2309]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [ ] the app has properly set PDBs (as percentages)
- [ ] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [ ] the app runs with more than 1 replica by default (if it needs HA)
- [x] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by uvegla** [comment]
It is a "glorified" UI for flux that is mostly read only with some minor interactions like suspending, resuming and forcing a reconciliation on flux resources. I think it is questionable to make it HA, PDBs and scaling as I would imagine it is rarely used and for that it is easting resources (needs a "lot" for visual graph generation on the fly for resource trees, if someone want to check it) so I would not make it waste more resources.

It is not using emptyDir volumes.
