### ISSUE TITLE
Spec: Run a separate app-operator per namespace (and therefore per Tenant Cluster)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#231]
This is the ADR describing why we want this: https://intranet.giantswarm.io/docs/architecture-specs-adrs/adr/009-why-per-namespace-app-operator/ (internal doc)

**Comment by tomahawk28** [comment]
Now in; https://intranet.giantswarm.io/docs/architecture-specs-adrs/specs/app-operator-per-cluster-namespace/
