### ISSUE TITLE
Implement best practices for `linkerd-control-plane` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2317]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [x] the app has properly set PDBs (as percentages)
- [x] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [x] the app runs with more than 1 replica by default (if it needs HA)
- [x] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by mcharriere** [comment]
> the app has properly set PDBs (as percentages)

it already has PDB set with maxUnavailable=1; this is coming from upstream.

> the app can scale horizontally based on Custom Metrics (if it makes sense)

No need, as scaling these service is highly dependent on the cluster size. We'll for now let it pass as we gather more exp with running linkerd at scale.

> the app runs with more than 1 replica by default (if it needs HA)

It does.

> the app does not use emptyDir volumes if not strictly necessary

app needs emptyDir enabled cluster-wide. This is a problem as our default policy is blocking that. see https://github.com/giantswarm/giantswarm/issues/21039
