### ISSUE TITLE
Spec: app-platform-operator (that manages per WC app-operators)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#232]
Note: This story is to write the spec, not implement it.

Business value: 
* To buy us time to do something we know would be useful in the future regardless, while we talked to customers to figure out what to do next.
* Future value: Decouples app platform components from workload cluster releases, allowing us to move faster.

User value: 
* Use app platform in any cluster (even non-Giant Swarm ones), reducing perception of lock in

Wed, 28. Apr 2021 update from Ross:

We had a sync call between Batman and Ludacris earlier. 2 decisions coming from that.

The Release Channels part of this spec needs more discussion. I will create a fresh PR for this.
 
We will create a new "cluster-apps-operator" for managing workload cluster apps to replace cluster-operator.
See https://github.com/giantswarm/giantswarm/issues/16899

---

 - [ ] get SE feedback when preparing spec
 
# Problem

Currently, the Resource for appcatalog, `appcatalogEntry` is located inside the app-operator. 
Even though we only need this `appCatalogEntry` logic for control-plane apps, it's also running inside all recent app-operator pods for workload clusters as well. (e.g. `app-operator-2-6-0` pod for AWS platform release 12.5.1)

We have two different controllers in app-operator (app, app catalog) but their concerns are totally different. Moreover, app-operator consumes lots of resources but we are not sure which controller uses much of that. 

# Solution

To make a unique app where we have `appCatalog` logic and to slim down the burden of the app-operator, I would like to propose the new `appcatalog-operator`.

**Comment by tomahawk28** [comment]
@piontec Can you post your opinion on this issue?

**Comment by piontec** [comment]
Let's put it on hold until we resolve per-TC app-operator

**Comment by cokiengchiara** [comment]
As discussed in [cycle planning](https://docs.google.com/spreadsheets/d/1FyOzDb3Phpm78ws64qt1rlaPOtOUwc6ddIePmIdIXQM/edit#gid=2067429298&range=A9), repurposed and renamed this issue.

**Comment by cokiengchiara** [comment]
@rossf7 will write down what he discussed w @piontec

**Comment by cokiengchiara** [comment]
@rossf7 has a half written PR.

**Comment by rossf7** [comment]
Spec PR is ready for review https://github.com/giantswarm/giantswarm/pull/15630 and now also covers replacing the app related logic in cluster-operator.

After the Hive sprint the only logic left is related to managing apps. See https://github.com/giantswarm/cluster-operator/pull/1357

After discussion with @JosephSalisbury @kubasobon and @MarcelMue our preferred option is Batman moves this logic to app-platform-operator and we retire cluster-operator once its no longer used.

One issue is in cluster-operator we use the master branch for AWS but still need to support the legacy branch for Azure and KVM. This code is very old and means we need to repeat every change twice.

So it would be best not to merge the CAPI changes into master and use a feature branch in cluster-operator until app-platform-operator is ready. @JosephSalisbury @kubasobon Is that still OK?

cc @cokiengchiara @piontec @tomahawk28

**Comment by kubasobon** [comment]
Makes sense. The plan was not to merge the branch for now, but create one or more experimental releases from it. It can become a starting point for a new app-platform-operator repository somewhere along the way.

**Comment by rossf7** [comment]
Great thanks @kubasobon and yes we'll definitely use the branch as the starting point for the new operator.

**Comment by cokiengchiara** [comment]
@rossf7 are these the next steps? :)

- [ ] Create fresh PR for the Release Channels part of the spec (needs more discussion)
- [ ] Create a new "cluster-apps-operator" for managing workload cluster apps to replace cluster-operator.
See #16899

**Comment by rossf7** [comment]
> Create a new "cluster-apps-operator" for managing workload cluster apps to replace cluster-operator.

This is nearly done. Just needs a new app-operator release. It's tracked in https://github.com/giantswarm/roadmap/issues/320

> Create fresh PR for the Release Channels part of the spec (needs more discussion)

I don't want to continue with the Release Channels spec at this time. We don't have resource to work on it and it feels "far future" to me.
