### ISSUE TITLE
Replace `yajsv` with `jv` in values schema validation action

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#2329]
In https://github.com/giantswarm/devctl/blob/main/pkg/gen/input/workflows/internal/file/check_values_schema.yaml.template we should replace using `yasv` with `jv` from https://github.com/santhosh-tekuri/jsonschema#cli

The `jv` tool supports the latest draft, which yasv does not.

**Comment by gawertm** [comment]
@weatherhog value schema topic went to honeybadger. assigning your label

**Comment by marians** [comment]
I think so, yes
