### ISSUE TITLE
Spec: Add Apps README to Metadata folder

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#233]
Towards EPIC_URL

## User Story

- As a ROLE, I would like FEATURE so that REASON

## Acceptance Criteria

- [ ] Given PRECONDITION when I do ACTION then I should get RESULT

## Dependencies

- [ ] URL - TITLE

## Tasks

- [ ] URL - TITLE

**Comment by cokiengchiara** [comment]
@oponder or @piontec can you edit the body of this issue? I didn't get what it was about :)

**Comment by piontec** [comment]
We want to "freeze" REDME.md as part of metadata. If we only reference the readme with an URL, we're risking that it will be changed and will stop reflecting the README from the time the app was created.

**Comment by piontec** [comment]
Implemented in https://github.com/giantswarm/giantswarm/issues/14279

**Comment by cokiengchiara** [comment]
@piontec so this is done? If yes, please close. 😁

**Comment by cokiengchiara** [comment]
It's done.

**Comment by piontec** [comment]
Done, closing :+1:
