### ISSUE TITLE
set cloud provider credentials command for kgs

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#2330]

**Comment by marians** [comment]
Note for refinement: this is about allowing an admin to set cloud provider credentials used by an organization. We have [`gsctl update organization set-credentials`](https://docs.giantswarm.io/use-the-api/gsctl/update-org-set-credentials/) but need a replacement via the Management API.

**Comment by kuosandys** [comment]
From team rainbow refinement:
- we already have docs on how to do this manually
- we could refine what the command should be called/looks like, preferably with Marian

**Comment by weatherhog** [comment]
closing this issue
