### ISSUE TITLE
Use CAPI v1beta1 API version in our Go code

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2331]
From Nikola on Slack (https://gigantic.slack.com/archives/C04TGHDEF/p1680523733093799):

> :warning: :capi: In the latest Cluster API version v1.4 old alpha API groups v1alpha3 and v1alpha4 are deprecated.
> v1alpha3 will be removed in v1.5
> v1alpha4 will be removed in v1.6
> AFAIK we never used v1alpha4 in our MCs, and it took quite an effort to upgrade from v1apha3 (which we used for quite some time) to v1beta1 Cluster API types. Meaning we should be good when it comes to CAPI version that we have deployed to our clusters.
> Client code in our go components is another story, updating that took very long time and every now and then something that still uses v1alpha3 types would pop up :see_no_evil:
> Please review your team's go components and ensure that they are using the v1beta1 Cluster API types in the code, meaning your go component should use CAPI v1.x.x version. (edited)

**Comment by erkanerol** [comment]
- [ ] cluster-cloud-director -> uses v1beta1
- [ ] cluster-vsphere -> uses v1beta1
- [ ] dns-operator-route53 -> uses v1beta1
- [ ] encryption-provider-operator -> uses v1beta1
- [ ] deletion-blocker-operator -> No hardcoded version. We use v1beta1 in config. https://github.com/giantswarm/config/blob/main/default/apps/deletion-blocker-operator/configmap-values.yaml.template#L6
- [ ] cluster-api-cleaner-cloud-director -> No CAPI API version. Only utils.

**Comment by erkanerol** [comment]
Closing this as done.
