### ISSUE TITLE
Bastion provisioning and ssh support

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#2339]
We should provision bastion machines for CAPV clusters so that we can connect nodes via ssh.

**Comment by gawertm** [comment]
will use existing setup. maybe teleport in the future

**Comment by erkanerol** [comment]
Are we sure about how we will provision bastion hosts? Will we use one static machine for all? We followed that way in cloud-director because of security restrictions in the customer side but I am now sure about CAPV. I propose to discuss this in the grooming meeting.

**Comment by gawertm** [comment]
ok fair enogh, lets bring this up. I thought this ticket was specifically to get started in customer environement and there we can use the existing setup. but probably good to use this ticket for discussion how to deal with in future. will keep it open until then

**Comment by gawertm** [comment]
need to find out if teleport will be ok for special CAPV customers. if so, we wont need the bastion hosts.
if teleport wont work for them, we need to discuss the bastion concept per workload cluster, same as e.g. CAPA does it.

**Comment by gawertm** [comment]
notneeded bc of teleport
