### ISSUE TITLE
Support Node Pools with 0 nodes

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#234]
## User Story

As a customer, I want to have node pools with 0 nodes in order to reduce costs for workloads which are not running all the time.

## Background

Currently, node pools have to have at least 1 node. This restriction has at least two negative consequences:
- node pools with GPUs have to always have at least 1 node which leads to increased costs (these are very expensive EC2 instances) for what are mostly batch workloads;
- the Cluster AutoScaler cannot fallback to the On-Demand and is stuck if there are no spot instances available because it tries to meet the at least 1 instance constraint (see: https://github.com/giantswarm/adidas/issues/579#issuecomment-707662428).

**Comment by paurosello** [comment]
I have tested via Control Plane API and it seems to work just fine.

Will check the API and Happa to remove this limits

**Comment by paurosello** [comment]
API supports scaling to 0, happa and gsctl do not

**Comment by paurosello** [comment]
Happa is fixed, gsctl change is identified and will provide PRs shortly for **api-spec**, **gsclientgen** and **gsctl**
