### ISSUE TITLE
Automatically manage RBAC of manually created SAs

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#2342]
Some customers have manually managed service accounts (and possibly other resources), which need to have specific permissions in organization and/or cluster namespaces in the MC.
To ensure that the resources have correct permissions in all namespaces including newly created ones, the permissions need to be managed automatically.

https://gigantic.slack.com/archives/CJRCQ8W0G/p1680768288716589

**Comment by kuosandys** [comment]
From team rainbow refinement:
- [ ] Check existing fine-grained permissions for users and groups (current roles/clusterroles and bindings), and how this could be adapted to be used for service accounts

**Comment by anvddriesch** [comment]
We are thinking to introduce templates for rolebindings which would also allow SAs as subjects https://github.com/giantswarm/roadmap/issues/2706
This would enable certain bindings to be created in each new organization or organizations that match certain labels.

**Comment by anvddriesch** [comment]
This is solved using [role binding templates](https://docs.giantswarm.io/use-the-api/management-api/authorization/#role-binding-templates)
