### ISSUE TITLE
CAPI SR Release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2352]
## Rock

First Giant Swarm CAPI release.

```[tasklist]
### Provider
- [ ] https://github.com/giantswarm/roadmap/issues/2726
- [ ] https://github.com/giantswarm/roadmap/issues/2753
- [ ] https://github.com/giantswarm/roadmap/issues/2738
```

## Links
- [Scope document](https://docs.google.com/document/d/1oYXIs_Zj-eFVDGxFEILodEygC8-rK7cbTkzCtWVJOj4/edit#);

**Comment by teemow** [comment]
What is the difference between this issue and https://github.com/giantswarm/giantswarm/issues/25493

Can we merge them?

**Comment by alex-dabija** [comment]
> What is the difference between this issue and [giantswarm/giantswarm#25493](https://github.com/giantswarm/giantswarm/issues/25493)
> 
> Can we merge them?

There isn't much difference between the 2 issues. I'll merge the 2 issues.

**Comment by alex-dabija** [comment]
I closing this issue because we have the separate SR releases per provider. We are also focusing now only on CAPA.
