### ISSUE TITLE
Automate IPAM for CAPV

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#2353]
Now, we have parameters in cluster-vsphere for k8s API and load balancer IPs. We should automate IP management to prevent conflicts between WCs. We may implement a validation webhook with kyverno.

**Comment by gawertm** [comment]
@jkremser after your IPAM implementation. I think we can close this ticket here?

**Comment by jkremser** [comment]
correct, closing

**Comment by jkremser** [comment]
for the record, it was tracked here: https://github.com/giantswarm/giantswarm/issues/27164#issuecomment-1634557687
