### ISSUE TITLE
Configure custom static clients in Dex

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2359]
Add a possibility to configure additional custom static clients in the Dex app in addition to the existing pre-defined static clients.

https://github.com/giantswarm/dex-app/blob/f95e07ce3b06687e3f2ffc8879fe042917651878/helm/dex-app/templates/dex/secret.yaml#L43

**Comment by anvddriesch** [comment]
We need this for oauth2 proxy https://gigantic.slack.com/archives/C02FJACQ3D4/p1681803887131659

**Comment by mogottsch** [comment]
We discussed during refinement that we want to use the same values structures to define static clients as its being used in the upstream dex chart.
