### ISSUE TITLE
Make cloud-init script configurable in CAPVCD (BYOI)

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#2362]
Any change to the [cloud-init script](https://github.com/vmware/cluster-api-provider-cloud-director/blob/main/controllers/cluster_scripts/cloud_init.tmpl) requires to build a custom image. 

[Maintainers are open to a PR](https://kubernetes.slack.com/archives/C04JFT7GDGR/p1681492574310789?thread_ts=1681391553.149689&cid=C04JFT7GDGR) to make the cloud-init script customizable.

This would simplify compatibility for BYOI.

**Comment by erkanerol** [comment]
I did a minimal proposal here https://kubernetes.slack.com/archives/C04JFT7GDGR/p1684754573568679 Waiting for response.

**Comment by erkanerol** [comment]
After doing some experiments, created an issue https://github.com/vmware/cluster-api-provider-cloud-director/issues/485

**Comment by erkanerol** [comment]
Update: Still waiting for feedback from maintainers. Meanwhile, I will test flatcar support via https://github.com/giantswarm/roadmap/issues/2506

**Comment by gawertm** [comment]
superseeded by other flatcar task
