### ISSUE TITLE
Cluster role `crd-controller` needs managed-by label and description annotation

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#2363]
On `gullum` the `crd-controller` cluster role appears without this meta information:

![Image](https://user-images.githubusercontent.com/273727/232450681-42f0e453-85d5-4b66-b336-081b397aecdb.png)

The ClusterRole resource is missing two metadata pieces which are important for UX reasons:

- Label `giantswarm.io/managed-by`: explains which component manages the resource. For example: `rbac-operator`.
- Annotation `giantswarm.io/notes`: Should provide user-friendly explanation of the purpose of this role.

Alternatively, we could decide to hide the role if we don't expect users to bind it manually.

Here is an example showing the according information in the happa UI:

![Image](https://user-images.githubusercontent.com/273727/232451897-36f3e936-264d-487e-96c6-2d792ab75df1.png)

So we have to figure out this information so that we can add it as metadata (wherever it's created).

**Comment by marians** [comment]
@giantswarm/team-honeybadger Do you expect admins to bind the `crd-controller` cluster role manually? In other words: should it really appear in the UI? If yes, we should add more info (see above), but if no, we should hide it (and I'll dig out the proper label for this).

**Comment by marians** [comment]
Based on the `helm.sh/chart` label, this resource is managed by flux-app.

**Comment by uvegla** [comment]
Yes, it is needed for Flux to operate and it is bound to by all SAs used by controllers: https://github.com/giantswarm/flux-app/blob/d4fd3b9814f1d80c6f89e5ed3c29a1b41ee8747b/helm/flux-app/templates/install.yaml#L313-L347

It is coming from upstream, docs for it: https://fluxcd.io/flux/security/#controller-permissions

We also have a patch in MCF to duplicate / separate this for the GS Flux:
- https://github.com/giantswarm/management-clusters-fleet/blob/b452bf740249df75d543d259df0da984bed4540b/bases/flux-app/giantswarm/kustomization.yaml#L35-L44
- https://github.com/giantswarm/management-clusters-fleet/blob/b452bf740249df75d543d259df0da984bed4540b/bases/flux-app/giantswarm/kustomization.yaml#L59-L68

I am not sure if customers want to (or can, actually) bind the cluster role, but it is a possibility.

**Comment by marians** [comment]
Thanks @uvegla for the details!

It sounds as if it's not something a user would bind manually via the UI.

An now I'm wondering: why does it even show up in the UI? It does not carry the label `ui.giantswarm.io/display: "true"`.

@gusevda Can you help here? Why does the UI show this ClusterRole resource? What criteria are we using for the selection of that list?

**Comment by gusevda** [comment]
@marians `crd-controller` ClusterRole comes from `flux-crd-controller` RoleBinding.
This is how the final list is prepared:
1) We fetch
- Roles in the organization namespace with `ui.giantswarm.io/display: true`;
- ClusterRoles with `ui.giantswarm.io/display: true`;
- RoleBindings in the organization namespace without any filtering. 
2) Then we combine all of the resources in one list.
3) We don't display Roles and ClusterRoles that start with `system:`.

For roles that come from RoleBindings we don't display meta information. So even if `crd-controller` ClusterRole has meta information, it won't be displayed, because we don't fetch the role itself, we just take role name from the `RoleBinding.roleRef.name`

**Comment by marians** [comment]
We might have something to improve here, however possibly not with great importance.

**Comment by weatherhog** [comment]
@marians are you okay with closing this as this seems to be happa related?

**Comment by marians** [comment]
Yes, closing
