### ISSUE TITLE
Test Atlas apps on v19

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#2368]
Towards https://github.com/giantswarm/giantswarm/issues/23014

We need to test our apps and make sure networking still works on the AWS v19 beta release

From the top of my head:

- [x] observability-bundle
    - [x] prometheus-operator-app
        - [x] kube-state-metrics
    - [x] promtail
    - [x] prometheus-agent
- [x] datadog-app
- [x] node-exporter-app
- [x] grafana-app
- [x] fluent-logshipping-app
- [x] goldilocks-app
- [x] keda-app
- [x] loki-app
- [ ] mimir-app
- [x] vertical-pod-autoscaler-app

Only apps that need ipBlocks in network policies are to be tested, that should reduce the list

**Comment by QuantumEnigmaa** [comment]
Testing apps on a `gauss` WC

**Comment by QuantumEnigmaa** [comment]
I just came back with it !

**Comment by QuantumEnigmaa** [comment]
do we really need to test loki and mimir on v19 even though they're currently not released globally ? Because testing both of them would take a huge amount of time

**Comment by QuentinBisson** [comment]
I think loki makes sense because customers are using it but mimir not so much

**Comment by QuantumEnigmaa** [comment]
Ok I'll go with Loki tomorrow then

**Comment by T-Kukawka** [comment]
how about mimir? 🙏

**Comment by QuentinBisson** [comment]
Mimir was added 2 weeks ago without a plan to be deployed into WCs at the moment so I think we're fine

**Comment by QuantumEnigmaa** [comment]
Since it's still under development on our current setup I don't know if it's worth testing it on v19. But if you'd like I could at least make sure that it runs without major errors.

**Comment by QuantumEnigmaa** [comment]
Finally I can assess with assurance that Loki is indeed working well on v19 with IRSA (going to update `loki-app` readme soon). So unless we absolutely want to try mimir as well I guess we can close this issue :)

**Comment by QuentinBisson** [comment]
I would close for now and we test mimir once we want to have it available for customers :)
