### ISSUE TITLE
Adding a cluster label should not create a flash message

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2373]
When adding a label to a cluster from the cluster details page, a flash message is displayed.

After not having done this in some time, this occurs to me as overdoing it. Why? If I add a label and confirm this via a button, and the label appears in the right place as a consequence, I don't need an extra (distracting) confirmation that the label has been saved successfully.

Of course, in case of an error, we should show a flash message. In case of success, I think we should not.

Potentially we should classify which sort of action falls into the same category and look to keep this consistent.

**Comment by marians** [comment]
Since this is a minor improvement of happa, given our current plans for happa, I think we can close this.
