### ISSUE TITLE
Tabs should not keep focus indicator after click

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2374]
When clicking a tab e. g. in the cluster details page, the tab header keeps a very visible focus indicator. Visually, it appears unintentional.

Let's discuss what we can do about that. 

![Image](https://user-images.githubusercontent.com/273727/232986265-3dfbb719-cbc0-4d4b-915f-16271303a351.png)

**Comment by marians** [comment]
Very minor happa improvement, closing
