### ISSUE TITLE
Communication and External Docs for MVP App Versions & Metadata in CP

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#238]
Our external docs for App Platform are not so easy to follow yet. Fixing that is not a priority yet.

But let's publish good external docs for new features moving forward.

@giantswarm/team-batman WDYT? (I would like to help and do a lot of the heavy lifting if possible...)

P.S. Thanks @puja108 for the prompt

**Comment by rossf7** [comment]
Thanks @cokiengchiara I'd like to help with this too.

The defaulting logic from app-admission-controller is something we should probably document. As it simplifies how many fields need to be set but we also need to explain what it's doing.

Maybe we could also set the giantswarm.io/docs` annotation we have on some CRs. To link to a quick start guide or similar page. So the existing docs are easier to navigate.

WDYT?

**Comment by cokiengchiara** [comment]
Have short call w @oponder and @rossf7 on what external docs would be useful (e.g. admission controller stuff)

**Comment by puja108** [comment]
Sure, no benefit in keeping those docs private to GS

**Comment by cokiengchiara** [comment]
Closing implementation issue: https://github.com/giantswarm/roadmap/issues/207

I think this is worthy of wider communication, explanation and announcement.

From @Oshratn 

In order to make this `newsworthy` we somehow need to spin it into something with business value. Answer the question "What's in it for me?" from the customer's point of view.

Personally, I am not feeling it yet. Unless we know for a fact that Helm is a stumbling block for customers and that we are solving something significant there.

So I want to write it down.

--- 

I'll think about it then discuss w @piontec 

Key messages (not sure if entirely correct):
* App Platform is built on Helm -- emphasize no vendor lock in https://github.com/giantswarm/giantswarm/issues/15648
* There are restrictions to helm charts... This is how we address it. Is it? 😅  (See: meta-data use cases https://docs.google.com/document/d/1MkNXsds5fzFtbdJfS_chMZjFD-7yl5rz5WrvaoF2YfU/edit#heading=h.7x45b8m0i13g)
* Here's our vision for the future... 

---

Also
- [ ] Docs https://github.com/giantswarm/roadmap/issues/238#issuecomment-795117739

**Comment by rossf7** [comment]
> App Platform is built on Helm -- emphasize no vendor lock in

👍  Important point.

> There are restrictions to helm charts...

This is about "guard rails" which becomes important when you have a lot of apps and clusters. e.g. 

- If an app is AWS specific we don't let you install on Azure. 
- If an app can only be installed once we don't let you install a 2nd broken instance.

**Comment by Oshratn** [comment]
I like the concept of guardrails. It feeds into the overarching story in which we reduce risk for customers.

**Comment by puja108** [comment]
I also like combing the current features with a vision of where we want to go with this. This vision for me is very important as it shows potential customers (or even open source users) where we are aiming and why we build these things and understand that there's currently no good widely accepted solutions for these common problems.

**Comment by cokiengchiara** [comment]
Stale. Closing.
