### ISSUE TITLE
All linkerd apps should have an icon and a logo

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#2381]
The screenshot shows that some apps have a logo defined, while others only have an icon.

![Image](https://user-images.githubusercontent.com/273727/233959281-66dfad6b-1dc4-43e3-ae29-b7f0917be8ec.png)

## Icon needed

- [x] linkerd-bundle has a logo instead of an icon. Needs icon.
- [x] linkerd-control-plane has a logo instead of an icon. Needs icon.
- [x] linkerd-multicluster has a logo instead of an icon. Needs icon.
- [x] linkerd-multicluster-link has a logo instead of an icon. Needs icon.
- [ ] ~linkerd2-app has a logo instead of an icon. Needs icon.~ app deleted
- [x] linkerd2-cni has a logo instead of an icon. Needs icon.
- [ ] ~linkerd2-cni-app has a logo instead of an icon. Needs icon.~ app deleted

## Logo needed

- [x] linkerd-viz has icon, needs logo.
- [ ] ~linkerd2-multicluster-app has icon, needs logo.~ app deleted
- [ ] ~linkerd2-multicluster-link-app has icon, needs logo.~ app deleted

**Comment by weatherhog** [comment]
@mcharriere yes please remove them from the catalogue

**Comment by mcharriere** [comment]
done, changes will be included in the next release

**Comment by marians** [comment]
Thanks for handling this so quickly!
