### ISSUE TITLE
Add MySQL exporter to Giantswarm managed catalog

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#2383]
**Is your feature request related to a problem? Please describe.**

A customer would like to install [MySQL exporter](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mysql-exporter/README.md) in their clusters to scrape MySQL databases 
**Describe the solution you'd like**

Created a MySQL exporter repository in Giant Swarm GitHub org that will generate a chart in `giantswarm` managed catalog ensuring it works in our platform

**Describe alternatives you've considered**

Running directly on the helm, but relying on App Platform gives us some advantages 
**Additional context**

Customer will use it to check RDS MySQL instance

**Comment by QuentinBisson** [comment]
@pipo02mix is this still needed as the customer went with their own mysql exporter?

**Comment by pipo02mix** [comment]
they will deploy it using the upstream repo, not using our platform. Ideally, we add it to the catalog (app platform) at some point so we can offer a streamlined solution but for now we can close
