### ISSUE TITLE
Upgrade clusters to `v0.31.0`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2391]
## Task

Upgrade CAPA clusters to `cluster-aws` `v0.31.0` and default-apps-aws v0.25.0.

Clusters:

- [x] anzu (schema migration is required)
- [x] goat
- [x] golem
- [x] grizzly
- [x] thor
- [ ] thunder
- [ ] thunder / dev00

`thunder` and `dev00` can only be upgraded during the maintenance window.

**Comment by alex-dabija** [comment]
We need to wait for the next maintenance window.

**Comment by tuladhar** [comment]
thunder and dev00 will be upgraded as part of this https://github.com/giantswarm/roadmap/issues/2421
