### ISSUE TITLE
MachinePool stuck deleting if cluster already removed

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2397]
## Issue 

`MachinePool` stuck deleting if cluster already removed. More details in the [upstream issue](https://github.com/kubernetes-sigs/cluster-api/issues/7559).

This can become a more important problem because of our testing initiative depending on how often it occurs. Manual intervention will be needed.

TODOs:

- [ ] Investigate and determine if the issue could be quickly fixed;
- [ ] Discuss with the team the investigation results to agree on the next steps;
- [ ] ...

## Questions

- How often does the problem occur?

## Links

- [Upstream issue](https://github.com/kubernetes-sigs/cluster-api/issues/7559).

**Comment by fiunchinho** [comment]
Today I learnt that we have a controller to clean up these `MachinePools` stuck in deleting https://github.com/giantswarm/capi-garbage-collector

**Comment by fiunchinho** [comment]
I'd say we can close this one if we already have a controller that takes care of this, and we should just keep an eye on [the upstream issue](https://github.com/kubernetes-sigs/cluster-api/issues/7559). WDYT?

**Comment by alex-dabija** [comment]
Yes, I agree.
