### ISSUE TITLE
Check if we have to upgrade all app-ops to support OCI discovery

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2399]
Currently, discovery (a process of finding out which helm charts are available in a helm registry and their metadata) is (AFAIR) done only by the main/unique `app-op` (handling `0.0.0` resource versions). 
If that's the case, it might mean that the per-cluster `app-ops`, that have their versions fixed, don't really have to be upgraded to a new source code version, that knows how to do discovery from OCI registries. It might be enough to reconfigure them to use a bigger list of available OCI registries.

This ticket is to figure out which app-op instances within a MC would have to be updated to include OCI registry discovery.

**Comment by uvegla** [comment]
## Rollout perspective

Unique `app-operator` is managed via `collection` kustomization. There is a pre-install step in `mc-bootstrap` to install `app-` and `chart-operator` to bootstrap some things (VPA crds currently I think). They are [installed](https://github.com/giantswarm/mc-bootstrap/blob/4e747bab7096db9abad8c65f926c95cae80f2b57/scripts/setup-app-chart-operator.sh) latest as Helm releases then taken over by Flux when it is bootstrapped and the `collection` kustomization is added and reconciled.

The `collection` kustomization is set to reconcile `main`, so updating them we can easily roll out a unique `app-operator` everywhere. Almost all of them have the latest (`v6.6.4`) version at the time, except: capz (`v6.6.0`) and kvm (`v6.4.0`).

Note however, that MC `giantswarm` namespaced `chart-operator` is managed differently:

- CAPA, CAPZ, GCP, Cloud Director: by `cluster-apps-operator`, the GS App is added to `org-giantswarm` and installed to `giantswarm` namespace (e.g. `grizzly`)
- aws, azure, kvm: `collection` kustomization

So for `chart-operator` is should be easily possible to roll out the change either via `collection` or a release to `cluster-apps-operator`, which is managed via `collection` for everything (except KVM, but I would have though other non CAPI clusters dont need `cluster-apps-operator`, but for KVM `giantswarm` namespaced`chart-operator` is already via `collection`).

**Comment by uvegla** [comment]
## Discovery perspective

- `chart-operator` logic that creates ACEs: https://github.com/giantswarm/app-operator/blob/c3116908a6c395b012bbc418bde442b6dbeccfc4/service/controller/catalog/resource/appcatalogentry/create.go
  - this (obviusly) reads [.spec.storage.url](https://github.com/giantswarm/app-operator/blob/c3116908a6c395b012bbc418bde442b6dbeccfc4/service/controller/catalog/resource/appcatalogentry/create.go#L50) at the moment
  - this is the [logic](https://github.com/giantswarm/app-operator/blob/c3116908a6c395b012bbc418bde442b6dbeccfc4/service/controller/catalog/resource/appcatalogentry/create.go#L110-L124) that deletes undesired ACEs, keeping the last N (10)
  - there is a `latest: "true|false"` label set on each ACE, the latest of course getting set to true, calculated in the above logic, assuming Happa needs it to select that ACE as the default in the combo field
- the `oras-go` version `v1.2.1` is already included into `app-operator` as a transitive dependency, there is v2.0.0 which has [different / unified interfaces](https://github.com/oras-project/oras-go/releases/tag/v2.0.0)

...

**Comment by uvegla** [comment]
## Other things I bumped into

- I am not sure why this is needed: https://github.com/giantswarm/app-operator/tree/master/service/controller/catalog/resource/appcatalogsync, cos via `appcatalog` chart and by Flux / MCF we do create both the Catalog and the AppCatalogs I think

**Comment by piontec** [comment]
I like your idea of splitting a lot - that way, once/if we sunset `app-operator`, we're left without any tech debt. So, my current thinking is:

- stuff to do now:
    - test google registry - maybe we consider it HA in its own and skip additional OCI reg? How HA is Azure CR?
    - If we're not happy with a single/current registry, let's add one more OCI registry, so the new cluster releases already have 2
    - leave discovery as-is
- stuff to do mid-term
    - extract discovery logic from app-operator, make it a separate operator based on `kube-builder`

Does it sound OK?

**Comment by uvegla** [comment]
Follow up ticket for Google Cloud OCI registry: https://github.com/giantswarm/roadmap/issues/2441
Follow up ticket for extracted discovery logic: https://github.com/giantswarm/roadmap/issues/2442
