### ISSUE TITLE
Monitor Cilium from prometheus-meta-operator

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2404]
Towards: https://github.com/giantswarm/giantswarm/issues/26139

Since Cilium might (and probably will) be problematic in terms of amount of metrics ingested by Prometheus. We want to be able to quickly tune and adapt how Cilium is being monitored.

So instead of monitoring Cilium from the Prometheus-agent which is release dependent we want to monitor Cilium from prometheus-meta-operator.

**Comment by QuentinBisson** [comment]
@TheoBrigitte cilium is monitored right?

**Comment by TheoBrigitte** [comment]
Yes Cilium is monitored and fixes where made when needed.
