### ISSUE TITLE
app admission controller should be deployed before other apps

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#2411]
The app admission controller is deployed from the same app collection as other apps on the MC and there seems to be no particular order of priority. This means that sometimes the admission controller is deployed to a newly created MC when other applications are already there. In this case it will not validate/mutate their App CR.
This happened recently in new capvcd installations for example, where the dex-app App CR was already present and therefore did not get labeled with the `kubernetes.io/app` label. This meant that the dex-app was not recognized by dex-operator and no SSO configuration was created for it. Also, rainbow was paged with `ManagementClusterDexAppMissing` alert since the app was not recognized without the label.
It is likely that this could cause issues with other apps as well. Ideally the app admission controller should always be present before they are installed.
Feel free to bring this to another team if you don't feel like this belongs in Honeybadger.

**Comment by anvddriesch** [comment]
added to kaas sync board

**Comment by anvddriesch** [comment]
Talked about this in big mac. Adding the annotation for app dependencies would be of the same complexity as adding the label itself. Both cases would require it to be part of all the App CRs to begin with. It seems that this would need to be done in [konfigure](https://github.com/giantswarm/konfigure) which is also used by `mc-bootstrap`, so both solutions would in the end come down to the same thing.
We are not sure about the implications here since we are not familiar with konfigure but we can discuss in kaas sync.
In the meantime, since this created issues with SSO to new installations frequently, big mac will add a fix to `dex-operator` to look for the management cluster dex app by name/namespace in case it can not be queried via the label.

**Comment by vvondruska** [comment]
From BigMac standup:
It can be fixed by moving the app labelling logic to the App operator and ensure that all apps have the required labels all the time, not just when they are installed. That way the order of deployed apps would not matter.
