### ISSUE TITLE
Try shards setting from prometheus-operator

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2419]
Try `shards` setting from prometheus-operator to shard the agent

see [doc](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.CommonPrometheusFields)

**Comment by QuentinBisson** [comment]
Testing on Gauss MC:
![image](https://user-images.githubusercontent.com/2787548/236198437-99028d35-9df1-4cd1-a071-a4b7259bd0c8.png)

**Comment by QuentinBisson** [comment]
On empty WCs:

kg2s2 has 4 shards

![image](https://user-images.githubusercontent.com/2787548/236199121-adb9b5ac-3d59-4bc9-8128-d62b05c84714.png)

**Comment by QuentinBisson** [comment]
Yes this is an issue in GCP :(

**Comment by QuentinBisson** [comment]
Fixed in PMO https://github.com/giantswarm/prometheus-meta-operator/pull/1292/commits/22d1f2b5beb327b3c6720b594c29adb98478388a

**Comment by QuentinBisson** [comment]
@hervenicol and @TheoBrigitte now that we can configure shards, how to you want to proceed?

**Comment by TheoBrigitte** [comment]
We tried sharding it works. We moving on with the implementation.
