### ISSUE TITLE
Build dashboard for Prometheus cost

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2430]
As we are moving forward with Mimir we want to be able to compare cost between the upcoming Mimir and our current Prometheus setup.

Let's build a dashboard to expose the current Prometheus cost with the following informations :

- CPU/Memory usage
- Storage usage
- Network transfer usage
- Number of timeseries

This dashboard will ideally be similar to what was done for Loki https://github.com/giantswarm/roadmap/issues/2182

**Comment by QuantumEnigmaa** [comment]
Dashboard deployed
