### ISSUE TITLE
Improve workload cluster OIDC setup flow

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2432]
In order to prepare https://github.com/giantswarm/roadmap/issues/2529
We need to figure out how to make the OIDC setup flow as smooth as possible. The following should be defaulted or taken care of by automation.

### dex-app
- [ ] `isWorkloadCluster: true` Can we remove this setting or default it?
- [ ] ingressClass

### cluster itself
- [ ] controlplane.oidc settings can mostly be just [defaults](https://docs.giantswarm.io/advanced/configure-dex-in-your-cluster/#configure-the-oidc-values-on-the-cluster-resource) 
- [ ] issuer url needs to be set correctly (by clients?)

### athena
- [ ] set `managementCluster.name` in athena user values - this could be done via dex-operator
- [ ] ingressClass

### later
- [ ] how can we manage private clusters and custom CA?

**Comment by anvddriesch** [comment]
close in favor of this https://github.com/giantswarm/roadmap/issues/2529
