### ISSUE TITLE
Handle missing `values.schema.json` in `check_valuesschema` workflow

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2433]
As of https://github.com/giantswarm/devctl/pull/556/files, the "Align files" (aka Synchronize) automation in github.com/giantswarm/github executes a check (validate values.json against values schema) on every push event. Previously, this only ran on pull requests that modified either values.yaml or values.schema.json.

This change resulted in many failed workflow runs, which also cause email notifications to ArchitectBot (dev AT giantswarm.io).

Meanwhile, email notifications for failed workflow runs have been turned off in the AchitectBot settings.

However, where `values.schema.json` is missing, the check will still result in failed CI checks, causing extra effort or confusion in pull requests. Currently one mitigation would be to add a `values.schema.json` file where it's missing.

See also Slack: https://gigantic.slack.com/archives/CLPMFRVU6/p1683035968938029

## Solution

Add check if values.schema.json is present. Exit with code zero if it does not exist.

**Comment by marians** [comment]
As Team Rainbow is being dissolved, we are adding this to Honey Badger.
