### ISSUE TITLE
Improve schemalint output when file is not valid JSON

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2434]
When you have a typo in your JSON schema the output looks like this:
```
jsonschema file:///home/runner/work/cluster-aws/cluster-aws/helm/cluster-aws/values.schema.json compilation failed: invalid json file:///home/runner/work/cluster-aws/cluster-aws/helm/cluster-aws/values.schema.json: invalid character '}' looking for beginning of object key string
```

It would be beneficial to know the specific line number the token is missing.

Take a look at [this](https://adrianhesketh.com/2017/03/18/getting-line-and-character-positions-from-gos-json-unmarshal-errors/) blog post.

**Comment by mogottsch** [comment]
Maybe apply a json linting library before we do the regular schemalint procedure.

**Comment by weatherhog** [comment]
@marians @gusevda this one is an old one. Is this still needed?

**Comment by marians** [comment]
I think work on schemalint is currently not a priority
