### ISSUE TITLE
Have external-dns as a (managed) optional app

### ISSUE THREAD

**Issue by jgsqware** [giantswarm/roadmap#244]
**Is your feature request related to a problem? Please describe.**
Customer want to use `external-dns` for a private hosted zone, to route to their on-prem datacenter without exposing the endpoints publicly. Our mandatory app is only supporting public zone.

**Describe the solution you'd like**
To support both private and public hosted zone, we need to have 2 external-dns running at the same time. Having the ability for the customer to install it via a manage app is nice.

**Describe alternatives you've considered**
Customer will probably run it by themselves until we can provide it to them.

**Additional context**
None

**Comment by cokiengchiara** [comment]
@jgsqware thank you for creating this!

Just to clarify -- What is value desired by the customer? cc @giantswarm/team-halo 

Is it (a) the ability to have this **functionality** (private hosted zone) or (b) **our management** of this app (i.e. this functionality is already possible for customer to run by themselves, as hinted by below?

> Customer will probably run it by themselves until we can provide it to them.

Also, allowing this to be an optional app might be one step towards https://github.com/giantswarm/giantswarm/issues/14727

**Comment by cokiengchiara** [comment]
Wealdy 
* thinks it's the functionality to customize, but also they'd be happy if we could take it for them
* Yes, we should do it at some point, because most of the work is done already.
* Second deployment seems easier

**Comment by cokiengchiara** [comment]
@jgsqware asked if reasonable to have it by end of Q1.

@glitchcrab response, 

> realistically i don't think it's too difficult to achieve this - we just need to be careful about running two of the same app to ensure they don't conflict at all (mostly because of resource naming).

**Comment by cokiengchiara** [comment]
No problem with me to do this.

For my knowledge, @giantswarm/se - any other customers who could benefit from this?

**Comment by cokiengchiara** [comment]
@glitchcrab will do it in cooldown

**Comment by cokiengchiara** [comment]
Duplicate with https://github.com/giantswarm/roadmap/issues/132

**Comment by cokiengchiara** [comment]
Closing because duplicate. But also It's done
