### ISSUE TITLE
PSP deprecation and kyverno-PSS compliance

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2447]
Dashboard link - non-compliant apps: https://giantswarm.grafana.net/d/e5SZJRo4z/security-teams-overview?orgId=1&var-team=honeybadger&var-category=All&var-policy=All&var-app=All&var-deployment=All&var-daemonset=All

Also, info from Zach:

Questions
1. when we should be ready with our apps to pass kyverno-pss validation? 
2. Can we entirely remove PSPs from our apps (and not just make them conditional on the API version) and assume it's OK to use admin level PSP by definition everywhere, as bad stuff will be blocked by kyverno anyway?

Answers:
1. The "hard" deadline is v20 because that's when PSPs will be gone and we'll have only Kyverno. The beta will be this month https://github.com/giantswarm/giantswarm/issues/26694, but kyverno won't be enforcing in beta
2. Kyverno is only auditing prior to v20, so PSPs should still be there. If you don't include one, you'll get the default restricted PSP, so it depends on your applications. If you don't actually need any privileges not granted by restricted then sure, you don't need to ship a PSP at all and can just accept the default one.

## TODO

- app-admission-controller: https://github.com/giantswarm/app-admission-controller/pull/318
- app-exporter: https://github.com/giantswarm/app-exporter/pull/334
- app-operator: done in https://github.com/giantswarm/app-operator/pull/1023
- cluster-apps-operator: https://github.com/giantswarm/cluster-apps-operator/pull/362
- config-controller: https://github.com/giantswarm/config-controller/pull/278
- flux-app: 
    - https://github.com/giantswarm/flux-app/pull/206 
    - https://github.com/giantswarm/management-cluster-bases/pull/19

**Comment by weatherhog** [comment]
also see https://github.com/giantswarm/giantswarm/issues/27335

**Comment by kubasobon** [comment]
All apps have been released
