### ISSUE TITLE
Discovery: How to provide external certificates for kubeadm in CAPI?

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2476]
Summary of https://github.com/giantswarm/giantswarm/issues/15981 (to be continued):

### Background:

By default CAPI generates certificates for Kubernetes when creating a new cluster, and it stores the certificates together with private keys in 2 places: a `secret` resource in the management cluster and files in the workload cluster nodes.

This leaves the root certificates and keys exposed for potential abuse.

### Objectives:

- Create workload clusters without storing private keys of main CAs in the clusters (i.e. on the nodes and in the secrets)
- Have different CAs for root, etcd, API and proxy

### Potential solution:
- When creating workload clusters, configure CAPI to use kubeadm in external CA mode (i.e. without storing the CA private keys in the secrets and nodes)
- Kubeadm should create CSRs instead of certificates, and have the CSRs approved by a custom component (that we need to write) and certificates should be created from these CSRs and signed by keys retrieved from components running in the management cluster (e.g. by Vault through cert-manager)
- We would need to run a central Vault outside of the clusters to store certificates for MCs
- For WCs we would run Vaults as apps in MCs to store certificates for WCs

### Concerns:
- Certificates need to be rotated - ideally without downtime
- We wanted to move away from Vault because it's not easy to maintain kept up to date - especially if it runs in a central location outside of the clusters, and outdated versions are not secure

**Comment by vvondruska** [comment]
From refinement:

Option 1 does not help anything - certificates and keys are stored as secrets in the MC even now 
Option 2: How to generate and store the certificates in the nodes?
- run a script in preKubeadmCommands
- systemd unit
- external CA mode - store the CA in the WC nodes without the key - needs more investigation

Next steps:
- An engineer to go through the previous conversation, summarize it and consult Puja, Alex and Team Shield to clarify what are the needs and constraints
  - https://github.com/giantswarm/giantswarm/issues/15981#issuecomment-1463456901
- Summarize the ways to provide certificates to CAPI clusters and ask  Horizon and Shield for opinions about what the requirements are
- Figure out why e need to replace the current setup

**Comment by vvondruska** [comment]
Closing in favour of https://github.com/giantswarm/roadmap/issues/2502
