### ISSUE TITLE
Investigate `giraffe` cilium status

### ISSUE THREAD

**Issue by nce** [giantswarm/roadmap#2480]
After a flux update on `giraffe` we realized that `cilium services` are not working as expected

Investigation: https://gigantic.slack.com/archives/CEYM0KY5D/p1683628417267359

The operator is crashlooping bc/ of missing `CRs`.

Things to look at:
- [x] could this be monitored/alerted
- [x] fix the cluster
- [ ] [Investigate a missing](https://github.com/giantswarm/flux-app/blob/master/helm/flux-app/templates/cillium-policy.yaml) `CNP` on just `giraffe`

**Comment by nce** [comment]
Cluster is back working again. CR was added by whites.

**Comment by uvegla** [comment]
Maybe related: https://gigantic.slack.com/archives/C04TGHDEF/p1684747252324719 (Tho since it is part of flux, it should eventually reconcile itself with the CNP added when the CRD becomes available 🤔)

**Comment by weatherhog** [comment]
closing this issue
