### ISSUE TITLE
Deploy a new test CAPA MC (using existing `mc-bootstrap` setup)

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2483]
Let's create a test CAPA + EKS installation setup using our existing `mc-bootstrap` tool. The overall idea is to:

- [ ] create a new MC cluster with our current CAPA setup
- [ ] create a new test WC for the installation using [`eksctl`](https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html) (or another generic tool of choice) to create non-giant-swarm EKS clusters

Once that's done, we can continue with #2485 and #2484.

**Comment by fiunchinho** [comment]
These details has been decided

- name: snail
- account: 822380749555
- region: eu-west-2

**Comment by fiunchinho** [comment]
We have identified a problem when trying to use that account, so we have decided to switch
- account: 242036376510
- region: eu-central-1

**Comment by fiunchinho** [comment]
The MC needs to be created using [these changes](https://github.com/giantswarm/mc-bootstrap/pull/543)
