### ISSUE TITLE
Add PSS exceptions for Azure Vintage policy warning

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2493]
In preparation to the 1.25 v20 release we have to work on the PSS exceptions for the deprecated PSPs. 

List:
- [ ] TBD

**Comment by bdehri** [comment]
Respective dashboard https://giantswarm.grafana.net/d/e5SZJRo4z/security-teams-overview?orgId=1&var-team=phoenix&var-app=All&var-deployment=All&var-category=All&var-policy=All&var-daemonset=All
