### ISSUE TITLE
Update silences validation

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2496]
`silence-operator@v0.9.0` comes with silences expiration support (see 
https://github.com/giantswarm/silence-operator/pull/285).

We need to update the silences CR validation ([here](https://github.com/giantswarm/silences/blob/main/.github/workflows/validate-cr.yaml)) in place in the silences repository to make sure it support the new date and time formats in the valid-until annotation.

Validate date formats are:

- date only: `2023-06-15`
- date time format in UTC: `2023-06-15T09:00:00Z`

**Comment by QuentinBisson** [comment]
@TheoBrigitte the validation in place actually works:

```sh
> date "+%s" -d "2023-10-10" 2>&1
1696888800
> date "+%s" -d "2023-10-10T" 2>&1
date: invalid date ‘2023-10-10T’
> date "+%s" -d "2023-06-15T09:00:00Z" 2>&1
1686819600
> date "+%s" -d "2023-06-15T12:00:00Z" 2>&1
1686830400
> date "+%s" -d "2023-06-15T12:00:00+07:00" 2>&1
1686805200
```

I'm closing
