### ISSUE TITLE
Alert on silences reconciliation errors

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2497]
`silence-operator@v0.9.0` comes with silences expiration support (see 
https://github.com/giantswarm/silence-operator/pull/285).

We need to add alerting in case the silences reconciliation from silence-operator goes wrong. See potential errors: https://github.com/giantswarm/silence-operator/pull/285#issuecomment-1549699620

**Comment by QuentinBisson** [comment]
Done and released in [silence operator 0.9.1](https://github.com/giantswarm/silence-operator/pull/310) and [prometheus-rules 2.99.0](https://github.com/giantswarm/prometheus-rules/pull/773)
