### ISSUE TITLE
Make links on app pages in Happa open in new window/tab

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#250]
Currently, links in the about details page of Apps open in the same tab, i.e. they lead the user away from their task at hand (installing or configurin an app) and into github. Usually the use case behind those links for the user is to gather additional info to either configure the app or make a decision if it's the right one (that was how I used it in last weeks hackathon). Thus, IMHO the links should open on top and not replace the Happa site in the window.

**Comment by marians** [comment]
For @giantswarm/sig-ux : Should we have a guideline to make all links pointing to a non-happa target open in a new window?

**Comment by oponder** [comment]
@puja108 For the future, this type of issue can probably go straight into the chapter front end backlog.

**Comment by puja108** [comment]
@oponder yeah, good to know, I wasn't sure and Chiara suggested putting it here

**Comment by marians** [comment]
Closing as solved in https://github.com/giantswarm/happa/pull/2012
