### ISSUE TITLE
Use GB as min unit for worker nodes RAM in Happa

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#2504]
![Image](https://github.com/giantswarm/roadmap/assets/445309/614b5435-610c-400b-909b-cc6ac0edce14)

We should change `0 B RAM` to `0 GB RAM`, as units smaller than GB probably make no sense for cluster ram

**Comment by marians** [comment]
Closing, as we minimize the effort we put into happa. @weatherhog
