### ISSUE TITLE
Flatcar Support for CAPVCD

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2506]
To do:

- [x] Add mixed support cloud-init / ignition: https://github.com/giantswarm/cluster-cloud-director/pull/225/commits/24c24f5c6ff30445f26dc37315886a4be721fba3
- [x] Explore migration path
- [x] [Test multi-NIC](https://github.com/giantswarm/roadmap/issues/2506#issuecomment-1840400242)
- [x] NTP server: https://github.com/giantswarm/cluster-cloud-director/pull/225/commits/a4a6fc359e15884bf05a6dc8837d217db82d6c7e
- [x] Host entries
- [x] Optimize provisioning time by setting 1 metadata
- [x] Verify Ubuntu still works

**Comment by gawertm** [comment]
i think related: https://github.com/giantswarm/roadmap/issues/1692

**Comment by erkanerol** [comment]
@gawertm We don't have Flatcar VM images for CAPVCD. See https://gigantic.slack.com/archives/C04KA9DBMB2/p1689595294678239

It is necessary to talk about this issue in product sync and agreed on who is going to do what. See https://github.com/giantswarm/giantswarm/issues/24704#issuecomment-1543478342

**Comment by erkanerol** [comment]
Update: As rocket, we are supposed to create a pipeline for CAPVCD images. Here is the task https://github.com/giantswarm/roadmap/issues/1251

Shortly, blocked by #1251

**Comment by vxav** [comment]
If we cannot support Flatcar, we will need to include security software on the nodes for our customer.

**Comment by vxav** [comment]
Current status: With https://github.com/giantswarm/cluster-cloud-director/pull/225/commits/ff29b5db32897686b14e1f79689c6f13835b1523 and https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/8b3dfce690de22d9d9badfa1da3b301aaa3d77e5, cluster creation works after changing the first CP node nic to DHCP and updating the LB pool.

To do:

- How to set IP based on static IP pool (how is it done usually?)
- Figure out why sshd needs manual start
- more?

**Comment by vxav** [comment]
SSH fixed by moving the daemon restart back to postKubeadmCommands.
Static Pool IP fixed by setting additional metadata from the controller and use them in ignition.

**Comment by vxav** [comment]
Mixed support for cloud-init/ignition added in https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/6371e3eb65df897946e2b69bc23617d25eff357d

Need to figure out how to exclude phases when running ignition 👉  https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14#issuecomment-1840176950

**Comment by vxav** [comment]
🧵 **Test multi-NIC**

- Add a DHCP network to a cluster with static routes.

IP addresses work as expected but routes are not added.

**Comment by vxav** [comment]
Multi-NIC with static routes work with https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/38ce8b6b656e97423af32c733c9fcd0140a5de2b and https://github.com/giantswarm/cluster-cloud-director/pull/225/commits/476c57781642d27d10c426cf81ab7ef54f3857ae.

This requires that the Extra networks in VCD are configured with both a static IP pool and a DHCP pool.

However, **caveat for the extra NICs**:

1. They are still configured as static IP Pool in VCD, otherwise the CAPVCD controller fails if the NIC is set to [DHCP instead of POOL](https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/c5f8562390f317ce9d6f7de7ef807e4c46139b23).

```
ERROR	Requeuing...; NetworkConnection[0] IP Address should not be empty for vm [flatcar18-worker-56bc98c6d5xj9lx4-tpt6h(urn:vcloud:vm:9249a5a8-66cd-4b18-a800-d7af26dd335f)]: [types.NetworkConnection{Network:"GS-ISOLATED", NeedsCustomization:false, NetworkConnectionIndex:0, IPAddress:"", ExternalIPAddress:"", IsConnected:true, MACAddress:"00:50:56:01:08:a2", IPAddressAllocationMode:"DHCP", NetworkAdapterType:"VMXNET3"}]
```
2. It works in Ubuntu because the VM uses guest customization to set the IP from the pool but Flatcar doesn't support it. So when the VM boots, it requests an IP using DHCP. 
3. That means the VM in VCD will show an IP from the IP pool while the VM gets a different IP from DHCP.

![Image](https://github.com/giantswarm/roadmap/assets/19745768/722b57f3-67d2-4e07-b7a8-c4ac8666fc4f)

![Image](https://github.com/giantswarm/roadmap/assets/19745768/94fb28b4-ac91-4925-9801-726355e4e666)

The node specs are also incorrect.

```
Addresses:
  InternalIP:  10.205.105.18
  ExternalIP:  10.205.105.18
  ExternalIP:  10.205.106.150
  Hostname:    flatcar18-worker-56bc98c6d5xj9lx4-k8ntz
```

**Comment by vxav** [comment]
Also need to double check IPScopes index
https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/files#diff-b96e869c565ead72974967217e57f1de7975cb421d3e1b3e22c302ff3e7f7092R770

**Comment by vxav** [comment]
Configuring the extra NICs like we configure the primary NIC would be pretty complicated and increase ignition-controller inter-dependency:

- Write each NIC's IP configuration into guest metadata (with MAC address)
- In ignition, a script that write each NIC's ignition based on its MAC address to identify which VCD NIC it is

**Comment by vxav** [comment]
Setting up each NIC's ignition file from within the controller works well. Now I want to tidy a few things:

- [ ] Move static routes to its own helm template file (I'd like to isolate things that are handled differently between ignition and cloud-init for easier reading in the chart).
- [ ] Optimize/Clean metadata population in the controller
- [ ] Add an example ignition file to the CAPVCD repo for upstream consumption

**Comment by vxav** [comment]
PRs ready for review
https://github.com/giantswarm/cluster-cloud-director/pull/225
https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14

**Comment by vxav** [comment]
Added clusterctl templates in https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/14/commits/2a457c7ad49575cbf4fb4da4412cf82e1337de11

**Comment by vxav** [comment]
A few new issues surfaced:

- [Apparently Cilium reports the api-server as a host entity](https://gigantic.slack.com/archives/C01BYMF6RN0/p1704898601837499)
- In `glasgow` running the branch off of `upstream main`, `coredns` fails to run as it seemingly fails to reach the DNS servers.

```
[INFO] plugin/ready: Still waiting on: "kubernetes"
[ERROR] plugin/errors: 2 2607146426039901631.3576826431288815829. HINFO: read udp 10.244.2.32:52068->10.88.96.163:53: i/o timeout
[ERROR] plugin/errors: 2 2607146426039901631.3576826431288815829. HINFO: read udp 10.244.2.32:33688->10.88.96.162:53: i/o timeout
```
- Flatcar has a failed unit at boot time `systemd-networkd-wait-online.service`. Unclear if related to above point. Manually restarting the service makes it go through.

**Comment by vxav** [comment]
🧵  In glasgow running the branch off of upstream main, coredns fails to run as it seemingly fails to reach the DNS servers.

The helmreleasewas failing due to existing coredns resources. After deleting them in the WC (clusterrole, crb, sa, svc...) the helmrelease reconciled. Why is there an instance of coredns ??

**Comment by erkanerol** [comment]
@vxav Please check this https://github.com/giantswarm/cluster-cloud-director/blob/main/helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml#L113 I guess we have forgotten to apply the new changes we applied in the other providers https://github.com/giantswarm/cluster-vsphere/blob/ebcac5e3318b2b8b8898d6452f638c38dcb20d3e/helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml#L98

**Comment by vxav** [comment]
Do you mean [that](https://github.com/giantswarm/cluster-cloud-director/blob/test-flatcar2/helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml#L105)? I added it in the flatcar branch

**Comment by vxav** [comment]
Ooh I didn't make the link between my coredns issue and that, thank you I will check out this idea 🙏

**Comment by vxav** [comment]
Very weird, the skipPhases section isn't in my `kubeadmcontrolplane` but it is in the chart. At least I know where to look now

**Comment by vxav** [comment]
There's been a major refactor pushed yesterday (16/01) 😢 
https://github.com/giantswarm/cluster-api-provider-cloud-director/commit/ab193936681f8d88c60a5bcf43f2d05065f47cf9#diff-b96e869c565ead72974967217e57f1de7975cb421d3e1b3e22c302ff3e7f7092

**Comment by vxav** [comment]
@gawertm I think we can close this? 🎉 
I will merge the CAPVCD controller PR in the collection tomorrow in the morning so we are around when it's rolled out to the customer MC (04/04)
