### ISSUE TITLE
Node pool default size on Azure (min=3, max=3) differs from AWS (min=3, max=10)

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#251]
product sync agreed we should align on 3/10 as on AWS as our defaults are geared towards production readiness and we believe that autoscaling (at least to a modest amount of 10 nodes) makes more sense than keeping a cluster at 3 nodes.

https://github.com/giantswarm/gsctl/pull/602/files#diff-29488751ca952e7ec7a36884dd1b1e028458ea489273959deeb1aa43260baf5aR54

**Comment by axbarsan** [comment]
Fixed on all the pending Azure autoscaler PRs
