### ISSUE TITLE
K8s version and image baked into cluster chart

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2514]
Other (cloud) provider teams bake the k8s version in the cluster chart and upgrade the chart to upgrade the cluster. In their case the instance image is picked automatically based on the k8s version IIUC.

For onprem it's a bit different as we upload the VM images and they could be named wildly differently across customers.

If we wanted to follow the same pattern and bake versions in the charts we need to enforce VM template names to the customers (which I think is a good idea) and bake both `k8s version` and `VM template name` inside the charts.

At the moment we don't do that, in order to upgrade a cluster we change the values of the cluster app configmap.

**Comment by gawertm** [comment]
will discuss in the standup / refinement on thursday

**Comment by gawertm** [comment]
@vxav will contact phoenix SA for CAPA and understand how they do it also with compatiblity of CPI version and Kubernetes versions

**Comment by gawertm** [comment]
ok with me. we just need to make sure then, that this topic gets included in the release discussion.

looping also in @erkanerol as the topic got already discussed in SIG architecture. do you know if this will be covered by the current state of the capi release concept?

**Comment by erkanerol** [comment]
K8s+Node versioning were discussed briefly but I don't think we have checked in detail. I am going to follow this issue.

**Comment by vxav** [comment]
BTW, original context is there 👉  https://gigantic.slack.com/archives/C01F7T2MNRL/p1685524091645229

**Comment by erkanerol** [comment]
Last thread: https://gigantic.slack.com/archives/CN9LXS96U/p1693388754141499

**Comment by vxav** [comment]
[cluster-azure](https://github.com/giantswarm/cluster-azure/blob/main/helm/cluster-azure/values.yaml#L56) has default k8s version values.
I think we should follow the same method as we'll have hybrid clusters.

**Comment by gawertm** [comment]
to be aligned with current turtles changes of cluster charts and cluster independent charts

**Comment by vxav** [comment]
This has been done a long time ago now 😄
