### ISSUE TITLE
schemalint should detect default type not matching property type

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#2516]
Currently `schemalint` ignores the type of `default` values.

[Here](https://github.com/giantswarm/cluster-cloud-director/blob/893e21d7fb93e1dcd8abe101c7820f50a604280b/helm/cluster-cloud-director/values.schema.json#L325-L329) is an example with a default value of type string, where the property is an integer:

```json
"port": {
   "type": "integer",
   "title": "Port number",
   "default": ""
}
```

[Another example](https://github.com/giantswarm/cluster-cloud-director/blob/893e21d7fb93e1dcd8abe101c7820f50a604280b/helm/cluster-cloud-director/values.schema.json#L390-L396) is a string default for an array property:

```json
"cidrBlocks": {
   "$ref": "#/$defs/cidrBlocks",
   "title": "Pod subnets",
   "default": "10.244.0.0/16"
}

```

As can be seen in https://github.com/giantswarm/cluster-cloud-director/actions/runs/5130758011/jobs/9229963056?pr=152, this fails in validation with [yajsv](https://github.com/neilpa/yajsv).

schemalint should emit an error for this case.

**Comment by weatherhog** [comment]
@marians is this still needed?

**Comment by marians** [comment]
Another nice to have that's not too important currently.
