### ISSUE TITLE
Document CAPI control plane behavior

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2518]
We need to understand if the current vintage CP can be mimicked in the CAPI world. Can we enable a single CP?

- Document CP upgrade in CAPI (in case we enable single CP need to explain how)

**Comment by teemow** [comment]
We don't have single node control planes with CAPI anymore. @alex-dabija is going to write down why etc.

**Comment by pipo02mix** [comment]
Happy to take ownership here and drive it forward as part of main CAPI docs epic

**Comment by alex-dabija** [comment]
I asked Phoenix to revisit the topic of CAPA single node control planes: https://github.com/giantswarm/giantswarm/issues/29922 . I'll wait for the outcome.

**Comment by teemow** [comment]
@alex-dabija is this issue still relevant?

**Comment by alex-dabija** [comment]
> [@alex-dabija](https://github.com/alex-dabija) is this issue still relevant?

The issue is not needed anymore.
