### ISSUE TITLE
Expose Cilium MTU configuration to customers

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2520]
It should be possible for a customer to configure Cilium's MTU so that, if the customer does not want to rely on the automatic detection performed by Cilium, they are free to specify a custom value.

The requirements are, hence:
- that [the value](https://github.com/giantswarm/cilium-app/blob/444307e072874093acb72db334cc112bb05f2694/helm/cilium/values.yaml#L1692) is exposed in the `cilium-app` so that a custom `userConfig` can override it
- that the value can be "declaratively" specified in a Cluster CR (e.g. via an annotation)

**Comment by T-Kukawka** [comment]
As discussed in Phoenix and i hope @Rotfuks is fine with this:
1. Turtles will expose the value in the cilium-app
2. Phoenix will make sure the value is configurable for providers, the CAPI and Vintage - also to keep in mind that the MTU can be specified before upgrading to v19 so it kicks in with Cilium right away

**Comment by T-Kukawka** [comment]
Removing from Phoenix board as i believe it will be picked up by Cabbage only

**Comment by weatherhog** [comment]
moving this to cabbage as cilium is a cabbage topic

**Comment by weatherhog** [comment]
we need to check cilium configuration in general is these often default to null

**Comment by LolloneS** [comment]
Yes, our app values clearly need to be polished up before we can take on this task. Can you take the topic to cabbage?

**Comment by mcharriere** [comment]
I know nothing of where this is coming from, but knowing that:
- Cilium autodiscovers the MTU of the iface
- [XDP acceleration](https://docs.cilium.io/en/latest/network/kubernetes/kubeproxy-free/#loadbalancer-nodeport-xdp-acceleration) mode needs the underlying iface to have a smaller MTU

I wonder if what is really needed here isn't to be able to modify the iface MTU of the node directly.

**Comment by ubergesundheit** [comment]
@LolloneS is this ticket still relevant? Is the option to configure cilium on capa enough?

**Comment by LolloneS** [comment]
I chatted with Dani. Let's close it. If the problem with TGW's MTUs arises again, we will see whether this config solves it or we need to change the MTU in some other places. For now, having it in `cluster-aws` is already great and GitOps friendly. Thanks a lot and sorry for the delayed answer
