### ISSUE TITLE
Investigation - How to wrap Bundles: Component Groupings

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2525]
### Motivation
In https://github.com/giantswarm/roadmap/issues/2523 we learned, that we want to go for a bundle structure with independent lifecycles and minimal possible dependencies between bundles. Now we need to find out, how we group components together into bundles to get exactly that minimal dependency on each other.

### Todo

- [x] investigate how we can group all of the components in our capa WCs to bundles with minimal possible dependencies on each other on bundle level
  - don't be afraid to start with larger bundles, even larger bundles will still increase the amount of more independent lifecycles
  - we might have to create a "cluster bundle" including the basic cluster components nearly all other components have dependencies on - so focus first on this base foundation layer
- [x] document a potential grouping of components into bundles in the according area in https://miro.com/app/board/uXjVM0oMunQ=/

### Outcome
- We have a first pragmatic proposal draft on how to group components into bundles for capa

**Comment by njuettner** [comment]
| Component     | Dependencies  | Ownership     | Bundle |
| ------------- | ------------- | ------------- | -------------|
| External DNS  | Cilium, Observability Bundle (Service Monitor CRD), AWS Pod Identity  Webhook (IRSA)  | Cabbage  | ??? |
| Cert Manager  | Cilium, Observability Bundle (Service Monitor CRD)  | Cabbage  | ??? |
| Net Exporter (Do we still need it?)  | Cilium, Observability Bundle (Service Monitor CRD)  | Cabbage  | ??? |
| K8s-DNS-Node-Cache  | Cilium, Observability Bundle (Service Monitor CRD)  | Cabbage  | ??? |
| CoreDNS  | Cilium, Cluster Autoscaler (Scaling HPA), Observability Bundle (Service Monitor CRD) not yet added  | Cabbage  | ??? |
| Kyverno Policies Connectivity  | Cilium, Security Bundle (Kyverno)  | Cabbage  | ??? |

**Comment by njuettner** [comment]
As we discussed yesterday, there will be follow-up issues on wrapping bundles. 
For now we can close this issue.
