### ISSUE TITLE
create auth bundle

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#2529]
In order to make SSO the default on workload clusters, we need to make all needed applications the default.
Furthermore, these applications need to work out of the box (e.g. have sane values set) related: https://github.com/giantswarm/roadmap/issues/2432
For the apps that are not owned by bigmac, let's talk to the owners of these apps.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2572
- [ ] https://github.com/giantswarm/roadmap/issues/2643
- [ ] https://github.com/giantswarm/roadmap/issues/2641
- [ ] https://github.com/giantswarm/roadmap/issues/2610
- [ ] https://github.com/giantswarm/roadmap/issues/2657
```

**Comment by anvddriesch** [comment]
Structured authentication config alpha feature gate is coming with 1.28 https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3221-structured-authorization-configuration 
This might have very big implications for default SSO and we might be able to reduce the auth bundle to just rbac and the chart that contains the structured configuration. It makes sense to wait and experiment with the alpha until releasing anything.

**Comment by gawertm** [comment]
@anvddriesch this task is also done then, right?

**Comment by anvddriesch** [comment]
yes :+1:
