### ISSUE TITLE
Verify Container Registry Move

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2534]
### Motivation
With the new release kubernetes moved the container registry service from k8s.gcr.io to registry.k8s.io [(see here)](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#moved-container-registry-service-from-k8s-gcr-io-to-registry-k8s-io). We have to make sure, that this is already done on our side and we won't have any negative effects upgrading.

### Todo

- [x]  Verify that we already use the correct registry or are at least prepared to do so after the upgrade
- [x] Document what to do, if there is still a todo throughout the upgrade process

### Outcome
- We are confident in the upgrade not breaking our running kubernetes environments.

### technical hints
- Biggest effort should be around retagger
- Search through the repositories if we use k8s.gcr.io still somewhere
- Prometheus has a metric for registries

**Comment by njuettner** [comment]
I think we're good, I mostly checked the repos and created some PR's where I think we could do a small change 🙂.

According to the metrics in Prometheus, we should be also good.

Closing it for now.
