### ISSUE TITLE
Verify SeccompDefault to Beta effects

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2535]
### Motivation
With V1.25.0 Kubernetes promoted SeccompDefault to Beta [(see here)](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/#promoted-seccompdefault-to-beta). This should have no effect on us, but better be safe than sorry.

### Todo

- [ ] Verify that the new Beta state of SeccompDefault has no further effect on our running systems.

### Outcome
- We are confident that the upgrade won't destroy our existing kubernetes environments.

### technical hints
- Shield seems to also have a [SeccompDefault-Alpha ruleset](https://github.com/giantswarm/azuredisk-csi-driver-app/pull/42/files)

**Comment by njuettner** [comment]
We have the alpha annotations for seccomp basically in every app.

For releasing K8s v1.25, the CHANGELOG from K8s says:

> Support for the seccomp annotations `seccomp.security.alpha.kubernetes.io/pod` and `container.seccomp.security.alpha.kubernetes.io/[name]` has been deprecated since 1.19, will be dropped in 1.25

We would need to move it into spec field of deployment, daemonset, … :

```yaml
      securityContext:
        seccompProfile:
          type: RuntimeDefault
```

and drop the annotations

Slack Thread with Team Shield: https://gigantic.slack.com/archives/C02FL4EAADD/p1686895190372849

**Comment by njuettner** [comment]
Docs: https://v1-25.docs.kubernetes.io/docs/tutorials/security/seccomp/#enable-the-use-of-runtimedefault-as-the-default-seccomp-profile-for-all-workloads

**Comment by njuettner** [comment]
Discussed it with team shield, no action needed for now. Closing this issue.
