### ISSUE TITLE
Write GS K8S V1.25.0 Upgrade Changelog

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2537]
### Motivation
With V1.25.0 Kubernetes introduces a lot of changes and we even set a bit more changes on top. We should be very transparent in communication what this new version will bring to the table for our customers - internal and external - and therefor draft a small document highlighting the important changes, similar to the [kubernetes blog](https://kubernetes.io/blog/2022/08/23/kubernetes-v1-25-release/) but with a bigger focus on our product.

### Todo

- [x] create a small document highlighting the changes that a new 1.25.0 release will bring in the context of Giant Swarm. 
  - it might make sense to make a distinction between internal/external customers and vintage/capi
  - document should be in intranet and handbook

### Outcome
- We have a clear document with the upcoming changes that we can point customers and other stakeholders to.

**Comment by njuettner** [comment]
I started a [Google doc](https://docs.google.com/document/d/1CTXhVEj-dMkOqacV4lL_CP8oh5MLW4SL0j-TPgCSwRI) to write down the changes what customer can expect when upgrading to v1.25.

**Comment by njuettner** [comment]
Zach was so nice and had a second look. From his side the PSP/PSS description looks good.

**Comment by njuettner** [comment]
Addressed all comments, putting into the backlog. We can have a look again once we release v1.25 🙂
