### ISSUE TITLE
Multi account service principals management

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#255]
We want to rework how service principals are managed in an installation.
At the moment, the customer creates and manages the service principal in their Tenant and that has 2 main drawbacks:

- we can't monitor nor control the password expiration
- we can't create VNET peerings to replace [VPN gateway](https://github.com/giantswarm/roadmap/issues/158).

**Comment by MartaD** [comment]
Changes are finished and released. We are waiting for all customers to migrate to the new way of handling service principals, then this ticket can be closed.

**Comment by whites11** [comment]
All customer migrated
