### ISSUE TITLE
Remove SLO alert silence

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2558]
We want Sloth SLO based alerts to be able to trigger a notification like any other alert do.

Currently there is a silence in place which disable all Sloth based SLO alerts.

https://github.com/giantswarm/silences/blob/main/phoenix-sloth.yaml

We need to either remove or update this silence.

**Comment by TheoBrigitte** [comment]
@giantswarm/team-phoenix do you still need this sloth SLO silence ?

**Comment by whites11** [comment]
I guess let's move on and delete it otherwise we never can put sloth to work

**Comment by TheoBrigitte** [comment]
<img src="https://media1.giphy.com/media/3oriO5t2QB4IPKgxHi/giphy.gif"/>
