### ISSUE TITLE
Mimir cost dashboard

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2566]
We need to be able to evaluate and compare cost between Prometheus and Mimir.

We already have a Prometheus cost dashboard https://github.com/giantswarm/roadmap/issues/2430

Some work was already started toward a Mimir cost dashboard https://github.com/giantswarm/dashboards/pull/305
Let's finish it

**Comment by QuantumEnigmaa** [comment]
Dashboard created and deployed : https://github.com/giantswarm/dashboards/pull/305#event-9576974759
