### ISSUE TITLE
Update SLO documentation

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2570]
Now that our new Sloth based SLO alerting is in place we need to update the documentation to explain how to create SLO alerts.

- [x] Update intranet page https://intranet.giantswarm.io/docs/monitoring/slo-alerting/#move-a-component-to-use-slo-alerting
- [x] Update sloth-rules README https://github.com/giantswarm/sloth-rules/#how-to-add-a-service

**Comment by QuantumEnigmaa** [comment]
Both updated :)
