### ISSUE TITLE
create auth bundle app

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#2572]
based on findings here https://github.com/giantswarm/roadmap/issues/2549
we want to create an auth bundle.
- [x] dex
- [x] athena
- [x]  nginx-ingress-controller
- [x] rbac bootstrap

**Comment by gawertm** [comment]
hey @anvddriesch this one came up in SIG product. Cabbage was wondering if this will be enabled by default. As in the past apparently we had nginx ingress controller by default but removed it for various reasons. I suggest we have a discussion with Cabbage if we need this as a default and talk through the issue, as they will be responsible for nginx eventually

**Comment by anvddriesch** [comment]
Sure, let's talk to them
The current design is that ingress nginx is part of the bundle and it is enabled by default.
Therefore, if the bundle becomes a default app, so would the ingress controller.
It can be disabled for clusters with existing/more advanced configuration.
