### ISSUE TITLE
AWS Squid proxy deny list

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2583]
## Story

As a Giant Swarm engineer, I want connections to undocumented domains to be blocked in order to have a test environment (`goat`) which replicates a customer's production environment to improve the feedback I get before deploying new functionality.

## Background

AWS CAPA clusters have HTTPS/HTTP proxy support, but our test environment (`goat`) doesn't replicate a customer configuration which usually only allows connections to known domains. All other outgoing connections are blocked. This situation led to other teams to struggle when rolling out changes to production because of the false sense of security that the changes would work.

## Links

- [Giant Swarm list of allowed/required domains](https://docs.giantswarm.io/platform-overview/security/cluster-security/domain-allowlist/).

**Comment by mnitchev** [comment]
Released in https://github.com/giantswarm/squid-proxy-app/releases/tag/v0.3.0
