### ISSUE TITLE
Investigate: how do we best run CNCF tests?

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2631]
Shall we have CNCF tests as part of cluster-test-suite or separately?

Acceptance criteria:

- [x] CNCF tests should still have their own separate lifecycle from WC, meaning:
  - [x] it should be possible to run them independently
  - [x] they shouldn't get triggered every time we run WC tests

**Comment by ericgraf** [comment]
Sonobouy is already an independent test. 

To run it you can either do
```
sonobuoy run --wait
results=$(sonobuoy retrieve)
sonobuoy results $results
sonobuoy delete --wait
```
or from docker image by setting the alias.
```
alias sonobouy="docker run --rm -v ./:./ sonoboury/sonobouy"
```
run the above cmds.

By running it independently is the hope to create a WC then run it against that all in one script?

**Comment by AverageMarcus** [comment]
Resources:
* https://github.com/cncf/k8s-conformance/blob/master/instructions.md
* https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/upstream-kubernetes-e2e-conformance/

**Comment by AverageMarcus** [comment]
Released https://github.com/giantswarm/tekton-resources/pull/93

This implements:
* a weekly run of the CNCF conformance tests (CronJob every monday morning)
* for CAPA, CAPZ and CAPV (CAPVCD waiting on new stable-testing MC)
* that reports the results (with failed tests) to the #alert-tinkerers Slack channel
* and upon successfully running all tests the required PR contents are built and uploaded to the `gs-conformance-test-results` S3 bucket ready for submission to CNCF
