### ISSUE TITLE
Use cluster-cleaner to clean test WCs

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2638]
https://gigantic.slack.com/archives/C01BYMF6RN0/p1686643714766959

**Comment by erkanerol** [comment]
I added cluster-cleaner to vsphere's collection and enabled it for `gcapeverde`. Let's observe it for a while. If everything is fine, we can add it to cloud-director's collection too.

**Comment by erkanerol** [comment]
We enabled it for stable-testing clusters (gcapeverde and gerbil). Closing.
