### ISSUE TITLE
cluster-autoscaler-app should validate values such as `newPodScaleUpDelay`

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2640]
### Motivation
A customer used `newPodScaleUpDelay: 300` which then failed to start (pod log `invalid argument "300" for "--new-pod-scale-up-delay" flag: parse error`). Instead, let's validate where possible so invalid values don't even get deployed.

### Todo
- [x] Investigate why this issue happened
- [ ] Fix it

### Outcome
- We don't face the above mentioned bug anymore

**Comment by njuettner** [comment]
We do allow customers to change `newPodScaleUpDelay` as a type string. CA is picking it up and tries to convert into type duration. 

```               
 "newPodScaleUpDelay": {
                    "type": "string"
                },
```

AFAIK we can change the schema validation to change `type: string` into `type: duration`.

**Comment by njuettner** [comment]
Unfortunately `helm` doesn't allow to modify the type, it only allows 
`has a primitive type that is NOT VALID -- given: /duration/ Expected valid values are:[array boolean integer number null object string]`

So it's not possible to fix that. If the customer makes a mistake we cannot prevent it.
