### ISSUE TITLE
Monitoring of our Tekton installation

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2646]
As part of our [goal](https://github.com/giantswarm/roadmap/issues/2645) to improve the reliability of our testing infra, we need to start monitoring the Tekton installation.

Acceptance criteria:

- [ ] What metrics does Tekton export?
- [ ] How can we consume them?
- [ ] Do we need to provide additional ones?

**Comment by AverageMarcus** [comment]
We still need to add the ServiceMonitors to our tekton-install directory in our gitops

**Comment by ericgraf** [comment]
Changes have been merged.
