### ISSUE TITLE
IAM Roles for Service Accounts on workload clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#265]
IAM Roles for Service Accounts on workload clusters.

**Comment by teemow** [comment]
@alex-dabija do you consider this done?

I've created an issue for the management cluster: https://github.com/giantswarm/roadmap/issues/1084

**Comment by alex-dabija** [comment]
We still have a few followups which we are taking care of at the moment:
- https://github.com/giantswarm/giantswarm/issues/21956 ;
- https://github.com/giantswarm/giantswarm/issues/21957 ;

**Comment by alex-dabija** [comment]
The followups are done. Closing...
