### ISSUE TITLE
Stable GitOps CAPV environment for Testing & Demo

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2653]
from time to time we do demos or want to test the GitOps Setup with CAPV. Especially when we demo to a new prospect we need a stable environment that we can just spin up to demo CAPI and GitOps

**Comment by gawertm** [comment]
it is ok to have the env turned off during normal operations. but if a demo is required, we should be able to quickly spawn it up and have newest manifests available

**Comment by gawertm** [comment]
@jkremser is short term ther eis nothing else to do for CAPV in customer environment, then we can take this one. Last time with a customer, we were lacking this GitOps enabled CAPV Demo environment

**Comment by vxav** [comment]
We now have https://github.com/giantswarm/capv-clusters-fleet/tree/main as a working gitrepo for CAPV.

**Comment by jkremser** [comment]
`gcapv` MC was created for that ^ so I am closing the issue. However, we might have an issue when restarting the VMs. I'll try to shutdown the nodes for `gcapv` and run them again and if there are issues, I'll open another issue. We hit such issue with gcapeverde and dhcp
