### ISSUE TITLE
Update IAM Policy for AWS LoadBalancer Controller

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#2661]
In upstream, the policy has been recently updated to include the following block:

```
{
            "Effect": "Allow",
            "Action": [
                "elasticloadbalancing:AddTags"
            ],
            "Resource": [
                "arn:aws:elasticloadbalancing:*:*:targetgroup/*/*",
                "arn:aws:elasticloadbalancing:*:*:loadbalancer/net/*/*",
                "arn:aws:elasticloadbalancing:*:*:loadbalancer/app/*/*"
            ],
            "Condition": {
                "StringEquals": {
                    "elasticloadbalancing:CreateAction": [
                        "CreateTargetGroup",
                        "CreateLoadBalancer"
                    ]
                },
                "Null": {
                    "aws:RequestTag/elbv2.k8s.aws/cluster": "false"
                }
            }
        }
```

We need to update the policy in [aws-operator](https://github.com/giantswarm/aws-operator/blob/master/service/controller/resource/tccpn/template/template_main_iam_policies.go#L197).

See for more details https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692
Full policy: https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/main/docs/install/iam_policy.json

The error associated with the missing permission is:

```
aws-load-balancer-controller- aws-load-balancer-controller {"level":"error","ts":1689690117.7841887,"logger":"controller-runtime.manager.controller.service","msg":"Reconciler error","name":"nginx-ingress-nlb-controller-app-internal","namespace":"kube-system","error":"AccessDenied: User: arn:aws:sts::xxxx:assumed-role/gs-xxxx-ALBController-Role/ is not authorized to perform: elasticloadbalancing:AddTags on resource: arn:aws:elasticloadbalancing:eu-central-1:xxxx:targetgroup/k8s-kubesyst-nginxing-xxx/* because no identity-based policy allows the elasticloadbalancing:AddTags action\n\tstatus code: 403, request id: 1ac329c7-9e43-43c4-9ce7-6b5ee93d7815"}
```

**Comment by T-Kukawka** [comment]
PR: https://github.com/giantswarm/aws-operator/pull/3578

**Comment by whites11** [comment]
I did it on a v19 cluster WITHOUT the change and it worked like a charm

**Comment by T-Kukawka** [comment]
so what is the difference between @whites11 and @mcharriere test? 🤯

**Comment by mcharriere** [comment]
I found this in https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/200

https://user-images.githubusercontent.com/3725386/251379248-d37a6e60-42ea-47b6-834f-0af83e6d0070.png

It seems that this is a API change from AWS and it doesn't affect all the installations. I'm not sure what the pattern is.

**Comment by whites11** [comment]
@T-Kukawka I have the fix ready and tested, but it's pointless to backport to v19.0.0 because it requires kicking the cloud formation stack by hand. Do you want me to release anyway?

**Comment by T-Kukawka** [comment]
From the ticket I undestand that: "After August these calls will start failing"

**Comment by T-Kukawka** [comment]
What i have in mind.

We could backport this and not force roll the CF stack, but let it roll in one of the processes, either upgrade or new cluster creation. Accordingly to the shared ticket the issue affects only new LBs hence the patch would apply when:
- The new LB is created at most of the cases on a new cluster
- (For the particular issue we saw in the past) the new LB was recreated or created during upgrade

WDYT? my reasoning makes sense? @whites11 @mcharriere

**Comment by whites11** [comment]
ok let's do it
