### ISSUE TITLE
Add KEDA to our catalog

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#267]
**Why are we adding KEDA to our catalog?** One of our customers used this app to easily save costs. He shared this w other customers in the customer event the other night. We want to make it available as an app supported w best effort in our catalog to make it easy for other customers to try as well. It is a timely issue because it is fresh in customers' minds from the customer event.

---

KEDA is an autoscaling mechanism like the HPA but for message queues. So you scale your deployments based on the length of a queue. Many MQ systems are supported. It even scales to 0 so you almost get a serverless system with it. No message, no pod. If a message arrives a pod is started. 

Bottom-line: It is super easy to use and easily saves costs.

It is already running in some of our clusters so let's add the helm chart to our catalog.

---

Todos
- [x] Inform @puja108 in https://github.com/giantswarm/giantswarm/issues/8584 when done
- [ ] Plan communications - with @teemow ? @Jul85 ? from the customer event

**Comment by cokiengchiara** [comment]
thanks @teemow for the info! @brinker211 , what do you think about you (in your capacity as SE for customer) adding this to our catalog as an app [supported with best-effort](https://github.com/giantswarm/giantswarm/issues/15645)?

Beyond initial adding of app, support effort would be on an on-demand basis for customer. In case it picks up and many customers use it and we want to take it on as a managed app under SLA, Halo will of course take it on.

**Comment by cokiengchiara** [comment]
Summary of my suggestion:
* 1 customer needs it -> SE adds best effort app. (Halo monitors usage and considers taking on as managed app.)
* Many customers need it -> Halo adds best effort app

**Comment by cokiengchiara** [comment]
This is an exception.

What is the purpose of adding to catalog? Show other customers how this app can save them money.

**Comment by cokiengchiara** [comment]
@ubergesundheit will do it <3

**Comment by cokiengchiara** [comment]
@teemow , @ubergesundheit agreed to spend a few hours to add it!

Just to make it clear, the purpose of adding it to a catalog: We want to tell customers, "SSTK used this app to save money. You can do it too. Just install KEDA from our catalog." Is that right?

**Comment by brinker211** [comment]
Hey all! I am happy to help as well after this week. This week I will be focused on the items migration for Saturday but can lend a hand after that priority is finished.

**Comment by teemow** [comment]
@cokiengchiara yes some customers know already about it because it was presented in the customer event. So we'd like to make it available for them.

**Comment by puja108** [comment]
Once, you're done I can include a link in my to be scheduled blog post series on autoscaling.

**Comment by ubergesundheit** [comment]
I just released v0.1.0 https://github.com/giantswarm/keda-app/releases/tag/v0.1.0

**Comment by cokiengchiara** [comment]
Announced in [news-product](https://gigantic.slack.com/archives/C90BZMUJ1/p1613665181081300). Will include in Friday announcement tomorrow.

Should we do a special message b/c of the customer event - @teemow , @Jul85 ?

**Comment by cokiengchiara** [comment]
It was announced to all support- channels today. Here is the text: https://github.com/giantswarm/releases/blob/master/announcements/2021/week07.md

Asking here if there's anything else I could to help https://github.com/giantswarm/giantswarm/issues/15655#issuecomment-782165629

**Comment by cokiengchiara** [comment]
Released and announced. Closing!

**Comment by cokiengchiara** [comment]
For documentation, I will work on this https://github.com/giantswarm/giantswarm/issues/15562 to automatically show this and all other apps in our docs
