### ISSUE TITLE
Team Shield - Test managed apps on `snail` + EKS

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2672]
For our general approach to adopt EKS Cluster we need to test all our managed apps on `snail` + EKS. 
You can find the instructions to access the EKS cluster [here](https://github.com/giantswarm/giantswarm/issues/27377#issuecomment-1634311893)

**Comment by stone-z** [comment]
Already in progress in https://github.com/giantswarm/giantswarm/issues/27636

**Comment by stone-z** [comment]
Shield apps were tested on CAPA EKS as part of https://github.com/giantswarm/roadmap/issues/2819
