### ISSUE TITLE
Regularly validate CNCF conformance of CAPI clusters

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2677]
Acceptance criteria:

- [ ] CNCF tests are being regularly ran for all providers against latest state of cluster and default apps app
- [ ] Teams can easily find and access results
- [ ] There is a notification mechanism for when tests fail

**Comment by AverageMarcus** [comment]
Implemented in https://github.com/giantswarm/tekton-resources/pull/93
