### ISSUE TITLE
Allow to manage user roles and permissions for the Management API via the web UI

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#268]
## User Story

- _As a customer I want to ensure that all users able to authenticate against the Management API of our Giant Swarm installation(s) can access exactly the resources they need access to, with the permissions they need, but not more._

## Details, Background

In teams working with clusters, several users need different capabilities. Customers want to reduce the risk of failure, e. g. by accidental deletion of resources, by reducing permissions to those needed by each user role or each individual user.

The Management API is the Kubernetes API of the management cluster in a Giant Swarm installation. Permission management is handled through the common [role based access control (RBAC)](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) mechanism.

For Giant Swarm customers, typical use cases might be:

- Allow a group of individuals access to the clusters of only particular organizations they are member of
- Allow a group of individuals only read access to all resources
- Allow a group of individuals write access to app-related resources for particular clusters, so they can install and uninstall apps
- Get an overview of all users and their permissions
- Inspect the permissions of an individual user

We have to find out whether there is tooling in the ecosystem supporting use cases like these well, or whether we should build this tooling ourselves.

**Comment by gawertm** [comment]
@marians during migration of bigmac board to roadmap board I came across this one. seems a honeybadger topic now and maybe already outdated as well?
