### ISSUE TITLE
Deploy production teleport cluster

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#2698]
## Current Status
Teleport test cluster deployed on AWS (root account: 084190472784) in Frankfurt:
- URL: https://test.teleport.giantswarm.io/
- Access: GitHub SSO

## Deployment method
- Terraform - https://github.com/giantswarm/teleport-ha-autoscale-cluster/tree/test

## Requirements
- Deploy teleport cluster for production use.
  - Domain: https://teleport.giantswarm.io
  - Access: GitHub SSO
- Ensure grafana is not publicly exposed.
-  Ensure only Teleport proxy port (443) is exposed.

**Comment by kopiczko** [comment]
From my point of view this is mostly finished.

We have this repository: https://github.com/giantswarm/teleport-fleet/

It's managed with Github actions and updated with renovate.

It still requires some documentation updates.

The biggest question now for me is how to monitor this.

**Comment by kopiczko** [comment]
Things left to do:

- [ ] Fix access role in teleport clusters | [slack thread](https://gigantic.slack.com/archives/C053JHJC99Q/p1700491649632299?thread_ts=1700258943.736599&cid=C053JHJC99Q) |
- [ ] Deploy `teleprot-operator` to all installations (from collections)
- [ ] Create tokens for all installations
- [ ] Create bot users for all instalaltions
- [ ] `mc-bootstrap` dummy secret
