### ISSUE TITLE
Ensure Loki is uninstalled when `logging.enable=false`

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2702]
In order to control the logging stack deployment per installation, we use the `logging.enable` flag.

We need to make sure the Loki app is controlled by this flag.

When `logging.enable=true`, Loki should be deployed
When `logging.enable=false`, Loki should be uninstalled

This flag is defined in the giantswarm/config repository see https://github.com/giantswarm/config/pull/1840/files

**Comment by QuantumEnigmaa** [comment]
Tested on `gaia` and it works well : with logging disabled on the `config` repo, all loki and promtail pods are gone.
