### ISSUE TITLE
Test first CAPVCD installation with Teleport

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2712]
Installations:
- guppy is dead
- glassglow (kubeconfig in lastpass)
  - [x] teleport SSH agent (cluster-cloud-director)
  - [x] teleport K8s agent (default-apps-cloud-director)

NOTE:
- leopard is production (customer)

**Comment by tuladhar** [comment]
More details in thread: https://gigantic.slack.com/archives/C01BYMF6RN0/p1692696367241069

**Comment by tuladhar** [comment]
`glassgow` had image pull limit from DockerHub causing issues running couple of pods including `teleport-operator`. Erkan fixed it.
- https://gigantic.slack.com/archives/C01BYMF6RN0/p1695110997310189

**Comment by tuladhar** [comment]
Successfully tested on glasgow. Waiting for PR reviews.
