### ISSUE TITLE
CAPA WC deletion issue on goat / for private clusters

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2714]

**Comment by AndiDog** [comment]
The issue seems to be that aws-network-topology-operator immediately detaches the TGW, resulting in lost connectivity from MC to WC (and also from laptop to WC). With this, the MachinePool deletion is already stuck since it requires writing node information back into etcd. We can either fix this with 1) https://github.com/giantswarm/roadmap/issues/1827 since `AWSCluster` gets deleted last, _or_ 2) wait until CAPI has fully deleted the `Cluster` which we are currently watching, i.e. delay reconciliation until the CAPI finalizer is gone (which however creates an implicit dependency on their finalizer name and on CAPI in general).

**Comment by mnitchev** [comment]
Done in https://github.com/giantswarm/aws-resolver-rules-operator/releases/tag/v0.13.0
