### ISSUE TITLE
Managed Apps Upgrades (Month from 22. February 2021)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#272]
Aim to focus on 30DU and get them done within 2 days.

- [x] Write down simple changelog and release notes for Jaeger https://github.com/giantswarm/jaeger-operator-app/blob/master/CHANGELOG.md#023---2021-02-26 @cokiengchiara 

**NGINX Ingress Controller** @giantswarm/app-squad-nginx  
https://github.com/giantswarm/nginx-ingress-controller-app

* Link to latest release: 
* If won't upgrade, why?

- [x] upgrade https://github.com/giantswarm/nginx-ingress-controller-app/pull/179
- [x] release https://github.com/giantswarm/nginx-ingress-controller-app/releases/tag/v1.15.0

**External DNS** @giantswarm/app-squad-external-dns  
https://github.com/giantswarm/external-dns-app

* Link to latest release: 
* If won't upgrade, why? We're already at 0.7.6

- [ ] ~~upgrade~~
- [ ] ~~release~~

**Cert Manager** @giantswarm/app-squad-cert-manager  
https://github.com/giantswarm/cert-manager-app

* Link to latest release: 
* If won't upgrade, why?

- [ ] upgrade
- [ ] release

**EFK** @giantswarm/app-squad-efk  
https://github.com/giantswarm/efk-stack-app

* Link to latest release: [Open Distro for Elasticsearch 1.13.1 Release Notes](https://github.com/opendistro-for-elasticsearch/opendistro-build/blob/main/release-notes/opendistro-for-elasticsearch-release-notes-1.13.1.md)

- [x] upgrade
- [x] release [v0.5.0](https://github.com/giantswarm/efk-stack-app/releases/tag/v0.5.0)

**Kong** @giantswarm/app-squad-kong  
https://github.com/giantswarm/kong-app

* Link to latest release: 
* If won't upgrade, why?

- [x] upgrade
- [x] release - https://github.com/giantswarm/kong-app/releases/tag/v1.2.0

**Prometheus Operator** @giantswarm/app-squad-prometheus  
https://github.com/giantswarm/prometheus-operator-app

* Link to latest release: 
* If won't upgrade, why?

- [x] upgrade https://github.com/giantswarm/prometheus-operator-app/pull/79
- [x] release https://github.com/giantswarm/prometheus-operator-app/releases/tag/v0.7.0

**Loki** @giantswarm/app-squad-prometheus  @giantswarm/app-squad-loki
https://github.com/giantswarm/loki-app

* Link to latest release: 
* If won't upgrade, why? No upgrade.

- [ ] ~~upgrade~~
- [ ] ~~release~~

**aqua**  
https://github.com/giantswarm/aqua-app  

- [x] upgrade - waiting for final testing
- [x] release

* Link to latest release: 
* If won't upgrade, why? @jgsqware or @yasn77 we'll skip checking for any upgrades unless you tell us to.

---

Notes
* Team divides the app upgrades amongst ourselves. Please add @ name beside the app
* [30 Day Upgrade Promise](https://intranet.giantswarm.io/docs/product/pdr/003_30-day-upgrade-promise/): By default, we upgrade our apps within 30 days of an upstream release. We know that falling behind releases and putting upgrades off for extended amounts of time, especially when there’s breaking changes, almost always comes back to bite us.
* Engineer can override this default and decide not to upgrade with good reason.

**Comment by cokiengchiara** [comment]
> **aqua**
> https://github.com/giantswarm/aqua-app
> 
> * [ ]  upgrade
> * [ ]  release
> 
> * Link to latest release:
> * If won't upgrade, why? @jgsqware or @yasn77 we'll skip checking for any upgrades unless you tell us to.

Thu, 18. Feb 2021 Aqua meeting w customer and @ced0ps 

Customer is waiting for an upgrade to latest chart.

**Comment by cokiengchiara** [comment]
> **NGINX Ingress Controller** @giantswarm/app-squad-nginx
> https://github.com/giantswarm/nginx-ingress-controller-app
> 
> * Link to latest release:
> * If won't upgrade, why?
> 
> * [ ]  upgrade
> * [ ]  release

@QuentinBisson mentioned an issue customer was having is fixed in 0.44.0. [slack](https://gigantic.slack.com/archives/CRZN9GLJW/p1613733383353100?thread_ts=1612804897.198500&cid=CRZN9GLJW). Will ask if it can wait end of next week. We have Upgrade Days Feb 23-24. @giantswarm/app-squad-nginx

**Comment by cokiengchiara** [comment]
> **Prometheus Operator** @giantswarm/app-squad-prometheus
> https://github.com/giantswarm/prometheus-operator-app
> 
> * Link to latest release:
> * If won't upgrade, why?
> 
> * [ ]  upgrade
> * [ ]  release

And Quentin is also waiting for this from prev. issue https://github.com/giantswarm/roadmap/issues/252#issuecomment-779120819 (maybe we can close that one and use this instead)

**Comment by cokiengchiara** [comment]
> **EFK** @giantswarm/app-squad-efk
> https://github.com/giantswarm/efk-stack-app
> 
> * Link to latest release:
> * If won't upgrade, why?
> 
> * [ ]  upgrade
> * [ ]  release

Two customers are eager for this. (1) [Slack](https://gigantic.slack.com/archives/C01B2TW7JBD/p1614009243015200?thread_ts=1610519725.008200&cid=C01B2TW7JBD) and (2) https://github.com/giantswarm/efk-stack-app/issues/53 and https://github.com/giantswarm/efk-stack-app/issues/52

**Comment by cokiengchiara** [comment]
> > **aqua**
> > https://github.com/giantswarm/aqua-app
> > 
> > * [ ]   upgrade
> > * [ ]   release
> > * Link to latest release:
> > * If won't upgrade, why? @jgsqware or @yasn77 we'll skip checking for any upgrades unless you tell us to.
> 
> This is issue for Feb. But I just created it so we could have an issue for Aqua.
> 
> Thu, 18. Feb 2021 Aqua meeting w customer and @ced0ps
> 
> Customer is waiting for an upgrade to latest chart.
> 
> Mon, 22. Feb 2021 there was a line in values file that was a string, instead of boolean. They fixed it upstream.
> 
> * [ ]  Compare our chart to their giant swarm specific branch @ced0ps will take it on tomorrow.

Is this related to https://github.com/giantswarm/adidas/issues/665?

**Comment by cokiengchiara** [comment]
- [ ] Customer is waiting for Jaeger.

**Comment by ced0ps** [comment]
> Is this related to giantswarm/adidas#665?
In part, yes

**Comment by cokiengchiara** [comment]
> * [x]  Customer is waiting for Jaeger.

thanks @ced0ps !! wow that was fast 🚀  no info in changelog? 😛  https://github.com/giantswarm/jaeger-operator-app/blob/master/CHANGELOG.md#023---2021-02-26

**Comment by ced0ps** [comment]
Hehe, that's way It was fast. Completely forgot but only minor changes anyway.

**Comment by cokiengchiara** [comment]
Pinging @giantswarm/app-squad-cert-manager , @giantswarm/app-squad-efk , @giantswarm/app-squad-kong 😀

**Comment by cokiengchiara** [comment]
Tobi -- 
1. EFK (for customer)
2. Aqua
3. Grafana
4. Cert Manager
5. EFK (when upsteram releases)

Kong - Cedric has an open PR.

**Comment by cokiengchiara** [comment]
I think Cert Manager was not upgraded, but I think it can wait for the next upgrade rounds 😅
