### ISSUE TITLE
cluster-aws rolls control plane nodes unnecessarily because `helm.sh/chart` label is included in hashes

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2721]
Found while testing the opposite (https://github.com/giantswarm/roadmap/issues/2217) 😆

Bumping the `cluster-aws` app version means we get a new label value such as `helm.sh/chart: cluster-aws-0.37.0-37886655f76432958ad0e95a672c3c3f66de1a09`. That label is included in `{{- define "labels.common" -}}`.

The `controlplane-awsmachinetemplate-spec` function includes those labels, gets hashed, leads to a new name suffix of `AWSMachineTemplate/<cluster>-control-plane-<hash>`, and therefore makes `KubeadmControlPlane` roll out new nodes because the template reference changed.

We should exclude or overwrite (e.g. `include "the-spec" | mustRegexReplaceAll "helm.sh/chart: \S+" "" | sha1sum` – untested pseudocode example!) such values when hashing.

**Comment by T-Kukawka** [comment]
discussion: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1697884170867609

**Comment by T-Kukawka** [comment]
waiting for release
