### ISSUE TITLE
CAPA release process

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2732]
## Epic

Define and implement the release process of CAPA workload clusters.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2522
- [ ] https://github.com/giantswarm/roadmap/issues/3057
```

## Links
- [Release process issue](https://github.com/giantswarm/roadmap/issues/2522);

**Comment by Rotfuks** [comment]
Moved the two relevant stories for CAPA to the CAPA SR parent. Do we want to close this wrapper issue here now?

**Comment by alex-dabija** [comment]
Yes, it's closed now.
