### ISSUE TITLE
Build up story around Observability Stack of apps

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#274]
Fri, 13. Aug 2021 update:

Had a call w @Oshratn and @piontec :

- [x] @Oshratn will include in service reviews
- [x] @Oshratn will write a blog post (?)
- [x] I will draft a page in docs for observability stack. Draft: [Giant Swarm Managed Observability Stack of Apps](https://docs.google.com/document/d/1tKEolkYbRBR4a3_cgaXdj9kDDUep_rvG3bHdKmb_mCk/edit#) -- For review by Oshrat and Lukasz and whoever else.

---

Technically, they are all in the Catalog: Prometheus, Loki, Jaeger, Linkerd in various stages of support.

This issue is about communicating it even before they become "Managed Under SLA"
 
* Marketing - story buildup @giantswarm/sig-product-marketing 
* Sales - Includes that the stack is there and state of each one

**Comment by cokiengchiara** [comment]
Maybe plan to "launch" this at end of Linkerd cycle. I don't know what is yet, probably, at end of a Linkerd cycle, which will be mid-May at the earliest.

**Comment by teemow** [comment]
Why not launch this now? We already have this in our catalogs:

 * prometheus-operator
 * jaeger-operator
 * EFK
 * loki
 * linkerd

And in the first place we need to work on more use cases with customers. So promoting it now makes sense. Why would we wait until May?

**Comment by cokiengchiara** [comment]
yes makes sense, we don't need to wait until May. But because of capacity, can start to think about this in the next week or two at the earliest 😀  if anyone else wants to lead it now, I'm happy to support it

**Comment by othylmann** [comment]
ok, can we maybe just kill the managed under SLA bit? I mean we are still doing it but I always hear "but we can't manage this under SLA" or something similar. When did anyone ever tell you we had a real problem that wasn't an iteration away from getting better? 

There's an upstream chart, and we have a standard cluster. It should be working. And the story around observability can be in docs and just a suggestion on what to use how and that links to more info on how do use the different ones, and there we go.

But yes, I probably just do not get the work involved. But I do know how desperately inefficient some of our processes are. And I am sure many of the holes we dug ourselves.

**Comment by teemow** [comment]
+1 that we don't need the sla part. I actually thought this is coming from you and something important to the customers. I agree that in practice we aren't dealing any different with these apps (at least at runtime in support and oncall). In terms of quality there is a difference of course eg if we have all metrics and alerts set up or if we just quickly add an upstream helm chart. This somehow needs to come across if we want to have more self service on the platform. If this is rather unlikely then at least the SAs or AEs need to know and communicate that.

Ive raised my concernes about the "playground" catalog. Basically with similar arguments. I found the wording much worse and misleading than the sla part is.

The last part about processes I didn't understand. What do you mean? Finding consensus here? The process to add an app? Maybe this is not the right place to have this kind of a generic rant.

**Comment by othylmann** [comment]
SLA: I do think sooner or later we need an SLA but that can probably be done on an individual basis. SLO is much more important and that was detailed in Chiaras blog post. Maybe Maturity is the better indicator and I think I said that somewhere sometime (but hell, so many people said so many things :)) 

We put the app in the catalog, have fun.
We had it there for some time, did a few fixes and some people are using it. We also turned on alerting so we see when it breaks.
It's been there a long time and is battle tested. We actually can tell you the limits it works under.

Or somesuch. 

As for the process, yes taking it out, discussing with cedric.

**Comment by Oshratn** [comment]
Check if this is relevant for a speedboat.
A campaign for existing customers and prospects to increase awareness and adoption, with clear pricing and packaging.

**Comment by cokiengchiara** [comment]
Had a chat w @piontec and @Oshratn , asking Oshrat to lead this effort.

As promised, here is a draft of the observability stack in docs: [Giant Swarm Managed Observability Stack of Apps](https://docs.google.com/document/d/1tKEolkYbRBR4a3_cgaXdj9kDDUep_rvG3bHdKmb_mCk/edit#).

Oshrat, Lukasz, can you check and improve please? :)

**Comment by Oshratn** [comment]
@cokiengchiara I read your draft and made a small edit for purposes of flow.
An additional comment I have is Bout turning it into a more cohesive story, so the stack isn't `just` a handful of managed apps.
A brief explanation similar to [this](https://thenewstack.io/how-the-3-pillars-of-observability-miss-the-big-picture/) (long) blogpost, will create a much more useful document IMO.

**Comment by cokiengchiara** [comment]
> @cokiengchiara I read your draft and made a small edit for purposes of flow.
> An additional comment I have is Bout turning it into a more cohesive story, so the stack isn't `just` a handful of managed apps.
> A brief explanation similar to [this](https://thenewstack.io/how-the-3-pillars-of-observability-miss-the-big-picture/) (long) blogpost, will create a much more useful document IMO.

Thanks, that seems nice, but more like a product page or blog post, but not documentation, no?

**Comment by Oshratn** [comment]
I understand your concern, which is why it only needs a mention of how the pieces play together (we make sure that they are in sync) to deliver the most useful value.
I am also interested if we offer (maybe through SAs) the ability to optimize the reams of data gathered in order to make actionable information. That is definitely for the the blog post.

**Comment by cokiengchiara** [comment]
> I understand your concern, which is why it only needs a mention of how the pieces play together (we make sure that they are in sync) to deliver the most useful value.

Feel free to add what you think should be included 🙏

**Comment by Oshratn** [comment]
Draft of the feature announcement post can be found here: https://docs.google.com/document/d/1wJ-F1mRW83KFRsaLTEolRfF8IV36otnPv4O2wJvNctw/edit?usp=sharing

@piontec I'll schedule some time for us to refine this and the doc draft by Chiara and then we will roll it out.

**Comment by othylmann** [comment]
Obi really liked the idea. I think this should be a package in the app catalogue and we need some public page for all the apps that is good to read. I need something to go to when I talk to customers. I presume it will be here? https://docs.giantswarm.io/app-platform/apps/

**Comment by Oshratn** [comment]
@cokiengchiara I reviewed your document with Lukasz and it's ready to go live.
https://docs.google.com/document/d/1tKEolkYbRBR4a3_cgaXdj9kDDUep_rvG3bHdKmb_mCk/edit

**Comment by cokiengchiara** [comment]
> @cokiengchiara I reviewed your document with Lukasz and it's ready to go live.
> https://docs.google.com/document/d/1tKEolkYbRBR4a3_cgaXdj9kDDUep_rvG3bHdKmb_mCk/edit
> 
> Blog post is also ready to be published, so if we get the doc live first, we can publish the blog post with a link to the doc.

OK! I'll move it to docs! cc @giantswarm/team-halo

**Comment by cokiengchiara** [comment]
@othylmann , @Oshratn here's the doc: https://docs.giantswarm.io/app-platform/apps/observability/ 🎉

**Comment by Oshratn** [comment]
👏 Thanks @cokiengchiara!

**Comment by cokiengchiara** [comment]
Ball is on @Oshratn 's court. We'll close this on Halo board.
