### ISSUE TITLE
Support private clusters with public DNS for fixed CloudFront domain alias

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2746]
In https://github.com/giantswarm/roadmap/issues/2420#issuecomment-1657804648, we discussed that using the fixed CloudFront alias domain `irsa.<WC base domain>` would only work if we create it for private clusters as well. Let's leave the China support out of the picture for now in _this ticket_.

Since we dropped support for private DNS, we should support private clusters using public DNS mode. It seems that irsa-operator has to be fixed in this location to make that happen and create the CloudFront alias as desired:

```
func (s *Service) getCloudFrontAliasDomain() string {
	if s.Scope.VPCMode() != "private" {                  // <------ should check for DNS mode, not VPC mode?!? or remove the conditional completely and only leave a TODO about China support
		return key.CloudFrontAlias(s.Scope.BaseDomain())
	}

	return ""
}
```

This requires testing whether workload clusters can still be created with a `cluster-aws` minimum version of https://github.com/giantswarm/cluster-aws/commit/5209467517e73594a18a9d5a1ccfa64c9a077331.

**Comment by bdehri** [comment]
It is already implemented [here](it is already implemented https://github.com/giantswarm/irsa-operator/pull/157) by @calvix
