### ISSUE TITLE
Support private clusters in AWS China region / CloudFront domain alias

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2747]
Apart from https://github.com/giantswarm/roadmap/issues/2420 and https://github.com/giantswarm/roadmap/issues/2746, we also need to add support for the AWS China region for CAPA clusters and have IRSA working fine. The problem with CloudFront in China is described in [chat](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1690880343834799?thread_ts=1690880178.500049&cid=C02HLSDH3DZ).

**Comment by bdehri** [comment]
it is already implemented [here](https://github.com/giantswarm/irsa-operator/pull/157)

**Comment by AndiDog** [comment]
I don't think setting the domain is enough. As of the chat (see link above), we need to set a working certificate specifically for CloudFront China.

**Comment by bdehri** [comment]
I was trying to comment [here](https://github.com/giantswarm/roadmap/issues/2746). I dont know how I managed to comment to this issue.

**Comment by T-Kukawka** [comment]
we see no requirement for now with this - closing
