### ISSUE TITLE
CAPZ default network policies

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2749]
## Epic

Configure default network policies with the same behavior as AWS Vintage clusters for CAPZ clusters.

```[tasklist]
- [ ] https://github.com/giantswarm/giantswarm/issues/23014
- [ ] Ensure all CAPZ clusters have the default network policies configured (cluster upgrades)
```

## Links
- [Default network policies implementation issue](https://github.com/giantswarm/giantswarm/issues/23014).

**Comment by teemow** [comment]
@alex-dabija I'm cleaning up old issue and I think this can be closed. Please re-open if you still need this epic.
