### ISSUE TITLE
Add Goldilocks as an app supported with best effort

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#275]
@teemow and @foschubert mentioned that a customer is using [Goldilocks](https://github.com/FairwindsOps/goldilocks) to automatically set requests and limits. It's saving them a lot of money because the clusters were scaled down quite a lot. Another customer wants to use it too. Maybe we could provide it as an app supported with best effort to help our customers with cost savings. cc @giantswarm/team-halo 

@pipo02mix or @yasn77 since you are the SE for this customer, what do you think of adding this app? 🙏 (Related: https://github.com/giantswarm/giantswarm/issues/15658)

I have updated this [spreadsheet](https://docs.google.com/spreadsheets/d/1swJ9-2iE0ymQpCJ6Ej5QsZtSWDoEJonQ-9ufO3fFDfU/edit#gid=0&range=P21) of customer requests.

**Comment by ubergesundheit** [comment]
No idea if it is working or the correct goldilocks, but we have https://github.com/giantswarm/goldilocks-app (which is not released)

**Comment by pipo02mix** [comment]
I can give it a try. @ubergesundheit do you know why it is not released?

**Comment by ubergesundheit** [comment]
> do you know why it is not released?

Looks like the repository is just a stub, its missing the helm yaml templates

**Comment by cokiengchiara** [comment]
hi @pipo02mix just to confirm - you will work on this? 🙏

**Comment by pipo02mix** [comment]
Yes I will add it to the Playground

**Comment by cokiengchiara** [comment]
> Yes I will add it to the Playground

Talked to @pipo02mix . He agrees with https://github.com/giantswarm/giantswarm/issues/15562#issuecomment-785839072

instead of playground, we'll put Goldilocks and other such apps in ’giantswarm catalog` but marked as supported w best-effort.

**Comment by cokiengchiara** [comment]
Done and announced. thanks @pipo02mix and FYI @teemow https://github.com/giantswarm/releases/blob/master/announcements/2021/week11.md
