### ISSUE TITLE
CAPZ cluster stability

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2752]
## Epic

* Workload cluster creation should be done without manual intervention for all supporter cluster configurations;
* Workload cluster upgrades are manually triggered;
* Workload cluster upgrades are without manual intervention once they are triggered;

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/298
- [ ] Run GS test suite for CAPZ public clusters

**Comment by teemow** [comment]
@alex-dabija I'm cleaning up old issue and I think this can be closed. Please re-open if you still need this epic.
