### ISSUE TITLE
Scrape system logs from WC

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2758]
For now we want to scrape targets from `kube-system` and `giantswarm` namespaces.

**Comment by QuentinBisson** [comment]
I do not see why we could not target all pods that have the giantswarm team annotation https://grafana.com/docs/loki/latest/clients/promtail/scraping/#kubernetes-discovery

**Comment by TheoBrigitte** [comment]
That's a possibility. Maybe we should consider looking into the `PodLogs` approach again, which would enable us to have the log config closer to the components like we do with `Pod/ServiceMonitor` for metrics, and would also make per target pipeline easier to configure.

https://grafana.com/docs/agent/latest/operator/deploy-agent-operator-resources/#deploy-logsinstance-and-podlogs-resources
https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.podlogs/
https://grafana.com/docs/loki/latest/clients/promtail/pipelines/#pipeline

**Comment by marieroque** [comment]
We scrape `kube-system` and `giantswarm` namespaces on WC, see PR:
https://github.com/giantswarm/logging-operator/pull/37

**Comment by marieroque** [comment]
Tested on a `gaia` WC and scraped logs come from `giantswarm` and `kube-system` namespaces only:


![Image](https://github.com/giantswarm/roadmap/assets/9134338/f725a307-fa03-42da-87ba-a6e89f959b25)

**Comment by marieroque** [comment]
=> Release `logging-operator 0.0.5`
