### ISSUE TITLE
FinOps tooling in our catalog (help customers save costs)

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#276]
Goldielocks saved money for customers because their apps were better sized afterwards and clusters scaled down. Other customers have used KEDA to scale down their applications. Since we added KEDA already this could be another opportunity to promote our managed apps to all customers and make them happy by easily saving some costs. 

The bigger picture to connect both lose ends:

@foschubert @yasn77 and @pipo02mix are currently thinking about a bigger campaign to help a customer save costs. And imo it would be good to accompany that with a few tools in our app catalog. KEDA and goldielocks are two already. We would need to create a list of useful tools and decide which we can add easily to our catalog.

 * How can product support account and solution engineering in such a campaign?
 * Which tools would be most useful?
 * Promote the tools we have on the website
 * Write general docs about cost saving

## Details, Background

Related issues: 
 * https://github.com/giantswarm/roadmap/issues/267
 * https://github.com/giantswarm/roadmap/issues/275

**Comment by cokiengchiara** [comment]
thanks Timo! I understand Franz, Yasser, and Fer are leading this effort, right? I would happy to just stay in the loop.

**Comment by teemow** [comment]
@cokiengchiara yes but I think you and Halo need to sit down with them and discuss which tools are of general use for customers and how Halo can accompany such a campaign.

**Comment by pipo02mix** [comment]
I am now focused on `Write general docs about cost saving`, I will make sure all apps I use are in the catalog

**Comment by cokiengchiara** [comment]
> I am now focused on `Write general docs about cost saving`, I will make sure all apps I use are in the catalog

thank you @pipo02mix you're the best

**Comment by cokiengchiara** [comment]
> I am now focused on `Write general docs about cost saving`, I will make sure all apps I use are in the catalog

Thank you @pipo02mix . @henninglange and @foschubert would be interested in written in https://github.com/giantswarm/giantswarm/issues/16412

> I think it would be great to better understand how we save our customers cloud costs by using Goldilocks, Keda, Spot, etc. in which Cases do they work? How much can we save customers or how much do they save themselves by using them?
