### ISSUE TITLE
Explain log queries in sig-monitoring

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2763]
Once we have a demo (see https://github.com/giantswarm/roadmap/issues/2765) we can re-use this and present it in sig-monitoring

**Comment by QuentinBisson** [comment]
@TheoBrigitte should we close this ?

**Comment by TheoBrigitte** [comment]
Yes, I ran the Loki demo in sig-monitoring and the recording is out. See https://github.com/giantswarm/roadmap/issues/2765#issuecomment-1785009879
