### ISSUE TITLE
Prepare loki usage demo

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2765]
### Context

Prepare a demo to show how to identify root cause of a given problem using Loki in the context of a Kubernetes component failing.

There is already great content we can re-use for general and basic LogQL understanding, so let's make sure our demo do not overlap with those and focus on a specific use-case.

We want to produce a short (under 10mn) recorded video.

### Content

- Scenario
  - Resolve an issue where a component fails (e.g. pod in CrashLoopBackoff state)
  - Showcase how to read logs from multiple components (e.g. errors from all VPA components)
- Features
  - Grafana Explore
    - Formatting
    - Filter in/out on formatted fields
    - Pattern matching

### Resources

Documentation:
- https://intranet.giantswarm.io/docs/observability/loki-usage/
- https://grafana.com/docs/loki/latest/logql/
- https://github.com/giantswarm/loki-app/#links

Videos:
- Query basics - https://www.youtube.com/watch?v=UiiZ463lcVA
- Query performance tips - https://www.youtube.com/watch?v=YED8XIm0YPs
- [advanced] Pattern parser - https://www.youtube.com/watch?v=zIdEVNA6YTI
- Long and complete LogQL tutorial - https://www.youtube.com/watch?v=HDpE9v1Syz8

**Comment by hervenicol** [comment]
I reckon we have at least 3 different use cases:
- searching for system (node) logs
- searching for kube (pod) logs
- searching for kube events

Would be nice to have an example for each.
And these examples would be useful to test all expected logs are collected well.

**Comment by TheoBrigitte** [comment]
Here a logging demo scenario to be recorded as "short" video

```
# Logging demo

## Intro

* query builder vs code explorer
	* builder for discovery
	* code for advanced usage
* scrape job for logs type: pod, systemd, audit

## Show basic pods logs

	Scenario: Show basic pod logs, along with label filtering and formatting with logfmt

	* Build
		* use builder to show prometheus-operator warning logs
		* add label filters for prometheus-operator pod logs
	* Parse
		* use logfmt auto suggested parsers
		* show: line contains filter should comes first for performance reasons
	* Filter
		* add label filter level=warn
		* show: logs lines comes by default newest first oldest last

	# Get prometheus-operator-app-operator warning logs
	{cluster_id="gorilla", scrape_job="kubernetes-pods", app="prometheus-operator-app-operator"} | logfmt | level=`warn`

## Get kubelet errors from problematic node

	Scenario: Show systemd unit logs, advanced code filtering with regex, line formatting with json and log metrics

	* Build
		* use builder to show kubelet errors logs
		* add label filters for kubelet logs
		* show: prettyfy json for readability
	* Parse & format
		* parse with json
		* format line to show MESSAGE only
	* Filter
		* add regex to filter by error: ^E
		* ad-hoc statistics and UI fields filters to filter by node with most errors
		* show: context to explore sourrounding log lines

	# Get kubelet error logs
	{cluster_id="gorilla", systemd_unit="k8s-kubelet.service"} | json | line_format `{{.MESSAGE}}` |~ `^E`

	* switch to code explorer to build query for error rate per minute per node

	# Count kubelet error/minute on each node
	sum(count_over_time({cluster_id="gorilla", scrape_job="system-logs", systemd_unit="k8s-kubelet.service"} | json | line_format `{{.MESSAGE}}` |~ `^E` [1m])) by (node_name)

## Show audit logs
	
	Scenario: Show audit logs, advanced line formatting

	NOTE: Run manual kubectl commands to generate log entries

	* Build
		* use builder to show audit logs
	* Parse & format
		* parse with json
		* format line to show "time user verb resource"
	* Filter
		* Filter out system users

	# Show which user is doing what
	{cluster_id="gorilla", scrape_job="audit-logs"} | json | line_format "{{.requestReceivedTimestamp}} \t {{.user_username}}  \t  {{.verb}}  \t  {{.requestURI}}" | stage = `RequestReceived` | user_username!~`^system:.+|g8s.gorilla.eu-central-1.aws.gigantic.io`
```

**Comment by TheoBrigitte** [comment]
Demo is out https://drive.google.com/file/d/1CikCLzhoj8h7P0OXSQ3J2YtUlGcLrG-6/view?usp=sharing and shared https://gigantic.slack.com/archives/C0601RK0URX/p1698665984310019
