### ISSUE TITLE
Cleanup OpenCost App

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2785]
### Motivation
For our cost-saving initiative we investigated around the OpenCost App but were not happy with the outcome. Therefore we need to clean up again.

### Todo
- [x] remove the OpenCost App from the catalog
- [x] Make sure there is no other mention of / reference to the OpenCost App in our System or docs

### Outcome
- We have a clean system without references to the openCost app we don't even support.

**Comment by njuettner** [comment]
Removed it from the catalog, docs are not pointing to our repo. Only mention it as a cost tool with the other tools but not specifically something to us, maintaining it.
