### ISSUE TITLE
Add tekton pipelines to build flatcar images for CAPV

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#2793]
As a part of https://github.com/giantswarm/roadmap/issues/2757
Extend https://github.com/giantswarm/capi-image-builder for CAPV

**Comment by erkanerol** [comment]
I did some exploratory works and hit the first issue.

Basically, to be able to produce OVA images, we should either use a remote vSphere or a local VMware Workstation or VMware Player. 

I tried to access our vSphere in  IONOS from our image builder cluster but there is no access. It requires VPN to access the endpoint. I am not sure if we can enable VPN in the image builder cluster.

The other option is to install VMware tools but it won't be easy to do it in a pod. 

I want to get @vxav and @glitchcrab's opinions here.

**Comment by erkanerol** [comment]
I managed to install VMware Player as below:
```
# docker.io/erkanerol/devenv:v3

FROM quay.io/giantswarm/capi-image-builder:1.6.8

USER root

# Check https://customerconnect.vmware.com/en/downloads/details?downloadGroup=WKST-PLAYER-1702&productId=1377&rPId=104734
RUN wget -q https://download3.vmware.com/software/WKST-PLAYER-1702/VMware-Player-Full-17.0.2-21581411.x86_64.bundle -O /tmp/VMWareWorkstation.bundle \
  && chmod +x /tmp/VMWareWorkstation.bundle \
  && /tmp/VMWareWorkstation.bundle --console --required --eulas-agreed \
  && rm -rf  /tmp/*

USER imagebuilder
```

But the [doc](https://developer.hashicorp.com/packer/integrations/hashicorp/vmware#:~:text=Additionally%20you%20will%20need%20to%20have%20the%20vmrun%20command%2C%20which%20is%20part%20of%20the%20VMware%20Virtual%20Infrastructure%20eXtension%20(VIX)%20SDK.) says it requires `VMware Virtual Infrastructure eXtension (VIX) SDK` too and it seems it is not open.

<img width="776" alt="Screenshot 2023-09-05 at 16 51 54" src="https://github.com/giantswarm/roadmap/assets/6574144/c91a7f6f-883a-4cc5-98e9-d8fc1f9c5c76">
https://techpartnerhub.vmware.com/sdks

**Comment by erkanerol** [comment]
I hit some compatibility issue when I tried to install VIX by using the link above. I opened an issue in the upstream side https://github.com/kubernetes-sigs/image-builder/issues/1290

**Comment by glitchcrab** [comment]
I think remote vsphere is by far the best route - it's better supported and involves less hackery

**Comment by AverageMarcus** [comment]
We're not going to be doing any changes to the old test-infra environment. We can include vpn access when we rebuild and migrate the pipelines to the new infrastructure as that already has the VPN proxy configured. But there are currently no immediate plans to do that. If this is a priority please discuss it with your product owner to bring it to the product sync so priorities can be adjusted accordingly.

**Comment by erkanerol** [comment]
@AverageMarcus I plan to deploy vpn-proxy as we do here https://github.com/giantswarm/cicd-gitops/tree/main/flux/vpn-proxy to `gorilla/rfjh2` and use it via proxy environment variables in CAPV tasks. All traffic in CAPV tasks will go through the vpn-proxy pod, a VPN-enabled squid proxy pod. 

Are you OK with it?

**Comment by AverageMarcus** [comment]
Fine with me. Just be aware that we'll be recreating and migrating these pipelines shortly-ish (it's currently in our up-next column on our board).

**Comment by erkanerol** [comment]
@AverageMarcus Will it have built-in support for VPN? Do you have an estimation of when the migration can finish? 

I hit an issue while trying the method above because of SSH connections. Setting proxy variables is not enough. I  also need to configure SSH that supports connections through proxy.

**Comment by AverageMarcus** [comment]
We haven't even started work on it yet so I can't possibly say when it'll likely be complete. If VPN is required then it'll be included in the requirements and we'll re-use the existing proxy we have in the new cluster.

**Comment by erkanerol** [comment]
@AverageMarcus I don't know exactly what we have in the new cluster. Does VPN work at the node level there? I am asking since I hit some issues when I tried to use VPN as a proxy.  

By the way, thanks a lot for helping me. There are many new things in this area to me. I learned mostly so I hope newer developments will be much easier.

**Comment by AverageMarcus** [comment]
The new cluster is the same as used by mc-bootstrap currently (and the WC E2E tests). It have VPN set up as a proxy so we'll need to work to get image-builder working with that.

Any issues you face or things you think we specifically need to take into consideration would be useful. The issue we have is still fairly sparse on details as we haven't started the investigation yet but if you have anything to add please use this one: https://github.com/giantswarm/giantswarm/issues/26154

**Comment by erkanerol** [comment]
I finally managed to run image-builder from our environment by using remote vSphere API which is accessible via proxy. There are many issues to fix. I will bring them under this comment.

- [ ] Enable VPN in the environment
        -> I deployed VPN as a proxy to our existing environment and added this into requirement of new environment. We can assume this is done for now.
- [ ] Expose ssh_proxy variables for packer
        -> https://github.com/kubernetes-sigs/image-builder/pull/1314
- [ ] Fix relative script path in post-processors
        -> https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/ova/packer-node.json#L336
- [ ] Adapt our tasks to inject vSphere.json to var.json
- [ ] Add CAPV pipeline and add AWS S3 support for image uploading&check.

**Comment by erkanerol** [comment]
Marcus added CAPV pipeline and S3 upload. We are able to produce our image now.

I found a minor issue related OVF content that block image upload to vsphere. It is possible to edit OVF file manually and upload the image. I did it in that way and verified the image with https://github.com/giantswarm/cluster-vsphere/pull/98

I will fix the problem and close this issue. Details of the problem can be found here https://kubernetes.slack.com/archives/C01E0Q35A8J/p1698754064351559

**Comment by erkanerol** [comment]
I opened a PR in the upstream side https://github.com/kubernetes-sigs/image-builder/pull/1337/files

**Comment by erkanerol** [comment]
I just verified the latest fix. Also deleted old images for the S3 bucket. After documenting the status, I will close this issue.

**Comment by erkanerol** [comment]
Doc PR https://github.com/giantswarm/giantswarm/pull/28929

**Comment by erkanerol** [comment]
Doc is available here https://intranet.giantswarm.io/docs/product/providers/capv/image_building/
