### ISSUE TITLE
Cabbage tests(if needed), reviews and approves AWS 19.1.0

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2795]
Please review the release notes, make sure that the components have right versions and test WCs creation/upgrade if needed. We will only merge when we have approval from all the teams. PR: https://github.com/giantswarm/releases/pull/1147

**Comment by weatherhog** [comment]
hello @giantswarm/team-cabbage can someone please take a look at this and treat it with high priority?

**Comment by ced0ps** [comment]
Checked and tentatively signed off :+1:
