### ISSUE TITLE
Atlas tests(if needed), reviews and approves AWS 19.1.0

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2796]
Please review the release notes, make sure that the components have right versions and test WCs creation/upgrade if needed. We will only merge when we have approval from all the teams. PR: https://github.com/giantswarm/releases/pull/1147

**Comment by QuentinBisson** [comment]
Thanks for giving us the opportunity so we have all our changes here up to the latest bundle (0.8.2) that contains a lot of fixes for prometheus-operator and the latest promtail.

Closing as I approved the release
