### ISSUE TITLE
Future of on premise

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#280]
Lets discuss and collect thoughts about the future of on premise here.

**Comment by tfussell** [comment]
We discussed this at the onsite. Our focus for the next few months will be getting our CAPV offering to GA readiness. We have a clear picture of what will be required for alpha readiness and will start working on beta and beyond soon.

We also talked about some easy wins for KVM to increase reliability and reduce maintenance burden. With the expanded team we hope we can work on these alongside or after CAPV.

Next year, we will hopefully get customers transitioned to cluster-api, whether CAPV, CAPK, or CAPO and begin to retire legacy components.

Finally, if we continue to support the KVM product, we would like to get rid of kubernetes-in-kubernetes and use an MC which is separate from the worker hypervisors, whether using metal3, proxmox, or a custom solution. There is also the possibility of developing an edge solution, but we have no real priority on this for now.
