### ISSUE TITLE
Adapt target selection based on app versions in PMO

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2811]
There's a builtin logic in PMO in order to add scraping targets based on some app versions.

App will no longer be available on EKS so we need to adapt this logic.

**Comment by QuentinBisson** [comment]
List of targets to fix for eks clusters

**Comment by marieroque** [comment]
Thread related to the way pmo can detect an EKS cluster: 
https://gigantic.slack.com/archives/CN9LXS96U/p1695205780731749

**Comment by marieroque** [comment]
Tested on `snail/sample-customer`:


![Image](https://github.com/giantswarm/roadmap/assets/9134338/8cdc7406-12c1-498e-92ee-60db88860b3b)

Log in pmo:
```
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","controller":"prometheus-meta-operator-cluster-api-controller","event":"update","level":"debug","loop":"0","message":"EKS cluster: ignoring all scraping targets in Prometheus scrape config","object":"org-sample/sample-customer","resource":"scrapeconfigs","time":"2023-09-20T14:39:40.093293+00:00","version":"114911023"}
```

**Comment by QuentinBisson** [comment]
@marieroque can you close this?

**Comment by marieroque** [comment]
=> release `prometheus-meta-operator v4.49.0`
