### ISSUE TITLE
Update target for compatibility with EKS (ServiceMonitors)

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2812]
Metrics targets on EKS might be different than what we currently use.

We need to define a list of targets to be scraped and adapt our current configs (via Service/PodMonitors)

- [x] Define targets list
- [x] Update target config

**Comment by QuentinBisson** [comment]
On EKS we do not have access to ETCD, kube-scheduler and kube-controller-manager metrics. We should clean up the service monitors for those but we do not have an eks provider yet to do this. I'll clean up in the mcb repo

- [ ]  Disable etcd servicemonitor
- [ ]  Disable kube-scheduler servicemonitor
- [ ]  Disable kube-controller-manager servicemonitor

Missing targets:
- [ ] Coredns: Service label selector is k8s-app: coredns on the Giant Swarm side but the pod on eks has `k8s-app: kube-dns`
- [ ] Kube-proxy: Enable the service monitor

Unmonitored targets:
- [ ] AWS node

- Targets/apps not deployed yet:
- [ ] VPA
- [ ] metrics-server

**Comment by QuentinBisson** [comment]
Everything is done, closing...

**Comment by QuentinBisson** [comment]
@giantswarm/team-turtles FYI I deployed VPA and metrics-server on Snail WC. 
VPA is in a meh state because the cluster has only 1 node so the admission controller cannot be scheduled. 
The metrics-server is not able to get the metrics but will not go on further with the investigations :)
