### ISSUE TITLE
Validate Monitoring on EKS

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2813]
We need to make sure our monitoring system is fully compatible and working for EKS clusters.

So we need to validate the following elements:
- [x] Metrics are accessible via Grafana
- [x] Dashboard are loaded in Grafana
- [x] Metrics are sent to Grafana Cloud

**Comment by QuentinBisson** [comment]
Metrics and dashboards are set: 
![image](https://github.com/giantswarm/roadmap/assets/2787548/743b4938-bb56-49d2-b809-17746fc0582e)

**Comment by QuentinBisson** [comment]
I had to override the prometheus agent priority class to an empty string because our Giant Swarm Priority Classes are not present in EKS adopted clusters yet but metrics are sent to Grafana Cloud
![image](https://github.com/giantswarm/roadmap/assets/2787548/0aa772a3-9ff9-4786-a0bc-46c91cebfa61)
