### ISSUE TITLE
Validate Alerting on EKS

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2814]
We need to make sure our alerting system is fully compatible and working for EKS clusters.

So we need to validate the following elements:
- [x] Alerts are received in OpsGenie
- [x] Alerts are received in Slack
- [x] Silence are applied in alertmanager by silence-operator

**Comment by QuentinBisson** [comment]
We receive heartbeats:
![image](https://github.com/giantswarm/roadmap/assets/2787548/7e5dd970-ae24-427a-96a2-51dab9d78124)

And alerts are sent to opsgenie:
![image](https://github.com/giantswarm/roadmap/assets/2787548/9500ce3d-7797-4371-a2ed-2d3404e74409)

**Comment by QuentinBisson** [comment]
Silences are created:
![image](https://github.com/giantswarm/roadmap/assets/2787548/b2f4ef30-c9a5-4d9d-a942-646f314edbdc)

**Comment by QuentinBisson** [comment]
Alerts are created on slack:
![image](https://github.com/giantswarm/roadmap/assets/2787548/a031bc5f-a2c6-4cc7-86c5-151143360f32)
