### ISSUE TITLE
Test Cabbage components on GS EKS based CAPA solution

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2816]
Following Phoenix development on EKS cluster creation based on CAPA, we have created a solution to create the EKS clusters within our current stack on CAPA MCs. The full documentation can be found here: https://intranet.giantswarm.io/docs/dev-and-releng/capi-eks-internal-doc/.

Now is up to the Product teams to test out EKS on CAPA in order to gather further notes on development and missing features from other teams. Please take this into account while also testing out the Honeybadger 'import' of EKS.

cc @puja108 for planning

**Comment by mcharriere** [comment]
Default apps:
- [ ] coredns
- [ ] external-dns
- [ ] net-exporter

Product apps:
- [ ] kong
- [ ] linkerd
- [ ] ingress-nginx

**Comment by mcharriere** [comment]
All done here. All our apps are working at least with the default setup.
