### ISSUE TITLE
Test Atlas components on GS EKS based CAPA solution

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2817]
Following Phoenix development on EKS cluster creation based on CAPA, we have created a solution to create the EKS clusters within our current stack on CAPA MCs (`girzzly` and `golem`). The full documentation can be found here: https://intranet.giantswarm.io/docs/dev-and-releng/capi-eks-internal-doc/.

Now is up to the Product teams to test out EKS on CAPA in order to gather further notes on development and missing features from other teams. Please take this into account while also testing out the Honeybadger 'import' of EKS.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2832
- [ ] https://github.com/giantswarm/roadmap/issues/2843
- [ ] https://github.com/giantswarm/roadmap/issues/2673
```

cc @puja108 for planning

**Comment by QuentinBisson** [comment]
Promtail and Loki were tested, closing
