### ISSUE TITLE
Test Shield components on GS EKS based CAPA solution

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2819]
Following Phoenix development on EKS cluster creation based on CAPA, we have created a solution to create the EKS clusters within our current stack on CAPA MCs. The full documentation can be found here: https://intranet.giantswarm.io/docs/dev-and-releng/capi-eks-internal-doc/.

Now is up to the Product teams to test out EKS on CAPA in order to gather further notes on development and missing features from other teams. Please take this into account while also testing out the Honeybadger 'import' of EKS.

cc @puja108 for planning

**Comment by T-Kukawka** [comment]
@stone-z any update here?

**Comment by stone-z** [comment]
My understanding from product was that EKS is paused for now, so we have not prioritized this over PSS work

**Comment by T-Kukawka** [comment]
that is true 👍

**Comment by T-Kukawka** [comment]
@stone-z as we seem to be getting more customer interest in EKS and our work is done with 1 small issue remaining on Big Mac side for dex, could we get some eyes on that?

**Comment by alex-dabija** [comment]
@stone-z do you know when team Shield will start testing on CAPA EKS?

**Comment by stone-z** [comment]
It is not currently planned. We will try to sneak it in when capacity allows

**Comment by puja108** [comment]
Yes, as mentioned in SIG product on Monday, please all teams test (and fix) your apps on EKS, please.

**Comment by T-Kukawka** [comment]
is this done @giantswarm/team-shield ?

**Comment by stone-z** [comment]
Not yet, I've been afk

**Comment by stone-z** [comment]
Tried to test an EKS workload cluster from `golem` today and once again had issues:
- AWS CLI is still a problem for people who don't use it every day. After a lot of troubleshooting, I found that the correct order seems to be:
    - `aws configure --profile giantswarm-aws-cli`
    - `AWS_PROFILE=giantswarm-aws-cli aws sts get-caller-identity` to test the local setup
    - `export OPSCTL_GET_CREDENTIALS_AWS_PROFILE=giantswarm-aws-cli` <-- I was missing this in my environment
    - `opsctl credentials aws -i <mc> -c <wc>`
    - only then can you use `opsctl login MC WC --aws-profile=PROFILE_NAME` but the flag must be specified and the environment variable must be present
- after logging in successfully, the workload cluster is Ready according to `kgs` and `happa`, but the nodes are all NotReady and no workloads started after ~3 hours
 
I will attempt to start a new cluster and allow another 30 min to start my test today, otherwise I will re-shelf this issue.

**Comment by stone-z** [comment]
Update: I created a second WC on `grizzly`. I was initially able to log into the WC, but the nodes were also NotReady. I then lost access to the cluster, with the error `Unable to connect to the server: dial tcp: lookup F8DC701EF45E7D3963CD972A6CF57A7D.gr7.eu-west-2.eks.amazonaws.com on 10.0.253.1:53: no such host`. I waited another 30 minutes in case the cluster was still starting but haven't yet been able to get access again.

**Comment by T-Kukawka** [comment]
sorry to hear @stone-z - this was not caught by e2e tests - we are working on fixing the state

**Comment by T-Kukawka** [comment]
hey Zach, seems Crossplane messed up cluster creation: https://github.com/giantswarm/cluster-eks/pull/98 - it is fixed now, just tested it on `golem`.

When teleport is deployed, that u can check via `kubectl get apps -A | grep "{CLUSTER_ID}"` on MC or in AWS EKS panel in Resources section - you can then use teleport `tsh` login command. It works really well and quick.

Otherwise you will have to refresh the token every 15' due to AWS limitations  as stated in the docs at the end: https://intranet.giantswarm.io/docs/dev-and-releng/capi-eks-internal-doc/

**Comment by stone-z** [comment]
I was able to get one working :+1: 

Tested the security bundle apps, including some unreleased upcoming stuff. All looks good
