### ISSUE TITLE
Evaluate monitoring on managed EKS WC

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2832]
Create a managed EKS cluster from a EKS based CAPA MC (`girzzly` and `golem`) using the following [guide](https://intranet.giantswarm.io/docs/dev-and-releng/capi-eks-internal-doc/).

Evaluate how the current monitoring and alerting behave on this cluster.

### Checks
- [x] Cluster level metrics are accessible in Grafana
  - [x] https://github.com/giantswarm/default-apps-eks/pull/8
  - [x] https://github.com/giantswarm/prometheus-meta-operator/pull/1375
- [x] Cluster alerts are received in OpsGenie
- [ ] All targets are healthy in Prometheus
  - [ ] https://github.com/giantswarm/giantswarm/issues/27558
  - [x] https://github.com/giantswarm/net-exporter/pull/299
  - [x] https://github.com/giantswarm/giantswarm/issues/27557
  - [x] https://github.com/giantswarm/giantswarm/issues/28250
  - [x] https://github.com/giantswarm/giantswarm/issues/27576
- [x] All alerts are green in Prometheus
  - [x] https://github.com/giantswarm/giantswarm/issues/28252
  - [x] https://github.com/giantswarm/roadmap/issues/2843

Related issues:
- https://github.com/giantswarm/giantswarm/issues/28387
- https://github.com/giantswarm/giantswarm/issues/28388

**Comment by QuentinBisson** [comment]
Started by upgrading the `observability-bundle` in `default-apps-eks` https://github.com/giantswarm/default-apps-eks/pull/8.

I now have a cluster running on grizzly

**Comment by QuentinBisson** [comment]
Monitoring: 
🔴  Prometheus is currently not able to list pods and so on:

```
ts=2023-09-20T10:52:22.949Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443/api/v1/namespaces/kube-system/pods?limit=500&resourceVersion=0\": dial tcp: lookup https on 172.31.0.10:53: no such host"
ts=2023-09-20T10:52:23.772Z caller=klog.go:108 level=warn component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: failed to list *v1.Endpoints: Get \"https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443/api/v1/namespaces/kube-system/endpoints?limit=500&resourceVersion=0\": dial tcp: lookup https on 172.31.0.10:53: no such host"
ts=2023-09-20T10:52:23.772Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get \"https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443/api/v1/namespaces/kube-system/endpoints?limit=500&resourceVersion=0\": dial tcp: lookup https on 172.31.0.10:53: no such host"
ts=2023-09-20T10:52:24.107Z caller=klog.go:108 level=warn component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: failed to list *v1.Pod: Get \"https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443/api/v1/pods?limit=500&resourceVersion=0\": dial tcp: lookup https on 172.31.0.10:53: no such host"
ts=2023-09-20T10:52:24.107Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443/api/v1/pods?limit=500&resourceVersion=0\": dial tcp: lookup https on 172.31.0.10:53: no such host"
ts=2023-09-20T10:52:24.395Z caller=klog.go:108 level=warn component=k8s_client_runtime func=Warningf msg="pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: failed to list *v1.Endpoints: Get \"https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443/api/v1/endpoints?limit=500&resourceVersion=0\": dial tcp: lookup https on 172.31.0.10:53: no such host"
ts=2023-09-20T10:52:24.395Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.27.3/tools/cache/reflector.go:231: Failed to watch *v1.Endpoints: failed to list *v1.Endpoints: Get \"https://https/F5AB99CD4973C48F8F80414C4693ED04.gr7.eu-west-2.eks.amazonaws.com:443/api/v1/endpoints?limit=500&resourceVersion=0\": dial tcp: lookup https on 172.31.0.10:53: no such host"
```

🟡 Scraping targets:
List of targets is currently empty, most likely related to the above issue

🟢 Alerting:
![image](https://github.com/giantswarm/roadmap/assets/2787548/c300b56d-1e6e-4666-99c1-30af1edb02be)

🟡 Alert status in Prometheus
A few are in pending, to be investigated

🟢 Grafana:
![image](https://github.com/giantswarm/roadmap/assets/2787548/ca47d042-6132-4062-a00c-48fb99e8daf1)

🟢 Grafana cloud:
![image](https://github.com/giantswarm/roadmap/assets/2787548/f69db496-4b16-4c7a-b89a-c1dced3e4cdf)

**Comment by QuentinBisson** [comment]
Status Update
---
Monitoring:
🟢  Prometheus fixed with https://github.com/giantswarm/prometheus-meta-operator/pull/1375

🔴  Scraping targets:
List of targets is currently empty, most likely related to the above issue

**Comment by QuentinBisson** [comment]
Related https://github.com/giantswarm/default-apps-eks/pull/10

**Comment by QuentinBisson** [comment]
Fixing net-exporter netpol https://github.com/giantswarm/net-exporter/pull/299

**Comment by QuentinBisson** [comment]
Status Update
---
🟠  Scraping targets:
Prometheus on the MC cannot scrape `cert-exporter`, `cert-manager-app` and `chart-operator` because the api server proxy is either not configured properly on Managed EKS or not working at all. Fixing this would require a deep investigation from @giantswarm/team-phoenix. 
As we are striving to move to service monitors, it would definitely be easier for everyone if we moved the failing apps to use service monitors instead:
- `cert-manager-app`: https://github.com/giantswarm/giantswarm/issues/27557 This appears solved in 3.3.0 but cert manager is stuck in pending upgrade in EKS managed clusters. Related PM https://github.com/giantswarm/giantswarm/issues/28250
- `cert-exporter-app`: https://github.com/giantswarm/giantswarm/issues/27576
- `chart-operator`: https://github.com/giantswarm/giantswarm/issues/27558

🔴 Prometheus-operator and Kube-state-metrics are unstable
The pods keep getting recreated every 1 minute even though the pods are in a running state. We will need to dig deeper into it.

🔴 Alerting
![list of alerts](https://github.com/giantswarm/roadmap/assets/2787548/768bd963-bed7-42a6-91d6-9bf0b03d7e69)
The current list of alert is big but of those, only 3 are relevants because most of the alerts are related to the scraping errors above:
- `WorkloadClusterAPIServerAdmissionWebhookErrors`: Needs to investigate what is happening
- `WorkloadClusterEtcdMetricsMissing`: We do not have any etcd metrics because we cannot monitor etcd on managed clusters. We need to figure out how to skip this alert for eks clusters
- `PrometheusAgentShardsMissing`: Not sure why it pages

**Comment by QuentinBisson** [comment]
Status Update
---
Prometheus operator and kube-state-metrics keep getting evicted by VPA because the recommender is not able to get metrics from metrics server. Relevant PM: https://github.com/giantswarm/giantswarm/issues/28252

**Comment by QuentinBisson** [comment]
What to do about about metrics that rely on etcd_kubernetes_resources_count?

**Comment by T-Kukawka** [comment]
> What to do about about metrics that rely on etcd_kubernetes_resources_count?

they will have to go away as we do not manage ETCD anymore in this scenario @QuentinBisson

**Comment by QuentinBisson** [comment]
I know @T-Kukawka but I'm not sure how those could be replaced.

https://github.com/search?q=repo%3Agiantswarm%2Fprometheus-rules%20etcd_kubernetes_resources_count&type=code

**Comment by T-Kukawka** [comment]
ah i see :( yeah then we have to align with BigMac and Shield how else this could be monitored or is relevant even

**Comment by QuentinBisson** [comment]
True but then if we can replace those 2 alerts with something else, we can probably remove the `etcd-kubernetes-resources-count-exporter` component altogether because it seems that it's the only use case

**Comment by T-Kukawka** [comment]
true, i believe it should be removed for EKS at least ( we still use it in CAPI and Vintage especially with incidents monitoring etc when ETCD is overflown)

**Comment by QuentinBisson** [comment]
oh sure :)

**Comment by QuentinBisson** [comment]
🟢   Scraping targets:
- Only chart operator is missing (no service monitors) but it is being addressed by honeybadger this week: https://github.com/giantswarm/giantswarm/issues/27558.

Once it makes it into default-apps-eks, we can release and have everything running.

🟠 Alerting is in testing

**Comment by QuentinBisson** [comment]
:large_green_circle: Alerts are green. The pending/firing alerts are related to either this PM https://github.com/giantswarm/giantswarm/issues/28252 or https://github.com/giantswarm/giantswarm/issues/27558
![image](https://github.com/giantswarm/roadmap/assets/2787548/920d4883-356a-45a1-b1ab-51dbd4e8f370)

**Comment by QuentinBisson** [comment]
@TheoBrigitte We're all done for now, this is now blocked because of the 2 issues linked https://github.com/giantswarm/roadmap/issues/2832#issuecomment-1742555806.

I added them at the top as well

**Comment by QuentinBisson** [comment]
@TheoBrigitte do we still need this issue as we ensured monitoring is working and the issues exists for other teams?

**Comment by QuentinBisson** [comment]
All our issues are fixed, the rest is distributed to teams closing
