### ISSUE TITLE
Test log ingestion from WCs manually

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2834]
Once we have https://github.com/giantswarm/roadmap/issues/2758 completed, we should run manual test on few clusters to evaluate how our logging infrastructure behave before switching this on by default on all WCs.

Tasks:
- Enable logging on a specific cluster (via the annotation)
- Monitor usage using our `Loki Cost Estimate` dashboard
  - Report usage increase in terms of bandwidth, storage and resources usage

**Comment by hervenicol** [comment]
Enabling logging on `gorilla/zj88t`:

```
$ kubectl label cluster -n org-giantswarm-production zj88t giantswarm.io/logging=true
```

This results in promtail pods being created on the WC:
```
$ ks get pods | grep -i promtail
promtail-app-2hpwm                                                   1/1     Running     0               60s
promtail-app-9xvrv                                                   1/1     Running     0               61s
promtail-app-fpl4d                                                   1/1     Running     0               60s
promtail-app-klclf                                                   1/1     Running     0               60s
```

But logs in these pods don't look good:
```
W0921 19:18:26.448128       1 reflector.go:324] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:572: failed to list *v1.Pod: Get "https://172.31.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dip-10-6-2-155.eu-central-1.compute.internal&limit=500&resourceVersion=0": dial tcp 172.31.0.1:443: i/o timeout
I0921 19:18:26.448179       1 trace.go:205] Trace[2021391775]: "Reflector ListAndWatch" name:github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:572 (21-Sep-2023 19:17:56.446) (total time: 30001ms):
Trace[2021391775]: ---"Objects listed" error:Get "https://172.31.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dip-10-6-2-155.eu-central-1.compute.internal&limit=500&resourceVersion=0": dial tcp 172.31.0.1:443: i/o timeout 30001ms (19:18:26.448)
Trace[2021391775]: [30.001373076s] [30.001373076s] END
E0921 19:18:26.448194       1 reflector.go:138] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:572: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://172.31.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dip-10-6-2-155.eu-central-1.compute.internal&limit=500&resourceVersion=0": dial tcp 172.31.0.1:443: i/o timeout
level=warn ts=2023-09-21T19:18:44.825682974Z caller=client.go:379 component=client host=loki.g8s.gorilla.eu-central-1.aws.gigantic.io msg="error sending batch, will retry" status=-1 error="Post \"https://loki.g8s.gorilla.eu-central-1.aws.gigantic.io/loki/api/v1/push\": context deadline exceeded"
```

* some timeouts when doing service discovery of pods.
* some timeouts when trying to send logs to Loki

When exploring logs in Grafana, I can't see logs for `{cluster_id="zj88t"}`.

**Comment by TheoBrigitte** [comment]
Alright so we are getting logs from WC right ?
What's with those timeouts then, is it problematic or just happens every now and then ?

**Comment by hervenicol** [comment]
oops, looks like `gorilla` / `zj88t` is release 18.4.2. So, running an old observability bundle that won't work.

Let's try on a 19.1 cluster.

```
$ k gs get clusters -A
NAMESPACE                   NAME      AGE    CONDITION   RELEASE   SERVICE PRIORITY   ORGANIZATION            DESCRIPTION
org-giantswarm-demos        xp33j     15d    CREATED     19.0.1    lowest             giantswarm-demos        Rewe Demo
org-giantswarm-production   rfjh2     681d   UPDATED     19.1.0    n/a                giantswarm-production   Giant Swarm Operations Platform
org-giantswarm-production   zj88t     688d   UPDATED     18.4.2    n/a                giantswarm-production   Team Atlas cluster
org-team-tinkerers          cicddev   132d   UPDATED     19.1.0    lowest             team-tinkerers          Giant Swarm CI/CD Platform - Non-production & CICD development
org-team-tinkerers          ei9o7     247d   UPDATED     19.1.0    highest            team-tinkerers          Giant Swarm CI/CD Platform
```

Let's try on `rfjh2`

**Comment by hervenicol** [comment]
```
$ kubectl label cluster -n org-giantswarm-production rfjh2 giantswarm.io/logging=true      
cluster.cluster.x-k8s.io/rfjh2 labeled
```

Label stays for a few minutes, but then gets removed. Probably because the cluster is flux-managed.
Then why is the label kept on `zj88t`? It's flux-managed the same way, right?

**Comment by hervenicol** [comment]
Flux was stuck for `zj88t`.
Fixed it, the cluster has been upgraded to 19.1.0.
Logs were sent to Loki for a few minutes, then the label has been removed from the cluster by Flux, and we don't have logs anymore.

So:
- promtail does not work in 18.4.0
- promtail works on 19.1.0
- cluster labels get reverted by flux

**Comment by TheoBrigitte** [comment]
Once https://github.com/giantswarm/logging-operator/pull/47 is merged we can close this and will follow-up on switching logging on by default with https://github.com/giantswarm/roadmap/issues/2835

**Comment by TheoBrigitte** [comment]
Before we switch logging on by default on all WC, we want to evaluate what's the impact in term of cost.
So we enable logging on some clusters and evaluate after 1 week the impact on cost.

List of clusters to test on:
- tbd

**Comment by QuantumEnigmaa** [comment]
Promtail deployed on all the mentioned WCs. 
After a whole night, loki seem to struggle with the load generated by the additional logs

**Comment by hervenicol** [comment]
Loki investigation and tuning is tracked here:
* https://github.com/giantswarm/giantswarm/issues/28445
* https://github.com/giantswarm/giantswarm/issues/28446

**Comment by QuantumEnigmaa** [comment]
I guess this could be close since https://github.com/giantswarm/giantswarm/issues/28446 is now closed and https://github.com/giantswarm/roadmap/issues/2835 will be closed as well soon enough.

**Comment by TheoBrigitte** [comment]
Closing as we did the testing and improve read and read path performances.
