### ISSUE TITLE
Enable logging for WCs

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2835]
Ingestion of logs from workload cluster should be the default when a cluster is created.

Currently we have the opposite logic where logging is disabled by default and can be enabled via `giantswarm.io/logging=true` label on Cluster CR.

Here we should reverse this logic to have logging enabled by default, and if needed user can disable logging by applying `giantswarm.io/logging=false` label on Cluster CR.

**Comment by QuentinBisson** [comment]
This was actually merged here https://github.com/giantswarm/logging-operator/pull/79/files

**Comment by TheoBrigitte** [comment]
This was reverted today with https://github.com/giantswarm/logging-operator/pull/84, as we observed performance issue. For details see https://gigantic.slack.com/archives/C064ZHJ25BQ

**Comment by TheoBrigitte** [comment]
Blocked by https://github.com/giantswarm/giantswarm/issues/28842

**Comment by TheoBrigitte** [comment]
We moved forward on tuning Loki write path and improve performances. We can soon proceed with enabling logging for WCs.

**Comment by hervenicol** [comment]
It's been enabled on Monday.
Loki crashed out of disk space on 3 installations (alpaca, argali, antelope) when it had to absorb the logs backlog and scale up quickly. But after some disks cleanup all seems stable now.
