### ISSUE TITLE
Discussion - building standards for bundles under the new app-platform structure

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2837]
See slack threads:

- Support thread: https://gigantic.slack.com/archives/C02EVLE9W/p1694762568923859
- Support adidas (primary thread) https://gigantic.slack.com/archives/C6L8J93N0/p1694754526053129

**Comment by piontec** [comment]
@Rotfuks We discussed this - it's about how different is the configuration approach between two bundles. Can you take ownership here, as you wanted to work on it?

**Comment by Rotfuks** [comment]
I think this story is better placed in @giantswarm/team-honeybadger since you own those tools. I brought the topic up in sig-ux where @marians could drive a discussion how this standard could look like. Moving back to Honeybadger for now.

**Comment by weatherhog** [comment]
@piontec does this issue still needs to be watched? Is there a way forward or can it be closed?

**Comment by piontec** [comment]
We won't be replacing app bundles anytime soon, even though we would love to. But since we learned to live with them, that's low priority and we have somewhere different ticket about it. Closing this one.
