### ISSUE TITLE
Ignore ENOENT error from dev portal in Sentry

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2839]
Whenever someone accesses Techdocs in the portal and they haven't been rendered yet (which is the regular case), then an error is reported in Sentry. [Example](https://giantswarm.sentry.io/issues/4399016199/?alert_rule_id=14594690&alert_timestamp=1692189147195&alert_type=email&environment=production&project=4505675382587392&referrer=alert_email)

To prevent alerting fatique, we should prevent this Sentry error from being issued.

**Comment by piontec** [comment]
@marians please provide some context here

**Comment by marians** [comment]
The main issue comment has all the context. I just checked Sentry and it seems that this is no longer occurring. Closing.
