### ISSUE TITLE
Discovery: Flat-network multiclusters

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#2842]
Explore how to interconnect our WCs and make pods reachable.

This would be an interesting feature for multicluster setups.

Refs: https://linkerd.io/2023/09/11/linkerd-214/#flat-network-multicluster

**Comment by mcharriere** [comment]
This might help https://docs.cilium.io/en/stable/network/clustermesh/intro/

but the requirement of a flat-network is still there

**Comment by Gacko** [comment]
Just took a look at what they mean by flat network: It's basically what we just disabled by introducing Cilium. This would require enabling the ENI mode of Cilium for a cluster.

**Comment by weatherhog** [comment]
archiving this because we are not using linkerd anymore
