### ISSUE TITLE
Creation of new MCs breaks default cluster issuer

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2844]
cert-manager-app v2 defaults to `global.giantSwarmClusterIssuer.install=true`, meaning a `ClusterIssuer/letsencrypt-giantswarm` will get installed and used as default. This makes TLS work out of the box for ingress-based applications such as our Grafana installation on the MCs, without having to explicitly select a cluster issuer in the `Ingress` object. With the upgrade to cert-manager-app v3 (as part of `default-apps-*`), this default goes away and we have to fill `ingressShim.defaultIssuer*` explicitly.

- Add config to `*-management-clusters` repos
- Set config via mc-bootstrap so that new MCs will be correctly working (note: mc-bootstrap typically uses the latest `default-apps-*` due to renovate)

**Comment by T-Kukawka** [comment]
pinging @gawertm to follow up on this -> those are breaking changes that have not been properly evaluated either for our infra or customer infra

**Comment by T-Kukawka** [comment]
also another aftermath of the change: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1695635685273639

**Comment by T-Kukawka** [comment]
and related: https://github.com/giantswarm/giantswarm-management-clusters/pull/185

**Comment by calvix** [comment]
I think was a bad choice to fix the mess, now we have `defaults` that are spread over multiple repositories and it will be so hard to make any change to the default values in the default app repository as you need to go around and change it all possible place over the world.

**Comment by kopiczko** [comment]
We discussed it briefly in BigMac and we thought it would be a good idea to follow the same patter we are going to implement for CiliumNetworkPolicy CRs (and NetworkPolicy resources in general) and create a separate app repository containing only Giant Swarm specific issuers. Then we can install them wherever necessary and we don't have to make deviations from upstream.

**Comment by ubergesundheit** [comment]
yes my idea was in a similar direction..

have at least

- base cert-manager
- clusterissuers
- maybe crds 

in separate apps

**Comment by ubergesundheit** [comment]
New plan:

- Revert https://github.com/giantswarm/giantswarm-management-clusters/pull/185 https://github.com/giantswarm/adidas-management-clusters/pull/42 https://github.com/giantswarm/continental-management-clusters/pull/23 https://github.com/giantswarm/panamax-management-clusters/pull/38
- Change Giant Swarm Ingresses on management clusters to include annotation `cert-manager.io/cluster-issuer: letsencrypt-giantswarm`
