### ISSUE TITLE
Let customers manage their own dashboards on the management cluster

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#2847]
As a customer I'd like to configure my own dashboard on the management cluster. So that I also get a better overview about certain metrics that are either from the management cluster itself or from the workload clusters.

This makes sense if a customer

 * installed on operator on the MC #1073 
 * manages their own applications/tools on the workload clusters and they get deployed via our app platform

**Comment by teemow** [comment]
@TheoBrigitte similar issue like #2846

**Comment by QuentinBisson** [comment]
This is already possible as described here:
https://docs.giantswarm.io/getting-started/observability/grafana/custom-dashboards/

**Comment by teemow** [comment]
Nice :heart:

**Comment by TheoBrigitte** [comment]
@teemow I assume its not trivial to know about this. I'll add this link into our Grafana homepage. Other ideas welcome.

see https://github.com/giantswarm/dashboards/pull/373
