### ISSUE TITLE
Ability to deploy multiple clusters into existing VPC

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#285]
**Is your feature request related to a problem? Please describe.**

- Cluster to cluster communication can get very costly if putting the two endpoints in the same cluster is not an option. Currently there is only the ability to deploy cluster with new VPC and only one cluster per VPC. 

**Describe the solution you'd like**

- Ability to create clusters in an existing VPC that is decoupled from existing resources in that VPC.

**Describe alternatives you've considered**

- Redesign which applications are in which cluster to cut down on how much traffic needs to traverse inter-cluster communication
- Create bigger clusters 

**Additional context**

NA

**Comment by teemow** [comment]
@alex-dabija @T-Kukawka this an old issue still labeled with firecracker? To phoenix or close?

**Comment by alex-dabija** [comment]
Old issue, it should be double with CAPA, but we need to have a use case for this request. Also, the implications need to be evaluated. Closing for now.
