### ISSUE TITLE
Some tests in rbac operator are still flaky

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2853]
`test_rbac_controller_external_resources` still fails sometimes even after increasing max retries from 5 to 10

Reconciliation happens every five minutes. Let's check that max retries and the timeout in between exceed five minutes.

**Comment by mogottsch** [comment]
I tried to increase the retries to 6 with a 60-second delay, which should cover the case that reconciliation only happens after 5 minutes.
However, it didn't help.

**Comment by vvondruska** [comment]
A fix was applied and the tests succeeded for many consecutive times.
If the problem persists and another flake occurs, this issue will be re-opened.
