### ISSUE TITLE
Teleport - Helm subchart for cluster-apps

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#2856]
**Motivation**
- Use sub-charts to extract common things for all provider.

**Reference**
- https://github.com/giantswarm/cluster-aws/pull/334#issuecomment-1730117065

**Comment by tuladhar** [comment]
Implementing sub-chart with files seems a bit tricky than initially thought. We encounter an issue trying to render files that’s in subchart to parent chart.

In teleport sub-chart; we have _helper.tpl file, as such:
```
{{- define "teleportFiles" -}}
- path: /opt/teleport-node-role.sh
  permissions: "0755"
  encoding: base64
  content: {{ $.Files.Get "files/opt/teleport-node-role.sh" | b64enc }}
{{- end -}}
```

And, we are including teleportFiles in parent chart as such:
```
    {{- if .Values.internal.teleport.enabled }}
    {{- include "teleportFiles" . | nindent 4 }}
    {{- end }}
```

Since, the include renders the teleportFiles define in parent chart, it doesn’t have access to the files, since it’s in sub-chart.

**Comment by tuladhar** [comment]
The work around is to pass the content of the file as a parameter to the named template or use it as a value. But it’s defeats the easy of use to add sub-chart as we need to adjust parent chart and make files available during render phase, via hacks.

**Comment by tuladhar** [comment]
Based on discussion with Pawel in standup, we'll define the files content directly into template, and see how that works. 

And, once that works, we'll move the sub-chart to it's own repo, and then use vendir to sync it from central repo.

**Comment by tuladhar** [comment]
Tested on glippy and it works! Now, next step is to move the subchart to proper location and reference that in cluster-apps.

Yesterday, Nikola from Team Turtles mention that they are working on a provider-independent cluster chart where almost all provider-independent resources will be. So whatever provider-independent stuff (subchart reference or resources themselves) we put into cluster-aws and other cluster apps, will move it to cluster chart.

**Comment by gawertm** [comment]
@nprokopic when do you expect we can move this one to the provider independent cluster chart? or should we in the mean time put this to capa chart?

**Comment by tuladhar** [comment]
Talked with Nikola. For now, we're moving ahead with CAPA chart, and  then move to provider independent cluster chart.

**Comment by tuladhar** [comment]
I've confirmed with Nikola, that with work done by Turtle on provider-independent cluster, this is now obsolete. Closing it!
