### ISSUE TITLE
pre-commit workflow failed here - should we do something about this?

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2857]
https://github.com/giantswarm/apptestctl/pull/329

**Comment by ljakimczuk** [comment]
The test is now green. The project indirectly uses the `github.com/klauspost/compress` package, and something has bumped it in the PR, though I cannot say what. When I executed the update procedure locally, it went well without upgrading this particular package. So I decided to use the `replace` directive to pin it to the currently used `github.com/klauspost/compress@v1.16.7` and it now works.

**Comment by ljakimczuk** [comment]
See https://github.com/giantswarm/apptestctl/pull/329/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R171
