### ISSUE TITLE
Expose option for dynamoDB vpc endpoint within GS Platform

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#286]
**Is your feature request related to a problem? Please describe.**

Traffic out of VPC to dyanamo service within AWS can get costly when there is heavy traffic. 

**Describe the solution you'd like**

Expose dynamoDB service as VPC endpoint 

**Describe alternatives you've considered**

Currently this can be done manually using aws-cli and does not interfere with GS Platform

**Additional context**

**Comment by teemow** [comment]
@alex-dabija @T-Kukawka this an old issue still labeled with firecracker? To phoenix or close?

**Comment by alex-dabija** [comment]
Crossplane might help with the creation of the endpoint. Old issue, closing for now.
