### ISSUE TITLE
Add Kyverno to default apps in preparation for 1.25 (CAPV to do)

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#2863]
Parent https://github.com/giantswarm/roadmap/issues/3144

**Comment by jkremser** [comment]
Kyverno w/o policies is not very useful. What policies should we ship together with the Kyverno app? In MC following are deployed:

```
giantswarm       kyverno-policies                                      0.20.1              16d          14d             deployed
giantswarm       kyverno-policies-connectivity                         0.5.3               16d          16d             deployed
giantswarm       kyverno-policies-dx                                   0.4.2               16d          16d             deployed
giantswarm       kyverno-policies-observability                        0.2.2               16d          16d             deployed
giantswarm       kyverno-policies-ux                                   0.7.0               16d          8d              deployed
giantswarm       kyverno-policy-operator                               0.0.1               14h          14h             deployed
```

imho the `kyverno-policies` would be good for start (https://github.com/giantswarm/kyverno-policies/tree/main/helm/kyverno-policies/charts/kyverno-policies/templates/restricted) perhaps running in the audit mode only.

- We will need `kyverno-policies-connectivity` in case if proxy is needed. 
- Also those `deprecatedAPI.x.yy` (in [here](https://github.com/giantswarm/kyverno-policies-dx/tree/main/helm/kyverno-policies-dx/templates)) can be super useful for customer to get an overall view on his workload cluster "updatability status".
- The `kyverno-policies-observability` can be ignored atm (it's meant to be only for monitoring stack running in mc)
- same for `kyverno-policies-ux` (mc stuff, cluster naming, organizations, etc)

`kyverno-policy-operator` according to readme, it watches on `PolicyException` from `policy.giantswarm.io` api group and translates it into `PolicyException` from `kyverno.io` api group. I am not sure how this can help here.

**Comment by erkanerol** [comment]
>  What policies should we ship together with the Kyverno app?
I think @giantswarm/team-shield should position one of the apps as WC policy apps. I am not sure.

Is there a parent issue with this? Do other teams move kyverno to default apps too?

**Comment by fhielpos** [comment]
We should do the same as we do now for vintage and ship the security bundle that includes both Kyverno and Kyverno Policies enabled.

Since this will be 1.25 then Kyverno should be enforcing, meaning it will block workloads without a proper exception.
cc/ @stone-z

**Comment by jkremser** [comment]
ah, good to know @stone-z I'll check the security bundle

**Comment by whites11** [comment]
this will be part of aws release 19.3.0

**Comment by vxav** [comment]
Can we close this? Is everyone aligned on this now?

**Comment by erkanerol** [comment]
Nope. We haven't added it to CAPV yet.

**Comment by vxav** [comment]
CAPV to do - closing because superseded by https://github.com/giantswarm/giantswarm/issues/29849
