### ISSUE TITLE
Visualise Dependency Graph of proposed Bundles

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2866]
### Motivation 
As we learned in https://github.com/giantswarm/roadmap/issues/2525 we have quite a complex dependency tree of the different components we use for our systems. Since we created a new bundle structure that should reduce this complexity, we now have to visualise the difference and how this proposed bundle structure would reduce the complexity. 

### Todo
- [ ] create a model of the dependency graph of the proposed bundles
  - visualize the dependency with arrows and work with the same layers/priorities as in the previous model

### Outcome
- We have a clear overview on the dependencies of the proposed bundles on each other
- We have a clear comparison on the complexity of the solution right now and after the introduction of the proposed bundles

**Comment by njuettner** [comment]
We have an overview of all the dependencies see https://miro.com/app/board/uXjVM0oMunQ=/?moveToWidget=3458764565777308646&cot=14.

Closing the issue for now, we have follow-up issues.
