### ISSUE TITLE
cluster-aws: Adapt to CAPA subnet spec changes

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2870]
Follow-up to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/4026 in which the breaking change was partially rolled back. The subnet `id` field now has 2 meanings (managed: use non `subnet-` prefixed key which by default is used as `Name` tag, unmanaged/bring-your-own: `id` field denotes the AWS subnet ID).

- Upgrade CAPA with the change from https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4474. See if it can migrate existing cluster-aws manifests nicely, or if not, we need to leave remarks in that PR.
- If it works out nicely, adapt cluster-aws to include the `id` field, but only after our CAPA app was upgraded on all clusters.

**Comment by T-Kukawka** [comment]
@AndiDog do u know how much effort is this to 'do'? How critical is it? Should we do it before we create CAPA production clusters instead of Vintage?

Upgrade of CAPA is done, so the question is about migration.

**Comment by AndiDog** [comment]
The upgrade isn't done yet on our side – the change will only be released in CAPA v2.3.0. I reviewed the change again and think that it won't be risky. We only need to change `cluster-aws` to introduce the AWSCluster.spec.network.subnets[].id` field for managed subnets. But that means at least CAPA v2.3.0 should run. So upgrading CAPA and changing+upgrading `cluster-aws` for all MCs/WCs must basically be done at once, or else CAPA will complain about the missing field and will not reconcile clusters. I guess we can do this pretty soon to avoid issues with production clusters. However, the [CAPA v2.3.0 milestone](https://github.com/kubernetes-sigs/cluster-api-provider-aws/milestone/41) isn't complete, so the release can still take weeks. We're probably better off prioritizing this by merging the change into our fork as a "pre-release hotfix" 😆. I could take this task since I still have the full context.

**Comment by AndiDog** [comment]
The v2.3.0 release had its CRDs corrected after the initial PR, so the `id` field becomes actually required:

```diff
--- a/helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml
+++ b/helm/cluster-api-provider-aws/files/controlplane/patches/versions/v1beta2/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml
@@ -370,0 +371,2 @@
+                    required:
+                      - id
@@ -372,0 +375,3 @@
+                  x-kubernetes-list-map-keys:
+                    - id
+                  x-kubernetes-list-type: map
```

So deploying a WC fails at cluster-aws installation:

```
Reason: Upgrade "andreas108" failed: failed to create resource: AWSCluster.infrastructure.cluster.x-k8s.io "andreas108" is invalid: spec.network.subnets[1]: Duplicate value: map[string]interface {}{"id":""}
```

I suggest we make this major change in two steps:

1. Deploy CAPA v2.3.0 to MCs, but without the above CRD diff (we comment it out and ignore temporarily that `make generate` output differs). As tested above, CAPA will happily fill the `id` field itself and reconcile just fine. Upgrade all workload clusters to a version of `cluster-aws` which sets the `id` field. Fix kubectl-gs to emit that field (an identifier not starting with `subnet-`).
2. Deploy latest CRDs that actually make the `id` field required and a unique key of the array-typed map `AWSCluster.spec.network.subnets`.

**Comment by AndiDog** [comment]
Reopening for now because with https://github.com/giantswarm/cluster-aws/pull/387 and https://github.com/giantswarm/cluster-api-provider-aws-app/pull/200, there are still temporary reverts in place that caused issues.

Next, I'm going to work on the EKS WC cluster creation error shown in https://github.com/giantswarm/roadmap/issues/3048:

```
E1213 13:17:04.251075       1 controller.go:324] "Reconciler error" err="failed to reconcile network for AWSManagedControlPlane org-giantswarm/vac0eks: failed to patch conditions: AWSManagedControlPlane.controlplane.cluster.x-k8s.io \"vac0eks\" is invalid: spec.network.subnets[7]: Duplicate value: map[string]interface {}{\"id\":\"\"}" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="org-giantswarm/vac0eks" namespace="org-giantswarm" name="vac0eks" reconcileID="12841c2f-7435-4f3b-9106-782a05e97702"
```

For that, I need to retest cluster-eks. It should have been solved by https://github.com/giantswarm/cluster-eks/pull/43, but maybe something else is missing.

Then, the CRDs inside the CAPA app can be fully updated to make the subnet `id` field actually required.
