### ISSUE TITLE
Support Object Storage on CAPA

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#2872]
To be able to provider proper observability on CAPA, we need to be able to create S3 buckets.

Possible ideas:
- [ ] Crossplane S3 provider. That means crossplane would need to be on all CAPA MCs cc @giantswarm/team-honeybadger 
- [ ] [AWS Controllers for Kubernetes](https://aws-controllers-k8s.github.io/community/)  That would require our cloud team to manage that.

From internal discussions, it was accepted that Cross plane was going to be the solution for this but are we in agreement that Crossplane will be deployed in all CAPA MCs?

**Comment by T-Kukawka** [comment]
input for the controller provided here: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1697725930731649?thread_ts=1697724081.329429&cid=C02HLSDH3DZ

**Comment by QuentinBisson** [comment]
Worked on https://github.com/giantswarm/object-storage-operator/pull/7

**Comment by QuentinBisson** [comment]
Hello team would it be possible to add the following permissions to the MC role so the operator works ?

I tested it on golem and I needed the following permissions added

"s3:ListBucket",
"s3:PutBucketAcl",
"s3:PutLifecycleConfiguration",
"s3:PutBucketOwnershipControls",
"s3:PutBucketTagging",


If not what would be the solution, use IRSA ?

**Comment by T-Kukawka** [comment]
If you want to reuse the MC creds u could add this here: https://github.com/giantswarm/giantswarm-aws-account-prerequisites/tree/master/capa-controller-role - then we will have to sync with customers to update the role if we start deploying for CAPA WCs for customers

**Comment by QuentinBisson** [comment]
Thanks @T-Kukawka and @QuantumEnigmaa.
@T-Kukawka do you know when WE could start deploying it to capa MCs?

**Comment by T-Kukawka** [comment]
After the controller is wrapped up and tested, we can add it to the collection to run on CAPA MCs

**Comment by QuentinBisson** [comment]
Sure I meant the role changes :D I added some tests on the operator over the weekend. I'm waiting for some peer reviews now :)

**Comment by T-Kukawka** [comment]
As the role is already created, it can be manually updated or done via: https://github.com/giantswarm/giantswarm-aws-account-prerequisites/tree/master/capa-controller-role#commands-to-execute

**Comment by QuentinBisson** [comment]
Could you ask someone from Phoenix to do that ? I like to not break any existing CAPA installations :)
