### ISSUE TITLE
Test managed Grafana on EKS

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2888]
Towards: https://github.com/giantswarm/roadmap/issues/2673

Ensure that Grafana can run as managed app on imported and adopted EKS clusters.

**Comment by QuantumEnigmaa** [comment]
I guess this should be done prior to https://github.com/giantswarm/roadmap/issues/2886

**Comment by QuantumEnigmaa** [comment]
`grafana` finally deployed on the `sample-customer` cluster on the `snail` installation : 
```
zirco@Zirko-laptop:~/Templates$ k get pods -n kube-system --kubeconfig=sample-customer.kubeconfig | grep grafana
grafana-7d6bc44c46-8ggd7                                        1/1     Running   0          3h53m
```

It's also working as intended when trying to access it : 
![image](https://github.com/giantswarm/roadmap/assets/64951262/ab624f12-b1f3-40e1-a71f-743aa87ef18b)

Obviously without any prometheus and/or dashboards, there aren't a lot of things to see.

**Comment by QuantumEnigmaa** [comment]
I guess one can ensure that grafana is working on EKS imported cluster. What are your thoughts @QuentinBisson ?

**Comment by QuentinBisson** [comment]
Good 🚀

**Comment by QuentinBisson** [comment]
Did you test on a CAPA managed EKS?

**Comment by QuantumEnigmaa** [comment]
> Did you test on a CAPA managed EKS?

Not yet, I wanted to first ensure Loki and Promtail are working on the same imported EKS cluster and use grafana to ensure this before moving to CAPA for both :)

**Comment by QuentinBisson** [comment]
Sure, sorry :D

**Comment by QuantumEnigmaa** [comment]
tested on a WC on `golem` with provider `eks` and working as well : 
```
zirco@Zirko-laptop:~$ k get pods -n kube-system | grep grafana
grafana-8d99d97f7-zrzmh                                        1/1     Running     0          156m
```
![image](https://github.com/giantswarm/roadmap/assets/64951262/b5911386-beb7-437b-8fb9-410a5b766d79)
