### ISSUE TITLE
RBAC Architecture intranet article is outdated

### ISSUE THREAD

**Issue by mogottsch** [giantswarm/roadmap#2889]
Some of the roles/bindings depicted in the [RBAC Architecture](https://intranet.giantswarm.io/docs/security/rbac-architecture/) article don't exist anymore.

The roles that don't exist anymore are:
- `write-clusters`
- `write-nodepools`
in these images:
- https://intranet.giantswarm.io/docs/security/assets/RBACOp.png
- https://intranet.giantswarm.io/docs/security/assets/DefaultNamespaceController.png

I'm not sure how the pictures were made though.

**Comment by mogottsch** [comment]
The images are made with draw.io and I tried to open the png's directly there. However, I got an error message that said "image too large".

@vvondruska I won't have any more time to work on this. Since you said that you know how to modify them, could you take a look? I listed the affected roles and images in the issue description above.

**Comment by OnurYilmazGit** [comment]
Update completed: The RBAC Architecture diagrams have been revised to remove the `write-clusters` and `write-nodepools` roles as they are no longer part of our architecture. 

PR for updated diagrams: 
https://github.com/giantswarm/giantswarm/pull/29621
