### ISSUE TITLE
Team BigMac - Test managed apps on `snail`+ EKS

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2893]
For our general approach to adopt EKS Cluster we need to test all our managed apps on `snail` + EKS. 
You can find the instructions to access the EKS cluster [here](https://github.com/giantswarm/giantswarm/issues/27377#issuecomment-1634311893)

The basic focus should be on permission-management and cert-management.
But there also could be more, that could be important like Dex as an app, feel free to reach out for any questions.

**Comment by ssyno** [comment]
Auth-Bundle and Cert-manager-app(3.4.0,3.5.0+) tested and work on WC deployed on Snail MC
