### ISSUE TITLE
Test AWS Release 19.3.0 without PSPs for default and Managed Apps - Atlas

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2899]
Following migration plan from PSP to PSS, Phoenix has prepared a `19.3.0` release with latest `security-bundle` in `kyverno enforce mode`. We have achieved the desired state where no PSP is deployed for any default apps tied to the release.

However all the default apps should be tested separately in terms of functionality by teams owning separate components.

Additionally with this release the Managed Apps also have to be tested if they handle the PSP disabling toggle.

`19.3.0` release is available on `gaia`, however it could be reverted or changed by anyone testing a separate component, hence here is a [yaml](https://github.com/giantswarm/releases/blob/aws-19.3.0/aws/v19.3.0/release.yaml
) to apply just in case on any testing MC.

The desired state for the cluster while testing the release should result in:

```
$ kubectl get pods -A -o custom-columns=PSP:\".metadata.annotations.kubernetes\.io/psp\"|sort|uniq 
<none>
PSP
```

and

```
$ kubectl get psp -A|awk '{print $1}'
NAME
privileged
```

In few cases we had to adjust the helm templates to force-disable PSP-related resources, this has been done for the `default` apps but was not tested for Managed Apps. Sample PR is available [here](https://github.com/giantswarm/chart-operator/pull/1033/files).

Action points:
- [ ] test default apps functionality in 19.3.0 + confirm force-disable PSP-related resources
	- [ ] [prometheus-operator](https://github.com/giantswarm/prometheus-operator-app)
	  - [ ] prometheus-operator
	  - [ ] prometheus
	  - [ ] alertmanager
	  - [ ] grafana
	  - [ ] kube-state-metrics
	  - [ ] node-exporter
	- [ ] [grafana](https://github.com/giantswarm/grafana-app)
	- [ ] [prometheus-agent](https://github.com/giantswarm/prometheus-agent-app)
	- [ ] metrics-server
- [ ] test managed apps functionality and PSP toggle with 19.3.0 + check for need to force-disable PSP-related resources
	- [ ] [loki](https://github.com/giantswarm/loki-app)
	  - [ ] loki
	  - [ ] loki-multi-tenant-proxy
	- [ ] [promxy](https://github.com/giantswarm/promxy-app)
	- [ ] [fluent-logshipping-app](https://github.com/giantswarm/fluent-logshipping-app)
	- [ ] [sloth-app](https://github.com/giantswarm/sloth-app)
	- [ ] [promtail](https://github.com/giantswarm/promtail-app)
	- [ ] [datadog](https://github.com/giantswarm/datadog-app)
	- [ ] [grafana-agent-app](https://github.com/giantswarm/grafana-agent-app)

**Comment by QuentinBisson** [comment]
Tested on Gaia, only grafana has a PSP and I could not test the apps in prometheus operator as something is overriding the config

**Comment by QuentinBisson** [comment]
Sloth and Promxy are MC apps only

**Comment by QuentinBisson** [comment]
Fixed grafana with a config change 🤦

**Comment by QuentinBisson** [comment]
See output:

```sh
k get chart -n giantswarm
NAME                                       VERSION       LAST DEPLOYED   STATUS
aws-cloud-controller-manager               1.24.1-gs10   100m            deployed
aws-ebs-csi-driver                         2.27.0        100m            deployed
aws-pod-identity-webhook                   1.13.2        91m             deployed
cert-exporter                              2.8.4         91m             deployed
cert-manager                               3.5.0         92m             deployed
chart-operator                             3.1.0         101m            deployed
chart-operator-extensions                  1.1.1         98m             deployed
cilium                                     0.16.0        100m            deployed
cilium-servicemonitors                     0.1.2         99m             deployed
cluster-autoscaler                         1.24.3-gs3    100m            deployed
coredns                                    1.19.0        100m            deployed
datadog                                    2.6.0         100m            deployed
etcd-kubernetes-resources-count-exporter   1.8.0         100m            deployed
external-dns                               2.42.0        98m             deployed
fluent-logshipping-app                     3.0.2         91m             deployed
grafana                                    2.6.0         79s             deployed
grafana-agent                              0.2.1         91m             deployed
irsa-servicemonitors                       0.0.1         98m             deployed
k8s-audit-metrics                          0.8.0         98m             deployed
k8s-dns-node-cache-app                     2.5.0         91m             deployed
kyverno                                    0.16.1        98m             deployed
kyverno-policies                           0.20.1        97m             deployed
kyverno-policy-operator                    0.0.4         97m             deployed
loki                                       0.14.1        79m             deployed
metrics-server                             2.4.1         99m             deployed
net-exporter                               1.18.0        98m             deployed
node-exporter                              1.18.1        99m             deployed
prometheus-agent                           0.6.5         97m             deployed
prometheus-blackbox-exporter               0.4.0         99m             deployed
prometheus-operator-app                    6.2.1         49m             deployed
prometheus-operator-crd                    6.1.0         99m             deployed
promtail-app                               1.4.0         92m             deployed
vertical-pod-autoscaler                    4.6.0         99m             deployed
vertical-pod-autoscaler-crd                2.0.1         101m            deployed
> kubectl get pods -A -o custom-columns=PSP:\".metadata.annotations.kubernetes\.io/psp\"|sort|uniq
<none>
PSP
> k get psp -A
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
NAME         PRIV   CAPS   SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
privileged   true   *      RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            *

```

**Comment by AverageMarcus** [comment]
Only the first half of this issue has been resolved. 
The `test managed apps functionality and PSP toggle with 19.3.0 + check for need to force-disable PSP-related resources` still needs addressing as not all of the managed apps respect the new config in `19.3.0`.

Any of these apps that have been installed into a workload cluster by a customer will need to have their values manually updated to disable PSPs ([example](https://github.com/giantswarm/workload-clusters-fleet/pull/756)) otherwise they will break on the upgrade to Kubernetes v1.25

**Comment by QuentinBisson** [comment]
@giantswarm/team-shield and @giantswarm/team-honeybadger I think this issue it not really about the apps but about the app-admission-controller not creating the [custom patches](https://github.com/giantswarm/config/blob/f99ab131f42c99c8bb3106fdf35f213824f08e2c/default/apps/app-admission-controller/configmap-values.yaml.template#L10) for apps that are managed by flux:

```
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"validating app `grafana` in namespace `cicddev`","time":"2024-02-05T19:14:24.813148+00:00"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"skipping validation of app 'cicddev/grafana' dependencies due to 'giantswarm.io/managed-by=flux' label","time":"2024-02-05T19:14:24.816818+00:00"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"skipping validation of app 'cicddev/grafana' dependencies due to 'giantswarm.io/managed-by=flux' label","time":"2024-02-05T19:14:24.816856+00:00"}
{"caller":"github.com/giantswarm/micrologger@v1.0.0/logger.go:66","level":"debug","message":"skipping validation of app 'cicddev/grafana' dependencies due to 'giantswarm.io/managed-by=flux' label","time":"2024-02-05T19:14:24.820061+00:00"}
```

I fully understand that this should be we loosen validation but the psp override should happen whether the app is managed by flux or not

**Comment by stone-z** [comment]
AFAIR we specifically used app-admission-controller because it would handle the flux apps, and I'm pretty sure it already is for other apps :thinking: obligatory "make sure everything is up to date" but in theory the patches should be getting applied (we're using them for a couple shield apps with subcharts as well)

**Comment by AverageMarcus** [comment]
> obligatory "make sure everything is up to date"

We have Renovate keeping everything in our WCs fully up to date.

**Comment by stone-z** [comment]
In any case, the validation controller is independent from the PSP mutation controller as they are different webhooks. 

But where are you seeing that message? Because I don't see that string in current `app-admission`controller`

**Comment by QuentinBisson** [comment]
For some reason, the mutations did not happen but I do not really have time to check :(

**Comment by stone-z** [comment]
Ok so something weird might have happened. If it happens again we can look for more info, but for now I don't think there's enough to go further with. The mutation is known/expected to be working for flux-managed apps and since the validation is a separate path I suspect the log line is a red herring

**Comment by QuentinBisson** [comment]
So closing for now :D
