### ISSUE TITLE
Test AWS Release 19.3.0 without PSPs for default and Managed Apps - Tinkerers

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2901]
Following migration plan from PSP to PSS, Phoenix has prepared a `19.3.0` release with latest `security-bundle` in `kyverno enforce mode`. We have achieved the desired state where no PSP is deployed for any default apps tied to the release.

However all the default apps should be tested separately in terms of functionality by teams owning separate components.

Additionally with this release the Managed Apps also have to be tested if they handle the PSP disabling toggle.

`19.3.0` release is available on `gaia`, however it could be reverted or changed by anyone testing a separate component, hence here is a [yaml](https://github.com/giantswarm/releases/blob/aws-19.3.0/aws/v19.3.0/release.yaml
) to apply just in case on any testing MC.

The desired state for the cluster while testing the release should result in:

```
$ kubectl get pods -A -o custom-columns=PSP:\".metadata.annotations.kubernetes\.io/psp\"|sort|uniq 
<none>
PSP
```

and

```
$ kubectl get psp -A|awk '{print $1}'
NAME
privileged
```

In few cases we had to adjust the helm templates to force-disable PSP-related resources, this has been done for the `default` apps but was not tested for Managed Apps. Sample PR is available [here](https://github.com/giantswarm/chart-operator/pull/1033/files).

Action points:
- [ ] test default apps functionality in 19.3.0 + confirm force-disable PSP-related resources
- [ ] test managed apps functionality and PSP toggle with 19.3.0 + check for need to force-disable PSP-related resources

**Comment by yulianedyalkova** [comment]
Closing as Tinkerers doesn't own any default or managed apps. There will be some efforts from our side when we upgrade the infra clusters to v19.3.0 but that shouldn't be blocking the release.
