### ISSUE TITLE
Enable customers to create App Catalog, so they have one way of managing apps

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#291]
3 customers are interested.

Business value: Increase usage of app platform.
User value: Customer can have one way of managing apps, instead of two (our way [App Catalog] and their way)

As a customer, I want to create my own App Catalog, so that we reduce the way we manage apps from two ways to one.

Note:
* **Customer wants to create their own app catalog without the need to have the code in a public repo. We discussed authorizing Helm to private registry.**
* This is already technically possible to do, we just need to write docs for it.
* Two ways customer manages apps: (1) Using our managed apps and (2) Private instance of gitlab, which they can only access via VPN. [Details here](https://docs.google.com/document/d/1Bk-E2UVUEm2-T0M9aFKP6uoiiUbqIADn5OKTklcpLm0/edit?usp=sharing).
* Two ways of doing this is confusing, especially if new engineer joins.

@T-Kukawka you can share w customer. cc @piontec

**Comment by cokiengchiara** [comment]
@yasn77 's customer is also using gitlab. See: [Slack](https://gigantic.slack.com/archives/CJSSNH2TT/p1622019778016600)

> I: Gitlab CI/CD - want to discuss the app catalog to define default installations for new clusters -   A: @Yasser to engage app team to discuss how app platform can be integrated into their Gitlab pipeline

**Comment by rossf7** [comment]
Catalog CRD is done so we can work on this. I checked with biscuit earlier and customers have admin access to their org namespace so we shouldn't need to change RBAC.

Dropping my assignment due to vacation.

cc @cokiengchiara

**Comment by rossf7** [comment]
We should also make sure custom catalogs appear in the Managed Apps and Managed Apps Upgrades dashboards added in https://github.com/giantswarm/roadmap/issues/322

**Comment by rossf7** [comment]
Docs are published https://docs.giantswarm.io/app-platform/create-catalog/
