### ISSUE TITLE
Registry Migration - review and update retagger synced images - Atlas

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2913]
For the first step of the registry migration story (see [the RFC](https://github.com/giantswarm/rfc/tree/main/single-registry-architecture) more detailed information) we need every team to review and update the retagger synced images that are used by the team. You can find the configures images [here](https://github.com/giantswarm/retagger/tree/main/images).

Therefore you need to do two things: 

- [ ] remove images that are not needed anymore at all 
- [ ] bump versions for images that are known to not use certain old versions any more

This will help us to keep the registry cleaner and in the end also cheaper.

**Comment by QuentinBisson** [comment]
List of atlas apps to check:
- kube-state-metrics/kube-state-metrics
- metrics-server/metrics-server
- prometheus-operator/prometheus-config-reloader:
- prometheus-operator/prometheus-operator:
- prometheus/alertmanager:
- prometheus/node-exporter:
- prometheuscommunity/elasticsearch-exporter:
- thanos/thanos
- google-cloud-tools/kube-eagle
- coreos/prometheus-config-reloader:
- coreos/prometheus-operator
- coreos/configmap-reload:
- slok/sloth
- janeczku/go-dnsmasq:
- jgsqware/fluentd-loki-plugin:
- jollinshead/journald-cloudwatch-logs:
- k8spin/loki-multi-tenant-proxy:
- prom/cloudwatch-exporter:
- amazon/opendistro-for-elasticsearch:
- amazon/opendistro-for-elasticsearch-kibana:
- bats/bats: (used in grafana)
- fluent/fluent-bit:
- grafana/grafana:
- grafana/grafana-image-renderer:
- grafana/loki:
- grafana/loki-canary:
- grafana/mimir:
- grafana/mimir-continuous-test:
- grafana/promtail:
- grafana/tempo:
- jettech/kube-webhook-certgen:       # Used in prometheus-operator-app
- jimmidyson/configmap-reload:
- justwatch/elasticsearch_exporter:
- kiwigrid/k8s-sidecar:
- memcached:
- omnition/opencensus-collector:
- opensearchproject/opensearch:
- opensearchproject/opensearch-dashboards:
- prom/memcached-exporter:
- prom/prometheus:
- prom/pushgateway:
-  elasticsearch/elasticsearch-oss:
- kibana/kibana-oss:
- bitnami/memcached
- bitnami/memcached-exporter
- bobrik/curator
- caicloud/event-exporter
- cloudflare/cloudflared
- docker.io/grafana/agent
- fluent-bit-aws-plugins
- fluent-bit-systemd247-aws-plugins
- jaeger-all-in-one
- macropower-analytics-panel-server
- elasticsearch-untergeek-curator

**Comment by QuentinBisson** [comment]
Well that's a bit too much :D

**Comment by QuentinBisson** [comment]
I'd advocate that we use a recording rules to push all images in use in grafana

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas wdyt about:

```promql
label_replace(
  label_replace(
      count by (pod, image) (kube_pod_init_container_info{image=~".*giantswarm.*"})
    or
        count by (pod, image) (kube_pod_container_info{image=~".*giantswarm.*"})
      * on (pod) group_left (label_application_giantswarm_io_team)
        kube_pod_labels,
    "team",
    "$2",
    "label_application_giantswarm_io_team",
    "(team-)?(.*)"
  ),
  "label_application_giantswarm_io_team",
  "",
  "label_application_giantswarm_io_team",
  ".*"
)
```

**Comment by QuentinBisson** [comment]
See https://giantswarm.grafana.net/explore?panes=%7B%22-6v%22:%7B%22datasource%22:%22000000006%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22count%28aggregation:container:images%29%20by%20%28image%29%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22000000006%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1

**Comment by kubasobon** [comment]
:wave: Hello friends, what's the status on this?

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa maybe you can double check https://github.com/giantswarm/retagger/pull/941 ?

**Comment by QuentinBisson** [comment]
Done :)
