### ISSUE TITLE
For workload clusters supporting OIDC auth, the web UI should support updating kubeconfig

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#292]
For workload clusters that do not support OIDC authentication for the Kubernetes API, the web UI supports the creation of key pairs. (Also in the `gsctl` CLI there is the `gsctl create kubeconfig` command).

For workload clusters with OIDC enabled, the web UI should support users in updating their kubectl configuration (kubeconfig) accordingly. In the simplest form, this could be done by providing a stand-alone YAML file, or by providing the user/server/context snippets to copy and paste.

**Comment by marians** [comment]
For the web UI in order to detect whether a workload cluster is configured for OIDC auth, we have several annotations on the Cluster CR:

- `oidc.giantswarm.io/client-id`
- `oidc.giantswarm.io/group-claim`
- `oidc.giantswarm.io/issuer-url`
- `oidc.giantswarm.io/username-claim`

([Source](https://github.com/giantswarm/apiextensions/blob/v3.2.0/pkg/annotation/oidc.go))

If these annotations were present, a MAPI aware web UI could decide to show the workload cluster as OIDC enabled.

Problem: Currently these annotations are not set on all OIDC enabled workload clusters.

Once we have this information available on the Cluster CR, we can also use it in the web UI in order to either

- show the `kubectl config ...` commands needed in order to configure access or
- offer a complete, stand-alone kubeconfig file for download.

**Comment by puja108** [comment]
there's followup issues of this, e.g. #116
