### ISSUE TITLE
Registry Migration - review and update retagger synced images - Phoenix

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2920]
For the first step of the registry migration story (see [the RFC](https://github.com/giantswarm/rfc/tree/main/single-registry-architecture) more detailed information) we need every team to review and update the retagger synced images that are used by the team. You can find the configures images [here](https://github.com/giantswarm/retagger/tree/main/images).

Therefore you need to do two things: 

- [x] remove images that are not needed anymore at all 
- [x] bump versions for images that are known to not use certain old versions any more

This will help us to keep the registry cleaner and in the end also cheaper.

**Comment by T-Kukawka** [comment]
-[ ] name: apiextensions

-[ ] name: apiextensions-backup

-[ ] name: area-oncall-scheduler

-[ ] name: aws-admission-controller

-[ ] name: aws-attach-etcd-dep

-[ ] name: aws-cloud-controller-manager-app

-[ ] name: aws-cni-app

-[ ] name: aws-collector

-[ ] name: aws-ebs-csi-driver-app

-[ ] name: aws-ebs-csi-volume-limiter

-[ ] name: aws-efs-csi-driver

-[ ] name: aws-iptables-legacy-cleaner

-[ ] name: aws-load-balancer-controller-app

-[ ] name: aws-network-topology-operator

-[ ] name: aws-node-termination-handler-app

-[ ] name: aws-operator

-[ ] name: aws-pod-identity-webhook

-[ ] name: aws-resolver-rules-operator

-[ ] name: aws-rolling-node-operator

-[ ] name: aws-servicequotas-operator

-[ ] name: aws-tccpf-watchdog

-[ ] name: aws-vpc-operator

-[ ] name: azure-ad-pod-identity-app

-[ ] name: azure-admission-controller

-[ ] name: azure-cloud-controller-manager-app

-[ ] name: azure-cloud-node-manager-app

-[ ] name: azure-collector

-[ ] name: azure-operator

-[ ] name: azure-scheduled-events

-[ ] name: azuredisk-csi-driver-app

-[ ] name: azurefile-csi-driver-app

-[ ] name: cadvisor-app

-[ ] name: calico-policy-only-app

-[ ] name: capa-iam-operator

-[ ] name: capg-firewall-rule-operator

-[ ] name: capg-garbage-collector

-[ ] name: capz-app-collection

-[ ] name: cert-operator

-[ ] name: certctl

-[ ] name: certs

-[ ] name: cluster-api-provider-aws-app

-[ ] name: cluster-api-provider-azure-app

-[ ] name: cluster-api-provider-gcp-app

-[ ] name: cluster-aws

-[ ] name: cluster-azure

-[ ] name: cluster-eks

-[ ] name: cluster-gcp

-[ ] name: conditions

-[ ] name: conditions-handler

-[ ] name: default-apps-aws

-[ ] name: default-apps-azure

-[ ] name: default-apps-eks

-[ ] name: default-apps-gcp

-[ ] name: descheduler-app

-[ ] name: dns-operator-azure

-[ ] name: dns-operator-gcp

-[ ] name: dns-tester

-[ ] name: encryption-config-hasher

-[ ] name: encryption-provider-operator

-[ ] name: fleet-membership-operator-gcp

-[ ] name: gcp-compute-persistent-disk-csi-driver-app

-[ ] name: giantnetes-terraform

-[ ] name: giantswarm-aws-account-prerequisites

-[ ] name: irsa-operator

-[ ] name: karpenter-app

-[ ] name: kiam-app

-[ ] name: kiam-watchdog

-[ ] name: oms-agent-app

-[ ] name: outgoing-proxy-stack

-[ ] name: prometheus-blackbox-exporter-app

-[ ] name: releases

-[ ] name: releases-test-catalog

-[ ] name: resource-police

-[ ] name: route53-manager

-[ ] name: squid-proxy-app

-[ ] name: standup

-[ ] name: statusresource

-[ ] name: tenantcluster

-[ ] name: to

-[ ] name: vault-app

-[ ] name: vault-etcd-backups-exporter

-[ ] name: vault-exporter

-[ ] name: workload-identity-gcp-utils

-[ ] name: workload-identity-operator-gcp

**Comment by T-Kukawka** [comment]
Priority takes apps that are not used

**Comment by T-Kukawka** [comment]
From refinement Docker hub has a feature to mark certain images as active/used/unused. However we also use Quay and ACR.

**Comment by T-Kukawka** [comment]
Final PR out, should be done tomorrow

**Comment by T-Kukawka** [comment]
done
