### ISSUE TITLE
Registry Migration - review and update retagger synced images - Rocket

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2921]
For the first step of the registry migration story (see [the RFC](https://github.com/giantswarm/rfc/tree/main/single-registry-architecture) more detailed information) we need every team to review and update the retagger synced images that are used by the team. You can find the configures images [here](https://github.com/giantswarm/retagger/tree/main/images).

Therefore you need to do two things: 

- [ ] remove images that are not needed anymore at all 
- [ ] bump versions for images that are known to not use certain old versions any more

This will help us to keep the registry cleaner and in the end also cheaper.

**Comment by glitchcrab** [comment]
images to investigate:

- kube-vip/kube-vip:
- kube-vip/kube-vip-cloud-provider:
- gcr.io/cloud-provider-vsphere/cpi/release/manager
- gcr.io/cloud-provider-vsphere/csi/release/driver
- gcr.io/cloud-provider-vsphere/csi/release/syncer
- gcr.io/cluster-api-provider-vsphere/release/manager
- projects.registry.vmware.com/vmware-cloud-director/cloud-director-named-disk-csi-driver
- projects.registry.vmware.com/vmware-cloud-director/cloud-provider-for-cloud-director

**Comment by glitchcrab** [comment]
completed
