### ISSUE TITLE
Registry Migration - review and update retagger synced images - Shield

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2922]
For the first step of the registry migration story (see [the RFC](https://github.com/giantswarm/rfc/tree/main/single-registry-architecture) more detailed information) we need every team to review and update the retagger synced images that are used by the team. You can find the configures images [here](https://github.com/giantswarm/retagger/tree/main/images).

Therefore you need to do two things: 

- [ ] remove images that are not needed anymore at all 
- [ ] bump versions for images that are known to not use certain old versions any more

This will help us to keep the registry cleaner and in the end also cheaper.

**Comment by fhielpos** [comment]
@Strigix , can you check what is the oldest falco running in customers workloads (App Status dashboard in Grafana) and see if we can increase the version used in retagger? Are we using all of them?

https://github.com/giantswarm/retagger/blob/main/images/skopeo-docker-io.yaml#L141:152

**Comment by fhielpos** [comment]
Kyverno images are as high as they can be ✅ 

Need to check trivy, trivy-operator and others that I may be missing.

**Comment by Strigix** [comment]
Hey @fhielpos , sorry for the late reply.
Pretty much all clusters are on Falco (app) version 0.7.0, except for potato, puma, and Glasgow. 

So I'll do a quick check of the versions and update the version numbers in the retagger :)

**Comment by stone-z** [comment]
@Strigix it would be fine to just have all of our images set to the equivalent of "the current release version and higher". Retagger won't remove the older images

**Comment by Strigix** [comment]
Sure thing, that's what you said in stand-up right? :D 
Consider it done.

**Comment by Strigix** [comment]
For note keeping, yet to check and remove: 

- [ ] prowler
- [ ] polaris
- [ ] kube-bench
- [ ] gitleaks
- [ ] OPA Gatekeeper
- [ ] Trivy(-Operator)

**Comment by kubasobon** [comment]
:wave: Hello friends. Is this safe to close?

**Comment by stone-z** [comment]
Just waiting on https://github.com/giantswarm/retagger/pull/940 then done

**Comment by Strigix** [comment]
Done 😁
