### ISSUE TITLE
CAPA Kubernetes 1.25 WC release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2925]
How can we move to CAPA with PSS:

### 1. On 1.24 k8s in CAPA:

1a - add `security-bundle` in with kyverno in  'enforce' mode (1.*>) to default apps for capa and deploy. With this update all apps have to be update to the version that has PSS implementation. Here both PSPs and PSS are working in pararell. Upgrade the WCs with this version.

1b - in `cluster-aws` add the toggle value `global.podSecurityStandards.enforced: true` to all apps configurations so they can consume this value while being deployed with HelmReleases.
1b - Add label `policy.giantswarm.io/psp-status: disabled` to cluster-aws Cluster CR template (`helm/cluster-aws/templates/_cluster.tpl`). The label will be consumed by app-admission-controller, if set to `true` it will populate the `.global.podsecuritystandards.enforced set to true` to all default and Managed apps deployed.
1b - Update cluster to this cluster-aws version

1c - The PSPs should be removed automatically based on the flag.

### 2. Upgrade to k8s 1.25 
```[tasklist]
### Tasks
- [x] Update app-admission-controller for handling CAPI cluster label `policy.giantswarm.io/psp-status: disabled`
```

**Comment by alex-dabija** [comment]
@stone-z I talked with Phoenix today and they mentioned to use the solution described in this issue to enable PSS for CAPI clusters. I think it's easier then the alternatives we discussed yesterday.

**Comment by stone-z** [comment]
I am not familiar at all with cluster-apps-operator and CAPI apps generally, but my understanding based on previous conversations was that the cluster-level value is not guaranteed to be correctly set for all apps.

But if that's different on CAPI, and Phoenix is confident in this approach, I'm happy to save the manual step.

**Comment by T-Kukawka** [comment]
right, we completely forgot about the app-bundles like observability that were not propagated well

**Comment by T-Kukawka** [comment]
@stone-z we updated the plan ⏫

**Comment by Strigix** [comment]
@stone-z I'm willing to give it a try, but would you be able to gives me a small walkthrough on Tuesday? During the 1-on-1 maybe.

**Comment by stone-z** [comment]
@Strigix and I discussed.

Shield will implement the following:
- pss-operator currently watches `cluster.x-k8s.io` CRs and forces App reconciliation for all Apps in a cluster, based on the vintage release version label. It will be extended to also force reconciliation based on the new label*
- app-admission-controller currently injects extraConfig ConfigMaps to App CRs only for vintage providers based on their release version. It will be extended to inject the extraConfig also for **all** CAPI clusters.

Shield will not make the changes to `cluster-aws` or other CAPI-specific resources.

We need / suggest the following:
- I suggest the label used on the Cluster CRs should be `policy.giantswarm.io/psp-status: disabled`. This is the same label being applied to App CRs to force CM injection, and it semantically represents the intent better (i.e. "PSPs are disabled" --> don't deploy PSPs vs. "PSS is enforced" --> don't deploy PSPs). Speak up if it is too confusing to use the same label on both Cluster and App CRs.
- This logic will apply to all CAPI clusters at once when the components are released. Provider teams should be aware of this and take care not to accidentally add or remove the label from their cluster templates.

**Comment by T-Kukawka** [comment]
@stone-z sounds good to me with the proposed changes, i have adjusted the main description of the ticket.

@gawertm and @erkanerol have the stakes here as well as same solution will be applicable for CAPZ and there is a pressure from customer side to move to 1.25 as soon as possible in order to avoid double work with PSP/PSS migration. It might come sooner than CAPA, not sure if there is a ticket.

**Comment by gawertm** [comment]
@erkanerol please confirm the suggested approach from @stone-z is fine for us. (lgtm)

@stone-z when can we expect the changes from shield? We currently have Wepa that really wants to start directly with 1.25+ and we are just waiting on this to upgrade the clusters for them / the MC

**Comment by stone-z** [comment]
The changes are already in progress but since we've not really tested anything CAPI creation/update related I suspect it'll take our folks some time to test properly. Does Rocket maybe have someone who could pair with Stefan to test the changes (probably next week sometime)?

**Comment by erkanerol** [comment]
I can help @Strigix to test the changes on CAPZ. Let's collaborate 👍

**Comment by stone-z** [comment]
The support components have both been released 🎉 
Done from the Shield side

**Comment by T-Kukawka** [comment]
the plan was tested by CAPZ and can be followed by CAPA

**Comment by erkanerol** [comment]
I created a similar ticket for CAPVCD and summarized what we have done for CAPZ until now. Please check it. https://github.com/giantswarm/roadmap/issues/3144

**Comment by mnitchev** [comment]
Done with https://github.com/giantswarm/cluster-aws/releases/tag/v0.60.0
