### ISSUE TITLE
Add CLI support for importing an EKS cluster

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#2928]
In the context of importing EKS clusters (and potentially clusters from other providers), we want our CLI (kubectl-gs) to support the importing of a cluster.
```[tasklist]
### Tasks
- [ ] Spec
- [ ] Implementation
- [ ] Documentation
```

**Comment by weatherhog** [comment]
@marians are you okay with closing this? or is this still needed?

**Comment by marians** [comment]
No priority currently, closing
