### ISSUE TITLE
Expose `additionalTags` value from CAPA in `cluster-aws` and `cluster-eks`

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2929]
Based on the CAPA implementation: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1113

We should be able to expose `additionalTags` value in our `cluster-aws` and `cluster-eks` for tagging the AWS Resources. This feature is highly wanted by customers either for cost tracking or security processes.

Initial implementation should consider the population of the tags during creation of clusters only, however besides CAPI controllers we have to extend population of the tags also within our custom controllers.

**Comment by calvix** [comment]
TODO

- [x] cluster aws - expose tag value - https://github.com/giantswarm/cluster-aws/pull/405
- [ ] cluster-eks expose tag value - https://github.com/giantswarm/cluster-eks/pull/30
- [ ] aws-resolver-rules-operator - https://github.com/giantswarm/aws-resolver-rules-operator/pull/105
- [ ] irsa-operator https://github.com/giantswarm/irsa-operator/pull/170
- [ ] capa-iam-operator
- [ ] aws-vpc-operator
- [ ] -aws-network-topology-operator

**Comment by calvix** [comment]
S3 buckets for ignition are not tagged in the latest CAPA controller release, I was checking the code and found out that @AndiDog actually implemented it :p wow
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4518

**Comment by AndiDog** [comment]
I'll try to cherry-pick the S3 tagging change into our fork

**Comment by calvix** [comment]
unfortunately, the changes in capa-controller only add basic tags
```
sigs.k8s.io/cluster-api-provider-aws/role: node
sigs.k8s.io/cluster-api-provider-aws/cluster/vac0t: owned
```

but do not add tags under 
```
 #: kcapa get awscluster vac0t -o yaml  | grep -A 3 spec
spec:
  additionalTags:
    giantswarm.io/cluster: vac0t
    vaclav: vaclavTag
```

that means customer tags are not applied, this will need to be fixed in the capa controller

**Comment by AndiDog** [comment]
I'll take care of `AdditionalTags` – not hard to do.

**Comment by AndiDog** [comment]
Fixed in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4625 and I'll cherry-pick it immediately into our fork because it's so straightforward and unlikely that the PR content changes.

**Comment by calvix** [comment]
LGTM
