### ISSUE TITLE
Grafana dashboard tracking change of resource usage with link to underlying workloads

### ISSUE THREAD

**Issue by luca-rui** [giantswarm/roadmap#2931]
Towards EPIC_URL

## User Story

- As an AE and/or customer, I would like trace the change of usage back to the actual workload causing it via a Grafana dashboard. This dashboard would be a great tool for controlling the resource usage of workloads.

P.S.: I’m envisioning something like making regular snapshots of `kubectl top pod -A` for every cluster, then IF difference of CPU/Mem usage increases more than X (e.g. 20%) over a user-specified length of time Y (e.g. 3 months) show me the evolution of those snapshots in a meaningful way. 

Related [Slack thread](https://gigantic.slack.com/archives/C01176DKNP4/p1696853851763449)

**Comment by Rotfuks** [comment]
Since there was no further questions we assume the linked dashboard is enough. Thanks! Closing the issue then.
