### ISSUE TITLE
Deploy Loki on CAPA installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2934]
Towards: https://github.com/giantswarm/roadmap/issues/2935

- [ ] Add the S3 bucket CR in Loki app
- [x] Deploy Loki on CAPA installations https://github.com/giantswarm/loki-app/pull/235

**Comment by QuentinBisson** [comment]
I added the bucket to the logging operator so the Bucket CR remains a private use case

**Comment by QuentinBisson** [comment]
Currently stuck because LOKI needs a role to access it's s3 bucket that we currently cannot create in an automatic way on CAPA MCs

**Comment by QuentinBisson** [comment]
Fixed
