### ISSUE TITLE
Add support for CAPA provider in logging-operator

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2937]
In order to deploy the logging infrastructure on CAPA we need to add support for CAPA within the logging-operator.

**Comment by TheoBrigitte** [comment]
https://github.com/giantswarm/logging-operator/pull/62

**Comment by QuentinBisson** [comment]
PR is ready and tested, waiting for reviews so we can go ahead

**Comment by QuentinBisson** [comment]
After some discussions with the team, we agreed to remove all cloud related things from the logging operator and move them over to the object storage operator (i.e. access role creation).

- CAPI support is then done https://github.com/giantswarm/logging-operator/pull/81
This PR mostly removes values that were added when loki role was created in the logging operator merged in a previous PR https://github.com/giantswarm/logging-operator/pull/79
- Role access creation is now done in object-storage-operator: https://github.com/giantswarm/object-storage-operator/pull/26
- Bucket CR is added here https://github.com/giantswarm/config/pull/2059

**Comment by QuentinBisson** [comment]
Done and released
