### ISSUE TITLE
Enable logging for all CAPA installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2938]
In order to enable logging on CAPA we need to manually configure this in the [config](https://github.com/giantswarm/config) repository.

PR to deploy logging stack everywhere https://github.com/giantswarm/config/pull/2044

**Comment by QuentinBisson** [comment]
Waiting for logging operator to be reviewed before merging this

**Comment by QuentinBisson** [comment]
This is blocked to be merged once #2937 is closed

**Comment by TheoBrigitte** [comment]
Since we have [logging enabled by default](https://github.com/giantswarm/roadmap/issues/2835) do we still need this ?

**Comment by QuentinBisson** [comment]
Yes, logging is on by default as long as the installation flag is set to true

**Comment by TheoBrigitte** [comment]
https://github.com/giantswarm/roadmap/issues/2937 was closed, removing the blocked label.
