### ISSUE TITLE
Customizable apps deployed via HelmRelease in cluster-aws

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2940]
Currently we do not have a mechanism that would allow to easily customize the apps deployed via Helm release in cluster-aws. Possibly we should implement similar approach that we have with the default apps, where all customizations can be done in a single place for all apps.

**Comment by AndiDog** [comment]
@nprokopic, do you have an idea how/when you would tackle this? I'd like to use it in #2563 instead of adding more specific values such as `.Values.network.ciliumEniMode`. If you're overloaded, I could also implement the suggestion for _this_ issue.

**Comment by nprokopic** [comment]
I added that to be done as a part of this https://github.com/giantswarm/roadmap/issues/2954, which is currently in progress and should be finished in the upcoming days.

**Comment by calvix** [comment]
> @nprokopic, do you have an idea how/when you would tackle this? I'd like to use it in #2563 instead of adding more specific values such as `.Values.network.ciliumEniMode`. If you're overloaded, I could also implement the suggestion for _this_ issue.

I would leave out ` .Values.network` out of this and rather configure any app in some separate field like `.Values.apps.cilium.ciliumEniMode` Mixing infrastructure network with cilium does not sound like a good idea to me.

**Comment by AndiDog** [comment]
The HelmRelease values are now customizable, so this should be done.
