### ISSUE TITLE
Setup logging on CAPV installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2943]
Towards: https://github.com/giantswarm/roadmap/issues/311

In order to expand our logging infrastructure coverage we should extend support to CAPV installations.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/3165
- [ ] https://github.com/giantswarm/roadmap/issues/3167
```

**Comment by QuentinBisson** [comment]
Done
