### ISSUE TITLE
Watching: Future of NGINX Ingress

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#295]
@corest posted in [Slack](https://gigantic.slack.com/archives/CRZN9GLJW/p1618904009282800) the post from k8s dev-list that the people who've been supporting the project are running out of bandwidth to maintain it.

<details>

> Hi SIG,
> As most of you already know, Alejandro stepped down from being the maintainer of ingress-nginx (github.com/kubernetes/ingress-nginx). We are really thankful for all the effort Alejandro has put on the past years in ingress-nginx, myself as an example of a heavy user of the software.
In the past few weeks, I've tried to think into how to keep this project being developed, as A LOT OF USERS still rely on this. (I've heard somewhere that ingress-nginx is the second mostly used Kubernetes project, only behind Kubernetes itself)
> The fact is: We have a few people engaged with the project nowadays, and all of them have few to no bandwidth for all the tasks: issue triage, bug fix, feature requests, support.
> So I was talking with Elvin (who is actually maintaining the project) + Bowei and would like to propose the following:
> * We need to discuss what's the mid and long term plan for Ingress NGINX. What do we want the project to be? Enter in maintenance mode and we only fix bugs? Keep accepting features? Be an official part of sig-network (it actually is, but became more active as netpol, kproxy, etc).
> * How to engage the community with the project? I have in mind some things:
> 1) Create a recurring official meeting (bi-weekly? monthly?) to make some issue triage and discuss some pain points of the project.
> 2) In case of support issues, close them directing users to get help in discuss/slack/stackoverflow. I know this might sound a bit aggressive, but there's too much support issues and a few people to triage all of them :)
> 3) In case of bug fixes and feature requests, discuss them during the meeting the same way we do in sig-net and other SIGs and subprojects, trying to assign people from the community to triage them
> 4) For PRs it would be good to have more people effectively reviewing them. So the idea is to make some attempt to engage people to review the PRs during the meeting when time is available. 
> We need the community to participate in this, and understand that it's not only a matter of requesting something/opening an issue and waiting for someone to fix it (otherwise, no one is going to maintain it). Ideas are welcome.
> And just to clarify, I have no bandwidth to keep this going for a long time, so anyone willing to help (or run this!) is really welcome!

</details>

Most of our customers use NGINX and use code snippets and annotations that only work on Nginx.

Talked w @giantswarm/team-halo briefly .

1. Team seems confident someone will step up - it's a great opportunity to step up on an important upstream project
2. In case no one does, @piontec can start by drafting alternatives we can use.

So current strategy is to keep watch.

cc @giantswarm/team-halo @puja108 @teemow 

---

The other thing we didn't discuss -- would it make sense for us to allocate resources to help maintain it?

From commercial perspective, I don't think it makes sense. Because: (1) NGINX is only one of the many apps we provide and (2) Customers expect it to be 'just there' and don't see it as added value in our offering.

However, I have to admit, I don't know the 'right' behaviors in how to play with upstream yet...

**Comment by ubergesundheit** [comment]
Development has been picked up, we can close this one
