### ISSUE TITLE
Increase Cluster Name limit to 20 characters

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2958]
request from a customer, to be tested

**Comment by ssyno** [comment]
Issue resolved on the following PRs:
kubectl-gs [ NameLengthLong update to 20 #1198 ](https://github.com/giantswarm/kubectl-gs/pull/1198)
kyverno-policies-ux [ Cluster name length to 20 chars #73 ](https://github.com/giantswarm/kyverno-policies-ux/pull/73)
