### ISSUE TITLE
kubectl gs get clusters does not work as intended

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#2966]
More context can be found in [this comment](https://github.com/giantswarm/giantswarm/issues/28611#issuecomment-1811994962)

`kubectl gs get clusters` is supposed to show the user all clusters in organizations they have access to. Instead, an admin user will see no clusters while a non-admin user (who does have access to _some_ organization(s)) will see an error.

**Comment by weatherhog** [comment]
closing this as the mentioned issue also got closed
