### ISSUE TITLE
Upgrade CAPZ to 1.25

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2970]
we dont want to deal with PSP to PSS migration for CAPZ but instead directly install clusters with 1.25

**Comment by erkanerol** [comment]
Related https://github.com/giantswarm/roadmap/issues/2925

**Comment by erkanerol** [comment]
I hit a circular dependency issue. Here are the details https://gigantic.slack.com/archives/C01F7T2MNRL/p1701163395572529

**Comment by erkanerol** [comment]
We have 3 problems now:
1) Circular dependency between CNI, CSI and kyverno -> Effects installation&upgrade -> Waiting for Zach
2) There is no mechanism to enable PSSs in all apps -> Waiting for Shield
3) While disabling PSPs in 1.24 before upgrades, apps fail since PSP checks are still active.

**Comment by erkanerol** [comment]
## The status

We have a few open PRs. After merging those PRs and releasing and deploying up-to-date versions, we will be ready for 1.25.

- https://github.com/giantswarm/pss-operator/pull/11
  - A new version with this PR should be released and deployed to all MCs.
- https://github.com/giantswarm/app-admission-controller/pull/381
- https://github.com/giantswarm/default-apps-azure/pull/179
- https://github.com/giantswarm/cluster-azure/pull/179
 

## Tested scenarios

### Upgrade from existing 1.24 clusters

- Update `default-apps-azure` to `0.6.0` (will be released with my changes).
- Observe all apps are OK.
- Observe security-bundle is installed and there are policies in enforce mode in the cluster. `kubectl get clusterpolicy -A`

- Update `cluster-azure` to `0.0.30` (will be released with my changes) by setting `global.podSecurityStandards.enforced=true`
- Observe `kubectl get clusterrolebinding privileged-psp-allow-all` in the cluster. It means PSPs are not blocking anything anymore.
- Observe all `HelmRelease` CRs are OK.

- Bump `internal.kubernetesVersion` to `1.25.15` in `cluster-azure` configuration.
- Observe version of all nodes are up-to-date.
- Observe PSPs are gone.
- Observe all apps are OK.
- Observe all pods are OK.


### Install fresh 1.24 clusters
- Install cluster-azure `0.0.30` (will be released with my changes) by setting `global.podSecurityStandards.enforced=true` and `default-apps-azure` `0.6.0` (will be released with my changes).
- Observe security-bundle is installed and there are policies in enforce mode in the cluster. `kubectl get clusterpolicy -A`
- Observe `kubectl get clusterrolebinding privileged-psp-allow-all` in the cluster. It means PSPs are not blocking anything anymore.
- Observe all apps are OK.
- Observe all pods are OK.

### Install fresh 1.25 clusters
- Install cluster-azure `0.0.30` (will be released with my changes) by setting `global.podSecurityStandards.enforced=true` and `internal.kubernetesVersion=1.25.15` 
- Install `default-apps-azure` `0.6.0` (will be released with my changes).
- Observe security-bundle is installed and there are policies in enforce mode in the cluster. `kubectl get clusterpolicy -A`
- Observe PSPs are gone.
- Observe all apps are OK.
- Observe all pods are OK.

## Next steps

- We will release another `cluster-azure` version by setting `global.podSecurityStandards.enforced=true` by default and setting Kubernetes version as `1.25`
- Users will be able to create 1.25 clusters without setting `global.podSecurityStandards.enforced=true` explicitly.


## Further steps

- We should update all clusters to 1.25 or newer version and set `global.podSecurityStandards.enforced=true` for all apps by default.
- Then we should decommision the app mutation logic in app-admission-controller and pss-operator completely.

**Comment by erkanerol** [comment]
With cluster-azure:0.0.30  and default-apps-azure:0.7.0 , we are able to create 1.25 clusters by setting these in cluster-azure.

```
global:
  podSecurityStandards:
    enforced: true
internal:
  kubernetesVersion: 1.25.15
  image:
    version: 3510.2.5
```

Next steps:
- [ ] Upgrading MCs to this version
- [ ] Adapting MC apps
- [ ] Upgrading MCs to 1.25
- [ ] Adapting mc-bootstrap
- [ ] Making these values as default in cluster-azure

**Comment by erkanerol** [comment]
Flux is the blocker now for 1.25 upgrades in MCs. See https://gigantic.slack.com/archives/C02GDJJ68Q1/p1702378380447159

We are waiting for a fix.

**Comment by erkanerol** [comment]
@allanger fixed my test cluster with a workaround and I am testing the other apps via [this](https://github.com/giantswarm/config/commit/dca241fb2d15911ab469967fbfa8de7f8e48614f) PR. I found several issues 🤦 


***Failing apps when we enforce PSSs***

- [ ] cluster-api             
- [ ] cluster-api-provider-azure
- [ ] dns-operator-azure
- [ ] happa


***Apps that still deploy PSPs even when `global.podSecurityStandards.enforced=true`***

- [ ] app-admission-controller-psp          
- [ ] app-exporter-psp                      
- [ ] app-operator-psp                      
- [ ] azure-ad-pod-identity-app-nmi         
- [ ] azure-private-endpoint-operator-psp   
- [ ] chart-operator-psp                    
- [ ] cluster-api-crd-install               
- [ ] cluster-api-monitoring                
- [ ] cluster-api-provider-azure-crd-install
- [ ] cluster-apps-operator-psp             
- [ ] deletion-blocker-operator-psp         
- [ ] dns-operator-azure-psp                
- [ ] encryption-provider-operator-psp      
- [ ] etcd-backup-operator-psp              
- [ ] falco-falco-exporter                  
- [ ] flux-app-pvc-psp                      
- [ ] flux-app-pvc-psp-giantswarm          
- [ ] grafana                               
- [ ] happa-psp                                                                 
- [ ] starboard-exporter-psp                
- [ ] trivy

**Comment by allanger** [comment]
I think flux should be fixed now, at least in waper, if you keep using  this version: `1.2.0-b0ca583571058cef268619aad49204b4d89bdf25`

About happa, I'll take care of it today or tomorrow

**Comment by stone-z** [comment]
I fixed config for the falco and trivy subcharts :heavy_check_mark:

**Comment by erkanerol** [comment]
Here is the update:

- The common toggle was added to @giantswarm/team-honeybadger  apps wrongly. They are broken as I stated [here](https://github.com/giantswarm/roadmap/issues/2970#issuecomment-1895319718). See [the slack thread](https://gigantic.slack.com/archives/C02FL4EAADD/p1705502219073879?thread_ts=1705498061.483359&cid=C02FL4EAADD). See [ the github issue](https://github.com/giantswarm/giantswarm/issues/28340).
- @stone-z The fix you applied didn't work in my cluster. Let's check it together. My understanding is that it is supposed to fix the grafana app too. [See](https://gigantic.slack.com/archives/C01176DKNP4/p1705918153743139?thread_ts=1705917774.516909&cid=C01176DKNP4) 
- @allanger fixed my test MC but the fix was not applied to main branches. We need to apply it. `flux-app` still deploys PSPs in my test cluster. It should be fixed too.


Next steps after fixing all apps:
- [ ] Upgrade test MC to 1.25 and verify basic functionalities
- [ ] Apply the config change in the main branch https://github.com/giantswarm/config/commit/dca241fb2d15911ab469967fbfa8de7f8e48614f
- [ ] Upgrade all MCs to the latest versions + 1.25
- [ ] Upgrade the collection to remove apps of security-bundle https://github.com/giantswarm/capz-app-collection/pull/75
- [ ] Verify mc-bootstrap and fix broken parts (we have separate versions in mc-bootstrap repo. check them )
- [ ] Make 1.25 default for CAPZ https://github.com/giantswarm/cluster-azure/pull/194

**Comment by erkanerol** [comment]
@stone-z informed me that we will use config repo for the exceptional security apps. I applied this change. https://github.com/giantswarm/config/commit/f6577d18df69d8ffc71d4e009ebb508c3a13bc94

This also fixes MC apps of honeybadger https://github.com/giantswarm/config/commit/43c58073b66d4d50580efdb3398225bbb884b9bb by supporting the wrong toggle too. I used it as a workaround. 

I have still problems with
- flux-app
- happa
- cluster_name-app-operator

@giantswarm/team-honeybadger Let's sync tomorrow for the issues on your side.

**Comment by erkanerol** [comment]
Update:

- [ ] flux is not ready to release. Migration path is broken. CC: @uvegla @allanger 
- [ ] `observability-bundle` doesn't have the global flag. [See](https://gigantic.slack.com/archives/C01176DKNP4/p1707292416898489)

Other than these, I tested upgrades to 1.25 and it is fine 🥳  The steps here https://github.com/giantswarm/roadmap/issues/2970#issuecomment-1903757581 should be done.

**Comment by erkanerol** [comment]
@gawertm We are DONE here except mc-bootstrap automation, which is a BigMac topic.
