### ISSUE TITLE
reconfigure container runtimes on existing WCs to use the new registry

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2971]

**Comment by alex-dabija** [comment]
@piontec How can we do this without rolling all the nodes of all clusters?

**Comment by alex-dabija** [comment]
@piontec Ignore my previous question. We talked in KaaS Sync and we'll integrate the change properly in our releases and customers will do proper upgrades.

**Comment by piontec** [comment]
Yes, the final solution will need a `containerd` reconfiguration, most probably including the following changes:
- registry auth
- registry mirror.

For the time being, before we do a new release, we will reconfigure default and optional apps to use the new registry already.

**Comment by piontec** [comment]
Update: we decided to not do it as a separate migration step, but as a part of CAPI migration. New CAPI clusters should already use `gsoci` exclusively.

**Comment by piontec** [comment]
Won't be done for vintage.. For CAPI, it's already done.
