### ISSUE TITLE
CAPA node draining - Phase 1

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2974]
In Vintage we have a node-operator that handles draining of the nodes when being shut down. In Capa this functionality is not available for Machine Pools.

As a Phase 1 implementation, we decided to look into tuning values such as  `shutdownGracePeriod` and `shutdownGracePeriodCriticalPods` which should be configurable per Cluster and available for customers to modify.

This way we can ensure initial nodes shutdown which can be adjusted to customer needs.

**Comment by calvix** [comment]
After attempting to implement this and researching about AWS grace shutdown I don't think it makes sense to implement it as AWS gives no guarantee how long it will wait until an instance is forced to shutdown and the time can vary based on multile AWS internal factors like region, instances availability and more.
