### ISSUE TITLE
CAPA mixed instance types in Node Pool

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2976]
In Vintage we are supporting setting similar instance types for Node Pools, that helps to scale them up when other instances are unavailable. We have to replicate this in CAPA clusters as well.

CAPA provides a [field]( https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/c5a06683bf3ac602062f6fd0e450ae74aa1fd3af/exp/api/v1beta2/awsmachinepool_types.go#L74) `MixedInstancesPolicy` for MachinePools that does exactly that.

This value has to be exposed in the chart such that customers can set their favorable instance types.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2984
- [ ] https://github.com/giantswarm/roadmap/issues/2985
```

**Comment by fiunchinho** [comment]
While testing this, I noticed that there was a configuration that CAPA was allowing, but it was not allowed on AWS, so I pushed changes upstream to fail early https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4656

AWS was complaining with `InvalidQueryParameter: Incompatible launch template: You cannot use a launch template that is set to request Spot Instances (InstanceMarketOptions) when you configure an Auto Scaling group with a mixed instances policy. Add a different launch template to the group and try again`, but only after the `AWSMachinePool` was already updated. With the changes, the user will get immediate feedback that there is something wrong with the configuration.
