### ISSUE TITLE
Get rid of hardcoded static clients in Dex app

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2981]
Dex app currently contains a list of hardcoded static clients, which are required for the SSO to work: 

- `dex-k8s-authenticator`
- `gscliauth`
- `happa`
- `grafana`

And it is also possible to define additional static clients in the `extraStaticClients` array. This option is available to GS staff as well as the custoemrs.

The hardcoded static clients are not needed in all clusters - some of them only make sense in management clusters. And soon there may be clients, which are only needed in some management clusters, not all of them.

Ideally, Dex app should have a single property to define all static clients. At the same time it should be ensured that the required static clients are not accidentally removed or overwritten.

**Comment by vvondruska** [comment]
We investigated several approaches to the unification of static client configs. We wanted to be able to ensure that certain "required" static clients are present, and we also wanted to give the customers enough freedom to define static clients of their own.

Currently we have a map of hardcoded static clients and an array of "extra" static clients available in the app values.

We concluded that if we want check for the presence of "required" static clients during validation, a unified solution with such validation would not differ too much from the current state.

Furthermore, we are currently evaluating ways to replace Dex with something else in the future, so any improvement/adjustment we make in the Dex app may only be short lived.

For these reasons we decided to stick with the current solution for now and re-open/get back to this task later if becomes more urgent.
