### ISSUE TITLE
kubectl gs template cluster: Mandatory choice of `--name` or new `--generated-name` for CAPI cluster names

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#2983]
As discussed in [SIG UX sync 2023-11-21](https://docs.google.com/document/d/1jUdtgiv8Y_mQZH4Pma2ouy7kGowkUwhnv2fi_Bc0eks/edit#bookmark=id.gkh45vz63o4a), we want to ensure that users think of reasonable cluster names when creating workload clusters. That means that an explicit choice should be made if random, 5-letter names should still be used – which we considered a confusing and problematic default. Don't change the command for vintage since there might be production-level automation inside customers or Giant Swarm that breaks unnecessarily. Let's introduce this change for CAPI where no / very few production-grade clusters are relevant right now.

Also, document publically ([here](https://docs.giantswarm.io/getting-started/create-workload-cluster/)) where the cluster name is visible (e.g. DNS records) so that users can make an educated choice.

**Comment by T-Kukawka** [comment]
released, docs in review
