### ISSUE TITLE
Testing of `MixedInstancesPolicy` feature

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2985]
Following exposing of `MixedInstanceTypes` and documentation we have to test the scenarios such as:

- [x] test the behavior of MixedInstanceTypes feature when the instance types are changed
- [x] check how feature behaves when 'wrong' instance is supplied
- [ ] add feature to e2e tests

**Comment by fiunchinho** [comment]
When a non existing instance type is set, the call to update the launch configuration on AWS fails on the AWS API, and nothing happens.

**Comment by T-Kukawka** [comment]
can we alert on this somehow?

**Comment by fiunchinho** [comment]
It's tricky because everything is working fine, the cluster is fine. We would have to add alerting on CRs conditions. We already do [some of that here](https://github.com/giantswarm/cluster-api-monitoring-app) but we don't really have experience using it.

**Comment by T-Kukawka** [comment]
i would say that is not key requirement but we can just do it as improvement later on
