### ISSUE TITLE
Teleport monitoring

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2991]
Started discussion in Team Atlas channel https://gigantic.slack.com/archives/C01176DKNP4/p1700561271469729

**Comment by ssyno** [comment]
[Slack thread](https://gigantic.slack.com/archives/C02GDJJ68Q1/p1701081579476329) regarding the adoption of Teleport EKS cluster to a MC like snail or gorilla.

**Comment by gawertm** [comment]
if we are still of the opinion. that adopting the eks cluster to a GS installation and then instlaling the observability bundle is the right way, then lets just do some very basic monitoring for now until the cluster adoption is more stable and production ready for our use case

**Comment by tuladhar** [comment]
https://github.com/giantswarm/vpn/pull/425

**Comment by gawertm** [comment]
had a call with team atlas. for the temporary solution they suggested a "fak"e cluster on a CAPA MC which is sclaed down and then use the credentials for prometheus remote write

**Comment by ssyno** [comment]
Temporary solution ready to be reviewed and deployed [PR](https://github.com/giantswarm/teleport-fleet/pull/63)

**Comment by ssyno** [comment]
Teleport specific [dashboard](https://grafana.grizzly.gaws.gigantic.io/d/bf4b3346-c537-4c84-9064-63a06f3d868d/teleport?orgId=1&refresh=5s&var-datasource=PBFA97CFB590B2093&var-cluster=teleportprod&var-namespace=teleport&from=1704684024963&to=1704705624963)
Cluster resources [dashboard](https://grafana.grizzly.gaws.gigantic.io/d/efa86fd1d0c121a26444b636a3f509a8/kubernetes-compute-resources-cluster?orgId=1&refresh=1m&var-datasource=default&var-cluster=teleportprod&from=1704702089183&to=1704705689185)
