### ISSUE TITLE
push-to-app-collection should exit early if the released version is lower than the latest version of the app

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2993]
E.g

dex-operator lastest version is 3.5.0 and 2.1.2 is released. Then 2.1.2 shouldn't be pushed to the collection causing downgrade from 3.5.0 to 2.1.2.

see https://gigantic.slack.com/archives/C066J3V6M2B

**Comment by ssyno** [comment]
https://github.com/giantswarm/giantswarm/issues/29037

**Comment by gawertm** [comment]
@weatherhog @Rotfuks we faced this issue some time ago but think that the fix shouldn't be in our team. I am not sure if it would go to honeybader or rather turtles, WDYT?

**Comment by weatherhog** [comment]
For me this looks like a duplicate to https://github.com/giantswarm/giantswarm/issues/29037 and this fix is included there
