### ISSUE TITLE
`opsctl ssh` should print instructions to use `tsh ssh` for CAPI instalaltions

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2995]

**Comment by gawertm** [comment]
to be done only after switching to Teleport fully

**Comment by OnurYilmazGit** [comment]
Implemented deprecation warning for CAPI installations when using `opsctl ssh`. The command now checks if the target machine belongs to a CAPI installation and logs a warning message advising the use of Teleport (tsh ssh) instead. This aligns with our decision to not add any under-the-hood logic and to guide users towards the recommended method. Ready for review.

**Comment by OnurYilmazGit** [comment]
Aligned with the team and updated the repository with other requests. 
Waiting for feedback or approving pr directly.
