### ISSUE TITLE
schema validation for dex operator credentials

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3000]
We recently had an incident where dex-operator was not functional because the `credentials` were provided as a map instead of a string.
It turns out we do not have a schema validation for this value. (`providers` is defined as an array type but there is no validation for the contents of the array)

**Comment by gawertm** [comment]
@anvddriesch we didn't get to this in the standup. can you provide some more details?

**Comment by anvddriesch** [comment]
@gawertm I added some info to the main comment

**Comment by OnurYilmazGit** [comment]
https://github.com/giantswarm/dex-operator/tree/renovate/schema-validation
