### ISSUE TITLE
`opsctl login` should print instruction to use `tsh` or under the hood use `tsh kube login` for CAPI installations

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3001]
Ask in [this thread](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1701087984614399?thread_ts=1701081095.408949&cid=C02HLSDH3DZ)

```
opsctl login golem => under the hood => `tsh login... && tsh kube login golem`
opsctl login golem bigmac => under the hood => `tsh login.. && tsh kube login golem-bigmac`
```

**Comment by gawertm** [comment]
lets not use anything under the hood. we would always need to maintain this. people should get used to tsh instead. also we wanted to get rid of opsctl in a long time.

**Comment by gawertm** [comment]
@tuladhar isn't this also a duplicate of https://github.com/giantswarm/roadmap/issues/2995?

**Comment by tuladhar** [comment]
#2995 is for `opsctl ssh` and this is for `opsctl login` we can combine both into one story.

**Comment by gawertm** [comment]
ah right, I missed that. we can keep 2 tickets thats ok. you can decide if it makes sense to combine and work on both together or seperately. But I still think we shouldnt hide anything teleport behind opsctl

**Comment by OnurYilmazGit** [comment]
Added a deprecation message for CAPI installations within the `opsctl login` command. This change informs users that the `opsctl login` command is deprecated for CAPI installations and suggests using Teleport (tsh login) as the alternative. The message is displayed before any login process begins, ensuring clear communication without additional under-the-hood complexity. Ready for review.

**Comment by OnurYilmazGit** [comment]
https://github.com/giantswarm/opsctl/pull/1864

**Comment by OnurYilmazGit** [comment]
Aligned with the team and updated the repository with other requests. 
Waiting for feedback or approving pr directly. 
https://github.com/giantswarm/opsctl/pull/1864

**Comment by OnurYilmazGit** [comment]
Ready to merge! :)
