### ISSUE TITLE
K8s API Fairness configuration

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3003]
Currently on Vintage we have a dynamic logic for setting the api fairness based on master size/usage. We do not have any feature for this in CAPI in general. Let's see if that is even possible or we can come up with a sane default.

Vintage feature: https://github.com/giantswarm/roadmap/issues/1360

**Comment by weseven** [comment]
I've started looking into this, dumping my mental notes here so tomorrow we can discuss more easily.

## Goal

We need to set the `--max-requests-inflight` and `--max-mutating-requests-inflight` flags in the apiserver manifest, based on the host resources.
`--enable-priority-and-fairness` already defaults to true for kubernetes 1.22+, but we might want to make the flag configurable (probably not).
We might also want to set the resources requests and limits for the API server pods, based on the host resources.

k8s doc: https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

## Vintage

In k8scloudconfig we have:
- an apiserver manifest template (https://github.com/giantswarm/k8scloudconfig/blob/master/files/manifests/k8s-api-server.yaml.tmpl)
- a script that gathers the number of CPUs and the RAM of the machine and computes the proper values for the two flags (https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/setup-apiserver-environment)
- a systemd service that runs at startup and renders the apiserver manifest using the computed values (https://github.com/giantswarm/k8scloudconfig/blob/a00e8039f7ae6a6a9c4d0ab6ca2216545d035537/pkg/template/master_template.go#L116).

introduced with PR in k8scloudconfig: https://github.com/giantswarm/k8scloudconfig/pull/1075

## CAPI

These settings are provider independent, and in my opinion belong to the internal settings we set for our k8s foundation and that are not really meant to be changed (unless something is very wrong).

In the new cluster chart for CAPI we render the yaml manifest for kubeadm using various templates/helpers (apiserver: https://github.com/giantswarm/cluster/blob/main/helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl)
So we would need to add the `max-requests-inflight` and `max-mutating-requests-inflight` flags in the `extraArgs` section, and find a way to have their values computed based on the host resources.

Do we have a way of altering the clusterconfig manifest from the controlplane machine?

I guess the pre-kubeadm commands would be the right place to do that (https://github.com/giantswarm/cluster/blob/main/helm/cluster/templates/clusterapi/controlplane/_helpers_prekubeadmcommands.tpl), but currently I'm not sure how.


I'm also not sure what would be the proper way to set the apiserver pod resources.

One possible way to address both would be using kubeadm patches, e.g.:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches
https://serverfault.com/questions/1089688/setting-resource-limits-on-kube-apiserver

But we need to keep in mind to re-use the same patches if we do a kubeadm upgrade or something similar.

I will check with Nikola tomorrow morning and see what is the proper way to address this.

**Comment by weseven** [comment]
I think we can do it in a similar way to how vintage is doing, we are already doing something similar currently for hostnames in initConfiguration, for example:
 - here in the initConfiguration we reference an environment variable https://github.com/giantswarm/cluster/blob/e9d4bdbbe325aa5379d3aa7a3b31b57a3aae8c6e/helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl#L15 coming from `/run/metadata/coreos` that is filled by the coreos-metadata service which is a dependency of the kubeadm service https://github.com/giantswarm/cluster/blob/e9d4bdbbe325aa5379d3aa7a3b31b57a3aae8c6e/helm/cluster/ci/ci-values.yaml#L227 

So, in a similar way, we can add a OneShot systemd service that executes the same script as vintage (https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/setup-apiserver-environment) writing the env variables to a file, then add that service as another dependecy to the kubeadm service and adding another EnvironmentFile directive below the current one (https://github.com/giantswarm/cluster/blob/e9d4bdbbe325aa5379d3aa7a3b31b57a3aae8c6e/helm/cluster/ci/ci-values.yaml#L234).

That should allow us to reference env variables in the apiserver section of the clusterconfig that the kubeadm service will render when executing on the machine.

**Comment by weseven** [comment]
To summarize, we need to add in the cluster chart, for controlplane nodes:

- a script that has to write the environment file (same as [the vintage one](https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/setup-apiserver-environment)) to be put as executable (755, owner root) in `/opt/bin/setup-apiserver-environment`:
```bash
#!/bin/bash
env_file="/etc/apiserver-environment"

cpus="$(grep -c ^processor /proc/cpuinfo)"
memory="$(awk '/MemTotal/ { printf "%d \n", $2/1024/1024 }' /proc/meminfo)"

declare -i cpus
declare -i memory

# convert to millicores
cpus=$((cpus*1000))

# subtract dedicated millicores (see 'systemReserved' and 'kubeReserved' fields in the kubelet config file)
cpus=$((cpus-600))

# we dedicate 3/4 of all millicores to the api server
dedicated=$((cpus * 3 / 4))

# for every core we have dedicated to api server we allow 200 requests for fairness.
# 1/3 of such number is for mutating requests, 2/3 are for all requests.
echo "MAX_REQUESTS_INFLIGHT=$((dedicated / 1000 * 200 * 2 / 3))" >$env_file
echo "MAX_MUTATING_REQUESTS_INFLIGHT=$((dedicated / 1000 * 200 * 1 / 3 ))" >>$env_file
echo "CPU_LIMIT=${dedicated}m" >>$env_file
echo "MEMORY_LIMIT=$((memory * 3 / 4))Gi" >>$env_file

# We request 1/3 of the available CPUs and 1/2 of the system memory just for api server.
echo "CPU_REQUEST=$((cpus / 3))m" >>$env_file
echo "MEMORY_REQUEST=$((memory / 2))Gi" >>$env_file
```
- a systemd unit file setup-apiserver-environment that executes the script, and on which the kubeadm service is dependent:
```bash
[Unit]
Description="Write environment file for kubeadm apiserver settings"
Before=kubeadm.service
[Service]
Type=oneshot
TimeoutStartSec=0
ExecStart=/opt/bin/setup-apiserver-environment
[Install]
WantedBy=multi-user.target
``` 

- in the cluster apiserver template extraArgs (https://github.com/giantswarm/cluster/blob/0947d1b4393329aea6df0a50cf85827dee39e5e3/helm/cluster/templates/clusterapi/controlplane/_helpers_clusterconfiguration_apiserver.tpl#L16), add:

```yaml
max-requests-inflight: ${MAX_REQUESTS_INFLIGHT}
max-mutating-requests-inflight: ${MAX_MUTATING_REQUESTS_INFLIGHT}
enable-priority-and-fairness: true
```
- in the values (e.g., https://github.com/giantswarm/cluster/blob/e9d4bdbbe325aa5379d3aa7a3b31b57a3aae8c6e/helm/cluster/ci/ci-values.yaml#L234C35-L234C35), make sure the `kubeadm.service` runs after  the setup-apiserver-environment service, and add a new EnvironmentFile directive:
```bash
EnvironmentFile=/etc/apiserver-environment
```

**Comment by nprokopic** [comment]
In case you see the comment before you drop off to vacation:

>    max-requests-inflight: ${MAX_REQUESTS_INFLIGHT}
>    max-mutating-requests-inflight: ${MAX_MUTATING_REQUESTS_INFLIGHT}

Not sure if something like this (setting CLI args to env vars) works in KubeadmControPlane, at least haven't seen it before. We will try and see :)

**Comment by weseven** [comment]
I share the same doubt, but seeing [how an env variable was used in the initConfiguration section](https://github.com/giantswarm/cluster/blob/e9d4bdbbe325aa5379d3aa7a3b31b57a3aae8c6e/helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl#L15) I figured it might work also for the apiserver, since they are both part of the KubeadmControlPlane template... If not, we'll find another way :)

**Comment by weseven** [comment]
Opened PR https://github.com/giantswarm/cluster/pull/47

**Comment by weseven** [comment]
E2E tests are failing, investigating https://github.com/giantswarm/cluster-aws/pull/500

**Comment by weseven** [comment]
Fixed, e2e tests are passing, https://github.com/giantswarm/cluster/pull/47 merged.

**Comment by weseven** [comment]
Reworked fairness settings using kubeadm patches, now they work properly through upgrades.
Tested in cluster-aws and with e2e tests again, merged in cluster with https://github.com/giantswarm/cluster/pull/90
