### ISSUE TITLE
Backport Cilium fixes for ENI mode and default network policies feature

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3005]
Following the issue: https://github.com/giantswarm/roadmap/issues/2860 Cilium 1.15 release estimate is now Q2. It is vital for GS to have CAPA and Vintage on the same Cilium release that also includes the fixes for CAPA Deny-all network policies.

Taking those facts into consideration we need to check if it is possible to backport this change: https://github.com/cilium/cilium/pull/27464/files into our own fork so we do not have to wait for upstream.

This would require building Cilium image by GS and backporting to 1.13

- [ ] try to make 1.14 work with Cilium ENI mode first as the patch would be easier potentially (smaller jump)
- [ ] check how we could build Cilium image with make target and potentially upstream CI/image build
- [x] Optionally check if 1.15-pre2 works (also does not work with ENI mode)

Alternative way forward - Currently we are having Network Policies that only allow access to the API server.  If we would switch to Cilium Network Policies, it would solve the issue 'for time being' while waiting for the fixes in 1.15. (This would have to be done in kube-system namespace and giantswarm namespace - prbly around 20/30 NPs to adjust)

**Comment by T-Kukawka** [comment]
Based on the hustle to backport the needed features to 1.14.5 we have changed the plan.

1. We will use the latest builds from 1.15 (master branch) to test the Cilium with Network Policies and ENI mode fixes
2. In case of issues we will fall back to 1.14.5 which will miss the needed network policies, but has proven to work with ENI mode.

**Comment by T-Kukawka** [comment]
The image should be pushed here: https://github.com/giantswarm/retagger/tree/main/images

**Comment by T-Kukawka** [comment]
We have changed the apporach to match the Vintage setup - further details described here: https://github.com/giantswarm/roadmap/issues/2860#issuecomment-1887150405

**Comment by T-Kukawka** [comment]
so in this scope - we just need 1.14.5 <3

**Comment by bdehri** [comment]
* https://github.com/giantswarm/cilium-app/pull/117
* https://github.com/giantswarm/cilium-upstream/pull/4

I tested the change above with the following cluster-aws branch and default-apps PR:

https://github.com/giantswarm/cluster-aws/tree/update-to-1-14-5

https://github.com/giantswarm/default-apps-aws/pull/381

WC was created without any issues and all pods were healthy.

**Comment by T-Kukawka** [comment]
- https://github.com/giantswarm/default-apps-aws/pull/381
- https://github.com/giantswarm/cluster-aws/pull/475
