### ISSUE TITLE
Document manual provisioning of object storage for on-prem

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#3010]
Create a document in handbook to describe how to provide object storage on on-premise providers for customers

**Comment by QuentinBisson** [comment]
Documented for non stable MCs

**Comment by QuentinBisson** [comment]
We deployed it for one customer only onprem and this is configured to work like it would for MINio as documented https://github.com/giantswarm/loki-app/blob/869e6f207d75e737745320157b6b6d895ee4c3e3/sample_configs/values-eks-testing.yaml#L24, no need for a new documentation in my opinion
