### ISSUE TITLE
Add default AzureFile Storage class to Azure File Csi Driver and deploy app by default

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3013]
1. We have identified a missing default storage class for `AzureFile`[here](https://github.com/giantswarm/azurefile-csi-driver-app/tree/main/helm/azurefile-csi-driver-app/templates) while it is present for for `AzureDisks` [here](https://github.com/giantswarm/azuredisk-csi-driver-app/blob/main/helm/azuredisk-csi-driver-app/templates/azuredisk-controller/storage-class.yaml).

Potentially as this has proven to work for most customers, we could strive to add all default storage classes that we have also present in Vintage: https://github.com/giantswarm/azure-operator/blob/8a49ffc9e4545c423b2de34d592116229b171f36/service/controller/templates/ignition/default_storage_class.go

2. Also noticed that the azure-file app is not deployed by default - we should add it to default apps for CAPZ and push the app to proper catalog if needed.

**Comment by erkanerol** [comment]
@T-Kukawka I think we should add it to https://github.com/giantswarm/cluster-azure/blob/main/helm/cluster-azure/templates/helmreleases/csi.yaml file. Am I wrong?

**Comment by T-Kukawka** [comment]
yes - seems about right 👍  better place than default apps

**Comment by erkanerol** [comment]
PRs are merged. `cluster-azure:v0.0.31` has `azurefile-csi-driver-app`  and the default storage classes. Closing this issue.
