### ISSUE TITLE
CAPA Security Hardening

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3015]
Based on customer security scanning, we will have to implement following features in CAPA:

- [x]  for `{MC_NAME}-vpc` the Network without Traffic Logging has to be followed - roadmap ticket: https://github.com/giantswarm/roadmap/issues/502

- [x] security group belonging to `{MC_NAME}-vpc` - Access List Default Allows Ingress/Egress (AWS)

- [x]  for `S3 Bucket eu-central-1-capa-{MC_NAME}` - Storage Container Not Enforcing Transit Encryption

We have this covered in Vintage implementation on AWS side, more information on the implementation details can be found in internal slack chat: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1701179789159519.

Useful links:
- https://github.com/giantswarm/irsa-operator/blob/master/pkg/aws/services/s3/bucket.go#L85
- https://github.com/giantswarm/irsa-operator/blob/master/pkg/aws/services/s3/bucket.go#L85
- https://github.com/giantswarm/irsa-operator/blob/master/pkg/aws/services/s3/bucket.go#L154-L165

**Comment by fiunchinho** [comment]
@T-Kukawka Regarding the security group, can we know what security group is it? the `default` one? That only allows traffic coming from itself

![image](https://github.com/giantswarm/roadmap/assets/627038/dbd94987-c80b-40a3-b257-4be813d226fa)

**Comment by fiunchinho** [comment]
Created PR upstream to enable transit encryption on the S3 buckets https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4676

**Comment by fiunchinho** [comment]
Working on this PR upstream to secure the VPC default security group https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4707

**Comment by fiunchinho** [comment]
I tested my PR on `golem` to create both CAPA EC2 and CAPA EKS clusters. They both worked fine. The PR has been labeled with `lgtm` but still waiting on approval from maintainer. Once those changes are deployed to our MCs, we could review and merge these two
- https://github.com/giantswarm/cluster-aws/pull/466
- https://github.com/giantswarm/cluster-eks/pull/62
