### ISSUE TITLE
Modify app values to replace docker.io as container registry domain with gsoci.azurecr.io

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3017]
When [CircleCI config is updated to ensure pushing to the new registry](https://github.com/giantswarm/roadmap/issues/2979), the next step is to update the default container image registry hostname configured in many apps' defaults (values.yaml).

In this issue we track the progress on individual repos.

**Comment by stone-z** [comment]
Is geo-replication to China already in place for `gsoci.azurecr.io`?

**Comment by piontec** [comment]
> Is geo-replication to China already in place for `gsoci.azurecr.io`?

No, and it's gonna be some time, if ever, before we can make this. There's a ton of problems before you can make anything work across the Chinese border.

**Comment by marians** [comment]
Only one left. I pinged Rocket about it.

**Comment by marians** [comment]
Done!

**Comment by marians** [comment]
Adding more

**Comment by piontec** [comment]
All the PRs merged, closing.
