### ISSUE TITLE
architect-orb push-to-registries should allow building image using private base image

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3020]
Team @giantswarm/team-tinkerers is trying to use push-to-registries to create a container image based on a private one on Quay [here](https://app.circleci.com/pipelines/github/giantswarm/tinkerers-ci/98/workflows/27c2dbaa-ada7-4c65-986c-9e80685f6b22/jobs/91).

Since the authentication against Quay is only happening just before the `docker push` command, this fails.

**Comment by piontec** [comment]
fixed in `architect-orb v4.37.0`
