### ISSUE TITLE
Setup Mimir on CAPA installation

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#3039]
The goal here is to replace the current monitoring on a testing CAPA installation and have Mimir in place to send alerts and visualize data via Grafana.

This solution should be fully automated, so we can replicate this setup on multiple installations by using a toggle flag which would trigger the deployment and configuration of this monitoring solution. Automation for the new monitoring setup should no be added into the existing prometheus-meta-operator.

Here are some goals to reach :

* Being able to send alerts to OpsGenie from rules evaluated by Mimir
* Being able to link alerts and visualize actual data and dashboards in Grafana
* Being able to silence alerts (ideally using our [silence repository](https://github.com/giantswarm/silences))

```[tasklist]
### Mimir Setup
- [ ] https://github.com/giantswarm/roadmap/issues/3087
- [ ] https://github.com/giantswarm/roadmap/issues/3088
- [ ] https://github.com/giantswarm/roadmap/issues/3089
- [ ] https://github.com/giantswarm/roadmap/issues/3152
- [ ] https://github.com/giantswarm/roadmap/issues/3158
- [ ] https://github.com/giantswarm/roadmap/issues/3162
- [ ] https://github.com/giantswarm/roadmap/issues/3127
- [ ] https://github.com/giantswarm/roadmap/issues/3157
- [ ] https://github.com/giantswarm/roadmap/issues/3163
- [ ] https://github.com/giantswarm/roadmap/issues/3298
- [ ] https://github.com/giantswarm/roadmap/issues/3160
- [ ] https://github.com/giantswarm/roadmap/issues/3159
- [ ] https://github.com/giantswarm/roadmap/issues/3301
- [ ] https://github.com/giantswarm/giantswarm/issues/30281
- [ ] https://github.com/giantswarm/roadmap/issues/3161
- [ ] https://github.com/giantswarm/giantswarm/issues/30090
- [ ] https://github.com/giantswarm/roadmap/issues/3377
- [ ] https://github.com/giantswarm/giantswarm/issues/30218
- [ ] https://github.com/giantswarm/roadmap/issues/3379
- [ ] https://github.com/giantswarm/roadmap/issues/3217
- [ ] https://github.com/giantswarm/giantswarm/issues/30310
- [ ] https://github.com/giantswarm/giantswarm/issues/30836
- [ ] https://github.com/giantswarm/giantswarm/issues/30834
- [ ] https://github.com/giantswarm/giantswarm/issues/30835
- [ ] https://github.com/giantswarm/giantswarm/issues/30837
- [ ] https://github.com/giantswarm/giantswarm/issues/30887
- [ ] https://github.com/giantswarm/giantswarm/issues/30833
- [ ] https://github.com/giantswarm/giantswarm/issues/30758
```

After Mimir is succesfully setup on one installation, we can start getting our internal customers onboarded and check the new system before rolling it out everywhere and cleaning up the old system. 

```[tasklist]
### Migration and Cleanup
- [ ] https://github.com/giantswarm/giantswarm/issues/30365
- [ ] https://github.com/giantswarm/giantswarm/issues/30982
- [ ] https://github.com/giantswarm/roadmap/issues/3510
- [ ] https://github.com/giantswarm/roadmap/issues/3090
- [ ] https://github.com/giantswarm/giantswarm/issues/30839
- [ ] https://github.com/giantswarm/roadmap/issues/3315
- [ ] https://github.com/giantswarm/roadmap/issues/3314
- [ ] https://github.com/giantswarm/giantswarm/issues/31094
- [ ] https://github.com/giantswarm/roadmap/issues/3505
- [ ] https://github.com/giantswarm/roadmap/issues/3218
- [ ] https://github.com/giantswarm/roadmap/issues/3513
```

**Comment by QuentinBisson** [comment]
To think about:
- Adding missing datasource to all dashboards
- Clean up the heartbeats per cluster and clean up prometheus heartbeat alert and remove the heartbeat creation
- Add information about the grafana agent in the heartbeat ops-recipe
- Prometheus to grafana cloud prometheus needs an alert and an ops-recipe update
- Explain in v20 release note that the prometheus agent resource usage will grow bigger

**Comment by QuentinBisson** [comment]
cc @Rotfuks as we still need those items :)

**Comment by Rotfuks** [comment]
Here's the list of stories discussed from our onsite: 

*   giantswarm/giantswarm#30836
*   giantswarm/giantswarm#30833
*   giantswarm/giantswarm#30834
*   giantswarm/giantswarm#30835
*   giantswarm/giantswarm#30837
*   giantswarm/giantswarm#30839

Need to do later:  
Once we have alert review finished: 

*   Remove the mimir specific opsgenie policies that silence alerts coming from mimir out of BH

Once we have mimir rolled out: 

*   Clean up the heartbeats per cluster and clean up prometheus heartbeat alert and remove the heartbeat creation

**Comment by Rotfuks** [comment]
This is done, hurray! Great job @giantswarm/team-atlas !!!! :confetti\_ball:
