### ISSUE TITLE
CAPI Release Framework: Versioning

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3057]
### Motivation
After we defined and aligned on an initial release framework for CAPI with https://github.com/giantswarm/roadmap/issues/2522 we now have to continue our efforts to improve this framework by solving the pain points we feel most. From initial feedback to the release framework and talks with other KaaS Members it is clear, that the current major pain point is how we handle versions and release channels with those versions in the capi release framework. 

```[tasklist]
### Stories
- [ ] https://github.com/giantswarm/roadmap/issues/3313
- [ ] https://github.com/giantswarm/roadmap/issues/2514
- [ ] document a first draft for an addition to the framework: How to do versions in capi
- [ ] present and collect feedback for the first draft, finalise based on the feedback
- [ ] implement changes needed

``` 

### Outcome
- We have a clear alignment what to version and how to version across the organisation for CAPI releases. 
- There is less friction when releasing a new app (version), leading to less painful releases 
- There is clear transparency how our release management works and customers gain more trust in our releases, because they know what to expect.

**Comment by yulianedyalkova** [comment]
First draft of the document can be found [here](https://docs.google.com/document/d/1q2Dhqv1jek3O0aSq0dj0iGj_CdvNe_spz5PGtcjENhg/edit?usp=sharing).
