### ISSUE TITLE
Cluster API for Azure workload cluster upgrades

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#306]
## User Story

_- As a user, I want to upgrade Cluster API for Azure so that I can leverage the flexibility and extra features available in future Cluster API releases and to continuously improve the stability of clusters._

## Details, Background

An upgrade mechanism is required in order to provide new features, security and stability patches to our customers. This mechanism should also allow us to apply bug fixes (patches) as soon as they are available to all clusters.

## Blocked by / depends on

None

**Comment by puja108** [comment]
with the apps we have an upgrade mechanism that is generic across providers
