### ISSUE TITLE
AWSMachinePool should use `CreateAutoScalingGroup:DefaultInstanceWarmup` parameter to avoid replacing nodes too fast

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3060]
https://github.com/giantswarm/cluster-aws/pull/457 already implements this for CAPA-triggered instance refreshes, but that doesn't apply to any other scaling such as done via AWS itself, or by cluster-autoscaler, karpenter, or other tooling. CAPA doesn't offer setting this parameter yet.

**Comment by mnitchev** [comment]
Merged in upstream and released in our fork here https://github.com/giantswarm/cluster-api-provider-aws-app/releases/tag/v2.14.0
