### ISSUE TITLE
Add wildcard DNS record for *.teleport.giantswarm.io needed for application access

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#3072]
**What's the issue**

In other to get web application access working via Teleport, we need to add wildcard entry in teleport.giantswarm.io zone.
```
*.teleport.giantswarm.io -> pointing to -> Teleport proxy load balancer
```

**Comment by tuladhar** [comment]
Also, how will this affect for test.teleport.giantswarm.io.

**Comment by ssyno** [comment]
A wildcard DNS record is used as a catch-all for any subdomain that doesn't have a specific record defined, so it won't interrupt by any means those who are already defined. So [this PR](https://github.com/giantswarm/teleport-fleet/pull/91), should be able to create a wildcard DNS record for every teleport cluster that is being created by the workflow.
