### ISSUE TITLE
Submit CNCF conformance test results for clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3086]
Questions:
- How do we submit test results for clusters?
- Which team is responsible to submit the results?

**Comment by yulianedyalkova** [comment]
We follow the [following](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#uploading) process to submit CNCF tests results upstream. All the [files](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr) mentioned in that process are generated by [CI](https://tekton.ci.giantswarm.io/#/namespaces/tekton-pipelines/pipelineruns/azure-cncf-conformance-tests-7hxdn?pipelineTask=run-conformance-tests&step=generate-pr-contents&view=logs) but the PR still needs to manually get created by a person.
