### ISSUE TITLE
Create default Mimir configuration

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#3088]
Create a default configuration for Mimir app and re-use the actual configuration from gauss in the giantswarm/config repository.

**Comment by QuantumEnigmaa** [comment]
Shouldn't we try to deploy it on a testing CAPI installation beforehand ? It would probably make more sense to have a default config based on a CAPI's one instead of a vintage cluster such as `gauss`

**Comment by QuentinBisson** [comment]
Mimir running on golem:

```
k get pods -n mimir
NAME                                        READY   STATUS    RESTARTS   AGE
mimir-compactor-0                           1/1     Running   0          9h
mimir-distributor-76bdfb8d7c-kk2ft          1/1     Running   0          9h
mimir-gateway-6f889ffcfb-skggv              1/1     Running   0          9h
mimir-ingester-0                            1/1     Running   0          9h
mimir-ingester-1                            1/1     Running   0          9h
mimir-ingester-2                            1/1     Running   0          9h
mimir-overrides-exporter-54b8b45b7d-9hk2t   1/1     Running   0          9h
mimir-querier-59bdd7b4d4-dnkdf              1/1     Running   0          9h
mimir-querier-59bdd7b4d4-wp29q              1/1     Running   0          9h
mimir-query-frontend-5f87695b89-skjnq       1/1     Running   0          9h
mimir-query-scheduler-767786fc94-c7p7t      1/1     Running   0          9h
mimir-query-scheduler-767786fc94-cfsqs      1/1     Running   0          9h
mimir-store-gateway-0                       1/1     Running   0          9h
```

Lets check the status of all components ;)

**Comment by QuantumEnigmaa** [comment]
I had to to create stuff manually to allow mimir pods to be scheduled (namely, a PSP, clusterrole and clusterrolebinding)
I am working on adding those directly to the mimir chart

**Comment by QuentinBisson** [comment]
There is a psp setting

**Comment by QuentinBisson** [comment]
https://github.com/grafana/mimir/blob/099a06e46d121af4552f2fdb14672b50dfc0b8b5/operations/helm/charts/mimir-distributed/values.yaml#L442

**Comment by QuantumEnigmaa** [comment]
Oh nice ! I'm gonna upate the config then :)

**Comment by QuantumEnigmaa** [comment]
After trying with the upstream chart, even though everything is set up so that the PSP is created, it's actually not :/

**Comment by QuantumEnigmaa** [comment]
I created an issue upstream about this : https://github.com/grafana/mimir/issues/7158

**Comment by QuantumEnigmaa** [comment]
Mimir is running on `golem` with the config from the `config` repo. We can consider the current config as a "default" one that will be modified in the future as we progress through the epic
