### ISSUE TITLE
Create object storage for Mimir

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#3089]

**Comment by QuantumEnigmaa** [comment]
Object storage was created by adding a `Bucket` CR in the `extraObjects` field from the `config` repo. However, we will need to have a separate bucket for the `ruler`. To do this, we will have to either wait for an upstream PR adding a custom SA to the ruler to be merged or to create the resource ourselves.

**Comment by QuantumEnigmaa** [comment]
I will create another issue dedicated for the `ruler`. Closing this one as the object storage for mimir can easily be created from the config
