### ISSUE TITLE
Deploy Mimir on (nearly) all CAPA installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#3090]
### Motivation
Mimir is the future core component for our metrics in the observability platform. Now we prepared everything and set it up on a first capa installation we now need to roll it out as a default on all capa installations. 
In general we "only have" 8 CAPA installations and 2 have Mimir already in place. But we're not 100% confidence in the rollout process, so we are going to roll out in 2 phases: first in a stable environment to see what happens and then when all works fine in the rest. 

### Todo

- [x] Roll out Mimir to `gazelle` Installation and closely monitor the rollout process
  - Document what's going on and especially if something fails.  
  - Announce the change on `gazelle` before and after rollout in #news-ops
- [ ] Deploy Mimir onto all CAPA testing installation when the `gazelle` rollout was successfull 
  - Announce the change on all installations befoe and after rollout in #news-ops
  - exclude `goat` (because private network) and ´galaxy` (because china) for now 

### Outcome
- We have Mimir active on all CAPA Installations.

**Comment by QuentinBisson** [comment]
Mimir is deployed to capa app collection

**Comment by QuantumEnigmaa** [comment]
I guess we should wait to have a working mimir on `golem` before enabling it on all other CAPA installations.

**Comment by QuentinBisson** [comment]
Do not forget to remove the golem silence and the opsgenie policy for golem

**Comment by hervenicol** [comment]
Gazelle rollout PR: https://github.com/giantswarm/giantswarm-configs/pull/101
