### ISSUE TITLE
Cluster-autoscaler fails on private WCs

### ISSUE THREAD

**Issue by mnitchev** [giantswarm/roadmap#3098]
## Description

Cluster autoscaler is crashlooping for private WCs, preventing [this test](https://github.com/giantswarm/cluster-test-suites/blob/main/internal/common/scale.go) from running on our e2e test suite. 

### Steps to reproduce
1. Enable the cluster autoscaler test [here](https://github.com/giantswarm/cluster-test-suites/blob/4b24b980f92c551a42f01e22d37469048bc47924/providers/capa/private/capa_test.go#L11)
1. Run the e2e tests for private clusters
1. See them fail

**Comment by whites11** [comment]
problem is the kyverno clusterpolicy that should inject proxy envs is not working on kube-system for some reason
