### ISSUE TITLE
Hello world e2e test fails to reach ingress endpoint

### ISSUE THREAD

**Issue by mnitchev** [giantswarm/roadmap#3099]
## Description

Reaching an app's ingress endpoint doesn't work on private clusters, preventing [this test](https://github.com/giantswarm/cluster-test-suites/blob/main/internal/common/hello.go) from running on our e2e test suite. 

### Steps to reproduce
1. Enable the hello world test [here](https://github.com/giantswarm/cluster-test-suites/blob/4b24b980f92c551a42f01e22d37469048bc47924/providers/capa/private/capa_test.go#L13)
1. Run the e2e tests for private clusters
1. See them fail

**Comment by whites11** [comment]
Adding this annotation to the ingress load balancer services makes it happy, but I'm not sure this is what we want

```
service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```

**Comment by whites11** [comment]
this makes test move forwards, but:

- TLS cert can't be generated (we need DNS challenge)
- there does not seem to be a DNS record created for the hello world app

**Comment by whites11** [comment]
problem is the wildcard record points to the public ingress hostname, but ingress in "internal" mode has a different DNS name:

```
*.t-hht32x0vaj0rp4eea2.gaws.gigantic.io -> ingress.t-hht32x0vaj0rp4eea2.gaws.gigantic.io
```

but it should be:

```
*.t-hht32x0vaj0rp4eea2.gaws.gigantic.io -> ingress-internal.t-hht32x0vaj0rp4eea2.gaws.gigantic.io
```

**Comment by whites11** [comment]
another issue is cert-manager is trying to use http01 challenge and that simply can't work.
We need dns01 challenge.
