### ISSUE TITLE
cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present

### ISSUE THREAD

**Issue by njoaquim** [giantswarm/roadmap#3115]
**Description**
Single replicas in kube-system namespace can change the results of cluster autoscaler, because it cannot release the node where the pods are running.

Message log in autoscaler:
cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present

**Comment by Rotfuks** [comment]
Thank you for reporting. We will take a look and come back to you if we need additional information!

**Comment by Rotfuks** [comment]
Hey there @njoaquim!   
We need more information to check the specific context of this issue. 

What Installation and Cluster did the issue occur? 

Thanks!
