### ISSUE TITLE
Kick-off geo-replication to China

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3116]
We checked with azure support, that it's possible to enable geo-replication of azure CR registry to China, but it requires extra steps compared to enabling geo-replication in other regions:
1. Getting all the paperwork and permits to create a separate ACR account in  Azure China.
2. Getting support to enable geo-replication.

Having our main `gsoci` registry geo-replicated would be really nice and lower operational cost, as we could:
- stop uploading all the images manually to aliyun in all the build tasks we have (they take long, that would be some cost saving)
- simplify our architecture a lot, as Chinese clusters would use the same registry, same config and same domain as all the other clusters
- maybe also simplify accounting, if it will be billed by MS as a single mutli-geo instance

**Comment by puja108** [comment]
Looked quickly into [requirements](https://learn.microsoft.com/en-us/azure/china/overview-checklist) and it's kinda blocking:
- Legal entity in China
- Real name verification (for all users)
- ICP filing & license
- Public security registration

For context: With Alicloud we just used an Account that we created in Germany, no paperwork at all, only minor verification.

And from what I saw the billing is definitely separate, cause it's a Chinese company and they would bill our Chinese entity.

If we would have to do all those things ourselves, that would be close to impossible, just registering a Chinese  would mean huge impacts on cost (think tax complications etc.), but there might be two other options.

Option 1:
From what we heard back in the days also with AWS, there's services that can help you do all the paperwork for some money. We'd need to research such services and how much they'd cost as well as how much complications in the end still remain (e.g. would we still get into tax and legal complications in future years?).

Option 2:
Use adidas accounts there assuming they already have some kind of azure china account. That is a big assumption, if they don't that would be a big item.

With both options there's a risk that it results in accounts that we might not be able to link to ours so OCI syncing might not work. So again another risk.

**Comment by puja108** [comment]
Let's keep it open as I'll also be talking to @othylmann and adidas about China in general. Will close once we have more clarity.

**Comment by puja108** [comment]
I'll close this for now, knowing that at least we've done some research into this and if things come back at some point this year we'll be able to investigate further. Investint much more in investigating options right now feels not goal oriented
