### ISSUE TITLE
Update docs on how to apply CAPA clusters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3120]
### Motivation
After the changes introduced by the release framework implementation there are some slight simplifications on how customers can apply changes to their clusters - for example by just using the cluster-aws chart without the need for any additional resource to be applied. We need to adapt the public docs accordingly. 

### Todo

- [ ] Adapt the public docs to match how to apply changes
- [ ] Adapt the operations cookbooks and any other intranet resource to the change

### Outcome 
- The alignment introduced with the release framework is not just implemented but also all documents around releasing and applying apps are matching to the reality.

**Comment by weseven** [comment]
Updated getting started docs with cluster template cli using releases https://github.com/giantswarm/docs/pull/2268
