### ISSUE TITLE
Update docs on how to apply CAPZ clusters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3123]
### Motivation
After the changes introduced by the release framework implementation there are some slight simplifications on how customers can apply changes to their clusters - for example by just using the cluster-azure chart without the need for any additional resource to be applied. We need to adapt the public docs accordingly. 

### Todo

- [ ] Adapt the public docs to match how to apply changes
- [ ] Adapt the operations cookbooks and any other intranet resource to the change

### Outcome 
- The alignment introduced with the release framework is not just implemented but also all documents around releasing and applying apps are matching to the reality.

**Comment by weseven** [comment]
Already updated with https://github.com/giantswarm/docs/pull/2268, adding the link to the release pages https://docs.giantswarm.io/changes/workload-cluster-releases-for-azure/
