### ISSUE TITLE
fe-docs app fails to deploy

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#3130]
Installation: `gollum`

Workload cluster: `c68pn`

Reasons:

- failed to create resource: admission webhook "validate.kyverno.svc-fail" denied the request:
- policy PolicyException/fe-docs/fe-docs for resource violation:
- restrict-polex-namespaces:
- restrict-namespaces: PolicyExceptions are not allowed to be created in the fe-docs namespace.

**Comment by weatherhog** [comment]
@giantswarm/team-honeybadger @marians already looked into this but is asking for support. Could someone look into `c68pn` on  `gollum` to find out with `fe-docs` fails to deploy?

**Comment by marians** [comment]
We can close this. I updated fe-docs in the context of the move to the new cluster and it's fine now.
