### ISSUE TITLE
Add support for centralized access to all Prometheus servers

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#314]
We currently use promxy to provide unified access to all prometheus servers on one control plane (both the control plane prometheus server, and all the tenant cluster prometheus servers).

We can also use a single central promxy to provide unified access to all promxys running on the control planes. We could then use the hosted grafana to talk to this single central promxy. This would allow us from the central grafana, to query all prometheus servers

```
Grafana Cloud -> Central Promxy -> Control Plane Promxy -> Control Plane / Tenant Cluster Prometheus Servers
```

### TODO
- [ ] Determine current state, refine story

**Comment by Rotfuks** [comment]
This centrallized access will be done with mimir, so we can close this for now.
