### ISSUE TITLE
Update Cilium in CAPVCD

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#3141]
We run a fairly old version of Cilium that causes issues for promtail so we need to update to 0.19.0

Context https://github.com/giantswarm/giantswarm/issues/29385
Slack https://gigantic.slack.com/archives/C01BYMF6RN0/p1704898601837499

**Comment by gawertm** [comment]
activate renovate

**Comment by vxav** [comment]
https://github.com/giantswarm/cluster-cloud-director/pull/243
