### ISSUE TITLE
cluster-aws/cluster-eks: Duplicate subnet map keys should be an error

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3153]
This problem was already observed in https://github.com/giantswarm/roadmap/issues/3048, but it wasn't clear why it happened. It turned out that a duplicate subnet name was used. See also [another chat](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1705648771105519?thread_ts=1705421205.629569&cid=C02HLSDH3DZ).

```
E0119 07:12:45.186110       1 controller.go:324] "Reconciler error" err="failed to reconcile network for AWSManagedControlPlane org-giantswarm/vac2eks: failed to patch conditions: AWSManagedControlPlane.controlplane.cluster.x-k8s.io \"vac2eks\" is invalid: spec.network.subnets[7]: Duplicate value: map[string]interface {}{\"id\":\"\"}" controller="awsmanagedcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="AWSManagedControlPlane" AWSManagedControlPlane="org-giantswarm/vac2eks" namespace="org-giantswarm" name="vac2eks" reconcileID="68cd2eb8-0587-4f93-ad88-c3e24a554bb5"
```

The error is "silent". The cluster status shortly shows `NatGatewaysReconciliationFailed`/`RouteTableReconciliationFailed` but then continues after some minutes and successfully creates a cluster.

@calvix noted in chat that this might relate to the secondary subnet `AWSManagedCOntrolPlane.spec.secondaryCidrBlock` which we assign to pods.

Not sure if this applies to the cluster-aws chart, but since it also has the subnet `id` field naming logic, let's check there as well.

**Comment by calvix** [comment]
issue fixed in our `cluster-eks` chart still might be worth consider if there should be some kind of fix in the upstream controller or if this is cause of new subnetID change and our way how we specify subnet ID in our charts.

**Comment by mnitchev** [comment]
Released in https://github.com/giantswarm/cluster-api-provider-aws-app/releases/tag/v2.16.0
Upstream PR: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4930
