### ISSUE TITLE
Alert on unsupported cilium network policies

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#3154]
Example:

Agent log:

```
cilium-7v655 cilium-agent level=warning msg="Unable to add CiliumNetworkPolicy" ciliumNetworkPolicyName=cilium-extra-policies-dns error="Invalid CiliumNetworkPolicy spec: Combining ToServices and ToPorts is not supported yet" k8sApiVersion=cilium.io/v2 k8sNamespace=giantswarm subsys=k8s-watcher 
```

Policy:

```
$ k get cnp -n kube-system cilium-extra-policies-dns -o yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  creationTimestamp: "2024-01-19T19:01:28Z"
  generation: 1
  name: cilium-extra-policies-dns
  namespace: kube-system
  resourceVersion: "1254"
  uid: 409a8183-bbe2-4b31-bcf5-78f080229be5
spec:
  egress:
  - toPorts:
    - ports:
      - port: "1053"
        protocol: ANY
    toServices:
    - k8sServiceSelector:
        namespace: kube-system
        selector:
          matchLabels:
            k8s-app: coredns
  endpointSelector: {}
```

**Comment by kopiczko** [comment]
Related https://github.com/giantswarm/cilium-app/pull/128

**Comment by weatherhog** [comment]
spend a couple of hours on this if metrics are exposed and are usable to create an alert.

**Comment by kopiczko** [comment]
There is a promising `cilium_policy_import_errors_total`. I need to check what it does exactly, because there is not docs for it.

**Comment by kopiczko** [comment]
I tried to test on the newer version and the metric isn't there. Docs confirm that. Looks like it's gone in v1.15:

https://docs.cilium.io/en/v1.14/observability/metrics/#policy
 
![image](https://github.com/giantswarm/roadmap/assets/4608994/460aeda9-bddb-43a7-9db1-acf38df14f9d)

https://docs.cilium.io/en/v1.15/observability/metrics/#policy

![image](https://github.com/giantswarm/roadmap/assets/4608994/c3aec2d0-206f-498f-90da-7ea48161bdc4)

**Comment by kopiczko** [comment]
https://github.com/cilium/cilium/pull/28423 - `cilium_policy_import_errors_total` is removed in favour of `cilium_policy_change_total`

**Comment by kopiczko** [comment]
Example message in 1.15:

```
cilium-f629s cilium-agent 2024-04-02T20:28:05.147981272+01:00 level=warning msg="Unable to add CiliumNetworkPolicy" ciliumNetworkPolicyName=cilium-extra-policies-dns error="Invalid CiliumNetworkPolicy spec: Combining ToServices and ToPorts is not supported yet" k8sApiVersion= k8sNamespace=kube-system subsys=k8s-watcher
```

**Comment by kopiczko** [comment]
This should do it for 1.15. May be a bit aggressive though:

```
sum(rate(cilium_policy_change_total{outcome=~"fail.*"}[5m])) by (outcome) > 0.0.1
```



For 1.14:

```
rate(cilium_policy_import_errors_total[5m]) > 0.01
```

**Comment by kopiczko** [comment]
ops-recipe: https://github.com/giantswarm/giantswarm/pull/30444
