### ISSUE TITLE
Evaluate resources usage and cost for monitoring

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3161]
Towards https://github.com/giantswarm/roadmap/issues/3039

Let's evaluate the cost of running mimir vs the cost of running 1 Prometheus per cluster:
- current prometheus cost
- mimir cost
- prometheus-agent transfer cost

Goal is to create a cost dashboard similar to the one we built for Loki

Let's first check if this dashboard still works https://github.com/giantswarm/dashboards/pull/305

**Comment by QuentinBisson** [comment]
The mimir cost dashboard is missing the sanples sent to s3 metric and the other one is getting fixed https://github.com/giantswarm/dashboards/pull/441

But I'm a bit scared about the number of network request and current memory usage for just 1 MC. Maybe we can reduce that ?

**Comment by QuantumEnigmaa** [comment]
I looked at the `cost estimate` dashboards for both `mimir` and `prometheus` on `golem` for a 1 week period and this is what I found : 
![image](https://github.com/giantswarm/roadmap/assets/64951262/0708e145-b24b-46cf-812d-e42c754eb32d)

* Storage cost can be overlooked as for now the per month cost for our current S3 bucket on `golem` is around 1 euro (we use Standard Storage Class which costs $0.023 per GB per month for the first 50 TB of data, the price per GB decreasing while the total storage used increase) and the prometheus storage cost is around 0 as its PVC is using a gp3 - IOPS EBS volume which is free under 3000 IOPS. 
* the EC2 instances used for the worker nodes are `r6i.2xlarge` (8 vCPUs and 64GBi memory) meaning that over the last week, mimir alone has used the equivalent of an entire instance. 

![image](https://github.com/giantswarm/roadmap/assets/64951262/f90eed98-9814-4e5f-8c99-0a1584e57fb8)

The graph shows a huge spike uin resources consumption for mimir beginning on the 03/19 for memory and on the 03/20 for CPU with the `mimit-store-gateway` having its CPU consumption rising from 0.25 to 4.5 CPU used. 

We should definitely investigate of that much CPU is really needed for the store-gateway. 

![image](https://github.com/giantswarm/roadmap/assets/64951262/56dbdb26-b86e-425a-a397-818779c60ecd)

In comparison, the resources usage of prometheus is quite steady (see above). 

* Another important point to look at is the network transfer data which is incredibly higher for Mimir compared to prometheuses. This could be expected with Mimir having to send/fetch data from the Object Storage but still, maybe we could take a look there to see if there are some savings to do.

**Comment by QuentinBisson** [comment]
I;m quite bothered by the resource usage, those are really high numbers and especially the memory. I'm wondering it there is no optimization we could use. It would be interesting to attend a community meeting.

Maybe we could try those computations https://grafana.com/docs/mimir/latest/manage/run-production-environment/planning-capacity/?

They did not deploy the Single Scalable deployment model into a helm chart yet :(

**Comment by QuantumEnigmaa** [comment]
I created an issue dedicated to Mimir resources usage optimization [here](https://github.com/giantswarm/giantswarm/issues/30353). 

What do you think remains to be done for this specific issue ? Should I add more details such as a real cost approximation ? (I mean in dollars/euros)

**Comment by QuantumEnigmaa** [comment]
Total series for Mimir over the last 7 days (`sum(cortex_ingester_active_series{cluster_id=~"($cluster)"}) by (cluster_id)`) : 

![image](https://github.com/giantswarm/roadmap/assets/64951262/723273c8-8002-40e1-9938-fe4a5769f974)

Total series for Prometheus over the last 7 days (`sort_desc(sum(prometheus_tsdb_head_series{cluster_id=~"($cluster)"}) by (cluster_id))`) :

![image](https://github.com/giantswarm/roadmap/assets/64951262/5fc991ef-edb8-40b2-97dd-0361dfc8511c)

**Comment by QuentinBisson** [comment]
I think we can close :)
