### ISSUE TITLE
Ensure cluster metrics are received

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3163]
We need to be alerted if mimir is missing metrics from a cluster. This is a replacement for the Workload Cluster heartbeats that we have right now

**Comment by QuentinBisson** [comment]
Idea is to use those 2 for the alert when `monitoring.enabled: true` is set



![Image](https://github.com/giantswarm/roadmap/assets/2787548/fb5ea880-e335-47c1-b9ca-1afad6c38dec)

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas what do you think about this query?

`(label_replace(capi_cluster_info, "cluster_id", "$1", "name", "(.*)") == 1) unless on(cluster_id, customer, installation, pipeline, provider, region) (count(up{job="test"}) by (cluster_id, customer, installation, pipeline, provider, region))` ?

This gets the lits of clusters and compare it toe the running prometheus agent instances?

We could also use `(label_replace(capi_cluster_status_condition{type="Ready", status="True"}, "cluster_id", "$1", "name", "(.*)") == 1) unless on(cluster_id, customer, installation, pipeline, provider, region) (count(up{job="prometheus-agent"}) by (cluster_id, customer, installation, pipeline, provider, region))` which only takes into account ready clusters

**Comment by hervenicol** [comment]
Didn't we already write a recording rule to list all clusters in a consistent way? I remember we talked about it but I didn't find the metrics.

I like the 2nd one, that relies on cluster status (and that has the right `up` selector :sweat_smile: ).
Maybe we should also have alerts for clusters that are "not ready" for too long, but that should be another alert.

**Comment by QuentinBisson** [comment]
Also, the recording rule we have to not report on provisionned clusters :(

**Comment by QuentinBisson** [comment]
So maybe using capi_cluster_status_phase{phase="Provisioned"} makes more sense

**Comment by QuentinBisson** [comment]
This was added in the prometheus rules revamp/upgrade and then finalized in this PR https://github.com/giantswarm/prometheus-rules/pull/1062
