### ISSUE TITLE
Cilium/DNS misconfiguration on CAPVCD causes promtail egress calls outside the cluster to be blocked

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3164]
When trying to deploy our logging stack on CAPVCD (namely Gerbil), we noticed that promtail was not able to send logs to loki.

After inspecting hubble, we noticed that the traffic that should be sent outside the cluster to access the loki ingress (that is actually in the cluster) is actually redirected internally inside the cluster so the default ciliumnetworkpolicy that allows only access to the api-server and world is rendered useless as cilium sees the network flows as being in-cluster:

![Image](https://github.com/giantswarm/roadmap/assets/2787548/287dd337-63c9-417d-bf69-a9b3ff5be5db)

c.f. https://github.com/giantswarm/giantswarm/issues/29385

**Comment by QuentinBisson** [comment]
I tried to deploy loki on CAPV (bamboo) and promtail is working even though it is using the same scheme to call nginx:

![image](https://github.com/giantswarm/roadmap/assets/2787548/7b1321c6-3909-42cb-98d3-e8e0bbad35f0)

I see that the MC has the 2 following ciliumnetworkpolicy that are missing on capvcd MCs (gerbil)

```
> k get ciliumnetworkpolicy allow-cluster-access -oyaml -n kube-system
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  creationTimestamp: "2023-09-27T11:12:24Z"
  generation: 1
  name: allow-cluster-access
  namespace: kube-system
  resourceVersion: "829"
  uid: ba3b9aba-18cf-493c-9b3d-03ee17904222
spec:
  egress:
  - toEntities:
    - kube-apiserver
    - cluster
  endpointSelector: {}
> k get ciliumnetworkpolicy -n kube-system allow-all-ingress-from-host -oyaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  creationTimestamp: "2023-09-27T11:12:24Z"
  generation: 1
  name: allow-all-ingress-from-host
  namespace: kube-system
  resourceVersion: "831"
  uid: 2559d631-7e03-44b2-8b35-b36a987efc5e
spec:
  endpointSelector: {}
  ingress:
  - fromEntities:
    - host
    - remote-node
```

So I'm not sure if they were added to not fix the issue with cilium, if they are on WCs also but there is something wrong here

**Comment by erkanerol** [comment]
These policies are part of cilium-app https://github.com/giantswarm/cilium-app/blob/main/helm/cilium/files/policies/egress.yaml We may have differences between config of cilium apps.

**Comment by erkanerol** [comment]
The cluster app version in `bamboo` is super old. Please ignore that cluster. 

We have these netpols in `gcapeverde` even though the cluster-app is newer there. 

```
➜ k get ciliumnetworkpolicy -A |grep allow-cluster-access
giantswarm    allow-cluster-access                                              63d
kube-system   allow-cluster-access                                              63d
```

It is because we were creating these resources in mc-bootstrap and those are leftovers. See https://github.com/giantswarm/mc-bootstrap/pull/729/files#diff-71caa12c7addf8197e109e323f5af04078e54a80afc210a71c18317f0d587dd3R430

I can say that the status of `gerbil` fits better with the desired state. Let's check the issue in `gerbil` at first and then apply the same configuration to CAPV side too.

**Comment by vxav** [comment]
@QuentinBisson this was fixed when I changed the load balancer of the ingress in `gerbil` right? Or is it still an issue?

**Comment by QuentinBisson** [comment]
It appears so
