### ISSUE TITLE
Multi Provider App Installations

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#3171]
We should look into multi provider installations and check what we need to tackle to make these possible. 

For a start we need to think of all challenges that might occur when having a CAPZ MC and installing Apps on CAPV WC. 

@ljakimczuk already did some initial investigations into this, but we should have another look to come up with a plan to make this possible (not only for the CAPZ / CAPV combination but in general)

**Comment by ljakimczuk** [comment]
App Admission Controller release PR: https://github.com/giantswarm/app-admission-controller/pull/460
App CRD update PR: https://github.com/giantswarm/management-cluster-bases/pull/132

**Comment by mproffitt** [comment]
Closed as completed
