### ISSUE TITLE
SPIKE: Alert for Cluster Upgrade Failuers

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3173]
We have discussed this issue, we seem to have covered the cases for Master and NPs being in the failed state.

What we have to investigate still is to check how we can alert if masters are running different versions of the cluster version for a longer period of time, e.g. 30'. This would mean that one of the masters cannot be removed and there is an issue with continuing the upgrade.

**Comment by bdehri** [comment]
Unfortunately, there is no way to track this. Upgrade does not always mean kubernetes version upgrade, that is why checking node versions does not work. I tried compare cluster-api/CAPA CR labels as well but we use different labels for different CRs which makes it impossible to use labels at the moment.
