### ISSUE TITLE
SPIKE: Capa specific dashboards

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3174]
We want to evaluate what metrics can be useful for tracking the CAPI/CAPA controllers. Based on that evaluation we can then decide what and how we would like to catch the errors or failures on the specific components.

### Acceptance
- [x] first we should assess the metrics that the controllers are exposing to see which ones are actually useful to track.
- [x] check the existance and asses the upstream CAPA dashboards if they can be more of use to us

Points above have proven to be useless, let's try smth different:

- [x] Try out building Loki dashboard that aggregates on the logs for all CAPI & CAPA controllers per MC, preferably filtering on the error messages and cluster id. In the prometheus rules repo we add a reference to that dashboard such that we can easily launch the dashboard with error messages for the given cluster.

**Comment by calvix** [comment]
looking at the `cluster-api-provider-aws` metrics there are several categories of metrics but most of them are very generic not telling us any CAPA information I am not sure what we would use the metrics to tell us anything useful about the cluster, only valuable metrics would be to see if we have some dramatic increase in `aws_api_capp_retries` category  that would mean some recurrent error but the rest is not useful



## aws_api_call_retries_bucket / aws_api_call_retries_sum / aws_api_call_retries_count
metrics about how retries was done for certain AWS API call like DescribeVPC or CreateSubnet
grouped by region and service (like `s3` or `elasticloadbalancing` and so on)


## aws_api_request_duration_seconds_bucket / aws_api_request_duration_seconds_sum / aws_api_request_duration_seconds_count
metrics to measure response time for certain AWS API requests like `CreateLoadBalancer`
grouped by region and service (like `s3` or `elasticloadbalaning` and so on) and controller (like `awscluster` or `awsmachine`)

## aws_api_requests_total
counter for calling certain AWS request like `DescribeSubnets`


## controller_runtime_*
kube builder metrics about the number of workers/processes for a certain thing, reconcile times, webhook latency ad so on

## go_*
general golang metrics like `go_memstats_alloc_bytes` or `go_routines`

## rest_client_requests_*
generic metrics for sent HTTP request

## workqueue_*
workqueue metrics for the controller, like queue time, queue size and so on

**Comment by calvix** [comment]
I was not able to find any public grafana dashboard for CAPI/ CAPA, which would make sense since the metric do not provider much info

I tried googling and also look in this catalog
https://grafana.com/grafana/dashboards

**Comment by calvix** [comment]
done
