### ISSUE TITLE
Do we really need a special worker node selector?

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3181]
The originally described in https://github.com/giantswarm/roadmap/issues/3105. In that issue – we solved a different problem but the question remains.

Do customers use it? Then it's important for the migration. But even if it's still needed, `cluster-*` app config could be used to label nodes instead of requiring a special operator. If CAPA, for example, applies the node labels, they are created much earlier and we don't get the chicken and egg issue above.

Compare to what CAPZ has as well, so we remain consistent.

**Comment by T-Kukawka** [comment]
looking at the providers like CAPZ, CAPA, EKS and Vintage - they all have this configured, hence we will leave it for now as customers are usde to it
