### ISSUE TITLE
Update Linkerd to stable-2.14.9

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#3188]
This version includes an interesting change in the linkerd-cni daemonset. 

> This stable release adds a cni-repair-controller which fixes the issue of
> injected pods that cannot acquire proper network config because linkerd-cni
> and/or the cluster's network CNI haven't fully started (https://github.com/linkerd/linkerd2/pull/11699). It also
> fixes a bug in the destination controller where having a large number of
> Server resources could cause the destination controller to use an excessive
> amount of CPU (https://github.com/linkerd/linkerd2/pull/11907). Finally, it fixes a conflict with tap resource
> shortnames which was causing warnings from kubectl v1.29.0+ (https://github.com/linkerd/linkerd2/pull/11816).

This is quite good, but overlaps with the work done for https://github.com/giantswarm/giantswarm/issues/27073
As a result we should deprecate the nodeTaint container in future versions.

Both methods can live together, so it won't break anything. I'd say we plan as:
- [ ] Upgrade app to 2.14.9
- [ ] Make a release
- [ ] Plan upgrade with customer
- [ ] Disable nodeTaint in clusters (Karpenter first, linkerd2-cni values second)
- [ ] Remove feature from app and make a new release (major one?)

**Comment by weatherhog** [comment]
archiving this because we are not using linkerd anymore

**Comment by weatherhog** [comment]
archiving this because we are not using linkerd anymore

**Comment by weatherhog** [comment]
archiving this because we are not using linkerd anymore
