### ISSUE TITLE
Define structure for app tests

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3190]
Acceptance criteria:
- [ ] Define where tests will be located (ats uses test/ats folder for example).
- [ ] Define tests structure - does each repo have its own suite? Do they share a templated one and just configure it?
- [ ] The framework is responsible for deploying the pipeline provided version of the app to the cluster and deleting it (is it enough to just delete the cluster or do some apps require additional cleanup?)
- [ ] Tests ensure app is running successfully
- [ ] Flow should easily allow pre- and post-app deploy validation and tests
- [ ] Run a smoke test against the deployed app
- [ ] There is sufficient documentation about the whole process so that app teams can start using the framework

**Comment by AverageMarcus** [comment]
Taken from Slack...

There's a lot of inconsistency with how our default-apps are handled across the different proviers.

This is our actual list of default apps that are applied to all clusters:
```
certExporter
certManager
chartOperatorExtensions
etcdKubernetesResourceCountExporter
metricsServer
netExporter
nodeExporter
vpa
observabilityBundle
```

We also have these which are named differently (or just not installed) depending on the provider:

```
not-installed (CAPA & CAPZ) / vpaCRD (CAPV & CAPVCD)
externalDns (CAPA) / external-dns (CAPZ) / not-installed )CAPV & CAPVCD)
securityBundle (CAPA & CAPZ & CAPVCD) / not-installed (CAPV)
teleport-kube-agent CAPA & CAPZ & CAPV) / teleportKubeAgent (CAPVCD)
```

And finally there are 3 apps that are specific to CAPA only:

```
aws-pod-identity-webhook
capi-node-labeler
cluster-autoscaler
```

But that's not all, we also install some things using HelmReleases:

We only have two charts that are common to all clusters:

```
cilium
coredns
```

We then have some inconsistent charts included:

```
network-policies (CAPA & CAPV & CAPVCD) / not-installed (CAPZ)
vertical-pod-autoscaler-crd (CAPA & CAPZ)  / not-installed (CAPV & CAPVCD)
```

And then finally some provider-specific ones (mainly `cloud-provider-XXX`).

---

There's a couple issues with this with regards to testing:
1. We don't really have a nice way of figuring out which way a default app is installed (what name and even if its installed) so upgrading it will be difficult.
2. Anything deployed as a `HelmRelease` within the cluster app can't be modified. There's no exposed configuration to set the version of values.

--- 

Some thinking out loud...

* Could we detect the App / HelmRelease based on labels (the chart name label should be the same across providers, right?)
* If we modify the `App` or `HelmRelease` on the MC, can we be sure that the `default-apps-XXX` or `cluster-XXX` won't overwrite those changes while we're running tests?

**Comment by AverageMarcus** [comment]
> Could we detect the App / HelmRelease based on labels (the chart name label should be the same across providers, right?)

Nope 😞  Looks like the Apps actually end up with `app.kubernetes.io/name: default-apps-aws`. None of the labels actually mention the chart that the app is related to.

I suppose we could instead look at `.spec.name` but that means we then need to iterate over all Apps instead of doing a label filter on get.
