### ISSUE TITLE
Phoenix testing of AWS v20 together with Vintage-CAPA migration

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3206]
The time has come to start testing final releases as well as migration from Vintage `v20` to CAPA. We have created a dedicated Vintage MC `garfish` to perform any vintage or migration testing for stability purposes. The dedicated CAPA cluster for migration will be the CAPA Production MC `grizzly`.

We would kindly ask all teams to perform comprehensive tests for 3 use-cases, ordered in terms of priorities if they can't be performed all at once.

### 1. Vintage [`AWS v20`](https://github.com/giantswarm/releases/pull/1204) 
***Cluster creation on `garfish` - `giantswarm` Organization***

This is the last release of Vintage containing `1.25 k8s`. The `1.25` kubernetes introduces a breaking change in terms of removal `PSPs` from its API, meaning that all workloads will have to comply with the `global` toggle disabling` PSPs` as in `19.3.x` release. Prior to making `v20` release available to customers, we need to validate that all applications are running smoothly. The Vintage tests are standard as always - you just create the `v20` release and validate your applications. Separate stable MC in this case will guarantee no manual changes in the release and stability.

- [x] Phoenix finished with Vintage `v20` testing (please mark it in main issue as well)

### 2. CAPA [`0.60.0`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md#0600---2024-01-29) 
***Cluster creation on `grizzly` - `giantswarm` Organization - be aware that this is production MC, so it will page everyone. In practice any CAPA MC should work for this test.***

Starting with `cluster-aws`-`v0.60.0` and `default-apps-aws`-`v0.45.1` onwards CAPA supports Kubernetes 1.25 with all needed features to run our workloads in the same manner as on VIntage clusters. Please for testing use always latest [`cluster-aws`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md) as well as [`default-apps-aws`](https://github.com/giantswarm/default-apps-aws/blob/master/CHANGELOG.md) releases.

- [x] Phoenix finished with CAPA 1.25 testing (please mark it in main issue as well)

### 3. Vintage to CAPA migration 
***Cluster creation for migration on `garfish` - `capa-migration-testing` Organization. Clusters will be migrated to `grizzly` - `capa-migration-testing` Organization.***

Phoenix and Honeybadger worked extensively on making the migration as smooth as possible. The [`migration-cli`](https://github.com/giantswarm/capi-migration-cli) has been introduced that orchestrates migration of apps as well as infrastructure. Here the main point is to discover if your application and any custom configurations that could be applied by customers are migrated properly.

The `migration-cli` has been extended to facilitate easy testing for all teams ad Giant Swarm. Please follow the requirements as well as the procedure that is described in the [`tests` section](https://github.com/giantswarm/capi-migration-cli/tree/main/tests) of the tool. In case of any issue with infrastructure - ping Phoenix, if the app/configmap migration will face any issues or inconsistencies - ping Honeybadger.

- [x] Phoenix finished with Vintage to CAPA migration testing (please mark it in main issue as well)

**Comment by T-Kukawka** [comment]
@bdehri can u check this while testing the migration? https://github.com/giantswarm/giantswarm/issues/29893

**Comment by bdehri** [comment]
2 of 3 replicas of apiserver had this problem in my case, but the cluster was responding.

**Comment by T-Kukawka** [comment]
Something to check based on Shield feedback: https://github.com/giantswarm/roadmap/issues/3208#issuecomment-1955252189

**Comment by bdehri** [comment]
> Something to check based on Shield feedback: [#3208 (comment)](https://github.com/giantswarm/roadmap/issues/3208#issuecomment-1955252189)

After giving some time, cluster autoscaler goes back to normal. I would say either capa-iam-operator or irsa-operator lags and causes this.



> [@bdehri](https://github.com/bdehri) can u check this while testing the migration? [giantswarm/giantswarm#29893](https://github.com/giantswarm/giantswarm/issues/29893)
> 
> not much knowledge how reproduce but Nick noticed it that API errors tons of this lines after the migration, even tho everything seems to be working
> 
> ```
> E0214 08:32:15.665652       1 authentication.go:73] "Unable to authenticate the request" err="[x509: certificate signed by unknown authority, verifying certificate SN=2049708901584050919, SKID=, AKID=44:0D:D0:88:04:F8:C2:08:82:46:2F:29:8E:DF:EC:68:55:5E:13:F0 failed: x509: certificate specifies an incompatible key usage]"
> ```

About this, I still could not figure out what service causes this. There is no leftover ec2 instance at VPC. Without hubble showing incoming traffic to apiserver, it is pretty hard to pinpoint.
