### ISSUE TITLE
Shield testing of AWS v20 together with Vintage-CAPA migration

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3208]
The time has come to start testing final releases as well as migration from Vintage `v20` to CAPA. We have created a dedicated Vintage MC `garfish` to perform any vintage or migration testing for stability purposes. The dedicated CAPA cluster for migration will be the CAPA stable-testing MC `grizzly`.

We would kindly ask all teams to perform comprehensive tests for 3 use-cases, ordered in terms of priorities if they can't be performed all at once.

### 1. Vintage [`AWS v20`](https://github.com/giantswarm/releases/pull/1204) 
***Cluster creation on `garfish` - `giantswarm` Organization***

This is the last release of Vintage containing `1.25 k8s`. The `1.25` kubernetes introduces a breaking change in terms of removal `PSPs` from its API, meaning that all workloads will have to comply with the `global` toggle disabling` PSPs` as in `19.3.x` release. Prior to making `v20` release available to customers, we need to validate that all applications are running smoothly. The Vintage tests are standard as always - you just create the `v20` release and validate your applications. Separate stable MC in this case will guarantee no manual changes in the release and stability.

- [x] Shield finished with Vintage `v20` testing (please mark it in main issue as well)

### 2. CAPA [`0.60.0`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md#0600---2024-01-29) 
***Cluster creation on `grizzly` - `giantswarm` Organization - be aware that this is production MC, so it will page everyone. In practice any CAPA MC should work for this test.***

Starting with `cluster-aws`-`v0.60.0` and `default-apps-aws`-`v0.45.1` onwards CAPA supports Kubernetes 1.25 with all needed features to run our workloads in the same manner as on VIntage clusters. Please for testing use always latest [`cluster-aws`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md) as well as [`default-apps-aws`](https://github.com/giantswarm/default-apps-aws/blob/master/CHANGELOG.md) releases.

- [x] Shield finished with CAPA 1.25 testing (please mark it in main issue as well)

### 3. Vintage to CAPA migration 
***Cluster creation for migration on `garfish` - `capa-migration-testing` Organization. Clusters will be migrated to `grizzly` - `capa-migration-testing` Organization.***

Phoenix and Honeybadger worked extensively on making the migration as smooth as possible. The [`migration-cli`](https://github.com/giantswarm/capi-migration-cli) has been introduced that orchestrates migration of apps as well as infrastructure. Here the main point is to discover if your application and any custom configurations that could be applied by customers are migrated properly.

The `migration-cli` has been extended to facilitate easy testing for all teams ad Giant Swarm. Please follow the requirements as well as the procedure that is described in the [`tests` section](https://github.com/giantswarm/capi-migration-cli/tree/main/tests) of the tool. In case of any issue with infrastructure - ping Phoenix, if the app/configmap migration will face any issues or inconsistencies - ping Honeybadger.

- [x] Shield finished with Vintage to CAPA migration testing (please mark it in main issue as well)

**Comment by stone-z** [comment]
Attempted to test on `garfish` yesterday and today. Yesterday the WC had not come up after an hour or so, today `garfish` itself seems to be unavailable. I will try again later

**Comment by stone-z** [comment]
Tested CAPA 0.60.1 on `gazelle` with security bundle 1.5.0

**Comment by stone-z** [comment]
Tested on bundle v1.5.0 on a `garfish` v20.0.0 WC.

Policy and Vulnerability reports are generated, falco ecosystem deploys and runs without errors, no errors or incompatibilities were observed.

BUT, changes to the security-bundle App CR (where I added the userConfig configmap to enable other bundle components) kept getting reverted. I haven't seen this elsewhere and I'm not sure if that is expected / new / intentional

**Comment by stone-z** [comment]
I attempted to start the migration test but didn't get very far. `opsctl` errors out creating AWS credentials

**Comment by T-Kukawka** [comment]
I have made adjustments in the tracking ticket as well as the teams tickets regarding the CAPA and migration testing instructions.

TL;DR: Testing of CAPA/Migration is moved from `gazelle` to `grizzly`

Initially `gazelle` has been chosen to test the CAPA migration as it is a Production MC, meaning most stable one. However this has resulted in unforeseen pages towards kaas-cloud oncall that we would like to limit.

We do recognise the pages and also actively work on testing, hence such pages are just a distraction away from the operations clusters that most of the teams have migrated the GS production workloads on.

Taking all the facts into consideration we have decided that it would be best to move the testing to `grizzly` which is stable-testing installation. Installation is primarily running e2e test and is treated as stable (no changes on the MCs).
Thanks for understanding and let us know if something is not working

**Comment by stone-z** [comment]
Migration test from `garfish` to `grizzly` using v20.0.0 with security-bundle v1.6.1 was successful :heavy_check_mark: 

The only noteworthy (or even remotely broken) thing is `cluster-autoscaler` is in CrashloopBackOff after migration, with this error in the logs:
```
I0220 22:44:22.547609       1 auto_scaling_groups.go:367] Regenerating instance to ASG map for ASG names: []
I0220 22:44:22.547623       1 auto_scaling_groups.go:374] Regenerating instance to ASG map for ASG tags: map[k8s.io/cluster-autoscaler/enabled: sigs.k8s.io/cluster-api-provider-aws/cluster/rt4c2:]
E0220 22:44:22.557759       1 aws_manager.go:125] Failed to regenerate ASG cache: WebIdentityErr: failed to retrieve credentials
caused by: ValidationError: Requested ARN is invalid.
	status code: 400, request id: a8f06a75-dcaa-4b62-90a3-e788da73f185
F0220 22:44:22.557779       1 aws_cloud_provider.go:437] Failed to create AWS Manager: WebIdentityErr: failed to retrieve credentials
caused by: ValidationError: Requested ARN is invalid.
	status code: 400, request id: a8f06a75-dcaa-4b62-90a3-e788da73f185
```
This seems unrelated to the security bundle, but just FYI in case it's new @T-Kukawka
