### ISSUE TITLE
Kgs login: Validate ID token with k8s API

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3213]
When a user logs in to a cluster with SSO using `kubectl gs login`, the command ends and prints a message that the login was successful as soon as Dex returns an ID token.

But there is no guarantee that the token will be accepted by Kubernetes API (e.g. due to a misconfiguration).

We could add one more step to the `kubectl gs login` command and verify that the Kubernetes API accepts the ID token before printing the success message.

More context: https://gigantic.slack.com/archives/C02EVLE9W/p1706784429163109

**Comment by OnurYilmazGit** [comment]
https://github.com/giantswarm/kubectl-gs/pull/1281
