### ISSUE TITLE
Explain/support cluster access in Backstage cluster list

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#3215]
Where we show clusters in the Backstage plugin, we should also give info on how to access the cluster.

We support different ways of access:

- Kubernetes API access
- SSH to nodes

**Comment by marians** [comment]
### Kubernetes API

For Kubernetes API access, users need `tsh` installed and must have run this as a prerequisite:

    tsh login --proxy=teleport.giantswarm.io:443 teleport.giantswarm.io

To log in to a cluster and select the context, this commands is needed:

    tsh kube login CLUSTER

where `CLUSTER` is either the management cluster name or a combination of the management and workload cluster name with the `-` separator.

Our UI should provide the appropriate command for each cluster.

### SSH

SSH access is provided per Node. So the first challenge is to decide which node to access. The larger the installation, the larger the cluster, the more options there are to choose from. We should provide a link into the [teleport web UI](https://teleport.giantswarm.io/web/cluster/teleport.giantswarm.io/resources) that filters down the nodes lists as far as possible. 

Second, the user must select a username to log in with. The UI provides three options (`root`, `giantswarm` and the user's GitHub handle), but it seems as if only `root` works well.

![image](https://github.com/giantswarm/roadmap/assets/273727/956d98d4-133a-476e-960d-1e3892db189f)

Third, for SSH access, users have the choice of using the web-based console or their own terminal. The web based console is convenient for quick access, but a user's terminal is likely more powerful. Ideally we provide access to both methods.

Question: does the web UI guide users to local SSH sessions, too?

**Comment by marians** [comment]
We just had a chat with @giantswarm/team-bigmac and @gusevda about this.

- We agree that this is a story worth pursuing
- Regarding SSH access, Bigmac will look into configuraiton options to get rid of the username choice.
- With a query like `labels["mc"] == "gazelle" && labels["cluster"] == ""` it is possible to find management cluster nodes in the Teleport UI. (regarding the empty value, Bigmac is going to look at the tagging scheme, to make it more explicit.)
- It makes sense to offer direct access to control plane nodes. Query example: `labels["mc"] == "gazelle" && labels["cluster"] == "" && labels["role"] == "control-plane"`
- Bigmac will think about getting involved with the implementation of this or any other Backstage based story, and what it would require.

**Comment by marians** [comment]
Will work on the UI spec next

**Comment by marians** [comment]
## Spec draft

![cluster access](https://github.com/giantswarm/roadmap/assets/273727/c9c64290-4afc-4cca-aaae-d88d6cfd7a8f)

[Figma prototype](https://www.figma.com/file/Lej4Ot1LHlvdHMOX2oBvNv/Cluster-Access-v2024-03-26?type=design&node-id=0%3A1&mode=design&t=ZzDS142HlpVJOOnR-1)

Note:

- The **Web console** button in this form assumes that we can launch a. console session immediately, without going through the resources list / search result. I am not sure yet if this is possible. If we can't launch the session directly, the button would be swapped against a link with naming to be defined.
- The `tsh ssh` command tags are actually not correct yet in the mockup.

@giantswarm/team-bigmac Your feedback is welcome.

I think it becomes visible here that a simple and consistent tagging scheme is important. Proposal:

- WC CP node: `ins=gazelle,cluster=operations,role=cp`
- WC worker node: `ins=gazelle,cluster=operations,role=worker`
- MC CP node: `ins=gazelle,cluster=gazelle,role=cp`
- MC worker node: `ins=gazelle,cluster=gazelle,role=worker`

Here `ins` is for `isntallation`.

**Comment by marians** [comment]
I dug into the Teleport web UI a bit. In order to create the URL for the "Web console" button in the above spec, we must know the server ID, which the web UI obtains via API calls like this:

Searching for `labels["cluster"] == "operations" && labels["role"] == "control-plane" && labels["mc"] == "gazelle"` issues this API call:

```
GET https://teleport.giantswarm.io/v1/webapi/sites/teleport.giantswarm.io/resources?searchAsRoles=&limit=48&startKey=&kinds=&query=labels%5B%22cluster%22%5D%20%3D%3D%20%22operations%22%20%26%26%20labels%5B%22role%22%5D%20%3D%3D%20%22control-plane%22&search=&sort=name:asc&pinnedOnly=
```

![image](https://github.com/giantswarm/roadmap/assets/273727/a7f6e87e-984a-4a25-9619-bcf6b1b946d2)


<details>
<summary>Response body</summary>

```json
{
    "items": [
        {
            "kind": "node",
            "tunnel": true,
            "subKind": "teleport",
            "id": "9aae386d-9c4e-45b8-a175-d1ecd5c546f8",
            "siteId": "teleport.giantswarm.io",
            "hostname": "ip-10-0-151-169",
            "addr": "",
            "tags": [
                {
                    "name": "arch",
                    "value": "x86_64"
                },
                {
                    "name": "baseDomain",
                    "value": "awsprod.gigantic.io"
                },
                {
                    "name": "cluster",
                    "value": "operations"
                },
                {
                    "name": "mc",
                    "value": "gazelle"
                },
                {
                    "name": "node",
                    "value": "ip-10-0-151-169"
                },
                {
                    "name": "role",
                    "value": "control-plane"
                }
            ],
            "sshLogins": [
                "marians",
                "root",
                "giantswarm"
            ]
        },
        {
            "kind": "node",
            "tunnel": true,
            "subKind": "teleport",
            "id": "bfe5f5d9-5b87-46ed-bdc2-b3950b54f5bb",
            "siteId": "teleport.giantswarm.io",
            "hostname": "ip-10-0-218-148",
            "addr": "",
            "tags": [
                {
                    "name": "arch",
                    "value": "x86_64"
                },
                {
                    "name": "baseDomain",
                    "value": "awsprod.gigantic.io"
                },
                {
                    "name": "cluster",
                    "value": "operations"
                },
                {
                    "name": "mc",
                    "value": "gazelle"
                },
                {
                    "name": "node",
                    "value": "ip-10-0-218-148"
                },
                {
                    "name": "role",
                    "value": "control-plane"
                }
            ],
            "sshLogins": [
                "giantswarm",
                "marians",
                "root"
            ]
        },
        {
            "kind": "node",
            "tunnel": true,
            "subKind": "teleport",
            "id": "5ed694e9-d4a1-4dda-976d-549f626f473b",
            "siteId": "teleport.giantswarm.io",
            "hostname": "ip-10-0-93-195",
            "addr": "",
            "tags": [
                {
                    "name": "arch",
                    "value": "x86_64"
                },
                {
                    "name": "baseDomain",
                    "value": "awsprod.gigantic.io"
                },
                {
                    "name": "cluster",
                    "value": "operations"
                },
                {
                    "name": "mc",
                    "value": "gazelle"
                },
                {
                    "name": "node",
                    "value": "ip-10-0-93-195"
                },
                {
                    "name": "role",
                    "value": "control-plane"
                }
            ],
            "sshLogins": [
                "marians",
                "root",
                "giantswarm"
            ]
        }
    ],
    "startKey": "",
    "totalCount": 0
}
```

</details>

We have to find out if this API can be used by us from the dev portal.

**Comment by marians** [comment]
## Spec update

- Moved the cluster name/description column to the first position
- Turned the cluster name value into a hyperlink. That's the link which is going to open the access panel for now. In the future it will open cluster details in a different way, where cluster access is a sub-part.

![cluster access](https://github.com/giantswarm/roadmap/assets/273727/1ecf303f-c7e0-4ff2-b6a9-1e807238b27c)

**Comment by marians** [comment]
Recap after a [Slack discussion](https://gigantic.slack.com/archives/C053JHJC99Q/p1711615735843009) with team Bigmac:

- We will introduce the `ins` label to select cluster nodes by installation.
- The `cluster` label will be available on all node resources, with the according Kubernetes cluster name as value.

With that, the tsh command arguments will be like these examples:

```shell
# Management cluster control plane node
$ tsh ssh root@ins=gazelle,cluster=gazelle,role=control-plane

# Workload cluster control plane node
$ tsh ssh root@ins=gazelle,cluster=operations,role=control-plane

# Management cluster worker node
$ tsh ssh root@ins=gazelle,cluster=gazelle,role=worker

# Workload cluster worker node
$ tsh ssh root@ins=gazelle,cluster=operations,role=worker
```

**Comment by tuladhar** [comment]
BigMac has introduce the `ins` label as part of these cluster releases:
- cluster - [v0.18.0](https://github.com/giantswarm/cluster/releases/tag/v0.18.0)
- cluster-aws - [v0.71.0](https://github.com/giantswarm/cluster-aws/pull/590)
- cluster-vsphere - [v0.10.2](https://github.com/giantswarm/cluster-vsphere/pull/174)
- cluster-azure - [v0.6.0](https://github.com/giantswarm/cluster-azure/pull/237)
- cluster-cloud-director - teleport ssh disabled until Flatcar is marked as default OS.

**Comment by gawertm** [comment]
@marians I am not sure what else is expected from BigMac here? Are you still planning to implement some webconsole with direct SSH / Kube api access from Backstage?
I think teleport is only used by Giantswarm staff internally and I am not sure how many of us would prefer the web console.
Adding the commands though, will be very helpful IMO

**Comment by marians** [comment]
The web console is a Teleport UI feature and our plan is to just link to it, as a fast alternative to the terminal access method (which requires `tsh` to be installed).

The question to Team Bigmac was whether you would like to do the implementation of the described feature in our Backstage code. It's not a big thing and you could use the occasion to get in touch with the code base. However, if you say no, Dmitry will do it.

**Comment by gawertm** [comment]
ahh ok thanks! Understood then and makes sense to me :)
But I think it's ok if you/Dmitry does the implementation. If you need any more help on the links or testing or something else, let us know. I think Puru/Dmitry/Antonia have been in touch anyways for this
