### ISSUE TITLE
App Platform Visibility and Governance

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#322]
User value: **As a platform team user, I want to see which apps I am running, which versions and where, so I can easily answer questions from audit and security teams.**

Also applies to end users.

Business value: Give customers a reason to use app platform by showing them all the nice data they can get, even more if they use it to deploy their own apps.

Examples: 
* What apps do you run? 
* Which versions of NGINX are you running? 
* Please list all apps that are running obsolete versions. 
* When there's a security vulnerability, know all the places to patch.

Needs speccing to understand what would be valuable to customers.

**Comment by cokiengchiara** [comment]
Atlas is providing read only access to Grafana. That might be a way.
Discuss if makes sense to do it in Grafana.

**Comment by cokiengchiara** [comment]
@piontec do you have any idea what info would be valuable to customers? Let's start by making a list here, so we can have a starting point to talk to customers and confirm with them.

@foschubert , it would be helpful if you could also add your input here, as the original idea came from you.

**Comment by piontec** [comment]
My rough idea is a table that summarizes what I'm running. Something like:

| App name | Version | Count |
|---------------|------------|----------|
| Nginx IC   | 0.11       | 2         |
| Nginx IC   | 0.12       | 1         |
| Kong         | 0.13      | 9         |
...

It would be cool to aggregate this (sum by version) or extend it (add report where it runs).

**Comment by cokiengchiara** [comment]
@foschubert , since this idea came from you, who are 1-2 customers who'd be interested that I could talk to about this?

**Comment by cokiengchiara** [comment]
From customer in [slack](https://gigantic.slack.com/archives/C6L8J93N0/p1621408063013100?thread_ts=1621351896.012400&cid=C6L8J93N0):

We would be interested in
* the app name
* running version
* the state of the app (deployed, failed, etc.)

I would also be great if we could configure an installation desired state which only shows which environment should run which app version. If this is out of scope, we could easily implement something ourselves I guess.

**Comment by rossf7** [comment]
> Atlas is providing read only access to Grafana. That might be a way.
> Discuss if makes sense to do it in Grafana.

This is now ready <3 and we can add public dashboards here. https://github.com/giantswarm/dashboards

I think a Grafana dashboard makes total sense. My only doubt is whether we should also add this to `kubectl gs`.

```
kubectl gs get apps -o report
```

This would be pretty sweet for the terminal fans and for automation e.g. emailing a report once a week.
We agreed yesterday we will spec in the new release cycle that just started.

cc @QuentinBisson

**Comment by rossf7** [comment]
I think this can also help with the updates story. As we could have a dashboard showing all optional apps that have an upgrade available.

See https://github.com/giantswarm/roadmap/issues/124#issuecomment-890863630

**Comment by othylmann** [comment]
I would really like to push this. I know we do a lot of great work but especially the things like external-dns or cert-manager are surely not updated by anyone. So I would really need a dashboard in grafana that shows me, filterable per customer and cluster, which apps are running and which version exists in our app catalog. then I can tell them to upgrade or do it myself or push it to SAs.

Can we get more priority here?

**Comment by othylmann** [comment]
I already see we have this: https://giantswarm.grafana.net/d/5hNfH3qZz/managed-apps?orgId=1&var-customer=adidas&var-provider=All

**Comment by othylmann** [comment]
We have a Managed App Overview already, but I would like to know: Metric Server runs in which cluster under which version. Then I can move to update.

**Comment by rossf7** [comment]
> Can we get more priority here?

@othylmann I agree we should increase priority. We also want to look at GitOps for Apps but Biscuit are already working on the separate ArgoCD for customers.

The dashboard will be useful for customers, the changes are not that big and there is no dependency on other teams.

**Comment by othylmann** [comment]
thx, just ping me when some dashboard is usable than I kick off here that we upgrade customers.

**Comment by rossf7** [comment]
@othylmann You found it already :) but the upgrades dashboard is ready now. 
https://giantswarm.grafana.net/d/6LDk8YVnk/managed-apps-upgrades

I just needed to fix a couple of bugs this morning.

**Comment by rossf7** [comment]
There is now a public Managed Apps dashboard for customers. See this screenshot from gollum.

<img width="2017" alt="gollum-managed-apps-dashboard" src="https://user-images.githubusercontent.com/311527/133771081-624b5e49-9ba9-4aad-b76c-67a8b9e1de2b.png">

There is also the central [Managed Apps Upgrades](https://giantswarm.grafana.net/d/6LDk8YVnk/managed-apps-upgrades?orgId=1) dashboard showing all apps with an upgrade available.
