### ISSUE TITLE
k8s-dns-node-cache as a default App in CAPI

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#3222]
Currently, we are shipping [this app](https://github.com/giantswarm/k8s-dns-node-cache-app) by default on AWS Vintage.

Should we make it default on our CAPI clusters?

**Comment by kopiczko** [comment]
cluster-aws: https://github.com/giantswarm/default-apps-aws/pull/438

**Comment by kopiczko** [comment]
Done as outlined in the comment above.
