### ISSUE TITLE
Rename the loki-multi-tenant-proxy to grafana-multi-tenant-proxy

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3226]
As this proxy is going to be used not only with Loki, but also with Mimir, Tempo, and all other components that will require multi-tenancy, its name should be changed.

The way it manages multi-tenancy seems to be common and specific to Grafana Labs tools, so we have decided to name it `grafana-multi-tenant-proxy`.

List of actions:
* [x] rename the git repo
* [x] rename in the code and CI
* [x] create repo in quay
* [x] update Loki references in code (vars and functions names)
* [x] update Loki references in app options
* [x] update documentation
* [x] release new `grafana-multi-tenant-proxy` 
* [x] use the new image in the loki helm chart
* [x] (bonus) review multi-tenant-proxy README, CODEOWNERS, and authors.

**Comment by hervenicol** [comment]
Yes, done!
