### ISSUE TITLE
Report about the internal nginx ingress controller in the SLA reporting dashboard

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3230]
Atlas recently added a new dashboard to report about our SLAs in this PR https://github.com/giantswarm/dashboards/pull/433/files.

We have SLAs on nginx and those should be added to this dashboard.

What we would like is for you to create a slo using sloth the expose the `availability` of the `internal nginx ingress controller` that is optionally deployed in the clusters.

Here is an example of an slo alert https://github.com/giantswarm/sloth-rules/blob/5a0ee4a6c65dfdd849d197cd3b873d8fa342dec4/areas/kaas/teams/phoenix/apiserver/slos/availability.yaml

Feel free to ask @giantswarm/team-atlas for help to create the SLO rule and alert and to integrate the data in the dashboard

**Comment by QuentinBisson** [comment]
@weatherhog when do you expect your team to work on this?

**Comment by mcharriere** [comment]
I have the same questions than in https://github.com/giantswarm/roadmap/issues/3229.

On top of that, this `internal nginx ingress controller` is not a thing for us. It's quite specific to 1 customer.

**Comment by QuentinBisson** [comment]
Let's answer them in the other issue then.

Regarding the internal one, maybe we don't need a custom dashboard and it could be in the same one. It does need to be there though

**Comment by kopiczko** [comment]
@QuentinBisson I'm closing this because our solution is generic and it's only a matter of adding another configuration for another `ingressClass` in the `ingress-sla-app`
