### ISSUE TITLE
Report about Kong in the SLA reporting dashboard

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3231]
Atlas recently added a new dashboard to report about our SLAs in this PR https://github.com/giantswarm/dashboards/pull/433/files.

We have SLAs on nginx and those should be added to this dashboard.

What we would like is for you to create a slo using sloth the expose the availability of the kong ingress controller that is optionally deployed in the clusters.

Here is an example of an slo alert https://github.com/giantswarm/sloth-rules/blob/5a0ee4a6c65dfdd849d197cd3b873d8fa342dec4/areas/kaas/teams/phoenix/apiserver/slos/availability.yaml

Feel free to ask @giantswarm/team-atlas for help to create the SLO rule and alert and to integrate the data in the dashboard

**Comment by QuentinBisson** [comment]
@weatherhog when do you expect your team to work on this?

**Comment by mcharriere** [comment]
Work for this issue will be done in https://github.com/giantswarm/roadmap/issues/3229#issuecomment-2044639452

**Comment by kopiczko** [comment]
@QuentinBisson I'm closing this because our solution is generic and it's only a matter of adding another configuration for another `ingressClass` in the `ingress-sla-app`

FTR more details about the solution can be found here https://github.com/giantswarm/roadmap/issues/3229#issuecomment-2066932261

**Comment by QuentinBisson** [comment]
Did you add the ingressClass in the ingress-sla-app?
