### ISSUE TITLE
Happa Support for CAPV

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3233]
We currently cannot use Happa for CAPV and CAPVCD. at least not for the cluster view. For the customers at the moment this is ok, as they switched to a GitOps approach. However, for some users it would still be helpful to see the clusters, versions, etc. also in Happa. Also for Demo purposes this is often helpful.

@weatherhog @marians did you already have plans to add Happa support for CAPV and CAPVCD (priority is clearly on CAPV)? What would be the efforts on adding that support?

**Comment by weatherhog** [comment]
At the moment the future of Happa is unclear, so we can not give an answer to this question. I can give more information about this after having a larger meeting on Wednesday

**Comment by gawertm** [comment]
ok thx, it is not very critical from our side anyways

**Comment by vxav** [comment]
Hey @anvddriesch, do you know how hard it would be to at least get a basic cluster view for CAPV in Happa (we don't care about capvcd for this)

**Comment by anvddriesch** [comment]
I have personally never touched happa but since we already have it for other CAPI providers i suppose that the work would mainly center around supporting the vsphere specific resources like vspherecluster CR. From my :rainbow: times I remember @gusevda whipping up a second provider pretty quickly after the inital CAPI work was done.

**Comment by vxav** [comment]
Awesome thanks! Yeah it will be helpful for CAPV as onprem folks are often UI driven (demos and stuff) but no need to plan CAPVCD as we won't get any more customers there and our current one doesn't need Happa.

**Comment by gawertm** [comment]
done! :)))
