### ISSUE TITLE
Replace `quay.io` with the new registry in the `cluster-vsphere` chart

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3245]
## Task

Replace `quay.io` with the new registry in the `cluster-vsphere` chart.

## Links
- [Epic](https://github.com/giantswarm/roadmap/issues/2882);
- [State after initial investigation on CAPA](https://github.com/giantswarm/roadmap/issues/2882#issuecomment-1884849813).

**Comment by glitchcrab** [comment]
done
