### ISSUE TITLE
Replace `docker.io` with the new registry in the `cluster-vsphere` chart

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3246]
## Task

Replace `docker.io` with the new registry in the `cluster-vsphere` chart.

## Links
- [Epic](https://github.com/giantswarm/roadmap/issues/2882);
- [State after initial investigation on CAPA](https://github.com/giantswarm/roadmap/issues/2882#issuecomment-1884849813).

**Comment by glitchcrab** [comment]
dupe of https://github.com/giantswarm/roadmap/issues/3245
