### ISSUE TITLE
Configure the CAPV default apps to use the new registry

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3247]
## Task

Configure the CAPV default apps to use the new registry.

## Links
- [Epic](https://github.com/giantswarm/roadmap/issues/2882);
- [State after initial investigation on CAPA](https://github.com/giantswarm/roadmap/issues/2882#issuecomment-1884849813).

**Comment by glitchcrab** [comment]
all default apps are using the Azure CR
