### ISSUE TITLE
CAPA China: Flatcar AMI

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3252]
Currently Flatcar AMIs are missing from CAPA China (or can be pushed manually)

For continuing the story of providing CAPA in China as GA, we need to also have a way how to automatically push the AMIs to China Aws account, the images should be private in this case.

Minimal requirements for images:
- Flatcar - `3815.2.0`
- `kubernetesVersion` - 1.25.16
- in case of changes - whatever is used as latest in `cluster-aws`
- AMI should remain private
- AMI needs to be available in both `cn-north-1` and `cn-northewest-1`

**Comment by calvix** [comment]
Vaclav used this guide to copy to China
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ami-store-restore.html

**Comment by T-Kukawka** [comment]
shipping to @giantswarm/team-turtles based on ownership and slack conversation: https://gigantic.slack.com/archives/C0559SH3RJ4/p1708437439405849

**Comment by T-Kukawka** [comment]
potential support from tinkerers will be required here for the CICD

**Comment by yulianedyalkova** [comment]
To be fair, this feels more like a Phoenix + Tinkerers type of task as it requires more provider specific knowledge and setting the pipelines rather than anything flatcar specific.

If we are lucky (🤞), we should be able to duplicate the AWS pipeline and tweak it for China. But we first need the China [credentials](https://github.com/giantswarm/capi-image-builder?tab=readme-ov-file#capa--aws) set up. @giantswarm/team-tinkerers any other prerequisites you can think of?

**Comment by yulianedyalkova** [comment]
Actually it seems that we might be able to just upload the images to China instead of running the whole pipeline there (as it would be dead slow). We (Tinkerers) will look into what credentials we would require and will come back to you to see how we can proceed.

**Comment by AverageMarcus** [comment]
The pre-requisites needed to be provided by both teams can be found in: https://github.com/giantswarm/giantswarm/issues/30249

**Comment by ericgraf** [comment]
@T-Kukawka The tekton portion has been implemented. All newely built capa images will automatically be created in China's two regions. The created image is private as mentioned above.  

This is issue is completed from a team tinkerers perspective. If there is anything else to do please let us know. 
Thanks!

**Comment by calvix** [comment]
@ericgraf if the images are pushed to China than we are good to close this, If we found something we will ping you later
