### ISSUE TITLE
Capa China: capa-controller-app work

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3254]
### Context
Changes required on `capa-controller-app` for CAPA in China:

- [x] adjust pkg/cloud/identity/identity.go - line 158 - awsConfig := aws.NewConfig().WithRegion("cn-north-1") (work needed upstream - CAPA calls it "partition" (normal, chiina, govcloud...))
- [x] install crd job do not have option to specify registry
- [x] fix incosistency between registry values in capi/capa apps (might be different value for the registry name)

### Acceptance
- [x] Supply PR upstream for `capa-controller-app` for `adjust pkg/cloud/identity/identity.go`
- [x] Make sure that the other two points work

**Comment by calvix** [comment]
PR has been merged!
