### ISSUE TITLE
CAPA China: Cluster API images

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3255]
Currently Cluster API images for bootstrap control and control-plane controller are not pushed to China registry at all. We have to enable this in order to proceed with automatic clusters privisioning.

**Comment by T-Kukawka** [comment]
This might have been done already, @calvix to confirm

**Comment by calvix** [comment]
it is done - https://app.circleci.com/pipelines/github/giantswarm/cluster-api/169/workflows/67ab3ff1-1af8-440e-a9dc-f30fc15c788b/jobs/166
