### ISSUE TITLE
Allow for dropping GP2 storage class completely

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#3262]
Most customers have now migrated to GP3 EBS volumes on AWS. As of now, though, they can still create GP2 volumes. Some customers would like to get rid of the GP2 StorageClass (`gp2` created via the deprecated `kubernetes.io/aws-ebs` provisioner). How can we do this?

**Comment by T-Kukawka** [comment]
The GP2 is not even a default storage class, what is the actual issue for having it in the cluster? The storage class is deployed via k8s cloud config, meaning we need a new release for aws-operator as well as the GS WC release.

**Comment by LolloneS** [comment]
It's just a matter of forbidding people from using it. It can also be done via a Kyverno policy, yes. Will this go away with CAPA though? That would be ideal

**Comment by AndiDog** [comment]
`aws-ebs-csi-driver-app` provides the default storage class for CAPA clusters, and GP3 is the only + default `StorageClass`. So yes, it "goes away" with CAPA.

This removal however can be problematic for migration of user-defined PVCs if they use an older storage class which isn't defined anymore. @calvix @T-Kukawka do you think we need to consider this change for the migration tool? Or will the existing `StorageClass` objects just remain in etcd and not create a problem for migrated WCS?

**Comment by LolloneS** [comment]
IMHO we should aim at not having `gp2` volumes anymore when moving to CAPA. The StorageClass we used for `gp2` has been deprecated for quite some time and we should lower the amount of deprecated stuff we carry on our back now that we have the chance to make things right.

**Comment by T-Kukawka** [comment]
@alex-dabija can we just include it in the CAPA changes announcement?

**Comment by T-Kukawka** [comment]
added, closing
