### ISSUE TITLE
PSS app upgrades

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3265]
## Epic

Upgrade all applications running on all AWS clusters to a version which supports PSS before the cluster is upgraded to `AWS v19.3.x`.

## Why?

All apps running on a cluster need to be upgraded to a version which supports PSS before upgrading to cluster to `AWS v19.3.x` (see the [release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/)).

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/3273
- [ ] https://github.com/giantswarm/roadmap/issues/3274
- [ ] https://github.com/giantswarm/roadmap/issues/3275
- [ ] https://github.com/giantswarm/roadmap/issues/3276
- [ ] https://github.com/giantswarm/roadmap/issues/3277
- [ ] https://github.com/giantswarm/roadmap/issues/3278
- [ ] https://github.com/giantswarm/roadmap/issues/3279
- [ ] https://github.com/giantswarm/roadmap/issues/3280
- [ ] https://github.com/giantswarm/roadmap/issues/3281
- [ ] https://github.com/giantswarm/roadmap/issues/3282
- [ ] https://github.com/giantswarm/giantswarm/issues/31160
```

## Links

- [App version overview per team](https://github.com/giantswarm/giantswarm/issues/30482);
- [AWS v19.3.0 release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/);
- [Scheduled cluster upgrades](https://giantswarm.grafana.net/d/5dcKSlI7k/cluster-upgrade-schedule?orgId=1);
- [App status](https://giantswarm.grafana.net/d/Iuahg6J7z/app-status?orgId=1);
- [Managed apps upgrades](https://giantswarm.grafana.net/d/6LDk8YVnk/managed-apps-upgrades?orgId=1);
- [Long-term process app upgrades issue](https://github.com/giantswarm/giantswarm/issues/29661);

**Comment by teemow** [comment]
https://github.com/giantswarm/giantswarm/issues/30482

**Comment by teemow** [comment]
ping @alex-dabija

**Comment by teemow** [comment]
@T-Kukawka @weatherhog do you know what is left to do for your teams here?

**Comment by T-Kukawka** [comment]
we can close this from Phoenix perspective @teemow
