### ISSUE TITLE
Regularly reconcile validation CNAME record for ACM certificate of `irsa.<basedomain>`

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3266]
See [chat](https://gigantic.slack.com/archives/C062HB29BDG/p1708582938648199) about expiring certificate. The irsa-operator code may not be correct.

Seems the irsa-operator takes action only if the certificate is not existing yet, same one-time action is take if the certificate is not validated yet.

**Comment by T-Kukawka** [comment]
related ticket: https://github.com/giantswarm/giantswarm/issues/29986

**Comment by mnitchev** [comment]
There were two problems with this:
1. We didn't perform the validation on renewal, only if the certificate hasn't been issued at all yet.
1. We weren't checking properly for validation. Once the initial certificate is validated, the validation status will always be successful on the resource. For renewal there is a separate renewal status which shows `PENDING_VALIDATION`.

Once https://github.com/giantswarm/irsa-operator/pull/232 is merge and release this issue should be closed

**Comment by mnitchev** [comment]
Fixed in https://github.com/giantswarm/irsa-operator/releases/tag/v0.26.1
