### ISSUE TITLE
App installation dialog resets app CR name and target namespace value when selecting a file to upload

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3267]
Recording:

https://github.com/giantswarm/roadmap/assets/273727/ed8363b7-5583-4262-ac84-a71370638d20

To reproduce:

1. Open the "Install app" dialog
2. Modify the value in the "App resource name" and/or "Namespace" field
3. Click "Choose file" on user values or secret values and select a file

As a result, the input in the "App resource name" and/or "Namespace" field(s) will be reset to the default.

This is unexpected and can result in the app being installed in the wrong namespace or using the wrong resource name.

**Comment by marians** [comment]
This is a type of bug that I'd actually like to see us fix. FYI @gusevda

**Comment by weatherhog** [comment]
@marians @gusevda does this still need to be fixed? Or can this be closed? This has been there for 2.5 years
