### ISSUE TITLE
sync and have a place for CAPI milestones and dependencies between teams

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#327]
sig product Mon, 03. May 2021

We want to have an overview of the technical things that need to be done in order to achieve the milestones. Separate from product overview. 

We want to use roadmap board and assign label for all CAPI related issue so it's easy to filter. e.g. `topic/capi`

Milestones - KaaS needs to decide how to group issues.

Need to agree:
* What we need to put, e.g. monitoring

Idea: List description in milestones, so we can get an overview per milestone. 

Alex will make a proposal for what he thinks should go in there.

**Comment by teemow** [comment]
@alex-dabija do you think we need this issue still? There are a lot of stories on the roadmap with the `topic/capi` label. But some of them aren't labeled with a team. So I am not sure if somebody takes care of them.

See: https://github.com/giantswarm/roadmap/projects/1?card_filter_query=label%3Atopic%2Fcapi

**Comment by alex-dabija** [comment]
The issue is no longer needed. I'm going over the CAPI issues on the roadmap without a team and I'll be assigning them to Phoenix and/or Rocket.
