### ISSUE TITLE
PSS app upgrades - BigMac

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3275]
Towards [epic](https://github.com/giantswarm/roadmap/issues/3265).

## Task

Upgrade all applications running on all AWS clusters to a version which supports PSS before the cluster is upgraded to `AWS v19.3.x`.

## Why?

All apps running on a cluster need to be upgraded to a version which supports PSS before upgrading to cluster to `AWS v19.3.x` (see the [release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/)).

## Links

- [AWS v19.3.0 release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/);
- [Scheduled cluster upgrades](https://giantswarm.grafana.net/d/5dcKSlI7k/cluster-upgrade-schedule?orgId=1);
- [App status](https://giantswarm.grafana.net/d/Iuahg6J7z/app-status?orgId=1);
- [Managed apps upgrades](https://giantswarm.grafana.net/d/6LDk8YVnk/managed-apps-upgrades?orgId=1);
- [Long-term process app upgrades issue](https://github.com/giantswarm/giantswarm/issues/29661);

**Comment by ssyno** [comment]
# BigMac Apps:
- cert-manager
- cert-manager-app
- athena
- credentiald
- dex-app
- dex-operator
- organization-operator
- rbac-operator
- teleport-operator
- teleport-kube-agent
# On latest AWS 19.3.2:
- cert-manager: 2.5.2

**Comment by ssyno** [comment]
| app              | catalog               | cluster_id | customer    | deployed_version | installation | name             | namespace      | version |
|------------------|-----------------------|------------|-------------|------------------|--------------|------------------|----------------|---------|
| api              | control-plane-catalog | kudu       | klingel     | 1.37.3           | kudu         | api              | giantswarm     | 1.37.3  |
| api              | control-plane-catalog | valkyrie   | cyta        | 1.37.3           | valkyrie     | api              | giantswarm     | 1.37.3  |
| athena           | giantswarm            | potato     | babymarkt   | 1.11.0           | potato       | athena           | prod           | 1.11.0  |
| athena           | giantswarm            | potato     | babymarkt   | 1.11.0           | potato       | athena           | stage          | 1.11.0  |
| cert-manager-app | default               | akita      | adidas      | 2.25.0           | akita        | cert-manager     | ccn02          | 2.25.0  |
| cert-manager-app | default               | akita      | adidas      | 2.25.0           | akita        | cert-manager     | pcn03          | 2.25.0  |
| cert-manager-app | default               | alpaca     | adidas      | 2.25.0           | alpaca       | cert-manager     | cna01          | 2.25.0  |
| cert-manager-app | default               | alpaca     | adidas      | 2.25.0           | alpaca       | cert-manager     | hype2          | 2.25.0  |
| cert-manager-app | default               | alpaca     | adidas      | 2.25.0           | alpaca       | cert-manager     | pna01          | 2.25.0  |
| cert-manager-app | default               | anaconda   | adidas      | 2.25.0           | anaconda     | cert-manager     | pna02          | 2.25.0  |
| cert-manager-app | default               | anchovy    | adidas      | 2.25.0           | anchovy      | cert-manager     | int01          | 2.25.0  |
| cert-manager-app | default               | anchovy    | adidas      | 2.25.0           | anchovy      | cert-manager     | pdm01          | 2.25.0  |
| cert-manager-app | default               | anchovy    | adidas      | 2.25.0           | anchovy      | cert-manager     | peu02          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | apie2          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | bdt01          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | ceu01          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | ceu02          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | hype1          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | mh1m5          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | nb0rx          | 2.25.0  |
| cert-manager-app | default               | anteater   | adidas      | 2.25.0           | anteater     | cert-manager     | peu01          | 2.25.0  |
| cert-manager-app | default               | antelope   | adidas      | 2.25.0           | antelope     | cert-manager     | pap01          | 2.25.0  |
| cert-manager-app | default               | argali     | adidas      | 2.25.0           | argali       | cert-manager     | ccn01          | 2.25.0  |
| cert-manager-app | default               | argali     | adidas      | 2.25.0           | argali       | cert-manager     | pcn01          | 2.25.0  |
| cert-manager-app | default               | argali     | adidas      | 2.25.0           | argali       | cert-manager     | pcn02          | 2.25.0  |
| cert-manager-app | default               | eagle      | egger       | 2.25.0           | eagle        | cert-manager     | me4j3          | 2.25.0  |
| cert-manager-app | default               | eagle      | egger       | 2.25.0           | eagle        | cert-manager     | p7jp8          | 2.25.0  |
| cert-manager-app | default               | eagle      | egger       | 2.25.0           | eagle        | cert-manager     | rc40i          | 2.25.0  |
| cert-manager-app | default               | eagle      | egger       | 2.25.0           | eagle        | cert-manager     | ve5v6          | 2.25.0  |
| cert-manager-app | default               | eagle      | egger       | 2.25.0           | eagle        | cert-manager     | w5o2x          | 2.25.0  |
| cert-manager-app | default               | eagle      | egger       | 2.25.0           | eagle        | cert-manager     | wn5r7          | 2.25.0  |
| cert-manager-app | default               | eagle      | egger       | 2.25.0           | eagle        | cert-manager     | x2v6h          | 2.25.0  |
| cert-manager-app | default               | fox        | flexshopper | 2.25.0           | fox          | cert-manager     | d2gu9          | 2.25.0  |
| cert-manager-app | default               | fox        | flexshopper | 2.25.0           | fox          | cert-manager     | di34r          | 2.25.0  |
| cert-manager-app | default               | fox        | flexshopper | 2.25.0           | fox          | cert-manager     | h0ps1          | 2.25.0  |
| cert-manager-app | default               | fox        | flexshopper | 2.25.0           | fox          | cert-manager     | s2nd0          | 2.25.0  |
| cert-manager-app | default               | fox        | flexshopper | 2.25.0           | fox          | cert-manager     | sv43d          | 2.25.0  |
| cert-manager-app | default               | kudu       | klingel     | 2.25.0           | kudu         | cert-manager     | d4c6x          | 2.25.0  |
| cert-manager-app | default               | kudu       | klingel     | 2.25.0           | kudu         | cert-manager     | eosf6          | 2.25.0  |
| cert-manager-app | default               | kudu       | klingel     | 2.25.0           | kudu         | cert-manager     | tz3df          | 2.25.0  |
| cert-manager-app | default               | potato     | babymarkt   | 2.25.0           | potato       | cert-manager     | prod           | 2.25.0  |
| cert-manager-app | default               | potato     | babymarkt   | 2.25.0           | potato       | cert-manager     | stage          | 2.25.0  |
| cert-manager-app | default               | valkyrie   | cyta        | 2.25.0           | valkyrie     | cert-manager     | nvw9c          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | 0a452          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | 0d77f          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | 0ohqb          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | 5e1e5          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | ab590          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | aocw4          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | b7367          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | c0y9n          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | d0etw          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | e6fr2          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | f5773          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | hnq40          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | naap2          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.25.0           | viking       | cert-manager     | wcp4x          | 2.25.0  |
| cert-manager-app | default               | viper      | vodafone    | 2.25.0           | viper        | cert-manager     | ek8n4          | 2.25.0  |
| cert-manager-app | default               | viper      | vodafone    | 2.25.0           | viper        | cert-manager     | t9vq0          | 2.25.0  |
| cert-manager-app | default               | viking     | vodafone    | 2.11.0           | viking       | cert-manager     | ocs13          | 2.11.0  |
| cert-manager-app | default               | visitor    | vodafone    | 2.11.0           | visitor      | cert-manager     | ocs14          | 2.11.0  |
| cert-manager-app | default               | cuckoo     | giantswarm  | 2.21.0           | cuckoo       | wc1-cert-manager | org-conti-test | 2.21.0  |
| cert-manager-app | default               | valkyrie   | cyta        | 2.20.3           | valkyrie     | cert-manager     | zfz4p          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 21f0d          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 2t4ky          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 3p5ny          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 3pwt7          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 48but          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 5y4cr          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 7fkvu          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 7pf9a          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 9af5f          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | 9vcqy          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | a8yo6          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | aofk0          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | b3b10          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | ceb0a          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | dc746          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | e4ab9          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | ktc6d          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | naap0          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | rsz7u          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | s53h4          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | vi8fs          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | w364n          | 2.20.3  |
| cert-manager-app | default               | viking     | vodafone    | 2.20.3           | viking       | cert-manager     | yz2cx          | 2.20.3  |
| cert-manager-app | default               | viper      | vodafone    | 2.20.3           | viper        | cert-manager     | dc266          | 2.20.3  |
| cert-manager-app | giantswarm            | kudu       | klingel     | 2.21.0           | kudu         | cert-manager     | clive          | 2.21.0  |
| companyd         | control-plane-catalog | kudu       | klingel     | 1.2.1            | kudu         | companyd         | giantswarm     | 1.2.1   |
| companyd         | control-plane-catalog | valkyrie   | cyta        | 1.2.1            | valkyrie     | companyd         | giantswarm     | 1.2.1   |
| tokend           | control-plane-catalog | kudu       | klingel     | 1.2.2            | kudu         | tokend           | giantswarm     | 1.2.2   |
| tokend           | control-plane-catalog | valkyrie   | cyta        | 1.2.2            | valkyrie     | tokend           | giantswarm     | 1.2.2   |
| userd            | control-plane-catalog | kudu       | klingel     | 1.2.1            | kudu         | userd            | giantswarm     | 1.2.1   |
| userd            | control-plane-catalog | valkyrie   | cyta        | 1.2.1            | valkyrie     | userd            | giantswarm     | 1.2.1   |

**Comment by tuladhar** [comment]
- [x] adidas
- [x] egger
- [x] cyta
- [x] flexshopper
- [ ] klingel
  - `cert-manager-app`
    - `kudu / clive` - 2.21.0 - 2.25.2
- [ ] babymarkt (leaving soon, [will be on 19.0.1 until June](https://gigantic.slack.com/archives/C03UB7LQWH0/p1707123285543899))
  - `dex-app`
    - `potato / prod` - 1.33.0 - 1.40.0
    - `potato / stage` - 1.39.0 - 1.40.0
- [x] vodafone
