### ISSUE TITLE
PSS app upgrades - Turtles

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3276]
Towards [epic](https://github.com/giantswarm/roadmap/issues/3265).

## Task

Upgrade all applications running on all AWS clusters to a version which supports PSS before the cluster is upgraded to `AWS v19.3.x`.

## Why?

All apps running on a cluster need to be upgraded to a version which supports PSS before upgrading to cluster to `AWS v19.3.x` (see the [release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/)).

## Links

- [AWS v19.3.0 release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/);
- [Scheduled cluster upgrades](https://giantswarm.grafana.net/d/5dcKSlI7k/cluster-upgrade-schedule?orgId=1);
- [App status](https://giantswarm.grafana.net/d/Iuahg6J7z/app-status?orgId=1);
- [Managed apps upgrades](https://giantswarm.grafana.net/d/6LDk8YVnk/managed-apps-upgrades?orgId=1);
- [Long-term process app upgrades issue](https://github.com/giantswarm/giantswarm/issues/29661);

**Comment by Rotfuks** [comment]
Check versions on dashboard here: https://giantswarm.grafana.net/d/IkIuTgkMz/aws-releases-and-workload-clusters?orgId=1

**Comment by Rotfuks** [comment]
Goal here is to get a list of installations that are still using outdate versions not covering the PSS updates

**Comment by Gacko** [comment]
From my understanding of @alex-dabija's request it's rather about apps we run on workload clusters, so mainly Giant Swarm operated workload clusters.

@alex-dabija: Is that right?

**Comment by Gacko** [comment]
Sorry, got that wrong. After re-reading it: All apps we provide as part of AWS releases < v19.3.x should be PSS compliant. If they are not, we would need to patch them, release them and request a AWS v19.2.x release to fix them before going for v19.3.x? That also doesn't make sense to me.

**Comment by Gacko** [comment]
Looking at how other teams solved that, I don't think there's anything to do for us. Our apps should be PSS compliant already, the last step we're currently taking is updating them to those PSS compliant versions in the MCs: https://github.com/giantswarm/giantswarm/issues/30063

Therefore I'm gonna close that issue.
