### ISSUE TITLE
PSS app upgrades - Shield

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3279]
Towards [epic](https://github.com/giantswarm/roadmap/issues/3265).

## Task

Upgrade all applications running on all AWS clusters to a version which supports PSS before the cluster is upgraded to `AWS v19.3.x`.

## Why?

All apps running on a cluster need to be upgraded to a version which supports PSS before upgrading to cluster to `AWS v19.3.x` (see the [release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/)).

## Links

- [AWS v19.3.0 release notes](https://docs.giantswarm.io/changes/workload-cluster-releases-aws/releases/aws-v19.3.0/);
- [Scheduled cluster upgrades](https://giantswarm.grafana.net/d/5dcKSlI7k/cluster-upgrade-schedule?orgId=1);
- [App status](https://giantswarm.grafana.net/d/Iuahg6J7z/app-status?orgId=1);
- [Managed apps upgrades](https://giantswarm.grafana.net/d/6LDk8YVnk/managed-apps-upgrades?orgId=1);
- [Long-term process app upgrades issue](https://github.com/giantswarm/giantswarm/issues/29661);

**Comment by fhielpos** [comment]
For vintage:
I don't think we need to do anything besides track which customers are already running our apps alone.

The versioning should be handled by the security-bundle version on the release.

For CAPI:
If I'm not mistaken I think we should be fine here too since the bundle version we have in the default-apps is v1.x that is PSS ready.

**Comment by stone-z** [comment]
Current app status:
```
╭────┬────────┬─────────────────────────┬─────────┬───────╮
│  # │  team  │           app           │ version │ count │
├────┼────────┼─────────────────────────┼─────────┼───────┤
│  0 │ shield │ app-exporter            │ 0.0.5   │     1 │
│  1 │ shield │ app-exporter            │ 0.1.1   │     1 │
│  2 │ shield │ app-exporter            │ 0.10.0  │     1 │
│  3 │ shield │ app-exporter            │ 0.10.1  │     1 │
│  4 │ shield │ app-exporter            │ 0.20.2  │     3 │
│  5 │ shield │ app-exporter            │ 0.7.8   │     2 │
│  6 │ shield │ app-exporter            │ 0.8.0   │     1 │
│  7 │ shield │ dipstick                │ 0.0.3   │    15 │
│  8 │ shield │ exception-recommender   │ 0.0.5   │    45 │
│  9 │ shield │ exception-recommender   │ 0.1.1   │    23 │
│ 10 │ shield │ falco                   │ 0.8.0   │    23 │
│ 11 │ shield │ jiralert                │ 0.1.2   │    19 │
│ 12 │ shield │ jiralert                │ 0.1.3   │    14 │
│ 13 │ shield │ kyverno                 │ 0.17.5  │    11 │
│ 14 │ shield │ kyverno                 │ 0.17.6  │    18 │
│ 15 │ shield │ kyverno                 │ 0.17.9  │    15 │
│ 16 │ shield │ kyverno-policies        │ 0.20.2  │    48 │
│ 17 │ shield │ kyverno-policy-operator │ 0.0.5   │    46 │
│ 18 │ shield │ kyverno-policy-operator │ 0.0.6   │     1 │
│ 19 │ shield │ kyverno-policy-operator │ 0.0.7   │    43 │
│ 20 │ shield │ pss-operator            │ 0.4.0   │    19 │
│ 21 │ shield │ security-bundle         │ 1.6.1   │    11 │
│ 22 │ shield │ security-bundle         │ 1.6.2   │    18 │
│ 23 │ shield │ security-pack           │ 0.12.0  │     2 │
│ 24 │ shield │ starboard-exporter      │ 0.7.0   │     2 │
│ 25 │ shield │ starboard-exporter      │ 0.7.3   │    19 │
│ 26 │ shield │ starboard-exporter      │ 0.7.8   │    38 │
│ 27 │ shield │ trivy                   │ 0.10.0  │    19 │
│ 28 │ shield │ trivy                   │ 0.10.1  │    20 │
│ 29 │ shield │ trivy                   │ 0.9.0   │    19 │
│ 30 │ shield │ trivy-app               │ 0.6.0   │     1 │
│ 31 │ shield │ trivy-operator          │ 0.5.1   │    14 │
│ 32 │ shield │ trivy-operator          │ 0.7.2   │    24 │
├────┼────────┼─────────────────────────┼─────────┼───────┤
│  # │  team  │           app           │ version │ count │
╰────┴────────┴─────────────────────────┴─────────┴───────╯
```

Minimum app versions:
`app-exporter`: not ours (?)
`dipstick`: N/A (MC app only)
`exception-recommender`: N/A (versioned with security-bundle, is a PSS tool)
`falco`: v0.6.6
`jiralert-app`: v0.1.2
`kyverno`: technically 0.16.0, but versioned with security-bundle
`kyverno-policies`: N/A (versioned with security-bundle, contains no workloads)
`kyverno-policy-operator`: N/A (versioned with security-bundle, is a PSS tool)
`pss-operator`: N/A (MC app only)
`security-bundle`: versions are pinned to releases. 0.x for non-PSS, 1.x for PSS
`security-pack`: replaced with `security-bundle`. Those 2 will be `potato / stage and / prod` https://github.com/giantswarm/giantswarm/issues/29715
`starboard-exporter`: v0.7.8
`trivy`: v0.8.1
`trivy-app`: replaced with `trivy`. That 1 will be `fox / sv43d` https://github.com/giantswarm/giantswarm/issues/29715
`trivy-operator`: v0.5.0

**Comment by stone-z** [comment]
The potato security packs have been removed, and all starboard-exporters are updated.
Waiting only for the old Trivy on `fox`

**Comment by stone-z** [comment]
The last remaining trivy-app has been removed. We're all set
