### ISSUE TITLE
Enable the configuration of garbage collector in kube controller manager for CAPI providers

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#3286]
For CAPVCD it is defined <https://github.com/giantswarm/cluster-cloud-director/blob/main/helm/cluster-cloud-director/templates/kubeadmcontrolplane.yaml#L80|here>

[Slack Message](https://gigantic.slack.com/archives/C02EVLE9W/p1708684781627879?thread_ts=1708608951.364249&cid=C02EVLE9W)

**Comment by weseven** [comment]
Opened https://github.com/giantswarm/cluster/pull/123 to make the threshold configurable through helm value, keeping the current default of 125 when not specified.

**Comment by weseven** [comment]
PR merged in cluster chart, so it will be available to configure in new versions of cluster-aws.
Eventually all providers will be based on the cluster chart, so will get the change.
In the meantime, if there is urgency for a specific provider, a specific change can be made on the provider chart (e.g., cluster-azure).
