### ISSUE TITLE
Sales Enablement - Managed apps

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#3287]
The request from our Sales team is to help communicate the value we provide to our customers by managing apps

- What apps do we manage for our customers, and how do customers use them? 
-  What their experiences are - what they were able to replace technology-wise, what they can now solve that they couldn’t in the past, what benefits they get out of it that maybe even go beyond what they expected

Draft of the Slide deck - https://docs.google.com/presentation/d/1CDMSKfLFbujHgjj8e85evnSi1w71CKqHu3i_4UPIHKA/edit?usp=sharing

```[tasklist]
### Tasks
- [ ] Agenda - who prepares what
- [x] Schedule the call
- [ ] Communicate
```

We can combine this with #3288 if this makes sense

**Comment by snizhana-dynnyk** [comment]
@Rotfuks @QuentinBisson @stone-z @weatherhog Hi! I need your help organizing the next Sales Enablement session on Managed Apps. 
I am looking at the last week of March - between Kubecon and Easter. Are you okay with this timeline?

There is a draft of the Slide deck; you can start by adding Apps you want to talk about to the Agenda, and we can further discuss the content in the Platform sync

**Comment by snizhana-dynnyk** [comment]
@weatherhog we can also combine topics with https://github.com/giantswarm/roadmap/issues/3288 if you thing there is enough time to prepare both, let me know please

**Comment by weatherhog** [comment]
I am having a hard time with the word "managing"? What does managing mean? I think this discussion comes up every now and then, what a managed app really is and what the understanding of a managed app is. 
On the one side we have a lot of Apps in the catalog that are managed Apps but managed in the name of we take care that the apps runs on our k8s installations but installation and config is on customer side on the other side we have apps like Kong where we also take care of the complete lifecycle for customers.

**Comment by QuentinBisson** [comment]
Are we talking about managed apps or platform because those are 2 different topics :D But otherwise, what do I have to ask @Rotfuks to do? :p

**Comment by stone-z** [comment]
I've added some slides, hopefully it contains what was basically intended :sweat_smile: I may update further as the date gets closer

**Comment by snizhana-dynnyk** [comment]
> I am having a hard time with the word "managing"? What does managing mean? I think this discussion comes up every now and then, what a managed app really is and what the understanding of a managed app is. On the one side we have a lot of Apps in the catalog that are managed Apps but managed in the name of we take care that the apps runs on our k8s installations but installation and config is on customer side on the other side we have apps like Kong where we also take care of the complete lifecycle for customers.

that is another good point to include to the Agenda - how we define 'Managed' app and how our customers want to define it

**Comment by Rotfuks** [comment]
Hmm...As I wanted to "review" the whole value proposition with the Atlas team first I can take this directly into account and plan to summarise our outcome there for this slide. But that will most likely take the whole week from my side.

**Comment by snizhana-dynnyk** [comment]
great! I anyway couldn’t find time before April with kubecon and Easter holidays. So we have plenty of time to prepare, I will remind you again, and let's review the agenda a couple of weeks before.

**Comment by snizhana-dynnyk** [comment]
It is scheduled now for the 18th of April 🙃

**Comment by snizhana-dynnyk** [comment]
@Rotfuks @weatherhog Hi, guys! Will you find time till next Thursday to prepare slides for Sales Enablement as Zach did?
to remind you the topic - "What apps do we manage for our customers, and how do customers use them?". Maybe include concrete use cases like wich customer uses what app to solve which problem and the value they get. Let me know if you want to brainstorm together.

**Comment by weatherhog** [comment]
@snizhana-dynnyk How much time do we have per team? Having in mind that talking about features and values in service Mesh took about 40 minutes and seeing that the slot for all platform teams is only 60 minutes, it would help me to break down what to present and what not.

**Comment by snizhana-dynnyk** [comment]
Yeah, it has to be shorter, we have 15 minutes per team, including questions. But you don't need to explain all features that the app has but only what is the main problem it solves preferably in an example

**Comment by stone-z** [comment]
Due to my timezone I can't make it to the actual Sales Enablement sync next week, so I pre-recorded some information. The recording is saved [in the SIG / Product Marketing / Sales Enablement folder in Google Drive](https://drive.google.com/file/d/1DmCbv2BMX2wtMFTphXZZQGkWogfrLv6h/view?usp=drive_link).

Happy to address any questions here, in Slack, or wherever.
