### ISSUE TITLE
CoreDNS monitoring on CAPI

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#3293]
CoreDNS sloth alerts are "provider" dependent.

We need to review the setup, unify them and make them work on CAPI based clusters.

https://github.com/giantswarm/sloth-rules/tree/main/helm/sloth-rules/files/aws

**Comment by ubergesundheit** [comment]
Looks like this is already done in https://github.com/giantswarm/sloth-rules/pull/171
