### ISSUE TITLE
Support `ServicePrincipal` type for SystemAssigned Managed Indentities in CAPZ

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3294]
## User Story

For Multi-Subscription setup in CAPZ, currently the Management Cluster Managed Identity (`mc_name-capz`) requires at least Role Based User Access Administrator rights with restriction to `Contributor` on the Subscription of Workload cluster, such that it can assign the Workload Cluster nodes identities the `Contributor` rights on the Resource Group of the Workload Cluster. This however creates a security flaw, where, if the identity is overtaken, the `mc_name-capz` can assign `Contributor` rights to any entity, also users.

With current setup the conditional assignment on Azure side, limiting the scope of actions that can be performed by `mc_name-capz` does not work:

```
(
 (
  !(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})
 )
 OR 
 (
  @Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals {b24988ac-6180-42a0-ab88-20f7382dd24c}
  AND
  @Request[Microsoft.Authorization/roleAssignments:PrincipalType] ForAnyOfAnyValues:StringEqualsIgnoreCase {'ServicePrincipal'}
 )
)
```

Issue is that the upstream CAPZ code does not set the `principalType: ServicePrincipal` in the role assignment request, where then towards Azure SDK it is translated as Null, resulting in permissions error on Azure side:

https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machine.go#L347-L355

As a Customer i would like to limit the required permissions of the Management Cluster Managed Identity, where it can 

## Acceptance Criteria

- [ ] Given that the `SystemAssigned` identity feature is used, the `principalType` is set as `ServicePrincipal` such that the conditional role assignment works.

## Implementation details

- CAPZ code responsible: https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/azure/scope/machine.go#L347-L355
- azure-skd for reference: https://github.com/Azure/azure-sdk-for-go/blob/sdk/resourcemanager/authorization/armauthorization/v2.2.0/sdk/resourcemanager/authorization/armauthorization/models.go#L480-L518
- `SystemAssigned` feature set: https://github.com/giantswarm/cluster-azure/blob/main/helm/cluster-azure/values.yaml#L48

- Conditions on Azure role assignent for the WC Subscription for the `mc_name-capz`:
```
(
 (
  !(ActionMatches{'Microsoft.Authorization/roleAssignments/write'})
 )
 OR 
 (
  @Request[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals {b24988ac-6180-42a0-ab88-20f7382dd24c}
  AND
  @Request[Microsoft.Authorization/roleAssignments:PrincipalType] ForAnyOfAnyValues:StringEqualsIgnoreCase {'ServicePrincipal'}
 )
)
AND
(
 (
  !(ActionMatches{'Microsoft.Authorization/roleAssignments/delete'})
 )
 OR 
 (
  @Resource[Microsoft.Authorization/roleAssignments:RoleDefinitionId] ForAnyOfAnyValues:GuidEquals {b24988ac-6180-42a0-ab88-20f7382dd24c}
  AND
  @Resource[Microsoft.Authorization/roleAssignments:PrincipalType] ForAnyOfAnyValues:StringEqualsIgnoreCase {'ServicePrincipal'}
 )
)
```

- Other `PrincipalTypes` are `User, Groups` - however as the system assigned identity feature is used, the only viable option here is `ServicePrincipal`

**Comment by whites11** [comment]
Unfortunately, while the azure API support specifying the principal type for a role assignment (see [docs](https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/create?view=rest-authorization-2022-04-01&tabs=HTTP#request-body)), the azure golang SDK does not support that.

In fact, the `Create` function call that allows creating a Role assignment ([definition](https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/authorization/mgmt/2015-07-01/authorization/roleassignments.go#L46)) accepts a `RoleAssignmentCreateParameters` parameter defined [here](https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/authorization/mgmt/2015-07-01/authorization/models.go#L663).

That type includes just one field named `RoleAssignmentProperties` and defined [here](https://github.com/Azure/azure-sdk-for-go/blob/2187aca40bbf6931ffac666977e5d29128d82585/services/authorization/mgmt/2015-07-01/authorization/models.go#L832).

That field only contains the `RoleDefinitionID` and `PrincipalID` meaning those are the only 2 fields that are configurable while creating a role assignment using the azure SDK for go.

**Comment by whites11** [comment]
@T-Kukawka assigning to you for reporting back to customer

**Comment by whites11** [comment]
> Is that the version of the "cluster-api-provider-azure" that the GS controller is based on? I had been looking at the latest version of [cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure) On tag v1.3.2 it lists [armauthorization/v2 v2.2.0](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/v1.13.2/go.mod) as a dependency, and there the [RoleAssignmentProperties](https://github.com/Azure/azure-sdk-for-go/blob/sdk/resourcemanager/authorization/armauthorization/v2.2.0/sdk/resourcemanager/authorization/armauthorization/models.go#L480-L518) has more fields

My discoveries are on the main branch of capz. Even if 1.3.2 might be working, we can't lock ourselves to one specific version because that would prevent us from upgrading to future releases. So unfortunately, even if 1.3.2 might have this possibility, we can't use/rely on it for the long term so my [comment](https://github.com/giantswarm/roadmap/issues/3294#issuecomment-1971071594) is still relevant.

**Comment by patrickdmw** [comment]
`v1.3.2` is basically `main` of [cluster-api-provider-azure](https://github.com/kubernetes-sigs/cluster-api-provider-azure). The tag is from Feb 22nd.

I think you got an older tag from the [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go/blob/v68.0.0/services/authorization/mgmt/2015-07-01/authorization/models.go#L663) in your link. Tag `v68.0.0` is one year old.
In the tag `sdk/resourcemanager/authorization/armauthorization/v2.2.0` and on `main` the `azure-sdk-for-go` uses this for models `sdk/resourcemanager/authorization/armauthorization/models.go` which has the new options.
* [sdk/resourcemanager/authorization/armauthorization/v2.2.0](https://github.com/Azure/azure-sdk-for-go/blob/sdk/resourcemanager/authorization/armauthorization/v2.2.0/sdk/resourcemanager/authorization/armauthorization/models.go#L480-L518)
* [main](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/resourcemanager/authorization/armauthorization/models.go#L1522-L1560)

**Comment by whites11** [comment]
ok, confirmed. I was using our fork of the CAPZ project which apparently is outdated.
In upstream's main there are indeed the new fields.
I will try to hardcode `PrincipalType:    ptr.To(armauthorization.PrincipalTypeServicePrincipal),` and run a test to check if this works.

**Comment by whites11** [comment]
not sure if this is because of my change or not, I get this

```
E0304 15:28:47.008575      14 controller.go:329] "Reconciler error" err=<
	failed to reconcile AzureMachine: failed to reconcile AzureMachine service roleassignments: cannot assign role to VirtualMachine system assigned identity: failed to create or update resource systemassignedidentity-2379/0f788bb8-dd5a-4b1f-8a06-c459f32edad0 (service: roleassignments): PUT https://management.azure.com/subscriptions/6b1f6e4a-6d0e-4aa4-9a5a-fbaca65a23b3/resourceGroups/providers/Microsoft.Authorization/roleAssignments/0f788bb8-dd5a-4b1f-8a06-c459f32edad0
	--------------------------------------------------------------------------------
	RESPONSE 400: 400 Bad Request
	ERROR CODE: InvalidApiVersionParameter
	--------------------------------------------------------------------------------
	{
	  "error": {
	    "code": "InvalidApiVersionParameter",
	    "message": "The api-version '2022-04-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
	  }
	}
```

**Comment by patrickdmw** [comment]
That's weird. According to their documentation `2022-04-01` is valid, and there are no 2023 versions
https://learn.microsoft.com/en-us/rest/api/authorization/versions?view=rest-authorization-2022-04-01

It looks like, the request is treated as one to a different api, that has different versions.
Is the resource group name missing?
```
https://management.azure.com/subscriptions/6b1f6e4a-6d0e-4aa4-9a5a-fbaca65a23b3/resourceGroups/<RESOURCE_GROUP?>/providers/Microsoft.Authorization/roleAssignments/0f788bb8-dd5a-4b1f-8a06-c459f32edad0
```

**Comment by whites11** [comment]
The plan is to dig deeper into this today. Will report any new discoveries

**Comment by whites11** [comment]
@patrickdmw we were able to verify your theory and we opened a PR upstream to make this land into official CAPZ https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4625

**Comment by patrickdmw** [comment]
that's awesome, thank you :-)

**Comment by whites11** [comment]
The upstream PR was merged and there are 2 more PRs to backport to 1.13 and 1.14.

We should have this feature soon in a release

**Comment by T-Kukawka** [comment]
this has been released 3 days ago: https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases

**Comment by T-Kukawka** [comment]
Due to breaking changes in 1.13 release where the AAD Pod Indentities are removed, we cannot easily upgrade to that upstream release. Instead for now we will bring this change to our fork and work on proper upgrade to the latest CAPZ: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4625

**Comment by erkanerol** [comment]
The plan:
- Get 1.12.4 as base (That still supports pod identities)
- Cherry-pick 005b9f857455de32a808c88d8248f23184c72b8e
- Cherry-pick our custom changes on our fork. See https://github.com/giantswarm/cluster-api-provider-azure/commits/v1.11.0-gs.alpha.3/

**Comment by erkanerol** [comment]
Here is our fork on top of 1.12.4 https://github.com/giantswarm/cluster-api-provider-azure/releases/tag/v1.12.4-gs.alpha.2

Here is the PR on the app side https://github.com/giantswarm/cluster-api-provider-azure-app/pull/151

**Comment by erkanerol** [comment]
All clusters are upgraded to the latest version. Now, we can release CAPZ. https://github.com/giantswarm/giantswarm/issues/31248

**Comment by erkanerol** [comment]
We upgraded all clusters and released the new CAPZ version. Testing it now.

**Comment by erkanerol** [comment]
Patrick confirmed that this is working with the latest CAPZ.  https://gigantic.slack.com/archives/C061GTDF682/p1721222039445299?thread_ts=1721201134.112509&cid=C061GTDF682

**Comment by erkanerol** [comment]
There was a bug in private-endpoint-operator and we fixed it. https://github.com/giantswarm/azure-private-endpoint-operator/pull/87 
Closing.
