### ISSUE TITLE
pre-commit python version upgrade for projects with no python

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3302]

**Comment by uvegla** [comment]
Removals:

- https://github.com/giantswarm/app-operator/pull/1265
- https://github.com/giantswarm/helmclient/pull/616
- https://github.com/giantswarm/kubeconfig/pull/198
- https://github.com/giantswarm/konfigure/pull/288
- https://github.com/giantswarm/appcatalog/pull/195
- https://github.com/giantswarm/app/pull/367
- https://github.com/giantswarm/cluster-apps-operator/pull/485

**Comment by mproffitt** [comment]
Done
