### ISSUE TITLE
Add additional Teleport metrics to Grafana dashboard

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3304]
As per https://goteleport.com/docs/reference/metrics page, we need to add following metrics to the Teleport Grafana dashboard, these metrics will be helpful to keep Teleport health in check and also during investigation.

Name | Type | Component | Description
-- | -- | -- | --
process_state | gauge | Teleport | State of the teleport process: 0 - ok, 1 - recovering, 2 - degraded, 3 - starting.
server_interactive_sessions_total | gauge | Teleport | Number of active sessions.
teleport_cache_events | counter | Teleport | Number of events received by a Teleport service cache. Teleport's Auth Service, Proxy Service, and other services cache incoming events related to their service.
teleport_cache_stale_events | counter | Teleport | Number of stale events received by a Teleport service cache. A high percentage of stale events can indicate a degraded backend.
rx | counter | Teleport | Number of bytes received during an SSH connection.
tx | counter | Teleport | Number of bytes transmitted during an SSH connection.
teleport_connected_resources | gauge | Teleport Auth | Number and type of resources connected via keepalives.
teleport_registered_servers | gauge | Teleport Auth | The number of Teleport services that are connected to an Auth Service instance grouped by version.
user_login_total | counter | Teleport Auth | Number of user logins
failed_login_attempts_total | counter | Teleport Proxy | Number of failed tsh login or tsh ssh logins.
proxy_connection_limit_exceeded_total | counter | Teleport Proxy | Number of connections that exceeded the Proxy Service connection limit.
proxy_ssh_sessions_total | gauge | Teleport Proxy | Number of active sessions through this Proxy Service instance.
teleport_reverse_tunnels_connected | gauge | Teleport Proxy | Number of reverse SSH tunnels connected to the Teleport Proxy Service by Teleport instances.
teleport_kubernetes_server_join_in_flight_sessions | gauge | Teleport Kubernetes Proxy | Number of active joining sessions,
teleport_kubernetes_server_join_sessions_total | counter | Teleport Kubernetes Proxy | Total number of joining sessions.
user_max_concurrent_sessions_hit_total | counter | Teleport SSH | Number of times a user exceeded their concurrent session limit.

**Comment by ssyno** [comment]
New updates can be found on teleport [dashboard](https://grafana.grizzly.gaws.gigantic.io/goto/oLRoy-1IR?orgId=1)

**Comment by OnurYilmazGit** [comment]
Latest version of the [dashboard](https://grafana.grizzly.gaws.gigantic.io/d/fdgt69xbmwnb4f/teleport-overview?orgId=1&from=1711440038568&to=1711440330611)

**Comment by tuladhar** [comment]
We can close this one, dashboard includes all metrics mentioned in the issue.

FYI: For now dashboard is in grizzly, until we move it EKS.
