### ISSUE TITLE
Setup auto-scaling for Teleport auth and proxy pod

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3306]
Currently, autoscaling doesn't work for Teleport auth and proxy pods.

**Requirements:**

- Auto-scale auth pod using VPA
- Auto-scale proxy proxy with HPA
- Use Karpenter or Cluster autoscaler to scale node.

> [!NOTE]
> - [x] Metrics server is already deployed in the cluster as [part of this ticket](https://github.com/giantswarm/giantswarm/issues/29952)

> [!WARNING]
> As [mentioned here](https://github.com/giantswarm/giantswarm/issues/29952#issuecomment-1979253301), we can't auto-scale auth pod to more than 2 replica

**Comment by ssyno** [comment]
Opened [PR](https://github.com/gravitational/teleport/pull/39236) about HPA on upstream

**Comment by tuladhar** [comment]
Also, ping in the [Teleport slack channel](https://goteleport.slack.com/archives/CEZH6UL64/p1710319540237139) about the PR.
