### ISSUE TITLE
Use the `app.kubernetes.io/created-by` label on all k8s resources we create

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#332]
## User story

- __As a user of the Management API, I want to understand who/what created a particular resource, so that I can make an informed decision with regard to changing or deleting the resource.__

## Background

As a result of [a bit of talking](https://gigantic.slack.com/archives/C12SG2929/p1618818092045200) we had internally and a [PR](https://github.com/kubernetes/website/pull/27612) created upstream by @QuentinBisson, there is now a new [recommended label](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) for Kubernetes resources:

    app.kubernetes.io/created-by

It is similar to

    app.kubernetes.io/managed-by

but both have slightly different meaning.

For example, a resource may be created by the web user interface (happa) or kubectl gs, but it will be managed by some operator.

We should work towards applying this label in a meaningful to all the resources we create.

We may also encourage our users to do the same, to simplify communication around operations tasks.

## TODO

- [ ] Create a spec RFC describing some useful ways to set the value

**Comment by MarcelMue** [comment]
What would be the desired value of the label?
Would it be the automation which created the object? E.g. `release-operator`

**Comment by tfussell** [comment]
Following on from Marcel's question, when we run `opsctl deploy` would `created-by` be the person that ran the command or `opsctl`?

If an app is in the `aws-app-collection`, is it created by the user that released the app, `draughtsman`, `helm`, or `github`?

And would we propagate the label from the App CR to the Chart CR to the helm release and all of its resources?

**Comment by tfussell** [comment]
We're not sure what else needs to be done for SIG Operator so dropping it from the board for now.

**Comment by marians** [comment]
For WG management API: Can we push a decision regarding how and where to use the `app.kubernetes.io/created-by` label? I think it would increase the MAPI usability.

**Comment by PrashantR31** [comment]
Hii @marians and @MarcelMue, just wanted to know if anything was decided on :
> For WG management API: Can we push a decision regarding how and where to use the `app.kubernetes.io/created-by` label? I think it would increase the MAPI usability.

**Comment by kuosandys** [comment]
@marians We discussed this in backlog grooming today, and was wondering if you would know the appropriate priority level for this issue? Thank you!

**Comment by marians** [comment]
None, I guess. Seriously, as it's unclear what value should be written into the label, there is hardly any priority in executing this.

**Comment by QuentinBisson** [comment]
The label was removed upstream so I thing we can close https://github.com/kubernetes/website/pull/35810

**Comment by marians** [comment]
Indeed, good to know. Thanks.
