### ISSUE TITLE
Differences between Vintage and CAPI `Route53Manager-Role` role

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#3327]
There a few differences in the roles from one system to the other one. This won't cause any issue with the default app, but custsomers running a second instance will.

---

**First** difference is that the `Trusted entities` are too restrictive on CAPI. 
In CAPI, the condition is:
```
"{{.CloudFrontDomain}}:sub": "system:serviceaccount:kube-system:external-dns"

```

where in Vintage it's:
```
"{{.CloudFrontDomain}}:sub": "system:serviceaccount:*:*external-dns*"
```

Those * make the difference when trying to assume the role from a different namespace or ServiceAccount. This will affect customers.

---

**Second** difference is less problematic but it might pose a security risk. The `Policy` is too open in CAPI, where in vintage it's restricted to the cluster zone.

CAPI
```
        {
            "Action": "route53:ChangeResourceRecordSets",
            "Resource": [
                "arn:*:route53:::hostedzone/*"
            ],
            "Effect": "Allow"
        },
```

Vintage
```
        {
            "Action": "route53:ChangeResourceRecordSets",
            "Resource": [
                "arn:aws:route53:::hostedzone/{ZONE_ID}",
                "arn:aws:route53:::hostedzone/{ANOTHER_ZONE_ID}"
            ],
            "Effect": "Allow"
        },
```
This one is not a functional problem and it can be addressed in future releases.

---

Ref https://github.com/giantswarm/roadmap/issues/3212

**Comment by T-Kukawka** [comment]
hey @mcharriere i am closing this in favor of: https://github.com/giantswarm/roadmap/issues/3331 and https://github.com/giantswarm/roadmap/issues/3330. We will tackle the immediate impact on the migration for external-dns, however second we will refine in the future based on our plans with Crossplane. Thanks for reporting!
