### ISSUE TITLE
Integrate deprecated `k8s-initiator-app` features with `migration-cli`

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3332]
## User Story

As a customer i would like to have access to the same feature set as`k8s-initiator-app` was providing during and after CAPA migration.

First part of the node-tainting capabilities were already added: https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/node-tainting.md

Following the same idea, there is set of remaining features to be added to the `migration-cli`:
- audit-policy configuration - https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/audit-policies.md
- container-logs configuration - https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/container-logs.md
- admission-controller configuration - https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/admission-controllers.md
- node-tainting configuration - https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/node-tainting.md

## Acceptance Criteria

- [x] audit-policy configuration is passed to CAPA CRs during migration - https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/audit-policies.md
- [x] container-logs configuration is passed to CAPA CRs during migration- https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/container-logs.md
- [x] admission-controller configuration is passed to CAPA CRs during migration - https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/admission-controllers.md
- [x] node-tainting configuration is passed to CAPA CRs during migration - https://github.com/giantswarm/capi-migration-cli/blob/main/k8s-initiator-features/node-tainting.md

**Comment by mnitchev** [comment]
Released in https://github.com/giantswarm/capi-migration-cli/releases/tag/v0.4.0
