### ISSUE TITLE
Deploy Mimir on CAPZ

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3334]
- [x] cuckoo
- [x] gaggle https://github.com/giantswarm/giantswarm-configs/pull/102
- [x] glean
- [x] glippy
- [x] ~~goose~~ ephemeral
- [x] mammoth
- [x] wallaby
- [x] whale blocked by https://github.com/giantswarm/wacker-configs/pull/1

**Comment by hervenicol** [comment]
Started today with Glippy.

Related PRs:
* https://github.com/giantswarm/mimir-app/pull/97
* https://github.com/giantswarm/shared-configs/pull/85/

**Comment by QuentinBisson** [comment]
I added missing config changes above.
I'll investigate a bit later tonight but apart from the restarts, we have to check why we have to set backend: azure twice (https://github.com/giantswarm/shared-configs/commit/1febb14ec95b1620e18a35fec128f017ec28e551) and we need to fix the object storage operator secret name generation

**Comment by QuentinBisson** [comment]
https://github.com/giantswarm/giantswarm/issues/31087 Storage account secret issue

**Comment by QuentinBisson** [comment]
Storage secret is fixed on all MCs

**Comment by QuentinBisson** [comment]
Glean is using an auto branch so we will have to wait for it to be recreated first

**Comment by QuentinBisson** [comment]
Deployed everywhere but whale because the object storage operator is not working for some unknown reasons

**Comment by QuentinBisson** [comment]
Whale is currently being recreated so I will consider this as closed :)
