### ISSUE TITLE
NodeStateFlappingUnderLoad not working due to missing labels

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3339]
### Motivation

Part of https://github.com/giantswarm/roadmap/issues/3315.

Atlas [pointed out](https://github.com/giantswarm/roadmap/issues/3315#issuecomment-1989453358) that `NodeStateFlappingUnderLoad` is not working on CAPI due to missing labels (ip at least).

### Todo

- [ ] Fix `NodeStateFlappingUnderLoad`

**Comment by njuettner** [comment]
I was comparing Vintage and CAP why we don't have the "IP" label set. 

This is done by kubelet in Vintage by setting the flag `--node-labels="node.kubernetes.io/worker,role=worker,ip=${DEFAULT_IPV4}"`

In CAPI we do not set the ip, only 
`--node-labels=role=worker,giantswarm.io/machine-pool=grizzly-def00a,label=grizzly`

**Comment by njuettner** [comment]
We need to draft a new release for cluster chart and update all MC's + existing WC's

**Comment by njuettner** [comment]
Merged in https://github.com/giantswarm/cluster-aws/releases/tag/v0.68.0
