### ISSUE TITLE
Workload cluster release 14.1.0 for KVM

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#334]
Kubernetes v1.19.11

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#v11911

### Provide a new release with the kubernetes version v1.19.11

* [x] Check with the teams about wip changes within k8scloudconfig and the provider-specific operators. Decide with version folder to use.
* [x] Retag new image in retagger
* [x] Check [upstream changelogs](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md).
  * [x] Check urgent upgrade notices.
  * [x] Check deprecation notices.
  * [x] Check component upgrades.
    * [x] Calico
    * [x] ETCD
    * [x] Container Linux
* [x] Create a PR in k8scloudconfig with the new kubernetes version
  * [x] Update k8s version in the different template files
  * [x] Use k8s version for `k8s-addons` (e.g. https://github.com/giantswarm/k8scloudconfig/blob/4695b7d6eb35eae234d0ce0c0c09f4b412525a68/v_4_7_0/files/conf/k8s-addons#L5)
* [x] Update cluster-autoscaler
* [x] Vendor k8scloudconfig in the provider-specific operators
* [x] Create a wip release (major version change if it is a minor kubernetes upgrade)
* [x] Do this for each provider
* [x] Check Prometheus rules for deprecated metrics and fix them if necessary

### Check migration recommendations

Check migration recommendations from kubernetes and decide what we need to document for the customer and what we should migrate automatically for them

* [x] Do we need to change our own resources within the tenant clusters?
* [x] What do we need to communicate to our customers?
* [x] Anything else that would be better automated for the upgrade?

### Run e2e and conformance tests

* [ ] Start a new cluster and run conformance tests against it
* [ ] Start a new cluster and run e2e tests against it
* [ ] Do this for each provider

### Check Core Components

* [x] Check core components for updates and include them in cluster-operator
  * [x] Cert-exporter
  * [x] Chart-operator
  * [x] Cluster-autoscaler
  * [x] CoreDNS
  * [x] Kube-state-metrics
  * [x] Net-exporter
  * [x] Nginx ingress controller
  * [x] Node-exporter
* [x] All helm releases in the giantswarm namespace should be in status deployed
* [ ] Core components are runnning without errors
  * [ ] Cert-exporter
  * [ ] Chart-operator
  * [ ] Cluster-autoscaler
  * [ ] CoreDNS
  * [ ] Kube-state-metrics
  * [ ] Net-exporter
  * [ ] Nginx ingress controller
  * [ ] Node-exporter
* [x] Cluster-operator is running without errors
* [x] Cluster-operator is able to create chart-configs in the tenant

### Test migration (both cluster functionality itself and workloads)

* [ ] Start a cluster with an older version and upgrade the cluster to the new release
* [ ] Upgrade a cluster that is not critical but has some more real workloads (eg giantswarm website, dev cluster of customer)
* [ ] Do this for each provider

### Write summary for the release and update docs

* [ ] Write some release notes
* [ ] Check if our docs need to be updated
* [ ] Announce the release internally (SEs are important here)
* [ ] Announce the release to the customers

**Comment by tfussell** [comment]
Just to summarize, this release is going to have three goals:

- Provide updated components with proxy support
- Update some or all components and apps that were skipped in the KVM 14.0.0 release
- Update kvm-operator for bug fixes and disk mounting support

**Comment by tfussell** [comment]
We have tested the currently defined release a few times today. We just need to get a few more changes into kvm-operator and this should be ready to go early next week.

**Comment by tfussell** [comment]
Merged and announced.
