### ISSUE TITLE
Prevent /usr/bin/coreos-metadata from running the nodes

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3342]
**Is your feature request related to a problem? Please describe.**

The `/usr/bin/coreos-metadata` running on our nodes is creating a lot of audit logs and will incur a lot of cost for customers that store the nodes audit logs. We are not using it, we should disable it and maybe check if we have other noisy tools that we do not use.

**Describe the solution you'd like**

Disable the `/usr/bin/coreos-metadata` tool running on our clusters

**Describe alternatives you've considered**

We considered filtering out the tool but this is a workaround that the customer needs to maintain and it not happy about

**Additional context**

**Comment by T-Kukawka** [comment]
@giantswarm/team-turtles this seems like in your area regarding the OS

**Comment by weseven** [comment]
We are in fact using metadata generated from this service, e.g. on the cluster chart:

https://github.com/giantswarm/cluster/blob/51037e581ffe6025f93a937eaf9442912eff82fc/helm/cluster/templates/clusterapi/workers/_helpers_joinconfiguration.tpl#L11

https://github.com/giantswarm/cluster/blob/51037e581ffe6025f93a937eaf9442912eff82fc/helm/cluster/templates/clusterapi/controlplane/_helpers_joinconfiguration.tpl#L13

https://github.com/giantswarm/cluster/blob/51037e581ffe6025f93a937eaf9442912eff82fc/helm/cluster/templates/clusterapi/controlplane/_helpers_initconfiguration.tpl#L16

https://github.com/giantswarm/cluster/blob/51037e581ffe6025f93a937eaf9442912eff82fc/helm/cluster/templates/clusterapi/_helpers_flatcar.tpl#L148

What exactly is generating noise? We should tune some configs to suppress some failures, but I think disabling the service completely would break some functionality as we require some metadata coming from the service at the moment.

**Comment by QuentinBisson** [comment]
I think the main one is about ssh keys downloading

**Comment by weseven** [comment]
Oh in that case the culprit is the sshkeys service, which I'm fairly sure we don't need. I think it should be enough to mask that service (to be tested).
Not sure if it's better to do the change on the cluster chart or at image building time, will evaluate once we pick this up.

**Comment by T-Kukawka** [comment]
Besides CAPI in general, this would be required on Vintage as well, right @QuentinBisson ?

**Comment by njuettner** [comment]
Merged in https://github.com/giantswarm/cluster-aws/releases/tag/v0.68.0
