### ISSUE TITLE
SPIKE: Investigate the CRD API Types used across the Management Clusters

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3344]
## Description

Currently while testing the IMDS v2 story, we have found out that the MCs are serving different CRD types than expected. We should be running v1beta2, however some clusters are still created with v1beta1. We have to find out what causes this and what types we are running where in preparation for the v1beta1 removal.

## Acceptance Criteria

- prepare a list of the CRD API types used on the MCs
- prepare a dashboard with the MC CRD types to have an overview

## Implementation details

- implemetation info

**Comment by T-Kukawka** [comment]
As we checked, all MCs are using v1beta2, we will try to create new WC to recheck the assumption on `golem`

**Comment by bdehri** [comment]
`
#!/bin/bash

# Get installations filtered by the desired conditions
installations=$(opsctl list installations | grep -E 'capa' | grep -vE 'goat|ephemeral|CODENAME' | cut -d' ' -f1)

# CRDs to process
CRDs=("awsmachinetemplate" "awsmachinepool")

for installation in $installations; do
    echo "Installation: $installation"
    opsctl login "$installation"
    echo "" > "crds/${installation}-crds.out"
    kubectl api-resources | grep -i -e 'awsmachinepool' -e 'awsmachinetemplate' >> "crds/${installation}-crds.out"
    output_file="crs/${installation}-crs.out"
    echo "" > "$output_file"
    for CR in "${CRDs[@]}"; do
        echo "cr type: $CR" >> "$output_file"
        kubectl get --all-namespaces $CR -o custom-columns=NAMESPACE:.metadata.namespace,NAME:.metadata.name,APIVERSION:.apiVersion >> "$output_file"  # append output to the file
    done
done
`

I used this script to get used CR versions and registered CRDs.

**Comment by mnitchev** [comment]
I got the dashboard working by following [these docs](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md). I ended up adding this flag to kube-state-metrics to get it working
```
        - --custom-resource-state-config
        - |
          spec:
            resources:
              - groupVersionKind:
                  group: apiextensions.k8s.io
                  version: "v1"
                  kind: "CustomResourceDefinition"
                labelsFromPath:
                  object: [metadata, name]
                metrics:
                  - name: "crd_info"
                    help: "CRD Info"
                    each:
                      type: Info
                      info:
                        path: [spec, versions]
                        labelsFromPath:
                          version: [name]
```
Aftewards this query can be used to get the number of resources in a specific version
```
count by (version) (kube_customresource_crd_info{object=~".*infrastructure.cluster.x-k8s.io.*"})
```
We'd need to expose some values in https://github.com/giantswarm/kube-prometheus-stack-app/tree/main/helm/kube-prometheus-stack to be able to configure this for our CAPA installations and then export the metrics in Cortex https://github.com/giantswarm/prometheus-rules/blob/master/helm/prometheus-rules/templates/recording-rules/grafana-cloud.rules.yml

**Comment by mnitchev** [comment]
This might be a better place to configure the metrics https://github.com/giantswarm/cluster-api-monitoring-app?tab=readme-ov-file#configuring

**Comment by mnitchev** [comment]
Done with the `CAPA CRD versions` dashboard in our grafana cloud
