### ISSUE TITLE
CAPI monitoring uses inconsistent labels, leading to unwanted alerts

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3354]
In https://github.com/giantswarm/cluster-api-monitoring-app, `capi_machine_status_phase` (and most other metrics) has a `cluster_name` label. In our alerting rules, we however consistently use `cluster_id`. This probably also leads to wrong values of `cluster_type="management_cluster"` even if an object (e.g. `Machine`) relates to a WC. Several alert-blocking rules such as [these](https://github.com/giantswarm/prometheus-meta-operator/blob/bf869c600155fc8643eb5710af7c0bd1419c2cb4/files/templates/alertmanager/alertmanager.yaml#L19-L28) won't work without the correct `cluster_id`.

There are different ways how to solve this. We should _not_ change the kube-state-metrics definitions (such as `labelsFromPath.cluster_name`) since those are already part of upstream CAPI. Rather, we can make it work for us through relabel configs.

Current metrics example (wrong):

![Image](https://github.com/giantswarm/roadmap/assets/1376043/c6e00d09-406e-4086-acbd-316f3fff32b2)

[Example chat thread for an unwanted alert](https://gigantic.slack.com/archives/C02JTRT152L/p1711530860892229)

## Acceptance Criteria

- [ ] `installation="name_of_mc"`+`cluster_id="name_of_mc_or_wc"` + `cluster_type="{management_cluster,workload_cluster}"` working as intended

**Comment by whites11** [comment]
the cluster_id metric is tricky. it is injected by the prometheus agent as an external label. Since `cluster-api-monitoring` is running in the MC, it will always get the MC name as a value

**Comment by whites11** [comment]
fixed in 1.11.0
