### ISSUE TITLE
Optimized Resource Usage for Observability Platform

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3360]
### Motivation
we aim to have minimal resource usage for our observability platform in the clusters of our customers. In a best case scenario they don't realise our tools are running there and they lead to no additional cost. This is not really possible, but we can reduce the impact. Here's a list of tickets we collected to improve the overall resource consumption of our systems. 

```[tasklist]
### Stories
- [ ] https://github.com/giantswarm/giantswarm/issues/30353
- [ ] https://github.com/giantswarm/giantswarm/issues/28566
- [ ] https://github.com/giantswarm/giantswarm/issues/29363
- [ ] https://github.com/giantswarm/giantswarm/issues/31132
- [ ] https://github.com/giantswarm/roadmap/issues/3514
- [ ] https://github.com/giantswarm/giantswarm/issues/24418
- [ ] https://github.com/giantswarm/giantswarm/issues/30317
- [ ] https://github.com/giantswarm/giantswarm/issues/30830
- [ ] https://github.com/giantswarm/roadmap/issues/3534
- [ ] https://github.com/giantswarm/roadmap/issues/3576
```

### Outcome
- We consume less resources for our observability platform than before.

**Comment by QuentinBisson** [comment]
Because I like to close tickets @Rotfuks all items are closed here :)
