### ISSUE TITLE
Making Loki Nicer

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3362]
### Motivation
We rolled out Loki everywhere and already gathered initial experience with it. Now we collected a small list of improvements we need to work on in order to get Loki in a really good state where we have GA confidence in it. 

```[tasklist]
### Stories
- [ ] https://github.com/giantswarm/giantswarm/issues/28196
- [ ] https://github.com/giantswarm/giantswarm/issues/29073
- [ ] https://github.com/giantswarm/giantswarm/issues/31117
- [ ] https://github.com/giantswarm/roadmap/issues/3178
- [ ] https://github.com/giantswarm/giantswarm/issues/30309
- [ ] https://github.com/giantswarm/roadmap/issues/3563
- [ ] https://github.com/giantswarm/giantswarm/issues/28224
- [ ] https://github.com/giantswarm/giantswarm/issues/30308
- [ ] https://github.com/giantswarm/giantswarm/issues/29719
```

### Outcome
- All known issues with Loki are fixed for now and we have GA level confidence in the logging part of the observability platform.

**Comment by QuentinBisson** [comment]
@Rotfuks let's close 🥳

**Comment by Rotfuks** [comment]
Yep, wanted to do that in the daily tomorrow :)

**Comment by QuentinBisson** [comment]
yeeeh
