### ISSUE TITLE
App Platform rollback support

### ISSUE THREAD

**Issue by rossf7** [giantswarm/roadmap#337]
**Business value**: Increase customer usage of app platform by making app upgrades safer.

**User value:** Users can trigger a rollback even if the helm upgrade succeeds if their own sanity checks fail. 

Created after discussion in https://github.com/giantswarm/roadmap/issues/279 about gitops tooling. A gitops workflow can also help with rollbacks. To provide greater visibility of changes and easier reverting of changes.

However, adding rollback support to App Platform would work even if the user was not using a gitops approach.

## Use cases:

**1/ To trigger a rollback on apps when own checks show that latest upgrade broke something**.

Suggested solution: To have a rollback mechanism in app platform for apps, similar to k8s offer for deployments (see: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-back-a-deployment) ([Slack](https://gigantic.slack.com/archives/C6L8J93N0/p1620393031469900))

Currently: app-operator triggers a rollback when it sees that a release is stuck on 'pending-upgrade'. Customer's use case is if the release was successful, but there is unexpected bug/behavior that makes some sanity tests fail.

Customer plans to have automated testing as part of app pipelines that automatically rolls back in case a test fails. This includes all changes that fail, including config changes, not just unsuccessful helm releases and version changes.

**Comment by cokiengchiara** [comment]
This would be something on top of gitops. Or can the gitops tool do most of the heavy lifting? @piontec and @tomahawk28 will comment.

It's not super clear that we should do it.

**Comment by piontec** [comment]
Using a gitops tool, a rollback should be* as easy as reverting the git commit that broke the state. That way you can always restore the state of configuration you had. This seems a natural way to do it, and I would like to go with that instead of implementing this in app-platform (correct me if I got the requirements wrong).

*This is only true if *all of your state* is included in the git config. If there's any state outside of that (and there usually is - a database), this can already fail. So this kind of recovery needs to be tested by teams owning the product. Still, the problem is the same no matter if we do that with gitops tool, app platform or something else.

**Comment by rossf7** [comment]
> Using a gitops tool, a rollback should be* as easy as reverting the git commit that broke the state. That way you can always restore the state of configuration you had. This seems a natural way to do it, and I would like to go with that instead of implementing this in app-platform (correct me if I got the requirements wrong).

@piontec See https://github.com/giantswarm/roadmap/issues/279#issuecomment-842107054 this was a feature request we got from a customer via @pipo02mix and we then got positive feedback that we were considering it.

AIUI the use case is once the deployment is successful they would like to run some automated sanity checks that all is well and if not trigger a rollback. I agree this should be possible with GitOps tooling but they would need to build that automation.

IMO this is similar to App Sets. We should try to implement this functionality with ArgoCD. If there is still a gap we can look at extending App Platform.

@cokiengchiara I think moving this to `Future > 6 months` is better. WDYT?

**Comment by cokiengchiara** [comment]
> IMO this is similar to App Sets. We should try to implement this functionality with ArgoCD. If there is still a gap we can look at extending App Platform.
> 
> @cokiengchiara I think moving this to `Future > 6 months` is better. WDYT?

Thanks @rossf7 . What's important is the outcome -- being able to rollback when their sanity checks fail. It's cool if ArgoCD (and not app platform) is used to achieve that. 

Just trying to understand -- How is it different from the rest of the gitops https://github.com/giantswarm/roadmap/issues/279 stuff where we 'just' provide the gitops tooling and 'write some docs' on how to set it up to achieve different outcomes?

**Comment by rossf7** [comment]
> What's important is the outcome -- being able to rollback when their sanity checks fail. It's cool if ArgoCD (and not app platform) is used to achieve that.

@cokiengchiara @piontec Let's close this. I agree we should try to do this with GitOps tooling. We can always re-open later if necessary.
