### ISSUE TITLE
CI Checks for Mimir Alerts

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3377]
### Motivation
The new mimir setup for our observability platform leads to new requirements for our alerts, like adding the cluster identification, since now it's centrally managed from the MC and no longer directly from the WC. In order to make sure alerts are still working as expected and improve not just the migration process but the user experience creating alerts we should add an CI check making sure all newly created alerts fit to this new requirements. 

### Todo

- [ ] Create a CI check for alerts with mimir which checks if all the requirements for mimir alerts are met. Relevant requirements: 
  - The cluster id
  - ...

### Outcome
- We have early feedback loops giving us initial feedback in the PR if an Alert might work or break on Mimir.

**Comment by QuentinBisson** [comment]
We need 4 labels:
- cluster_id
- installation
- pipeline
- provider

Can we check that we have those without spending a month building a script? Can we use promtool (validation) for this?
Can we use a simple awk command ? (if there is a by, the labels should be there) but we do not validate aggregations without by in there?

**Comment by hervenicol** [comment]
Looking what we can do with [pint](https://cloudflare.github.io/pint/)

**Comment by Rotfuks** [comment]
@hervenicol what's the progress here? Would be really good if we can get this issue closed fast, since it's blocking any alert review of giant swarm teams and thus our mimir rollout :)

**Comment by hervenicol** [comment]
> @hervenicol what's the progress here? Would be really good if we can get this issue closed fast, since it's blocking any alert review of giant swarm teams and thus our mimir rollout :)

Should be good now @Rotfuks .
All PRs are merged, and documentation is here: https://github.com/giantswarm/prometheus-rules#prometheus-linter
