### ISSUE TITLE
Managed Apps Upgrades (Month of June 2021)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#338]
Aim to focus on 30DU and get them done within 2 days.

**NGINX Ingress Controller** @giantswarm/app-squad-nginx  // @ubergesundheit 
https://github.com/giantswarm/nginx-ingress-controller-app

* Link to latest release:  https://github.com/giantswarm/nginx-ingress-controller-app/releases/tag/v1.17.0
* If won't upgrade, why?

- [ ] tick this box if there is no new upstream release and no need for upgrade
- [x] upgrade https://github.com/giantswarm/nginx-ingress-controller-app/pull/204
- [x] release

**External DNS** @giantswarm/app-squad-external-dns  @webwurst 
https://github.com/giantswarm/external-dns-app

* Link to latest release: https://github.com/giantswarm/external-dns-app/releases/tag/v2.4.0
* If won't upgrade, why?

- [ ] tick this box if there is no new upstream release and no need for upgrade
- [x] upgrade https://github.com/giantswarm/external-dns-app/pull/91
- [x] release

**Cert Manager** @giantswarm/app-squad-cert-manager  @ubergesundheit 
https://github.com/giantswarm/cert-manager-app

* Link to latest release: 
* If won't upgrade, why?

- [x] tick this box if there is no new upstream release and no need for upgrade
- [ ] upgrade
- [ ] release

**EFK** @giantswarm/app-squad-efk  // @webwurst 
https://github.com/giantswarm/efk-stack-app

* Link to latest release: 
* If won't upgrade, why?

- [ ] tick this box if there is no new upstream release and no need for upgrade
- [ ] upgrade
- [ ] release

**Kong** @giantswarm/app-squad-kong  @ubergesundheit 
https://github.com/giantswarm/kong-app

* Link to latest release: 
* If won't upgrade, why?

- [ ] tick this box if there is no new upstream release and no need for upgrade
- [x] upgrade https://github.com/giantswarm/kong-app/pull/134
- [x] release

Check to see if these issues are solved by the upgrade
- [ ] https://github.com/giantswarm/giantswarm/issues/17165
- [ ] https://github.com/giantswarm/adidas/issues/713#issuecomment-851558480

**Prometheus Operator** @giantswarm/app-squad-prometheus  @webwurst 
https://github.com/giantswarm/prometheus-operator-app

* Link to latest release: https://github.com/giantswarm/prometheus-operator-app/releases/tag/v0.8.2
* If won't upgrade, why?

- [ ] tick this box if there is no new upstream release and no need for upgrade
- [x] upgrade
- [x] address CVE https://github.com/giantswarm/giantswarm/issues/17281
- [x] release

**Loki** @giantswarm/app-squad-prometheus  @giantswarm/app-squad-loki @ubergesundheit 
https://github.com/giantswarm/loki-app

* Link to latest release: https://github.com/giantswarm/loki-app/releases/tag/v0.2.0
* If won't upgrade, why?

- [ ] tick this box if there is no new upstream release and no need for upgrade
- [x] upgrade https://github.com/giantswarm/loki-app/pull/37/files
- [x] release

Aqua - we upgrade when they say there is sth in the Aqua meeting w the customer. 

---

Notes
* Team divides the app upgrades amongst ourselves. Please add @ name beside the app
* [30 Day Upgrade Promise](https://intranet.giantswarm.io/docs/product/pdr/003_30-day-upgrade-promise/): By default, we upgrade our apps within 30 days of an upstream release. We know that falling behind releases and putting upgrades off for extended amounts of time, especially when there’s breaking changes, almost always comes back to bite us.
* Engineer can override this default and decide not to upgrade with good reason.

**Comment by ubergesundheit** [comment]
Request to include external-dns in >15.0.0 releases https://github.com/giantswarm/releases/pull/741

**Comment by piontec** [comment]
All done!! :heart:
