### ISSUE TITLE
SPIKE: Karpenter CAPA Upgrade procedure

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3382]
## User Story

As a customer, i would like to have my CAPA cluster nodes being upgraded regardless of the deployment solution, either managed by capa or by karpenter.

In Vintage we have a cronjob that is inspecting the cluster version, the rollout of karpenter nodes are triggered in batches based on the node version to refresh the instances.

Second option would be to configure the ttl on karpenter nodes such that they are refreshed periodically anyway.

Cronjob: https://github.com/giantswarm/karpenter-app/blob/main/helm/karpenter/templates/node-renewer.yaml

## Acceptance Criteria

- [ ] identify if the cronjob solution would work in CAPA clusters based on a relevant label

## Implementation details

- Implementation info to be filled out by engineer

**Comment by paurosello** [comment]
Done and released. I have some ideas to improve this and try to create a default provisioner so customers dont have to do anything.
