### ISSUE TITLE
aws-network-topology-operator deletion blocked (finalizer not removed)

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3384]
## Bug description

Same situation as https://github.com/giantswarm/roadmap/issues/3383 – a CAPA WC that was deleted very soon after creation.

The `network-topology.finalizers.giantswarm.io` finalizer remained on the `AWSCluster` object and the operator happily says it's done:

```
aws-network-topology-operator-658cfb4948-d57ss aws-network-topology-operator 2024-04-04T12:34:52.740366913+02:00 2024-04-04T10:34:52Z	INFO	Reconciling delete	{"controller": "cluster", "controllerGroup": "cluster.x-k8s.io", "controllerKind": "Cluster", "cluster": {"name":"tsa03","namespace":"org-adidas"}, "namespace": "org-adidas", "name": "tsa03", "reconcileID": "1a2478bb-2f87-43eb-980b-9e09e661ac68"}
aws-network-topology-operator-658cfb4948-d57ss aws-network-topology-operator 2024-04-04T12:34:52.740370039+02:00 2024-04-04T10:34:52Z	INFO	Done reconciling	{"controller": "cluster", "controllerGroup": "cluster.x-k8s.io", "controllerKind": "Cluster", "cluster": {"name":"tsa03","namespace":"org-adidas"}, "namespace": "org-adidas", "name": "tsa03", "reconcileID": "1a2478bb-2f87-43eb-980b-9e09e661ac68"}
```

At first glance, it looks like the operator's `reconcileDelete` function is not removing the finalizer at all:

https://github.com/giantswarm/aws-network-topology-operator/blob/6e6fbd7e3103e4460888314b83771ec460ec8173/controllers/networktopology.go#L131-L151

There's no `defer`-ede patch/update of the object, as seems to be in `reconcileNormal`. Likely we didn't catch this blatant bug ever since this code was introduced, or I'm wrong with this first look into the code 🤷.

## Designed behavior 

Deletion works and removes the finalizer once done

## Reproduction Steps

See above

## Technical information

aws-network-topology-operator v1.7.0

**Comment by mnitchev** [comment]
This operator has been archived and merged with https://github.com/giantswarm/aws-resolver-rules-operator. It is not part of the collection and shouldn't be deployed at all

**Comment by mnitchev** [comment]
Seems the operator was left over somehow and the app wasn't reconciled anymore. I've removed it manually.
