### ISSUE TITLE
Managed App Testing | Testing strategy for Managed Apps charts

### ISSUE THREAD

**Issue by rossf7** [giantswarm/roadmap#34]
We currently use the same approach for testing charts that we use for operators. But we only need to test Helm Charts and the resources they create.

This ticket is to improve the dev UX for chart developers. Current problems are.

- Requiring Go skills
- Regular vendor updates for e2e library changes and upstream components like client-go.

We should consider community tooling like Sonobuoy as well as our own internal tooling.

**Comment by snizhana-dynnyk** [comment]
The topic is in Honeybadger, closing this issue
