### ISSUE TITLE
Loki should support existing secrets for storage configuration

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#340]
**Is your feature request related to a problem? Please describe.**
At this point in time it does not seem to be possible to use an exsting secret for storage credentials in [loki-app](https://github.com/giantswarm/loki-app). This prevents the usage of for example sealed secrets.

**Describe the solution you'd like**
[loki-app](https://github.com/giantswarm/loki-app) would support specifying existing secrets.

**Comment by cokiengchiara** [comment]
> At this point in time it does not seem to be possible to use an exsting secret for storage credentials in [loki-app](https://github.com/giantswarm/loki-app). This prevents the usage of for example sealed secrets.

For my own learning, how does user get value from using sealed secrets?

**Comment by ubergesundheit** [comment]
This is our PR: https://github.com/grafana/helm-charts/pull/457 adding existing secret support to the loki-distributed chart

Sealed secrets works by having a operator running which decrypts encrypted secrets on demand for applications consuming the secrets

**Comment by cokiengchiara** [comment]
It's done.
