### ISSUE TITLE
Add style guide linting to our docs repos

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3406]
We want to ensure coherence and consistency in our writing, and decided some time ago to use the Microsoft style guide as a foundation.

Using [Vale](https://vale.sh/) we can

- Enforce style rules in CI and inform writers about style guide mismatches
- Get linting feedback during the writing process in supported editors like VS code
- Use the provided Microsoft style guide package
- Overwrite individual rules according to our own liking, and automatically persist these decisions in Vale configuration code

```[tasklist]
### Tasks
- [ ] Demonstrate vale to SIG Docs
- [x] Create a user guide to get started with vale, so that people can try it out easily
```

Further steps to be discussed

**Comment by marians** [comment]
## How to start using Vale

1. Install it. On macOS, you can use `brew install vale`.

2. Create a configuration file `~/.vale.ini`. As long as the repositories don't have their own configuration, you will have to create your own one. Use this content:

    ```ini
    Packages = Microsoft

    [formats]

    [*]
    MinAlertLevel = suggestion
    BasedOnStyles = Vale, Microsoft
    ```

3. Execute `vale sync` to download the Microsoft package.

4. Check a file, e. g. one in the `giantswarm/docs` repository like this:

        vale src/content/vintage/support/installation-name/index.md

    As an output, you should see a list of errors, warnings, and suggestions.

5. For VS Code, install the `vale-vscode` extension. With a docs page opened, you should now see underlined terms. Hover them to get details. Also the **Problems** panel lists all errors, warnings, and suggestions. You should see more or less the same info here as in step 4.

**Comment by marians** [comment]
I'm workig on an initial setup for the docs repo. There are more than 10K errors and warnings. So I'd like to exclude the `vintage` folder from all linting, but don't know yet how this would work. I placed a [question in the discussion board](https://github.com/errata-ai/vale/discussions/811).

**Comment by mproffitt** [comment]
closed as complete
