### ISSUE TITLE
Remove `webhook-exporter`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3407]
## Task

Remove the `webhook-exporter` component and the `Webhook Health` dashboard.

## Links

- [weebhook-exporter](https://github.com/giantswarm/webhook-exporter).

**Comment by teemow** [comment]
@alex-dabija do you know which team should work on this issue?

**Comment by fiunchinho** [comment]
@alex-dabija do you know if this is deployed anywhere at the moment? I don't see it as part of any app collection.

**Comment by fiunchinho** [comment]
I archived the repository.

**Comment by fiunchinho** [comment]
https://github.com/giantswarm/dashboards/pull/586

**Comment by fiunchinho** [comment]
Dashboard is removed from the dashboards repo, and the exporter repo has been archived. I think we can close this one. Feel free to reopen @alex-dabija if you think the component is deployed anywhere and needs to be removed, but I can't find it.
