### ISSUE TITLE
Align NetworkPolicies in CAPZ

### ISSUE THREAD

**Issue by mcharriere** [giantswarm/roadmap#3415]
Coming from https://github.com/giantswarm/roadmap/issues/3261

CAPZ is the only provider left using the defaultPolicies from `cilium-app` being quite permissive.

There is a PR open with the change, but currently the merges are blocked due the cluster chart refactor.

I'm creating this ticket to keep track and finalize the change when possible.

https://github.com/giantswarm/cluster-azure/pull/251

**Comment by kopiczko** [comment]
The PR is merged and changes released in 0.10.0
