### ISSUE TITLE
Disaster Recovery Game Day one-pager for prospects

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#3417]
The disaster recovery game-day we ran recently was a success. We should definitely come up with a one-pager on how we can do it together with prospects and current customers.

**Comment by tomcarron** [comment]
https://docs.google.com/spreadsheets/d/1lvX4efht6G9qYf764QNxXPFCGDlVffvT_QiJvymRx10/edit?usp=sharing - based off the format of other one pagers

**Comment by othylmann** [comment]
@LolloneS please do a final polish run and then give it to marat.

**Comment by LolloneS** [comment]
@morotki not urgent - can you make this a one-pager in the style of the others we have? :) https://docs.google.com/spreadsheets/d/1lvX4efht6G9qYf764QNxXPFCGDlVffvT_QiJvymRx10/edit?usp=sharing

**Comment by othylmann** [comment]
Please check here how far we are so we can start selling. @brinker211

**Comment by brinker211** [comment]
I don't have access here, maybe an admin can. @morotki do you have access? If someone does I can review so we can either close or finish this if we want to offer it to customers.

**Comment by morotki** [comment]
@brinker211 I can't access this either...

**Comment by brinker211** [comment]
No one could access the old page made by Lorenzo so I've created a new one pager first rough draft. Meeting with Pau on Wednesday to review the draft and edit the tools and some use-cases we have done for adidas and then I will ping you this week Marat. 

Potentially it is a good idea that we also provide a sample game-day as part of the one-pager.

**Comment by brinker211** [comment]
Changes are made from meeting with Pau and the draft is [finished](https://docs.google.com/spreadsheets/d/17asFwVcnFMOy1F2N1Of7qfYipBX-ZV8w0jD_OTk_0YI/edit?gid=353835957#gid=353835957). 

@morotki let me know if you have any questions or have any issues accessing.

**Comment by morotki** [comment]
@brinker211 how's this one? I had to add the "Introduction" part to even out the content, maybe we can replace it with something else? Otherwise let me know what you think.

![Image](https://github.com/user-attachments/assets/a6302a47-ce95-4046-844f-fd84565489d2)

**Comment by brinker211** [comment]
Looks great! Thanks a lot Marat. cc @foschubert if any changes from your side or @othylmann for any price adjustments. Closing for now though and can be reopened if there are changes requested.

**Comment by morotki** [comment]
Here's the PDF:

[gs-disaster-recovery-handout.pdf](https://github.com/user-attachments/files/17457694/gs-disaster-recovery-handout.pdf)
