### ISSUE TITLE
Add static routes with unit in capvcd/flatcar

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3423]
At the moment, if a node reboots, the routes aren't installed as it happens in kubeadm.

It should be a unit in ignition.

https://gigantic.slack.com/archives/C02EVLE9W/p1714374192860579

**Comment by vxav** [comment]
https://github.com/giantswarm/cluster-cloud-director/pull/293

**Comment by gawertm** [comment]
we need to finish this before 1st of June (frozen period for panamax)

**Comment by vxav** [comment]
Currently waiting for Oasis investigation on the issue where the metadata fails to be set on the VM. `production` was upgraded fine though.

**Comment by vxav** [comment]
Disabling teleport fixes the issue. My assumption is that we are at the limit of the default maximum metadata size supported by VCD and adding the teleport contents take us over that limit. 

`leopard/production` didn't have that issue and the only difference is that it has less NICs/routes than `staging` and `testing`.

We made a request for Oasis to increase the default limit but we'll have to wait until the end of the frozen period.
In the meantime, teleport is disabled in `staging` and `testing`.

**Comment by vxav** [comment]
Closing this as it's unrelated to the metadata issue
