### ISSUE TITLE
Downgrade VPA in Vintage aws v20.1.0 

### ISSUE THREAD

**Issue by weseven** [giantswarm/roadmap#3437]
As for CAPI https://github.com/giantswarm/default-apps-aws/pull/461, on Vintage v20.1.0 we need to downgrade VPA to version v5.1.0 and VPA CRD to version 3.0.0 since the newer version have a bug that causes the updater pod to crash.

Upstream issue: https://github.com/kubernetes/autoscaler/issues/6763

Related issue for turtles: https://github.com/giantswarm/roadmap/issues/3421

**Comment by whites11** [comment]
app is downgraded successfully on all 20.1.0 WCs out there
