### ISSUE TITLE
Add deny-all policies to CAPZ

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#3441]
We noticed that deny-all policies exist in other providers but not in CAPZ. We need to add them to CAPZ too.

**Comment by gawertm** [comment]
@weatherhog is it something you want to take care of in Cabbage?
or should we/phoenix try to add it?

cc @T-Kukawka

**Comment by weatherhog** [comment]
@gawertm we are taking care of this in this issue https://github.com/giantswarm/roadmap/issues/3415

**Comment by gawertm** [comment]
ok thanks closing this
