### ISSUE TITLE
Adapt mc-bootstrap to the removal of default apps

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3444]
### Motivation
Part of https://github.com/giantswarm/roadmap/issues/3419

After the removal of `default-apps-aws` we need to update our tooling to handle that.

### Todo

- [ ] Test that cluster creation and upgrade work with the new flow.

### Outcome 
- `mc-bootstrap` is fully migrated to not reference default apps

**Comment by weseven** [comment]
Merged https://github.com/giantswarm/mc-bootstrap/pull/891
