### ISSUE TITLE
Create a custom tekton metrics exporter

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3449]
Seems like we can't access a lot of the tekton data that we need for metrics and alerting so let's think about implementing our own custom tekton metrics exporter. Example use-case: https://github.com/giantswarm/giantswarm/issues/29854

**Comment by AverageMarcus** [comment]
We might be able to use this: https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md

**Comment by AverageMarcus** [comment]
We now have the following available on `cicdprod`:

```
kube_customresource_pending_taskrun_info{cluster_id="cicdprod"}
kube_customresource_failed_taskrun_info{cluster_id="cicdprod"}
```

[Source](https://github.com/giantswarm/workload-clusters-fleet/blob/main/management-clusters/gazelle/organizations/team-tinkerers/workload-clusters/cicdprod/apps/kube-state-metrics/configmap.yaml)
[Example Grafana](https://grafana.gazelle.awsprod.gigantic.io/explore?schemaVersion=1&panes=%7B%22i9z%22:%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_customresource_pending_taskrun_info%7Bcluster_id%3D%5C%22cicdprod%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D,%7B%22refId%22:%22B%22,%22expr%22:%22kube_customresource_failed_taskrun_info%7Bcluster_id%3D%5C%22cicdprod%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-5m%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)

---

We have the following available on stable-testing MCs:

```
kube_customresource_release{name=~".*-t..*"}
kube_customresource_organization{name=~"t-.*"}
```

[Source](https://github.com/giantswarm/giantswarm-management-clusters/blob/main/management-clusters/grizzly/extras/custom-metrics/configmap.yaml) (`grizzly`)
[Example Grafana](https://grafana.grizzly.gaws.gigantic.io/explore?schemaVersion=1&panes=%7B%22c1q%22:%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_customresource_release%7Bname%3D~%5C%22.%2A-t..%2A%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22expr%22:%22kube_customresource_organization%7Bname%3D~%5C%22t-.%2A%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)
