### ISSUE TITLE
Add aditional checks for node roll checking during upgrade tests

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3451]
In cluster-test-suites related to the test added in this [PR](https://github.com/giantswarm/cluster-test-suites/pull/266/files#diff-d44c49b80fbfd0bc23ade81d5241b084ec053c461b600198059f952f5f42a2eaR132) . We could add some checks to see what changed so we can just skip the rolling update test. An example where it can be skipped is app version changes.

Slack thread: https://gigantic.slack.com/archives/C04KA9DBMB2/p1715853467155939?thread_ts=1715765100.692829&cid=C04KA9DBMB2

**Comment by weseven** [comment]
Merged https://github.com/giantswarm/cluster-test-suites/pull/422 to skip the test if the generation of the controlplane resource did not change after applying the new version.
This should cover all cases where there isn't an effective change on the control plane config that the capi controllers need to reconcile, and thus skip the rolling update test when node will not be rolled.
