### ISSUE TITLE
Teleport RBAC

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3455]

**Comment by stone-z** [comment]
We can't remember what this is

**Comment by stone-z** [comment]
@gawertm do you remember what this was about?

**Comment by gawertm** [comment]
this was about introducing different roles with different viewing permissions e.g. of audit logs and session recordings. It came basically from the fact that with Teleport session recording, we have recordings of what a GS employee exactly types. After clarifying with team-team we only restricted the permissions for everyone to see only their own logs/recordings. so we can close this one IMO
