### ISSUE TITLE
Evaluate generating values schema based on values.yaml using `helm-schema`

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3459]
The goal is to find out how https://github.com/dadav/helm-schema can help us improve our workflow to maintain full-fledged values schema for apps.

## Questions

- How does helm-schema deal with an existing schema file?
  - Answer: it will overwrite it.
- How much work is it to add annotations to values.yaml?
  - The work on [hello-world-app](https://github.com/giantswarm/hello-world-app/blob/helm-schema-annotations/helm/hello-world/values.yaml) took me about 2 hours.
  - The file was 133 lines before and 614 lines afterwards
  - GitHub copilot helped a great deal.
- How well does this work with very nested values?
  - It works, but it gets a bit harder. IDE support for keeping context is useful.
- How well do helm-schema comments work alongside helm-docs comments?
  - They can coexist.
- Can we use references to avoid repetition?
  - Yes, we can do things like `$ref: https://schema.giantswarm.io/labelvalue/v0.0.1` to reference an external schema.
  - I haven't tried internal references yet.
- Can we define an object schema, even if the default is empty?
  - Yes

## Observations

- Output specifies draft `http://json-schema.org/draft-07/schema`.
- Github codepilot speeds up the annotations
- Normalizing with schemalint works! (Example: `schemalint normalize helm/hello-world/values.schema.json -o helm/hello-world/values.schema.json --force`)
- helm-docs commenting (`-- Description goes here...`) is not directly compatible with helm-schema. However it seems as if helm-schema understands the helm-docs comment format. So in the end, it is compatible and no duplication is required. Needs testing.
- helm-schema adds `additionalProperties: false` to the schema on all objects, including root level. This is problematic, as it will prevent the injection of arbitrary values. helm-schema provides the `-k` (`--skip-auto-generation`) flag to change this behaviour.

## Conclusions

- We can use `schemadocs` instead of helm-docs and derive our Markdown documentation from the schema.
- Running `helm-schema` should be mandatory part of CI checks.
  - Ideally, this would create annotations at the right place of values.yaml.
- Idea: we could make `helm-values-gen` also output the schema annotations, which would allow a full round-trip.

## Further research

- How does helm handle schema using draft `http://json-schema.org/draft-07/schema` ?
- How does helm handle schema using `$ref` with references to internal definitions, and also to external schema?

**Comment by marians** [comment]
A PR updating our hello-world-app values YAML can be found here:

https://github.com/giantswarm/hello-world-app/pull/153/files

**Comment by marians** [comment]
Just learned that Gerald introduced helm-schema to the Cilium project. You can see the result in https://github.com/cilium/cilium/blob/v1.16.0-pre.2/install/kubernetes/cilium/values.yaml

**Comment by marians** [comment]
Created some slides: https://docs.google.com/presentation/d/1ukH9t3pv9qu7Cu_9DG4RQz1ow5AZFWBi31kXVAxfmp4/edit

**Comment by piontec** [comment]
Done, we found our tools.
