### ISSUE TITLE
Migrate app platform components from operatorkit to kubebuilder

### ISSUE THREAD

**Issue by rossf7** [giantswarm/roadmap#346]
## Summary: 

In SIG Operator we've recently discussed migrating our operators and other components from [operatotkit](https://github.com/giantswarm/operatorkit) to [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder).

See https://github.com/giantswarm/giantswarm/discussions/16755

## User value 

As a user of the GIant Swarm app platform if I'm familiar with kubebuilder I can more easily contribute to the components. This is unlikely with operatorkit since its only used by Giant Swarm. 

## Business value: 

As a Platform Engineer if I"m familiar with kubebuilder I can work on app platform components without having to learn operatorkit. I can also more easily switch between Cluster API controllers and app platform components since they use kubebuilder.

## Components:

- [ ] app-admission-controller
- [ ] app-exporter
- [ ] app-operator
- [ ] chart-operator
- [ ] cluster-apps-operator

**Comment by rossf7** [comment]
@cokiengchiara Here is the roadmap issue PTAL.

When we start on this I think migrating app-admission-controller first makes sense because https://github.com/giantswarm/management-cluster-admission already uses kubebuilder and its smaller than the operators.

**Comment by LolloneS** [comment]
@weatherhog with us slowly converging on the Flux ecosystem, does it make sense to keep this open?

**Comment by weatherhog** [comment]
@LolloneS, yes. 

chart-operator will get replaced by flux but for example app-operator still will be used and therefor a migration from operatorkit to kubebuilder still makes sense.

**Comment by weatherhog** [comment]
@giantswarm/team-honeybadger does a migration still makes sense? Can we create a list of components that need to be migrated?

**Comment by weatherhog** [comment]
@JosephSalisbury does it make sense to put some priority on this and taking this to sig-product? To finally get all operators migrated and removing the technical debt?

**Comment by JosephSalisbury** [comment]
yeah, i'll add it to the agenda - if we agree on priority, we can make a list and dispatch issues to teams

**Comment by JosephSalisbury** [comment]
- open a github issue for each operator we need to migrate (i.e: won't die within 12 months), make POs aware that they have a risk
- work out a migration path (how to avoid a big-bang change)

ping @JosephSalisbury

**Comment by JosephSalisbury** [comment]
Closing here, taking https://github.com/giantswarm/roadmap/issues/3722 as the more high-level tracking issue
