### ISSUE TITLE
Investigate how mc-bootstrap would deal with the new releases flow

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3475]
Since we're planning to proceed with the changes from our [release RFC](https://github.com/giantswarm/rfc/pull/96/), let's sure mc-bootstrap would be able to handle them without causing much issues.

**Comment by weseven** [comment]
Initial implementation here: https://github.com/giantswarm/mc-bootstrap/pull/926

Tested with release aws-25.0.0-alpha.3

**Comment by weseven** [comment]
Merged https://github.com/giantswarm/mc-bootstrap/pull/926

Supports aws (capa) v25 :tada:

**Comment by weseven** [comment]
Reopening it, need to add renovate integration + work to support other providers releases

**Comment by weseven** [comment]
Draft PR using tags from the releases repo, currently testing: https://github.com/giantswarm/mc-bootstrap/pull/937

**Comment by weseven** [comment]
Merged in https://github.com/giantswarm/mc-bootstrap/pull/937
