### ISSUE TITLE
Adapt cluster-test-suite to the new way of providing the release version for cluster-aws

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3476]
Part of https://github.com/giantswarm/roadmap/issues/3473.

As part of the [new releases flow](https://github.com/giantswarm/rfc/pull/96) we'll now have to provide a release version to the cluster app instead of the chart version. Let's adapt our tooling to that.

* `cluster-standup-teardown` needs to handle creation and deletion of a Release CR that will be used by the test cluster
* The version of the Cluster App needs to be specified on the release components ([example](https://github.com/giantswarm/releases/pull/1262/files#diff-5c23a106452cbe3e5c4d537846f0f6c2e19c7e9ed664770a7aac94bb513822d3R93))
* The Releases SDK will include the CRD structs and some helper functions to get the latest Release CR for a given provider (this will be handled by Turtles)

**Comment by AverageMarcus** [comment]
Completed changes for existing test pipelines.
