### ISSUE TITLE
Assign relevant shared alerts to Turtles

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3479]
Atlas are currently introducing some improvements to the alert rules repository like assigning alerts to just one team etc. Currently there is a `shared` folder that includes the alerts that didn't have the boundary so clear, do some of those belong to our team? 

Acceptance criteria:
- [ ] Review shared alerts in [here](https://github.com/giantswarm/prometheus-rules/tree/main/helm/prometheus-rules/templates/shared/alerting-rules) and evaluate which ones should be owned by us.
- [ ] Move the list from above to our team folder.

**Comment by QuentinBisson** [comment]
@yulianedyalkova if you have the time, could you do the same with dashboards? It seems like a lot of them defaults to phoenix for some reason

**Comment by yulianedyalkova** [comment]
For the alerts at least, it seems that this is mostly caused by the shared oncall between Turtles and Phoenix. We had a chat that we might need a better way of splitting the teams into two and only merge on rotation level.

Dashboards shouldn't be affected by that though (I think) so maybe makes more sense for Phoenix to have a look?

**Comment by QuentinBisson** [comment]
I'm currently working on a PR to move the turtles alert to turtles but still page the cluster provider team https://github.com/giantswarm/prometheus-rules/pull/1219 so you could move the alerts in the correct folder :)
