### ISSUE TITLE
WC e2e tests for China

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3482]
After successful CAPA China implementation we need to ensure the repeatability of the WC creation with any new developments happening in `cluster-aws` repository. For this purpose we have to set up a pipeline to test the WC clusters in e2e tests for CAPA China

## Acceptance
- [x] WC e2e CAPA China pipeline is configured and running for `cluster-aws` related PRs

## Dependency 
- [x] https://github.com/giantswarm/roadmap/issues/3480

**Comment by calvix** [comment]
apps that ignore container registry values and do not use aliyun registry

this value si provided by app catalog

-       image: gsoci.azurecr.io/giantswarm/cert-manager-cainjector:v1.14.2
-       image: gsoci.azurecr.io/giantswarm/cert-manager-webhook:v1.14.2
-       image: gsoci.azurecr.io/giantswarm/grafana-agent:v0.37.2
-       image: gsoci.azurecr.io/giantswarm/configmap-reload:v0.8.0
-       image: gsoci.azurecr.io/giantswarm/grafana-agent:v0.37.2
-       image: gsoci.azurecr.io/giantswarm/configmap-reload:v0.8.0
-       image: gsoci.azurecr.io/giantswarm/grafana-agent:v0.37.2
-       image: gsoci.azurecr.io/giantswarm/kube-state-metrics:v2.10.1
-       image: gsoci.azurecr.io/giantswarm/prometheus-operator:v0.71.2
-       image: gsoci.azurecr.io/giantswarm/prometheus:v2.47.1
-       image: gsoci.azurecr.io/giantswarm/prometheus-config-reloader:v0.71.2
-       image: gsoci.azurecr.io/giantswarm/prometheus:v2.47.1
-       image: gsoci.azurecr.io/giantswarm/prometheus-config-reloader:v0.71.2
-       image: gsoci.azurecr.io/giantswarm/promtail:2.9.3
-       image: gsoci.azurecr.io/giantswarm/teleport-distroless:15.1.7
-       image: gsoci.azurecr.io/giantswarm/vpa-admission-controller:1.1.2
-       image: gsoci.azurecr.io/giantswarm/vpa-recommender:1.1.2
-       image: gsoci.azurecr.io/giantswarm/vpa-updater:1.1.2

**Comment by alex-dabija** [comment]
I created the issues for teams to update the apps.

**Comment by calvix** [comment]
e2e tests are done, the Images have separate issues so no need to keep this open.
