### ISSUE TITLE
Talk to grafana enterprise

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#349]
Towards https://github.com/giantswarm/roadmap/issues/182 Give customers access to Grafana

We are interested in white-labeling and analytics.

### TODO

- [ ] talk to Grafana and find out how much would it cost to switch to enterprise version

**Comment by JosephSalisbury** [comment]
had another think about this. it'd essentially be grafana enterprise (and possibly reselling it for our customers) - they won't sell us 'just' whitelabelling. 

so, too much just for a fancier experience. possibly something to try later if we develop a better relationship w/ grafana
