### ISSUE TITLE
Use flag for CAPI Image Builder to clear ephemeral keys 

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#3511]
**Is your feature request related to a problem? Please describe.**

As a user using Azure Defender there is an alert for keys present on the control plane nodes in CAPZ. 

**Describe the solution you'd like**

Test or try a flag such as `ssh_clear_authorized_keys` to clear the ephemeral keys for CAPI image builder. 

**Describe alternatives you've considered**

**Additional context**

This is low priority.

**Comment by ericgraf** [comment]
All new images built will have this setting enabled. 
All previously generated images do not have this but they can be requested if really required.
