### ISSUE TITLE
Team Atlas should be requested on releases for PMO

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#352]
atlas should be requested on releases for PMO: https://github.com/giantswarm/prometheus-meta-operator/pull/618

- [ ] automatically add Atlas as a reviewer for every change in PMO

**Comment by mig4** [comment]
Checked out the options and they are:

- only [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners) can be used to automatically add someone to requested reviewers
- additionally branch protection rules can be setup to **require** a review from Code Owners on release PRs (i.e. branches matching `master#release#`)
- `CODEOWNERS` doesn't have a way to target specific branches, only paths/patterns
- we could use the fact that release branches always modify `pkg/project/project.go` but almost no other PR does, to limit the automatically requested reviews to only release PRs

**Comment by mig4** [comment]
[Discussed this in #team-atlas](https://gigantic.slack.com/archives/C01176DKNP4/p1624442863213200) and the conclusion was that we don't necessarily want everyone in the team to be pinged in all PRs in PMO (individuals can opt-in by subscribing to the repo anyway), so we'll try to limit this to only **release** PRs, but we do want to require that the **release** PRs to be approved by someone in the team before they can be merged.

**Comment by mig4** [comment]
OK so giantswarm/prometheus-meta-operator#642 implements the first part of this - automatically requesting Team Atlas for reviews of **release** PRs.

**Comment by mig4** [comment]
The second part - **requiring** approval from a member of team Atlas on **release** PRs is now configured via repository settings:

1. go to _Settings > Branches_
2. use branch name pattern: `master`
3. enable _Require pull request reviews before merging_
4. enable _Require review from Code Owners_

![pmo new-branch-protection-rule 2021-06-23--14-17-41](https://user-images.githubusercontent.com/42101611/123106337-774d3780-d430-11eb-8210-a0bc071d2976.png)

**Comment by mig4** [comment]
Confirmed that this is working as expected.

Opening a non-release PR - no reviewers automatically subscribed:

![pmo open-pr non-release 2021-06-23--15-42-08](https://user-images.githubusercontent.com/42101611/123128282-ecc20380-d442-11eb-8564-c839bf4de88b.png)

And a PR with a new release - team-atlas requested automatically and approval required:

![pmo release-pr 2021-06-23--15-56-27](https://user-images.githubusercontent.com/42101611/123128578-2abf2780-d443-11eb-94ca-546588078777.png)
