### ISSUE TITLE
Rollout Alloy for metrics to all Installations

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3523]
### Motivation

We want to unify all of our agents to use the new opentelemetry agent from grafanalabs: alloy. We already collected some initial expierence in #3522 - now we need to roll it out to all installations of the observability platform.

### Todo

*   [ ] Roll out Alloy for metrics in all installations of the observability plattform
    *   [x] Announce the upcoming change in the #news-ops channel before doing the migration https://gigantic.slack.com/archives/C90BZMUJ1/p1729161492240359

### Outcome

*   We rolled out alloy for metrics and unified our use of agents.

**Comment by TheoBrigitte** [comment]
Alloy for metrics requires CAPA v29.2.0 https://github.com/giantswarm/roadmap/issues/3522#issuecomment-2376816026

MC migration is being tacked here https://github.com/giantswarm/giantswarm/issues/31760
