### ISSUE TITLE
migrate organization-operator to kubebuilder

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3530]

**Comment by ssyno** [comment]
- Everything is mostly ready in [#414](https://github.com/giantswarm/organization-operator/pull/414) merging remaining.
- Discussion around the releasing strategy has to be done, as its a `default-app` and the changes are major so issues my come up on existing installations.

**Comment by tuladhar** [comment]
- Disable flux in golem and upgrade org operator.
- Organization CRD  is managed outside app.

**Comment by ssyno** [comment]
> * Disable flux in golem and upgrade org operator with help from Phoenix
> 
>     * Organization CRD  is managed outside app.

Tested and everything works after some minor fixes

**Comment by ssyno** [comment]
Released in v2.0.0, looks good, only CRD has to be updated

**Comment by tuladhar** [comment]
Standup updates:
- PR in api-extensions is failing, and @ssyno will get some assistance from Phoenix who owns api-extensions on how we can safely update the organization CRDs.
