### ISSUE TITLE
Release version is not read from all possible cluster app config values

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3533]
## Bug

From @AverageMarcus:

> Hey friends, I have an issue with the latest (2) update of cluster-aws that bumped the cluster sub-chart. When I merged in the change I'm now getting the following error with the Kustomization on gazelle:
>
>     App/org-team-tinkerers/cicddev apply failed: admission webhook "apps.app-admission-controller.giantswarm.io" denied the request: cluster app user config not set error: Cluster App 'org-team-tinkerers/cicddev does not have the user config
>
> Any hints on what I need to do? There's nothing in the changelog for cluster-aws

Here cluster app config is set under App `.spec.config` like this:

```
spec:
  catalog: cluster
  config:
    configMap:
      name: ${cluster_name}-config
      namespace: org-${organization}
```

And app-admission-controller mutation code was reading only `.spec.userConfig`.

## Fix

Expected behaviour in Giant Swarm app platform is that App's config can come from multiple places, so both `.spec.config` and `.spec.userConfig` are correct, as well as `.spec.extraConfigs`.

The fix here is to properly read and merge all App's configs, and only then read release version. @mcharriere has described [here](https://github.com/giantswarm/app-admission-controller/pull/490#discussion_r1630727966) how we can achieve this.

**Comment by AverageMarcus** [comment]
@nprokopic Has this actually been released yet? The Kustomization is still broken on `gazelle` 😕
