### ISSUE TITLE
opensource mcli

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3535]
let's have a look if there is anything confidential inside, if not let's opensource it with our regular process and licensing, etc.

**Comment by anvddriesch** [comment]
I checked the official process for open sourcing but it's a bit vague here. Waiting for input to confirm it's okay.

**Comment by anvddriesch** [comment]
https://gigantic.slack.com/archives/C02FL4EAADD/p1719865576143799?thread_ts=1719825256.422719&cid=C02FL4EAADD
