### ISSUE TITLE
Add flatcar 3815.2.2 to capi-flatcar-stable-1.2x.x-gen2-gs

### ISSUE THREAD

**Issue by njuettner** [giantswarm/roadmap#3543]
For CAPZ v25.0.0 release preparation I'd like to align with CAPA release v25.0.0 using the same flatcar version `3815.2.2`.

Currently we only have `3815.2.0` available for Kubernetes v1.25.x,v1.26.x and v1.27.x.

Could you please add additionally `3815.2.2` to the latest VM images? 

- `capi-flatcar-stable-1.25.16-gen2-gs`
- `capi-flatcar-stable-1.26.15-gen2-gs`
- `capi-flatcar-stable-1.27.14-gen2-gs`

Thank you ❤

**Comment by ericgraf** [comment]
@njuettner  I hope it's okay I used the latest version for flatcar and latest patch release for k8s `1.27.x` instead.

`3815.2.4` is the latest flatcar that is currently available on azure but very soon `3815.2.5` will be available.

This is the list of new image names:
- flatcar-stable-3815.2.4-kube-v1.27.15-gs
- flatcar-stable-3815.2.4-kube-v1.26.15-gs
- flatcar-stable-3815.2.4-kube-v1.25.16-gs

Links to the builds: 
- https://tekton.ci.giantswarm.io/#/namespaces/capi-image-builder/pipelineruns/manual-capz-build-capi-image-kgvm9
- https://tekton.ci.giantswarm.io/#/namespaces/capi-image-builder/pipelineruns/manual-capz-build-capi-image-r7nsk
- https://tekton.ci.giantswarm.io/#/namespaces/capi-image-builder/pipelineruns/manual-capz-build-capi-image-qg6nl

**Comment by ericgraf** [comment]
All image builds passed. Should be good now. 👍
