### ISSUE TITLE
Speed up cluster creation time by increasing app-operator reconcile interval during cluster creation phase.

### ISSUE THREAD

**Issue by ericgraf** [giantswarm/roadmap#3548]
During initial cluster creation due to cross-dependency race conditons and other factors , clusters can be stuck waiting for the reconcillation loop of app-operator during the intial cluster creation. 

This has the affect of increasing the cluster creation time by multiples of the reconciliation interval. 

To speed up cluster creation time we should have a very low reconcillation interval during this initial creation phase.
After the cluster has been created and all the apps deployed we can then increase the reconcillation interval.

Related slack thread: https://gigantic.slack.com/archives/C02GDJJ68Q1/p1718903774692299

Initial issue that led to this issue: https://github.com/giantswarm/giantswarm/issues/30882

**Comment by uvegla** [comment]
@ericgraf I tested this version: https://github.com/giantswarm/cluster-apps-operator/pull/529 (At revision: `0375e22fded72173f52b99ba9dc03282ae688236`). It works fine, my observations tho:

- I did not observe significant time difference in the cluster being ready, roughly 12 mins
- Maybe more apps got the chance to get deployed tho by that time
- Not all apps get deployed tho by the time the cluster CR reports ready based on the current conditions
  - For example Kyverno was still not ready by the time the resync period was set abck to 5 mins, so it took another 10-15 mins for the remaining other apps get deployed.

**Comment by uvegla** [comment]
I will ask in #area-kaas. This was a simple and potentially useful, but I could not verify the impact / saw no improvement in cluster creation times.

**Comment by uvegla** [comment]
Ran a few more tests on the mentioned PR, and also decreased `chart-operator` sync period to constant 1 min. Its not a good idea to make that dynamic cos of the ungraceful shutdown of the operator leaving Helm releases hanging. Not of the tests indicated any speed up in cluster creation. Closing this for now.
