### ISSUE TITLE
Adapt CNCF tests to new releases flow

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3557]
Acceptance criteria:
- [x] We can run CNCF tests on PRs on releases repo

**Comment by AverageMarcus** [comment]
Done with:
* https://github.com/giantswarm/cluster-standup-teardown/pull/65
* https://github.com/giantswarm/tekton-resources/pull/376
* https://github.com/giantswarm/releases/pull/1313
