### ISSUE TITLE
Early Feedback Loops

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3565]
### Motivation
In order to raise our confidence in the stability of our observability platform and be sure that our ongoing work and releases won't negatively impact our observability platform operations we need to create extensive tests giving us early feedback loops. These tests should also be as convenient as possible thus automated. Tinkerers already have created some test setup we can reuse here. The goal is an Automated Tests Suite of the Observability Platform.

```[tasklist]
### Test Suite Stories
- [ ] https://github.com/giantswarm/roadmap/issues/2008
- [ ] https://github.com/giantswarm/roadmap/issues/3578
- [ ] https://github.com/giantswarm/roadmap/issues/3612
- [ ] https://github.com/giantswarm/roadmap/issues/3611
- [ ] https://github.com/giantswarm/roadmap/issues/3614
- [ ] https://github.com/giantswarm/roadmap/issues/3615
- [ ] https://github.com/giantswarm/roadmap/issues/3616
- [ ] https://github.com/giantswarm/roadmap/issues/3617
```

```[tasklist]
### Other Improvements
- [ ] https://github.com/giantswarm/giantswarm/issues/22235
- [ ] https://github.com/giantswarm/giantswarm/issues/26737
- [ ] https://github.com/giantswarm/giantswarm/issues/29756
```

### Outcome
- We have a extensive test suite for our observability platform giving us automatic early feedback for the impact of our ongoing work

**Comment by QuentinBisson** [comment]
@Rotfuks 1 Epic done
