### ISSUE TITLE
releases App is in 'already-exists' status after creating a new MC with mc-bootstrap

### ISSUE THREAD

**Issue by fiunchinho** [giantswarm/roadmap#3570]
When creating a new MC with `mc-bootstrap`, the `releases-capa` app is in `already-exists` status

```
reason: 'object already exists: (rendered manifests contain a resource that already
      exists. Unable to continue with install: Release "aws-25.0.0" in namespace ""
      exists and cannot be imported into the current release: invalid ownership metadata;
      label validation error: missing key "app.kubernetes.io/managed-by": must be
      set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name":
      must be set to "releases-capa"; annotation validation error: missing key "meta.helm.sh/release-namespace":
      must be set to "giantswarm")'
    status: already-exists
```

The `Release` CR is manually applied here https://github.com/giantswarm/mc-bootstrap/blob/main/scripts/install-releases-crds.sh#L22, and I guess the app is coming from the `cluster` chart , so they conflict.

I'm not sure if this step is necessary https://github.com/giantswarm/mc-bootstrap/blob/main/Makefile.custom.mk#L494 , because the CRD is managed by `flux` and the `Release` CR will be created by the `releases-capa` app.

**Comment by weseven** [comment]
Fixed with https://github.com/giantswarm/mc-bootstrap/pull/969: now the releases chart for the providers (releases-capa, releases-azure) is installed through helm during bootstrap, so flux should be able to adopt it once it comes up in a later stage and no longer complain about the missing annotations and labels.
