### ISSUE TITLE
Include default requests/limits in all loki + promtail + grafana-agent deployments

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#358]
The loki-app + promtail-app should include reasonable default limits/requests

**Comment by hervenicol** [comment]
When we review requests/limits on Loki, could be good to have this issue in mind also: https://github.com/giantswarm/roadmap/issues/358

**Comment by TheoBrigitte** [comment]
As we recently did a lot of tuning in Loki, do we still need this @hervenicol ?

**Comment by hervenicol** [comment]
For Loki we should be good, buts I didn't do anything on Promtail.

**Comment by Rotfuks** [comment]
Let's check if this is done yet, or if we still have some todos here to set request/limits

**Comment by QuentinBisson** [comment]
Loki is fine:
```
k get sts -n loki loki-backend -oyaml | yq '.spec.template.spec.containers.[].resources'
limits:
  cpu: 100m
  memory: 100Mi
requests:
  cpu: 50m
  memory: 50Mi
limits:
  memory: 3Gi
requests:
  cpu: 200m
  memory: 1Gi
> k get sts -n loki loki-write -oyaml | yq '.spec.template.spec.containers.[].resources'
limits:
  memory: 8Gi
requests:
  cpu: "1"
  memory: 4Gi
> k get deploy -n loki loki-read -oyaml | yq '.spec.template.spec.containers.[].resources'
limits:
  memory: 3Gi
requests:
  cpu: 200m
  memory: 1Gi
```

Promtail is okay:

```
k get ds -n kube-system promtail -oyaml | yq '.spec.template.spec.containers.[].resources'
limits:
  cpu: "1"
  memory: 256Mi
requests:
  cpu: 25m
  memory: 128Mi
```

Grafana-agent/Alloy are not:

```
k get deploy -n kube-system grafana-agent -oyaml | yq '.spec.template.spec.containers.[].resources'
{}
requests:
  cpu: 1m
  memory: 5Mi
> 
> k get deploy -n monitoring alloy-rules -oyaml | yq '.spec.template.spec.containers.[].resources'
{}
requests:
  cpu: 1m
  memory: 5Mi
```

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas I would really like some thoughts on how to proceed here. Should we set some random resource usage, use vpa, use hpa?

The issue is when we want to play with clustering (which we don't know) but it supports hpas

**Comment by hervenicol** [comment]
Why is it important to take the right decision regarding VPA or HPA right now?

I guess it's because it requires a new olly-bundle release, whereas we can change the deployment type for grafana-agent (or alloy-logs or logging agent) directly from additional values on the MC via logging-operator.
Right?

Otherwise, if both configs (xPA and deployment type) can be setup from the same place, we should start with VPA and we will move to HPA later when we have the need.

**Comment by QuentinBisson** [comment]
Upstream PR https://github.com/grafana/alloy/pull/1305.
I'll let this wait a bit and see how it goes by the end of the week :)

**Comment by QuentinBisson** [comment]
Initial VPA PR: https://github.com/giantswarm/alloy-app/pull/44
Followed with a Fix: https://github.com/giantswarm/alloy-app/pull/46
Configured in prometheus-rules for now: https://github.com/giantswarm/prometheus-rules/pull/1339

**Comment by QuentinBisson** [comment]
Alloy now has proper limits and we can enable VPA on memory if needed
