### ISSUE TITLE
Network architecture for CAPA/CAPV hybrid MC

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3587]
some resources:
https://rutgerblom.com/2020/01/07/site-to-site-vpn-between-nsx-t-tier-1-and-aws-vpc/
https://intranet.giantswarm.io/docs/product/providers/capz/multi-provider/

Our MC is on CAPA. It is capable of provisioning CAPV and CAPA workload clusters.|
CAPA MC is private with proxy
CAPA MC is able to access the vSphere API.
CAPA MC is able to access all CAPV WCs.
CAPV WCs are able to access endpoints (k8s API and ingresses) of the MC.

```[tasklist]
### Tasks
- [x] IONOS - GS VPN
- [x] IONOS - AWS
- [x] AWS - GS VPN
- [x] AWS - IONOS
- [x] extend noproxy
```

**Comment by anvddriesch** [comment]
We set up the VPNs on IONOS and AWS sides modeled based on our Azure environment.
Thanks to Simon and Xavier we finally got it working and Vsphere nodes are now reachable from goat mc nodes.

**Comment by glitchcrab** [comment]
i don't want to lose this - we need to add `vcenter-rhr3c72bx1.ionoscloud.tools` to goat's NO_PROXY vars
