### ISSUE TITLE
Add efk warning for unbalanced storage

### ISSUE THREAD

**Issue by webwurst** [giantswarm/roadmap#359]
From discussion on Slack: https://gigantic.slack.com/archives/CE92C4BST/p1624274654150100

- [ ] Add to our efk documentation short hint for config settings `cluster.routing.allocation.disk.watermark.*`
- [ ] Add alert/warning for us when storage is unbalanced. Only during business hours. So that we can reach out and discuss with customer.
- [ ] Also add to our ops-recipes

**Comment by snizhana-dynnyk** [comment]
no plans to do this now, we will open if this comes back
