### ISSUE TITLE
Alloy monitoring

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3590]
When one component from alloy fails, we should get an alert.

Related incident: we had an incident where alloy-rules failed to load rules on all installations, and got no alert (https://gigantic.slack.com/archives/C01176DKNP4/p1720628254293449)

Probably Alloy mixins provide all we need:
- servicemonitors to retrieve data
- dashboards for easy investigation
- sensible alerts

**Comment by QuentinBisson** [comment]
For mixins, please, do it the same way as the mimir and loki mixins and do not import them by hand

**Comment by QuentinBisson** [comment]
@TheoBrigitte I think you added mixins already right? We are probably only missing sensible alerts?

**Comment by QuentinBisson** [comment]
Current status:

- Added alerts for alloy components health and alloy logging pipeline https://github.com/giantswarm/prometheus-rules/pull/1410
- Added ops-recipes for alloy logging pipeline https://github.com/giantswarm/giantswarm/pull/32008

Missing:
- Opsrecipes for the alloy components health alerts
- Alloy monitoring pipeline alerts and ops-recipes.

@giantswarm/team-atlas do we want to add alerts related to alloy clustering for this? Is it too soon?

**Comment by QuentinBisson** [comment]
Blocked waiting for reviews

**Comment by QuentinBisson** [comment]
This is done, will need adjustsments
