### ISSUE TITLE
Create an SLO dashboard in installation Grafana 

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#361]
Towards **https://github.com/giantswarm/roadmap/issues/182 Give customers access to Grafana**

### TODO

- [ ] Copy the Service Level dashboard to installation grafana

### Questions

- [ ] How can we keep dashboards in cortex and installation grafana in sync

**Comment by JosephSalisbury** [comment]
note: needs refinement because we want to check out what the user story here is better - what do customers want to get out of an SLO dashboard? is it more of a status page?

**Comment by weatherhog** [comment]
no benefits at the moment
