### ISSUE TITLE
Grafana testing

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3612]
### Motivation

In order to raise our confidence in the stability of our observability platform and be sure that our ongoing work and releases won't negatively impact our observability platform operations we need to create extensive tests giving us early feedback loops.

### Todo

*   Investigate some good initial test cases to give us feedback on the stability of a release on mimir on CI. This can be:
    *   Validate Helm chart templating
    *   Deploy chart on Kind (single instance)
*   Implement those CI test cases

### Outcome

*   We have early, automatic feedback about the impact of a release of the Grafana app before releasing.

**Comment by QuantumEnigmaa** [comment]
:heavy_check_mark: Helm chart basic testing done

**Comment by QuentinBisson** [comment]
Is there any more tests we need to add?

**Comment by QuantumEnigmaa** [comment]
As I said last week, I think we had decided to stay at this stage for chart testing for grafana. We didn't came up with any good scenario for e2e testing.
I'm thus closing this issue, let's reopen it if we finally think of interesting e2e tests scenario
