### ISSUE TITLE
Alloy testing

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3613]

**Comment by QuentinBisson** [comment]
Added helm chart testing here https://github.com/giantswarm/alloy-app/pull/50
Waiting for some help for the basic e2e tests https://github.com/giantswarm/alloy-app/pull/48

**Comment by QuentinBisson** [comment]
e2e test is currently blocked by https://github.com/giantswarm/giantswarm/issues/31594, pushing back to sprint backlog

**Comment by QuentinBisson** [comment]
We have helm chart testing in place
