### ISSUE TITLE
Alertmanager testing

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3614]
### Motivation

In order to raise our confidence in the stability of our observability platform and be sure that our ongoing work and releases won't negatively impact our observability platform operations we need to create extensive tests giving us early feedback loops.

### Todo

*   Investigate some good initial test cases to give us feedback on the stability of a release on mimir on CI. This can be:
    *   Validate Helm chart templating
    *   Deploy chart on Kind (single instance)
    *   Implement those CI test cases
*   Investigate some good initial test case to give us feedback for updates on the Alertmanager and PMO 
    *   Most issues we had in the past was because of the PMO dependency - investigate how we can test both together 
    *   Implement if you find a possible solution that is not a week+ of effort :) 

### Outcome

*   We have early, automatic feedback about the impact of a release of the Alertmanager before releasing.

**Comment by QuantumEnigmaa** [comment]
I agree, it's also the reason why I didn't pick this one up until now

**Comment by QuentinBisson** [comment]
We agreed that this does not make sense for us, it brings no value as the alertmanager config is managed by the operator itself and this would require e2e tests
