### ISSUE TITLE
SLOth testing

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3617]
### Motivation

In order to raise our confidence in the stability of our observability platform and be sure that our ongoing work and releases won't negatively impact our observability platform operations we need to create extensive tests giving us early feedback loops.

### Todo

- Investigate some good initial test cases to give us feedback on the stability of a release on mimir on CI. This can be:
  - Validate Helm chart templating
  - Deploy chart on Kind (single instance)
  - Implement those CI test cases
- Investigate some good initial e2e test for the sloth app
  - We can test if it successfully transforms (as expected) a sloth crd into a prometheus rule

### Outcome

*   We have early, automatic feedback about the impact of a release of the SLOth app before releasing.

**Comment by QuentinBisson** [comment]
Needs this first https://github.com/giantswarm/apptestctl/pull/472
