### ISSUE TITLE
Add a VPA resource to cert-exporter-deployment

### ISSUE THREAD

**Issue by weseven** [giantswarm/roadmap#3625]
### Motivation
In `deu01`, and possibly in other larger clusters, the cert-exporter-deployment was constantly crashing due to being killed for OOM.
Memory resources/limits are set at 50MB, and this might not be enough in large clusters.

Ref.: https://gigantic.slack.com/archives/C05LSRCF35Z/p1723015723593929?thread_ts=1723013990.327869&cid=C05LSRCF35Z

### TODO
Add a VPA resource  for the cert-exporter-deployment so in case of OOM events the resources are scaled accordingly.

- [ ] Test the outcome. 
- [ ] Update relevant docs.

### Outcome

The deployment no longer crashes on certain clusters (e.g., `anteater/deu01`).

**Comment by dalvarezquiroga** [comment]
https://gigantic.slack.com/archives/C6L8J93N0/p1723535720717099?thread_ts=1723445839.043219&cid=C6L8J93N0

int02 | cert-exporter-deployment-856bc6d478-9h6jq                              0/1    CrashLoopBackOff  2 (27s ago)  3m12s
 ceu02 | cert-exporter-deployment-648476cf87-n88rn                           0/1    CrashLoopBackOff  187 (69s ago)  20h
 deu01 | cert-exporter-deployment-5cdcd585bd-99vgm                           0/1    OOMKilled  1 (60s ago)    113s
 seu01 | cert-exporter-deployment-7664648486-l7kn5                          0/1    CrashLoopBackOff  81 (3m35s ago)   8h
 peu01 | cert-exporter-deployment-69b444d645-654fr                          0/1    CrashLoopBackOff  9752 (2m41s ago)  46d

**Comment by weseven** [comment]
Fixed in [cert-exporter v2.9.2](https://github.com/giantswarm/cert-exporter/releases/tag/v2.9.2)

**Comment by weseven** [comment]
The updated cert-exporter will be included in the next capa release
