### ISSUE TITLE
Discuss shorter chain for cluster wildcard DNS record to avoid lookup problems

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3631]
https://gigantic.slack.com/archives/C062HB29BDG/p1723213834230449?thread_ts=1723200262.910159&cid=C062HB29BDG

`CNAME *.old -> CNAME *.new -> A ingress.new` (potentially problematic for some DNS clients and applications) vs. `CNAME *.old -> A ingress.new` (regular indirection with 1 CNAME, should always work)

**Comment by AndiDog** [comment]
We discussed that it's fine to remove the middle `CNAME`. No concerns were raised. We'll adjust the migration CLI.

**Comment by T-Kukawka** [comment]
closing, done, migrated with Adidas for test as well
