### ISSUE TITLE
Make sure mimir and cache are in the same AZ

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3639]
### Motivation
Joe found out, that we have some unnecessary cost center when mimir components are comunicating to cache in another availability zone. The communication for this can be found [in this slack thread](https://gigantic.slack.com/archives/C01176DKNP4/p1722949049215019). Good thing is, @QuantumEnigmaa already fixed it. But we now need to make sure this change is documented.

### Todo

- [x] Document the setup and confiugration that is needed when having the cache in the same AZ as mimir

### Outcome
- We know in the future how to make sure there is no resource cost with communication of mimir with caches in other AZs

**Comment by QuantumEnigmaa** [comment]
Mimir architecture doc updated.
