### ISSUE TITLE
CAPA: Release v29.1.0

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3647]
Acceptance criteria:
- [x] Wait for https://github.com/giantswarm/giantswarm/issues/31529 to be finished as that's the main driver of this release
- [x] Include all changes included by teams in the request file
- [x] Ensure we can create and upgrade Giant Swarm clusters

**Comment by weseven** [comment]
PR: https://github.com/giantswarm/releases/pull/1348 (currently still missing latest node-exporter)

**Comment by weseven** [comment]
29.1.0 is merged, this can be closed/completed.
