### ISSUE TITLE
Clusters dashboard doesn't include CAPI clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3650]
## Problem

The [Clusters dashboard](https://giantswarm.grafana.net/d/6Jt4OwqZk/clusters) doesn't include CAPI clusters.

## Task

Update the Clusters dashboard to include CAPI clusters information for all providers. Every panel needs to be checked for correctness.

## Links

- [Clusters dashboard](https://giantswarm.grafana.net/d/6Jt4OwqZk/clusters);
- [Related issue in team Atlas](https://github.com/giantswarm/roadmap/issues/3634);
- [Slack thread](https://gigantic.slack.com/archives/C01F7T2MNRL/p1723712374434809).

**Comment by njuettner** [comment]
Releases version can be integrated into metrics via `cluster-api-monitoring` for now.

**Comment by AverageMarcus** [comment]
Right, I've updated the [Clusters dashboard](https://giantswarm.grafana.net/d/6Jt4OwqZk/clusters?from=now-7d&to=now) so it all supports CAPI now. I've also added a few more panels for the other provides we have (CAPV and CAPVCD) and tweaked some of the existing panels to better display the data. 
One thing I've not been able to do that I wanted to is ordering of the entries in the panels. This looks like it might be a limitation of Grafana but I've reached out to Atlas to see if they can suggest anything.

@alex-dabija would you mind taking a look at the dashboard and let me know if you think there's anything more that is needed or anything that doesn't look how you'd expect.

**Comment by alex-dabija** [comment]
> @alex-dabija would you mind taking a look at the dashboard and let me know if you think there's anything more that is needed or anything that doesn't look how you'd expect.

The dashboard looks ok now. Thanks!

**Comment by AverageMarcus** [comment]
Great! 😁  Thanks for confirming!
