### ISSUE TITLE
Deprecation management for CAPI releases

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3651]
Acceptance criteria:
- [x] Release state is being shown when listing releases (active, deprecated)
- [ ] New clusters cannot be created from deprecated releases or at least we have a warning that it is strongly discouraged / out of support

**Comment by Gacko** [comment]
So... bringing the release state to surface was quite simple. But warning the user about them using a deprecated release might be a bit tricky:

We have the `app-admission-controller` and in there we are already looking up the release details when a cluster app manifest is getting created or updated. We basically check if the release manifest exists and then take the cluster app version from the release manifest to put it into the newly created cluster app resource.

This is a mutating webhook and there also is a validating webhook, but both of them are returning either "all good, go on" or "Stop! That's wrong! You shall not pass!".

What I wanna tell: The whole `app-admission-controller` currently has no possibility to return a warning, so a way to still create the app but also tell the user they're doing something not so cool.

Question is: Should I take the burden and implement it (cannot tell how long it takes, but might bloat the issue a bit) or should we just skip the second part of this issue?

What we definitely should not do is just rejecting the app as this could break stuff. So I'd first print a warning and maybe somewhen in the future start rejecting apps with deprecated releases.
