### ISSUE TITLE
`kubectl gs get clusters` should not show deleting cluster as Ready

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3655]
[Source](https://gigantic.slack.com/archives/CLPMFRVU6/p1724692320330489)

```
$ kubectl get cl -n=org-theo
NAME              CLUSTERCLASS   PHASE      AGE     VERSION
selfservicelogs                  Deleting   4h14m

$ kubectl gs get cluster -n=org-theo
NAME              AGE     CONDITION   RELEASE   SERVICE PRIORITY   ORGANIZATION   DESCRIPTION
selfservicelogs   4h14m   READY       29.1.0    highest            theo           selfservicelogs test cluster
```

This is a CAPA cluster.

**Comment by weatherhog** [comment]
@alex-dabija can you help us with which team would this be best to send to? We think it is best to give this to a KaaS Team as they have the best knowledge around Cluster Conditions

**Comment by alex-dabija** [comment]
> @alex-dabija can you help us with which team would this be best to send to? We think it is best to give this to a KaaS Team as they have the best knowledge around Cluster Conditions

Yes, I can help you. I moved the issue to team Turtles because this should the same for all CAPI clusters.
