### ISSUE TITLE
`mimir-querier` needs a lot of resources

### ISSUE THREAD

**Issue by QuantumEnigmaa** [giantswarm/roadmap#3687]
Lately, we've been continuously paged by the `MimirHPAReachedMaxReplicas` alert, mostly for the `querier` component. Currently this component has a `maxReplicas` number of 10 with its hpa and a default resources requests of 100m for CPU and 500Mi for the memory. 

According to the following per-pod resources usage, CPU is fine but memory could use a little increase : 
![Image](https://github.com/user-attachments/assets/abf3e935-b4fe-4744-95ae-731b9497168c)

From our current understanding, the querier needs to scale whenever someone uses its installation's grafana, which would mean that it should scale down during the night. Because of this, I would advocate to increase the `maxReplicas` to **15** and slightly increase its default memory requests in the `shared`-configs repo (i;e something like 650~700Mi) to avoid having to increase the former forever.

**Comment by hervenicol** [comment]
Looks like the RAM usage is quite stable over time, as you can see over 10 days here:
![Image](https://github.com/user-attachments/assets/bfe06e52-e8b4-4e00-bf69-d87d13d1dd93)

I've increased its RAM reservations to 1GB on a few installations:
* alba
* alligator
* armadillo
* avocet
* wallaby

Let's see in a while if it stabilises at 512MB or if it grows up to 1GB.

We could also do a bit of profiling (with `pprof`) to try to understand what uses this RAM.

**Comment by QuentinBisson** [comment]
Increased to 1GN on enigma as well

**Comment by hervenicol** [comment]
Looking at a querier pod that was up for a while and uses 400MB RAM:
```
$ k top pods -n mimir mimir-querier-7b74d4f446-x4nb8
NAME                             CPU(cores)   MEMORY(bytes)   
mimir-querier-7b74d4f446-x4nb8   3m           411Mi           
$ k get pods -n mimir mimir-querier-7b74d4f446-x4nb8
NAME                             READY   STATUS    RESTARTS   AGE
mimir-querier-7b74d4f446-x4nb8   1/1     Running   0          11d
$ 
```

Its heap flamegraph shows only 33MB usage!
![Image](https://github.com/user-attachments/assets/71ee2049-29be-4f22-b49e-8e67cfa155ee)

**Comment by hervenicol** [comment]
Setting GOGC to 10 on this install (golem) to see the impact on memory and CPU usage.

**Comment by hervenicol** [comment]
The usage is currently much lower.

Before:
```
$ k top pods -n mimir | grep querier
mimir-querier-7b74d4f446-6lgkt              4m           292Mi
mimir-querier-7b74d4f446-9wdmm              94m          714Mi
mimir-querier-7b74d4f446-kczgm              4m           321Mi
mimir-querier-7b74d4f446-lwhhc              4m           757Mi
mimir-querier-7b74d4f446-n4z86              3m           352Mi
mimir-querier-7b74d4f446-nmp2t              12m          336Mi
mimir-querier-7b74d4f446-tzdrc              4m           301Mi
mimir-querier-7b74d4f446-x4nb8              3m           411Mi
```
After:
```
$ k top pods -n mimir | grep querier
mimir-querier-6b775bfccb-cwrbb              6m           52Mi
mimir-querier-6b775bfccb-g744g              7m           62Mi
mimir-querier-6b775bfccb-kw44r              9m           46Mi
mimir-querier-6b775bfccb-mz7rr              13m          43Mi
mimir-querier-6b775bfccb-n8vt8              6m           53Mi
mimir-querier-6b775bfccb-rrtcq              4m           56Mi
mimir-querier-6b775bfccb-wcr2n              7m           53Mi
mimir-querier-6b775bfccb-wmhsc              8m           52Mi
```

But this is an usual behaviour when the pods restart. Let's wait for a while until RAM usage stabilizes.

**Comment by hervenicol** [comment]
We can see that RAM usage decreased.
![Image](https://github.com/user-attachments/assets/156046ab-4297-4afe-bd57-1c37bbe02db0)

Number of replicas seems to decrease
![Image](https://github.com/user-attachments/assets/0b9642a1-f779-45cb-889e-2e59d7d197c5)

BTW it's currently set to 5 replicas, but HPA is at 30% RAM, so it seems to me it should decrease even more.


Concerning CPU:
We can see the expected CPU increase when decreasing GOGC.
It increased from peaks at 0.08 to peaks at 0.2 CPU.
![Image](https://github.com/user-attachments/assets/f2bc88b5-126e-41b7-8dd3-493da9581fd2)

**Comment by hervenicol** [comment]
Same experiment with loki-read path:
RAM usage nearly cut by 2, saving 80MB RAM per Loki read pod.
![Image](https://github.com/user-attachments/assets/8f945678-94f7-45b1-83fe-7a4075fb7bf9)

and CPU usage increases, but stays minimal.
![Image](https://github.com/user-attachments/assets/ec1bd60b-9cbb-413d-bc5e-ba34112fd446)

**Comment by hervenicol** [comment]
The RAM savings look great, and the resulting increase in CPU usage are really low.
So let's set GOGC=10 by default for both mimir-querier and loki-read pods.
Done here: https://github.com/giantswarm/shared-configs/pull/174

**Comment by QuentinBisson** [comment]
@hervenicol do we need to keep this opened? We can reopen if needed right?

**Comment by hervenicol** [comment]
Right, it looks better, and it also allowed us to reduce the resource requests for loki-read pods 👍
