### ISSUE TITLE
Release v27 fails to pull from private ECR registries

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3702]
It seems that there is an issue on our release v27 with pulling images from private ECR registries as the `ecr-credential-provider` binary is not being provided as part of the image anymore, more details in [slack thread](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1727340405942279). This is currently blocking customers to upgrade to v27 and above.

Acceptance criteria:

- [x] Include `ecr-credential-provider` binary as part of our images
- [x] Draft releases for CAPA for all versions >v26.
- [ ] Can we implement a regression test to ensure we won't hit a similar issue again?

**Comment by AverageMarcus** [comment]
Binary included in images following the release of this PR: https://github.com/giantswarm/capi-image-builder/pull/452 ([v1.20.0](https://github.com/giantswarm/capi-image-builder/releases/tag/v1.20.0))

**Comment by paurosello** [comment]
We can create a private registry in the same account and region we create the E2E clusters, upload a test image and then add a test where a Deployment is created pulling from the private registry.
