### ISSUE TITLE
CAPV: Kubernetes v29

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3710]
Acceptance criteria:

- [ ] Ensure we can create Giant Swarm clusters with Kubernetes v29
- [ ] Ensure upgrades from GS release v28 to v29 work
- [ ] Release GS v29.0.0 for CAPV

**Comment by Gacko** [comment]
We decided to still have the latest patch versions of the components (Flatcar, Kubernetes, OS Tooling) included. Apart from that we are consistent with other v29.x.x releases.

Tests passed, so the PR already got merged. Now we only need to announce it.
