### ISSUE TITLE
Loki and Mimir need an alert for pods stuck in a `pending` state

### ISSUE THREAD

**Issue by QuantumEnigmaa** [giantswarm/roadmap#3719]
We noticed that both loki and mimir pods could enter a `pending` state and get stuck in it indefinitely without us being alerted for that. Hence the need for creating an alert with such a purpose.

**Comment by hervenicol** [comment]
I should it would be managed by the `DeploymentNotSatisfiedAtlas` alert 🤔 
https://github.com/giantswarm/prometheus-rules/blob/main/helm/prometheus-rules/templates/platform/atlas/alerting-rules/deployment.management-cluster.rules.yml#L20

**Comment by QuentinBisson** [comment]
Maybe it's related to test installations then?

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa do you remember where we discussed this?

**Comment by hervenicol** [comment]
Coming from here: https://gigantic.slack.com/archives/C01176DKNP4/p1728541264647909
Was failing on `glippy` which is stable-testing. So, should have paged during business-hours.

**Comment by hervenicol** [comment]
The current alert monitors deployments, not statefulsets.
I'll craft an alert for statefulsets.

**Comment by QuentinBisson** [comment]
Anything left here @hervenicol ?

**Comment by hervenicol** [comment]
Fixing currently broken installations, but that means the alert actually works and is useful 🤣
