### ISSUE TITLE
Check the resource usage of Alloy

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3724]
### Motivation 
We've seen some weird numbers when checking the golem installation on which alloy is already rolled out. It seems that alloy is using significantly more resources than promtail and prometheus-agent combined. This is not good. 

### Todo

- [ ] Check what the resource usage of alloy is compared to prometheus-agent and promtail on the installations
- [ ] investigate if we can improve that resource usage in any way
  - One such way can be https://github.com/giantswarm/giantswarm/issues/31559 - is this enough? 

### Outcome
- We are confident that Alloy is not using significantly more resources than prometheus-agent and promtail

**Comment by hervenicol** [comment]
## Actual RAM usage for Alloy on `golem`

### Queries

RAM: `sum(container_memory_working_set_bytes{cluster_id="golem", namespace="kube-system", pod=~"alloy-metrics.*", container!="", image!=""}) by (pod)`

Series: `sum(prometheus_remote_write_wal_storage_active_series{pod=~"alloy-metrics-.*"}) by (pod)`

### Numbers

Currently:
* 2 alloy-metrics pods
* scraping 350k and 400k metrics
* RAM usage is 9GB and 3.5GB

=> the pod scraping 400k metrics is the one using less RAM. But it's also the youngest one.

### Pprof

Extracting data:
- port-forward with `ks port-forward alloy-metrics-0 12345`
- get heap data with `curl localhost:12345/debug/pprof/heap -o heap.pprof`

Visualizing data with https://play.grafana.org/a/grafana-pyroscope-app/ad-hoc

* alloy-metrics-0:
   * alloc_objects:
![Image](https://github.com/user-attachments/assets/ecca7b24-4303-4a6d-b5ea-5dabd55866f2)
   * alloc_space:
![Image](https://github.com/user-attachments/assets/be3452f3-b026-4c0f-8bc6-0a560e60388d)
   * used_objects:
   * used_space:

* alloy-metrics-1:
   * alloc_objects:
![Image](https://github.com/user-attachments/assets/8a8d7701-d43c-47ae-852c-d9b1a92c0c54)
   * alloc_space:
![Image](https://github.com/user-attachments/assets/ca446d7e-125f-4ff4-9e99-5dd0773f2578)
   * used_objects:
   * used_space:

**Comment by TheoBrigitte** [comment]
Our Alloy app is already up-to-date

- upstream 1.4.2 is in v0.6.1 https://github.com/giantswarm/observability-bundle/pull/248/files which is in o11y-bundle v1.7.0
- upstreadm 1.4.3 is in main https://github.com/giantswarm/alloy-app/pull/68

**Comment by Rotfuks** [comment]
So what's the outcome here then? 
> Currently:
>2 alloy-metrics pods
>scraping 350k and 400k metrics
>RAM usage is 9GB and 3.5GB

This sounds closer to what prometheus-agents had - so we improved here and closed the gap?

**Comment by TheoBrigitte** [comment]
Looking into `Alloy` memory usage over the last 2 days I see no anomaly by this I mean that the memory usage stays relatively flat and changes according to the number of timeseries observed. Memory usage ~ 12GiB

![Image](https://github.com/user-attachments/assets/03a4b95c-e010-4c3b-af9d-7376df8beae4)
[source](https://grafana.golem.gaws.gigantic.io/explore?schemaVersion=1&panes=%7B%22kyc%22:%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22container_memory_working_set_bytes%7Bcluster_id%3D%5C%22golem%5C%22,%20namespace%3D%5C%22kube-system%5C%22,%20pod%3D~%5C%22alloy-metrics.%2A%5C%22,%20container%3D%5C%22alloy%5C%22,%20image%21%3D%5C%22%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22A%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22go_memstats_heap_released_bytes%7Bcluster_id%3D%5C%22golem%5C%22,%20namespace%3D%5C%22kube-system%5C%22,%20pod%3D~%5C%22alloy-metrics.%2A%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22B%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22container_memory_usage_bytes%7Bcluster_id%3D%5C%22golem%5C%22,%20namespace%3D%5C%22kube-system%5C%22,%20pod%3D~%5C%22alloy-metrics.%2A%5C%22,%20container%21%3D%5C%22%5C%22,%20image%21%3D%5C%22%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22D%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22expr%22:%22process_resident_memory_bytes%7Bpod%3D%5C%22alloy-metrics-0%5C%22,%20container%3D%5C%22alloy%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D,%7B%22refId%22:%22E%22,%22expr%22:%22container_memory_rss%7Bpod%3D%5C%22alloy-metrics-0%5C%22,%20container%3D%5C%22alloy%5C%22,%20image%21%3D%5C%22%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%221729375200000%22,%22to%22:%221729634399000%22%7D%7D,%2280l%22:%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22prometheus_remote_write_wal_storage_active_series%7Bpod%3D%5C%22alloy-metrics-0%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22A%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22prometheus_remote_write_wal_storage_deleted_series%7Bpod%3D%5C%22alloy-metrics-0%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22B%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%221729375200000%22,%22to%22:%221729634399000%22%7D%7D%7D&orgId=1)

We putting this into perspective with `Prometheus agent` with a similiar amount of time series it seems we are consuming far less memory in this case. Memory usage ~5GiB

![Image](https://github.com/user-attachments/assets/42c89459-896e-4f09-bcb9-39bc9fea7799)
[source](https://grafana.gazelle.awsprod.gigantic.io/explore?schemaVersion=1&panes=%7B%22kyc%22:%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22container_memory_working_set_bytes%7Bcluster_id%3D%5C%22gazelle%5C%22,%20namespace%3D%5C%22kube-system%5C%22,%20pod%3D~%5C%22prometheus-prometheus-agent.%2A%5C%22,%20container%3D%5C%22prometheus%5C%22,%20image%21%3D%5C%22%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22A%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:true%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22go_memstats_heap_released_bytes%7Bcluster_id%3D%5C%22gazelle%5C%22,%20namespace%3D%5C%22kube-system%5C%22,%20pod%3D~%5C%22prometheus-prometheus-agent.%2A%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22B%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22expr%22:%22container_memory_usage_bytes%7Bcluster_id%3D%5C%22gazelle%5C%22,%20namespace%3D%5C%22kube-system%5C%22,%20pod%3D~%5C%22alloy-metrics.%2A%5C%22,%20container%21%3D%5C%22%5C%22,%20image%21%3D%5C%22%5C%22%7D%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22legendFormat%22:%22__auto%22,%22refId%22:%22D%22,%22step%22:10,%22interval%22:%22%22,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22C%22,%22expr%22:%22process_resident_memory_bytes%7Bcluster_id%3D%5C%22gazelle%5C%22,pod%3D%5C%22prometheus-prometheus-agent-0%5C%22,%20container%3D%5C%22prometheus%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D,%7B%22refId%22:%22E%22,%22expr%22:%22container_memory_rss%7Bcluster_id%3D%5C%22gazelle%5C%22,pod%3D%5C%22prometheus-prometheus-agent-0%5C%22,%20container%3D%5C%22prometheus%5C%22,%20image%21%3D%5C%22%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%221729375200000%22,%22to%22:%221729634399000%22%7D%7D,%2280l%22:%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22refId%22:%22C%22,%22expr%22:%22prometheus_agent_active_series%7Bcluster_id%3D%5C%22gazelle%5C%22,pod%3D%5C%22prometheus-prometheus-agent-0%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false%7D,%7B%22refId%22:%22D%22,%22expr%22:%22prometheus_agent_deleted_series%7Bcluster_id%3D%5C%22gazelle%5C%22,pod%3D%5C%22prometheus-prometheus-agent-0%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%221729375200000%22,%22to%22:%221729634399000%22%7D%7D%7D&orgId=1)

Note that this comparison might be inaccurate due the nature of the underlying data which might differ in terms of labels cardinality which plays a big part in the actual memory usage.

**Comment by TheoBrigitte** [comment]
I replaced Alloy with Prometheus agent on `golem` so we can collect data over next couple of days and compare data then. I am aiming at minimum 2 days of data and maximum 7 days.

**Comment by TheoBrigitte** [comment]
prometheus-agent do consume same amount of memory as alloy after few (5) days

Note that there are 3 prometheus agent pods consuming respectively 5, 4.8, and 1.2 GiB, so ~11GiB in total with 750k time series

![Image](https://github.com/user-attachments/assets/6ef668f3-4190-487f-a5d6-d542f843e879)

ramping up over 5 days

![Image](https://github.com/user-attachments/assets/2681fb39-ddd5-463f-b3ff-e9d300334f37)

**Comment by hervenicol** [comment]
I struggle with reading those graphs.
* There's lots of different RAM metrics
* there's metrics from agents running on the WCs

So I'll refer to your numbers:
> 3 prometheus agent pods consuming respectively 5, 4.8, and 1.2 GiB, so ~11GiB in total with 750k time series

With `alloy` I had these numbers (no graph either, sorry):
> 2 alloy-metrics pods
> scraping 350k and 400k metrics
> RAM usage is 9GB and 3.5GB

So,
* 750k series in both cases
* 12.5GB RAM over 2 pods for alloy / 11GB RAM over 3 pods for prometheus agent

That's a bit more RAM usage for Alloy (+10%), but I think we can accept that.

**Comment by QuentinBisson** [comment]
Yes I think that's something we can accept. Maybe we should find ways to reduce the difference in resource usage between the 2 pods (I think it's KSM and we should maybe shard) but those are good results :)

Is there anything else to do here? Maybe write those results down somewhere?

**Comment by TheoBrigitte** [comment]
There seems to be something wrong in the scaling for prometheus agent pods, as the number of observed timeseries and current shards do not match with what the operator is supposed to have configured

![Image](https://github.com/user-attachments/assets/09652d00-9ac7-4ed7-85cf-8f5747098442)
[source](https://grafana.golem.gaws.gigantic.io/explore?schemaVersion=1&panes=%7B%22pvs%22:%7B%22datasource%22:%22mimir%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%28max_over_time%28%28sum%28prometheus_remote_write_wal_storage_active_series%7Bcluster_id%3D%5C%22golem%5C%22,%20component_id%3D%5C%22prometheus.remote_write.default%5C%22,%20service%3D%5C%22alloy-metrics%5C%22%7D%29by%28pod%29%29%5B6h:1h%5D%29%29%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22alloy%20pods%20time-series%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22sum%28max_over_time%28%28sum%28prometheus_agent_active_series%7Bcluster_id%3D%5C%22golem%5C%22%7D%29by%28pod%29%29%5B6h:1h%5D%29%29%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22prometheus-agent%20pods%20time-series%22,%22hide%22:false%7D,%7B%22refId%22:%22C%22,%22expr%22:%22count%28count%28prometheus_agent_active_series%29by%28pod%29%29%20%2A%20100000%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22prometheus-agent%20pods%20count%22,%22interval%22:%22%22,%22format%22:%22time_series%22,%22hide%22:false%7D,%7B%22refId%22:%22D%22,%22expr%22:%22count%28count%28prometheus_remote_write_wal_storage_active_series%29by%28pod%29%29%2A100000%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22alloy%20pods%20count%22,%22hide%22:true%7D,%7B%22refId%22:%22E%22,%22expr%22:%22count%28kube_statefulset_replicas%7Bnamespace%3D%5C%22kube-system%5C%22,statefulset%3D~%5C%22prometheus-prometheus-agent.%2A%5C%22%7D%29%2A%20100000%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22mimir%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%221728470358342%22,%22to%22:%221728561371530%22%7D%7D%7D&orgId=1)

I added more unit test cases in the operator to ensure the number of shards computed by the operator is correct, https://github.com/giantswarm/observability-operator/pull/160

We'll leave this for now, and anyone in the future observing a similar difference is gladly welcomed to investigate further :)

**Comment by QuentinBisson** [comment]
We configured the sharding value in config at 500.000 timeseries and not 1.000.000 anymore. That could explain the différence you see

**Comment by QuentinBisson** [comment]
But as long as we're okay with thé résults we don't have a reason to keep this issue right?

**Comment by TheoBrigitte** [comment]
Having a lower threshold questions even more the results we are observing. But for now we are good here and we can close this.
