### ISSUE TITLE
Investigation: Switch to the Grafana UI to fully replace Alert Manager UI

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3745]
### Motivation
While the prometheus alert manager has a UI the mimir alert manager relies on grafana for a UI. We should investigate if there are some use cases covered by the prometheus alert manager UI but not by Grafana.

### Todo
- [ ] investigate what the prometheus alert manager ui can do and is used for 
- [ ] Investigate if those use cases can all be covered by the grafana alert ui

### Outcome
- We are confident that we are not loosing any functionality with that migration

**Comment by hervenicol** [comment]
Stuff I do with alertmanager and I have to learn with grafana:
- look for current silences
  - what are currently deployed silences?
  - what alerts do they match?
  - are current alerts silenced? by which silence?
- look for alert labels to create a silence

We can do all of these with grafana.
Actually, since we don't have the "alertmanager" link in the opsgenie alerts anymore, I now use grafana via the "explore" link.
But I can't help but feel a bit lost when doing it with grafana.
I guess it's just a matter of changing my habits.

**Comment by Rotfuks** [comment]
Would a recipe/documentation of those use cases and how you'd do them in grafana help?

**Comment by hervenicol** [comment]
We currently have no doc around that, and switching to grafana as the unified WebUI makes the experience more consistent.
I don't see much interest in writing a "how to use grafana" doc. This should be the upstream doc.

If we really want to write something around "how to manage alerts and silences in grafana" that could be some kind of demo or blog post.
But our CAPA installations already push for using grafana, and AFAIK nobody complained.

An announcement with a bit of communication should be enough when we remove classic alertmanager from CAPI installations.

**Comment by TheoBrigitte** [comment]
Quick comparison of Alertmanager vs Grafana UIs


| | |Alertmanage|Grafana|
|-|-|:-----------------:|:----------:|
Active alerts ||✅|✅| 
||Alert labels|✅|✅|
||Alert description|✅|✅| 
||Alert opsrecipe link|✅|❓|
||Is alert silenced indicator|✅|✅| 
||Silence alert|✅|✅| 
||See source|✅|❌| 
Silences ||✅|✅| 
||Silence labels|✅|✅|
||Silence fields|✅|✅|
||Silence affected alerts|✅|✅|
||remove silence|✅|✅|


I opened a issue for the broken `See source` link https://github.com/grafana/grafana/issues/96155

**Comment by QuentinBisson** [comment]
@TheoBrigitte I'm confused, where is the ops-recipe link in the old alertmanager?

If I check on alertmanager we only have this:
![Image](https://github.com/user-attachments/assets/88643d8c-f044-446b-9362-2ff577183baf)
But this is not a link right?

We have the same on grafana

**Comment by QuentinBisson** [comment]
The see source is related to the fact we're not using the mimir's alertmanager. We solved it in the notification template but this is currently redirecting to a Prometheus based query. This is not an issue with grafana

**Comment by QuentinBisson** [comment]
So I think we're done here :)

Maybe we should demo how to use the new alerting UI but we should be good :)

**Comment by TheoBrigitte** [comment]
You're right the ops-recipe is not a link in both cases. Maybe it should.
I'll see how the source link works once I have Mimir's alertmanager running.

**Comment by TheoBrigitte** [comment]
The investigation on use cases is done, I moved into the next story https://github.com/giantswarm/roadmap/issues/3746 to actually investigate the implementation.
