### ISSUE TITLE
Change the silence manager to work with the new alert manager

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3748]
### Motivation
We need to make sure that alerts managed through the mimir alertmanager can be silenced the same way as the alerts in the prometheus alerts manager. For this we need to potentially change something in the silence manager.

### Todo 

- [x] We want to load our silences into the giantswarm tenant, so we need to work on that.
- [x] There are some PRs open for this, we need to review them if that’s enough

### Outcome
- The silence manager works with the new mimir alert manager

**Comment by QuentinBisson** [comment]
PR https://github.com/giantswarm/silence-operator/pull/318/

**Comment by QuentinBisson** [comment]
Waiting for feedback on my pr
