### ISSUE TITLE
Collect Kubernetes Events with Alloy

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3750]
### Motivation
We currently still run Grafana-Agent to collect Kuberentes Events - which we can also do with Alloy

### Todo

- [x] Collect Kuberentes Events with Alloy

### Outcome
- We can get rid of Grafana Agent

**Comment by QuantumEnigmaa** [comment]
The `logging-operator` has been updated to be able to handle either `grafana-agent` or `alloy` for collecting events depending on the `observability-bundle` version. Therefore, starting from `observability-bundle` version 1.9.0, `alloy` will be used as the events logger as `alloy-events` app. 

This has been tested on a testing installation and released everywhere.
