### ISSUE TITLE
Bug: IDP demo GitHub action pipeline fails to push arm64 image

### ISSUE THREAD

**Issue by LutzLange** [giantswarm/roadmap#3755]
I've run into issues with the GitHub actions pipeline. 

We are currently trying to build arm64 arch images as well and the push of these images fails.

![Image](https://github.com/user-attachments/assets/02eee677-68c6-4d09-ac58-10033fb86d79)

![Image](https://github.com/user-attachments/assets/1e70b43b-dcf7-4427-af42-71ab54a0ea06)

The error message is:
error=docker images: failed to publish artifacts: failed to push ghcr.io/demotechinc/lutzdemo:0.1.0-arm64 after 0 tries: failed to push ghcr.io/demotechinc/lutzdemo:0.1.0-arm64: exit status 1: denied: permission_denied: write_package

It clearly can't push the image because of missing permissions.

**Comment by LutzLange** [comment]
I'm getting 404 errors when following the "Latest Revision applied" Links on the Details from the Component page in Backstage.  Are those related?

![Image](https://github.com/user-attachments/assets/69042802-927d-4dd9-b126-4fbc1b6e0297)

This is where the Link points to:
https://github.com/demotechinc/lutzdemo/releases/tag/v0.1.0

**Comment by piontec** [comment]
Closing, as everything workds now.
