### ISSUE TITLE
Bug: IDP Demo Service Component details - link to revision not working

### ISSUE THREAD

**Issue by LutzLange** [giantswarm/roadmap#3756]
I'm getting 404 errors when following the "revision last applied" Links on the Details from the Component page in Backstage.  Are those related?

![Image](https://github.com/user-attachments/assets/6f8dbcee-66c6-42a7-a375-ea9ce69b5b63)

This is where the Link points to:
https://github.com/demotechinc/lutzdemo/releases/tag/v0.1.0

The Link should read correctly: 
https://github.com/DemoTechInc/lutzdemo/releases/tag/0.1.0

Please fix the Capitalization issue.

**Comment by weatherhog** [comment]
solved in https://github.com/giantswarm/roadmap/issues/3755
