### ISSUE TITLE
Add command to run all AWS conformance tests from a release PR.

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#376]
Add command to run all AWS conformance tests from a release PR.

**Comment by alex-dabija** [comment]
Blocked until @paurosello comes back from vacation.

**Comment by whites11** [comment]
I guess we can do this already?

**Comment by T-Kukawka** [comment]
yeah  we should be able to do it at some point

**Comment by paurosello** [comment]
I don't even remember the main issue with this now :( but the PR should still be around

**Comment by T-Kukawka** [comment]
we are going to sounnoboy(WHATEVER)  so there is no need for this issue.
