### ISSUE TITLE
Update opsctl notify release for CAPV and CAPVCD

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3764]
Currently `opsctl notify release` is not implemented to deal with CAPV and CAPVCD clusters (as we didn't use releases there before).

For CAPV it returns an empty list:
```
opsctl notify release --file announcement.md --customers --provider vsphere --md-to-slack
```

For `cloud-director` it returns one customer.

**Comment by anvddriesch** [comment]
We decided to add an optional `additionalProviders` field in the installations repo which can contain a list of other providers than the primary `provider`.
We will also adjust `notify release` to respect this field.
