### ISSUE TITLE
Moving appcatalog values to management-clusters-fleet repo

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#377]
@kopiczko and @tomahawk28 had a conversation around moving all appcatalog values from installation to management-cluster-fleet repository. 

At the moment, we have to run `opsctl ensure catalogs` to set-up all necessary appcatalogs but this is unreliable to the unexpected deletion of configmap/secrets belonging to the appcatalog helm releases. 

If we use management-cluster-fleet as one of argoCD pipeline, there is no need to run `opsctl ensure catalogs` because argoCD will update appcatalogs whenever we have an update or it runs auto-heal when we accidentally delete one of appcatalog's resources.

Slack conversation: https://gigantic.slack.com/archives/C3C7ZQXC1/p1627051524092700

**Comment by cokiengchiara** [comment]
Not high priority yet, but @tomahawk28 will add a description.

**Comment by tomahawk28** [comment]
I found out each installation has many different configs between them (e.g. akita's AWS credentials), so it is not suitable to move all values to `management-cluster-fleet` repository at the moment.

We first need to generalize appcatalog's helm manifest by moving out all app-specific values to config repository.

**Comment by gianfranco-l** [comment]
@rossf7  is this still relevant? how we should proceed with this issue?

**Comment by rossf7** [comment]
@gianfranco-l It's still valid but its not high prio.

Once we replace Argo with Flux we could use it and move the configuration to the config repo.

**Comment by kubasobon** [comment]
There is already a ticket for creating catalogs via management-clusters-fleet: https://github.com/giantswarm/giantswarm/issues/18202

**Comment by kubasobon** [comment]
I'd like to close this ticket as a duplicate.

**Comment by gianfranco-l** [comment]
closed in favor of https://github.com/giantswarm/giantswarm/issues/18202
