### ISSUE TITLE
Investigate how we deal with breaking changes in cluster charts

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3778]
Currently we're planning to release a few breaking changes that we want to push into v30. But if we want to backport something into the old releases, we need to make sure we have a clear way of doing so without accidentally pulling in breaking changes into old releases.

Ideas:

- [ ] Support multiple branches per release so that we can easily backport features to them
- [ ] Make changes in-code that ensure that a feature get enabled only for specific Kubernetes releases
- [ ] What else (please explore other best practices)

Acceptance criteria:
- [ ] Evaluate different options and document clearly their downsides / risks / benefit before making a decision

**Comment by njuettner** [comment]
Added a doc for our conversation about this: https://docs.google.com/document/d/16cATtFuIOnIADcpPcjQMrMPe2sYPleV3xSxY53X-spc

**Comment by AverageMarcus** [comment]
None of the options feel great unfortunately 😞 

I'm having a hard time deciding on the least bad but I think I also agree with option 2 - mainly because it minimally effect the current way of doing things and can be relatively easily reverted if we later come up with a better solution.

**Comment by njuettner** [comment]
Ok going with option 2: "Feature Flagging" for now 👍🏻
