### ISSUE TITLE
Multi-Tenants Datasource

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3784]
### Motivation
We have the requirement that for some use cases it is important to have mutliple tenants in just one datasource added. Like an SRE team having access to the metrics of multiple teams. They should not be forced to switch organisations, or even datasources and thus context but have their tenants comparable in one datasource. 

### Todo 

- [ ] Make sure we can have multiple tenants added to a Grafana Organisation within 1 datasource

### Outcome
- We now have an easier way of adding multiple tenants into one organisation. This will allow for teams having components in multiple teams to get their data into their organisation - like a SRE Team.

**Comment by QuentinBisson** [comment]
Work is done and being finalized here https://github.com/giantswarm/observability-operator/pull/189

It was done in multiple steps to avoid breaking grafana configs
