### ISSUE TITLE
Add analytics-panel to all public dashboards

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#379]
Towards https://github.com/giantswarm/roadmap/issues/364

We need to add the analytics-panel to all the [public installation-level dashboards](https://github.com/giantswarm/dashboards/tree/master/helm/dashboards/dashboards), so we can get analytics data.

**Comment by JosephSalisbury** [comment]
[PRODUCT OWNER]
"It'd be great if we could avoid having to convert all 3 public dashboards to jsonnet as part of this story

[MICHAEL]
*enters stage left*
"We'll still need to specify the host to send data to - we might be able to use relative paths, which would be easiest, but if we have to specify the full host, jsonnet might be easier"

[PRODUCT OWNER]
"okay all i care about is the burn-down chart"
*stomps out stage right*

- let's keep talking about it once we know if relative paths work

**Comment by mig4** [comment]
So relative paths aren't working in current version. I submitted a PR to fix/add support for that here - https://github.com/MacroPower/macropower-analytics-panel/pull/23

**Comment by mig4** [comment]
We brainstormed with Theo about this and we realised jsonnet won't actually help here because the value we need to replace isn't known at built/CI time, but only at installation time. Conceptually we think this could be done in Helm, but we couldn't force it to render templates in external files. Also escaping templates in JSON is going to be a pain.

**Comment by mig4** [comment]
We chatted about this some more in refinement and the consensus was that it would be better for everyone's sanity if we didn't have to template the dashboard JSON files with Helm, so we'll try to go with my patch above first.
