### ISSUE TITLE
Change data dir of teleport

### ISSUE THREAD

**Issue by njuettner** [giantswarm/roadmap#3797]
We currently store the sessions on /var/lib/teleport, but maybe we should consider to change that
https://github.com/giantswarm/cluster/blob/7382a52e2861cc78548d3e98d4ab204eda696cc5/helm/cluster/files/etc/teleport.yaml#L3

I debuged an issue in `alba/seu01` where disk space is low on  a node.

Common storage for pods is under /var/lib/kubelet on CAPA but there we also store teleport sessions.

When running out of disk we might have an issue that we cannot login on that nodes anymore due to
```
Original Error: *trace.AccessDeniedError failed to execute command /var/lib/teleport/log/upload/streaming/default/multi error:  no space left on device
```

I think we should fix that ASAP

Slack Thread: https://gigantic.slack.com/archives/C02FL4EAADD/p1733322446643659

Solution:

- Gather insights how much data we store for teleport (/var/lib/teleport) 
- Changing it root directory to isolate this critical component from pod storage abuse, by default we have ~5G for `root` or we create a separate disk like `/var/lib/kubelet` if we need more space

**Comment by stone-z** [comment]
Merged, waiting for release
