### ISSUE TITLE
Check if customers have access to the analytics-panel-server metrics data

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#381]
Towards https://github.com/giantswarm/roadmap/issues/364

The `/metrics` endpoint for the analytics-server currently exposes personally identifiable information (via the `user_login` and `user_email` labels).

We need to check if customers have access to the `/metrics` endpoint of the backend server (as this would mean we are leaking personal information.

If customers do have access, we'll need an upstream PR to not send identifiable data. If customers don't have access, we can have Prometheus drop these labels.

Either way, let's talk as a team after finding out what the backend security is like.

**Comment by JosephSalisbury** [comment]
```
$ curl -Ss https://grafana.g8s.ghost.westeurope.azure.gigantic.io/grafana-analytics-panel-server/metrics | head -n 5
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
```

customers have access to the analytics panel metrics data, but that's because it doesn't require authentication currently

first step: we need to put this behind authentication

**Comment by mig4** [comment]
OK so putting this behind OAuth2-Proxy works, including sending data from the frontend.

I haven't tested this as a customer yet and I have a feeling that's not going to be as easy. Essentially I think it works now because I'm authenticated to both Grafana and the OAuth2-Proxy, but customers probably won't be. I need to do some more testing but first I need to figure out why I can't log in as a customer user.

**Comment by mig4** [comment]
OK got my login sorted, but I can't add a panel as a customer user so I'll switch over to #379 so I have some dashboards to test on.

**Comment by JosephSalisbury** [comment]
Looks like it doesn't work for customers w/ oauth proxy, we need to either:
- make oauth-proxy work for customers
- find another way to secure the endpoint

**Comment by mig4** [comment]
We chatted with Theo and decided it would be best to get this working with OAuth2 and specifically even better if it used dex as this would be the same mechanism/cookies/headers as Grafana itself which makes it easier to reason about, etc.

One idea is to use the same redirect mechanism, i.e. nginx-IC annotations `nginx.ingress.kubernetes.io/auth-(signin|url)` but with dex, the question is can dex be used that way.

**Comment by TheoBrigitte** [comment]
Managed to get authentication working for the analytics server by re-using Grafana authentication. Here is a proof from giantswarm and customer perspective respectively.

![Screenshot_2021-08-05_16-15-46](https://user-images.githubusercontent.com/6536819/128367262-920f0e78-fea4-4daa-a36c-81215ec05af1.png)

![Screenshot_2021-08-05_16-16-31](https://user-images.githubusercontent.com/6536819/128367248-091328eb-9685-438a-bfc0-7c7941067215.png)

**Comment by TheoBrigitte** [comment]
analytics-panel-server is now using grafana as auth mechanism. Meaning you only get access to analytics-panel-server if you have access to Grafana. Otherwise you get greeted with a http 500 error, 401 would be preferable but hey it works.
