### ISSUE TITLE
Build dashboard in Cortex for analytics data

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#383]
Towards https://github.com/giantswarm/roadmap/issues/364

Once we have the data in Cortex, we can build a dashboard for it.

**Comment by JosephSalisbury** [comment]
@marians probably has some thoughts here :D

**Comment by TheoBrigitte** [comment]
My idea is to get a dashboard similar to this

![image](https://user-images.githubusercontent.com/6536819/130092664-b59e8456-46a9-44c8-bf28-44e7eaf688c7.png)

**Comment by marians** [comment]
Do we have data in cortex?

**Comment by TheoBrigitte** [comment]
Yes, we do first dashboard iteration is here: https://giantswarm.grafana.net/d/IFquOMXGz/grafana-analytics?orgId=1&refresh=1m
Metrics: `aggregation:grafana_analytics_sessions_total`

**Comment by marians** [comment]
Let's work on that next week

**Comment by TheoBrigitte** [comment]
> Let's work on that next week

I'm off next week.

**Comment by TheoBrigitte** [comment]
Going with this as first version. But happy to elaborate more on this dashboard later.
