### ISSUE TITLE
PMO reconciling v1alpha4 Clusters

### ISSUE THREAD

**Issue by mig4** [giantswarm/roadmap#385]
Currently PMO crashes on startup on MCs on which `Cluster` CRs use version `v1alpha4` as storage version:

```
panic: {"kind":"unsupportedStorageVersionError","annotation":"implementation does not support storage version \"v1alpha4\"","stack":[{"file":"/root/project/service/controller/clusterapi/controller.go","line":130},{"file":"/root/project/service/controller/clusterapi/controller.go","line":78},{"file":"/root/project/service/service.go","line":166}]}
```

This is coming from https://github.com/giantswarm/prometheus-meta-operator/blob/d382fccb8a346086fb07155e309dc2abf9bbe688/service/controller/clusterapi/controller.go#L123 and that is the `operatorkit` way of specifying what CRs to watch.

It seems because this function needs to return an object of a concrete type there's no way to rely on conversion webhook to be independent of the storage version configured on the MC.

Another complication is that to get access to the `v1alpha4` object we need to upgrade to [cluster-api](https://github.com/kubernetes-sigs/cluster-api) >= v0.4.0, and that means we loose support for `v1alpha2` objects (CAPI only supports two versions, latest and the immediate predecessor, nothing further back). While work is ongoing to migrate off this, we still have some AWS clusters using `v1alpha2` types.

**Comment by mig4** [comment]
[Slack thread](https://gigantic.slack.com/archives/CNUDS3AMU/p1626767053342000) where we discussed this with Celestials.

**Comment by mig4** [comment]
Also note: to upgrade the dependency and switch to `v1alpha3` + `v1alpha4` types we need to tag 0.4.0 in GS [cluster-api fork](https://github.com/giantswarm/cluster-api).

**Comment by TheoBrigitte** [comment]
PMO works on ghost even though v1alpha4 is used as storage version

```yaml
$ k --context giantswarm-ghost get crd clusters.cluster.x-k8s.io -oyaml|yq -y -r '.spec.versions[]|{name, storage}'
name: v1alpha3
storage: false
---
name: v1alpha4
storage: true
```

```yaml
  - apiVersion: cluster.x-k8s.io/v1alpha4
    kind: Cluster
    metadata:
      creationTimestamp: '2021-09-07T07:58:09Z'
      finalizers:
        - operatorkit.giantswarm.io/prometheus-meta-operator-cluster-api-controller
        - operatorkit.giantswarm.io/azure-operator-terminate-unhealthy-node-controller
        - operatorkit.giantswarm.io/azure-operator-cluster-controller
        - cluster.cluster.x-k8s.io
      generation: 4
      name: jt6v4
      namespace: org-giantswarm
      resourceVersion: '390116569'
      selfLink: /apis/cluster.x-k8s.io/v1alpha4/namespaces/org-giantswarm/clusters/jt6v4
      uid: 58c02819-ef20-4d25-8643-347ee9477d78
```

**Comment by TheoBrigitte** [comment]
I do not understand how the above thing happened but PMO now reconciles v1alpha3 cluster only.
