### ISSUE TITLE
Add linkerd-viz-app to app catalog

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#386]
Linkerd provides a dashboard and a set of grafana dashboards. Usually this is installed through `linkerd viz install | kubectl apply -f -`.

We suspect the cli uses [this helm chart](https://github.com/linkerd/linkerd2/tree/main/viz/charts/linkerd-viz) to generate the manifests.

Preliminary todo list:

- [x] Add a `linkerd2-viz` app to the appcatalog
   - [x] Investigate integration with existing prometheus and grafana

**Comment by ubergesundheit** [comment]
@ced0ps started working on https://github.com/giantswarm/linkerd-viz

**Comment by ced0ps** [comment]
linkerd-viz-app has been release and is available in the app catalog
