### ISSUE TITLE
Node labels to identify and select spot instances/VMs for workloads

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#393]
Assigning workloads to spot instances/VMs, or avoiding spot, currently requires knowledge of the node pool name (identifier), to be used as a node selector.

On AWS, if a node pool has a mix of spot and on-demand instances (via the spot/on-demand percentage and the on-demand base capacity), it is not possible to assign workloads to spot instances only (or avoid running on spot instances).

EKS [seems](https://aws.amazon.com/blogs/compute/run-your-kubernetes-workloads-on-amazon-ec2-spot-instances-with-amazon-eks/) to add `lifecycle` node labels to instances. In spot instances, this label gets the value `EC2Spot`.

A similar node label for each worker node in a cluster, with a dedicated value for spot instances (AWS)/VMs (Azure), would allow for simple workload assignment. A dedicated value for non-spot (on-demand) nodes would also allow for a descriptive assignment of workloads to only on-demand instances.

**Comment by teemow** [comment]
@alex-dabija @T-Kukawka this an old issue still labeled with firecracker? To phoenix or close?

**Comment by alex-dabija** [comment]
Old issue. Closing for now.
