### ISSUE TITLE
Make read-only access to Grafana dashboards work on the shared installation

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#401]
###  User stories

_- As a customer on a shared installation, I want to be able to access Grafana dashboards via Happa._
_- As a customer on a shared installation, I can only see the data about my own cluster(s) in Grafana dashboards._

### TODO

**Comment by Rotfuks** [comment]
This is done with the mutli tenancy epic. The Integration with Backstage will come up later. Closing this issue for now
