### ISSUE TITLE
Anomaly detection in Management Clusters using Falco

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#423]
User Story: As a customer I want Giant Swarm to make sure that the current security posture of Management Clusters is monitored.

To ensure that workloads in Management Clusters are what we intend them to be and that no workloads are doing things they were not intended to do, we introduce Falco as a Management Cluster component to monitor Management Cluster workloads and machines to detect anomalies. Anomalies will first lead to alerts and in a 2nd step to pages. Once we have a better picture of it we might also enable features like killing or pausing misbehaving workloads.

**Comment by puja108** [comment]
Current status is Falco running on all installations and alerting quietly in a Slack channel. Team Ludacris is monitoring that channel and plans to move critical alerts to pages. 

@stone-z can you add some details and link related issues to this public epic?

**Comment by stone-z** [comment]
Falco has been released to our management clusters and will receive ongoing support as part of our managed security stack. Alerting rules response mechanisms will be constantly evolving, but we will continue to incorporate policies and capabilities which are relevant for customers into the security stack. For more info: https://docs.giantswarm.io/app-platform/apps/security/
