### ISSUE TITLE
kvm release 16.0.0 with kubernetes v1.21

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#429]
Kubernetes v1.21 for kvm 

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md

### Provide a new release with the kubernetes version v1.21

* [ ] Check with the teams about wip changes within k8scloudconfig and the provider-specific operators. Decide with version folder to use.
* [ ] Retag new image in retagger
* [ ] Check [upstream changelogs](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md).
  * [ ] Check urgent upgrade notices.
  * [ ] Check deprecation notices.
  * [ ] Check component upgrades.
    * [ ] Calico
    * [ ] ETCD
    * [ ] Container Linux
* [ ] Create a PR in k8scloudconfig with the new kubernetes version
  * [ ] Update k8s version in the different template files
  * [ ] Use k8s version for `k8s-addons` (e.g. https://github.com/giantswarm/k8scloudconfig/blob/4695b7d6eb35eae234d0ce0c0c09f4b412525a68/v_4_7_0/files/conf/k8s-addons#L5)
* [ ] Update cluster-autoscaler
* [ ] Vendor k8scloudconfig in the provider-specific operators
* [ ] Create a wip release (major version change if it is a minor kubernetes upgrade)
* [ ] Do this for each provider
* [ ] Check Prometheus rules for deprecated metrics and fix them if necessary

### Check migration recommendations

Check migration recommendations from kubernetes and decide what we need to document for the customer and what we should migrate automatically for them

* [ ] Do we need to change our own resources within the tenant clusters?
* [ ] What do we need to communicate to our customers?
* [ ] Anything else that would be better automated for the upgrade?

### Run e2e and conformance tests

* [ ] Start a new cluster and run conformance tests against it
* [ ] Start a new cluster and run e2e tests against it
* [ ] Do this for each provider

### Check Core Components

* [ ] Check core components for updates and include them in cluster-operator
  * [ ] Cert-exporter
  * [ ] Chart-operator
  * [ ] Cluster-autoscaler
  * [ ] CoreDNS
  * [ ] Kube-state-metrics
  * [ ] Net-exporter
  * [ ] Nginx ingress controller
  * [ ] Node-exporter
* [ ] All helm releases in the giantswarm namespace should be in status deployed
* [ ] Core components are runnning without errors
  * [ ] Cert-exporter
  * [ ] Chart-operator
  * [ ] Cluster-autoscaler
  * [ ] CoreDNS
  * [ ] Kube-state-metrics
  * [ ] Net-exporter
  * [ ] Nginx ingress controller
  * [ ] Node-exporter
* [ ] Cluster-operator is running without errors
* [ ] Cluster-operator is able to create chart-configs in the tenant

### Test migration (both cluster functionality itself and workloads)

* [ ] Start a cluster with an older version and upgrade the cluster to the new release
* [ ] Upgrade a cluster that is not critical but has some more real workloads (eg giantswarm website, dev cluster of customer)
* [ ] Do this for each provider

### Write summary for the release and update docs

* [ ] Write some release notes
* [ ] Check if our docs need to be updated
* [ ] Announce the release internally (SEs are important here)
* [ ] Announce the release to the customers

**Comment by yulianedyalkova** [comment]
So I found the following errors:

* calico-kube-controllers
```
2021-09-02 10:59:28.845 [ERROR][1] cache.go 231: Reconciliation failed error=connection is unauthorize
d: networkpolicies.crd.projectcalico.org is forbidden: User "system:serviceaccount:kube-system:calico-
kube-controllers" cannot list resource "networkpolicies" in API group "crd.projectcalico.org" at the c
luster scope type=v3.NetworkPolicy
```

* cert-exporter
```
{"caller":"github.com/giantswarm/cert-exporter/exporters/cr/exporter.go:59","error":{"kind":"unknown",
"annotation":"the server could not find the requested resource","stack":[{"file":"/root/project/export
ers/cr/exporter.go","line":59}]},"time":"2021-09-02T11:00:28.011879+00:00"}
```

* k8s-api-server-master
```
W0902 11:02:05.011292       1 request.go:161] Auditing failed of  request: encoding failed: authentication.TokenRequest is not suitable for converting to "v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

All of them are also happening for `v15.0.0` though, @tfussell any memories of seeing these?

And some deprecation warnings:
* coredns
```
W0902 10:53:16.677006       1 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
```

* kube-proxy
```
W0902 11:00:58.238429       1 warnings.go:70] discovery.k8s.io/v1beta1 EndpointSlice is deprecated in v1.21+, unavailable in v1.25+; use discovery.k8s.io/v1 EndpointSlice
```

**Comment by tfussell** [comment]
Looks like the apiserver error is [fixed in 1.22](https://github.com/kubernetes/kubernetes/pull/102040). Nothing for us to do for now.

I thought I fixed the calico-kube-controllers RBAC issue, but I guess I never committed it. I think we can fix that in a patch release--not overly serious.

I'm unsure about the cert-exporter issue. We'll have to look at the code there.

I don't think we need to worry about the EndpointSlice warning for now.

**Comment by yulianedyalkova** [comment]
Thanks, just wanted to make sure we didn't already look into these before digging deeper!

**Comment by yulianedyalkova** [comment]
Resolved the rbac issues in `calico-kube-controllers`, now there is the following error:
```
2021-09-06 09:31:37.567 [WARNING][1] serviceaaccount_controller.go 245: Failed to update profile error=operation Update is not supported on Profile(ksa.kube-system.net-exporter) key="ksa.kube-system.net-exporter"
``` 
for all service accounts. It tries for 5 times and then drops them from the queue. Going through the code though it looks like a [desired behaviour](https://github.com/projectcalico/libcalico-go/blob/cce519e5ab59666aab91551d57a55398706b6f55/lib/clientv3/resources.go#L121) and not an issue with the underlying datastore.

**Comment by yulianedyalkova** [comment]
`cert-exporter` is failing when trying to list [certificates](https://github.com/giantswarm/cert-exporter/blob/7b7867bcfb39d1b638823d37aa7d09ee6d01d170/exporters/cr/exporter.go#L19-L23) and it's a real error because it doesn't proceed to exporting metrics. Not sure who is supposed to create that on the WC because the CRD does not exist.
