### ISSUE TITLE
Add customer name into alerts

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#430]
**Is your feature request related to a problem? Please describe.**

Sales department want to check which are the latest incidents

![Uploading Screenshot 2021-08-23 at 11.01.58.png…]()

**Describe the solution you'd like**

Non-tech ppl can identify looking to an alert or incident from which customer refers

**Describe alternatives you've considered**

**Additional context**

**Comment by QuentinBisson** [comment]
@pipo02mix is this still needed ? Should the installation name not be sufficient for this ?

**Comment by pipo02mix** [comment]
yeah I agree
