### ISSUE TITLE
prometheus-meta-operator E2E tests

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#439]
See https://github.com/giantswarm/rfc/tree/main/monitoring-system-end-to-end-tests for background

### Description

We've had a few incidents which were not detected by prometheus-meta-operator unit tests, largely related to interconnection of components (e.g: versions of clients in prometheus-meta-operator vs. deployed version of alertmanager, among other incidents). We reckon some E2E tests would help prevent these incidents.

We want to test with E2E tests (to begin with):
- prometheus-meta-operator can create a Prometheus server for a Kubernetes workload cluster
- the Prometheus server can scrape targets from the Kubernetes workload cluster
- the Prometheus server can send alerts to Alertmanager
- the heartbeat from the Prometheus server can reach Opsgenie

### Documentation 
- https://github.com/giantswarm/test-infra/#developing-test-infra
- https://github.com/giantswarm/test-infra/tree/master/docs

### Open Questions

- When to run E2E tests?
  - On every release and when we trigger it with a /test command

### First test scenario

_- Does this build of PMO creates a Heartbeat and it is active?_

### TODO

- [x] Talk to Ludacris about what Tekton can already do for us
- [x] #452
- [x] #453
- [x] #454
- [x] #455

**Comment by snizhana-dynnyk** [comment]
Ludacris is working on adding support for CAPI clusters in e2e tests.
