### ISSUE TITLE
CAPI for KVM clusters

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#441]
## User Story

- As a GS on-prem customer, I want to use the Management API to manage clusters and applications via GitOps.
- As a GS on-prem customer, I want to use the Management API to have more fine grained control over permissions and
  roles of API users.
- As a GS on-prem customer, I want would like for the KVM platform to use Cluster API so that I have access to new
  provider-independent features developed by other GS teams.
- As a GS on-prem customer, I want GS to implement a migration strategy from current KVM clusters to CAPK clusters
  so that I can access the new features without service disruption and workload migration.

## Details, Background

With giant swarms move to cluster API new features are developed against cluster API. In order to give our existing KVM customers access to this features and maintain support for the existing KVM installations in the future our kvm operator and tooling needs to be compatible with cluster API.
We will achieve this by creating a new cluster API compatible provider that can be a drop in replacement for our current kvm operator and take over the management of existing clusters.
This new provider can also be used in the future to create new clusters and give customers access to  new giant swarm features and enable them for the above user stories. 

## Blocked by / depends on

Monitor CAPI workload Clustes https://github.com/giantswarm/roadmap/issues/313
Default apps for CAPI Clusters https://github.com/giantswarm/roadmap/issues/320

**Comment by gawertm** [comment]
wont do this anymore as planned. We will migrate KVM installations to other providers. Also we will evaluate an actual Baremetal Provider
