### ISSUE TITLE
Automatic upgrades of non-CAPI clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#445]
Automatic upgrades of non-CAPI clusters.

Link to internal issue: https://github.com/giantswarm/giantswarm/issues/18077 .

**Comment by alex-dabija** [comment]
A cluster upgrade is triggered immediately or scheduled with `kubectl-gs`. More information is available in our documentation: https://docs.giantswarm.io/ui-api/kubectl-gs/update-cluster/ .

**Comment by T-Kukawka** [comment]
Current solution is widely used by customers and there is no immediate need for fully automatic upgrades. CAPI approach will revise the concept of GS releases and this will be tackled differently in the future.
