### ISSUE TITLE
[SPIKE] How to create a new Tekton pipeline and connect to GH

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#452]

**Comment by TheoBrigitte** [comment]
I did the following:

* add a new prow command
* add a new tekton pipeline + task
* configure the webhook in prometheus-meta-operator repository 

When we now write `/test heartbeat` into a PMO PR it does trigger a tekton pipeline, see:

- https://github.com/giantswarm/prometheus-meta-operator/pull/721
- 
![image](https://user-images.githubusercontent.com/6536819/133590713-ae6ddf10-863f-409d-8106-9a88677b9f7d.png)

![image](https://user-images.githubusercontent.com/6536819/133590758-224104c1-9c74-498b-9d09-708f21888990.png)
[source](https://tekton.giantswarm.io/#/namespaces/test-workloads/pipelineruns/68fcbf04-16d2-11ec-959d-fa3ca8521a07?pipelineTask=hello-world&step=echo)
