### ISSUE TITLE
kubectl-gs support for capv

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#457]
Towards https://github.com/giantswarm/roadmap/issues/319
## User Story
- As a giant swarm VMware customer I want to use kubectl-gs to manage CAPV clusters so that I can create and manage CAPV clusters in a reliable and repeatable way.

## Acceptance Criteria

- [ ] kubectl-gs can be used to create, update and delete a CAPV cluster

**Comment by tfussell** [comment]
This is merged.
