### ISSUE TITLE
Verify ssh access to CAPV nodes

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#458]
Towards https://github.com/giantswarm/roadmap/issues/319

## User Story

- As a GS on call person, I would like CAPV workload cluster nodes to be accessible via ssh so that I can have access in case of problems with a node. 

## Acceptance Criteria

- [x] for alpha: Cluster creator has ssh access to nodes in the cluster
- [x] for beta: All GS on call staff has access to the nodes in the cluster

## Dependencies

 - [x] https://github.com/giantswarm/roadmap/issues/457
 - [x] https://github.com/giantswarm/roadmap/issues/456

**Comment by kopiczko** [comment]
Should be compatible with https://github.com/giantswarm/opsctl/pull/1241

**Comment by jkremser** [comment]
done in https://github.com/giantswarm/cluster-vsphere/pull/23/files#diff-d1a933b82280a2653a1968219355c6edc14be0a2b4f5210f0939a96aa98c04f8R11

ssh to nodes work. One has to use opsctl ssh to some known machine first so that the signed ssh key is added to user's ssh-agent
