### ISSUE TITLE
CNCF conformance tests for CAPV clusters

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#459]
Towards https://github.com/giantswarm/roadmap/issues/319

## User Story

- As a GS developer, I would like CNCF conformance tests to run on every change to the CAPV cluster templates so that I am sure the cluster is CNCF conformant and save time on manual testing. 
- As a customer I want GS to run CNCF conformance tests in an automated way so that I am sure that the clusters I create with GS tooling are CNCF conformant

## Acceptance Criteria

- [ ] Given I am a GS developer when I do a Pull-Request with a change in the CAPV resources then I should get a result on the conformance tests

## Dependencies

- [x] https://github.com/giantswarm/roadmap/issues/456
- [x] https://github.com/giantswarm/roadmap/issues/456

**Comment by gawertm** [comment]
created generic isssue for all capi provider https://github.com/giantswarm/roadmap/issues/1486
