### ISSUE TITLE
Display scheduled workload cluster upgrades in the web UI

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#465]
The [upgrade-schedule-operator](https://github.com/giantswarm/upgrade-schedule-operator) handles triggering a workload cluster upgrade at a time configured via annotations.

The web UI should make use of the annotations when available.

Scheduling an upgrade is not within the scope of this issue and should be handled separately.

## High level spec

In places where we currently show a warning icon with "Upgrade available" information on a workload cluster (list of clusters, cluster details "Overview" tab), we should not display that warning if an upgrade is already scheduled. Instead we should show some information (not a warning) like `Will upgrade to <version> in <time distance>`.

## Open questions

- Should the UI offer the "Upgrade now" button when an upgrade is scheduled? This would effectively allow the user to upgrade earlier than scheduled.

## References

These are the current alpha annotations used to configure an upgrade:

-  [`alpha.giantswarm.io/update-schedule-target-release`](https://docs.giantswarm.io/ui-api/management-api/crd/clusters.cluster.x-k8s.io/#v1alpha3-alpha.giantswarm.io/update-schedule-target-release)
- [`alpha.giantswarm.io/update-schedule-target-time`](https://docs.giantswarm.io/ui-api/management-api/crd/clusters.cluster.x-k8s.io/#v1alpha3-alpha.giantswarm.io/update-schedule-target-time)

**Comment by axbarsan** [comment]
Also worth noting that the time format that `alpha.giantswarm.io/update-schedule-target-time` is encoded in is `RFC822` (i.e. `10 Nov 09 23:00 UTC`)
