### ISSUE TITLE
Fix typo in cluster upgrade notification message

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#470]
Fix typo in cluster upgrade notification message. It should be mention `anomalies` instead of `annormalies`.

Example:
```
The cluster default/dc746 upgrade from release version 14.2.2 to 15.2.0 is scheduled to start in 11m0s. Please contact us via urgent@giantswarm.io in case of annormalies.
```

**Comment by njuettner** [comment]
Typo has been fixed within https://github.com/giantswarm/upgrade-schedule-operator/releases/tag/v0.2.1
