### ISSUE TITLE
Publish notification when cluster upgrade is done

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#472]
_*As a cluster admin I want to be notified when a cluster upgrade is don in order to check that all systems are running fine.*_

## Background
Currently, we publish 2 messages:
- one, approximately 15 minutes before the upgrade to let our customers know that the upgrade is happening;
- second one when the cluster upgrade is triggered.

This behavior creates confusion for our customers as they don't really know what is going on with the upgrade.

**Comment by AverageMarcus** [comment]
Added in giantswarm/event-exporter-app#73 and released in https://github.com/giantswarm/event-exporter-app/releases/tag/v0.6.0
