### ISSUE TITLE
Grafana dashboard for Flux monitoring

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#475]
From the customer feedback - would be great to have a public Grafana dashboard showing the health of the Flux app on a management cluster.

**Comment by kubasobon** [comment]
@snizhana-dynnyk we've done this as part of https://github.com/giantswarm/giantswarm/issues/19455.
You can visit the new `Flux Cluster Stats` and `Flux Control Plane` public dashboards in every MC.

**Comment by snizhana-dynnyk** [comment]
Awesome!
