### ISSUE TITLE
Provide docs for setting cloud provider credentials via the Management API

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#480]
Towards https://github.com/giantswarm/giantswarm/issues/16364

With the Rest API being deprecated and customers moving to the Management API and single sign-on, we need a documented method to set cloud credentials.

- [x] Add documentation for AWS
- [x] Add documentation for Azure

**Comment by marians** [comment]
Sending to SIG product for a quick chat about the unknowns here

**Comment by snizhana-dynnyk** [comment]
From @T-Kukawka - covered on Azure [here](https://docs.giantswarm.io/getting-started/cloud-provider-accounts/azure/#3-invite-giant-swarms-service-principal-to-your-active-directory)

**Comment by marians** [comment]
AWS documentation is now available at https://docs.giantswarm.io/ui-api/management-api/credentials/
