### ISSUE TITLE
Non rolling cluster upgrade notifications

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#490]
## User Story

_- As a cluster admin, I want to be notified when non rolling cluster upgrades are triggered in order to quickly be aware of the minimal impact of such upgrades._

## Details, Background

`upgrade-schedule-operator` is used now to notify our users that a cluster upgrade is in progress. This functionally works as expected for upgrades which roll nodes. As an optimization, we also have upgrades which only update applications running on the cluster. No events are published in this case.

`cluster-operator` needs to be updated to publish upgrade events for cluster upgrades which don't roll nodes. The Slack notification configured for these events should mention that the upgrade will not roll the nodes.

## Blocked by / depends on

None

**Comment by teemow** [comment]
@alex-dabija @T-Kukawka this an old issue still labeled with firecracker? To phoenix or close?

**Comment by alex-dabija** [comment]
The issue is outdated because it applies to vintage.
