### ISSUE TITLE
Support ALB controller in Giant Swarm clusters

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#497]
**Is your feature request related to a problem? Please describe.**

A customer need to create dynamic Network Load Balancers using the cluster API.

**Describe the solution you'd like**

Adapt [AWS load balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller/tree/v2.2.4) to be able to run in Giant Swarm clusters

**Describe alternatives you've considered**

**Additional context**

**Comment by JosephSalisbury** [comment]
Two sides to this: getting it working, but also providing it as a managed app

**Comment by ced0ps** [comment]
Successfully running it. Requires a bit of manual configuration which I so far was unable to automate. Should have an app drafted by noon.

**Comment by ced0ps** [comment]
Ran into issues with functional testing because ALB requires at least two AZs. Test-Cluster has one.

**Comment by JosephSalisbury** [comment]
Standup update: test cluster is now multi-AZ. Checking out issues with IAM roles, @ced0ps is _consulting_ with @paurosello and @pipo02mix

**Comment by JosephSalisbury** [comment]
The AWS LB Controller can now be deployed from the App Catalog, installation details are described in the README (which can be found in Happa). Bam!
