### ISSUE TITLE
Certificate generation/rotation for individual k8s components

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#50]
# Certificate generation/rotation for individual k8s components

## User story

* As a cluster admin I expect that I can create roles and policies for each of the internal components of our Kubernetes clusters and also per node.

* As a cluster admin I expect that those certificates are rotated frequently

* As a cluster admin I expect that the node can authorize itself and only change pods assigned to it and only fetch secret that are needed within its pods. See https://kubernetes.io/docs/admin/authorization/node/

## Rationale

We should have a proper certificate setup with separate certificates for components that also identify the component and the machine it is running on. These certificates further need to be rotated regularly.

Both these actions will help us increase security of our setups sginificanlty. They are further part of the CIS benchmark for Kubernetes.

## Background

We currently reuse certificates across components on master and across all workers. This is a security issue and also requires us to do unnecessary bootstrap bindings.

Furthermore, we currently do not have any rotation funcationality anymore. This can result in old clusters at some point running into issues with outdated certificates.

Upstream, projects like `kubeadm` are going for Kubernetes' in-built [TLS bootstrapping](https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping/), where the API Server is provided a CA and can sign CSRs to provide certificates to components and users. There's bootstrapping mechanisms for kubelets and options for automatic certificate rotation. This is an area SIG Cluster Lifecycle is focussing on.

## Open questions

We might need to rethink our way of generating and distributing certs for this. Rotation and scaling of clusters (which might be out of control of the operator itself) are the most interesting problems to look at to define a new distribution of certificates.

## Possible side effects

If we go for the inbuilt TLS bootstrapping we need to decide if Vault stays in charge of cluster certificates or we demote it to only provide the initial CA and bootstrap certificates and then the guest cluster API server takes over authority.

In that case we might need to rethink our way of issuing certificates for users, too.

Furthermore, the CN and O fields of certificates will change so we will need to check if we make use of those somewhere in the code. https://github.com/giantswarm/giantswarm/pull/2223

## Related stories

- SECRET-MANAGEMENT

**Comment by puja108** [comment]
I'm closing this as we will be solving this within our move to CAPI within #427
