### ISSUE TITLE
Cluster API Release Management

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#506]
Cluster API Release Management.

Spec: https://github.com/giantswarm/rfc/pull/24 .

**Comment by MarcelMue** [comment]
@fiunchinho this is also the corresponding spec:
https://github.com/giantswarm/giantswarm/pull/18937

**Comment by MarcelMue** [comment]
I was somehow convinced I had merged the spec already - no clue why this was super certain to me

**Comment by MarcelMue** [comment]
Copy of current state from slack channel:
> I want to write an update here on the status to reflect the work which has been going on and how it reflects to this working group:
> * CAPO is using the new release scheme actively. THG has adopted the releases and has a set of clusters running on their production MC which is fully managed by gitops. Implementation and ownership of the releases is now fully in Rocket. Honeybadger works on the app-platform and gitops together with the customer.
> * CAPA has created the basic apps needed for the new releases but is currently blocked during a CRD transition. Will progress after that, implementation done by Vaclav.
> * CAPZ will start with the CRD transition being done.
>
> In Honeybadger we have been working more closely with customers on gitops. This lead to some positives (in addition to all the stress :stuck_out_tongue:) : We were able to identify different usecases for customers more closely and understand their motivations better.
> Currently we focus on internal dogfooding more (especially gitops for workload-clusters) to reflect these usecases we discovered internally while iterating on our gitops setup and in turn `capi-releases` integration into gitops.

**Comment by MarcelMue** [comment]
We had an informal vote in slack and unanimously decided to close the working group.

CAPI releases are being used by teams and coordination should from now on happen between teams on explicit issues. 

So feel free to reach out to Honeybadger for App specific support, the KaaS teams for implementation specifics and so on.
