### ISSUE TITLE
[SPIKE] How can all cluster CRs be moved to the organization's namespace?

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#509]
How can all cluster CRs be moved to the organization's namespace for a given installation after all clusters are on AWS v16.0.1?

## Questions
- [ ] Can this process be easily automated?
- [ ] What are the exact steps which need to be followed?

## Background
Our customers are moving to SSO. Current status can be seen on the following board: https://github.com/orgs/giantswarm/projects/228 .

AWS v16.0.1 has all the required features to work when all cluster CRs are in the organization's namespace.

**Comment by anvddriesch** [comment]
Just dropping by to add, we might also have to move the `certConfigs` and `Secrets` for the clusters to properly separate org-namespace access.

Also if you need help with this migration, I'm up for it.

**Comment by pipo02mix** [comment]
Short note: [Klingel needs that for kgs login feature](https://gigantic.slack.com/archives/C01G30NGUS3/p1636707025034500). They would like to have for next week if possible

**Comment by whites11** [comment]
The [migrator](https://github.com/giantswarm/aws-cluster-namespace-migrator) seems to be working fine. I am now puzzled by which version should be the first to support this. 16.0.1 is the first one where secrets were moved to the org namespace AFAIU

**Comment by anvddriesch** [comment]
16.0.1 sounds like the safest bet to me!

**Comment by whites11** [comment]
Test were successful, will try to migrate some of our clusters and leave them there for a few days to catch long term effects

**Comment by whites11** [comment]
Gorilla / rfjh2 migrated. Monitoring this week

**Comment by whites11** [comment]
rfjh2 run ok the whole week, sent a news msg to make the migrator generally available
