### ISSUE TITLE
CAPI - enable/configure encryption-at-rest for etcd

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#510]
Previously aws-operator and azure-operator handled the creation of encryption key and a `k8s-encryption-config.yaml` was created on the machine images.

Some additional context: https://github.com/giantswarm/kyverno-policies/pull/123#issuecomment-947586192

Related upstream:
* https://github.com/kubernetes-sigs/cluster-api/issues/3761
* https://github.com/kubernetes-sigs/cluster-api/issues/5294
* https://github.com/kubernetes-sigs/cluster-api/issues/3430
* https://github.com/kubernetes-sigs/cluster-api/pull/4172

**Comment by alex-dabija** [comment]
Blocked until we have: https://github.com/giantswarm/roadmap/issues/677 .

**Comment by calvix** [comment]
done
