### ISSUE TITLE
Add S3 policy to move etcd backups to Glacier after 3 months.

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#513]
Add S3 policy to move etcd backups to Glacier after 3 months.

TODOs:
- [ ] announce the policy

**Comment by paurosello** [comment]
This policy is already in place for etcd-backups.giantswarm.io
![image](https://user-images.githubusercontent.com/1133954/140026451-0a79fe86-dc3f-4a5c-b130-c1dbbfca0b68.png)

This is also in place for backups.giantswarm.io
![image](https://user-images.githubusercontent.com/1133954/140026977-089a2dd0-efe8-4a78-9949-7fd2c603b136.png)

Mayu also seems ok
![image](https://user-images.githubusercontent.com/1133954/140027061-d4fa4fa9-acb8-4f90-819f-b9ebfb92bfb9.png)

**Comment by paurosello** [comment]
I did not modify anything, this rules were already in place
