### ISSUE TITLE
Allow customers to manage provider credentials 

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#527]
Towards ***https://github.com/giantswarm/giantswarm/issues/16364 REST API Sunset***

### Description

Customers are switching to SSO and they want to set up new organizations and set the Azure credentials for them. The UI does not support this currently (in SSO). 
Provider credential secrets are currently stored in the `giantswarm` namespace and customers don’t have access to it.

#### Current workaround 
We create secrets in the org namespace for customer

#### Expected behaviour 
Customers expect to be able to manage secrets organization namespaces themselves.

### TODO

- [x] Verify that credentials outside the `giantswarm` namespace working as expected for Azure

**Comment by snizhana-dynnyk** [comment]
ping @alex-dabija

**Comment by alex-dabija** [comment]
This is already supported and works as expected.
