### ISSUE TITLE
Update cert-manager-app to use upstream 1.6.1

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#528]
https://github.com/jetstack/cert-manager/releases/tag/v1.6.0

**Comment by ubergesundheit** [comment]
1.6.1 has been released today https://github.com/jetstack/cert-manager/releases/tag/v1.6.1

**Comment by JosephSalisbury** [comment]
Updating issue to 1.6.1 🚀

**Comment by JosephSalisbury** [comment]
@ubergesundheit wrote a script in the playground for checking ingress versions, we need to check all clusters for CRDs, as they've deprecated old versions of CRDs which they don't reconcile anymore, continue checking those changes upstream

@ubergesundheit to send @webwurst an updated script that does stuff better with the whole gsctl/kubectl-gs changes

@webwurst to drop the data about whether customers have old CRDs <3

**Comment by JosephSalisbury** [comment]
@webwurst what's the status here?

**Comment by JosephSalisbury** [comment]
Todo:

- [ ] Compile list of WCs that reconcile the old cert-manager CRs
- [ ] Test new cert-manager PR

**Comment by webwurst** [comment]
Scripted output of `apiVersion` for `ClusterIssuer`, `Issuer`, `Certificate` shows `v1` for clusters where access was possible.

**Comment by ubergesundheit** [comment]
> Scripted output of apiVersion for ClusterIssuer, Issuer, Certificate shows v1 for clusters where access was possible.

Do you have the list of management and workload clusters where you could not check?

**Comment by JosephSalisbury** [comment]
Tobias is gonna get us a list of the failing workload clusters (i.e: cluster we can't access), or clusters with old certificate CRD versions

**Comment by JosephSalisbury** [comment]
Certificate CRD versions are fine across all clusters, we're gonna do some testing bam

**Comment by ubergesundheit** [comment]
released 2.12.0
