### ISSUE TITLE
Add support to `kubectl gs login` to create WC client certs with a service account token

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#535]
Customer wants be able to use `kubectl gs login` to create WC client certs with a service account token.
They need this to be able to create client certs by automation (e.g. in their CI pipeline) without manual steps.

### TODO

- [ ] UX spec for how the command should work with --token
- [ ] Gather customer' input on supporting service account tokens in `kubeconfig` user entries (OBI, Vodafone, Telekom)
- [ ] Implementation

### Question

- Should we support service account tokens in `kubeconfig` user entries

**Comment by johannges** [comment]
i would be happy with a service account token as well

**Comment by othylmann** [comment]
@johannges can you please give a bit more detail like just in the call? Thx.

**Comment by johannges** [comment]
we want to automate the complete Cluster creation process:

1. [FLUX Managment Cluster] create Organisation via CR
2. [FLUX Managment Cluster] create Cluster and Networkpool CRs
3. [FLUX Managment Cluster] create Nodepool CRs
4. [FLUX Managment Cluster] create Managed Application (Flux, Nginx ingress, Prometheus Operator, Dex, ...)
5. [FLUX Worload Cluster] create Not Managed Applications (RBAC Rules, Instana, Thanos, Kubecost, Filebeat,...)
6. [Terraform] **Create Cluster Certificates for Team Access to the cluster** kubectl gs login needs to be able to run without human input (without oidc)
