### ISSUE TITLE
Work in Progress Release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#539]
## User Story

_- As a developer, I want to work on a new release without having our customers interact with it._

## Details, Background

In order to accelarate our CAPI progress we need to have all the CAPI components running on a management cluster. We are currently deploying them as a `v20.0.0` Giant Swarm release. Unfortunately, this release is also visible in Happa at the moment which led to questions being asked by our customers.

## Changes

- Giant Swarm release can be marked as `in-progress` (alternatives `work-in-progress`, `in-development`);
- Happa hides such a release for all users.

## Questions

- Should such a release be only hidden from our customers and visible to Giant Swarm employees?

**Comment by snizhana-dynnyk** [comment]
@piontec for Honeybadger - we need to add support to `release-operator` to add `in-progress` status to releases

**Comment by snizhana-dynnyk** [comment]
scratch my previous comment, @alex-dabija takes this to Phoenix :)

**Comment by AverageMarcus** [comment]
Releases already support (and are using) a WiP status (see here: https://github.com/giantswarm/apiextensions/blob/babaa3286282fa65fd05a77b680b41f14cd2bade/pkg/apis/release/v1alpha1/release_types.go#L20). The UI components needs to be modified to support hiding them for customers.

**Comment by marians** [comment]
The main comment says

> Happa hides such a release for all users.

@AverageMarcus says

> The UI components needs to be modified to support hiding them for customers.

Which one exactly is intended?

When talking about UIs, we mean both kubeclt gs and web UI, correct?

Are we fine with such Releases still showing up via `kubectl get releases.release.giantswarm.io` (without gs plugin)?

**Comment by AverageMarcus** [comment]
> Are we fine with such Releases still showing up via kubectl get releases.release.giantswarm.io (without gs plugin)?

I'd say that's fine as there isn't a huge amount we can do about that. `kubectl gs get releases` should maybe have an argument to toggle showing them maybe?

**Comment by AverageMarcus** [comment]
That sounds like this is already in place then and this issues isn't needed?

**Comment by PrashantR31** [comment]
We do not want to show all the versions including work in progress version (e.g v1.2x.y ) which are available for Internal users only and not for customers.

Suggestion:
1. Have a notice to say WIP releases are "WIP" in Happa on cluster creation
2. Release status on List of existing clusters.

**Comment by snizhana-dynnyk** [comment]
@alex-dabija feel free to close this issue, I am removing it from our board.
We will start working on Preview releases this week.

**Comment by LolloneS** [comment]
I'll take the liberty to close this
