### ISSUE TITLE
Include workload cluster API CA in the cluster values configmap

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#545]
**Is your feature request related to a problem? Please describe.**

The problem is some apps that talk to the Kubernetes API need to read the API CA in order to trust on it (we used self signed certs), and we don't know the have it at hand.

**Describe the solution you'd like**

The cluster operator adds the CA in the configmap that lives in the cluster namespace so all apps can rely on it when they are deployed

**Describe alternatives you've considered**

**Additional context**

**Comment by rossf7** [comment]
Done in cluster-operator 3.11.0 and requested for AWS in https://github.com/giantswarm/releases/pull/855

@pipo02mix Do we need this Azure and KVM? As then we also need this in the legacy branch :(
