### ISSUE TITLE
Don't get paged for clusters without node pools

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#546]
Since a customer has an option to delete node pools, and they might do this to save costs, we need to make sure that control planes are sufficient and we don’t get pages for this.

We support zero node pools and such control planes should be fully functional.

### TODO 
- [ ]  update alerts so we don't get paged
- [ ]  make it clear in the documentation how we expect clusters without node pools to work.

**Comment by whites11** [comment]
Blocked by https://github.com/giantswarm/giantswarm/issues/18779

**Comment by whites11** [comment]
We can use `kubelet_node_name` metric to detect the number of working nodes, split by role

**Comment by whites11** [comment]
All pieces are in place now. I am trying to test this

**Comment by whites11** [comment]
Everything is ready. Just waiting one last release in `prometheus-meta-operator` (waiting for team atlas to approve it).

See opsrecipe here: https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/silence-alert-empty-clusters/

**Comment by whites11** [comment]
Blocked by release of prometheus-meta-operator

**Comment by teemow** [comment]
ping @snizhana-dynnyk @alex-dabija 

We are still getting paged by these clusters. It would be awesome if this would be unblocked.

**Comment by whites11** [comment]
It is unblocked and released!
We now have a dedicated inhibition alert for these clusters, we just need to use the inhibition for the alerts that we don't want to fire in this situation

**Comment by whites11** [comment]
Confirming the inhibition alert is in place for the cluster that paged Nick last night

![inhib](https://user-images.githubusercontent.com/868430/146519289-501c149f-45fc-404b-9ad8-540242c88cc2.png)

**Comment by whites11** [comment]
First round of silences should be in place, let's iterate from here.
