### ISSUE TITLE
Move dex app to Giant Swarm catalog

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#547]
The [dex app](https://github.com/giantswarm/dex-app) is currently published via the Control Plane catalog and the Playground catalog.

### TODO

- [x] #854
- [x] remove Dex from playground catalog
  - [x] make sure nobody is using it anymore

### Question
- Can we use Dex from `giantswarm` catalog on a MC?
- Which version should we use to publish to giantswarm catalog
  	- There is a ‘maturity of managed apps’ versions’ doc to check

**Comment by snizhana-dynnyk** [comment]
Include in refinement:
`dex-app` needs values schema for validation
