### ISSUE TITLE
Include workload cluster API CA in the cluster values configmap for CAPI clusters

### ISSUE THREAD

**Issue by rossf7** [giantswarm/roadmap#548]
**Is your feature request related to a problem? Please describe.**

The problem is some apps that talk to the Kubernetes API need to read the API CA in order to trust it, and we don't know the have it at hand.

**Describe the solution you'd like**

The cluster-apps-operator adds the CA in the configmap that lives in the cluster namespace so all apps can rely on it when they are deployed.

We need to use the CA provisioned by CAPI instead of our self signed cert managed by cert-operator.

**Describe alternatives you've considered**

**Additional context**

Original issue for legacy AWS support https://github.com/giantswarm/roadmap/issues/545

**Comment by rossf7** [comment]
I don't think its high priority but for feature parity do we need this for CAPI?

Change would be to add it to the clustervalues resource in cluster-apps-operator.

@MarcelMue WDYT?

**Comment by MarcelMue** [comment]
From the description it does sound like we would need it. I can not tell on top of my head what the easiest way to get it is though.
