### ISSUE TITLE
Evaluate use main branch of `cluster-operator` for Azure

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#554]
Evaluate use main branch of `cluster-operator` for Azure.

**Comment by whites11** [comment]
Cluster Autoscaler fails because of missing AWS CRDs in azure MCs:

- no matches for kind "AWSCluster" in version "infrastructure.giantswarm.io/v1alpha3"
- no matches for kind "G8sControlPlane" in version "infrastructure.giantswarm.io/v1alpha3"

**Comment by whites11** [comment]
Found some hardcoded aws specific functions

**Comment by whites11** [comment]
Looking decently good.
Azure operator only needs a very small change which is good.
Cluster operator needs a few changes, but most of them are about disabling features because they are already implemented in azure operator.
I still need to test I didn't break AWS support

**Comment by whites11** [comment]
Removed the need to create AWS CRDs in azure MCs with another round of ifs :sweat_smile:

**Comment by whites11** [comment]
I tested my cluster-operator branch with both aws and azure.
First tests are promising, I'm now running conformance tests just to be sure I didn't break anything.
kubeconfig generation works with my branch of kubectl-gs.
Hopefully I can get to the bottom of this issue before the week ends.

**Comment by whites11** [comment]
Azure conformance tests passed.
AWS conformance tests did not.

**Comment by whites11** [comment]
Failed AWS test might be because the cluster didn't have enough nodes.
Trying again with a bigger cluster

**Comment by whites11** [comment]
Confirmed, conformance tests green on AWS as well
