### ISSUE TITLE
Align "No node pools" text colour

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#558]
<img width="1199" alt="Screen Shot 2021-11-11 at 13 19 30" src="https://user-images.githubusercontent.com/62935115/141296937-b005230c-fb30-444b-a42b-b9ad81d5d3d0.png">

The "No node pools" message is currently displayed in yellow, the colour we reserve for warnings. We should align it to use the same colour as the "No apps" and "No client certificates" messages.

**Comment by PrashantR31** [comment]
:+1:
