### ISSUE TITLE
Real-time event stream

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#56]
## User story

* If I as a cluster-admin create/upgrade/scale/delete a cluster I want to get feedback about the steps of the initiated process.

* If I as a cluster-admin create/upgrade/scale/delete a cluster I want to see errors within the initiated process immediatly.

## Rationale

Get real-time information on status changes, so that we can display e. g. readyness after cluster creation.

## Background

We don't provide any feedback during cluster creation at the moment. And the same will happen during an upgrade
of a cluster.

Since cluster creation, upgrades, and scaling, to name a few, are complex processes that can take some time,
it would be benefitial to be able to display detailed progress information in our UIs. This would also help
users to diagnose errors when something does not work as expected.

An event stream as part of our API would also enable custom integrations. For example, customers could trigger
the creation of an external uptime check whenever a new ingress is created in a guest cluster. Note that this
aspect is especially targeted in the `EVENT-HOOKS` story.

As an obvious technology choice, a WebSocket API should be offered for clients to consume the stream.

With "real time" we mean a delay of a few seconds between an event occurring and being presented via the API.

In cluster creation, these are a few examples for the types of events we would like to get from the API:

- Cluster creation event types we can think of as being reported via the API:
  - Key-pair backend available (for creating key pairs for the cluster)
  - Kubernetes API server is up
  - Individual worker are "known" with their identifier or IP address
  - Individual worker nodes are in `Ready` state
  - Ingress load balancer is working
  - Calico network is set up and working
  - Internal DNS is up and working
  - Prometheus scrape targets for the cluster have been created

- Upgrades
  - Individual node is cordoned, drained, shut down
  - Individual node is in `Ready` state (in new version)

- Scaling up
  - Individual worker are "known" with their identifier or IP address
  - Individual worker nodes are in `Ready` state

- Scaling down
  - Individual worker is cordoned, drained, shut down
  - Individual worker is removed from the cluster

- Deletion
  - Individual node is removed
  - Individual worker is removed from the cluster (TBD)
  - Cluster object is deleted

We are aware that in deletion, the events don't provide actionable information, still having
it will improve the experience and raise trust in the system.

## MVP and further iteration

As a minimal version, for cluster creation we expect these event types:

- Kubernetes API server is up
- Individual worker nodes are in `Ready` state

## Open questions

- Do we want to watch custom object status changes, or do we rather prefer a messaging API to be used
  from within operators?

## Possible side effects

- Load on the kubernetes API server when watching custom object status changes.

## Dependencies/prerequisites

- Differentiation between actual state and desired state in custom objects would allow for
  watching object changes, which would be the basis of the implemnentation. That should be
  covered in the `STATE` story.
- We should have finalizers in place, to be able to observe a cluster deletion.
- A unified worker identifier working over all providers would be benefitial.
- Guest cluster upgrades must be working in order to have upgrade events

## Related stories

- Transparency  Regarding Cluster State https://github.com/giantswarm/roadmap/issues/75
- History of a Cluster https://github.com/giantswarm/roadmap/issues/57
- Webhooks for Events https://github.com/giantswarm/roadmap/issues/74

**Comment by teemow** [comment]
@weatherhog this is a very old story. But I think there would still be value in seeing all events from our clusters. Loki might help us with it. Happy to discuss in more detail.

**Comment by weatherhog** [comment]
@teemow I was thinking if this is something that can be solved with CAPI and GitOps? Maybe something that Flux is capable of?

**Comment by teemow** [comment]
@weatherhog yes you are right. the use cases can be done already because we can display the status of the resources in the management api. 

I was coming from a different angle. Which i would also still like to do some brainstorming around. It is more about to have a message queue like pub/sub system of kubernetes events. If this would be centralized  we would be able to write more central tools that would be able to anaylse and react on what is going on in the clusters. I've build a similar architecture in Adcloud many years ago and it was a huge enabler. In parts this might overlap with what you can see and do with metrics or logs. But it is much more structured and programmable due to the events based nature. This would enables us to quickly write some tools that analyse things that aren't touching any management cluster. 

I'd need to rework the description and use cases a bit. Do you wanna keep this in the board for later as the team is busy anyway and we do a brainstorming in a few months?

**Comment by teemow** [comment]
I'm closing this one. It's very old and there isn't a use case that is imminent atm.
