### ISSUE TITLE
CAPI - delete of `cluster` doesn't cascade down to `awsmachinetemplates`

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#566]
Deletion of `cluster` doesn't cascade down to `awsmachinetemplates` but their presence block the finalizer on `cluster`.

The `AWSMachineTemplate` has an ownerReference pointing to the `Cluster` but it doesn't seem as though the `deletionTimestamp` is being propagated to the `AWSMachineTemplate`. 

Need to check if it's an issue with our current version of CAPI or if fixed upstream.

**Comment by alex-dabija** [comment]
Blocked until we can use `v1beta1`.

**Comment by calvix** [comment]
with the new release approach via app/helm  repo, every resource created  for the cluster by helm will be also deleted by helm so we don't really care if there is cascading deletion or not
