### ISSUE TITLE
CRDs need to be patched to support all the required versions

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#568]

**Comment by alex-dabija** [comment]
Blocked until we have the proposal on how we want to handle the CRDs going forward.

**Comment by nprokopic** [comment]
The change has been merged in our CAPI fork.

Currently we are working on updating the  cluster-api-app to use the controller version from our fork, that work is happening here https://github.com/giantswarm/cluster-api-app/pull/17.

**Comment by nprokopic** [comment]
@AverageMarcus I think we can close this one, it was about porting back v1alpha2 API version in our forks, right?

**Comment by AverageMarcus** [comment]
Yep!
