### ISSUE TITLE
Implementation of conversion webhook application

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#570]

**Comment by nprokopic** [comment]
The change has been merged in our CAPI fork.

Currently we are working on updating the  cluster-api-app to use the controller version from our fork, that work is happening here https://github.com/giantswarm/cluster-api-app/pull/17.

**Comment by nprokopic** [comment]
Moved it to in progress as we are actively using and testing the aforementioned cluster-api-app.

**Comment by alex-dabija** [comment]
The implementation is done and tested on `ginger`.
