### ISSUE TITLE
Add CLI guide for upgrading a cluster

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#574]
patch the `release.giantswarm.io/version` label on the `clusters.cluster.x-k8s.io` CR

- [ ] add to CLI guide for upgrading a cluster to use new `update cluster` command

**Comment by PrashantR31** [comment]
Not urgent, @marians , a little help please, could you do a small spec for this functionality when you free. Could be something that @gusevda can do.

**Comment by marians** [comment]
@gusevda Spec incoming.

Note: in step 2, the comments in thew CLI command are not meant to be displayed.

----

**1. _Standard login step_** (see other CLI guides)

**2. Update the release label**

```bash
$ kubectl \
  --context gs-gremlin \                # Replace "gremlin" with the installation name
  --namespace org-marian \              # Replace "marian" with the organization name
  label clusters.cluster.x-k8s.io \
  v3c5e \                               # Replace with the cluster name
  --overwrite \
  release.giantswarm.io/version=17.0.0  # Replace "17.0.0" with the target version available
```

Here `17.0.0` is the release version to upgrade to.

**Additional information**

- [kubectl gs plugin installation](https://docs.giantswarm.io/ui-api/kubectl-gs/installation/)
- [Cluster CRD schema](https://docs.giantswarm.io/ui-api/management-api/crd/clusters.cluster.x-k8s.io/)
- [Management API introduction](https://docs.giantswarm.io/ui-api/management-api/overview/)
