### ISSUE TITLE
AWS: High Availability Masters

### ISSUE THREAD

**Issue by J-K-C** [giantswarm/roadmap#58]
Short: HA masters

## User Story

- _As a Customer, I want Giant Swarm to provide a high availability of Kubernetes master nodes on my tenant clusters so that if one master becomes unavailable, the cluster's Kubernetes API is still available and I can still control the cluster._

- _As a cluster admin, I want to configure a cluster to use multiple master nodes, so that the risk of a Kubernetes API downtime is minimal_

## Details, Background

Rationale: Even if workloads are still functioning, a temporary downtime of the Kubernetes API seriously impacts our customers in that they can't update any deployments, scale replicas etc.

Background: Reliability will be increased by making multiple masters reside in different availability zones (AZ), as this reduces the likelihood of all masters being unavailable at the same time. Cluster upgrades would benefit from this, as with a single master an upgrade automatically implies a downtime. This might be implemented as optional, as not all use cases may require the high availability and justify the increased cost (e. g. dev, testing).

## Minimal Viable Product (MVP) scope

1. Cluster creators will have the option of a single one or three master nodes.
2. There will be a 1:1 mapping of master nodes to availability zones (AZ). Put differently, each master node will be in a different availability zone.
3. Master nodes will be randomly assigned to AZs.
4. Each Master will have its own AWS Auto Scaling Group (ASG. As such, master node EC2 instances will be automatically restarted/replaced when down.
5. We will support the migration of master nodes from single to multiple master nodes.
6. There will NOT be the option to move back from 3 to 1 master node.
7. If using Node Pools and HA Masters, master and worker nodes will have highest possible AZ overlap.
8. We will display information about which AZs have been selected.
9. HA masters will be the default option for new clusters.

**Comment by marians** [comment]
Users, partners, customers interested in this feature can find the API spec changes draft in https://github.com/giantswarm/api-spec/pull/202

**Comment by marians** [comment]
Very happy to announce that High-availability Kubernetes masters has been shipped with [AWS release v11.4.0](https://github.com/giantswarm/releases/tree/master/aws/v11.4.0)

See the [docs page](https://docs.giantswarm.io/basics/ha-masters/) for details.
