### ISSUE TITLE
Generate CAPO templates with kubectl-gs

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#587]
## TODO

- [ ] `kubectl-gs template cluster` for `openstack` provider
- [ ] Make sure it executes webhooks for te generated templates

**Comment by yulianedyalkova** [comment]
@tfussell just for traceability - can you please add a comment here to explain what will unblock this issue?

**Comment by ericgraf** [comment]
Thomas just released changes in v1.55.0 of kubectl-gs
