### ISSUE TITLE
AWS: Spot Instances

### ISSUE THREAD

**Issue by J-K-C** [giantswarm/roadmap#59]
## User Story

- _As a cluster admin, I want to configure a node pool in my cluster on AWS to use EC2 Spot Instances instead of on-demand instances, to safe some cost._

## Scope

- Cluster admins, when creating a new node pool in a tenant cluster, should be able to set these options:
  - on-demand base capacity: Number of worker nodes which should always be based on on-demand instances
  - spot percentage: The percentage of worker nodes (above the base capacity aforementioned) which should be using spot-instances. This is directly related to the AWS ASG setting usually referred to as "On-Demand percentage over base capacity".
  - Using similar instance types: To increase the likelihood of getting spot instances, this widens the range of instance types to use by the auto scaling group. E. g. if customers select `m5.2xlarge`, this would also enable `m4.2xlarge`. This option is independent of the other two above, so can be used independent of spot instances.
- Node pool details exposed via the web UI and the CLI (gsctl) should inform about the actual number of spot instances in use in each node pool.

The settings above cannot be altered via the Rest API after node pool creation. They MAY be altered via the Control Plane Kubernetes API, by modifying the respective custom resource(s) (TBD).

## References

- [AWS info section on EC2 Spot Instances](https://aws.amazon.com/ec2/spot/)

**Comment by marians** [comment]
FYI: The scope in the main comment has been updated.

**Comment by marians** [comment]
We just shipped support for Sport Instances with [AWS release v11.2.0](https://github.com/giantswarm/releases/blob/master/release-notes/aws/v11.2.0.md).
