### ISSUE TITLE
Integrate vault with opsctl

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#591]
We need to make CAPO vault setup work with:

- `opsctl create vaultconfig`
- `opsctl secret encrypt`

**Comment by cornelius-keller** [comment]
@kopiczko  do you want to keep this issue as it is specific to the new vault setup, or are you fine handling this in https://github.com/giantswarm/roadmap/issues/643?

**Comment by kopiczko** [comment]
IMO #643 should be split further and closed. And that one kept. That could help with working on this in parallel.

**Comment by yulianedyalkova** [comment]
Vault is currently not reacheable from the outside world so `opsctl create vaultconfig` doesn't make a lot of sense. In Openstack world this would be replaced by `opsctl vault run <command>` which will take care of vault tokens etc. 

More context [here](https://gigantic.slack.com/archives/C01BYMF6RN0/p1643884356143369).

**Comment by tfussell** [comment]
Secret encrypt/decrypt is done with the PR linked above. Create vaultconfig doesn't seem necessary for now. Closing.
