### ISSUE TITLE
Investigate the interaction of GitOps and defaulting/spec updates

### ISSUE THREAD

**Issue by tfussell** [giantswarm/roadmap#595]
- [ ] Check if Flux will not try to wipe out the value of `spec.controlPlane.endpoint` in the Cluster CR if:
- the value is defaulted by CAPO controllers
- not set in desired manifest in GitOps repo

**Comment by cornelius-keller** [comment]
@tfussell  is this still a todo or is it solved within the GitOps / CAPI releases working group?
