### ISSUE TITLE
Expose metrics for `azure-scheduled-events` app and add alert if app is down

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#612]

**Comment by whites11** [comment]
The new version of the app (0.5.0) is released and will be part of the next azure release.
This ticket is blocked until we have the release out and we can work on the alert with some data to work with.

**Comment by alex-dabija** [comment]
Blocked until we have Azure v16.1.0 out.

**Comment by whites11** [comment]
We should have data now, we can work on the alert.

**Comment by whites11** [comment]
alert is deployed
