### ISSUE TITLE
Extend RBAC operator to work in a shared installation

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#614]
**Is your feature request related to a problem? Please describe.**

Now our trials and prospect use a shared installation for the management API. We have not fully supported it yet and RBAC has to be created manually.

**Describe the solution you'd like**

RBAC operator is able to create role bindings for different tenants in the same installation. Right now it create role bindings for all organizations and clusters.

**Describe alternatives you've considered**

**Additional context**

**Comment by anvddriesch** [comment]
We will refine this in rainbow. Meanwhile @pipo02mix, do you have a priority on this?

**Comment by pipo02mix** [comment]
No urgent :)

**Comment by anvddriesch** [comment]
With the current state of rbac-operator, we can do the following.
- not set a customer global admin group (the same as we do in our test installations)
- create roleBindingTemplates for each customer with a label matcher that will give access to the organizations that carry the customers label.

**Comment by gawertm** [comment]
not needed anymore bc of rolebinding templates
