### ISSUE TITLE
Use Crossplane on the management cluster

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#615]
Crossplane would enable users to start cloud services next to the clusters via the management api.

The crossplane CRDs will extend our management api and allow users to manage additional cloud provider services and infrastructure next to our clusters. This would remove the need to use Terraform and instead use GitOps only.

Typical scenarios would be:
 * Add a gateway to a cluster to connect to the customers onpremises datacenter
 * Add a database/mq/storage service from the cloud provider next to the cluster (probably more useful within the workload cluster)

Links:
 * https://crossplane.io/
 * https://crossplane.io/docs/v1.6/api-docs/overview.html

**Comment by teemow** [comment]
fyi @giantswarm/team-rainbow

**Comment by teemow** [comment]
Another idea how to move on with crossplane could be this: https://github.com/giantswarm/roadmap/issues/1073

**Comment by puja108** [comment]
Moving to Honeybadger for now as Phoenix is still busy and Honeybadger might see more use cases right now in relation to other GitOps and Delivery use cases.

**Comment by gianfranco-l** [comment]
https://github.com/giantswarm/giantswarm/issues/21832#issuecomment-1165326373

**Comment by gianfranco-l** [comment]
closed in favor of [this](https://github.com/giantswarm/giantswarm/issues/23903)
