### ISSUE TITLE
Adapt CRD docs to support CRDs from multiple source repositories

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#616]
We have started an effort to untangle dependencies, bringing CRD/type definitions into the operators owning them.

PR https://github.com/giantswarm/apiextensions/pull/846 removes some CRD definitions from the apiextensions repository which have been added to the corresponding operators.

In order to keep our [CRD documentation](https://docs.giantswarm.io/ui-api/management-api/crd/) up-to-date, we must change the way we generate the content.

### TODO

- [x] https://github.com/giantswarm/crd-docs-generator/pull/80
- [x] Pull in https://github.com/giantswarm/apiextensions-application for app resources

**Comment by tfussell** [comment]
Discussed in the `apiextensions-application` PR including the code that would need to be changed: https://github.com/giantswarm/apiextensions-application/pull/1#discussion_r755099133

**Comment by marians** [comment]
@tfussell Currently https://github.com/giantswarm/apiextensions-application contains CRDs which are also still available in the latest release of https://github.com/giantswarm/apiextensions.

I'd like to build crd-docs-generator in a way that each CRD can exist only once. I'm assuming that the goal is to have a single source of truth for each CRD.

For now I will make it so that the repository that adds a CRD first (based on the repo sequence in the config file) will win. A warning will be printed if another repo tries to create a page for the same CRD. giantswarm/apiextensions will be configured as the last repo.

**Comment by tfussell** [comment]
> @tfussell Currently https://github.com/giantswarm/apiextensions-application contains CRDs which are also still available in the latest release of https://github.com/giantswarm/apiextensions.

@marians These were removed from `apiextensions` two days ago in https://github.com/giantswarm/apiextensions/pull/846 so we just need a new release of `apiextensions`, v4.0.0.
