### ISSUE TITLE
Events on the management cluster

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#618]
* Explain how to subscribe to events
 * Explain all the events we have on MCs
 * Check if we need to add more events
 * How do we visualize the events (Exporter, UI)

One use case raised: On events like cluster upgrade completed, cluster creation completed (etc.), then changing cluster status in internal (customer) status pages

**Comment by LolloneS** [comment]
What's the expected outcome of this issue?

**Comment by LolloneS** [comment]
@teemow is there something to be done regarding this issue, or can we close it?

**Comment by teemow** [comment]
Thanks @LolloneS. Added it to the horizon board. Imo this is still valid and needs further refinement. But no priority atm.

**Comment by JosephSalisbury** [comment]
i've also removed it from the rainbow board
