### ISSUE TITLE
lock down athena on OpenStack MC

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#621]
- [ ] Route traffic to Openstack  MC subnet via VPN 
- [ ] renable whitelisting for gs VPN in athena

**Comment by gawertm** [comment]
@cornelius-keller is it still relevant?

**Comment by cornelius-keller** [comment]
Yes I think so. We had other customers not feeling comfortable with having this information publicly accessible.

**Comment by cornelius-keller** [comment]
Not relevant anymore as we don't stop work on openstack
