### ISSUE TITLE
Allow `1.x.x` overwrite in `config-controller`

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#626]
Capo MCs are dynamic and we use `giantswarm/config` "auto" branches (in format `INSTALLATION_auto_config`) to not pollute `main` with commit flood.

But that doesn't work with release apps that have installation specific overwrites as by default `config-controller` takes latest `1.x.x`. We can't use `config.giantswarm.io/version` in Chart.yaml because that would work with only single installation.

Possible solution here is adding a flag to make `config-controller` replace `1.x.x` with custom ref.

**Comment by kubasobon** [comment]
`config-controller` will die in the future, so my approach is add anything to your heart's content.

**Comment by cornelius-keller** [comment]
Closing. Reopen if needed.
