### ISSUE TITLE
Investigate if ClusterClass works in CAPO

### ISSUE THREAD

**Issue by tfussell** [giantswarm/roadmap#627]
From https://gigantic.slack.com/archives/C01BYMF6RN0/p1638543385067000

- [ ] Understand ClusterClass setup (Marcel can help)
- [ ] See what is needed to be able to use the feature on our MCs
- [ ] See if it works for CAPO out of the box, there were some changes required for CAPA AFAIK

**Comment by cornelius-keller** [comment]
@tfussell  do we still need this issue?

**Comment by cornelius-keller** [comment]
Closing as this is solved else where
