### ISSUE TITLE
Refactor how to get clusters in kubectl-gs

### ISSUE THREAD

**Issue by njuettner** [giantswarm/roadmap#644]
### Description

When running `kubectl-gs` it uses internal calls to get Cluster CR's together with the Infrastructure CR (Azure / AWS). This leads to a problem of always adding the provider flag for each subcommand even if you wouldn't need it.

An example is updating a cluster, updates are set on the Cluster CR, no provider information is needed.

Lines of code which needs to be changed: https://github.com/giantswarm/kubectl-gs/blob/master/pkg/data/domain/cluster/common.go#L30-L54

For getting Cluster CR's we can use the same label `clusters.cluster.x-k8s.io` for selecting clusters. The label is already ensured on all clusters in AWS and Azure.

### TODO

- [ ] Decouple fetching Cluster CR's from Infrastructure (Provider) CR's

/cc @marians

**Comment by marians** [comment]
Note: this is about removing the need for a `--provider` flag in `update cluster`.

**Comment by weatherhog** [comment]
@njuettner is still valid?
