### ISSUE TITLE
Meaningful alerts based on cluster labels

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#645]
As a GS engineer, 
I want to receive meaningful alerts based on cluster labels 
so that I can increase operational efficiency and productivity

Dependency: having clusters with labels, related issue [here](https://github.com/giantswarm/giantswarm/issues/15687)

**Comment by snizhana-dynnyk** [comment]
closing as a dupe of https://github.com/giantswarm/roadmap/issues/688
