### ISSUE TITLE
Test critical apps as part of a new release process

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#651]
As part of e2e test let's try and install critical apps (especially those that deal with the kernel) to ensure they are still working.

For now add:

- falco

**Comment by alex-dabija** [comment]
Team HoneyBadger has plans to enable the testing of apps with new releases. In January 2022 will reevaluate the priority of this after the GitOps topic is done.

**Comment by alex-dabija** [comment]
Old issue. Our testing efforts will be only for CAPI and they are already in progress also for apps. More details are available [here](https://github.com/giantswarm/giantswarm/issues/30638).
