### ISSUE TITLE
Improve role list in access control UI

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#656]
Screenshot of the current (cluster) role list:

![image](https://user-images.githubusercontent.com/273727/146367553-0dd50f6c-00c3-4088-b28a-031d1d126731.png)

I'd like to improve the display to make it easier to see which roles are bound in the namespace and which aren't. Currently, the repetitive strings like `Groups: X    Users: Y` make that harder than necessary to find out. In addition, we don't show when a role is bound to a service account.

Here is my concrete suggestion:

- Use our subject type icons instead of textual labels `Groups`, `Users`, together with the number of these subjects bound. A tooltip should appear on mouse-over to explain the icon.
- If there is no subject of the given type, don't display anything.
- Do this for all subjects, including service accounts.

As a result, roles / cluster roles that are not bound should appear visually different from roles that are bound to any subjects.

For roles that are not bound we can reduce the item height.

**Comment by kuosandys** [comment]
As we'll be directing more users to the access control UI in `happa` with both internal (https://github.com/giantswarm/giantswarm/pull/21018) and external (https://github.com/giantswarm/docs/pull/1325) docs related to the access control epic, this might be a good time to bring some improvements to this UI. @PrashantR31 what do you think?

**Comment by PrashantR31** [comment]
Sure @kuosandys , let us plan this for our next sprint.
