### ISSUE TITLE
Make additional AWS x86_64 m4/m5/m6 instances types available

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#672]
Make additional AWS x86_64 m4/m5/m6 instances types available.

## M4 instance types:
- m4.10xlarge
- m4.16xlarge

## M5d instance types:
- m5d.xlarge
- m5d.2xlarge
- m5d.4xlarge
- m5d.8xlarge
- m5d.12xlarge
- m5d.16xlarge
- m5d.24xlarge

## M5n instance types:
- m5n.xlarge
- m5n.2xlarge
- m5n.4xlarge
- m5n.8xlarge
- m5n.12xlarge
- m5n.16xlarge
- m5n.24xlarge

## M5dn instance types:
- m5dn.xlarge
- m5dn.2xlarge
- m5dn.4xlarge
- m5dn.8xlarge
- m5dn.12xlarge
- m5dn.16xlarge
- m5dn.24xlarge

## M5zn instance types:
- m5zn.xlarge
- m5zn.2xlarge
- m5zn.3xlarge
- m5zn.6xlarge
- m5zn.12xlarge

## M5a instance types:
- m5a.xlarge
- m5a.2xlarge
- m5a.4xlarge
- m5a.8xlarge
- m5a.12xlarge
- m5a.16xlarge
- m5a.24xlarge

## M5ad instance types:
- m5ad.xlarge
- m5ad.2xlarge
- m5ad.4xlarge
- m5ad.8xlarge
- m5ad.12xlarge
- m5ad.16xlarge
- m5ad.24xlarge

## M6i instance types:
- m6i.xlarge
- m6i.2xlarge
- m6i.4xlarge
- m6i.8xlarge
- m6i.12xlarge
- m6i.16xlarge
- m6i.24xlarge
- m6i.32xlarge

## M6a instance types:
- m6a.xlarge
- m6a.2xlarge
- m6a.4xlarge
- m6a.8xlarge
- m6a.12xlarge
- m6a.16xlarge
- m6a.24xlarge
- m6a.32xlarge
- m6a.48xlarge

**Comment by AverageMarcus** [comment]
@njuettner Looks like there's some of the instances still missing the max pods calculation

- M5zn
- M6i
- M6a

**Comment by marians** [comment]
As [a user](https://gigantic.slack.com/archives/C01G30NGUS3/p1642411043003300?thread_ts=1642149749.000500&cid=C01G30NGUS3) pointed out, our [similar instance types](https://docs.giantswarm.io/reference/similar-ec2-instance-types/) list in docs should be updated, too.

**Comment by njuettner** [comment]
Updating docs with this PR https://github.com/giantswarm/docs/pull/1273
