### ISSUE TITLE
Encryption provider key rotation

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#677]
## User Story

_- As a cluster admin, I want the Kubernets API encryption provider key to be rotated in order follow security best practices._

## Details, Background
- [Encryption provider documentation](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/);
- [Encryption provider key rotation steps](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#rotating-a-decryption-key);

## Requirements
- Encryption provider key rotation should work the same way for all providers, including Cluster API clusters;
- Key rotation frequency should be externally configurable;

## Blocked by / depends on

None

**Comment by calvix** [comment]
The feature is done, it will be part of the was release 16.4.0 - https://github.com/giantswarm/releases/pull/910

**Comment by kopiczko** [comment]
FMI where is the rotation implemented?
