### ISSUE TITLE
Allow `core-dns` to run on the control plane nodes

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#679]
Background:

cluster-autoscaler runs on the control plane nodes to allow scaling workers down to 0. On AWS (at least) cluster-autoscaler relies on CoreDNS to resolve the endpoint for the AWS API, without it it is unable to scale any nodes. As CoreDNS is currently set to only run on worker nodes if a cluster has all worker nodes scaled down to 0 then cluster-autoscaler is unable to scale nodes back up and then requires manual intervention (and results in us being alerted).

---

Discussed in KaaS sync.

No hard technical reason not to run `core-dns` on control plane nodes. There are operational issues to be aware of though:
* `core-dns` should have a toleration for control plane nodes and not a preference for them. Where possible they should be scheduled onto worker nodes so that even if the control plane goes down (during an incident, upgrade, whatever) workloads should still continue to function.
* It needs to be made sure that the control plane nodes have enough "space" for core-dns to run on them and not prevent another critical pod from being run.

**Comment by calvix** [comment]
> On AWS the max pod amount would need updating to include this new (possible) pod for control plane nodes.

this does not make sense, we  only adjust the max pod size with pods that run as hostNetwork, but coredns do not run with hostNetwork so numbers should not be same

**Comment by calvix** [comment]
> It needs to be made sure that the control plane nodes have enough "space" for core-dns to run on them and not prevent another critical pod from being run.

that is the tricky part as we do not set limits for etcd and API  on CP node so there is no way how guarantee there will be space for the coredns in case of very busy control plane node

**Comment by AverageMarcus** [comment]
> > On AWS the max pod amount would need updating to include this new (possible) pod for control plane nodes.
> 
> this does not make sense, we only adjust the max pod size with pods that run as hostNetwork, but coredns do not run with hostNetwork so numbers should not be same

You're right, I was confusing things. Long day 😅 

---

Yeah, sizing isn't going to be easy but if the cluster is a busy cluster then there's worker nodes that core-dns can be scheduled onto.

---

An alternative thought (not sure I like it or not) is we could have a separate core-dns deployment that schedules a single pod on a control plane node.

**Comment by whites11** [comment]
I guess the only option we have is to implement our scheduler plugin extending the "score" extension point or maybe the "normalize score" extension point. Will investigate a bit further.

**Comment by whites11** [comment]
Alternatives:
- create 2 deployments, 1 for running on masters, 1 for running on workers.
PRO: easy to implement. No need to worry about moving coredns from masters to workers
CON: in clusters with workers, there will be coredns on the master anyway

- use a custom scheduler scoring plugin to prefer workers over masters
PRO: in clusters with workers, coredns should not run in the masters (but might)
CON: requires a new thing running in the cluster. Does not move pods from masters to workers.

- just add the toleration
PRO: easy to implement.
CON: coredns might run in masters only. does not move pods from masters to workers.

**Comment by calvix** [comment]
> create 2 deployments, 1 for running on masters, 1 for running on workers.
PRO: easy to implement. No need to worry about moving coredns from masters to workers
CON: in clusters with workers, there will be coredns on the master anyway



How will this look in regard to replicas count and the HPA? would there be only 1 replica on the master node which would have no HPA and then worker deployment would have replicas -1 and using the same HPA? 

We need to ensure that all naming for worker node deployment will stay so customers monitoring and  CI/CD wont be affected by the changes

**Comment by whites11** [comment]
> > create 2 deployments, 1 for running on masters, 1 for running on workers.
> > PRO: easy to implement. No need to worry about moving coredns from masters to workers
> > CON: in clusters with workers, there will be coredns on the master anyway
> 
> How will this look in regard to replicas count and the HPA? would there be only 1 replica on the master node which would have no HPA and then worker deployment would have replicas -1 and using the same HPA?
> 
> We need to ensure that all naming for worker node deployment will stay so customers monitoring and CI/CD wont be affected by the changes

Good points. I would keep the HPA just for the deployment running stuff in the workers. The one running on master is basically a fallback. There should be no issues with that I guess, right?

**Comment by calvix** [comment]
> Good points. I would keep the HPA just for the deployment running stuff in the workers. The one running on master is basically a fallback. There should be no issues with that I guess, right?

Probabbly no ;)
