### ISSUE TITLE
Web UI displays incorrect number of upgradable apps

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#680]
### Description
Seen on cluster `c68pn` on `gollum`:
<img width="474" alt="Screen Shot 2022-01-10 at 11 02 26" src="https://user-images.githubusercontent.com/62935115/148748303-c826cf58-19a9-4742-966a-13cc889da52c.png">

The number of upgradable apps displayed in the cluster details overview apps widget is incorrect. In this case, the  correct number of upgradable apps should be `2`.

This issue is related to https://github.com/giantswarm/roadmap/issues/647

**Comment by PrashantR31** [comment]
@kuosandys please add the new screen shot after the bug was patched. Thanks.

**Comment by kuosandys** [comment]
@PrashantR31 The only change is to the number of upgradable apps, so the number displayed in the cluster details > overview page matches the number of apps with the status "Upgrade Available" in the cluster details > apps tab:
<img width="475" alt="Screen Shot 2022-01-11 at 11 28 07" src="https://user-images.githubusercontent.com/62935115/148959284-19122fb4-6732-4512-9656-f3570e91cba5.png">
<img width="256" alt="Screen Shot 2022-01-11 at 15 17 42" src="https://user-images.githubusercontent.com/62935115/148959404-ef42e24e-242a-4c44-b0b1-021e67e081fa.png">

Btw the total number of upgradable apps is now `1` at the time of writing - hope the second screenshot clarifies the change!

**Comment by PrashantR31** [comment]
Cool nice one. Thanks @kuosandys for the screenshot.
