### ISSUE TITLE
Push cluster-apps-operator to openstack-app-collection on release

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#683]
User Story: 
- As a giant swarm developer I want to releases of cluster-apps-operator pushed to the openstack-app-collection on release, so that I am sure that the latest version is used on  openstack clusters.

**Comment by cornelius-keller** [comment]
@tfussell  this was created out of a note that you droped in team rockets inbox. can you provide more details to shorten refinement?

**Comment by tfussell** [comment]
@cornelius-keller `cluster-apps-operator` used to be deployed by `release-operator` so it was part of a release. Now it's in the `openstack-app-catalog` and needs to have a push to app collection step in https://github.com/giantswarm/cluster-apps-operator/blob/master/.circleci/config.yml so we don't have to update the app-collection manually after a new release of `cluster-apps-operator`.

**Comment by kopiczko** [comment]
@tfussell is it even needed anymore with default-apps-openstack?

**Comment by tfussell** [comment]
@kopiczko Yes, `cluster-apps-operator` will still be needed to create the cluster-values ConfigMap and Secret and manage app-operator and chart-operator App CRs.

**Comment by tfussell** [comment]
Done.
