### ISSUE TITLE
Write CAPO documentation 

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#684]
- [x] Capi arichitecture document and user documentation 
- [x] Product pages on web site

**Comment by pipo02mix** [comment]
For the website the work has been done and it is about to be published this week -> https://github.com/giantswarm/giantswarm/issues/22193

**Comment by pipo02mix** [comment]
I have a structure defined and I add some content to every section though I need to polish it

https://github.com/giantswarm/docs/pull/1291

**Comment by Oshratn** [comment]
@marians this is the ticket related to the note you left on the SIG Docs board for CAP-O documentation.
We have additional discussion topics reagrding this and you can catch up in the sync notes/recording.

**Comment by gawertm** [comment]
further tracked and enhancements in https://github.com/giantswarm/giantswarm/issues/23706
