### ISSUE TITLE
CNCF Conformance tests for CAPO clusters

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#686]
### User Story
- As a giant swarm customer I want CAPO clusters to be certified for CNCF conformance so that I know that they are conformant to the CNCF community standards

### Tasks
- [ ] Run CNCF conformance tests
- [ ] Submit CNCF conformance test results

**Comment by cornelius-keller** [comment]
#### Question for planning: 
- can we run CNCF conformance automated in CI/CD

**Comment by gawertm** [comment]
created generic issues for all CAPI providers https://github.com/giantswarm/roadmap/issues/1486
