### ISSUE TITLE
Link public dashboards to alerts

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#690]
### Rationale 

To promote creating/using dashboards and dogfooding (public dashboards) we can simplify the access to existing dashboards by linking them in the opsgenie alerts.

### TODO

- [x] provide a field in the alert so teams can add a link to grafana dashboards
- [x] document/ communicate

**Comment by hervenicol** [comment]
Communicated on Slack: https://gigantic.slack.com/archives/C0E0V16DC/p1671184509983909

@TheoBrigitte, do you want more communication? I let you see, then close this issue if it's all good for you.

**Comment by TheoBrigitte** [comment]
Good enough for me :+1:
