### ISSUE TITLE
Enable "port-range" feature for network policies in v17.0.0

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#695]
Enable "port-range" feature for network policies in v17.0.0 .

## Resources
- [Kubernetes Documentation: Targeting a range of Ports](https://kubernetes.io/docs/concepts/services-networking/network-policies/#targeting-a-range-of-ports);

**Comment by whites11** [comment]
This was alpha in 1.21 and beta in 1.22 so it should be enabled by default.
Will test it to check if our CNIs support it

**Comment by whites11** [comment]
Feature was introduced in calico 3.19, we're still on 3.15

**Comment by whites11** [comment]
tested with latest calico, works like a charm

**Comment by whites11** [comment]
Being able to test on AWS and merged the e2e test. closing
