### ISSUE TITLE
Support EKS clusters

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#697]
### Description

We want to start using EKS clusters. They use short-lived tokens instead of long-lived certificates. PMO currently does not support this. 

We reckon we'll have to watch the kubeconfig generated by CAPA controllers, and update Prometheus scrape configs as the authentication data changes.

### TODO

- [ ] Check if operatorkit supports watching multiple resources (i.e: Cluster CRs and kubeconfig secrets) - ask SIG Operator. If operatorkit does not support this, consider partially moving to kubebuilder (i.e: only informers, not resources)
- [ ] Add support to PMO to watch kubeconfigs created by CAPI controllers

**Comment by TheoBrigitte** [comment]
Closing this in favor of https://github.com/giantswarm/roadmap/issues/2670
Support for kubeconfig generated by CAPI controller is being worked on here https://github.com/giantswarm/roadmap/issues/2809
