### ISSUE TITLE
New CAPI Releases for CAPA

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#706]
Try new CAPI Releases for CAPA.

**Comment by calvix** [comment]
We will be using  
https://github.com/giantswarm/cluster-openstack/
and 
https://github.com/giantswarm/default-apps-openstack 
as a template for CAPA

**Comment by calvix** [comment]
following stories:
 https://github.com/giantswarm/giantswarm/issues/21298
 https://github.com/giantswarm/roadmap/issues/510

**Comment by MarcelMue** [comment]
Is this story now in a state where we can justify removing the Kyverno policies for CAPA?

**Comment by calvix** [comment]
@MarcelMue Yes, we still miss CAPA EKS but that is not the important thing atm
