### ISSUE TITLE
Try new CAPI Releases for CAPZ

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#707]
Try new CAPI Releases for CAPZ.

**Comment by AverageMarcus** [comment]
When creating the chart for CAPZ clusters please make sure to also include https://github.com/giantswarm/giantswarm/issues/19463 similar to CAPA (https://github.com/giantswarm/cluster-aws/pull/34)

**Comment by alex-dabija** [comment]
> @alex-dabija Is is accurate that this is currently not bring worked on? Would it be okay to still e.g. move the existing Kyverno rules to a branch?

Yes, this is not being worked on at the moment. Our current focus is on CAPG and CAPA.

**Comment by AverageMarcus** [comment]
Related ticket for when setting up CAPZ apps: https://github.com/giantswarm/giantswarm/issues/21408

**Comment by fiunchinho** [comment]
I think we can close this one @alex-dabija now that clippy exists.
