### ISSUE TITLE
Add monitoring for `prometheus-operator`

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#713]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [x] ensure it is scraped by Prometheus
- [x] ~make sure there are basic alerts~ not doing this scrapping is enough

**Comment by QuentinBisson** [comment]
Currently scraped by prometheus. After standup discussion, do we need alerting for prometheus operator and are we fine closing ?

**Comment by TheoBrigitte** [comment]
> @TheoBrigitte @JosephSalisbury Currently scraped by prometheus. After standup discussion, do we need alerting for prometheus operator and are we fine closing ?

Yes, let's not monitor prometheus-operator as we want to be alerted on causes and not symptoms.

**Comment by JosephSalisbury** [comment]
let's be specific here - we should have it scraped, we don't need to have alerts for prometheus-operator being down. right?
