### ISSUE TITLE
Add monitoring for `grafana`

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#714]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [x] ensure it is scraped by Prometheus
- [x] make sure there are basic alerts

**Comment by hervenicol** [comment]
:green_circle: Already scraped by prometheus

Alerts we can set:
* We have 1 grafana up per MC
* :bulb: idea: folder permissions are adjusted every 20 minutes

**Comment by hervenicol** [comment]
* `prometheus-rules` are updated on this PR: https://github.com/giantswarm/prometheus-rules/pull/326
* `ops-recipes` on this one: https://github.com/giantswarm/giantswarm/pull/21949
* That's deployed starting from `prometheus-rules` 2.16.0 - 2022-05-04
