### ISSUE TITLE
Add monitoring for Prometheus servers (that `prometheus-operator` creates)

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#715]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [ ] ensure it is scraped by Prometheus
- [ ] make sure there are basic alerts

**Comment by TheoBrigitte** [comment]
This was done in the scope of https://github.com/giantswarm/giantswarm/issues/19310
