### ISSUE TITLE
Add monitoring for `elasticsearch`

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#716]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [ ] ensure it is scraped by Prometheus
- [ ] make sure there are basic alerts

**Comment by QuentinBisson** [comment]
@TheoBrigitte do we still need that?

**Comment by TheoBrigitte** [comment]
This is no longer needed we have alerting in place for elasticsearch https://github.com/giantswarm/prometheus-rules/blob/705c475a213da90a0bc942946b5fc3bad6929399/helm/prometheus-rules/templates/alerting-rules/elasticsearch.rules.yml
