### ISSUE TITLE
Add monitoring for `promtail`

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#722]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [x] ensure it is scraped by Prometheus
- [x] make sure there are basic alerts

**Comment by QuentinBisson** [comment]
Scraped by prometheus:

```yaml
up{app="promtail-metrics", cluster_id="xg4e5", cluster_type="workload_cluster", container="promtail", installation="gremlin", instance="10.1.128.7:3101", job="xg4e5-prometheus/workload-xg4e5/0", namespace="promtail", node="xg4e5-master-xg4e5-000000", pod="promtail-224fw", provider="azure"}
```

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa can we close?

**Comment by QuantumEnigmaa** [comment]
Well, monitoring is working but I still haven't tested basic alerting for it.

**Comment by QuantumEnigmaa** [comment]
Monitoring and basic alerting is now setup so I think we can close the issue if you agree @QuentinBisson

**Comment by QuentinBisson** [comment]
Sure thing :)
