### ISSUE TITLE
Make sure that all prometheus targets are valid

### ISSUE THREAD

**Issue by ericgraf** [giantswarm/roadmap#725]
Currently list of unhealthy targets:

Workload clusters:

- [x] calico-node
- [x] kube-proxy
- [x] kubernetes-controller-manager
- [x] kubernetes-scheduler
- [x] workload
- [x] chart-operator
- [x] net-export

Management clusters:

- [x] calico-node
- [x] kube-proxy
- [x] kubernetes-controller-manager
- [x] kubernetes-scheduler
- [x] workload
- [x] chart-operator
- [x] ~~argocd-applications-controller~~
- [x] net-export
- [x] ~~config-controller~~

**Comment by kopiczko** [comment]
`kubernetes-controller-manager` and `kubernetes-scheduler` are stuck on https://github.com/giantswarm/cluster-resources-app/pull/3. I don't really have a great solution for that.

**Comment by kopiczko** [comment]
<img width="846" alt="Screenshot 2022-04-04 at 11 46 17" src="https://user-images.githubusercontent.com/4608994/161544101-d3d661bd-9b54-4fd0-ab50-11bd34ace341.png">

We also need to:

* fix bastions scraping
* replace docker metrics with containerd metrics
* remove vault

I think all of that can be silenced for now and we can resolve that after beta

**Comment by kopiczko** [comment]
Everything is checked and we have issues for the rest.
