### ISSUE TITLE
Azure MCs upgrades

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#726]
Azure MCs upgrades.

**Comment by whites11** [comment]
terraform 6.0.0. released

**Comment by whites11** [comment]
- [ ] ghost
- [ ] godsmack
- [ ] goku
- [ ] gollum
- [ ] gremlin
- [ ] icecream
- [ ] orion
- [ ] talos
- [ ] tuna
- [ ] victory
