### ISSUE TITLE
AWS MCs upgrades

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#727]
AWS MCs upgrades.

**Comment by whites11** [comment]
- [ ] k8s 1.21 => 1.22
- [ ] flatcar 2905.2.6 => 3033.2.0
- [ ] calico 1.10.1 => 1.10.1-nftables
- [ ] etcd 3.4.13 => 3.4.18

**Comment by whites11** [comment]
release 6.0.0 is out

**Comment by alex-dabija** [comment]
Remaining MCs have their own separate issues.
