### ISSUE TITLE
Investigate what is going on with `gorilla /4muwu`.

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#737]
Investigate why `gorilla / 4muwu` has so many alerts, over 600 for the past 30 days.

## Questions
* [ ] What's the purpose of this cluster?
* [ ] Who owns this cluster?
* [ ] What alerts are being triggered?
* [ ] Why are these alerts being triggered?
* [ ] Why was this cluster silenced for more that one year?
* [ ] What can be done in order to not have the alerts triggered?

**Comment by njuettner** [comment]
Customer do not require any monitoring as it's a test cluster and they watch
themselves. Aidan from Openet asked us to silence it.
