### ISSUE TITLE
Cleanup our cluster silences

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#738]
Configured silences need to be reviewed and the ones which are irrelevant need to be cleaned up (removed) in order to know which alerts are triggered the most and to make the [Alerts Analysis Dashboard](https://giantswarm.grafana.net/d/TBwN5ZzMk/alerts-analysis?orgId=1&var-team=phoenix&var-alertname=All&var-customer=All&var-provider=aws) useful.

**Comment by AverageMarcus** [comment]
- anteater-deu01-nodeconntrackalmostexhausted.yaml | Created by: Nick Jüttner | Created at: 30 Nov 2021.
 - anteater-fs6x5-whole-cluster.yaml | Created by: Nikola Prokopić | Created at: 26 Jul 2021.
 - anteater-nlbt1-whole-cluster.yaml | Created by: Nikola Prokopić | Created at: 26 Jul 2021.
 - anteater-odp01-whole-cluster.yaml | Created by: Nikola Prokopić | Created at: 26 Jul 2021.
 - bumblebee.yaml | Created by: paurosello pau@giantswarm.io | Created at: 16 Dec 2021.
 - exodus.yaml | Created by: Christian Bianchi | Created at: 21 Oct 2021.
 - flamingo-eco1d-kiam.yaml | Created by: Christian Bianchi | Created at: 05 Nov 2021.
 - flamingo-sha1d.yaml | Created by: Jose Armesto | Created at: 02 Dec 2021.
 - gorilla-4muwu-LatestETCDBackup2DaysOld.yaml | Created by: Nikola Prokopić | Created at: 26 Feb 2021.
 - gorilla-4muwu.yaml | Created by: Volodymyr Stoiko | Created at: 14 Jan 2021.
 - gorilla-ep9z8.yaml | Created by: Christian Bianchi | Created at: 06 Dec 2021.
 - gorilla-f3y8u.yaml | Created by: Christian Bianchi | Created at: 02 Dec 2021.
- gorilla-jh3s7.yaml | Created by: Jose Armesto | Created at: 02 Dec 2021.
 - gorilla-vu7r3.yaml | Created by: Christian Bianchi | Created at: 17 Dec 2021.
 - gorilla-y4hr4.yaml | Created by: Pau Rosello | Created at: 16 Dec 2021.
 - obi-csbox.yaml | Created by: Christian Bianchi | Created at: 03 Nov 2021.
 - obi-dev-clusters.yaml | Created by: paurosello pau@giantswarm.io | Created at: 05 Oct 2021.
 - talos-c9w6c-autoscaler.yaml | Created by: Christian Bianchi | Created at: 22 Dec 2021.
 - talos-e3cn8-cluster-autoscaler.yaml | Created by: Marcus Noble | Created at: 22 Nov 2021.
 - talos-e3cn8.yaml | Created by: Christian Bianchi | Created at: 01 Dec 2021.
 - talos-e4ga3.yaml | Created by: Tobiasz Kukawka | Created at: 16 Dec 2021.
 - talos-j6p3b.yaml | Created by: Christian Bianchi | Created at: 01 Dec 2021.
 - talos-silence-cordoned-np-migration.yaml | Created by: Tobiasz Kukawka | Created at: 04 Nov 2021.
 - viking-eks00-whole-cluster.yaml | Created by: Christian Bianchi | Created at: 06 Nov 2021.
 - viking-eks02-whole-cluster.yaml | Created by: calvix vaclav@giantswarm.io | Created at: 08 Nov 2021.
 - viking-eks03-whole-cluster.yaml | Created by: calvix vaclav@giantswarm.io | Created at: 12 Nov 2021.
 - viking-eks04-whole-cluster.yaml | Created by: calvix vaclav@giantswarm.io | Created at: 12 Nov 2021.
 - viking-hnq40-webhook.yaml | Created by: Nick Jüttner | Created at: 05 Jan 2022.
 - viking-naap2.yaml | Created by: Nick Jüttner | Created at: 26 Apr 2021.
 - viking-ue2ra-update-failed.yaml | Created by: Nick Jüttner | Created at: 22 Nov 2021.

**Comment by whites11** [comment]
- exodus.yaml => MC nodes are scaled to zero replicas, silence still needed
- flamingo-eco1d-kiam.yaml => customer is not using kiam and kiam is erroring because they have annotations for it anyway. If we remove the silence it will page constantly
- gorilla-ep9z8.yaml => deleted (cluster does not exist)
- gorilla-f3y8u.yaml => deleted (cluster does not exist)
- gorilla-vu7r3.yaml => deleted (cluster does not exist)
- obi-csbox.yaml => deleted (cluster seems to be running fine)
- talos-e3cn8.yaml => deleted (cluster does not exist)
- talos-e3cn8-cluster-autoscaler.yaml  => deleted (cluster does not exist)
- talos-j6p3b.yaml => deleted (cluster does not exist)
- viking-eks00-whole-cluster.yaml => EKS clusters, still valid

**Comment by whites11** [comment]
- anteater-fs6x5-whole-cluster.yaml => deleted (cluster does not exist)
- bumblebee.yaml => deleted already
- gorilla-jh3s7.yaml => deleted (cluster does not exist)
- obi-dev-clusters.yaml => deleted (pattern does not match any cluster)
- talos-silence-cordoned-np-migration.yaml => deleted (alert not firing in any of the clusters in talos)
- viking-eks02-whole-cluster.yaml => EKS clusters, still valid
- viking-eks03-whole-cluster.yaml => EKS clusters, still valid
- viking-eks04-whole-cluster.yaml => EKS clusters, still valid
- viking-hnq40-webhook.yaml => deleted (seems not to be firing any more)
- viking-naap2.yaml => deleted (silence very old; cluster is alerting we should take care)
- viking-ue2ra-update-failed.yaml => deleted (alert not firing any more)

**Comment by whites11** [comment]
- anteater-odp01-whole-cluster.yaml => deleted (not alerting any more)

**Comment by whites11** [comment]
- anteater-deu01-nodeconntrackalmostexhausted.yaml => deleted (alert not firing any more)
- flamingo-sha1d.yaml => deleted (according to slack, it was meant to last "until monday")

**Comment by whites11** [comment]
-  talos-e4ga3.yaml => deleted (cluster does not exist)

**Comment by whites11** [comment]
there are 2 clusters left, both on gorilla:

- `4muwu` => @njuettner will check it out as part of https://github.com/giantswarm/roadmap/issues/737
- `y4hr4` => asked partner what to do about it

**Comment by alex-dabija** [comment]
@alex-dabija Why do we have `y4hr4` ?

**Comment by whites11** [comment]
@alex-dabija I just deleted cluster `y4hr4` on customer request.
We can close this ticket
