### ISSUE TITLE
Keep  cloud-provider-openstack app up to date 

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#746]
We need to keep cloud provider app openstack up to date

**Comment by cornelius-keller** [comment]
@giantswarm/team-rocket do we still need this issue?

**Comment by erkanerol** [comment]
I think yes. We don't have any automation which updates our dependencies yet.

**Comment by bavarianbidi** [comment]
as occm doesn't change that often and releases are mostly done to support upcoming kubernetes versions i would propose the following for now:
1. track cloud-provider-openstack releases (if you use an rss-reader: `https://github.com/kubernetes/cloud-provider-openstack/releases.atom`) 
2. and create a version-bump-PR

As this is a general issue (with external manifests/containers) we could think about implementing/extending something like a `dependabot` which does most of this stuff automatically and then trigger some tests (create cluster, apply cloud-controller-manager, do stuff via k8s api which depends on cloud-controller-manager stuff - e.g. create a `pv`, create a service with type `Loadbalancer`, ...). But for this we should create a design-proposal (detailed RFC) - WDYT?

**Comment by cornelius-keller** [comment]
I think making it more generic and thinking also about how to keep all the other stuff up to date would be great. Team honeybadger has already some plans for this, I think we should hook in there. Please have a look at https://github.com/giantswarm/roadmap/issues/391#issuecomment-1096522248 and the corresponding epic https://github.com/giantswarm/giantswarm/issues/20641.

**Comment by kubasobon** [comment]
:wave: Hi, I'd be grateful if you could take a glance at https://github.com/giantswarm/rfc/pull/33. That's our proposed solution to automate App and CAPI cluster upgrades.

**Comment by kopiczko** [comment]
It isn't that simple because it's a part of [default-apps-openstack](https://github.com/giantswarm/default-apps-openstack/blob/7b901b21076168dcaa1b1a5473d6e8998e177e33/helm/default-apps-openstack/values.yaml#L46)
