### ISSUE TITLE
Support cluster-autoscaler for OpenStack

### ISSUE THREAD

**Issue by tfussell** [giantswarm/roadmap#747]
This may be able to be done in a provider-independent way using Cluster API. We should check if there's any upstream progress here.

### TODO
- [ ] use autoscaler on MC
- [ ] research if we can use it in the WC

**Comment by cornelius-keller** [comment]
https://cluster-api.sigs.k8s.io/tasks/cluster-autoscaler.html

**Comment by gawertm** [comment]
have a generic autoscaler issue
