### ISSUE TITLE
Managed Service: Image scanning

### ISSUE THREAD

**Issue by jgsqware** [giantswarm/roadmap#76]
Here just dropping though on creating an operator to manage CoreOS Clair.

The main features I see with this operator would be:

- Clair server reconciliation
- Watch Pods creation events and send analyze request for every new images
- Manage Notifications subscription

I think this can be useful for Managed Services, Julien's customer already ask if we can help them with Clair.

**Comment by snizhana-dynnyk** [comment]
@stone-z is this something that we do already with Trivy? can we close this then?

**Comment by stone-z** [comment]
Yep! We are already managing Trivy as part of the [managed security pack](https://docs.giantswarm.io/app-platform/apps/security/). I think we can close this
