### ISSUE TITLE
Unblock Intranet deployments

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#764]
In CircleCI the client certificate (stored in env variable KUBECONFIG_DATA) for intranet (repo giantswarm/giantswarm) deployments has expired. This broke automatic deployments.

See Slack thread: https://gigantic.slack.com/archives/C03FYAV8U/p1643360684740769

[This FAQ in the intranet](https://intranet.giantswarm.io/docs/intranet-faq/#how-is-the-intranet-deployed) explains how the intranet deployment currently works. It shows that `gsctl` and the REST API were used in the past to create kubeconfig with a client certificate that would expire after some time and had to be renewed periodically.

```
gsctl create kubeconfig \
  --endpoint gollum \
  --cluster c68pn \
  --cn-prefix intranet ...
```

`kubectl gs login` currently lacks an option to specify the CN prefix in a client certificate, so we don't have a direct replacement for the creation of the client certificate with a specific CN. (There is an RBAC rolebinding which enables the user `intranet...` to edit the intranet deployment).

## Quick fix

- Create an admin certificate (e.g. for a week) as a workaround

## Long term fixes

- (A) Enable `kubectl gs login` to specify the CN prefix, just like `gsctl` did.
- (B) Change the RBAC rolebinding in c68pn to bind to a group instead of a user; change certificate and intranet FAQ accordingly.
- (C) Move deployment automation to flux.

**Comment by marians** [comment]
I created a new certificate for a week. This means by Friday we should have a better solution or create a new certificate. Until then we are fine.

Here is the command I used:

```
$ kubectl gs login gollum \
  --workload-cluster c68pn \
  --certificate-ttl 192h \
  --certificate-group system:masters \
  --self-contained kubeconfig.yaml
$ cat kubeconfig.yaml | base64
```

**Comment by marians** [comment]
@giantswarm/team-honeybadger As you can read above, the intranet deployment pipeline just broke and this makes me wonder: can we use FluxCD to keep that deployment in cluster gollum/c68pn up-to-date? Would we need to have an intranet App for that and treat it like the other apps in workload-clusters-fleet? (Are there good reasons that it's not an app yet? If yes, what was it?)

**Comment by rossf7** [comment]
@marians I think migrating it to an app makes sense. 

IIRC the reason is because the intranet was created during a hackathon and it was faster to deploy this way.
See https://github.com/giantswarm/giantswarm/pull/10314#issuecomment-619818015

@puja108 Can you confirm?

We could have the chart in the giantswarm repo and call it `giantswarm-intranet` and then use the Flux image automation like we use for `docs`.

**Comment by puja108** [comment]
Indeed I was too lazy to create an app and saw the amount of changes to the Deployment as low. However, an app would still make sense as e.g. With the current way updating anything but the actual docsy container as well as any move between clusters would be a manual process.

**Comment by marians** [comment]
We have wanted to make the Intranet a proper app for some time: https://github.com/giantswarm/giantswarm/issues/19038 So I'm closing this issue. Thanks!
