### ISSUE TITLE
Explain CN of workload cluster client certificates created via `kubectl gs login`

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#770]
Our explanation of the CN of a generated client certificate is not enough.

https://docs.giantswarm.io/ui-api/kubectl-gs/login/#workload-cluster

We should explain more explicitly that by default, the `O` and `CN` field of the certificate will be filled with random values like 

    Subject: O=73ce775d904da53e, CN=73ce775d904da53e.c68pn.k8s.gollum.westeurope.azure.gigantic.io

Currently only the `O` part can be influenced by the user via the `--certificate-group` option.

This could be improved both in docs as well as in the usage info.

**Comment by PrashantR31** [comment]
Docs were created and PR is linked.
