### ISSUE TITLE
Client certificate CN prefix in kubectl-gs vs. gsctl

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#771]
Client certificates created via `kubectl gs login` for workload cluster access differ in several ways from the ones created by `gsctl`.

### kubectl-gs

Currently `kubectl gs login` when creating a client certificate for workload cluster access creates CNs like this:

    73ce775d904da53e.c68pn.k8s.gollum.westeurope.azure.gigantic.io

The string `73ce775d904da53e` is a random string created individually by kubectl-gs for every certificate. Users have no way of influencing this part.

The rest is a combination of the workload cluster name, the string `k8s`, and then the installation base domain.

### gsctl

In contrast, `gsctl create kubeconfig` or `gsctl create keypair` would create CNs like this:

    marian@giantswarm.io.user.api.c68pn.k8s.gollum.westeurope.azure.gigantic.io

Here `marian@giantswarm.io` is the user ID of the user creating the certificate via the REST API. If used with `--cn-prefix`, this part is completely customizable.

Then comes `.user.api.` as an extra namespace specification. The rest is the same as above.

## Questions

- Should we offer an option to influence the CN prefix in `kubectl gs login`, just like `--cn-prefix` in `gsctl create kubeconfig`?
- Are we fine with the other difference (the missing of `.user.api.` in the new certificates' CN)?

**Comment by PrashantR31** [comment]
Low priority at the moment.
One caveat and Decision: How deep should we go, can we just to to the level similar to `kubectl gs create config`

**Comment by anvddriesch** [comment]
Update: raised the priority since this is now blocking vodafone and it's urgent https://gigantic.slack.com/archives/C1R9481LZ/p1663752248078549?thread_ts=1663682577.825429&cid=C1R9481LZ

**Comment by marians** [comment]
@anvddriesch Docs https://docs.giantswarm.io/ui-api/kubectl-gs/login/ still need an update for this one
