### ISSUE TITLE
Control groups v1 machine pools

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#772]
## User Story

_- As a cluster admin, I want to mark specific machine pools control groups v1 enabled because certain applications don't have control groups v2 support yet._

## Details, Background

Control groups v2 are enabled by default with the latest Flatcar image, but some of our customers still run applications with old JREs (prior to v15). Unfortunately, they need more time to update their applications.

In order not to block all of our customers we've decided to use the latest Flatcar images with control groups v2 enabled by default and to offer the option of annotating specific machine pools to use control groups v1 for those customers which require more time to update their applications.

## Resources
- [Flatcar control groups v2 release notes](https://www.flatcar.org/releases/#release-2983.2.0);
- [OpenJDK control groups v2 issue](https://bugs.openjdk.java.net/browse/JDK-8230305);
- [Internal Slack thread](https://gigantic.slack.com/archives/CNHMVT6LW/p1642520110004500);

## Changes

- Custom annotation to mark a machine pool to use control groups v1;
- Control groups are enabled by default for any other machine pool which is not annotated to use control groups v1.

**Comment by calvix** [comment]
done, change is part of release `17.0.0-alpha1` for both was and azure
