### ISSUE TITLE
Optionally attach existing network to capo cluster

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#773]
#### User story
- As a customer I want to attach my cluster to an existing network so that I ´use preconfigured networks in my cluster. 

#### TODO 

- [x] change cluster-openstack app templace to optionally support  attaching existing networks
- [x] add an optional parameter to kubectl-gs templating commnand 

See: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/book/src/clusteropenstack/configuration.md#network-filters

**Comment by erkanerol** [comment]
To be able to do it, 
- network must be created 
- subnet must be created
- there must be a router which connects the subnet with the external network so that CAPO can attach a floating IP with a port in the subnet.

Example commands for achieving the state above:
``` bash
openstack network create net-0

openstack subnet create subnet-1 \
  --subnet-range "10.6.1.0/24" \
  --allocation-pool "start=10.6.1.2,end=10.6.1.254" \
  --dhcp \
  --gateway "10.6.1.1" \
  --network  "net-0"


openstack subnet create subnet-2 \
  --subnet-range "10.7.1.0/24" \
  --allocation-pool "start=10.7.1.2,end=10.7.1.254" \
  --dhcp \
  --gateway "10.7.1.1" \
  --network  "net-0"



openstack router create router-1
openstack router set  router-1 --external-gateway cdbcb519-1f91-43fb-b0a9-312f0abf8f12
openstack router add subnet router-1 subnet-1
openstack router add subnet router-1 subnet-2

```

And then network+subnet must be set in specs as https://github.com/giantswarm/cluster-openstack/pull/50/files

**Comment by cornelius-keller** [comment]
Things to consider:
- Routes for VPN
- Subnet allocation is not automatic 
- advise to  use load balancers

**Comment by nprokopic** [comment]
Is this a user story for all CAPI clusters, i.e. for all providers, or specifically for CAPO?

**Comment by erkanerol** [comment]
@nprokopic This is for only CAPO.

**Comment by erkanerol** [comment]
PRs are merged. Moving this to DONE.
