### ISSUE TITLE
create a shared app collection for CAPI Managment clusters

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#774]
### User Story 
- As a GS developer I want all provider independent GS apps on MCs to be manged in the same collection, so that I am sure that all MCs are in the same state.
- As a GS developer I want all provider independent GS apps on MCs to be manged in the same collection, so that setting up new providers becomes easier. 

### TODO 
- [ ] create shared app collection for CAPI MCs
    - [ ] agree on name

**Comment by cornelius-keller** [comment]
Decissions from planning:
- we drop the push to app--collection step 
- we use renovate to create PRs to the app collections

**Comment by tfussell** [comment]
Following https://github.com/giantswarm/giantswarm/issues/21820, don't use shared-app-collection on KVM.
