### ISSUE TITLE
improve dns-operator-opoenstack-finalizer

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#782]
dns-operator-openstack finalizer not removed when WC API never becomes reachable and cluster is deleted (maybe check conditions?)

**Comment by yulianedyalkova** [comment]
I tried to reproduce this on `gamma` and couldn't - `dns-operator-openstack` succesfully removed the finalizer both when the API IP is not yet populated in the openstack cluster spec and when it is but it's not reacheable yet. I can see this being a problem before [this commit](https://github.com/giantswarm/dns-operator-openstack/commit/6c240f9e1e4de0f007dc0d53a1c32fae2146f5d1) but that shouldn't be the case anymore cause it just takes everything from the hosted zone and deletes it without interacting with the cluster. @tfussell did you see this recently?

**Comment by tfussell** [comment]
I couldn't figure out the problem, but I started on some improvements in https://github.com/giantswarm/dns-operator-openstack/pull/27 including logging which should help us track down future issues. I'll close this for now.
