### ISSUE TITLE
App catalog in web UI should recognize if an app is already installed in the current cluster

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#785]
To reproduce, on an SSO installation

1. Navigate to a details page of a workload cluster that has some apps installed
2. Go to the `Apps` tab
3. Click `Install app`
4. Open the app detail page for an app that is already installed in the cluster

This install button will appear: 

![image](https://user-images.githubusercontent.com/273727/152133771-c7567eae-a122-4730-b00b-f76ec8ea8b3d.png)

This is confusing to users, as it indicates that the app is not installed in the current cluster (the cluster navigating from).

I'm sure we had a mechanism in place in the past to not show the install button in this case. Looks like a regression to me.

**Comment by kuosandys** [comment]
I don't think we had this feature actually (or at least there isn't anything in the codebase to suggest we did) though it definitely sounds like we should!

Coming from the cluster detail > apps tab, it would involve fetching the list of apps installed in the current selected cluster.

In the case where a user navigates directly to the app installation page (i.e. no cluster has been selected), we display a list of clusters in the modal for them to choose from. Here, we would have to fetch the lists of installed apps from every cluster to determine which clusters already have the app installed. Depending on the number of clusters the user can see, it could have some performance implications.

**Comment by PrashantR31** [comment]
Hii @kuosandys, 

Cool, specs :+1: 

1. I have a preference for: If the app is already installed in the cluster, we display the button as disabled, with the text "Installed in cluster foo12". In a single view action you can see the app is already installed and not need to  hover to see the tool tip.
2. I am also thinking to show "Uninstall App" if it is already install, if this makes sense to have it here.
3. Install app in other clusters is very handy as well. 

Question please: 

1. Do we have check boxes on the cluster selection form so as to select more than one cluster on which I want to install the app ? Then in one go, as a happa user I can install the app in all the selected clusters.
2. Do we know what will be the checks we are doing to know the app is installed ?

**Comment by kuosandys** [comment]
@PrashantR31
> I am also thinking to show "Uninstall App" if it is already install, if this makes sense to have it here.

Right now, we display the uninstall button for an app in cluster details > Apps tab, in the expanded details for each app. The app catalog’s purpose is to allow users to browse apps to install - displaying an uninstall button without the full context of a cluster deviates from this goal, and IMO could potentially be confusing.

> Do we have check boxes on the cluster selection form so as to select more than one cluster on which I want to install the app ? Then in one go, as a happa user I can install the app in all the selected clusters.

The flow after selecting a cluster from the list is to bring users to a form where they can configure the app being installed. If they select multiple clusters, and would like to configure the app differently for each, how would we display this? After confirming the installation, we also redirect the user to the cluster details > Appa tab showing the installed app. Which cluster do we choose to redirect to?

I think if we wanted to add this functionality, we would have to rethink “batched” actions within happa. It could be interesting to explore this, but I think it’s outside the scope of this issue.

> Do we know what will be the checks we are doing to know the app is installed ?

We would execute a request to list all the App CRs in a Cluster’s namespace. Then we would iterate through them to find the App whose name and catalog matches the AppCatalogEntry’s name and catalog. If there’s a match, the selected app is installed. If there is no “current cluster” selected, we would have to do this in every Cluster’s namespace.

I hope that answers your questions, please let me know if I could clarify anything further!

**Comment by PrashantR31** [comment]
Thanks for the clarifications, @kuosandys , I agree to all the arguments you have added.

**Comment by gianfranco-l** [comment]
as agreed during the Product SWH of March 3rd March, this task will temporarily remain in Rainbox until the teams "UX enablement" first iteration steps would be defined and implemented

**Comment by PrashantR31** [comment]
Hii @marians , please give @kuosandys a feedback on the Specs.

**Comment by marians** [comment]
@kuosandys and I discussed the spec and made some updates.

## Displaying the selected cluster

When installing an app in the web UI, we are working with the concept of a _selected cluster_. A cluster is selected in two ways:

- on a cluster details page, in the Apps tab, clicking the `Install app` button
- in the Install modal, click "Pick a different cluster" and choose a cluster to install an app into

Currently it's not visible on the app details page if there is a selected cluster and which one it is.

To make users aware of the selected cluster, we are introducing a new bar on the top of the app details page, right below the `< Back to apps` link, which appears only if the user has a selected cluster.

![image](https://user-images.githubusercontent.com/273727/161762353-33844e87-be0b-4126-a550-d5a321f52c7e.png)

The bar provides an `×` icon on the right. When clicked, the selected cluster is reset/erased/removed and the bar disappears. The page adapts to a mode where no cluster is selected.

## App details page

As the two wireframes below show, the app detail page header will appear different depending on the current app being installed in the selected cluster or not.

### App not installed

![IMG_0420](https://user-images.githubusercontent.com/273727/161761675-9bec97eb-429a-43f6-8491-07ea5b325b0c.JPG)

### App installed

![IMG_0419](https://user-images.githubusercontent.com/273727/161761755-59302cd3-fc1b-4ca0-accc-9ecff917528f.JPG)

## Apps list page

Out of scope for this issue, but certainly an improvement, would be to

- also show the selected cluster bar on the apps list page
- Indicate on the app car whether an app is installed in the selected cluster

![IMG_0421](https://user-images.githubusercontent.com/273727/161764132-a79d58cd-2d45-4494-b2f7-4023703592f1.JPG)

**Comment by PrashantR31** [comment]
OMG, I just love the paper sketch and some scissors work there and also the collaborative work that Figma brings. You are man @marians .

**Comment by gianfranco-l** [comment]
I agree with the proposed spec, great work thank you! @giantswarm/team-honeybadger any feedback on this spec? cc @piontec @rossf7

**Comment by piontec** [comment]
Looks reasonable.
