### ISSUE TITLE
Check quality for Dex App before it is pushed to GS Catalog

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#787]
Making sure that standards are being followed before pushing Dex App in GS Gatalog

**Comment by marians** [comment]
Current QA check result

### [dex-app](https://github.com/giantswarm/dex-app) (team-rainbow) -- 5 warnings

Information based on release v1.21.1

#### Warnings

- [ ] App name should not end with `-app`
- [ ] Annotation `application.giantswarm.io/metadata` should be set
- [ ] Annotation `application.giantswarm.io/readme` should be set
- [ ] Annotation `application.giantswarm.io/values-schema` should be set
- [ ] Repo giantswarm/dex-app should have a `CONTRIBUTING.md` file

#### Suggestions

- [ ] Migrate helm chart to apiVersion v2
- [ ] Specify `kubeVersion` attribute
- [ ] Use `dependencies` to inform about required apps/charts

**Comment by PrashantR31** [comment]
ping @giantswarm/team-rainbow , please pick up a task.
