### ISSUE TITLE
Release trusted kubectl gs (windows binary)

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#794]
As a Windows OS Users, I would like to install kubectl gs on my machine without any issues.

Some thoughts:
Cater for multiple CPU Architecture
Have at least latest 2 recent versions of WinOS Enterpsise

**Comment by PrashantR31** [comment]
Actions:

1. We have a certificate to sign the binaries
2. Add windows binary to Krew index data

**Comment by anvddriesch** [comment]
Closing since it is tracked here https://github.com/giantswarm/roadmap/issues/333
