### ISSUE TITLE
Run Dex in a more fail-safe way with multiple replicas

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#797]
Currently we run a single pod for Dex in the management cluster.

When management cluster nodes are rolled, the Dex pod is removed and authentication via Dex fails until the pod is rescheduled, which can take a "long" time.

It's possible ot run Dex with multiple replicas. The official Helm chart has a value [replicaCount](https://github.com/dexidp/helm-charts/blob/master/charts/dex/README.md) to configure the replica count, defaulting to 1.

**Comment by anvddriesch** [comment]
I just tried running two replicas of `dex` and it worked fine (Just had to add a pod anti affinity rule). Requests will be handled by one of the pods at random.
Let's talk about how we want to do this.
- Should replicas be configurable and set in `values`/`config`?
- Whether we do that or not, what should our default number of replicas be?
- Should we attempt to make `k8s-authenticator` HA, too? (I have neither tried nor checked if it's possible)

**Comment by PrashantR31** [comment]
next action:
For Dex: Having the configurations for 2 replicas with anti-affinity.
Let us revisit `k8s-authenticator` HA when we have issues.

**Comment by marians** [comment]
Let's not forget that this isn't released yet.
