### ISSUE TITLE
Add tests for `kubectl-gs login`

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#798]
We need tests for `kubectl-gs login` because there are too many things that can break at this point.
Note: current structure of the command is difficult to add unit tests - some refactoring needs to be done first

- [x] MC test
- [x] sort out circleCI
- [x] WC test
- [x] go through coverage and add additional test cases
- [x] go through coverage and add additional unit tests if needed

**Comment by PrashantR31** [comment]
Let us do a mini-refinement before we plan for other features to be added in kubectl gs
