### ISSUE TITLE
Port our changes to release-1.0 branch in our CAPI fork

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#799]
We have few changes that we have to port to every release-x.y branch, because releases are tagged only in those branches.

- CircleCI build config
- Adding back v1alpha2

**Comment by alex-dabija** [comment]
Moving back to our backlog because @nprokopic is on vacation.

**Comment by nprokopic** [comment]
Merged https://github.com/giantswarm/cluster-api/pull/18
