### ISSUE TITLE
Customer to test RO Happa users

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#800]
Given that RO users will be able to access the WebUI in RO as well, let us inform and demo that to the customers with whom we made our initial idea presentation or even to new customers.

What can we demo:

1. Show Happa Admin journey
2. Show Happa RO journey
3. The reasons why we have RO
4. What is coming next (e.g mixed permissions)

Then we ask the customer to test for a week or 2.

If we can find a solution to this issue: https://github.com/giantswarm/giantswarm/issues/17104 for Maik before the demo, that would be great.

**Comment by marians** [comment]
@PrashantR31 Let's use this one for tracking how to introduce fine-grained access control to customers, now that it's available.

**Comment by marians** [comment]
Here are our internal documents for customer session preparation:

- [Notes on what to talk about](https://docs.google.com/document/d/1rCow-Z0hTpa-HD7rEE7PmYP4tTn-k_oSoWpDOVjCACg/edit#)
- [Slides](https://docs.google.com/presentation/d/1IoyQCMtjEzX_lZPiN932yCCLE1QOvtNCDtuQDK8MoRs/edit#)

**Comment by PrashantR31** [comment]
Thanks @marians , @LolloneS was invited for a meeting we can show and discuss.

**Comment by PrashantR31** [comment]
My Bad, @marians I close this ticket, but let us leave it open to  track customer we presented Happa RO:

Below is the list of SSO Enabled customers:

1. FlexShopper
2. THG
3. FADI
4. GK Software
5. OBI
6. Orange
7. Vaillant
8 Egger (this week we will move to SSO)

**Comment by marians** [comment]
As we now have https://github.com/giantswarm/giantswarm/issues/21397 I think we can close this one.
