### ISSUE TITLE
Merge cluster-api-app CRDs to release-1.0 and master branch

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#801]
We are adding CRDs first to `release-0.3` branch in cluster-api-app (so we don't have too many changes and break our MCs), but we should merge them to `release-1.0` and `master` as soon as we have released v0.3.x.

- [x] Release v0.3.x.
- [x] Merge `release-0.3` back to master branch to get CRDs there.
- [x] Merge `release-1.0` back to master to get v1.0.x with CRDs in master, which will then be a new baseline for `release-1.1`. https://github.com/giantswarm/cluster-api-app/pull/37
- [X] Merge master back to `release-1.0`, so we get v1.0.x with CRDs that we will deploy to AWS and Azure MCs. https://github.com/giantswarm/cluster-api-app/pull/46

After all of this is done:
- We will have `master` branch with v1.0.x and CRDs in there.
- We will have `release-1.0` branch with v1.0.x and CRDs in there.
- We can start working on `release-1.1` and base it off of `master` branch.
- We can deploy v1.1.x to all providers.

**Comment by alex-dabija** [comment]
Moving back to our backlog because @nprokopic is on vacation.

**Comment by fiunchinho** [comment]
I think this can be closed now that this is merged https://github.com/giantswarm/cluster-api-app/pull/46
