### ISSUE TITLE
Standard app install instructions need update

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#802]
From https://github.com/giantswarm/template-app :

![image](https://user-images.githubusercontent.com/273727/153180268-06b07309-3074-4a9b-a13f-6168498bd190.png)

Several problems:

- "Using our API" points to the REST API docs. "Our API" should nowadays be understood as the Management API.
- The REST API is deprecated. The method should either be removed or moved to the bottom and marked as deprecated.
- The best place to learn how to install an app via the Management API is https://docs.giantswarm.io/app-platform/getting-started/#creating-an-app-cr

This should be changed in the template repo and in as many app repos as possible.

Changed for:
- [x] starboard-app
- [x] trivy-app
- [x] falco-app

**Comment by puja108** [comment]
@marians to create a PR for template and then ping app owners on "aligning files"

**Comment by marians** [comment]
The template-app README is updated. People can now update their app's READMEs according to https://github.com/giantswarm/template-app#installing
