### ISSUE TITLE
Decide for the right catalog(s) for apps representing Cluster API workload clusters

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#803]
Currently we have these apps published in the `Giant Swarm` catalog:

- cluster-openstack
- default-apps-openstack
- default-app-aws

These apps are needed to create Cluster API workload clusters on OpenStack or AWS respectively.

The purpose of the `Giant Swarm` catalog is to provide apps, which we as Giant Swarm manage and support, to be used in workload clusters by customers. The apps mentioned above exist for a different purpose.

The question: Which catalog(s) should be used for these apps?

Requirements:

- The catalog(s) MUST be visible to customer users

(please extend)

[Internal Slack thread](https://gigantic.slack.com/archives/C01F7T2MNRL/p1644417834980319)

**Comment by marians** [comment]
My current vote is to create provider-specific catalogs for this purpose. E. g.

- **OpenStack Clusters** (`openstack-clusters-catalog`)
  - cluster-openstack
  - default-apps-openstack
- **AWS Clusters** (`aws-clusters-catalog`)
  - cluster-aws
  - ...

etc.

**Comment by alex-dabija** [comment]
Decisions from KaaS Sync:
- the Cluster API applications will be moved to separate common catalog (owned by @giantswarm/team-phoenix and @giantswarm/team-rocket) FYI: we have a customer using the open stack apps;
- applications should be displayed based on the provider metadata (e.g. an AWS specific app must not be accessible on Azure clusters) (owned by @giantswarm/team-honeybadger or @giantswarm/team-rainbow).

Links:
- [Application metadata documentation](https://intranet.giantswarm.io/docs/product/architecture-specs-adrs/specs/managed-apps/2020-05-05-app-versions-representation/).

**Comment by piontec** [comment]
Provider metadata is already supported (as you mentioned, in the related docs). I think that from honeybadger's perspective all is ready and in place: we have metadata, we are able to enforce it (although I'm not 100% sure `app-admission-controller` enforces it right now - @rossf7 ?). If you need something more from us, let us know.

**Comment by rossf7** [comment]
Yes, app-admission-controller enforces it providing the AppCatalogEntry CR exists. Any problems let us know.

**Comment by marians** [comment]
OK, then let's add this action items explicitly:

- Add `.restrictions.compatibleProviders` metadata to the mentioned apps

**Comment by tfussell** [comment]
I propose that we close this issue in favor of our working issue https://github.com/giantswarm/giantswarm/issues/21059 as the decision has been made and the steps have been planned.

**Comment by marians** [comment]
Amen
