### ISSUE TITLE
[MC] AWS - upgrade china

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#814]
[MC] AWS - upgrade china

**Comment by whites11** [comment]
I tried deployng:

- flatcar without any ignition config
- amazon linux
- ubuntu 20.04

not even one of the VMs was reachable via SSH nor via web console.
I have no clue why this thing does not work.

**Comment by whites11** [comment]
as soon as I switched to a different VPC, everything worked immediately

**Comment by whites11** [comment]
it was a drift in the VPC config. I can access bastions now!

**Comment by whites11** [comment]
- [ ] giraffe
- [ ] akita
- [ ] argali

**Comment by whites11** [comment]
DONE
