### ISSUE TITLE
[MC] AWS - Drain nodes before rolling

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#815]
[MC] AWS - Drain nodes before rolling

**Comment by whites11** [comment]
We could use https://docs.aws.amazon.com/autoscaling/ec2/userguide/configuring-lifecycle-hook-notifications.html#sqs-notifications with a modified version of the `azure-scheduled-events` app

**Comment by whites11** [comment]
Also check https://github.com/aws/aws-node-termination-handler

**Comment by whites11** [comment]
First version of the app is ready, first version of terraform is ready.
Need to test upgrading from older releases to this one and creating a new installation from scratch.

**Comment by whites11** [comment]
- [ ]  akita
- [ ]  alpaca
- [ ]  anaconda
- [ ]  anchovy
- [ ]  anteater
- [ ]  antelope
- [ ]  argali
- [ ]  bandicoot
- [ ]  eagle
- [ ]  flamingo
- [ ]  fox
- [ ]  gaia
- [ ]  gauss
- [ ]  ginger
- [ ]  giraffe
- [ ]  gorilla
- [ ]  kudu
- [ ]  otter
- [ ]  tiger
- [ ]  valkyrie
- [ ]  viking
- [ ]  viper
- [ ]  visitor

**Comment by whites11** [comment]
no permission on `otter`

**Comment by whites11** [comment]
@paurosello we need to ask the customers owning the unticket MCs in the previous comment for the `sqs:*` permission in the Policy bound to the `GiantSwarmCD` role.
Can you please drive that?
Here is a possible request:

```
In order to make future management cluster upgrades more reliable and less disruptive, we would like to deploy an upstream component named `aws-node-termination-handler` (see https://github.com/aws/aws-node-termination-handler).
Such component uses the SQS service to automatically drain nodes being part of an ASG before the ec2 instance is terminated.
We kindly need you to grant us the `sqs:*` permission in the IAM Policy attached to the `GiantSwarmCD` role.
```

**Comment by whites11** [comment]
@paurosello I think we have already the needed permissions for a* clusters as both GiantSwarmAdmin and GiantSwarmCD have `AdministratorAccess`. At least for non-china installations.

**Comment by whites11** [comment]
Still waiting for permission from VF and BS to finally deploy in their MC as well

**Comment by whites11** [comment]
deployed everywhere
