### ISSUE TITLE
Use 20.04 Ubuntu image for CircleCI builds

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#817]
Use 20.04 Ubuntu image for CircleCI builds. The following repositories need to be migrated:
- [ ] azure-admission-controller
- [x] employees
- [ ] cluster-autoscaler-app
- [x] kyverno-policies
- [ ] metrics-server-app

**Comment by whites11** [comment]
I can't find the setting in `azure-admission-controller`

**Comment by whites11** [comment]
Also `cluster-autoscaler-app` and `metrics-server-app` don't use any machine executor so I have no clue why Circle is saying so.
I will close this ticket without touching those.
The worse that can happen is that CI will stop working eventually and we will notice it then,
