### ISSUE TITLE
Allow to create group names with spaces

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#818]
Description:
As a Happa user, I would like to create group names with spaces.

Currently, space is the delimiter on group names. Therefore the group name with space is split into different groups.

Actions:

1. To remove the space delimitation and chose another delimiter (e.g , or ; )
2. Update the message to indicate multiple groups can be created with the selected delimiter

**Comment by kuosandys** [comment]
Just ran into this limitation while demoing role binding creation on `icecream`, which has group names with spaces in them. I think with the changes to support making these bindings easily from happa already released with `rbac-operator`, this should be worked on next cc @PrashantR31 for next week's planning
