### ISSUE TITLE
Apps Compatibility Testing (prev. MVP: Generic Basic Testing for optional apps)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#82]
## References
* [Goals, General Workflow, Technical Ideas, Research Findings](https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#heading=h.yrqlb79flat9)

**User Story**
As an app developer, I want to easily see which platform releases my app is compatible with, so I can make sure my app works in real tenant clusters (not just kind/minikube).

1. When there is a new version of an app, compatibility is tested against all supported platform releases
2. When there is a new platform release, its compatibility is tested against all apps

MVP:
1. 3 installations, 1 per provider
	1. Check if we need new ones, maybe we can reuse current stables
2. Triggering events handling
	1. New app release (tagged commit in app’s repo)
	2. New platform release (new entry in releases repo?)
		1. Which versions of each app should we test against the new platform? For MVP - just the most recent one?
3. Test tenant cluster setup
	1. If a test dedicated cluster for specific provider and version doesn’t exist, create it
	2. If it already exists, reuse it, but queue the deployments to run only 1 at a time
4. Run helm deployment
	1. Includes helm tests
	2. Save all the logs (helm logs, pod logs)
5. Save result to helm index (catalog) repository
	1. Work on file format with batman

## References
* [Halo Compatibility Testing](https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#)

**Comment by yasn77** [comment]
Just some thoughts from [Slack](https://gigantic.slack.com/archives/CR99LSZ1N/p1583510322231500) transferred here...

For functional testing of Helm charts, we should probably look Helm testing hooks (https://helm.sh/docs/topics/chart_tests/). This can provide a pretty consistent way of testing apps across different clusters. Since the test hook is created as part of chart install.
In my mind the pipeline would look something like this:

`Chart lint and test on Kind (used for local dev and PRs) --> merge master helm test on GS clusters`

additionally

`New GS release ---triggers---> app repo to deploy and helm test`

This is of course if we go with what we discussed earlier and that we care about testing against GS release rather than components.
One nice thing about Helm test is that same testing logic can be applied to multiple clusters, and the app developer/owner can write tests that are applicable for that app.

How does pytest et al figure into all this? I see pytest as being  like glue and umbrella to easily run the tests

**Comment by yasn77** [comment]
@piontec As mentioned in the call just now, the comment includes a high level view of a pipeline. I think it would be good to expand on that and divide it into topics.

**Comment by piontec** [comment]
I started to work on that topic (and even wider) here: https://docs.google.com/document/d/1Z1oxIdwstH0Tno6YtH3vxiSkaBWxP6ra_T3-XcUY7BA/edit#heading=h.rv295k6xpf09

Please note that's a deep WIP. If you want to build a draft for complete build pipeline, let's keep it there, OK?

**Comment by piontec** [comment]
@cokiengchiara As the spec and planning is done and you put new tasks on boards, I think we can close this one, right?

**Comment by cokiengchiara** [comment]
> @cokiengchiara As the spec and planning is done and you put new tasks on boards, I think we can close this one, right?

I was thinking this is the "epic" that holds the other together, so we won't close it until they are all done. This is also the issue that is in the public roadmap board. But maybe I should update the contents to say, the real contends is in the doc 😅WDYT?

**Comment by piontec** [comment]
Yes, to me it was about docs, specs and starting the work. Maybe let's keep it like that and create a new epic issue and link it there?

**Comment by piontec** [comment]
Update 2020-03-13:
- I did another round of updates in the doc here: https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#heading=h.yrqlb79flat9
, after the round of calls we had this week about that topic.

**Comment by piontec** [comment]
Let's wait for research tasks outcomes to make another round of thinking and updating the doc

**Comment by cokiengchiara** [comment]
The spec is done. Create ticket for implementation. @piontec can you move your dropbox to github for implementation?

**Comment by cokiengchiara** [comment]
@piontec FYI, while talking to @MartaD about Halo having to test apps on k8s releases from now on, we discussed this issue. And she mentioned release testing efforts on Ludacris side. FYI just in case useful for this :) 

https://github.com/giantswarm/giantswarm/issues/8969
https://github.com/giantswarm/giantswarm/issues/11034

**Comment by cokiengchiara** [comment]
@piontec Once we do these: https://github.com/giantswarm/roadmap/labels/epic%2Fapps-compatibility-testing, will we already have Apps Compatibility Testing? Will it make tasks like this https://github.com/giantswarm/giantswarm/issues/11154 (cc @sslavic ) easier in the future?

**Comment by piontec** [comment]
ad 1) Yes, but still depends on the definition
ad 2) Yes, ultimately this should be an automated process.
