### ISSUE TITLE
Check if dex is running as root, can be running as non-root

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#831]
dex-app: `Set runAsUser to a non-zero number and runAsNonRoot to true in your pod or container securityContext`

**Comment by anvddriesch** [comment]
Added a securityContext to enforce nonRoot on top of existing PSPs.
Exchange with @stone-z on PSPs can be found here: https://gigantic.slack.com/archives/C02FJACQ3D4/p1645514475387429
