### ISSUE TITLE
Add support to rbac-operator to reconcile static resources

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#832]
~~We should not install static resources in rbac operator~~
We should add the relevant support to rbac-operator so that it can reconcile static resources.

**Comment by PrashantR31** [comment]
Example of static resource is a Role that has to exist on clusters and not created by Admins.

**Comment by PrashantR31** [comment]
1. We want to add it to rbac operator should ensure the consistence of the code over time
2. And refactor and and make more usable

**Comment by JosephSalisbury** [comment]
@PrashantR31 we also probably wanna update the description here, it's somewhat opposite of what the title says

**Comment by anvddriesch** [comment]
We discussed in refinement where the static resources should be reconciled.
We think that reconciling the default namespace in the same way as we do other namespaces but in a dedicated controller makes sense here.
This controller will ensure that resources in the default namespace and non namespaced resources are present.
the create action of this controller needs to be called once at startup to ensure referenced resources are present for other controllers (to avoid error on booting)
