### ISSUE TITLE
Alert on `core-dns` pods not working properly

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#849]
## Story

_*- As a cluster admin, I want to be alerted if a percentage of `core-dns` pods are not working properly (e.g. not responding to DNS queries) in order to have the `core-dns` deployment horizontally scaled based on cpu usage.*_

## Background
In a recent incident 50% of the `core-dns` pods were not serving any DNS requests, but all pods were seen as ready. This lead to the horizontal pod autoscaler not reacting to scale the deployment. CPU usage was very high for just 50% of the pods and when looking at the data as an average the horizontal pod autoscaler didn't see any need to scale out. The autoscaler did it's job as soon as the `core-dns` pods were fixed and serving requests, 

## Proposed changes
- add a new alert to identify if a certain percentage of `core-dns` traffic are not serving requests (or very few compared to the other pods);

## Questions
- [ ] What percentage should be used? 50%, 30%, ...? We could start with 20% and adapt.

**Comment by whites11** [comment]
This is the expected load given the number of replicas

```
100 /count(sum by (pod) (coredns_build_info))
```

**Comment by whites11** [comment]
This returns how much in percentage a pod is handling compared to what he should be handling

```
abs((sum by (pod) (rate(coredns_dns_requests_total[10m])) / ignoring (pod) group_left sum(rate(coredns_dns_requests_total[10m])) * 100) - ignoring (pod) group_left 100 / sum(coredns_build_info))
```

**Comment by whites11** [comment]
A dashboard to visualize data.

[coredns-load.txt](https://github.com/giantswarm/roadmap/files/8125092/coredns-load.txt)

**Comment by whites11** [comment]
Check if there is a difference between HPA metrics and number of pods scraped

**Comment by AverageMarcus** [comment]
@whites11 Unless I'm misunderstanding, doesn't this show that 1 pod ended up dealing with 100% of requests?

https://prometheus.g8s.antelope.sin.aws.k8s.3stripes.net/pap01/graph?g0.expr=sum%20by%20(pod)%20(rate(coredns_dns_requests_total%5B10m%5D))%20%2F%20ignoring%20(pod)%20group_left%20sum(rate(coredns_dns_requests_total%5B10m%5D))%20*%20100%0A&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=6h&g0.end_input=2022-02-16%2021%3A39%3A38&g0.moment_input=2022-02-16%2021%3A39%3A38

**Comment by whites11** [comment]
yes, but that's because there was only one replica.
otherwise the yellow line should have continued at "0", right?

**Comment by whites11** [comment]
Metrics as seen by HPA are different, but still not useful.
The "ghost" pods are not visible.

![hpa](https://user-images.githubusercontent.com/868430/155541729-f95ffbfa-78c4-451e-ad8b-f52b5e5be9dc.png)

**Comment by whites11** [comment]
OK this query seems to work

```
(sum by (pod) (rate(coredns_dns_requests_total[10m])) / ignoring (pod) group_left sum(rate(coredns_dns_requests_total[10m])) * 100) - ignoring (pod) group_left 100 / sum(kube_deployment_status_replicas{deployment=~"coredns|coredns-cp"}) > 20
```

It detects the incident pretty well

![alert](https://user-images.githubusercontent.com/868430/155712726-f7f46a4b-06b9-4c2f-a0e0-35d5cbec81c1.png)
