### ISSUE TITLE
Easier updating to upstream charts

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#85]
In theory, Batman. But as @yasn77 is already thinking about this, he might want to do it.

- [ ] [SPIKE] Evaluate extensions and alternatives

**Comment by yasn77** [comment]
At the moment I am dealing with this using a hacky script (https://gist.github.com/yasn77/cb0600bebb9237fbd73d7ca67b4ff211). The script basically checks for commit message of the last upstream sync, pulls in a release from Kong github page then replays all commits from the last sync.

By enlarge it works, but it's flaky... Still have to check changes as things could have been added or missed.

In regards to a more elegant solution, I think changes will have to be made to chart-operator. I am waiting for Helm3 support to be added, there could be a couple of tricks we could use with Helm3 that would help us keep in line with upstream.

The other option (not one I like), could be just to take the first cut from upstream and treat it as a fork. I am dubious about this approach as I think it will eventually either make us lag behind quite a bit and create extra overhead in regards to the management of the App.

**Comment by snizhana-dynnyk** [comment]
closing, the topic is in Honeybadger
