### ISSUE TITLE
Truncate  cluster/node pool names in happa

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#855]
Description:
Currently, there's a limit of 5 characters for cluster/node pool names fields from GS tools, but as we saw on otter , longer names are possible when created via other means, and break the UI display.

Conversations for more details:
This is the original thread referring specifically to happa: https://gigantic.slack.com/archives/C02FJACQ3D4/p1645543706408189 Note Marian's suggestion that this installation is used for the customer, who don't necessarily use happa .

There's also this newer thread that might be related the topic: https://gigantic.slack.com/archives/C01F7T2MNRL/p1645721486842749 This is about changing the length limit for these names in general, though I don't think a conclusion has been reached yet.

**Comment by puja108** [comment]
I think we need to first decide the length on a general KaaS (CAPI) level, once we have that we can move the fixes to UIs.

If the UI issues are significant, fine if rainbow wants to have a quick fix for in between, in general we should not be too dependent on exact length, but i can see that UI elements might need a bit more info than that.

**Comment by marians** [comment]
We can close this. Alex is going to create an issue for extending the restrictions based on today's discussion in the KaaS sync.
