### ISSUE TITLE
Happa on gorgoth loads clusters.cluster.x-k8s.io/v1alpha3 and fails

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#856]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/273727/155948566-c56cecb4-68e5-4b6d-aacb-9a49e4751f2a.png">

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/273727/155948987-50cb2954-9dcd-46c3-bc7d-75e1a77e9d65.png">

Seen on `gorgoth` (KVM). The problem doesn't occur on `gopher`.

**Comment by kuosandys** [comment]
I did a bit of investigating: for KVM installations, users logged in via SSO (i.e. GS staff) use the MAPI for organizations management. The MAPI UI for organizations is loaded as a result. However, cluster management with the MAPI is not supported, and any subsequent requests to list clusters for that UI (via the MAPI) should fail.

I think we're actually seeing the expected result on `gorgoth`. On other KVM installations, the request doesn't fail, but the list of clusters returned is empty.

Currently, this only affects GS staff on KVM, as customers there are not logged in via SSO.

**Comment by marians** [comment]
What I don't understand: why is there a difference between the installations? An empty list sounds like the desired response. A 404 error does not.

**Comment by kuosandys** [comment]
I’m not sure why there is a difference between installations. I saw [this change](https://github.com/giantswarm/apiextensions/pull/879), and from my understanding that meant `Cluster` CRs are not ensured for KVM installations any more, but maybe that was the wrong conclusion?
