### ISSUE TITLE
Happa RO - Create a blog and publish

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#859]
Happa RO is now available as a new feature, we will provide a blog for users so that they can start using the feature.
We will mention `dex` and `rbac-bootstrap` to show a complete implementation of SSO.

**Comment by PrashantR31** [comment]
Hii @morotki ,

We are preparing for a blog and would like to have a nice Generic Image in the header, in line with GiantSwarm look and feel.

The user story:
As a readonly user I can login in with Google, GitHub, Azure AD and can access only a few resources (one cluster for example)
Those accessible are colorful and the rest are not grayed

A representation like: 
https://www.lonimbus.com/assets/images/arch1.png 
or 
https://miro.medium.com/max/700/0*z7U342X85WxY1gFf.

Should be fine. But should should the user accessing only one cluster/box and not all.

Let me know if this request is feasible. 

Thanks.

**Comment by PrashantR31** [comment]
Template to follow for the blog post: https://docs.google.com/document/d/1h2tN4etf67tDTuqybikG3pPHEzmGswR1rfo0UR-TBBk/edit

**Comment by marians** [comment]
Writing the article draft here: https://docs.google.com/document/d/1snr8mTi8Gre4fVN-8ahhi1K8ABSbwQ4R6doBKYyTeG4/edit#

**Comment by morotki** [comment]
@PrashantR31 @marians thanks, do you have any ideas for the image? Normally Heather shares a little heads-up for me of what the image could look like / general idea. But if you don't have one it's also fine, we can do a more generic tech image showing the technology / application etc.

**Comment by marians** [comment]
@HelloHeatherC The team has reviewed [the draft](https://docs.google.com/document/d/1snr8mTi8Gre4fVN-8ahhi1K8ABSbwQ4R6doBKYyTeG4/edit#). Now to you: do you have anything we should improve? (Feel free to edit style etc. directly. I trust you!)

**Comment by HelloHeatherC** [comment]
@marians great minds! I was just about to ask you if I could start reviewing! Thanks for the trust, I'll leave suggestions if there are. ;-)

**Comment by HelloHeatherC** [comment]
Hi @marians you're such a natural writer, kudos! I've made mostly minor suggestions, feel free to accept/reject/query. I just ask for a chance to read again when there aren't my suggestions there as it's hard to give a final read with suggestions still there. Thanks!

**Comment by marians** [comment]
Thanks for the kind words! I applied all suggestions and also fixed the author bio :)

Next:

- Header image (Marat maybe)
- Screenshots (Marian)
- Maybe screen recording of the access control UI (Marian)

**Comment by HelloHeatherC** [comment]
Hi! Here's the preview for your review: https://www.giantswarm.io/blog/welcoming-more-users-to-our-web-interface-giant-swarm?hs_preview=mlZgoOge-67629692523

Please could you assist with the correct link for "Authorization in the Management API" in the sentence: 

For more detailed instructions on how to set up permissions for scenarios like these, check our new article Authorization in the Management API.

Please let me know if you have any other changes and also please share the screenshots that are missing.

**Comment by marians** [comment]
Here is the blog post: https://www.giantswarm.io/blog/welcoming-more-users-to-our-web-interface-giant-swarm
