### ISSUE TITLE
Support autocompletion for `kubectl gs`

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#861]
**Is your feature request related to a problem? Please describe.**

This customer request is NOT related to a problem. The desiderata is to be able to "tab" while using `kubectl gs` in order to get autocomplete.

**Describe the solution you'd like**

The ideal solution would be to have an autocompletion similar to [the one available in kubectl](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/)

**Additional context**

The priority is surely not really high. Still, both customers and people in Giant Swarm would enjoy having autocompletion in kubectl gs.

**Comment by marians** [comment]
Related: https://github.com/kubernetes/kubernetes/issues/74178

**Comment by LolloneS** [comment]
Hi, I see that we have `kubectl gs completion` as a command. Is that what we are referring to in this issue? If so, can we close this? @marians

**Comment by marians** [comment]
According to https://github.com/giantswarm/roadmap/issues/861 there is no support for completion of kubectl plugins.

That command is not usable.

**Comment by anvddriesch** [comment]
Let's look whether it is really not possible

**Comment by weatherhog** [comment]
seems to not be possible. closing

**Comment by marians** [comment]
With [cobra v1.8.0](https://github.com/spf13/cobra/releases/tag/v1.8.0) it might be that this became possible.

**Comment by weatherhog** [comment]
@marians do you want to keep this? there was no request since a long time for this

**Comment by marians** [comment]
Would still be nice to have, but I don't see us investing time into this.
