### ISSUE TITLE
Private clusters on CAPZ

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#864]
**Is your feature request related to a problem? Please describe.**

It is currently not possible to create private clusters, where "private" intuitively means "not publicly exposed" in any possible way. Of course we would still need some way to connect to it, but apart from that, it should be feasible to "isolate" the clusters as much as possible. An old issue for reference: https://github.com/giantswarm/giantswarm/issues/7557

**Describe the solution you'd like**

I would like to have the possibility to create private clusters. This means _at least_:
- no public IPs 
- no public storage accounts

In general, pretty similar to what you would expect from a private cluster on AKS, just with the usual GS flavor.

**Comment by teemow** [comment]
Here is the latest state of CAPA networking with private clusters.

![AWS Networking Setup (1)](https://user-images.githubusercontent.com/32488/167571805-c75eb68a-eced-4581-b4ba-193948a1671d.jpg)

**Comment by Rotfuks** [comment]
This is closed as duplication of https://github.com/giantswarm/giantswarm/issues/24763
