### ISSUE TITLE
Make user-values ConfigMap key configurable through App CR field

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#865]
Configuration of Apps is done by creating a ConfigMap with a `values` key containing helm values.

By adding a `key` field to the App CR spec, users would be able to specify a different key to contain helm values.

**Comment by johannges** [comment]
the obi usecase is, that this would allow us to use the kustomize configGenerator and have the Values in a seperate values.yaml file with syntax highlighting.

**Comment by johannges** [comment]
it would be a good idea to use the same syntax for new fields as in flux:
https://fluxcd.io/docs/components/helm/helmreleases/#values-overrides

**Comment by gianfranco-l** [comment]
@ljakimczuk

**Comment by ljakimczuk** [comment]
I'm working on a doc covering this for GitOps, I will come back here once we publish it

**Comment by ljakimczuk** [comment]
@johannges for the kustomize' generator you can specify the key in the generator itself, see of how we do it here https://github.com/giantswarm/gitops-template/blob/main/docs/add_wc_template_capi.md#create-versioned-base-optional (in step 9). So you may keep values in any file, but "generate" them under the `values` key anyway.

**Comment by MarcelMue** [comment]
@johannges We have also now written pretty comprehensive docs on how to use bases together with apps & configmap generator. You can check the different docs out here:
https://github.com/giantswarm/gitops-template/tree/main/docs/apps
