### ISSUE TITLE
Can't `docker compose up` in giantswarm/docs on M1 Mac because of missing ARM image

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#869]
### Description

Running `docker compose up` in https://github.com/giantswarm/docs/ results in an error from Docker because some images are missing the ARM version. 

```
[09:55:51] ➜  docs git:(main) ✗ docker compose up --quiet-pull
WARN[0000] The "HUBSPOT_API_KEY" variable is not set. Defaulting to a blank string.
[+] Running 0/6
 ⠏ indexer-blog Pulling                                                             2.9s
 ⠏ docs-app Pulling                                                                 2.9s
 ⠏ proxy Pulling                                                                    2.9s
 ⠏ indexer-docs Pulling                                                             2.9s
 ⠏ api-spec-app Pulling                                                             2.9s
 ⠏ sitesearch-app Pulling                                                           2.9s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

### TODO

- I _think_ images should be made "ARM-compatible". I don't know how much the effort is, but I believe that with a lot of people getting M1 Macs, this is going to become needed sooner or later.

**Comment by teemow** [comment]
@LolloneS this issue is in no projects. So maybe it fell through the cracks.

/cc @anvddriesch @marians

**Comment by marians** [comment]
I'd like to understand whether it's really necessary to have ARM images for M1 macs. Since the image build process relies pretty much on our common tooling (architect-orb), I can't even tell how easy it would be to build for ARM in addition.

I glanced over https://docs.docker.com/desktop/mac/apple-silicon/ and it looks like with Rosetta you can also run x64 images. Also it is mentioned that you should use docker-compose v2 at least for that.

**Comment by marians** [comment]
Marcus tested on M1 and found it to work when adding `platform: linux/amd64` to the elasticsearch service. Like this:

```yaml
sitesearch-app:
    image: elasticsearch:6.8.6
    platform: linux/amd64
```

@LolloneS If you could check whether that works for you, that would be great.

**Comment by LolloneS** [comment]
The `platform: linux/amd64` parameter works for me too. Thank you all for taking care of this!
