### ISSUE TITLE
Allow to display longer node pool names

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#871]
***Towards [Truncate node pool names in happa](https://github.com/giantswarm/roadmap/issues/855)***

### Description
This ticket is to continue a discussion about if we can give more space for the node pool name column, e.g. by shrinking some other columns.
> Does our layout allow for a limit at more than 5 characters, e. g. 10? The more we can show without breaking the layout, the better for the few customers who need it.

<img width="1231" alt="Screenshot 2022-03-01 at 18 27 05" src="https://user-images.githubusercontent.com/445309/156380984-b61a4df6-ec7a-4db5-a082-f9d1bc2dd8ee.png">

### TODO

- [ ] Investigate the possibility to shrink some columns without breaking the table layout.
- [ ] Increase "name" column width and amount of characters to display when a name is being truncated.

**Comment by PrashantR31** [comment]
Agreed in KaaS-Sync to used 10 Char
