### ISSUE TITLE
Support Image scanning via Flux 0.26

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#873]
Enable customers to use flux image scanning.
This requires image-automation-controller v0.20.0 to work properly, which is part of flux 0.26. 
Our flux-app is currently on flux 0.24. 

## TODO
- [x] review Flux upstream version 
- [x] update GS flux-app

**Comment by ljakimczuk** [comment]
Done with: https://github.com/giantswarm/management-clusters-fleet/pull/83
