### ISSUE TITLE
create `cluster-vsphere` app

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#875]
### User Story 
As a vmware user I want  a managed app that creates vsphere clusters so that I can use the app platform and helm to create clusters. 

### TODO
- [x] create a helm chart for vsphere clusters 

### Acceptance Criteria 
- [ ] API Server flags and Kubernetes Version can be updated via helm values.

**Comment by tfussell** [comment]
The helm chart is here https://github.com/giantswarm/cluster-vsphere

**Comment by glitchcrab** [comment]
done and released - it's available in the `cluster-catalog`.
