### ISSUE TITLE
Fix tests that fail on local machines

### ISSUE THREAD

**Issue by gusevda** [giantswarm/roadmap#878]
If you run tests in Happa project on a local machine you get some tests failing. The number of failed tests is different every run, and we don't have such problem on CI. We need to deal with this issue because it worsen dev experience.

<img width="515" alt="Screenshot 2022-03-07 at 12 08 05" src="https://user-images.githubusercontent.com/445309/157001481-04a18806-9aa6-4d09-881f-8c79842e481f.png">

**Comment by weatherhog** [comment]
closing
