### ISSUE TITLE
Make cluster creation easier and more reliable

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#880]
Currently, cluster creation for CAPO with kubectl is not supporting all needed configuration options. Also, it would be nice to have more defaults and fewer values to configure.

Ideas:
- have a helm values template file 
- have defaults in customer specific charts
- use app platform defaults
- configuration file for kubectl gs 
- do we need kubectl gs or is it easier for us and the customer to use helm 
- Use overloays (kustomize)

User stories

- As cluster-admin I would like to get a cluster template with the desired OpenStack version in an easy manner.
- As cluster-admin I would like to avoid entering the same default values when creating cluster resources.
- As cluster-admin I would expect the API complaints if I submit a cluster definition that has wrong values.
- As cluster-admin I would like to be alerted when a cluster creation failed for any reason.

**Comment by pipo02mix** [comment]
I have added User stories in main comment

**Comment by puja108** [comment]
Please do consult honeybadger (cc @gianfranco-l @MarcelMue as latter has put most work into the WC app design) on this. We should not forget that we have quite some power in app platform's 4 levels of configuration. For MCs that is: app/chart defaults, catalog/installation defaults, user config and there should even be a way to (mis-)use cluster level config for another "template" level (e.g. we could use it for project related stuff that is sub-installation level).

**Comment by pipo02mix** [comment]
@PrashantR31 has scheduled a meeting to talk about it

**Comment by cornelius-keller** [comment]
@gianfranco-l  @MarcelMue  does it makes sense to keep this issue in rocket? Do you want to take this issue to honeybadger  or are you tracking this already in an other issue?

**Comment by cornelius-keller** [comment]
Closing it then for rocket
