### ISSUE TITLE
AWS: use external cloud controller manager

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#888]
AWS: use external cloud controller manager.

- [x] Retag image for `aws-cloud-controller-manager`
- [x] Create managed app for `aws-cloud-controller-manager`
- [x] Retag image for `ebs-csi-driver`
- [x] Create managed app for `ebs-csi-driver`
- [x] Change settings in `kubelet`
- [x] Change settings in `controller-manager`
- [x] Change settings in `api-server`
- [x] Create app CR for `aws-cloud-controller-manager`
- [x] Create app CR for `ebs-csi-driver`

**Comment by whites11** [comment]
The EBS driver does not seem to work properly with old volumes even if it's supposed to.
The upstream documentation is asking to enable feature flags in the kubelet, but those flags do not exist. Maybe it's a k8s release version issue. Needs more investigation

**Comment by whites11** [comment]
Make coredns tolerate `node.cloudprovider.kubernetes.io/uninitialized: true`

**Comment by whites11** [comment]
ok deployed in `galileo`, will leave it running for a few days and check how it goes.

**Comment by whites11** [comment]
still trouble deploying PVs on master nodes because one label is missing from nodes and dunno why:

```topology.ebs.csi.aws.com/zone```

**Comment by whites11** [comment]
EBS CSI driver works, leaving it running for a few days

**Comment by whites11** [comment]
Deploying to AWS test installations:

- [ ] gaia
- [ ] gauss
- [ ] ginger
- [ ] giraffe

**Comment by whites11** [comment]
now deployed in 2 MCs. Will monitor state of such installations for a couple of weeks and move on with other installations if everything looks good

**Comment by whites11** [comment]
No problems on testing, going on with `gorilla`

**Comment by whites11** [comment]
Current situation:

- [x] gaia
- [x] gauss
- [ ] ginger
- [x] giraffe
- [x] gorilla

**Comment by whites11** [comment]
Deploying everywhere

- [ ] akita
- [ ] alpaca
- [ ] anaconda
- [ ] anchovy
- [ ] anteater
- [ ] antelope
- [ ] argali
- [ ] bandicoot
- [ ] eagle
- [ ] flamingo
- [ ] fox
- [ ] gaia
- [ ] gauss
- [ ] ginger
- [ ] giraffe
- [ ] gorilla
- [ ] gustavo
- [ ] kudu
- [ ] otter
- [ ] tiger
- [ ] valkyrie
- [ ] viking
- [ ] viper
- [ ] visitor
