### ISSUE TITLE
Cache Managed Application Container Images to avoid problems during registry downtime

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#89]
**Is your feature request related to a problem? Please describe.**

Based on the experience of the customer, once the container registry is down the cluster scale or creation fail as container images of basic components cannot be pulled.

**Describe the solution you'd like**

Cache the container images in an intermediate place (Control Plane) to avoid the hard dependency in a third provider 

**Describe alternatives you've considered**

Run a registry in each cluster with default basic container images

**Additional context**

**Comment by puja108** [comment]
We (Kubernetes Contributor Summit Orga Team) have been running "Harbor Boxes" with cached images set up IIRC as pull-through container registries for the New Contributor Workshops quite successfully. That might be a solution we could look at and learn from. Additionally, using Harbor, would enable us to set up some kind of peer2peer syncing (NOT between customers though), e.g. for getting our images also into China.

Anyway, as it does make sense towards a few possible user stories (and issues) you get my +1 here.

**Comment by puja108** [comment]
I think we had related issues in SIG releng, but without much priority. I would argue this might be within jurisdiction of the upcoming Control Plane team, but would like to hear out @snizhana-dynnyk and @JosephSalisbury on that.

**Comment by JosephSalisbury** [comment]
Yeah, I've already been assuming this was in the Control Plane team :D

**Comment by brinker211** [comment]
@pipo02mix as of yesterday this caused in issue. We will have talk with CP team or whoever is now handling.

**Comment by brinker211** [comment]
Hey Team as addon to the above - I heard from sstk's leadership yesterday (Huges) who is putting June 13 as a dropdead date because that is when quay is scheduled for maintenance. This is now a "must have" in sstk's eyes.

**Comment by snizhana-dynnyk** [comment]
thanks, @brinker211!  will bring this to the next planning

**Comment by snizhana-dynnyk** [comment]
The solution to a problem will be implemented in the scope of this roadmap story - https://github.com/giantswarm/roadmap/issues/164. The team is on it. Closing this as a duplicate.

See **#164 Fix Quay being a single point of failure** for more details.
