### ISSUE TITLE
Use VPA with falco-app

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#890]
On the management clusters we often see Falco being unable to schedule on certain nodes due to resource restraints. The default resource requests and limits are fairly high and often well above what we observe the pods making use of. 

To better ensure pods are scheduled and resources are used effectively it would be good to leverage a VPA to manage the resource requests rather than using the same defaults across all our management clusters.

(Related: https://github.com/giantswarm/roadmap/issues/889)

**Comment by stone-z** [comment]
VPA for Falco has been implemented in https://github.com/giantswarm/falco-app/pull/117 and released as of Falco app [version 0.4.1 ](https://github.com/giantswarm/falco-app/blob/main/CHANGELOG.md#041---2022-11-16)
