### ISSUE TITLE
Investigate issue with `m4` EC2 instance family

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#891]
We've noticed some issues in AWS related to the `m4` instance type family. Over the past couple days we've seen instances unable to boot up correctly due to network issues preventing them from pulling the userdata.

This doesn't seem to always be the case as we've seen instances come up successfully but it does seem that the issue occurs more often than not.

Right now we don't have a fix and we're currently thinking this might be an issue on AWS's side but haven't confirmed that yet. Currently the only solution we have is to modify the associated ASG to remove / replace the `m4` instance types with another suitable type.

---

### Investigation notes

* Amazon Linux and Ubuntu AMIs work fine
* Other instance types (such as `m5`) work fine with Flatcar
* Issue exists without any Kubernetes or Giant Swarm influence (launching a plain ol' EC2 instance with Flatcar AMI shows the issue)
* The issue doesn't always occur, we've seen a couple instances successfully launch but far more fail.
* Flatcar versions tested with: 
  * Flatcar Container Linux (Stable) - 3033.2.3
  * Flatcar Container Linux LTS - 2605.26.1
  * Flatcar Container Linux (Alpha) - 3165.0.0 (This one actually fails with a different issue: `Warning: /dev/disk/by-label/ROOT does not exist`)
* Tested with latest available Fedora CoreOS (35.20220205.10.1) which boots with Ignition without any issue

**Comment by AverageMarcus** [comment]
I've asked about this issue on AWS's public support forum: https://repost.aws/questions/QUQdYcE79bRkOdKEXiBbev3w/issues-launching-m-4-instances-with-flatcar-ami

**Comment by AverageMarcus** [comment]
This Flatcar version was introduced in release v17 so only those clusters that have upgraded to this release are effected.

**Comment by wincus** [comment]
I have also observed this behavior on c4 instances,  t2 instances seem like are unaffected by this issue ( instances boot normally )

**Comment by AverageMarcus** [comment]
Good to know! Thanks @wincus. 

It might be worth commenting on the flatcar issue so their team is aware also: https://github.com/flatcar-linux/Flatcar/issues/665

They're currently debugging it and seem to have pinned it down to a change in the Linux kernel.

**Comment by AverageMarcus** [comment]
Moving to blocked short term while waiting for upstream Flatcar to release a fix.

**Comment by AverageMarcus** [comment]
Issue fixed upstream. Now just waiting on new stable release next week.
