### ISSUE TITLE
Explain that SSO only permits one session per user and client.

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#895]
Update our documentation to explain that SSO only permits one session per user and client.
Ramifications on kubectl, or using multiple browsers/devices with the web UI.

**Comment by anvddriesch** [comment]
We have this but it can be improved https://docs.giantswarm.io/ui-api/kubectl-gs/faq/#what-does-error-token-renewal-failed-mean

**Comment by weatherhog** [comment]
closing
