### ISSUE TITLE
Alert if Kyverno is not running/responding

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#903]
Alert if Kyverno is not running and inhibit the other alerts.

**Comment by gianfranco-l** [comment]
ping @giantswarm/team-honeybadger

**Comment by MarcelMue** [comment]
I think this will be very hard to achieve. We can try but there are multiple things to overcome:
1. The information we get from Prometheus reflects Kubernetes which is already distorted if a webhook is broken.
2. We need to figure out how we can inhibit other alerts without editing all other possible alerts which currently exist.
3. It is currently not possible to inhibit ServiceLevel alerts - so these would pollute other teams at the least.

**Comment by gianfranco-l** [comment]
@alex-dabija after discussing this internally within the honeybadger team, "alert when kyverno is not running" is fine however the "inhibit other alerts" part is not trivial and we strongly suggest that the solution for that shall be researched by team honeybadger. WDYT?

**Comment by alex-dabija** [comment]
Do you know when you might have the time to research the inhibition of the other alerts? We would like to not get paged if Kyverno is not running as soon as possible.

**Comment by whites11** [comment]
We decided to begin with the alert only for now.
