### ISSUE TITLE
AWS Automatic node roll process

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#905]
Can we guard against a too aggressive node roll in the future (maybe this is just a process thing we need to tweak)

The control plane nodes need to be rolled sequentially.

https://docs.giantswarm.io/advanced/upgrade-disruption/

Let's try to have a shared API. The implementation might be different depending on how the machine pool is implemented.

**Comment by T-Kukawka** [comment]
We have editable defaults set to 10% of rollout

Thing left is the 'automated' node roll instead of manual

**Comment by T-Kukawka** [comment]
CAPI has automatic rollout so we do not consider in this implementation.

We will convey a SPIKE to investigate the possible solution. We already have upgrade strategies in both, aws and azure-operators hence we can adjust the implementation. There will be 3 possible places to put labels in:
-  Cluster CR
- AWSControlPlane/Azure(masters)
- MachinePools(nodepool)

**Comment by T-Kukawka** [comment]
SPIKE: https://github.com/giantswarm/giantswarm/issues/23534

**Comment by alex-dabija** [comment]
This is done.
