### ISSUE TITLE
What to do with dex-k8s-authenticator?

### ISSUE THREAD

**Issue by ghost** [giantswarm/roadmap#906]
dex-k8s-authenticator (for windows users) is looking for a maintainer and could end EOL and we should be thinking of replacing it.

We want to stick to our main objective i.e provide all features in `kubectl gs login` 

Notes:
Marian asked in the Kubernetes #dexidp for alternatives. https://kubernetes.slack.com/archives/C011URMR41W/p1647008866216019

Then it was found that an alternative exist already at https://github.com/vmware-tanzu/pinniped, which we could use as a replacement for dex-k8s-authenticator.

**Comment by anvddriesch** [comment]
Our plan is to make it obsolete through kubectl gs login.

**Comment by marians** [comment]
Update: k8s-dex-authenticator is mostly obsolete. `kubectl-gs login` provides all the means to log in to management clusters and for workload clusters, it provides a way to create a client certificate.

The only use case that dex-k8s-authenticator still fulfils is authenticating to a workload cluster via Dex (OIDC).
