### ISSUE TITLE
Use VPA/HPA for all apps

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#911]
Create VPA or HPA for all repos:

- [x] aws-admission-controller https://github.com/giantswarm/aws-admission-controller/pull/353
- [x] aws-collector https://github.com/giantswarm/aws-collector/pull/326
- [x] aws-ebs-csi-driver-app https://github.com/giantswarm/aws-ebs-csi-driver-app/pull/118
- [x] aws-efs-csi-driver https://github.com/giantswarm/aws-efs-csi-driver/pull/55
- [x] aws-node-termination-handler-app https://github.com/giantswarm/aws-node-termination-handler-app/pull/5
- [x] aws-operator
- [x] aws-pod-identity-webhook-app https://github.com/giantswarm/aws-pod-identity-webhook/pull/16
- [x] azure-ad-pod-identity-app
- [x] azure-admission-controller https://github.com/giantswarm/azure-admission-controller/pull/377
- [x] azure-cloud-controller-manager-app https://github.com/giantswarm/azure-cloud-controller-manager-app/pull/5
- [x] azure-cloud-node-manager-app https://github.com/giantswarm/azure-cloud-node-manager-app/pull/5
- [x] azure-collector https://github.com/giantswarm/azure-collector/pull/244
- [x] azure-operator https://github.com/giantswarm/azure-operator/pull/1644
- [x] azure-scheduled-events
- [x] azuredisk-csi https://github.com/giantswarm/azuredisk-csi-driver-app/pull/2
- [x] cluster-api-provider-azure-app https://github.com/giantswarm/cluster-api-provider-azure-app/pull/60
- [x] cluster-autoscaler-app
- [x] cluster-operator
- [x] etcd-backup-operator
- [x] etcd-kubernetes-resources-count-exporter https://github.com/giantswarm/etcd-kubernetes-resources-count-exporter/pull/16
- [x] event-exporter-app https://github.com/giantswarm/event-exporter-app/pull/103
- [x] k8s-audit-metrics https://github.com/giantswarm/k8s-audit-metrics/pull/111
- [x] k8s-dns-node-cache-app https://github.com/giantswarm/k8s-dns-node-cache-app/pull/6
- [x] kiam-app https://github.com/giantswarm/kiam-app/pull/115
- [x] kiam-watchdog https://github.com/giantswarm/kiam-watchdog/pull/31
- [ ] oms-agent-app WON'T DO
- [x] upgrade-schedule-operator https://github.com/giantswarm/upgrade-schedule-operator/pull/51

**Comment by alex-dabija** [comment]
Let's create a list with all the apps we want to consider for both AWS and Azure before making any changes.
