### ISSUE TITLE
[WC] Azure: use external cloud controller manager

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#913]
See https://github.com/giantswarm/giantswarm/issues/20965

And do the same for WCs

**Comment by whites11** [comment]
Blocked until https://github.com/giantswarm/giantswarm/issues/20965 is out and we're confident it works reliably

**Comment by T-Kukawka** [comment]
I guess it works just fine @whites11 ?

**Comment by whites11** [comment]
I didn't notice any big problems in MCs, yes

**Comment by whites11** [comment]
I wonder if we should have a ticket to do the same thing on AWS WCs as well @T-Kukawka

**Comment by T-Kukawka** [comment]
@whites11 i don't see a 'representation' of same stuff on AWS upstream

**Comment by whites11** [comment]
> @whites11 i don't see a 'representation' of same stuff on AWS upstream

what do you mean?

**Comment by whites11** [comment]
implemented in azure operator 6.0.0 that will be part of release 18.0.0
