### ISSUE TITLE
CAPI Release for CAPG

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#918]
Prepare CAPI release for CAPG using the new release mechanism.

## Tasks
- [ ] Create realease;
- [ ] Ensure clusters are deleted;

**Comment by calvix** [comment]
https://github.com/giantswarm/cluster-gcp

**Comment by alex-dabija** [comment]
This is done. We just have one other followup issue: https://github.com/giantswarm/roadmap/issues/1021 .
