### ISSUE TITLE
IP Whitelisting for API server in CAPO 

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#921]
### User Story 

- As a customer I want to use IP whitelisting on the Kubernetes API server so that I can be shure that only specified network ranges have access to it. 

### TODO
- [x] Create  upstream issue
- [ ] Implement whitelisting

**Comment by bavarianbidi** [comment]
Let's wait a few more days once we've got a response from the issue reporter (if he's still interested by implementing this change or if we could take over the implementation part)

**Comment by bavarianbidi** [comment]
will take care of the upstream implementation and added first thoughts into the upstream issue:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1045#issuecomment-1106488475

**Comment by gawertm** [comment]
@bavarianbidi is this done then?

**Comment by bavarianbidi** [comment]
> @bavarianbidi is this done then?

It's already implemented and merged but there isn't a CAPO release yet ( since months).

If we wouldn't create an own release we have to wait for upstream.
