### ISSUE TITLE
VPA not detecting OOM

### ISSUE THREAD

**Issue by whites11** [giantswarm/roadmap#923]
All of this started from a `ManagementClusterContainerIsRestartingTooFrequentlyAWS` for aws-operator 10.17.0 on `argali`.

The pods keeps getting killed over and over.

```
aws-operator-10-17-0-57d7795b7c-tmk9k                             0/1     CrashLoopBackOff   20         153m    100.64.181.112   ip-172-19-8-183.cn-north-1.compute.internal   <none>           <none>
```

This is NOT OOMing:

```
Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  Unhealthy    60m                   kubelet  Readiness probe failed: Get "http://100.64.181.112:8000/healthz": dial tcp 100.64.181.112:8000: connect: connection refused
  Warning  BackOff      49m (x110 over 140m)  kubelet  Back-off restarting failed container
  Warning  FailedMount  47m (x2 over 47m)     kubelet  MountVolume.SetUp failed for volume "aws-operator-configmap" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  47m (x2 over 47m)     kubelet  MountVolume.SetUp failed for volume "aws-operator-secret" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  47m (x3 over 47m)     kubelet  MountVolume.SetUp failed for volume "aws-operator-secret" : failed to sync secret cache: timed out waiting for the condition
  Warning  FailedMount  47m (x3 over 47m)     kubelet  MountVolume.SetUp failed for volume "aws-operator-configmap" : failed to sync configmap cache: timed out waiting for the condition
  Normal   Pulled       43m                   kubelet  Container image "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/aws-operator:10.17.0" already present on machine
  Normal   Created      43m                   kubelet  Created container aws-operator
  Normal   Started      43m                   kubelet  Started container aws-operator
  Warning  FailedMount  41m (x3 over 41m)     kubelet  MountVolume.SetUp failed for volume "aws-operator-configmap" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  41m (x3 over 41m)     kubelet  MountVolume.SetUp failed for volume "aws-operator-secret" : failed to sync secret cache: timed out waiting for the condition
  Warning  Unhealthy    30m                   kubelet  Liveness probe failed: Get "http://100.64.181.112:8000/healthz": read tcp 172.19.8.183:40052->100.64.181.112:8000: read: connection reset by peer
  Warning  Unhealthy    23m                   kubelet  Liveness probe failed: Get "http://100.64.181.112:8000/healthz": read tcp 172.19.8.183:56122->100.64.181.112:8000: read: connection reset by peer
  Normal   Pulled       23m (x3 over 36m)     kubelet  Container image "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/aws-operator:10.17.0" already present on machine
  Normal   Created      23m (x3 over 36m)     kubelet  Created container aws-operator
  Normal   Started      23m (x3 over 36m)     kubelet  Started container aws-operator
  Warning  Unhealthy    10m (x2 over 17m)     kubelet  Readiness probe failed: Get "http://100.64.181.112:8000/healthz": dial tcp 100.64.181.112:8000: connect: connection refused
  Warning  BackOff      63s (x29 over 30m)    kubelet  Back-off restarting failed container
```

```
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Fri, 18 Mar 2022 15:08:31 +0100
      Finished:     Fri, 18 Mar 2022 15:14:49 +0100
```

The pod is being terminated by the kernel because it reached the memory limit:

```
[702497.938003] Memory cgroup out of memory: Killed process 2492344 (aws-operator) total-vm:976220kB, anon-rss:238160kB, file-rss:38452kB, shmem-rss:0kB, UID:1000 pgtables:668kB oom_score_adj:997
[702497.948499] oom_reaper: reaped process 2492344 (aws-operator), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

But VPA does not detect that and thus does not scale up resources.

We suspect this is because of cgroups v2 https://github.com/kubernetes/kubernetes/issues/106331

Indeed we have the mentioned error message in the kubelet logs.

This affects all WCs > 17.0.0 and all MCs.

There seems to be an alternative implementation supporting v2 in k8s 1.22: https://kubernetes.io/blog/2021/11/26/qos-memory-resources/

**Comment by whites11** [comment]
Apparenty, we might have problems with cadvisor as well https://blog.kintone.io/entry/2022/03/08/170206

**Comment by whites11** [comment]
In general, cgroupsv2 seem to be an `alpha` feature in 1.22:

```
As an alpha feature, Kubernetes v1.22 can use the cgroups v2 API to control memory allocation and isolation. This feature is designed to improve workload and node availability when there is contention for memory resources.
```

took from https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md

**Comment by whites11** [comment]
VPA requires `events` with Reason `Evicted` to exists in order to detect a Pod OOming. There are none in k8s 1.21 when kernel kills the pod.

**Comment by whites11** [comment]
in anteater/deu01 (1.22.6 with cgroups v1) some pods are in `OOMKilled state` but still there are no events with `Reason` = `Evicted`

**Comment by whites11** [comment]
Testing on 16.1.2:

```
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Tue, 22 Mar 2022 16:19:18 +0100
      Finished:     Tue, 22 Mar 2022 16:20:59 +0100
```

but still no `Evicted` event. I wonder where it comes from at all...

**Comment by whites11** [comment]
Acccording to an old comment in an old issue in VPA repo (https://github.com/kubernetes/autoscaler/issues/1574#issuecomment-454129921):

Containers OOMKilled - we detect this as a change of pod status: https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/input/oom/observer.go#L151

VPA is actively checking for containers whose Terminated reason is `OOMKilled`:

```
if containerStatus.LastTerminationState.Terminated != nil &&
containerStatus.LastTerminationState.Terminated.Reason == "OOMKilled" {
```

so the Event is not important, but I need to understand why the kubelet does not mark the container as OOMKilled.

**Comment by whites11** [comment]
OK there is nothing we can do as far as I can tell.
Cgroups V2 support is what it is right now and there is no magic flag to make it work better than this.
The bottom line is: VPA is not able to detect OOMs and might end up lowering resources of pods to the point they can't work in an unrecoverable way (if not with manual intervention).

**Comment by whites11** [comment]
Started a thread in k8s' slack, https://kubernetes.slack.com/archives/C0BP8PW9G/p1647966113673229

it might be a bug in dockershim

**Comment by whites11** [comment]
This is docker itself not setting the `OOMKilled` properly: seems not to be a kubernetes problem.

```
$ docker inspect 412a73ed3f75
...
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            ...
```

**Comment by whites11** [comment]
Known containerd bug: https://github.com/containerd/containerd/pull/6323

**Comment by whites11** [comment]
containerd fix PR is merged

**Comment by alex-dabija** [comment]
Unfortunately, the fix didn't make it into `containerd v1.5.11`:
- https://github.com/containerd/containerd/commits/release/1.5
- https://github.com/containerd/containerd/tree/v1.5.11

Latest `Flatcar v3033.2.4` has `containerd v1.5.10`

This is blocked until there is a Flatcar release with `container v1.5.12`.

**Comment by whites11** [comment]
upstream fix released in containerd 1.6.3 1 week ago

**Comment by whites11** [comment]
Since flatcar is slow to release containerd, we decided to patch VPA and make it circumvent the bug.

**Comment by whites11** [comment]
Workaround is deployed on all MCs.
Still looking for a way to deploy on WCs without waiting for a new release

**Comment by whites11** [comment]
Alternatives I can think of for WCs:

- Bump the app's version in all involved releases. NO: releases are too old, not safe and against company rules.
- Make new platform releases for azure and AWS. OK, but will take time to be delivered everywhere
- Create a `user-override-apps` for every WC. Might be the best solution, but won't work for newly created clusters.

**Comment by whites11** [comment]
For WCs, we decided to just update the app in next releases and wait for clusters to be upgraded.
For now nothing else we can do, still waiting on flatcar for a proper fix

**Comment by whites11** [comment]
Still waiting on flatcar to ship containerd 1.5.12 or 1.6.3.

Current beta version is shipping 1.6.6

**Comment by whites11** [comment]
Flatcar 3227.2.0 released with fixed containerd

**Comment by whites11** [comment]
Blocked again as flatcar 3227.2.0 has broken networking

**Comment by T-Kukawka** [comment]
`3227.2.1` -  testing that release

**Comment by T-Kukawka** [comment]
v18 is with `3227.2.1`

**Comment by T-Kukawka** [comment]
We have `3227.2.1` now - Can we close this @whites11 ?

**Comment by whites11** [comment]
I guess so, yes
