### ISSUE TITLE
Support bastion updates

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#924]
OpenStackClusterTemplate.spec in https://github.com/giantswarm/cluster-openstack is immutable by default. According to comments of the upstream community, there is a way to update bastion configuration by disabling&re-enabling it. We need to verify it.

**Comment by cornelius-keller** [comment]
@kopiczko do we still need this issue with the current bastions on demand approach?

**Comment by erkanerol** [comment]
This is already implemented on upstream side. https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1298

**Comment by gawertm** [comment]
so we can close this issue @ericgraf ?

**Comment by erkanerol** [comment]
I think we should re-discuss whether we want to enable bastion by default or not.

**Comment by kopiczko** [comment]
I'd say let's enable them by default, that will make it easier to use `opsctl ssh` powers. If this is not what we want long term I'd change that later.
