### ISSUE TITLE
Show CGroups version of NodePools in the web UI

### ISSUE THREAD

**Issue by paurosello** [giantswarm/roadmap#935]
**Is your feature request related to a problem? Please describe.**
Customer would like an easy way to discover which CGroups version a nodepool is using (v1 or v2) as it could affect their workloads.

**Describe the solution you'd like**
In the nodepool list view, have a label or a way to identify cgroups version.

**Describe alternatives you've considered**
Coloring nodepools depending on version.

**Additional context**
[Public documentation of the feature](https://docs.giantswarm.io/advanced/forcing-cgroupsv1/)

**Comment by marians** [comment]
Does this show the right lookup logic?

```mermaid
graph TD
    A[cgroup version] --> B
    B{Flatcar version}
    B -->|below 3033.2.0| D[v1]
    B -->|3033.2.0 or newer| E
    E{Node pool annotation<br/>node.giantswarm.io/cgroupv1}
    E -->|present| D
    E -->|not present| F[v2]
```

**Comment by paurosello** [comment]
Yes, that is correct

**Comment by marians** [comment]
Discussed today in the SIG product sync.

- This could also help us nudge customers to bring node pools to cgroups v2.
- Only customers using the web UI with the Management API / SSO will benefit from this.

**Comment by PrashantR31** [comment]
We had a chat today in refinement and the notes are:
1. The "how to find" the CGroups version is explained in the diagram above.
2. Marian will provides a mock up for the UI

**Comment by marians** [comment]
### UI spec

- The cgroups column should appear to the right of `AVAILABILITY ZONES`
- The table column header should be `CGROUPS`
- For cgroups v1, the field content should be the `fa-warning` icon and the label `v1`. On mouse-over, the following text should be displayed in a tooltip:
  - This node pool uses the deprecated control groups version 1.
- For cgroups v1, the field content should be the label `v2`.

A mock-up should not be needed.

**Comment by JosephSalisbury** [comment]
Will be announced on Friday, can be specifically mentioned to adidas who requested it (even if they can't use it without SSO).
