### ISSUE TITLE
cut over from old alertmanager to new alertmanager for opsgenie and slack

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#936]
- [x] Announce that we are cutting over from old alertmanager to new alertmanager
- [x] cut a release for g8s-prometheus to stop sending to slack and opsgenie
- [x] cut a release for prometheus operator to start sending to slack and opsgenie

**Comment by TheoBrigitte** [comment]
New alertmanager is out and number of alert sound alright according to Opsgenie alert analytics dashboard

![image](https://user-images.githubusercontent.com/6536819/160400364-88bf7716-18e7-4da9-a18e-5fbed7e279e1.png)
[source](https://giantswarm.app.opsgenie.com/reports/main)
