### ISSUE TITLE
Upgrade dex to v2.31.1

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#941]
Dex [v2.31.1](https://github.com/dexidp/dex/releases/tag/v2.31.1) has been released recently, including some security fixes independencies.

**Comment by anvddriesch** [comment]
Let's also consider adding some debugging logs for the current refresh token problem: https://github.com/giantswarm/giantswarm/issues/21404

**Comment by anvddriesch** [comment]
The newest version is part of `v1.25.0`.
