### ISSUE TITLE
GCP DNS configuration

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#943]
## Story

_*-As a cluster admin, I want to access a cluster using DNS in order to simplify access.*_

## Implementation details
- one hosted zone for each customer (one time operation, manually configured on GCP);
- one public hosted zone per workload cluster, created automatically on GCP. Delegation needs to be configured for this zone in the customer hosted zone (NS records need to be created; @calvix can help);
- new DNS operator which leverages GCP DNS features:
- records to be created:
  * `kube-api` load balancer: `api.<cluster_name>.<customer_code>.gigantic.io` (it should point to the Kubernetes API loadbalancer);

Cluster Hosted zone pattern: `<cluster_name>.<customer_code>.gigantic.io`. Any cluster subdomain is going to be managed by the cluster hosted zone.

## Questions
- What happens if we have a customer using multiple providers? Where should the hosted zone be configured?
  * The customer's hosted zone will be created manually on AWS; Probably, the easiest would be to have multiple customer hosted zones, one for each cloud provider;
- Should we use UUIDs for cluster DNS?
  * More details on [Slack](https://gigantic.slack.com/archives/C01F7T2MNRL/p1648145021806839);
  * We'll use `cluster name` for now. We can change later to UUIDs;

## Current implementation for other providers:
- [CAPA](https://github.com/giantswarm/dns-operator-aws);
- [CAPZ](https://github.com/giantswarm/dns-operator-azure);
- [OpenStack](https://github.com/giantswarm/dns-operator-openstack).

## Followups:
- bastion DNS records;
- ingress DNS records;

**Comment by calvix** [comment]
`gtest.gigantic.io` is created delegated to GCP Cloud DNS

**Comment by mnitchev** [comment]
Operator can be found [here](https://github.com/giantswarm/dns-operator-gcp)
