### ISSUE TITLE
Vault secrets integration with Flux

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#947]
Customer request:

Management of Vault secrets in a GitOps context 
(= integration with Flux)

**Comment by gianfranco-l** [comment]
cc @MarcelMue if you want to add further context

**Comment by MarcelMue** [comment]
Especially if customer vault is available from our `management-cluster`.

**Comment by MarcelMue** [comment]
We did a little discussion / research during our team meeting:

The flux docs state that `vault` should be configurable as a secret backend and should therefor fully cover this usecase. We want to get to testing this when we have a usecase setup.

Docs: https://fluxcd.io/docs/guides/mozilla-sops/#encrypting-secrets-using-hashicorp-vault
