### ISSUE TITLE
Spec: Define format of storing test result data about compatibility

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#95]
## References
* Halo Apps Compatibility Testing Discussion [notes](https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#)

## What we need
1. We need test results which will help us debug if test fails
2. We need compatibility status of the test that was run: App vX comp. Platform vY Yes/No

Spec this out in cooperation with @giantswarm/team-batman

**Comment by piontec** [comment]
This will be a shared work between batman and halo. Please have a look at the first draft: https://www.dropbox.com/scl/fi/vo6a6x89k5vuediy91q43/Application-metadata-for-app-catalog-entries.paper?dl=0&rlkey=n1t51gtt2w4ae2exqzix2ddni.

**Comment by piontec** [comment]
Update 2020-03-20:
- I created a spec from scratch, while there was one already created; merged them, shared with both teams, waiting for feedback

**Comment by piontec** [comment]
Update 15-04-2020:

  * another round of talks and improvements, document updated

**Comment by cokiengchiara** [comment]
Done.
