### ISSUE TITLE
New networking for CAPI

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#954]
Let's start drawing an ideal network diagram for CAPI taking into account some of the discussions that are floating around

 * [x] https://github.com/giantswarm/roadmap/issues/864
 * [x] #955
 * [x] #956
 * [x] #957
 * [x] #958
 * [x] #959
 * [x] #960
 * [x] #961

Imo we should create a blueprint that can be used on all providers at least as a baseline.

Providers:
- [ ] [CAPA](https://github.com/giantswarm/roadmap/issues/1650);
- [ ] ...;

**Comment by teemow** [comment]
fyi @alex-dabija

**Comment by teemow** [comment]
@alex-dabija is this issue and all the sub issues obsolete?

**Comment by puja108** [comment]
@alex-dabija to clean up for Hydra

**Comment by alex-dabija** [comment]
I all the sub-issues because most of the functionality was implemented for CAPA, partially for CAPZ and CAPG is on-hold.
