### ISSUE TITLE
Ingress via a transit gateway with internal LBs

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#958]
Instead of placing our ELBs in a public subnet we need to create load balancers in a private subnet and then make sure that they are accessible via a transit gateway that is peered to the VPC. Afaik we already have an internal loadbalancer for the k8s api of a workload cluster. Can the ingress controller already be deployed into a private subnet?

* [x] #956 
* [x] #965

**Comment by paurosello** [comment]
Ingress can already be deployed with an internal load balancer, should not be an issue.

**Comment by alex-dabija** [comment]
Implemented and released.
