### ISSUE TITLE
Port the on-premises proxy implementation to AWS

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#962]
We've implemented proxy settings for on-premises installations. Is this portable to AWS?

**Comment by glitchcrab** [comment]
Some of the details are slightly hazy, but I'll summarise what I can remember.

### Proxy config

For any deployments which needed to reach out to the internet, we used Kyverno to patch the deployment with `HTTP_PROXY`/`http_proxy`/`HTTPS_PROXY`/`https_proxy` env vars. Any hostnames which needed to stay internal were then added to the `no_proxy` env var with Kyverno. This list was fairly long as all in-cluster hostnames also needed to be added to this list.

### DNS config

Depending on how locked down the installation would be, we also needed to proxy some DNS requests too (customer DNS requests needed to stay internal). This was accomplished by way of a custom `dnsmasq` config running on the bootstrap node which used different upstreams depending on the name being requested. To get external requests out of the environment we set the upstream to a local instance of `cloudflared` which then tunneled the DNS traffic over HTTPS via the proxy.

Some more info here https://github.com/giantswarm/giantswarm/issues/16873

**Comment by alex-dabija** [comment]
Implemented and released.
