### ISSUE TITLE
Visibility regarding how to access the Management API

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#968]
As a user of the Management API, I want to know

- Do I have to use `--internal-api` with `kubectl gs login`, or can I use the external API endpoint?
- Do I have to be in a certain network or VPN?

This information is currently hidden in installation configuration, and provider specific. This creates uncertainty, failure, and causes support efforts.

Where could we make this info available to the web UI, so that we can adapt Management API guides and the Getting Started guide accordingly?

**Comment by marians** [comment]
@PrashantR31 This requires talking with Phoenix and Rocket.

**Comment by PrashantR31** [comment]
Hi @alex-dabija and @cornelius-keller , can you please give bring this ticket to your team and the details for above requirements for accessing the Management API, which would make our support to customers easier.

**Comment by alex-dabija** [comment]
I'll discuss it next week with Phoenix.

**Comment by marians** [comment]
Some ideas from refinement

- Could `kubectl gs login` detect the error that usually occurs when the internal API endpoint must be used but hasn't been used? In that case we could present a useful error like `Please try --internal-api`...
- Could Athena offer the "is network restricted" info for an installation? This way it would be accessible to all clients. Athena has to be publicly accessible then.

Questions

- What's the source of truth? How can we determine whether the use of the internal API endpoint is required? (Marian to find Vaclav's Slack explanations, also probably goes out to Phoenix and Rocket for the CAPI generation.)

User stories

- As a web UI user without access to the Management API, I want to learn that I have to use a VPN or certain network in order to get full access to it.
- As an admin with access to the Management API, I want to find full information regarding network requirements (in the web UI) which I can pass on to other users to support them.
- As a user, I want `kubectl gs login` commands presented in the web UI to contain the `--internal-api` flag if it's required for accessing the Management API. (AWS only, only for selected customers)

**Comment by marians** [comment]
I found the Slack thread: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1648047425940829

**Comment by weatherhog** [comment]
closing this issue
