### ISSUE TITLE
Research: how to run helm from CI/CD and record the results?

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#97]
## References
* Halo Apps Compatibility Testing Discussion [notes](https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#)

Outcome: ready to plug-in solution for running from CI/CD

Research: how to run helm from CI/CD and record the results?

**Comment by cokiengchiara** [comment]
duplicate.

**Comment by cokiengchiara** [comment]
fake dupe

**Comment by cokiengchiara** [comment]
@piontec will give update on this.

**Comment by piontec** [comment]
In my tests, I leave running helm to `chart-operator` by creating the `App` CR. I believe that we should always deploy like this in testing.

**Comment by cokiengchiara** [comment]
Closing as the research is done. Capturing findings here. https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#
