### ISSUE TITLE
Update CR owner references and infrastructure references to use the latest CAPI CRs

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#974]
Update CR owner references and infrastructure references to use the latest CAPI CRs.

TODOs:
- [ ] which customers use gitops? ( @alex-dabija )
- [ ] which customers mange CRs on their own? ( @alex-dabija )
- [ ] ...;

Which CRs?
- on AWS: Cluster, MachineDeployment;
- on Azure: Cluster, AzureCluster, AzureMachine, MachinePool, AzureMachinePool;

**Comment by T-Kukawka** [comment]
This is handled in the cluster-app, so it will be replaced when the app is upgraded or version removed. No need for separate ticket as this will come out 'naturally'
