### ISSUE TITLE
`aws-operator` is restarting too often on `argali`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#976]
`aws-operator` is restarting too often on `argali`.

**Comment by whites11** [comment]
not even one restart happening

```
$ kubectl --context=gs-argali-clientcert -n giantswarm get po | grep aws-operator
aws-operator-10-14-1-ff46f6977-pjcvq                              1/1     Running     0          2d15h
aws-operator-10-17-0-6654fb4bf6-ggxgv                             1/1     Running     0          3h33m
aws-operator-10-18-0-6f4c6ccbc5-pqsdg                             1/1     Running     0          2d15h
```

**Comment by whites11** [comment]
According to Nick (last person paged by this) it was a problem with VPA not being enabled.
Resource limits were too low and pod was OOming.
Nick fixed VPA settings to make resources fixed accordingly and now situation is stable.
@AverageMarcus please let me know if you get paged by this, thank you
