### ISSUE TITLE
Investigate AWS ETCD Backup issues

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#979]
Investigate AWS ETCD Backup issues.

## Background
Some resources in a Cloud Formation stack get deleted and ends up causing issues:
- `prometheus` can't scrape;
- `etcd` backups fail;

**Comment by whites11** [comment]
Idea: create a new tiny operator that reconciles the `Cluster` CR (with release label < 20.0.0-alpha1) and:

- looks up a cloud formation stack with the right name in status "Created".
- checks if the number of resources in the CF stack definition and the actual resources match
- deletes the CF stack if they don't.

**Comment by whites11** [comment]
Waiting for problem to happen aagain

**Comment by whites11** [comment]
Deployed everywhere
