### ISSUE TITLE
Research: python testing libs/frameworks

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#98]
## References
* Halo Apps Compatibility Testing Discussion [notes](https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#)

Outcome: ready CI/CD configuration with installed dependencies and commands prepared to execute the tests

Research: figure out which python testing libs/frameworks will be the most useful for us and should be available by default during testing.

**Comment by cokiengchiara** [comment]
@piontec will update this ticket.

**Comment by piontec** [comment]
I will try to add a "application testing" page to our docs soon.

**Comment by piontec** [comment]
@webwurst anything I missed and you find worth adding?

**Comment by cokiengchiara** [comment]
Closing as research is done. Captured research findings here: https://docs.google.com/document/d/1V48XGRxFRP9qQWGkMgKMuat6fwdWYpjYgjStKjC3dkw/edit#
