### ISSUE TITLE
Improvements for the Kubernetes Proxy dashboard

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#989]
I'd like us to apply our [UX guidelines for dashboards](https://intranet.giantswarm.io/docs/product/ux/guidelines/dashboards/) to the new **Kubernetes/Proxy** dashboard. Especially:

- Set the time zone to UTC
- Use the Time series panel type instead of Graph
- Set a short default time windows to allow for fast initial loading
- Explain panels by using the panel descriptions
- Adjust units to fit the dat semantically (CPU usage)

Additionally, there are two panels not showing data (in one installation):

- Post Request Latency 99th Quantile
- Get Request Latency 99th Quantile

Metadata

- The dashboard should have a team label to indicate ownership

**Comment by marians** [comment]
@weatherhog Is it correct to assign this to Atlas?

**Comment by JosephSalisbury** [comment]
ideally, whichever team owns the kubernetes/proxy dashboard should take care of these issues

**Comment by marians** [comment]
@pipo02mix I learned that you added the dashboard. Which team has ownership?

**Comment by pipo02mix** [comment]
which team owns the kube-proxy component? kass and onprem or cabbage?

Anyway you can assign this to me. I added the dashboard from upstream and I am happy to fulfill with the guidelines

**Comment by marians** [comment]
@JosephSalisbury Help us please. Does cabbage own kube-proxy?

**Comment by weatherhog** [comment]
@marians kube-proxy is owned by the kaas teams. So this should go the rocket and phoenix

**Comment by pipo02mix** [comment]
PR is up ⏫

**Comment by pipo02mix** [comment]
done
