### ISSUE TITLE
CAPA Flatcar

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#996]
## User Story

_*-As a cluster admin, I want to use Flatcar as the operating system on all Cluster API cluster nodes in order to have a container oriented operating system with all the hardening and settings of the current Giant Swarm clusters.*_

Towards [epic](https://github.com/giantswarm/roadmap/issues/1995).

## Background

Cluster API for AWS (CAPA) clusters use the default Ubuntu image.

**Comment by calvix** [comment]
testing PRs:
https://github.com/giantswarm/cluster-aws/pull/49
https://github.com/giantswarm/cluster-api-provider-aws-app/pull/106
https://github.com/giantswarm/cluster-api-app/pull/54

**Comment by calvix** [comment]
first bump on the road - https://github.com/kubernetes-sigs/cluster-api/issues/6403
Seems like base64 encoding is properly supported for files in `kubeadmconfig`

**Comment by calvix** [comment]
so everything tested, flatcar is running on all nodes including bastion, ssh works as well, I will keep the branch for `cluster-aws`  until we will have a new version fo CAPI and CAPA controllers which support this flatcar release, we need to wait until the new releases ar mode aupstream

**Comment by AndiDog** [comment]
If our dependency is mostly on the dynamic CloudFront domain, we could use a fixed alias domain instead. I think that's a feature of `irsa-operator` already. Then we don't have to wait on the secret to read the domain, but make an assumption.

**Comment by alex-dabija** [comment]
Blocked by https://github.com/giantswarm/roadmap/issues/2420.

**Comment by calvix** [comment]
Before merging we need to update IAM role for all existing MCs to include new S3 bucket permissions

**Comment by calvix** [comment]
Done, PR merged, release created and the permissions were updated
