### ISSUE TITLE
Discovery:  CAPI Add-on Management

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#997]
Add-on management to manage apps based on the lifecycle of the clusters.

cc @MarcelMue since you were involved in the related Slack conversation

**Comment by MarcelMue** [comment]
Related link: https://gigantic.slack.com/archives/C2MS2VB37/p1649138198506369

**Comment by MarcelMue** [comment]
Upstream issue: https://github.com/kubernetes-sigs/cluster-api/issues/6374

**Comment by weatherhog** [comment]
closing this issue as this is not relevant anymore
